### PR TITLE
oobmigration: Fix off by one error

### PR DESCRIPTION
**Pull request by efritz**
Ensure that if you're upgrading to an exact version at which point an oobmigration is deprecated, we include that version.

## Test plan

Existing unit tests.

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
me stamping this PR

image

**Comment by efritz** [comment]
@rvantonder It's basically `(to < candidate)` -> `!(to > candidate)` = `(to <= candidate)` to make sure we include the upper bound.

**Comment by rvantonder** [comment]
no need to explain it, I'm just here to approve things.

**Comment by efritz** [comment]
oh good

**Pull request merged**
