### PR TITLE
Wildcard [Charts]: Add tail element to the chart tooltip UI

### PR DESCRIPTION
**Pull request by vovakulikov**
## Background

Prior to this PR we rendered tooltip (for example for line chart) without any tail element, and this makes it difficult to understand to which element this tooltip is related (when we move cursor over the chart, or focus point element with keyboard) 

In this PR we simply add tail element to the popover to make it easy to determine the element to which tooltip is related. See before/after demo recordings. 

| Before | After |
| -------- | -------- |
| <video src="https://user-images.githubusercontent.com/18492575/202858887-e3753a3a-fce1-4748-9b8f-e2253ebbeb49.mov" />| <video src="https://user-images.githubusercontent.com/18492575/202858883-90f0c6ac-65fa-4da4-a4cc-588ed0825909.mov" />|

## Test plan
- Check line chart and make sure that tooltip element and its tail UI look good for all points on the chart 

## App preview:

- [Web](https://sg-web-vk-add-chart-tooltip-tail-ui.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.34 kb) | 0.00% (+0.34 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vk/add-chart-tooltip-tail-ui/compare-report.html;tab=live_object) for a full comparison between the commits a5e1614 and 57ebf1a or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by AlicjaSuska — CHANGES_REQUESTED** [review]
Thank you for taking this on @vovakulikov. Couple thoughts:
- I think that tooltip shouldn't follow the cursor. It works against the goal of making user aware of what the tooltip is about. We should always keep the tooltip pointed at the data point as it is currently done for keyboard navigation.
- I would suggest to keep the tooltip a little closer to the point (half of the currently implemented distance). It's just a small visual correction.

**Comment by vovakulikov** [comment]
@AlicjaSuska thanks for your review. I agree with your points. I was a bit afraid that sticky tooltip will interrupt interactions from user's cursor but I played with it and it feels natural. It should be available on the web preview (when you will see this message) 

Here is a quick video how it works after I changed the tooltip positioning logic  

https://user-images.githubusercontent.com/18492575/203427594-f61b98d4-c0b5-4eb9-8f6b-7d1e2a9fe8c1.mov

**Review by AlicjaSuska — APPROVED** [review]
Thank you for making those changes @vovakulikov! It works way better than the first version :)

(as I mentioned on slack, I asked for a quick review from Quinn K. - he's in alignment with this direction)

**Review by philipp-spiess — APPROVED** [review]

**Pull request merged**
