### PR TITLE
sg: make grafana restart on changes to ./monitoring

### PR DESCRIPTION
**Pull request by Strum355**
image

### CODE REVIEW

**Review by bobheadxi — COMMENTED** [review]
FYI the "right" way top do this is `RELOAD=true` on the monitoring generator: https://docs.sourcegraph.com/dev/how-to/monitoring_local_dev#using-the-monitoring-generator , this will hit the Grafana API to reload dashboards without restarting the whole thing

**Comment by bobheadxi** [comment]
I was trying to hack on getting something like the monitoring generator - a service that just runs once, exits, and should be re-run again went watching files - to work, but I got a bit stuck and haven't had the chance to circle back to it yet: https://github.com/sourcegraph/sourcegraph/tree/sg/monitoring-generator-and-continue

**Comment by Strum355** [comment]
Ah good to know the right way :slightly_smiling_face: Ill work on using that instead tomorrow :+1:

**Comment by Strum355** [comment]
Superseded by #23895

**Pull request closed without merging**
