### PR TITLE
nogo: add gocritic

### PR DESCRIPTION
**Pull request by burmudar**
Add gocritic from https://sourcegraph.com/github.com/go-critic/go-critic

### Why do we have our own analyzer run implemention
We cannot use the analyzer exported by the `checkers/analyzer` package directly since it doesn't allow us to specify which linters we want to disable

### Test plan
* `bazel build //cmd/`  - disabled linters aren't reported issues
* printed out the linters that will be enabled and disabled
```
l = appendAssign ❌
l = appendCombine ✅
l = badCond ✅
l = badRegexp ✅
l = boolExprSimplify ✅
l = builtinShadow ✅
l = builtinShadowDecl ✅
l = captLocal ✅
l = caseOrder ✅
l = codegenComment ✅
l = commentFormatting ❌
l = commentedOutCode ✅
l = commentedOutImport ✅
l = defaultCaseOrder ✅
l = deferInLoop ✅
l = deprecatedComment ❌
l = docStub ✅
l = dupBranchBody ✅
l = dupCase ✅
l = dupImport ✅
l = dupSubExpr ✅
l = elseif ✅
l = emptyFallthrough ✅
l = evalOrder ✅
l = exitAfterDefer ❌
l = filepathJoin ✅
l = flagName ✅
l = hexLiteral ✅
l = hugeParam ✅
l = ifElseChain ❌
l = importShadow ✅
l = initClause ✅
l = mapKey ✅
l = methodExprCall ✅
l = nestingReduce ✅
l = newDeref ✅
l = nilValReturn ✅
l = octalLiteral ✅
l = paramTypeCombine ✅
l = ptrToRefParam ✅
l = rangeExprCopy ✅
l = rangeValCopy ✅
l = regexpPattern ✅
l = regexpSimplify ✅
l = ruleguard ✅
l = singleCaseSwitch ❌
l = sloppyReassign ✅
l = sloppyTypeAssert ✅
l = sortSlice ✅
l = sqlQuery ✅
l = todoCommentWithoutDetail ✅
l = tooManyResultsChecker ✅
l = truncateCmp ✅
l = typeAssertChain ✅
l = typeDefFirst ✅
l = typeSwitchVar ✅
l = typeUnparen ✅
l = underef ✅
l = unlabelStmt ✅
l = unlambda ✅
l = unnamedResult ✅
l = unnecessaryBlock ✅
l = unnecessaryDefer ✅
l = weakCond ✅
l = whyNoLint ✅

```

### CODE REVIEW

**Comment by jhchabran** [comment]
@burmudar I'm going to merge the PR that update the buildfiles, could you rebase against main once it's done before we merge this?

**Comment by burmudar** [comment]
> @burmudar I'm going to merge the PR that update the buildfiles, could you rebase against main once it's done before we merge this?

10000%

**Comment by burmudar** [comment]
Tested this now again after all the updates
```
INFO: Elapsed time: 1884.674s, Critical Path: 364.93s
INFO: 28196 processes: 3160 remote cache hit, 14538 internal, 3146 darwin-sandbox, 7352 local.
INFO: Build completed successfully, 28196 total actions
```

**Review by sanderginn — APPROVED** [review]
i'm just here with wet ink

**Pull request merged**
