### PR TITLE
ci: refactor foreach-ts-project to run in parallel

### PR DESCRIPTION
**Pull request by ggilmore**
This changes dev/foreach-ts-project.sh to run the commands it's given in parallel instead of sequentially. This seems to save ~1 minute for the build steps that use it (eslint, stylelint)

### CODE REVIEW

**Comment by ggilmore** [comment]
> What I don't like about this is that this means `parallel` needs to be installed on every dev machine, because this shell script is used in scripts for local dev too

This is already the case since our docker build scripts also use `parallel`. I think it's fine since parallel is a standard GNU utility that's easily installable on pretty much anything.

**Comment by felixfbecker** [comment]
I don't run the Docker build script in local dev though. But I run `yarn all:eslint` all the time

**Comment by ggilmore** [comment]
GNU parallel is easily installed through homebrew and all package major repositories (without adding any 3rd party ones).

Do you have some other npm package that you'd prefer to use instead?

**Comment by felixfbecker** [comment]
It would need to be added to the dev docs (getting started guide). And I couldn't find a version for Windows, so our scripts would not work there anymore (we had some PRs from contributors in the past to fix scripts on Windows, which is why we use `cross-env` for example). One tool I used in the past is `concurrently` from npm. Or we can decide it is not an issue, which I am fine with too (but it should still be documented).

**Comment by ggilmore** [comment]
@felixfbecker https://github.com/sourcegraph/sourcegraph/pull/7107/commits/e223d725b0d9a445a3eff5c797b00e8346a73286

**Pull request merged**
