### PR TITLE
code monitoring: logs can be expanded

### PR DESCRIPTION
**Pull request by limitedmage**
Create the UI inside the expanded code monitoring logs. See storybook for fully interactive example.

image

Part of #27168

## Test plan

- Storybook tests
- Manual testing

### CODE REVIEW

**Review by benvenker — APPROVED** [review]
Looks great, excited for this!

**Review by novoselrok — APPROVED** [review]

**Review by marisak — CHANGES_REQUESTED** [review]
Thanks for your patience, this looks great! I've got a couple visual things that extend some conversations we've had before. I looked at this PR on both [Chromatic](https://5f0f381c0e50750022dc6bf7-hbydmkqqkh.chromatic.com/?path=/story/web-enterprise-code-monitoring-codemonitoringlogs--default) and on local. 
- Skipped actions looks good, thanks for adding that! 
- Continuing our conversation around what to do with the space left by the absence of a top-level error icon, I've put together some options in [Figma](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1865%3A13899). I think using the grey checkmark icon could be good (2nd option), but I'm also okay with removing the extra space (3rd option). 
- It would probably be easier to align the "monitor name" header with the actual monitor names in either of those cases. 
- This also may relate to something I noticed in local but not on Chromatic, when the top level item is opened on local, the code monitor name "jumps" to the right about 8px. 
- Also on the topic of the top level of the logs table, would it make sense to move the "Monitor details" link to the top level? ([Figma](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1865%3A14216)) This would keep it hierarchically above the runs, while also making it clearer that the second level only contains runs. 
- I noticed a difference in font weights between Chromatic and local. On Chromatic, the top level (code monitor name and last run) are regular weight, while the runs on the second level are medium. On local it appears to be the reverse. From a text hierarchy perspective, I think it would make sense for the name of the code monitor to be medium/500 weight while the runs are regular/400. I can update this in the designs once we decide! ([Figma](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1865%3A14392))

**Comment by limitedmage** [comment]
@marisak Thanks for the thorough review! I'll make the changes. I think we can try going with the "gray checkbox" icon to start and we can remove it later if it feels off.

> This also may relate to something I noticed in local but not on Chromatic, when the top level item is opened on local, the code monitor name "jumps" to the right about 8px.

Is this because of the scrollbar appearing/disappearing as the page changes height when expanding?

> I noticed a difference in font weights between Chromatic and local. 

Hmm it's possible we don't have the same global styles on Chromatic than we do on the webapp. Would you mind attaching some screenshots? I can work with other frontend devs to fix this. Seems like a bad issue to have when testing design implementations.

**Comment by limitedmage** [comment]
@marisak I updated the PR to address the following issues:
- Added checkmark icon (also added tooltip for both the checkmark and error icon in the top level)
- Aligned "Monitor name" header to the monitor name, not the icon
- Fixed bottom spacing that was causing the loading spinner to not be centered and the table to have extra space at the bottom
- Moved monitor details link to be right of the monitor name, not inside the collapsible panel

Haven't addressed the font-weight issue yet; currently all the collapsible headers should have font-weight of 500 since they are buttons. If you think this should be modified, let me know and I can make that change.

**Review by marisak — APPROVED** [review]
This looks great, I'm so excited! I checked both local and Storybook, thanks for telling me how to see the latest Chromatic snapshot. 
- Alignment of everything looks great now! 
- I'm still seeing the slight "jump" when opening a top-level item on local. I will attempt to attach a video, and barring that, I will send it on Slack. This only happens on local, not Chromatic, though it doesn't seem to be caused by a scroll bar. 
- r.e. font weight in monitor rows: Ideally just the code monitor name would be 500 and the link to monitor/timestamp would be 400 (though it looks like timestamp is already 400). I appreciate that you made the rows into buttons, is that what makes the whole row clickable to expand/collapse?

**Comment by limitedmage** [comment]
@marisak  Thanks! I was finally able to catch the "jump" issue and it should be fixed, along with the font weight for the details link.

**Pull request merged**
