### PR TITLE
Cody: Fix chat view button

### PR DESCRIPTION
**Pull request by deepak2431**
This PR is for issue #52359.

## Test plan
I tested it manually, and it works fine. 

https://github.com/sourcegraph/sourcegraph/assets/44617923/acd0d1d5-3c56-4c43-9a5a-996ae69fbe78

### CODE REVIEW

**Comment by mrnugget** [comment]
Thank you! Since we now have e2e tests 

* How to r un them: https://github.com/sourcegraph/sourcegraph/blob/686a16d5b2580c36aa660200cb50eb32e8bd8022/client/cody/package.json#L62
* Example: https://github.com/sourcegraph/sourcegraph/blob/686a16d5b2580c36aa660200cb50eb32e8bd8022/client/cody/test/e2e/auth.test.ts#L7-L25

... I'm wondering: could you add an e2e test for this, just to make sure that if a user clicks from chat to recipes/history and on "start new chat" that they see the chat again?

**Comment by philipp-spiess** [comment]
@deepak2431 E2E tests would be awesome! There are also some hints in #52337. Would also love to hear what you think about the setup 🙂

**Comment by deepak2431** [comment]
> Thank you! Since we now have e2e tests
> 
> * How to r un them: https://github.com/sourcegraph/sourcegraph/blob/686a16d5b2580c36aa660200cb50eb32e8bd8022/client/cody/package.json#L62
> * Example: https://github.com/sourcegraph/sourcegraph/blob/686a16d5b2580c36aa660200cb50eb32e8bd8022/client/cody/test/e2e/auth.test.ts#L7-L25
> 
> ... I'm wondering: could you add an e2e test for this, just to make sure that if a user clicks from chat to recipes/history and on "start new chat" that they see the chat again?

@mrnugget Thanks for the review, I have added the tests for it.

**Comment by deepak2431** [comment]
> @deepak2431 E2E tests would be awesome! There are also some hints in #52337. Would also love to hear what you think about the setup 🙂

@philipp-spiess Thanks for sharing the reference, the instructions added in the Readme were useful. Not that difficult to set up. Just ran the ` pnpm:install` the same way from the root, and the test command wrote by beatrix under the client Cody.

**Comment by philipp-spiess** [comment]
@deepak2431 YOU ARE A MACHINE 💥 

Do you mind adding a new test file for this though? The authentication one is already getting pretty long and ideally we would conceptually split it into something more meaningful to what we're testing here (how about, say, `history.test.ts`?

**Comment by deepak2431** [comment]
> file

@philipp-spiess Yup, I will add it in a new file. I was thinking of this while writing tests as it doesn't relate to auth test, but yeah, let me do it now.

**Comment by deepak2431** [comment]
@philipp-spiess I have migrated the tests to a new file. Though, I think the implementation requires some cleanup at the end after a test run is completed. While running the test, I got this error a few times, and for some, it was successful.

iScreen Shoter - Code - 230525164952
iScreen Shoter - Code - 230525165024

If you see the first image, it says PORT is already in use and fails the other tests. While for the next, it ran successfully and passed both of them.

**Comment by philipp-spiess** [comment]
@deepak2431 Yeah we noticed this on @abeatrix's PR too. It's fixed via this change here: https://github.com/sourcegraph/sourcegraph/pull/52337/files#diff-ad35ce5eda208ff4565c382717dbe24e84077562549a981e471c92905eacb6c1R4

**Comment by philipp-spiess** [comment]
@deepak2431 Hey! Sorry for the long waits but I’m the opposite of free at the moment I’m afraid 😢 I can make sure to assign the cody reviewers to your other PRs though.

**Comment by deepak2431** [comment]
> @deepak2431 Hey! Sorry for the long waits but I’m the opposite of free at the moment I’m afraid 😢 I can make sure to assign the cody reviewers to your other PRs though.

No problem @philipp-spiess. Thanks a lot for tagging other reviewers, it's of great help.

**Review by philipp-spiess — APPROVED** [review]

**Pull request merged**
