### PR TITLE
Only redact URLs on Sourcegraph.com for paths that start with /github…

### PR DESCRIPTION
**Pull request by dadlerj**
….com, /gitlab.com, and /search, as we only provide private code browsing on Sourcegraph.com from GitHub.com and GitLab.com.

Related: https://github.com/sourcegraph/sourcegraph/pull/37581/files#commit-suggestions

## Test plan

All edited files are already covered by unit tests. There are no UI effects of this PR, so no storybook/e2e/integration tests should be required. 

My changes include updates to all relevant unit tests and an addition of a new test.

### CODE REVIEW

**Comment by unknwon** [comment]
> Sorry for tagging you, @unknwon , but I'm not sure who else would be able to review this and GitHub recommended you! If you can think of anyone on the frontend side, please let me know. I'd love eyes from eng team members on both TS and Go code if possible.

Haha, no problem at all! Also requested review to @eseliger for the TS part.

**Review by unknwon — APPROVED** [review]
I think both the TS and Go should work based on my limited TS knowledge.

**Comment by dadlerj** [comment]
Thanks @eseliger, and no worries, I noticed on Slack. I'm lost when it comes to our CI these days though—can I merge with the `sync-tracking-issues` failure, the `buildkite/sourcegraph-async` (storybook) failure, and the `pr-auditor` (no test plan) failure?

**Comment by dadlerj** [comment]
Also, even if it was ready to go, I don't have rights to merge it 🤦 . If it is ready, could one of you do that for me @unknwon @eseliger ?

**Comment by eseliger** [comment]
You need to fill in a test plan in the PR description below the ##test plan, that should make the last required check green and allow us to merge it (I currently also cannot merge it since a required check is failing).

**Pull request merged**
