### PR TITLE
http: set samesite cookie attribute to value none

### PR DESCRIPTION
**Pull request by uwedeportivo**
Related to https://github.com/sourcegraph/sourcegraph/issues/6167

When a local instance installs an extension it talks to a remote registry (for example sourcegraph.com).  With the change in browser behavior regarding the SameSite cookie attribute (nicely described here: https://www.troyhunt.com/promiscuous-cookies-and-their-impending-death-via-the-samesite-policy/) the session cookies from sourcegraph.com won't be sent to sourcegraph.com by the browser during the extension installation flow on the local instance. This is ok, the extension still installs (it gets the bundle). The only downside is the message in the console (as far as I can tell).

This PR sets the attribute value explicitly instead of relying on default value and behavior.  The assumption is that having explicit value will get rid of the message in the console. I haven't been able to confirm that yet, still setting up my test.

We could go with value Strict or Lax (see https://web.dev/samesite-cookies-explained/). Lax is the new default when attribute is not explicitly set (it used to be None before Chrome 80).

### CODE REVIEW

**Comment by uwedeportivo** [comment]
for testing i was thinking of temporarily  turning on https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/1996

**Comment by felixfbecker** [comment]
One thing I can think of this could affect: Did you test that the native integrations (Gitlab etc) still send the auth cookies to the private instance or sourcegraph.com?

**Comment by uwedeportivo** [comment]
@felixfbecker good point. thanks for thinking of that. this is what i'm looking for. i'm asking the hive mind what this would break (hence the long list of reviewers). and no, haven't tested the native integrations yet.

fun fact: during testing saw the console messages about this with google's own services, mostly google drive.

**Comment by tsenart** [comment]
> for testing i was thinking of temporarily turning on sourcegraph/deploy-sourcegraph-dot-com#1996

Can you elaborate on your test plan for this?

> We could go with value Strict or Lax 

What are the implications of each choice for us? Another question: Does this affect authentication with Grafana as an admin?

**Comment by uwedeportivo** [comment]
@felixfbecker you were right: i ran a local sourcegraph connected with native integration to a local gitlab and Chrome 80 doesn't send the cookies. as a matter of fact we need to actually explicitly set the SameSite attribute value to None to restore the behavior we had before Chrome 80. @slimsag this means the CSRF angle is back and we should keep CSRF protection outside of SameSite

**Comment by uwedeportivo** [comment]
so i'm doing a 180 on this: explicitly setting it to SameSite=None

**Comment by uwedeportivo** [comment]
> Can you elaborate on your test plan for this?

I ran a local gitlab and local sourcegraph to test the native integration (https://github.com/sourcegraph/about/pull/567)

> What are the implications of each choice for us? Another question: Does this affect authentication with > Grafana as an admin?

Nothing changes for Grafana. Unfortunately until we re-engineer some CSRF stuff you still need to port-forward and talk to Grafana directly (as opposed to through the reverse-proxy in the frontend) if you want to make changes (to panels and dashboard). for viewing we're fine either, this PR won't affect it

**Pull request merged**
