### PR TITLE
db: rename gitserver_localclone_jobs to gitserver_relocator_jobs

### PR DESCRIPTION
**Pull request by asdine**
This renames the `gitserver_localclone_jobs` table and `gitserver_localclone_jobs_with_repo_name` view to `gitserver_relocator_jobs` and `gitserver_relocator_jobs_with_repo_name`.

This is done after the [discussion](https://github.com/sourcegraph/sourcegraph/pull/33072#issuecomment-1082725270) about renaming the GitserverLocalClone worker to GitserverReplicator worker.

The table is not used yet so it's safe to just drop it instead of renaming it:
- so that we can fix the order of columns
- so we don't have to rename constraints too
- start fresh basically

## Test plan

sg migration up and undo

Related to #32827

### CODE REVIEW

**Comment by ryanslade** [comment]
Don't want to be too pedantic but technically it's not replicating repos since we still only support one copy per repo. Maybe `gitserver_rebalancer_jobs`?

**Comment by asdine** [comment]
I liked "replicator" because that component's job was to copy repos from one instance to another. In that context, technically it "replicates" a repo (with an option to remove it from the source). The issue with the word replicate though is that it clashes with replication in general which is a higher level concept.
If we ever support replication, this component will be the central piece, but if we don't this naming will be misleading.

I don't think "rebalancer" works either because all this component does is just copy stuff around. Maybe another synonym of copy?

**Comment by sashaostrikov** [comment]
> Maybe another synonym of copy?

Relocator

**Comment by asdine** [comment]
img

**Review by ryanslade — APPROVED** [review]

**Pull request merged**
