### PR TITLE
all: remove underscore in test function names

### PR DESCRIPTION
**Pull request by rvantonder**
As in title. I added underscores to my tests because I've seen it in other places, and I realize this is a Go convention for some projects, but should not necessarily be for ours. I tend to agree with @keegancsmith:

>  I think its pretty rare in our codebase and I am not sure I am a fan of it.

For consistency I'm putting up this PR to remove underscores throughout.

If these seem overzealous, LMK.

### CODE REVIEW

**Comment by uwedeportivo** [comment]
is this a campaign :-) ?

**Comment by rvantonder** [comment]
> is this a campaign :-) ?

Almost :-) I would use our campaign feature but want attribution to my GH, not the sourcegraph bot account.

I was experimenting with regex and comby with a combination of

`comby 'func Test_:[x~[A-Z0-9]]' 'func Test:[x]' test.go` and manual review
`comby 'func Test_:[x~[a-z]]' 'func Test:[x]' test.go -review ` and others

...because I don't have first class support for uppercasing or calling out to other scripts to do the upper casing (I should add that :P)

**Comment by unknwon** [comment]
I have objection to naively removes all underscores :)

There are two use cases top off my head for reasons why I think underscores are good:
1. A test case for private function, `Test_checkEmailAbuse` has exact name match with `checkEmailAbuse`, where `TestCheckEmailAbuse` does not. Also `Test_checkEmailAbuse` is clear that we're testing for a private method.
2. A test case for a method, `TestStruct_Method` is more clear than `TestStructMethod` especially when both struct and method name are not short.

**Comment by rvantonder** [comment]
@unknwon both of those are fair points. My question to the broader audience here is: shall we (as teams) adopt this convention then, or not? I _personally_ do not have a preference either way _except_ in the pursuit of consistency so there aren't nit review comments on PRs because 'sometimes we do this thing, but otherwise we should not, here are the bullet points to keep a mental model of ad-hoc stylistic rules where it's better' that myself and others are bound to forget.

**Comment by unknwon** [comment]
> @unknwon both of those are fair points. My question to the broader audience here is: shall we (as teams) try to adopt this convention then, or not? I _personally_ do not have a preference either way _except_ in the pursuit of consistency so there aren't nit review comments on PRs because 'sometimes we do this thing, but otherwise we should not, here are the bullet points to keep a mental model of ad-hoc stylistic rules where it's better' that myself and others are bound to forget.

Agree that we should make the convention explicit. A good starting point could be having a section in https://about.sourcegraph.com/handbook/engineering/languages/go that describes when it is OK to use underscores?

**Comment by rvantonder** [comment]
FYI linter doesn't like those underscores either so if we do adopt this convention that should be configured in the linter.

Screen Shot 2020-05-25 at 11 15 03 PM

 https://github.com/sourcegraph/sourcegraph/pull/10972/files#diff-bd32118b53139ae78a7f61397b4b65d1R31

**Comment by keegancsmith** [comment]
If you grep for your private function name, you will still get hits in the _test file because we have to call it. Personally I think it looks quite ugly. And to resolve these sort of issues I like to defer to deities (ie the go stdlib). It only has two hits for [`func Test_`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/golang/go%24%40go1.14.3+func+Test_&patternType=literal). However, it has lots of hits for underscore to separate the method from the struct name in a test: [`func Test.*_`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/golang/go%24%40go1.14.3+func+Test.*_&patternType=regexp&case=yes). Let's adopt that convention (which we mostly already do in our codebase):

- Use _ to seperate method name from struct name
- If testing a private function fooBar, the test is called `TestFooBar`.

**Comment by unknwon** [comment]
> Let's adopt that convention (which we mostly already do in our codebase):
> 
> * Use _ to seperate method name from struct name
> * If testing a private function fooBar, the test is called `TestFooBar`.

SGTM

**Comment by rvantonder** [comment]
Thanks for the input. I'll revert the changes in this PR for Keegan's suggestion and update the docs. Stay tuned.

**Comment by rvantonder** [comment]
Handbook PR https://github.com/sourcegraph/about/pull/980

**Pull request merged**
