### PR TITLE
dev/gqltest: Unskip bitbucket project perms tests

### LINKED ISSUE #54475: Investigate flaky integration tests for bitbucket permissions sync
We disabled some tests in https://github.com/sourcegraph/sourcegraph/pull/52057. 

We should follow up with enabling them and running them multiple times and investigate if the flakes are still occuring.

### PR DESCRIPTION
**Pull request by indradhanush**
Let's see how CI behaves here.

Originally skipped in #52057. 

Closes #54475.

## Test plan

CI and main-dry-run.

### CODE REVIEW

**Comment by indradhanush** [comment]
@willdollman Do you perhaps remember the context on why these tests were flaking? They passed in CI now. Do you think its safe to enable them again?

**Comment by burmudar** [comment]
> @willdollman Do you perhaps remember the context on why these tests were flaking? They passed in CI now. Do you think its safe to enable them again?

@indradhanush Here is the original thread https://sourcegraph.slack.com/archives/D03E81M0LQ4/p1688114287555429 TL;DR: We were getting license enforcement issues. When we tried cloning more repos it said we were not allowed to

**Review by burmudar — APPROVED** [review]
I've tried recreating it locally (the target is `//testing:backend_integration_tests` and not `//dev/gqltest:gqltest_test`) but wasn't able to hit the issue we previously got.

So I think lets enable it now and monitor!

**Comment by burmudar** [comment]
Merging this @indradhanush

**Comment by indradhanush** [comment]
Woohoo! Thank you @burmudar! ❤️ 

Do you want to leave a reference to the branch where you ran the tests for posterity's sake?

**Comment by burmudar** [comment]
Sure. Let the world see my _dirty laundry_ 😝  All my hacks can be found on `wb/unskip-bb`

**Pull request merged**
