### PR TITLE
app: move graphql resolvers into app package

### PR DESCRIPTION
**Pull request by keegancsmith**
This is the pattern we use with other new resolvers we add. It will also make it easier to fix the current todo around injecting servegit handler.

Test Plan: CI

### CODE REVIEW

**Comment by keegancsmith** [comment]
I just realised this makes it so that app graphql resolvers only work on enterprise. Not sure if that is what we want. Additionally, I wonder if we should running app initializers only to app. Right now it runs that github init even if we are not an app build.

**Comment by slimsag** [comment]
> I just realised this makes it so that app graphql resolvers only work on enterprise. Not sure if that is what we want.

Would be nice to avoid, but probably not the end of the world if it happens.

> I wonder if we should running app initializers only to app. Right now it runs that github init even if we are not an app build.

Not sure which github init you are mentioning, but we should definitely be careful about what we run where (and also about the differences between `deploy.IsApp` and `deploy.IsSingleBInary`)

**Review by slimsag — APPROVED** [review]
code lgtm generally

**Comment by gl-srgr** [comment]
> I wonder if we should running app initializers only to app. Right now it runs that github init even if we are not an app build.

Is the concern that folks running non-app will see suggestions for the graphql api that should be disabled or unreachable in a non-app setting? I was under that impression when the `appResolver` was first introduced.

**Comment by keegancsmith** [comment]
This is the code I am referring too. https://github.com/sourcegraph/sourcegraph/blob/v5.0.0/enterprise/cmd/frontend/internal/app/app.go#L36

It looks App specific to me, but we always call Init no matter the deployment target. Should we be skipping this code in non-app environments?

I am just gonna close out this PR, since I don't like that it makes it only work on enterprise.

**Pull request closed without merging**
