### PR TITLE
Update src-cli

### PR DESCRIPTION
**Pull request by Chickensoupwithrice**
Following the [release procedure](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/DEVELOPMENT.md#releasing)

## Test plan

Only doc / constant changes

## Changelog

- **misc: update src-cli minimum version const**
- **misc(docs): run `src doc -o ./doc/integration/cli/references`**

### CODE REVIEW

**Review by shivasurya — APPROVED** [review]
Thank you so much!

**Comment by Chickensoupwithrice** [comment]
Hey @MaedahBatool, I'm not entirely sure, but I think something is wrong with this test that's failing. I thought the new docs website is "sourcegraph.com/docs/...", but the test requires me to have "docs.sourcegraph.com/..."? `src-cli` is outputting "sourcegraph.com/docs". Not sure if you're the right person to ping, but hopefully you can lead me to them? :)

**Review by DaedalusG — APPROVED** [review]

**Comment by willdollman** [comment]
I've added the `backport 5.5.x` label as we also want these changes on the 5.5.x branch to patch the vulns there.

**Comment by Chickensoupwithrice** [comment]
@MaedahBatool informed me that the docs no longer live in this repo. We'll need to do a few things to land this

- Revert docs changes in this PR
- Run `src doc -o ... ` in the sourcegraph/docs repo
- Update the [src cli documentation](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/DEVELOPMENT.md#releasing) to point to the docs repo instead of here

**Comment by Chickensoupwithrice** [comment]
Okay, I got to fixing this up. Turns out the new [docs repo](https://github.com/sourcegraph/docs) already has the docs change. It also turns out that `src` outputs `.md` files while that repo is all `.mdx` files. Not a big deal since there's no changes currently, but something we'll probably want to fix. 

I'm going to go ahead and drop the docs changes from this PR so that we can still merge this in. Given we're now at `v5.6.0` (though to my knowledge no new `src-cli` release is necessary) We should probably also backport this to that branch.

**Pull request merged**
