### PR TITLE
Revert "Revert "use alpine postgres image (#22655)" (#23324)"

### PR DESCRIPTION
**Pull request by davejrt**
This reverts commit 791d5df2288c6d328d77000e7d11db68eba5c090 and uses alpine as a base

### CODE REVIEW

**Comment by rvantonder** [comment]
@davejrt there was a brief interval of about 20 minutes where I broke build on `main`. It looks like you got hit and branched off of aa18bda810de347abaccdbc68a0e501cf001617d. Please rebase (or I can do that for you on this PR).

**Comment by davejrt** [comment]
@rvantonder sure thing, go ahead

**Comment by ggilmore** [comment]
I think you need to wait for https://github.com/sourcegraph/sourcegraph/pull/23697, otherwise k8s.sdgev.org would get index corruption

**Comment by davejrt** [comment]
> I think you need to wait for #23697, otherwise k8s.sdgev.org would get index corruption

acknowledged

**Comment by rvantonder** [comment]
Will it be a while before #23697 or this PR is merged? I have some PRs that rely on building Sourcegraph for backend integration tests and these are blocked because the tests fail because of the `postgres` issue and can't merge 🙂

**Comment by ggilmore** [comment]
What `postgres` issue?

**Comment by ggilmore** [comment]
This PR doesn't change anything about how the images are built, only stuff at runtime

**Comment by rvantonder** [comment]
OK, then I guess it's unrelated (sorry). It seems somehow relevant.  As of 5d61c927fd355b314825b163328da6d62e3d7d0e `main` is broken because of this:

> ERROR: unable to select packages:
--
  | postgresql-12.8-r0:
  | breaks: world[postgresql=12.7-r0]

in the integration test job. [Example](https://buildkite.com/sourcegraph/sourcegraph/builds/105189#9d924763-9ba2-46e4-9b38-e24f211c60ce/1418-1568).

**Review by daxmc99 — APPROVED** [review]

**Comment by davejrt** [comment]
> OK, then I guess it's unrelated (sorry). It seems somehow relevant. As of [5d61c92](https://github.com/sourcegraph/sourcegraph/commit/5d61c927fd355b314825b163328da6d62e3d7d0e) `main` is broken because of this:
> 
> > ERROR: unable to select packages:
> > --
> >   | postgresql-12.8-r0:
> >   | breaks: world[postgresql=12.7-r0]
> 
> in the integration test job. [Example](https://buildkite.com/sourcegraph/sourcegraph/builds/105189#9d924763-9ba2-46e4-9b38-e24f211c60ce/1418-1568).

@rvantonder PR to fix that issue https://github.com/sourcegraph/sourcegraph/pull/23999

**Pull request merged**
