### PR TITLE
Add helper script to dump perforce instance state

### PR DESCRIPTION
**Pull request by ggilmore**
I won't provide an example of the output (for fear of leaking something), but you can run it once you set the environment variables as described in https://handbook.sourcegraph.com/departments/ce-support/support/process/p4-enablement/

For now, this is a relatively simple script that can be used of a perforce instance that you point it to. This includes:

- list of users
- list of groups
- list of depots
- mapping of user-to-group assignments
- p4 protection table for everything / from the perspective of individual users / from the perspective individual groups 

The idea I had is that this script could be used to "dump" the state of a perforce instance, which could be helpful with:

1. Drift detection - you can put the output of the script in version control - and see if the output of the script changes - which could indicate that someone edited the instance in a way that your tests didn't expect
2. calculating some aggregate information (like user-to-group) mappings from an instance which could be tedious / error-prone to repeatedly do by hand.

## Test plan

Tested locally

### CODE REVIEW

**Comment by ggilmore** [comment]
cc @mollylogue and @ryanslade

**Comment by ryanslade** [comment]
I'd say as long as it's in a working state it's worth merging as it could help with future debugging.

**Comment by mollylogue** [comment]
> I'd say as long as it's in a working state it's worth merging as it could help with future debugging.

Agreed. 👍

**Comment by ggilmore** [comment]
Feel free to adopt /merge this PR if you feel like it's helpful

**Comment by ryanslade** [comment]
I just pushed a small commit to move it under `/dev/perforce`

**Review by ryanslade — APPROVED** [review]
LGTM

**Pull request merged**
