### PR TITLE
phabricator: Remove custom json unmarshalling

### PR DESCRIPTION
**Pull request by ryanslade**
The custom unmarshaller on the Repo type was removed. Instead, we marshal into
an apiRepo struct and convert that into a Repo struct. Having a custom
unmarshal on the Repo type meant that when it was marshalled into our database
it couldn't be unmarshalled again.  This in turn broke our ability to build a
clone url from a stored Phabricator repo.

Spotted while investigating https://github.com/sourcegraph/customer/issues/371
but unlikely to be the fix.

### CODE REVIEW

**Comment by tsenart** [comment]
I don't have a lot of confidence in this change. I think we should try to replicate the customer issue or hop on a call to verify our assumptions.

**Comment by ryanslade** [comment]
This isn’t intended to fix the customer issue but at least gets the correct clone url for a Phabricator repo

**Comment by tsenart** [comment]
> This isn’t intended to fix the customer issue but at least gets the correct clone url for a Phabricator repo

But does the customer clone from Phabricator or from Gitolite? I'm a bit confused because our Phabricator integration is not like the others — we don't support repo syncing of Phabricator repos the same way we do other external services.

**Comment by ryanslade** [comment]
> > This isn’t intended to fix the customer issue but at least gets the correct clone url for a Phabricator repo
> 
> But does the customer clone from Phabricator or from Gitolite? I'm a bit confused because our Phabricator integration is not like the others — we don't support repo syncing of Phabricator repos the same way we do other external services.

I think they clone from Gitolite.

To be clear, I don't expect this fix to solve their issue but it is a bug we need to fix either way since it was causing our own Phabricator setup configured in `dev-private` to fail.

**Comment by tsenart** [comment]
OK. In that case would it be better to create an apiRepo type that has this custom marshal methods attached, and then we convert to a normal exported Repo?

**Comment by ryanslade** [comment]
@tsenart PTAL

**Review by tsenart — APPROVED** [review]

**Pull request merged**
