### PR TITLE
Auth tech debt

### PR DESCRIPTION
**Pull request by beyang**
~When set, the `organizations` field will require authenticating users be a member of one of the specified organizations.~

~This will enable us to turn on GitHub authentication on dogfood.~

~This can be reviewed commit by commit. The commit that actually implements the behavior is in the last commit. The previous ones are refactorings that were necessary to make the change possible.~

Auth refactorings / tech debt:
* remove `cmd/frontend/external/auth`
* use auth-provider-specific `sessionIssuerHelper`

### CODE REVIEW

**Comment by beyang** [comment]
Existing user sessions will not be invalidated. However, they won't be able to re-sign-in.

Whitelisting on a user-by-user basis seems like a separate feature. What if an admin wants to enable all users from a given org to sign up for accounts (as we do with our dogfood instance)?

Linking an existing account but not signing in directly via GitHub also seems like not the right thing—what if GitHub is the only enabled auth mechanism?

There may be a larger conversation to have about what we want to support with user authentication. But for now, I'd rather just ship this as-is and make the docs clear about what the behavior is, so we can unblock deploying this feature to dogfood and our own testing of GitHub auth. I also think this is the right behavior for an authn provider. Sourcegraph does not sync its session state to changes in any other SSO provider. If a customer is worried about blocking specific users, they should either (1) use a HTTP header-based auth proxy, in which case they have full control over the authentication of all requests or (2) we should add a user blocking/session revocation feature.

**Comment by sqs** [comment]
> What if an admin wants to enable all users from a given org to sign up for accounts (as we do with our dogfood instance)?

I am technically in the Google org on GitHub because I have push access to a repository (google/go-github). So I fear that adding this feature is going to lead to confusion. I think GitHub would say that this needs to support team-based auth too to be truly complete.

My point about just letting you link an existing account to a GH account would solve for us being able to dogfood the linkage on dogfood. (And we don’t need any kind of restriction for dotcom.) That seems better than adding a new feature that can easily cause confusion and result in more people having access than intended.

**Comment by beyang** [comment]
> I am technically in the Google org on GitHub because I have push access to a repository (google/go-github). So I fear that adding this feature is going to lead to confusion.

If you're an admin and part of an org that adds "outside collaborators" to its org, then I'd expect you to be aware of this fact. In that case, you probably want team-based auth (which we can build separately). Note, however, if you enabled authz, someone like your user wouldn't be able to access the private repositories unless they were granted access.

> I think GitHub would say that this needs to support team-based auth too to be truly complete.

I agree, but the feature as-is is likely to be useful. Building this to be feature-complete with GitHub auth now seems like premature optimization.

> My point about just letting you link an existing account to a GH account would solve for us being able to dogfood the linkage on dogfood.

We can do this, but in that case why invest in this as a feature at all? It seems highly unlikely that a user would want to use both built-in and GitHub auth. I'd rather just add it to `experimentalFeatures` and leave undocumented.

**Comment by sqs** [comment]
> We can do this, but in that case why invest in this as a feature at all? It seems highly unlikely that an external org would want to use both built-in and GitHub auth. I'd rather just add it to experimentalFeatures and leave undocumented.

If you implement the AuthProvider interface, you should get this nearly for free. My point is that to dogfood this feature, you could deploy it after just getting to that point, without needing org-based auth as well. It’s built now so it’s a sunk cost somewhat, but it’d still be easier to get it dogfoodable by letting people link accounts than reviewing and merging this. (Or if it doesn’t seem that way to you then we can chat)

**Comment by beyang** [comment]
Most of the PR was addressing dealing with tech debt I'd like to address regardless, so resubmitting just those commits. Will submit a PR for option to not permit new signups under GH auth later.

**Pull request merged**
