### PR TITLE
monitoring: Disable custom repo-updater pod availability alert

### PR DESCRIPTION
**Pull request by tsenart**
A 1m window is too small, and makes us receive pages for normal
deployments. We want to get alerted on container restarts, but requires
kube-state-metrics, which we don't yet have.

### CODE REVIEW

**Comment by tsenart** [comment]
cc @pecigonzalo

**Comment by pecigonzalo** [comment]
@tsenart I reckon we could increase the time window instead, and keep this alert.

**Comment by tsenart** [comment]
@pecigonzalo: What do you think is an appropriate time window? By default, this is 10 minutes, which is what this reverted to.

**Comment by pecigonzalo** [comment]
I think between 5 and 10m makes sense, but I inferred from the title this disabling the alert altogether.

**Review by pecigonzalo — APPROVED** [review]

**Review by asdine — APPROVED** [review]

**Pull request merged**
