### PR TITLE
Align tooltips on action sidebar to the left

### PR DESCRIPTION
**Pull request by philipp-spiess**
This PR fixes a small annoyance (thanks @vovakulikov for [reporting it](https://sourcegraph.slack.com/archives/C0HMGV90V/p1664454390437249)):

screenshot_2022-09-29_at_18 24 59

Unfortunately the root issue for this seems to be deeper in the tooltip library (as I can reproduce it in the wildcard storybook) so this is a quick workaround until we have a proper fix. 

## Test plan

Screenshot 2022-09-29 at 15 21 13

## App preview:

- [Web](https://sg-web-ps-fix-tooltip-position.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ajuithmgjt.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by taras-yemets — APPROVED** [review]

**Review by vovakulikov — APPROVED** [review]

**Comment by philipp-spiess** [comment]
@jjinnii Yeah this makes sense. I tried to do that now, wdyt?

Screenshot 2022-09-29 at 15 09 50

**Comment by vovakulikov** [comment]
@philipp-spiess it seems that GitHub icon isn't properly centred inside of hover layout container

**Comment by philipp-spiess** [comment]
@vovakulikov Yeah, lol. It's also noticeable on the original screenshot. On it.

**Comment by philipp-spiess** [comment]
Screenshot 2022-09-29 at 15 21 13

muuuch better 😎

**Review by jjinnii — APPROVED** [review]
Thanks so much for jumping on this! This was actually something I had seen and maybe might even have filed an issue for somewhere in our deep backlog, so glad it got worked on ❤️

**Pull request merged**
