### PR TITLE
search: Fix issue with type:commit where message and pattern return different results

### LINKED ISSUE #13313: Unintuitive commit search behavior
I'm not sure how our commit search interprets search patterns. In whatever this works, it's unintuitive. Example:

[`repo:^github\.com/sourcegraph/sourcegraph$ type:commit author:rvantonder refactor`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+author:rvantonder+refactor&patternType=literal)

No results. Note that my intent is to find commits that contain the word refactor. I don't really care if it's in the commit body or title (both is probably best). Now if I type `message:refactor`, all is well, lots of hits:

[`repo:^github\.com/sourcegraph/sourcegraph$ type:commit author:rvantonder message:refactor`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+author:rvantonder+message:refactor&patternType=literal)

Either:

(1) we should treat that first query as an implicit parameter. If I am missing something in the implementation for why we can't do this, then:

(2) we encode how to validate the case that doesn't contain a `message`, and offer a helpful hint.

I think we can probably support (1) and this is just a shortcoming. Should be very easy with the new parser code.

### PR DESCRIPTION
**Pull request by camdencheek**
The `git log` command was being built with the `-G` flag when a pattern was used for search, which restricts matches to diffs only. This was leading to incorrect results, and different results between `type:commit query` and `type:commit message:query`. 

This skips adding the `-G` flag when `type:commit`. 

Fixes #13313

### CODE REVIEW

**Comment by camdencheek** [comment]
Does anyone know why those tests might be failing in this env? Both of the integration tests that are failing pass locally. Interestingly, there is another (unrelated) integration test that is failing locally.

**Comment by rvantonder** [comment]
It's failing because `repo:^github\.com/sourcegraph/sourcegraph$` isn't in the repository test set in CI. It's probably cloned locally for you though. Pick a different repo to test on?

Also fixes #16969 I think.

**Comment by rvantonder** [comment]
I.e., one of these (`sourcegraph/sourcegraph` is a bit large to include I think):

```

"sgtest/java-langserver",
--
  | "sgtest/jsonrpc2",
  | "sgtest/go-diff",
  | "sgtest/appdash",
  | "sgtest/sourcegraph-typescript",
```

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/gqltest/search_test.go#L36-43

**Comment by rvantonder** [comment]
Also changelog entry, this is a great fix 🎉

**Review by rvantonder — CHANGES_REQUESTED** [review]
Just managing the review queue so it re-requests after you fix up the test.

**Comment by unknwon** [comment]
It is currently failing because "sourcegraph/sourcegraph" is not in the list of cloned repos (for testing):

https://github.com/sourcegraph/sourcegraph/blob/0e3a2c2c65ea60318ae70622ce2fa51c29616e94/dev/gqltest/search_test.go#L33-L43

Also note that in CI we use "ghe.sgdev.org" (our test instance) not GitHub.com for stable testing environment (in case of GitHub.com is done).

**Comment by camdencheek** [comment]
Alright -- got it passing! Thank you both for the help. One last question -- it looks like in `search_test.go`, it references `https://ghe.sgdev.org`, but my tests would fail if I used that URL, even against a local instance that had those repositories cloned. The only way I could get it to run was to use `github.com/sgtest/...`, modeling after the other tests in the file. I noticed that, further down in that file, we `WaitForReposToBeCloned` with the `github` URLs rather than the `ghe.sgdev.org` URLs. Are those repos aliased when we clone them or something?

**Review by rvantonder — APPROVED** [review]
slam-dunk

**Comment by rvantonder** [comment]
You mean you set up local tests to point to `https://ghe.sgdev.org`? You'd probably need to set up tokens for auth and I don't think it's useful/worth setting that up. Re: your other question, @unknwon can confirm, maybe it is the case that we are actually cloning from GH?

**Comment by camdencheek** [comment]
Yeah -- I got the tokens for auth all set up, and I could query `ghe.sgdev.org` on my local instance, but the tests wouldn't work using it. Not a huge deal since they seem to all still be available with the `github.com` URLs, but I don't really understand why it works that way

**Comment by unknwon** [comment]
All repos are cloning from https://ghe.sgdev.org, I can assure that. The reason that it looks like a GitHub.com URLs is because I renamed it! (using our own feature) 

https://github.com/sourcegraph/sourcegraph/blob/0e3a2c2c65ea60318ae70622ce2fa51c29616e94/dev/gqltest/search_test.go#L45

That way, I don't have to update strings ("github.com" -> "ghe.sgdev.org") in all test cases and continue to make them work.

Sorry about the confusion though...

**Comment by unknwon** [comment]
^ So if you happen to cloned "github.com/sourcegraph/sourcegraph" locally, it's there and works.

**Comment by camdencheek** [comment]
Aaah - that makes a lot more sense! Thanks for the explanation

**Pull request merged**
