### PR TITLE
Update cadvisor base image

### PR DESCRIPTION
**Pull request by andreeleuterio**
cadvisor has a few open CVEs that don't directly affect us but are quick to get rid of. I used the last cadvisor image that doesn't have a `test` tag. I built the new image locally and trivy found no CVEs:
```
trivy image --severity "HIGH,CRITICAL" andre/cadvisor-test
2022-05-20T11:27:03.578-0300	INFO	Detected OS: alpine
2022-05-20T11:27:03.578-0300	INFO	Detecting Alpine vulnerabilities...
2022-05-20T11:27:03.579-0300	INFO	Number of language-specific files: 0

andre/cadvisor-test (alpine 3.15.4)
===================================
Total: 0 (HIGH: 0, CRITICAL: 0)
```
## Test plan
I'm trusting CI checks. If any further testing is necessary let me know.

### CODE REVIEW

**Review by kevinwojo — APPROVED** [review]
Lgtm

**Comment by andreeleuterio** [comment]
@kevinwojo any ideas on the linter error? It seems like we use this pattern in other Dockerfiles

**Comment by andreeleuterio** [comment]
@kevinwojo I added a lint skip. The error seemed minor and it wasn't clear how to fix it. It was also unrelated to my changes.

**Comment by unknwon** [comment]
I don't understand how CI steps become different for different commits on the same PR (some commits triggered to build cadvisor but others only triggered lint?), look like a logic bug in our diff detect? cc @bobheadxi

**Pull request merged**
