### PR TITLE
(feat) add repo metadata key filter query link

### PR DESCRIPTION
**Pull request by erzhtor**
Part of https://github.com/sourcegraph/pr-faqs/issues/96.

## Test plan
- `sg start`
- Enable the `repository-metadata` feature flag
- Search repos (`select:repo`) with metadata. If not, add some via repo root page UI

## Screenshot

https://user-images.githubusercontent.com/6717049/235146640-bfb69bfd-a2ce-4602-b30f-b9b9ee585d98.mov

### CODE REVIEW

**Comment by sourcegraph-buildkite** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.94 kb) | 0.02% (+1.94 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/erzhtor/add-repo-metadata-filter-query-link/compare-report.html;tab=live_object) for a full comparison between the commits c296275 and 7c2057f or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by toolmantim** [comment]
👏🏼

The original intention was that each whole badge was clickable (say, with a darker background color change) — but only linking the text might work when we want to link the value too, and not just the key. Which leads to my next question…

Any reason we haven't linked the "value" part of the badge yet? Or is that coming in a follow-up? Feels odd without that. e.g. for "license: mit" we'd link "license" to `repo:has.meta(license)` and "mit" to `repo:has.meta(license:mit)` (or whatever the final search names we chose were)

**Comment by erzhtor** [comment]
Thanks @toolmantim, for the reviews. 

> Any reason we haven't linked the "value" part of the badge yet? Or is that coming in a follow-up? Feels odd without that. e.g. for "license: mit" we'd link "license" to `repo:has.meta(license)` and "mit" to `repo:has.meta(license:mit)` (or whatever the final search names we chose were)

1. That is easily doable, however, I'm just worried about the UX, will it be straight forward that two parts of the same badge be different links?

> The original intention was that each whole badge was clickable (say, with a darker background color change) — but only linking the text might work when we want to link the value too, and not just the key. Which leads to my next question…

2. My bad, I thought that we agreed on this approach. We can make the badge to make a link which will lead to `repo:has.key()` or `repo:has(key:value` depending on whether the metadata consists of key-value pair or just key.

I think 2nd makes more sense (with making the whole badge clickable), I will update to follow this logic. But let me know if you think, we should consider 1st point/option too.

**Comment by erzhtor** [comment]
@toolmantim, updated to make whole badge clickable and make link filter different based on metadata value presence 042149b5e11faf7fac418252661b494180fca69b.

**Comment by toolmantim** [comment]
I'll trust your gut feeling on the two links in the one badge being confusing!

And sorry about not being clear on the style! I assumed we would be going with the standard `<Badge as={Link}>` that I spotted in the following, but I should have been clear about that earlier:

https://github.com/sourcegraph/sourcegraph/blob/df2d87dda19f9be93b59d9ba48a3dc07d293d676/client/wildcard/src/components/Badge/Badge.story.tsx#L57

https://user-images.githubusercontent.com/153/235846986-93f6248f-2669-4247-829e-3fb118ecb6fc.mov

Could we make the whole thing clickable, similar to how it works in the Storybook example? I tried to the change myself, but I think it's too much component rejigging with where the link is defined, so might need to get your help.

Also… giving it a go locally… I realised that if you're on a repo root page, I think we should to strip the `repo` off the URL from the badge links, so you can easily navigate to other repositories (which was the intention). wdyt?

https://user-images.githubusercontent.com/153/235847562-22adf089-8ff3-49f7-a254-0bb3bc5fc744.mov

**Review by sashaostrikov — APPROVED** [review]

**Comment by erzhtor** [comment]
Thanks @toolmantim for the review. Addressed [both feedback items](https://github.com/sourcegraph/sourcegraph/pull/51258#issuecomment-1532515794).

https://github.com/sourcegraph/sourcegraph/assets/6717049/b33ec6e4-d8e8-4674-b6fe-9c5dd9da73fa

**Pull request merged**
