### PR TITLE
accesslog: RFC using conf.Cached for IsEnabled

### PR DESCRIPTION
**Pull request by keegancsmith**
This is a simplification of the current code I read. However, it does not have the same behaviour around logging (it only logs on startup). This commit exists as a discussion point, and can be completely abandoned. If it is liked, it needs more work since the tests now fail since they assert on logging.

conf.Cached is a generic function which takes in a function and then returns a function which wraps it. Its behavior is:
- on first call it just calls the passed in function and returns.
- then it starts to watch config, each time the config is changed the function is called again and the new return value is returned.

This is quite a neat pattern, but likely needs some changes to suit this use case. In particular behaviour around the value changing may be a requirement to be logged.

### CODE REVIEW

**Comment by mrnugget** [comment]
I like the idea. What happens if you put the logging inside the `conf.Cached()` call? Won't that log only whenever the config changed? If so, I think that's fine, right?

**Comment by keegancsmith** [comment]
Yup, I think we can think up a decent API for this, I believe we have this pattern in a few places. The only downside right now is we need a way to pass in a useful logger here. I suppose a global log.Scoped will be fine for what is actually needed for customers. But at the end of the day the tests do a lot of assertation on logging, so it will take some reshaping of APIs to make that happen / not sure if it will be as clean due to limitations in generics

**Comment by vrto** [comment]
Yup, I like the idea as well. @bobheadxi came up with the original watcher idea, perhaps he'll have thoughts, too.

I don't mind if we completely re-do the tests, we only need to be able to use a `logtest.Captured` and we're good.

**Comment by mrnugget** [comment]
closing this so it's gone from my notifications 😛

**Pull request closed without merging**
