### PR TITLE
Update postgres version 9.6 -> 11

### PR DESCRIPTION
**Pull request by ijt**

### CODE REVIEW

**Comment by tsenart** [comment]
https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/postgresql.md#version-requirements

**Comment by ijt** [comment]
Hey, sorry. I saw the green button and I just went on autopilot, having just been on a project where that means it's safe to proceed. I'll make the change suggested by Keegan in another PR.

**Comment by tsenart** [comment]
We should revert this commit to master.

**Comment by ijt** [comment]
Okay, I'll do it.

**Comment by tsenart** [comment]
@ijt: Is there any additional context you'd like for the need to revert this?

**Comment by ijt** [comment]
I have a pull pending, just waiting for it to be approved before merging. https://github.com/sourcegraph/sourcegraph/pull/2698

**Pull request merged**
