### PR TITLE
JetBrains: Fix resize by adding padding

### PR DESCRIPTION
**Pull request by vdavid**
Fixes https://github.com/sourcegraph/sourcegraph/issues/35919
Fixes 1/3 of https://github.com/sourcegraph/sourcegraph/issues/36704

Also a typo fix in a comment.

## Test plan

- Watch this [1-min Loom demo](https://www.loom.com/share/94873cc5be7040b59864a1ba4e9ea318) and check the code.

## App preview:

- [Web](https://sg-web-dv-jetbrains-fix-resize-by-adding.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-yecxjtavqd.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by vdavid** [comment]
@jjinnii I know it doesn't match the Figma, but I saw no other way to fix [this weird behavior](https://www.loom.com/share/4386bab2fd1b4647b2511106c2f16670). It's a 4px border on both sides, and 5px at the bottom. These were the minimum amounts needed. 🤷‍♂️

With the light theme, it looks like [this](https://share.cleanshot.com/djfI0D).

With the dark theme, it would look smoother if the background color of the result list matched the standard popup background color, just like in the "Find in Files" window (for example, in [this Loom](https://www.loom.com/share/94873cc5be7040b59864a1ba4e9ea318) at 0:42).
But with the light theme, there is not much to do.

Is this okay with you? Any ideas to make it look nicer?

**Review by taras-yemets — APPROVED** [review]

**Comment by vdavid** [comment]
As this is not in production yet, I'm merging this; will adjust it according to @jjinnii's feedback next week.

**Comment by philipp-spiess** [comment]
Was resizing this slow before as well? It feels super obvious to me that this is not a native view when I resize which it also kind-of did with the bug in place as well :( 

https://user-images.githubusercontent.com/458591/174558115-600061c2-83f0-4f12-85a6-817b3ea29978.mov

I'm also really not a big fan of the added margins. Instead of something that is broken only when I need to resize it, the extension now feels broken even if I don't need to change its dimensions. In my opinion we need to prioritize finding a proper fix _or_ revert this "fix" before we ship the extension.

**Comment by vdavid** [comment]
- It was this slow before as well. :/
- I honestly can't judge how broken it looks for a fresh eye. For me it's only visible when I focus on it, but since I started working on other stuff and forgot about this, I haven't noticed it. I'd probably trust @jjinnii on this. I'm happy to revert it if she deems it too ugly. That said, I don't have high hopes for a different fix, so the decision might be between the padding and a broken resize feature.

One idea though: maybe set up a "resize started" event handler that adds the padding only for the time of the resize? That could work!

**Pull request merged**
