### PR TITLE
db: Set constraints as deferred in migration

### PR DESCRIPTION
**Pull request by ryanslade**
Without this it can take a very long time

### CODE REVIEW

**Review by tsenart — APPROVED** [review]

**Comment by tsenart** [comment]
@ryanslade: Does this need to go into the recent patch release?

**Comment by ryanslade** [comment]
> @ryanslade: Does this need to go into the recent patch release?

Nope, luckily the migration was merged after the release

**Comment by ryanslade** [comment]
I'm going to merge this anyway since the failures above relate to non db issues.

**Review by unknwon — APPROVED** [review]

**Comment by indradhanush** [comment]
Obligatory and related tweet: 
image

Source: https://twitter.com/AdaRoseCannon/status/1380881598409740292?s=20

**Pull request merged**
