### PR TITLE
codeintel: Unexport unused service methods

### PR DESCRIPTION
**Pull request by efritz**
Refactor to remove unused exported methods from service layers.

1. Removed `service` interface in each package as it was private and blocked refactor tools from working
2. Un-exported each method used only by the service itself
3. Removed observability wrapping from non-exported methods
4. Replaced unexported methods that proxy to the store with a call directly to the store 
5. Cleaned out observability fields

Let's just keep hacking at these services until they're clean. It'll take a bit of time but I think it's coming together already.

cc @Numbers88s I'm not opposed to adding back service interfaces, but they weren't explicitly used anywhere (we should use the iface type as the export instead of the struct if we're committing).

## Test plan

Ran locally.

### CODE REVIEW

**Comment by Numbers88s** [comment]
That's disappointing. I can add them when I get back, and we'll export the interface instead of the struct.

**Comment by efritz** [comment]
@Numbers88s Can you explain the appeal of having the interface at the same level? Maybe I'm missing a benefit, but it keeps us from detecting unused methods outside of the package, and makes us type the declaration twice when we make a new method (or alter it twice on modification).

**Comment by efritz** [comment]
(I just want to understand, I won't block them existing, they just got in the way when doing this)

**Comment by Numbers88s** [comment]
If it's preventing you from anything, remove it. I find it easier to navigate the services, reason about what they are about at a quick glance. And generally, it's my preferred convention for organization and DX.

**Comment by efritz** [comment]
@Numbers88s Let's remove it for now (in this PR, just so I don't have to redeclare it _yet_) and we can re-add interface methods to the _proper_ services once they land. This PR and a few others will try to move some of the methods between services if they are more strongly coupled (for example, the uploads service reaches into the autoindexing service to do cleanup stuff, but they should be independent). Having the interface there now makes it a bit more cumbersome to deal with.

**Comment by Numbers88s** [comment]
Yeah sounds like a plan. No worries, do what you need to and I can add them later, no prob

**Pull request merged**
