### PR TITLE
Adding loading messages and buttons to Cody App loading screen

### PR DESCRIPTION
**Pull request by toolmantim**
In recent user testing of sourcegraph/cody#1275 all the users mentioned App’s loading time, and many showed some discomfort as to whether it was loading correctly. Loading also stalled for one of the users.

This updates the App’s loading screen to:
- After 5 seconds, start showing some messages (ala Slack & Discord) to give people a bit more confidence that things are happening
- After 30s says "Initializing" and includes a link to show the logs and to email support

https://github.com/sourcegraph/sourcegraph/assets/153/13ffa3c5-7679-4ca6-b77f-56b4c1113229

## Test plan

- Tested in browser
- Test links in Tauri wrapper

### CODE REVIEW

**Comment by toolmantim** [comment]
@thenamankumar @dominiccooney could I trouble you to test this in the Tauri app? Or if not, let me know how I can do that myself 🙏

**Review by dominiccooney — APPROVED** [review]
"Reticulating Splines" ...

**Comment by dominiccooney** [comment]
@thenamankumar we need a pointer to test this in app. Here's what I am seeing:

```
dpc@dominics-mbp sourcegraph % pnpm tauri dev
        Info Watching /Users/dpc/sourcegraph/src-tauri for changes...
   Compiling tauri-plugin-positioner v1.0.4
   Compiling tauri-plugin-log v0.0.0 (https://github.com/tauri-apps/plugins-workspace?branch=v1#c009cb38)
   Compiling app v0.1.0 (/Users/dpc/sourcegraph/src-tauri)
error: failed to run custom build command for `app v0.1.0 (/Users/dpc/sourcegraph/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/dpc/sourcegraph/src-tauri/target/debug/build/app-e7bded4a9cac0c8e/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  path matching ../.bin/sourcegraph-backend-aarch64-apple-darwin not found.
🚀 A new version of Tauri CLI is available! [1.4.0]
```

**Comment by toolmantim** [comment]
@dominiccooney 80958378ad9

**Review by chwarwick — APPROVED** [review]
I tried it successfully running a local release build via  `CODESIGNING=0 CI=false ./dev/app/build.sh`.  I did have to rebase because the build script was broken.

@dominiccooney To run app locally `sg start app` is usually the best case unless you need to test deep links which require a release build due to how they are implimented on mac.

**Comment by toolmantim** [comment]
Thank you!

**Pull request merged**
