### PR TITLE
Issue 25239 - Fix for code intel prompt errors while diffing files in split mode

### PR DESCRIPTION
**Pull request by subhash686**
Closes Issue - https://github.com/sourcegraph/sourcegraph/issues/25239

## Test plan
Tested visually,
- launched comparison in split mode
- hovered on code elements on both "base" and "head" sides
- code intel prompt apperead at right line and space.

Working code intel prompt - "base" side of comparison
Screenshot 2022-04-20 10 27 48 PM

Working code intel prompt - "head" side of comparison
Screenshot 2022-04-20 10 28 03 PM

Element property that needed changing "data-split-mode"
Screenshot 2022-04-21 9 45 13 AM

### CODE REVIEW

**Comment by subhash686** [comment]
Signed CLA.

**Comment by subhash686** [comment]
@cla-bot check

**Comment by subhash686** [comment]
@sourcegraph/contribution-reviewers Signed CLA.

**Comment by subhash686** [comment]
Create a clabot PR, wondering if that is the new workflow - https://github.com/sourcegraph/clabot-config/pull/70

**Comment by subhash686** [comment]
@valerybugakov @5h1rU Could you please take a look? I signed CLA and am waiting to get some eyes on this one.

**Comment by subhash686** [comment]
@cla-bot check

**Comment by subhash686** [comment]
@cla-bot check

**Comment by subhash686** [comment]
@sourcegraph-bot Can the codeowners review this PR pending for more than 4 months?

**Review by valerybugakov — APPROVED** [review]
Sorry for the delay, and thank you for the contribution! 🙌
I triggered the CI build for this PR. Once it passes, we will be able to merge it.

**Comment by valerybugakov** [comment]
@subhash686, could you merge the `main` branch into your branch? It has changes required for our CI pipeline to be green.

**Comment by subhash686** [comment]
> @subhash686, could you merge the `main` branch into your branch? It has changes required for our CI pipeline to be green.

I somehow missed that notification. I merged the `main` branch into mine. Please trigger the CI and let me know if you see any issues. Thanks!

**Comment by subhash686** [comment]
Can somebody please trigger CI on this PR?

**Comment by valerybugakov** [comment]
@subhash686, I triggered the build, thank you!

**Comment by subhash686** [comment]
> @subhash686, I triggered the build, thank you!

Thanks. I did merge from `main` and still see some steps fail. Unfortunately I don't have access to view the errors. Can somebody please guide me with the next steps here? Thanks!

**Comment by valerybugakov** [comment]
@subhash686, it was an issue on our side and it's fixed now 👌

**Pull request merged**
