### PR TITLE
Allow changing the overlay mount location

### PR DESCRIPTION
**Pull request by lguychard**
Rel https://github.com/sourcegraph/sourcegraph/issues/3228#issuecomment-481174882

On GitLab merge request pages, the diff tab is always present. As a result, when switching tabs, the hover overlay remains visible, since it is by default mounted to `document.body`, and as such is not affected by the change in visibility of the diff tab.

This PR introduces the ability to customize the hover overlay mount location, through `CodeHost.getHoverOverlayMountLocation()`. If `CodeHost.getHoverOverlayMountLocation()` is unspecified, or if it returns `null`, the hover overlay will be mounted to document.body. If the custom mount location is removed from the DOM, the hover overlay will be mounted to document.body again.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Code LGTM. For my understanding, could you describe what happens (in this code) specifically in Gitlab when the user is switching tabs on an MR?

**Comment by lguychard** [comment]
1. User visits https://gitlab.com/gitlab-org/gitaly/-/merge_requests/1575. `div.tab-pane.diffs` doesn't exist yet (it'll be lazy-loaded) -> the hover overlay is mounted to `document.body`.
2. User visits the 'Changes' tab -> the hover overlay is unmounted from `document.body`, mounted to `div.tab-pane.diffs`
3 User visits the 'Overview' tab -> `div.tab-pane.diffs` is hidden, and as a result so is the hover overlay.

Then there's some defensive code accounting for `div.tab-pane.diffs` being _removed_ (for example during a navigation away from the MR that only results in a soft reload), to remount the hover overlay to `document.body`. I haven't encountered this case in practice, but thought it best to account for it.

**Comment by felixfbecker** [comment]
That could be great to add in a comment somewhere as an example!

**Comment by lguychard** [comment]
Added as a doc block to `observeHoverOverlayMountLocation()`.

**Pull request merged**
