### PR TITLE
Migrate enzyme tests to @testing-library/react

### PR DESCRIPTION
**Pull request by gitstart-sourcegraph**
## Description
Migrate `enzyme` tests to `@testing-library/react`

## Refs
[Gitstart Task](https://app.gitstart.com/tasks/25367)
[SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/24986)

## Success Criteria
Migrate the following files to `@testing-library/react`

- [x] client/web/src/enterprise/code-monitoring/components/CodeMonitorForm.test.tsx 

-  [x] client/web/src/search/panels/PanelContainer.test.tsx 

-  [x] client/web/src/enterprise/code-monitoring/components/FormActionArea.test.tsx 

-  [x] client/web/src/repo/actions/InstallBrowserExtensionAlert.test.tsx 

-  [x] client/shared/src/components/activation/ActivationDropdown.test.tsx 

-  [x] client/web/src/nav/UserNavItem.test.tsx 

-  [x] client/web/src/tree/FileDecorator.test.tsx

### CODE REVIEW

**Review by limitedmage — APPROVED** [review]
@sourcegraph/frontend-platform  We should consider converting all snapshot tests that don't need any interaction to storybook tests. Snapshot tests are hard to review, while storybook tests are reviewed visually, so it's much easier to find regressions.

**Review by valerybugakov — APPROVED** [review]

**Review by valerybugakov — COMMENTED** [review]
@limitedmage, we can use Percy snapshots for that. It is preferable because it ensures that we capture that whole interface inside the application instead of the isolated part of the React tree. We will iterate on that later. The main intention behind these PRs is to ensure that we use _one_ library for React components unit tests.

**Comment by limitedmage** [comment]
@valerybugakov Agreed that converting these to testing-library is good! I think storybook tests might be superior to Percy tests in a number of ways for individual component testing. There are pros and cons for each. I think that anything that is being tested with Jest snapshots and doesn't have any interaction (eg. clicks) should first be migrated to storybook tests instead of Percy tests.

**Review by umpox — APPROVED** [review]

**Comment by umpox** [comment]
@limitedmage Fully agree, I think in many cases our snapshots won't be necessary as we'll have covered the component already in Storybook. Hoping to get some time to start improving our tests generally across the app once we've migrated everything to testing-library!

**Pull request merged**
