### PR TITLE
site-config: Reduce auth session duration

### PR DESCRIPTION
**Pull request by miveronese**
Jira ticket: [CLOUD-247](https://sourcegraph.atlassian.net/browse/CLOUD-247)

This PR reduces the session length from 90 days to 7 days as recommended in the ticket linked above

Blocked by this PR: https://github.com/sourcegraph/clabot-config/pull/51

## Test plan
- All existing tests should pass.
- When adding the configuration for "auth.sessionExpiry" (under User Admin > Site Configuration), the user should see an updated description for that field (informing that the default value is 7 days).

### CODE REVIEW

**Comment by miveronese** [comment]
Team, are these docs going to be updated automatically? Or should I manually update them?
https://docs.sourcegraph.com/admin/config/site_config

**Review by unknwon — CHANGES_REQUESTED** [review]
There are few things going on here:

1. Looks like your local Git config is using someone else name that is not linked to your GitHub account? That's probably why CLA bot is failing.
2. I think the ticket is about changing the `auth.sessionExpiry` only for Cloud, not for every Sourcegraph instance (which this PR does).
3. According to [How to make updates to sourcegraph.com config](https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/devops/update_sg_website_config), I think this config option is non-sensitive, so we should add a _new line_ after https://github.com/sourcegraph/deploy-sourcegraph-cloud/blob/release/base/frontend/non-sensitive-site-config.ConfigMap.yaml#L65 (we currently do not change this value in Cloud's config, so we're using 90 days default duration).
4. tip: You can just request review for the entire cloud saas team without picking individuals, that works! 

	CleanShot 2022-02-14 at 14 35 38@2x

Request changes because I think we're not making intended changes.

**Comment by miveronese** [comment]
@cla-bot check

**Comment by miveronese** [comment]
Thank you so much, @unknwon, for the comments/suggestions.  I will close this PR and open it in the repo that handles the cloud config.

**Pull request closed without merging**
