### PR TITLE
perforce: create example depot for use for use in permissions testing

### PR DESCRIPTION
**Pull request by ggilmore**
This PR adds two things:

## example depot for Perforce permissions testing

This is an example Perforce depot that has a file/folder layout similar to the one that the customer (linked in this [Slack thread](https://sourcegraph.slack.com/archives/C03MV6CKU1X/p1658383393797199)) uses in their test suite. 

- The exact file paths mentioned in the customer's original test suite were substituted with similar-enough ones. I chose to use human-friendly file / folder names instead of the machine-obfuscated ones contributed in https://github.com/sourcegraph/sourcegraph/pull/39063. Since we're going to be doing _manual_ testing at first, I thought it would be a lot easier for people to reason about files/folders that looked like common words instead of hashes. 

- Each folder has a file named `path.txt` in it. The tests in the original suite didn't enumerate the full file tree: there are folders that are alluded to in tests with unknown file contents. You can't create an empty folder in Perforce, so I added a stub `path.txt` file at every level to work around that. 

## ./p4-upload.sh

This is a simple bash script that uploads the above depot to the Perforce server specified in the supplied P4PORT and P4USER environment variables (default: `admin@perforce.sgdev.org`) . The script does this idempotently - on each run it'll delete and re-submit the depot from scratch. This ensures that the depot's state is exactly what we expect for each round of manual testing. Eventually, this script (or the logic in it) should be able to be used in an automated integration test setup as well. 

## Test plan

Tested by manually running this script against perforce.sgdev.org.

### CODE REVIEW

**Comment by ggilmore** [comment]
cc @sourcegraph/repo-management PTAL

**Review by mollylogue — COMMENTED** [review]
I wonder if it would make sense to put the depot files in a zip or tar file rather than committing them all as-is? It might just make things a bit more compact. Then the script would have an extra step to unzip before creating the depot.

**Comment by ggilmore** [comment]
@mollylogue  Part of the idea was to make it so that we could easily inspect the contents of the depot (in plain text) and version control it alongside the (eventual) automated tests. I do upload all the files in parallel, so this script should run relatively quickly.

**Comment by ggilmore** [comment]
superseded by https://github.com/sourcegraph/sourcegraph/pull/39721

**Pull request closed without merging**
