### PR TITLE
JetBrains: Detect install/uninstall events and generate a unique device id

### PR DESCRIPTION
**Pull request by philipp-spiess**
Part of #35178 

This PR adds a way for us to detect install/uninstall events as well as make sure we have a unique device id that we can use for all further logging.

## Test plan

Added custom dialogs and walked through the behavior here:

https://www.loom.com/share/f46fa0101a544cf19e1e9c0d73c078b6

## App preview:

- [Web](https://sg-web-ps-jetbrains-install-uninstall.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-deypglcdps.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by madppiper** [comment]
You can do it this way. 

I would only suggest renaming both the service classes that set the config to "Service" (ie: com.sourcegraph.config.SourcegraphConfig > com.sourcegraph.config.SourcegraphProjectService, 
SourcegraphApplicationConfig > SourcegraphApplicationService). Simply because it can be confusing as a name. But that's not a big issue

**Review by vdavid — APPROVED** [review]
Niice! I love that you could hook up events to _all_ of these actions! :o The only thing I don't like is the new `activities` folder because
1. we have other activities that are not in here
2. I prefer to organize code by business logic first rather than type
but that said, I have no better suggestion for this specific case and it's not really worth giving it more thought, so it's totally fine. It's also very easy to reorganize later.

**Comment by philipp-spiess** [comment]
> I prefer to organize code by business logic first rather than type

That makes sense, I'll create a module for logging related stuff

**Comment by philipp-spiess** [comment]
> I would only suggest renaming both the service classes that set the config to "Service" (ie: com.sourcegraph.config.SourcegraphConfig > com.sourcegraph.config.SourcegraphProjectService,
SourcegraphApplicationConfig > SourcegraphApplicationService). Simply because it can be confusing as a name. But that's not a big issue

Yeah makes sense, the official guide also uses the Service suffix for this: https://plugins.jetbrains.com/docs/intellij/persisting-state-of-components.html#defining-the-storage-location

Will change.

**Pull request merged**
