### PR TITLE
vcs/git: Sandboxed .gitconfig in all git commands

### PR DESCRIPTION
**Pull request by tsenart**
#### Background

Tests were failing for me because of some special .gitconfig options I
have set. We should not be reading or messing with system level or the
$USER's .gitconfig, only with the repo scoped one.

This commit makes it so that all git commands are ran with the repo's
local `.git/config` file.

#### Notes

Extracted from #1391.

### CODE REVIEW

**Comment by keegancsmith** [comment]
> How do I sign the CLA? 😅

cc @dadlerj

**Comment by dadlerj** [comment]
Hah, just added you @tsenart. Were you able to fill it out by clicking on the CI "Details" link, or was something broken?

**Comment by tsenart** [comment]
@dadlerj: I didn't see or click any details link. It seems to work now though!

**Comment by tsenart** [comment]
There some really strange errors in CI:

```

go: finding sourcegraph.com/sqs/pbtypes v0.0.0-20160107090929-4d1b9dc7ffc3
--
  | go: finding sourcegraph.com/sourcegraph/go-diff v0.0.0-20171119081133-3f415a150aec
  | go: finding sourcegraph.com/sqs/pbtypes v0.0.0-20180604144634-d3ebe8f20ae4
  | go: sourcegraph.com/sourcegraph/go-diff@v0.0.0-20171119081133-3f415a150aec: unexpected status (http://athens-athens-proxy/sourcegraph.com/sourcegraph/go-diff/@v/v0.0.0-20171119081133-3f415a150aec.info): 500 Internal Server Error
  | go: sourcegraph.com/sqs/pbtypes@v0.0.0-20160107090929-4d1b9dc7ffc3: unexpected status (http://athens-athens-proxy/sourcegraph.com/sqs/pbtypes/@v/v0.0.0-20160107090929-4d1b9dc7ffc3.info): 500 Internal Server Error
  | go: sourcegraph.com/sqs/pbtypes@v0.0.0-20180604144634-d3ebe8f20ae4: unexpected status (http://athens-athens-proxy/sourcegraph.com/sqs/pbtypes/@v/v0.0.0-20180604144634-d3ebe8f20ae4.info): 500 Internal Server Error
  | go: error loading module requirements
```

**Comment by keegancsmith** [comment]
Just fixed that, rebase to latest master. Context https://sourcegraph.slack.com/archives/C08JA8Q1H/p1544741061114200

**Pull request merged**
