### PR TITLE
web: Update insight search query description

### LINKED ISSUE #24023: Code insights backend: default to `archived:no` and `fork:no` filters on backend searches?
We have a strong POV (based on customer feedback + behavior so far) that customers expect insights to essentially match Sourcegraph search GUI. 

The Sourcegraph search GUI currently defaults to searching forks and archived repositories, however, because when you search explicitly using a `repo:` tag that's how it works ([see more context from](https://sourcegraph.slack.com/archives/C02BQB5CCFK/p1629138609041000) @slimsag there). 

Based on @slimsag 's [knowledge of why we default to _excluding_ forks and archive](https://sourcegraph.slack.com/archives/C02BQB5CCFK/p1629140492056800?thread_ts=1629139713.050900&cid=C02BQB5CCFK)s from sourcegraph GUI searches now, it makes sense to maintain this default in code insights – no reason to give you needless duplicates. 

One positive note/one note to maintain: explicitly passing `fork:` or `archived:` filters in the data series should always be honored (so when we change the default to these both being off, it should still be possible to manually set them on). This is how it works now, which is "positive" because it means even if customers don't want forks in their results, before we change the defaults we just have to advise them to include a `fork:no` and `archived:no` in their data series query. 
image

Example: [without archived+forks](https://k8s.sgdev.org/search?q=context:global+count:all+fork:no+archived:false+aardvark+lang:TypeScript+&patternType=literal) 32 results and [with archived+forks](https://k8s.sgdev.org/search?q=context:global+count:all+fork:yes+archived:true+aardvark+lang:TypeScript+&patternType=literal) 33 results

---

Edited by @unclejustin 

## Action Items

As per @felixfbecker's comment here https://github.com/sourcegraph/sourcegraph/issues/24023#issuecomment-900152127

1. Update help text with "This includes archived and forked repositories, add archived:no and forked:no to exclude them."

### PR DESCRIPTION
**Pull request by unclejustin**
image

Closes #24023

### CODE REVIEW

**Comment by unclejustin** [comment]
@felixfbecker can you give this a quick peek and make sure I understood the correct help text you were referring to?

**Comment by Joelkw** [comment]
@unclejustin you nailed the gist! Quick note, can we make these two sentences more obviously separate? (The "This" is unclear whether its referring to "this query" or "this repo: exclusion). 

I would suggest having it on its own line and changing it from a "do/do not" statement to a "tip" (since it doesn't break the queries like a repo: does). It's not "perfect UX" to have two concepts here but it's a great temporary solution until we figure this out more generally! (Screenshot because gh pr suggestions were being funky about the "deleted line" for me.) 
image

**Comment by unclejustin** [comment]
@Joelkw like this? I'm not SuperPumped™ about that dangling "above", but I don't think it's a deal breaker.

image

**Comment by Joelkw** [comment]
@unclejustin ah, two catches here! Thanks for checking 

1. **My fault entirely** I've got my booleans backwards – both `yes` **should be `no` ** (duh Joel, if you don't want archived files you say archived:no, not yes). You [can verify me here](https://sourcegraph.slack.com/archives/C02BQB5CCFK/p1629138609041000) if you want – the reason we're calling this out is that we a) want to advise you on how to match the search UI defaults (which exclude archived + forked repos) and b) want to do so before you wait a day for your queries to run and realize your mistake. 
2. Let's see if we can get rid of that dangle, also noticed it when I resized my screen. What about "Do not include the repo: filter; if needed, it will be added automatically." Because:
    1. does that get us to one line? 
    1. it occurs to me that if a user checks the "all repos" box, they may think to themselves "oh, I didn't include repos above, so this condition doesn't apply to me and I should add a repo: filter here!" but that's bad because that'll break the queries. Trying to make that clearer in the re-word!

**Comment by unclejustin** [comment]
image

Much better, thanks @Joelkw

**Comment by Joelkw** [comment]
@unclejustin one more catch here – I know this is confusing when they're next to each other – but it's **archived:** and **fork:** (not **forked:**)

https://k8s.sgdev.org/search?q=forked%3Ano+joel vs https://k8s.sgdev.org/search?q=context:global+fork:no+joel&patternType=literal

**Comment by Joelkw** [comment]
(Search syntax highlighting also makes it clear, but we don't yet have that on insights! Soon, I hear... :) ) 
image

**Comment by unclejustin** [comment]
> @unclejustin one more catch here – I know this is confusing when they're next to each other – but it's **archived:** and **fork:** (not **forked:**)
> 
> https://k8s.sgdev.org/search?q=forked%3Ano+joel vs https://k8s.sgdev.org/search?q=context:global+fork:no+joel&patternType=literal
> 
> (So the archived filter has the "ed" but the fork filter does not. I almost left search feedback about this yesterday but decided that, individually, if you were looking for just one and trying words, these terms make the most sense to me)

oooo good catch 🎉  fixed and setting to merge 😅

**Pull request merged**
