### PR TITLE
Simpler options menu in the browser extension

### PR DESCRIPTION
**Pull request by ijsnow**
There's a lot that went on here so I'd mostly like a review by testing but the most relevant code is in `src/libs/options/`.

The new options menu is behind a feature flag so we can merge this in (provided CI passes) and test by enabling the feature flag.

### CODE REVIEW

**Comment by chrismwendt** [comment]
@ijsnow Can you add instructions to the description?

- How to enable the feature flag (and what it is)
- What steps to take to test this and exercise functionality
- An image would be nice

**Comment by ijsnow** [comment]
The feature flag is `simpleOptionsMenu` and the `:cli` stuff was removed last week so theres only one way to enable feature flags. In the new options menu, click the settings icon and edit the JSON, in the old options menu, flip the check box.

I have the options menu behind a feature flag because there is a lot of changes in this PR and I'd prefer to fix any bugs, visual and functional, after this is merged in.

**Comment by ijsnow** [comment]
Did you manually remove the `featureFlags` item from the console? That's the only way I can repro it.

**Comment by chrismwendt** [comment]
Nope, I'm not sure why it was happening. The `featureFlags` item exists now.

**Comment by ijsnow** [comment]
Should be good now with https://github.com/sourcegraph/sourcegraph/pull/864

screen recording 2018-11-06 at 10 52 pm

**Comment by ijsnow** [comment]
I'm going to merge this soon so we can release/start testing

**Pull request merged**
