### PR TITLE
server: bump minor postgres versions

### PR DESCRIPTION
**Pull request by keegancsmith**
This should fix the docker build of server / e2e pipeline.

### CODE REVIEW

**Comment by mrnugget** [comment]
Nice try, copycat: https://github.com/sourcegraph/sourcegraph/pull/8442

**Comment by keegancsmith** [comment]
yours is wrong though :P we can't bump major versions without automatic migrations.

**Comment by mrnugget** [comment]
> yours is wrong though :P we can't bump major versions without automatic migrations.

I changed mine even before I saw yours! But my push failed because of missing `--force` :(

**Comment by keegancsmith** [comment]
#winning #closed #team #synergy

**Comment by mrnugget** [comment]
brb, printing "Thorsten pull requested first" shirts

**Pull request merged**
