### PR TITLE
Updated the logo

### LINKED ISSUE #51: Error: Cannot Render Binary File on C# repo
- Issue type: Bug report
- Sourcegraph version: sourcegraph.com

Steps to reproduce:

1. Go [here](https://sourcegraph.com/github.com/openhardwaremonitor/openhardwaremonitor@master/-/blob/GUI/NotifyIconAdv.cs) to NotifyIconAdv.cs of the OpenHardwareMonitor repo. Issue also happens with Utilities/EmbeddedResources.cs file in same repo, and Hardware/PInvokeDelegateFactory.cs, and Hardware/TBalancer/TBalancerGroup.cs. 
2. See "Error: Cannot render binary file".

My initial guess is the use of the DllImportAttribute in all the files except for EmbeddedResources.cs. But I'm not familiar enough with the implementation to know why that would be relevant.

image

### PR DESCRIPTION
**Pull request by kghopson**
Fixes https://github.com/sourcegraph/docsite/issues/51

### CODE REVIEW

**Comment by aileenrose** [comment]
I checked locally, the image is still the same.  Ping me tomorrow and I can help.  :)

**Comment by kghopson** [comment]
We talked via Slack. The logo did change (the capital S vs lowercase), but apparently the logo that's meant to replace the first one still needs docs on the end. She said she will talk to Victoria to get the logo fixed

**Comment by aileenrose** [comment]
We have two new logos, one for mobile in this folder:
https://drive.google.com/drive/folders/1qLmo7dlNbFKC6MY7xId-ywNzTn0YxE4L

**Comment by kghopson** [comment]
@aileenrose Okay, I added the latest logo from the folder

**Pull request merged**
