### PR TITLE
Make `dbtest.NewDB()` fast for real

### PR DESCRIPTION
**Pull request by camdencheek**
Alright. I've made a [couple](https://github.com/sourcegraph/sourcegraph/pull/21372) of [attempts](https://github.com/sourcegraph/sourcegraph/pull/21300) in the past to improve the performance and semantics of our `dbtest` package. 

Those PRs improved the speed of our database tests by migrating the database only once per package, doing incremental migrations, and running tests in parallel.

However, there are still some gotchas with the current package:
- The first call to `dbtest.NewDB()` in each package is slow because we run migrations once per package
- Test databases aren't tracked anywhere, so they don't get cleaned up
- The migrated template database isn't reused between test packages
- We don't have any good way to save a set of clean databases for use with transactions that leave the database clean
- Editing migrations doesn't cause test databases to be re-migrated, which is annoying when iterating while writing a migration

I think this PR is nearing endgame for the `dbtest` package. Here's an outline of what this PR does:
- It creates a new database `dbtest_pool` with three tables: `template_dbs`, `migrated_dbs`, and `schema_version`
- `schema_version` only contains a version of the schema for the `dbtest_pool` database. If that version is out of date, we blow away the database and recreate it with the new schema. This way we don't have to worry about migrations for this small utility database.
- `template_dbs` contains a list of databases that have had migrations run on them and can be used as a template for the test databases. Tests should never run directly against the template dbs. The template dbs are identified by a hash of the migrations used to create them. If a migration is added or changed, a new template db will be created.
- `migrated_dbs` contains a list of test databases that have been created from one of the template dbs. When a database is used by a test, it is marked as `claimed`. If, when the test is done, the database has been modified, it will be deleted.
- This creates the function `NewFastDB()`, which is equivalent to `NewDB()` except that it can more optimally reuse the migrated template DB between test processes.
- **Probably the most exciting part**: A new function `NewFastTx()` is created which returns a _transaction_ to a freshly migrated database. On test completion, the transaction is rolled back, leaving a still-fresh database that can be re-used. A returned transaction is always the only transaction pointing to a database, so there is never any risk of a deadlock between test transactions.
- Once per startup, we clean up any databases for migrations that haven't been used in more than a day. This is somewhat aggressive since the only cost is re-migrating the database once. 

This is only hooked up when the `USE_FAST_DBTEST` environment variable is set. Before cutting this over, I'd like to test this across a couple of migrations locally. In a few days, I'll rename `dbtest.NewFastDB()` to `dbtest.NewDB()` since it should be a drop-in replacement. Additionally, many uses of `dbtest.NewDB()` can be replaced with the much faster `dbtest.NewFastTx()`, which will be some followup work. 

Okay, so the numbers. On my machine:
- `dbtest.NewDB()` currently takes ~1s to to run the first time in each package, and ~120ms to run after that. The ~120ms is pretty unchanged, but the that extra second on the front mostly goes away with `dbtest.NewFastDB()` since we can reuse the template db between packages. 
- `dbtest.NewFastTx()` effectively takes 20ms, which is a big improvement, especially since we don't have to pay as much IO cost in recreating the database for every call.

I've segregated this into separate files so it's really easy to delete if we decide this approach won't work for us. It's certainly possible we decide the performance gains aren't worth the added complexity. However, I think it's worth integrating it a bit further and seeing what the performance improvements actually are before deciding the complexity is too much.

There is a bit of duplicated code right now, but I was struggling to deduplicate and maintain clarity, so I didn't for now.

### CODE REVIEW

**Comment by coury-clark** [comment]
> Probably the most exciting part: A new function NewFastTx() is created which returns a transaction to a freshly migrated database. On test completion, the transaction is rolled back, leaving a still-fresh database that can be re-used. A returned transaction is always the only transaction pointing to a database, so there is never any risk of a deadlock between test transactions.

Am I wrong in thinking that since Postgres transactions are opened in default read committed isolation, we would have to explicitly open these at a higher isolation level to avoid conflicts between concurrent tests? I'm not sure what the performance impact would be of that isolation level (repeatable read, probably?) on this strategy, but my guess is it should still come out ahead in most cases.

Or maybe I'm slightly misunderstanding, and this problem is avoided entirely by the db pool itself? In that you are serializing tests on the pool rather than on individual db instances?

**Comment by camdencheek** [comment]
> Am I wrong in thinking that since Postgres transactions are opened in default read committed isolation, we would have to explicitly open these at a higher isolation level to avoid conflicts between concurrent tests?

You are not wrong. In previous experiments, I attempted to replace all `dbtest.NewDB()` calls with transactions. This did not work for a number of reasons (deadlocks, isolation issues, etc.)

However, this approach is different because when `NewFastTx()` is called, the caller gets a transaction to _its very own database_. There will never be two transactions pointing to the same database. This means no conflict issues, isolation issues, or deadlocks. The reason this is still such a big win is after we roll back the transaction, the underlying database can be re-used for another transaction, or for another test that calls `NewFastDB()` (after which, the database will be thrown away). 

Does that answer your question?

**Comment by coury-clark** [comment]
> > Am I wrong in thinking that since Postgres transactions are opened in default read committed isolation, we would have to explicitly open these at a higher isolation level to avoid conflicts between concurrent tests?
> 
> You are not wrong. In previous experiments, I attempted to replace all `dbtest.NewDB()` calls with transactions. This did not work for a number of reasons (deadlocks, isolation issues, etc.)
> 
> However, this approach is different because when `NewFastTx()` is called, the caller gets a transaction to _its very own database_. There will never be two transactions pointing to the same database. This means no conflict issues, isolation issues, or deadlocks. The reason this is still such a big win is after we roll back the transaction, the underlying database can be re-used for another transaction, or for another test that calls `NewFastDB()` (after which, the database will be thrown away).
> 
> Does that answer your question?

Ah, got it, cool! So we have a connection pool of sorts where each connection points to a separate database instead. That's a pretty clever approach, I like it!

**Comment by camdencheek** [comment]
>  So we have a connection pool of sorts where each connection points to a separate database instead. 

Yes! 

> That's a pretty clever approach, I like it!

Thank you 😄 This problem has been bothering me for a long time (as evidenced by the previous PRs) and I finally had a breakthrough yesterday

**Review by bobheadxi — APPROVED** [review]
Looks exciting!

**Comment by camdencheek** [comment]
Alright, I cleaned this up a bit more, and converted a couple of tests to use the transactions just so there is _something_ exercising the new codepaths. I plan to use this locally for a while to suss out any issues, but then will make it default if things seem stable.

**Pull request merged**
