### PR TITLE
frontend: Instrument our internal http handlers

### PR DESCRIPTION
**Pull request by ryanslade**

### CODE REVIEW

**Comment by ryanslade** [comment]
Specifically I need this so I can track a possible performance improvement for the `.internal/repos/index` endpoint

**Comment by ryanslade** [comment]
@bobheadxi @tsenart @pecigonzalo Just want to resurface this on after the break :)

**Review by pecigonzalo — APPROVED** [review]
SGTM. I wonder if we should do it wrapper per wrapper like in https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/cli/http.go#L84-94

**Comment by ryanslade** [comment]
> SGTM. I wonder if we should do it wrapper per wrapper like in https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/cli/http.go#L84-94

Good idea, that's clearer

**Pull request merged**
