### PR TITLE
repos: add support for syncing Gitea repositories

### PR DESCRIPTION
**Pull request by keegancsmith**
We add support for fetching repositories from Gitea. It is behind the experimentalFeatures setting "gitea". This commit was modeled on the commit which added Pagure support.

Test Plan: Added unit tests which include recordings of interactions with a public gitea instance. Additionally manually tested the following conditions:

- against try.gitea and codeberg
- against local docker image
- ensure we do pagination correctly
- ensure we support tokens and private repos

Here are the respective code host configs. For the localhost version, I additionally tried the string "all" and then it did not sync the private repo. To run gitea locally I ran `GITEA_WORK_DIR=$HOME/gitea gitea`

``` jsonc
{
  "url": "https://try.gitea.io",
  "searchQuery": [
    // Set low limit to ensure we run our pagination code
    "?q=golang&topic=true&limit=2",
    "?uid=3&exclusive=true"
  ]
}

{
  "url": "https://codeberg.org",
  "searchQuery": ["?q=foot&archived=false&mode=source"]
}

{
  "url": "http://localhost:3000/",
  "searchQuery": [
    "?is_private=true"
  ],
  "token": "REDACTED",
}
```

Fixes https://github.com/sourcegraph/sourcegraph/issues/343

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.03 kb) | 0.03% (+3.95 kb) | 0.03% (+3.92 kb) | 0.14% (+1) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/k/gitea/compare-report.html;tab=live_object) for a full comparison between the commits bc74287 and c5181d0 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by mrnugget** [comment]
Hey! What’s the Why behind this? Adding another code host means more code, more docs, more support required. We want to make sure we only support what we _can_ support. And since Gitea is not on the shortlist of code hosts we want to add support for in the near future, this feels like adding unnecessary support burden on repo-management

**Comment by keegancsmith** [comment]
We can keep it hidden behind an experimental feature / beta support for a long time. Was relatively easy to add and is our most upvoted issue. Basically I wondered what it was like to add a code host these days after seeing it was the most upvoted issue. Was relatively easy to add. I understand the argument about support burden, and I'm unsure how to square that off in my head.

**Comment by keegancsmith** [comment]
I guess some extra motivation is we can add codehosts like https://codeberg.org to sourcergaph.com further increasing the corpus of OSS code we index that isn't gh.

**Comment by mrnugget** [comment]
I see. We’re very much focused on other things right now, and we plan to rework how the syncer works (and hope to get repo-updater finally removed). So ideally we’d keep the “old” code as small as possible before we’re in a better place. But @ryphil should weigh in here

**Comment by keegancsmith** [comment]
Agreed, but please take a look at the code as well to get a feeling for the actual introduction of complexity. btw it is pretty tiny. I know we have 23 files changed but most of those are tiny little things which are the same for every extsvc. The core change is really two things: the gitea client and the syncer which are both super tiny luckily. I imagine anything we do to make the syncer different here this client itself won't make more complicated vs all our other tiny extsvcs (gerrit, pagure, git src-serve)

**Comment by ryphil** [comment]
@keegancsmith - When you say it is the most upvoted, where is that list? From my knowledge, Gitea has not come up from any enterprise customer we have spoken to. 

The repo management team is focused on introducing code hosts used within the enterprise settings such as Perforce and we need to be mindful of introducing these with the expectation they'll be supported.

**Comment by mrnugget** [comment]
Looked at the code.

Hate to be this guy, but I‘d say we don‘t merge this in now. Our clear priority right now is strategic customers and fixing our shit, so in the spirit of Getting Better At Saying No and focusing, I don‘t think we should merge hundreds of lines just because.

**Comment by mrnugget** [comment]
Thanks for understanding! Appreciate it. 🙂

> I'm happy to follow-up and timebox like a day around tech debt to make things I noticed doing this better. Atleast while this stuff is fresh in my mind I should be able to make it so you don't have to change as many files / decouple things a bit / improve stuff. WDYT?

yes, please! I‘d hold off with larger-scale architectural refactoring, but any cleanups would be nice

**Comment by unknwon** [comment]
Drive-by:

Related with an ancient proposal: https://github.com/sourcegraph/sourcegraph/issues/5115

Also just an(other) idea: what if we (or have others to) have an API proxy that makes their APIs be GitHub-compatible?

**Comment by eseliger** [comment]
Hello! 

Is lack of official gitea support something that is currently a blocker to your usage of Sourcegraph?

**Pull request closed without merging**
