### PR TITLE
Add flakefile for `v4.2.0`

### PR DESCRIPTION
**Pull request by sanderginn**
Unblocks main build.

## Test plan
Build passes

### CODE REVIEW

**Comment by jhchabran** [comment]
@sanderginn could you share the context, that sounds pretty heavy handed and scary!

**Comment by sanderginn** [comment]
@jhchabran At least three are related to schema migrations. Only `TestIntegration` I'm not sure about:

### TestWebhooksHandler
```
_bk;t=1669800830591     |     [36mwebhooks_test.go[0m[35m:45[0m[90m: 
_bk;t=1669800830591     |         	Error Trace:	[36m/root/buildkite/build/sourcegraph/cmd/frontend/webhooks/webhooks_test.go[0m[35m:45[0m[90m
_bk;t=1669800830591     |         	Error:      	Received unexpected error:
_bk;t=1669800830591     |         	            	scanning webhook: ERROR: null value in column "name" violates not-null constraint (SQLSTATE 23502)
_bk;t=1669800830591     |         	            	(1) attached stack trace
_bk;t=1669800830591     |         	            	  -- stack trace:
_bk;t=1669800830591     |         	            	  | github.com/sourcegraph/sourcegraph/internal/database.(*webhookStore).Create
_bk;t=1669800830591     |         	            	  | 	[36m/root/buildkite/build/sourcegraph/internal/database/webhooks.go[0m[35m:95[0m[90m
_bk;t=1669800830591     |         	            	  | github.com/sourcegraph/sourcegraph/cmd/frontend/webhooks.TestWebhooksHandler
_bk;t=1669800830591     |         	            	  | 	[36m/root/buildkite/build/sourcegraph/cmd/frontend/webhooks/webhooks_test.go[0m[35m:39[0m[90m
_bk;t=1669800830591     |         	            	  | testing.tRunner
_bk;t=1669800830591     |         	            	  | 	[36m/root/.asdf/installs/golang/1.19.3/go/src/testing/testing.go[0m[35m:1446[0m[90m
_bk;t=1669800830591     |         	            	  | runtime.goexit
_bk;t=1669800830591     |         	            	  | 	/root/.asdf/installs/golang/1.19.3/go/src/runtime/asm_amd64.s:1594
_bk;t=1669800830591     |         	            	Wraps: (2) scanning webhook
_bk;t=1669800830591     |         	            	Wraps: (3) ERROR: null value in column "name" violates not-null constraint (SQLSTATE 23502)
_bk;t=1669800830592     |         	            	Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *pgconn.PgError
_bk;t=1669800830592     |         	Test:       	TestWebhooksHandler
```

### TestWebhookCount
```
_bk;t=1669800796548     |         	            	  | 	[36m/root/buildkite/build/sourcegraph/internal/database/webhooks_test.go[0m[35m:295[0m[90m
_bk;t=1669800796548     |         	            	  | testing.tRunner
_bk;t=1669800796548     |         	            	  | 	[36m/root/.asdf/installs/golang/1.19.3/go/src/testing/testing.go[0m[35m:1446[0m[90m
_bk;t=1669800796548     |         	            	  | runtime.goexit
_bk;t=1669800796548     |         	            	  | 	/root/.asdf/installs/golang/1.19.3/go/src/runtime/asm_amd64.s:1594
_bk;t=1669800796548     |         	            	Wraps: (2) scanning webhook
_bk;t=1669800796548     |         	            	Wraps: (3) ERROR: null value in column "name" violates not-null constraint (SQLSTATE 23502)
_bk;t=1669800796548     |         	            	Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *pgconn.PgError
_bk;t=1669800796548     |         	Test:       	TestWebhookCount
```

### TestWebhookList
```
_bk;t=1669800796558     |         	            	  | 	[36m/root/buildkite/build/sourcegraph/internal/database/webhooks_test.go[0m[35m:393[0m[90m
_bk;t=1669800796558     |         	            	  | github.com/sourcegraph/sourcegraph/internal/database.TestWebhookList
_bk;t=1669800796558     |         	            	  | 	[36m/root/buildkite/build/sourcegraph/internal/database/webhooks_test.go[0m[35m:316[0m[90m
_bk;t=1669800796558     |         	            	  | testing.tRunner
_bk;t=1669800796558     |         	            	  | 	[36m/root/.asdf/installs/golang/1.19.3/go/src/testing/testing.go[0m[35m:1446[0m[90m
_bk;t=1669800796559     |         	            	  | runtime.goexit
_bk;t=1669800796559     |         	            	  | 	/root/.asdf/installs/golang/1.19.3/go/src/runtime/asm_amd64.s:1594
_bk;t=1669800796559     |         	            	Wraps: (2) scanning webhook
_bk;t=1669800796559     |         	            	Wraps: (3) ERROR: null value in column "name" violates not-null constraint (SQLSTATE 23502)
_bk;t=1669800796559     |         	            	Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *pgconn.PgError
_bk;t=1669800796559     |         	Test:       	TestWebhookList
```

### TestIntegration

This one I'm not sure it's related to a migration, but it's failing on concurrent transactions.
```
_bk;t=1669800725115[90mSTART|     Service/ExecuteBatchSpec/success[0m
_bk;t=1669800725115     | [31mERROR[0m internal ]8;;vscode:[36m//file//root/buildkite/build/sourcegraph/internal/database/basestore/handle.go[0m[35m:207[0m[90m[36mbasestore/handle.go[0m[35m:207[0m[90m]8;; transaction used concurrently {"error": "transaction used concurrently"}
_bk;t=1669800725115     | [31mERROR[0m internal ]8;;vscode:[36m//file//root/buildkite/build/sourcegraph/internal/database/basestore/handle.go[0m[35m:207[0m[90m[36mbasestore/handle.go[0m[35m:207[0m[90m]8;; transaction used concurrently {"error": "transaction used concurrently"}
_bk;t=1669800725115[90mSTART|     Service/ExecuteBatchSpec/resolution_not_completed[0m
_bk;t=1669800725115[90mSTART|     Service/ExecuteBatchSpec/resolution_failed[0m
_bk;t=1669800725115[90mSTART|       Service/ExecuteBatchSpec/ignored/unsupported_workspace[0m
_bk;t=1669800725115     | [31mERROR[0m internal ]8;;vscode:[36m//file//root/buildkite/build/sourcegraph/internal/database/basestore/handle.go[0m[35m:207[0m[90m[36mbasestore/handle.go[0m[35m:207[0m[90m]8;; transaction used concurrently {"error": "transaction used concurrently"}
_bk;t=1669800725115     | [31mERROR[0m internal ]8;;vscode:[36m//file//root/buildkite/build/sourcegraph/internal/database/basestore/handle.go[0m[35m:207[0m[90m[36mbasestore/handle.go[0m[35m:207[0m[90m]8;; transaction used concurrently {"error": "transaction used concurrently"}
```

**Comment by unknwon** [comment]
I think we usually create a GitHub issue to make sure test owners to follow up for the fix and re-enable, and paste the link alongside the "skip" command.

**Comment by sanderginn** [comment]
@unknwon I was in the process of doing that when JH slammed on the brakes :D

**Review by davejrt — APPROVED** [review]

**Pull request merged**
