### PR TITLE
docs: ui refresh

### PR DESCRIPTION
**Pull request by ryan-blunden**
Builds on top of changes from #2564

Preview at http://newdocs.sgdev.org:5080/

Merge as part of 3.3 release process as this includes the version change to `3.3.0`.

### CODE REVIEW

**Comment by slimsag** [comment]
Slick, thanks for this! I'll take a look tomorrow :)

**Comment by francisschmaltz** [comment]
The nav bar covers the side bar

**Comment by francisschmaltz** [comment]
Screen Shot 2019-04-19 at 11 16 28 AM
Nav buttons on mobile are broken

**Comment by francisschmaltz** [comment]
Transparent nav menus should have a backdrop filter css property on them

```css
-webkit-backdrop-filter: saturate(240%) blur(14px);
     backdrop-filter: saturate(240%) blur(14px);
```

**Comment by francisschmaltz** [comment]
Font weight for headers should be `600`

**Comment by francisschmaltz** [comment]
The footer should be an exact copy of the footer on about.sourcegraph.com
about.sourcegraph.com (correct)
Screen Shot 2019-04-19 at 11 24 37 AM

docs:
Screen Shot 2019-04-19 at 11 23 55 AM

**Comment by francisschmaltz** [comment]
Screen Shot 2019-04-19 at 11 25 40 AM
Version number should be the full version number or `3.0.x` to communicate all 3.0.* versions

**Comment by francisschmaltz** [comment]
docs
After opening the version dropdown, clicking anywhere on the page toggles it. It should only be toggled on when clicking the dropdown or text and toggled off when clicking anywhere.

**Comment by francisschmaltz** [comment]
Screen Shot 2019-04-19 at 11 30 13 AM
Selected elements should have the same padding and border radius

**Comment by slimsag** [comment]
@ryan-blunden Given the extensive feedback here, I wouldn't be confident in addressing it all myself so what I am going to do is perform the 3.3 release without this change and we can follow up by merging this shortly after the announcement Mon. morning or over the weekend if important once we address all of the feedback here

**Comment by francisschmaltz** [comment]
Most of these issues are addressed in my PR at https://github.com/sourcegraph/sourcegraph/pull/2564 so we should follow up there

**Comment by ryan-blunden** [comment]
@francisschmaltz: Thanks for testing and reporting these.

I've tested more thoroughly on an iOS and Android simulator and I've fixed all but two of your changes:

> Version number should be the full version number or `3.0.x` to communicate all 3.0.* versions

This is not the way the current docs version chooser works so let's address it as a change for 3.4

> ui mismatch of selected list elements

This is a minor style change and can addressed in 3.4 as I don't want it to block this PR.

**Comment by sqs** [comment]
In "Site adminstration documentation", the `+` icon obscures the text:

image

**Comment by sqs** [comment]
If the page is short, the nav is cut off (eg at http://newdocs.sgdev.org:5080/user/repository):

image

**Comment by ryan-blunden** [comment]
> If the page is short, the nav is cut off (eg at http://newdocs.sgdev.org:5080/user/repository):
> 
> image

The nav is still scrollable but that's not necessarily obvious to the user. A solution could be making the page content height equal to the nav height.

**Comment by ryan-blunden** [comment]
> In "Site adminstration documentation", the `+` icon obscures the text:
> 
> image

I've shortened the link text but will file an issue to deal with this issue for 3.4

**Comment by francisschmaltz** [comment]
Other issues can be solved in 3.4 but the text overlap should be solved before merging

**Comment by francisschmaltz** [comment]
Screen Shot 2019-04-22 at 9 58 59 AM
You can currently scroll almost a full page-height's past the bottom of the footer. The footer should be stuck to the bottom of the page or the bottom of the content - whichever is lower.

**Comment by francisschmaltz** [comment]
The right hand nav is no longer in the correct place. it appears on the left hand side under the other page content
Screen Shot 2019-04-22 at 10 00 06 AM

**Comment by ryan-blunden** [comment]
Fixed the page nav issue.

**Pull request merged**
