### PR TITLE
dev: allow specify start.sh only and except via envvar

### PR DESCRIPTION
**Pull request by keegancsmith**
This allows me to always run with the same environment via direnv. For
example this is my setup to do docker free development :)

```sh
# Kill docker in dev with fire
export CTAGS_COMMAND=/Users/keegan/src/github.com/universal-ctags/ctags/ctags
export USE_SYNTECT_SERVER_FROM_PATH=t
export SRC_DEV_EXCEPT=grafana,prometheus,postgres_exporter
```

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
nice, will try that :)

**Review by mrnugget — APPROVED** [review]
That's cool!

**Comment by keegancsmith** [comment]
The symbols stuff doesn't work just yet, you also need #14037

**Comment by gbrik** [comment]
@keegancsmith i think this broke the default dev workflow, if i `enterprise/dev/start.sh` i get:
```
./dev/start.sh: line 169: SRC_DEV_ONLY: unbound variable
```
but if i `SRC_DEV_ONLY="" SRC_DEV_EXCEPT="" enterprise/dev/start.sh` everything runs fine

**Pull request merged**
