### PR TITLE
Add Cookiebot CSS for webapp

### PR DESCRIPTION
**Pull request by aileenrose**
Screen Shot 2020-05-26 at 7 11 03 PM

### CODE REVIEW

**Comment by felixfbecker** [comment]
@aileenrose how can I test this change?

**Comment by aileenrose** [comment]
> @aileenrose how can I test this change?

@felixfbecker -  The best way to view is via an incognito window.   The buildkite error is indicating a CSS issue with using nested id-selector.  I will have to redesign this component to work in both dark and light modes
I'll push out an update shortly.

**Comment by felixfbecker** [comment]
I see.

**Comment by felixfbecker** [comment]
According to this it's also possible to customize the HTML and CSS served by cookie bot directly: https://support.cookiebot.com/hc/en-us/articles/360003942753-Can-I-style-the-cookie-consent-banner-

Maybe that would be easier and better? E.g. we could give the buttons our `btn` classes to make them look consistent and rely on our global styles for text color, font sizing etc (which are all already defined in both the dark and the light theme)

**Comment by aileenrose** [comment]
> According to this it's also possible to customize the HTML and CSS served by cookie bot directly: https://support.cookiebot.com/hc/en-us/articles/360003942753-Can-I-style-the-cookie-consent-banner-
Yes, but that would affect about.sourcegraph.com as well.

@felixfbecker The cookiebot.scss failing on Buildkite.  Am I not allowed to use id selectors?  There are no classes.

**Comment by felixfbecker** [comment]
The Buildkite failure is because we generally forbid ID selectors in our webapp. If ID selectors are the only option, we'd need to add a comment `// stylelint-disable selector-max-id` at the top of the file.

> Yes, but that would affect about.sourcegraph.com as well.

Is there a reason I am missing why we would not want that? Afaik we have the same CSS classes in the about page (like `btn` etc) that we have in the webapp, so the template could work for both. Since every user will see this prompt, imo we should treat it with the same care for design and design consistency as we do any other UI in our webapp

**Comment by felixfbecker** [comment]
@rrhyne do you have thoughts on this?

**Comment by felixfbecker** [comment]
I customized the template, so this is no longer needed.

**Pull request closed without merging**
