### PR TITLE
convert external services tests to use new db mocks

### PR DESCRIPTION
**Pull request by camdencheek**
This PR converts the tests in `external_services_test.go` to use the new
database mocks.

I'm working towards creating a critical mass of example tests using the new database
mocks so the codebase moves in that direction independently of my intervention.
I'll keep making incremental progress towards deprecating the global mocks, but
I expect the PRs to slow down a bit from here, both because `database.DB` is spread
through the codebase enough that I can use the new mocks for new tests, and because
I expect to have less slack time moving forward.

### CODE REVIEW

**Review by efritz — APPROVED** [review]

**Comment by unknwon** [comment]
>I'm working towards creating a critical mass of example tests using the new database
mocks so the codebase moves in that direction independently of my intervention.
I'll keep making incremental progress towards deprecating the global mocks, but
I expect the PRs to slow down a bit from here, both because database.DB is spread
through the codebase enough that I can use the new mocks for new tests, and because
I expect to have less slack time moving forward.

Do we have a Code Insights dashboard that could tracking the current/overall progress of migrating all the existing global mocks? I would love to contribute some efforts here whenever needed.

**Comment by camdencheek** [comment]
> Do we have a Code Insights dashboard

That's a great idea! I just created a simple one that just tracks migration from global mocks to injected mocks and uses of `dbutil.DB` vs `database.DB` [here](https://k8s.sgdev.org/insights/dashboards/e498935a-c940-4b7c-ae1d-bded8a011d7c).

> I would love to contribute some efforts here whenever needed.

I'd welcome the help! There are still a large number of tests using the global mocks, so getting those migrated so we can remove the global mocks in `internal/database` is my current area of focus.

After that, I think we should think about how this will work with the enterprise-only stores. Right now, it's a little awkward since we don't want to import enterprise code from `internal/database`, so we can't just add methods that return enterprise stores on the `database.DB` type. I've got a few ideas here that I plan to write up for feedback, but I could use more heads thinking about the best way to approach this.

**Comment by camdencheek** [comment]
FYI: I updated the meta-issue [here](https://github.com/sourcegraph/sourcegraph/issues/26113#issuecomment-964769350) that I've been using to track all these changes

**Comment by unknwon** [comment]
> > I would love to contribute some efforts here whenever needed.
> 
> I'd welcome the help! There are still a large number of tests using the global mocks, so getting those migrated so we can remove the global mocks in `internal/database` is my current area of focus.

Sounds good, so I'll take the part to remove global mocks in `cmd/frontend/graphqlbackend` package. We can quick sync up again in Slack after that. WDYT?

**Comment by camdencheek** [comment]
> Sounds good, so I'll take the part to remove global mocks in cmd/frontend/graphqlbackend package. We can quick sync up again in Slack after that. WDYT?

Sounds great!

**Pull request merged**
