### PR TITLE
dev/ci: remove updater that is causing lockups

### PR DESCRIPTION
**Pull request by bobheadxi**
I have no idea what this is doing - the repos this thing targets don't seem used, and we use Renovate for deploy-sourcegraph-cloud right? This is causing 30+ min lockups in `main` that are triggering branch locks due to builds stalling for 45+ mins (which is the current threshold).

Closes https://github.com/sourcegraph/sourcegraph/issues/30150

### CODE REVIEW

**Review by jhchabran — APPROVED** [review]

**Comment by daxmc99** [comment]
Are these used for dogfood?

**Comment by bobheadxi** [comment]
@daxmc99 it seems to to target a nonexistent repo:

```
label: ':k8s: :arrows_counterclockwise: :dog: Trigger update pipeline for deploy-sourcegraph-dogfood-k8s-2'
```

**Comment by bobheadxi** [comment]
@ggilmore confirmd this is indeed used to roll out dogfood: https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1643134669095600?thread_ts=1643133699.094300&cid=C02FLQDD3TQ

**Comment by bobheadxi** [comment]
@daxmc99 https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/3853 will switch dogfood to use the same renovate config as Cloud, can you take a look? In the meantime, I will merge this PR for now because this has already happened twice, and see what we can do to align dogfood with Cloud. I imagine dogfood would be a good candidate for `sg ops`?

**Pull request merged**
