### PR TITLE
select: expose ctags kinds for select:symbol

### PR DESCRIPTION
**Pull request by stefanhengl**
This is more a proposal to start a discussion than a finished PR ;-)

I think `select:symbol.<kind>` could be better and this would be one way of doing it. 

We use ctags in Zoekt to detect and index symbols. However, right now, we don't expose ctags to the user. Instead we map a subset of the 345 ctags kinds (class, type, function, ... ) to [26 LSP kinds defined by Microsoft](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol). In some cases this was a poor fit, for example:

**ctags -> LSP:**
type -> class
macro -> function
union -> class
...

Most of the ctags kinds weren't mapped at all.

Check [this search](https://sourcegraph.com/search?q=context:global+lang:go+type:symbol+select:symbol.class+search&patternType=standard), where we see the consequence of "type" (ctags) being mapped to "class" (LSP).

This PR proposes to use ctags kinds directly.

### pros
- better guessability

### cons
- Changes the query language
- The list of proposed symbol filters in the UI is now 10x
- We have "seemingly" redundant filters, like `func` (Go) and `function` (Typescript)

### Alternatives
- We could just make a small change, extending the LSP definitions, every time we come across an odd case, like for types in Go. This would lead to something like an "LSP+"

### How to review
The core change is in `internal/search/result/symbol.go`. Most of the other changes follow based on what the compiler complains about.

## Test plan
- go test
- local testing

### CODE REVIEW

**Comment by tbliu98** [comment]
Quick thoughts:

I like the idea of making symbol kinds more precise than is allowed by sticking to the LSP symbol kinds. But, from a user perspective, I think always exposing all ctags kinds is too much. 

I feel like there should be a middle ground between sticking to the LSP definitions and using all ctags. I think creating some kind of "LSP+" as noted in the PR is an interesting idea, but I think the overhead of maintaining and updating that over time would be non-trivial.

I also wonder how many users would benefit from symbol kinds being more precise. I would guess that the for the vast majority of symbol searches, the symbol being searched for falls within one of the LSP symbol kinds. Exposing all ctags feels like it would mainly benefit a subset of users who are "super-power-users."

It would be _really_ cool if the range of `select:symbol.<kind>` suggestions narrowed based on what `lang:` filter is present, and broadened if no `lang:` filter is present.

**Comment by rvantonder** [comment]
In general I think this adds far too many symbol kinds with dubious value (`masterthesis`, `misc`, and many more). The autocompletion on `symbol.` wouldn't fit on most screens.  

It seems these are the main issues:

>  In some cases this was a poor fit, for example: `type -> class`

> better guessability / We have "seemingly" redundant filters, like func (Go) and function (Typescript)

I think manual effort here would go a long way: identify the ctag symbol kinds we feel are valuable and missing, then add those (e.g., `symbol.type`) and use the more accurate property. for redundant filters, we add an alias map. I think it's quite fine to extend the list/query for symbol kinds that seem missing and alias existing similar ones.

> This would lead to something like an "LSP+"

I'm not sure where the boundary is where we use precise symbols versus ctags right now, but the current select values apply to either precise or ctags. So, it isn't really that we need to stay exactly in line with LSP definitions, we can just expose a subset of non-LSP definitions, and we don't have to call this anything like `LSP+`, we can just say this is the set of symbol kinds we can search. If we wanted to explicitly case on on LSP versus ctag definitions, we can _also_ partition this with additional accessors:

- `select:symbol.ctag.<list of useful ctag names>`

- `select.symbol.lsp.<list of lsp names>`

- `select.symbol.<union of values in above two sets>`

**Review by rvantonder — CHANGES_REQUESTED** [review]
Managing PR review queue and popping this off. Feel free to comment / update to continue discussion.

**Comment by stefanhengl** [comment]
Thanks for all the feedback! I am closing this PR. I will not pursue this for now.

**Pull request closed without merging**
