### PR TITLE
Add tour snapshots

### PR DESCRIPTION
**Pull request by attfarhan**
Addresses https://github.com/sourcegraph/sourcegraph/pull/12972/files/732db55c9694a02c41cb7abda112b250fc867d35#r472387761

### CODE REVIEW

**Comment by felixfbecker** [comment]
Weird, I'm not seeing a Percy commit status. Maybe something is missing from CI config

**Comment by attfarhan** [comment]
Yeah I was confused about that. Where is Percy configured?

**Comment by felixfbecker** [comment]
Ah, we need to run the integration tests (in `pipeline-steps.go`) with `PERCY_ON` and using `percy exec` like here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/ci/e2e.sh#L48:65
Would you be down to include that change?

**Comment by felixfbecker** [comment]
@attfarhan I configured Percy in `main` so that should work now in CI 🙂

**Pull request merged**
