### PR TITLE
Embeddings: add time budget for search

### PR DESCRIPTION
**Pull request by camdencheek**
This adds an optional time budget for embeddings search. This is useful so clients can worry less about searching tons of embeddings by returning partial results if we exceed the time budget.

This is implemented as a separate "budget" rather than a "timeout" or via context cancellation because context cancellation and timeout implies "stop doing any more work," but the budget expiration is more of a "don't do extra, but return what you have so far" and we don't want to just blindly propagate context errors up the stack with no results.

Doing this before the merged keyword search / embeddings API because those changes have some dependencies on these.

## Test plan

Added a test and manually tested via the GraphQL API.

### CODE REVIEW

**Comment by jtibshirani** [comment]
@camdencheek I thought that instead of a time budget we were considering putting a limit on the number of repos searched. Maybe you give some context on how the final API will look?

A big challenge with using time budgets for search is that they can (1) produce non-deterministic results, and (2) hide relevance issues, because searches finish in a reasonable time regardless of whether they've considered enough data to give good results. Say it takes 6 sec to search through a repo's embeddings, but the client budget is 3 sec -- then we silently won't be considering 50% of the data every time... and somehow need to communicate that to clients/ users. (Instead in this case we should work on scaling the embeddings backend :))

**Comment by camdencheek** [comment]
> I thought that instead of a time budget we were considering putting a limit on the number of repos searched. 

Oh! My takeaway from our conversation was to implement both. We can't consistently rely on a repo limit because repos can be such variable sizes.

> and somehow need to communicate that to clients/ users

And we should! That's why I exposed the `budgetHit` in the response -- so we can indicate to users "this was not an exhaustive search."

Practically, I'm hoping that the budget will rarely be hit and we can improve embeddings scalability to continue to make that true. I plan to make a followup PR that collects some metrics on timings and budgets hits. 

WDYT? Should I just skip the budget portion entirely?

**Comment by jtibshirani** [comment]
Ah sorry for the miscommunication! I saw a more recent Slack message about using a hard limit and thought we settled on that.

My intuition is that we should go with a simple limit for now, and then look into adding budgeting as a follow-up, if run into perf issues. That way, we avoid a lot of potential conceptual and debugging complexity -- like having to alert the user that some portion of their data wasn't included (and what portion? how should they correct this?), and having to monitor metrics for whether we're ending searches too early and hurting relevance.

**Comment by camdencheek** [comment]
> My intuition is that we should go with a simple limit for now

Makes sense to me! I'll drop this PR then and we can implement it if there is a clear need instead

**Pull request closed without merging**
