### PR TITLE
Remove all tracking related code from the /-/editor rewrite endpoint and make editor and version optional

### PR DESCRIPTION
**Pull request by philipp-spiess**
Even though the extensions have removed all UTM params, they were still sending the `editor` and `version` request to the `/-/editor` API that is rewriting the URL to the sharable form.

Based on this version, however, the editor endpoint added a `utm_source` property as part of the rewrite:

Screenshot 2022-10-21 at 23 39 36

This could then still show up in the browser's URL bar and would be included if someone copies the link right away.

I did not notice this in my initial testing because it also seems that once the frontend code loads, `utm_source` is removed again:

https://user-images.githubusercontent.com/458591/197293149-1df778ad-ec70-463f-9bfa-87ec45479a39.mov

This PR also removes the need to pass an `editor` and `version` file so that we can remove that from the IDE extensions as well in a bit (we always have to support older instance versions for a bit unfortunlaty, so can't do this right away). 

I have also manually audited very grep result for `utm_source` in our repo now 😠 

## Test plan

Screenshot 2022-10-21 at 23 44 06

### CODE REVIEW

**Review by abeatrix — APPROVED** [review]
LGTM!

**Comment by sqs** [comment]
Thank you!

@olafurpg Give this a try once it's deployed.

**Comment by olafurpg** [comment]
I can confirm the `utm_source` parameter has been removed from the redirected URL. Thank you for the quick fix 🙏🏻 

I posted a message in https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1666603713012739 asking to remove one more redundant part of the URL

**Comment by philipp-spiess** [comment]
Fix for the follow-up here: https://github.com/sourcegraph/sourcegraph/pull/43345

**Pull request merged**
