### PR TITLE
ci: add go.mod to pipeline generator

### PR DESCRIPTION
**Pull request by asdine**
This adds a go.mod to the ci pipeline generator and modifies the `sg ci preview` command.
I had to modify the [CI step settings](https://buildkite.com/sourcegraph/sourcegraph/steps) for this to work (1. we might want to store them in the repository as a `pipeline.yml` ? 2. The modification [doesn't break main](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=ci%2Ftest-new-pipeline-steps))

### CODE REVIEW

**Comment by jhchabran** [comment]
Agreed with 1., storing the pipeline.yml in git would make such changes much easier and self contained.

**Comment by jplahn** [comment]
Do a clean up of some old PRs. Is this still needed?

**Comment by bobheadxi** [comment]
@jplahn I think this can be closed - IMO more trouble than it is worth, and it's a fairly lightweight module anyway

**Comment by asdine** [comment]
Closing this as this is not needed anymore

**Pull request closed without merging**
