### PR TITLE
updatecheck: Simplify return values

### PR DESCRIPTION
**Pull request by ryanslade**

### CODE REVIEW

**Comment by dadlerj** [comment]
Can you please test this? In particular, step 5 in https://about.sourcegraph.com/handbook/engineering/adding_ping_data#adding-data-to-pings

CC @ebrodymoore 

I know these are both `[]byte`s, but I believe that there's a reason for using a `RawMessage` here, and I'd like to confirm that BigQuery's ingestion doesn't fail on this modified format. 

E.g., please think about edge cases — what is an empty value for a []byte returned by json.Marshal vs. json.RawMessage, how are special characters like quotes handled/escaped, etc.

@ebrodymoore this is a case where we need better alerting on our data pipeline. I'd be happy to merge this if we'd get an alert if anything failed. We've missed a lot of issues in the past for long periods of time (and we don't know what we don't know — what if some % of instances just never show up and we never see the logs). Not urgent, but can you take this on? Perhaps work with someone from distribution on learning how to add alerting at each step in the process.

**Comment by ryanslade** [comment]
> Can you please test this? In particular, step 5 in https://about.sourcegraph.com/handbook/engineering/adding_ping_data#adding-data-to-pings
> 
> CC @ebrodymoore
> 
> I know these are both `[]byte`s, but I believe that there's a reason for using a `RawMessage` here, and I'd like to confirm that BigQuery's ingestion doesn't fail on this modified format.
> 
> E.g., please think about edge cases — what is an empty value for a []byte returned by json.Marshal vs. json.RawMessage, how are special characters like quotes handled/escaped, etc.

This change has no effect on what we return. The old code would marshal the data into a `[]byte` and then convert that into a `json.RawMessage`. The "conversion" doesn't change the actual data, just that it is now represented as a `json.RawMessage` type.

The new code does exactly the same thing, just with fewer lines. It marshals into a `[]byte` and because the return value of the method is `json.RawMessage` the conversion is happening there, it's just not explicitly written as a step in the code. 

On error, both the old and new code return a `json.RawMessage(nil)` which renders as json `null`: 
https://golang.org/src/encoding/json/stream.go?s=6976:7025#L253

**Comment by dadlerj** [comment]
LGTM 👍

**Comment by ebrodymoore** [comment]
> LGTM 👍

@dadlerj just to clarify, does this mean you're ok merging without alerting?

**Comment by dadlerj** [comment]
Sorry yep

**Comment by dadlerj** [comment]
@ebrodymoore can you add that to the analytics issue tracker?

**Pull request merged**
