### PR TITLE
Integration tests - limit worker processes

### PR DESCRIPTION
**Pull request by umpox**
Hopefully this will reduce our workerpool memory issues we're getting on buildkite

### CODE REVIEW

**Comment by umpox** [comment]
Merging this now as this could fix some immediate CI problems and is low-risk

**Comment by felixfbecker** [comment]
Does that mean we can remove the retry? (it may hide legit failures and increases CI time in failure cases...)

**Comment by limitedmage** [comment]
> Does that mean we can remove the retry? (it may hide legit failures and increases CI time in failure cases...)

Maybe? I'm still seeing the localStorage issue failure in some builds.

**Comment by limitedmage** [comment]
Filed #20379 for the localStorage issue, looking for a fix.

**Pull request merged**
