### PR TITLE
schema/site.schema.json: Auto format from editor

### PR DESCRIPTION
**Pull request by indradhanush**
Formatting changes only. No updates to schema itself.

Just setup LSP stuff for JSON and was adding a new config when my editor auto formatted this creating a bigger diff. 

Separate PR to sort that out.

This is also the format generated by some online JSON formatters, for example: https://codebeautify.org/jsonviewer/c6a219

## Test plan

- sg generate does not generate any new changes
- CI

### CODE REVIEW

**Review by sashaostrikov — APPROVED** [review]
It wasn't super clear for me that this PR only reformats a bunch of files, maybe next time just highlight in the description that it does formatting and doesn't change semantics :)

**Comment by indradhanush** [comment]
I added it to the first line in the description now. Good call out. 👌

**Comment by indradhanush** [comment]
Lol, sg lint in CI thinks I'm in the wrong. 😅

**Comment by indradhanush** [comment]
I guess our current formatter prefers the other way. No point in fighting the CI today.

**Pull request closed without merging**
