### PR TITLE
code monitoring: event logging

### LINKED ISSUE #17124: Code monitoring event logging
RFC: https://docs.google.com/document/d/1-Uj3Gl0-WrJsz_XH3QtHYl8jIf-cybeWE2ScZNCwWTY/edit#heading=h.trqab8y0kufp

This is a list of events that need to be logged in the code monitoring frontend, using EventLogger. 

- [ ] ViewCodeMonitorPage. This can be achieved by using `logViewEvent`. Example: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx#L62:32
- [ ] CodeMonitorCreated. This should include a `location` parameter, which specifies whether the code monitor is being created via the search results page or code monitoring form. Example: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/input/QueryInput.tsx
- [ ] CodeMonitorEmailLinkClicked. We can track this by adding a query parameter to URLs in our notification emails. We can parse for that query parameter when a user lands on a page, and if the query param exists, we'll log this event.

### PR DESCRIPTION
**Pull request by novoselrok**
Fixes #17124

### CODE REVIEW

**Review by quinnkeast — APPROVED** [review]

**Comment by novoselrok** [comment]
@lguychard @attfarhan Please review when you can, thanks!

**Review by lguychard — APPROVED** [review]
TS code LGTM. Maybe @stefanhengl can take a look at the Go code?

**Review by attfarhan — APPROVED** [review]
LGTM. Did you manage to test the functionality on the backend? In the past I'd just add a log in the [update check client](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/updatecheck/client.go?utm_source=VSCode-1.2.4#L461:34) to make sure the numbers came out as I expected. If you found a better way would love to hear it for future reference, if not no worries 😄

**Comment by novoselrok** [comment]
> LGTM. Did you manage to test the functionality on the backend? In the past I'd just add a log in the [update check client](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/updatecheck/client.go?utm_source=VSCode-1.2.4#L461:34) to make sure the numbers came out as I expected. If you found a better way would love to hear it for future reference, if not no worries 😄

I did the same manual check as you did, and I added a test in `internal/usagestats/code_monitoring_test.go` that should cover it for the future. I manually insert some events, aggregate them, and check the counts. I saw other `usagestats` perform the same test, so I copied it over.

**Review by stefanhengl — APPROVED** [review]
LGTM!

**Comment by ebrodymoore** [comment]
@novoselrok this PR needs to be reverted. I need to update the production database schema first ([steps here](https://docs.sourcegraph.com/dev/background-information/adding_ping_data#adding-data-to-pings)).

**Pull request merged**
