### PR TITLE
authz: cache duration metric for subrepo perms

### PR DESCRIPTION
**Pull request by keegancsmith**
I missed this in my previous commit, but we should also cache this metric. This provides another additional huge speedup of 58% on paths/s. Additionally I added a comment explaining why we cache WithLabelValues as well as providing a more useful help string for the metric.

```
name                 old time/op  new time/op  delta
FilterActorPaths-32  2.83ms ± 6%  1.78ms ± 3%  -36.97%  (p=0.000 n=10+9)

name                 old paths/s  new paths/s  delta
FilterActorPaths-32   1.77M ± 6%   2.80M ± 3%  +58.49%  (p=0.000 n=10+9)
```

Test Plan: go test

### CODE REVIEW

**Comment by keegancsmith** [comment]
Still lots of fruit to squeeze here, according to CPU profiles we are only spending ~15% of our time actually doing path matching (the BTree stuff below)... I think the next change I will look into is a bit of refactoring here so we don't have so much overhead per file check.

image

For others who want to join in the fun quickly, I've been running these commands:

```bash
cd sourcegraph/internal/authz
go test -bench=Filter -run=^$ -cpuprofile cpu.ppro
go tool pprof -call_tree -http=:8081 authz.test cpu.pprof
```

**Review by sashaostrikov — APPROVED** [review]
LGTM!

**Review by ryanslade — APPROVED** [review]
Nice!

**Comment by kopancek** [comment]
Should we make caching the new default to create prometheus metrics? At least for counters like this one. E.g. create a wrapper function around it? Because I think this is going to bite us in the future in other sensitive parts of code...

**Comment by sashaostrikov** [comment]
@kopancek Sounds like a great idea

**Review by mollylogue — APPROVED** [review]

**Comment by keegancsmith** [comment]
> Should we make caching the new default to create prometheus metrics? At least for counters like this one. E.g. create a wrapper function around it? Because I think this is going to bite us in the future in other sensitive parts of code...

TBH if you are measuring something where the overhead of measurements is bigger than what you are measuring... it isn't actually worth measuring. So I'd honestly opt to drop this metric instead. However, I think after the refactors I mentioned earlier in this PR, then there will be useful metrics to track where we only increase it a constant times per request. That would be more useful.

**Comment by sashaostrikov** [comment]
@keegancsmith `time.Now` definitely takes a significant runtime of `Permissions` function, dropping it (and therefore dropping the metric) is a nice speed-up. I don't remember using this metric very frequently, what would @ryanslade and @mollylogue say about it. Is it worth dropping for the sake of performance?

**Comment by ryanslade** [comment]
I think it makes sense to move the instrumentation higher up the stack. I don't think we need to be instrumenting in the `Permissions` method since it is often called in tight loops.

**Pull request merged**
