### PR TITLE
Add visitor tour with notebook links AB test

### PR DESCRIPTION
**Pull request by erzhtor**
Closes https://github.com/sourcegraph/sourcegraph/issues/36779.
## Tracking / event logs

image

## Screenshots
<details>

| BEFORE | AFTER |
| --: | :-- |
| image | image |
| image | image |
| image | image |
| when all steps are completed/clicked |  image |

</details>

## Recording

https://www.loom.com/share/f01275f9a44d40dba54c4b35332605e9

## Test plan
- `sg start dotcom`
- Open https://sourcegraph.test:3443/search?feature-flag-key=tour-visitors-notebook&feature-flag-value=true as not signed in user
- Go through tour

## App preview:

- [Web](https://sg-web-erzhtor-visitors-tour-with.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-zfcjckwxzo.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by thenamankumar — APPROVED** [review]

**Comment by a-bergevin** [comment]
I'm not able to to access the link `sourcegraph.test` for some reason. 

Looking at the screenshots though I think this is a bit strange - why do the numbers which from 1 -4 to 2-5?
image

Can we move the CTA button to the bottom of the square and have it say
"Register for a Free Account"

I think we want to emphasize that installing/signing up isn't a CTA to spend money here. Both are free options. It'd also be nice if we could emphasize somewhere what features that gives them. Maybe we can include a blue question mark next to the CTA that when you hover has a tooltip that says "Registration unlocks additional features like IDE integrations, browser extensions, saved searches and more" or something. Thoughts?

**Comment by erzhtor** [comment]
Thanks for the reviews @a-bergevin!

> I'm not able to to access the link sourcegraph.test for some reason.

Sorry for the confusion, it is should be run locally to access https://sourcegraph.test:3443.

> Looking at the screenshots though I think this is a bit strange - why do the numbers which from 1 -4 to 2-5?

Sorry, I forgot to update screenshots, it is fixed and will be always 1-4 order.

> and have it say
"Register for a Free Account"
> I think we want to emphasize that installing/signing up isn't a CTA to spend money here. Both are free options. It'd also be nice if we could emphasize somewhere what features that gives them. Maybe we can include a blue question mark next to the CTA that when you hover has a tooltip that says "Registration unlocks additional features like IDE integrations, browser extensions, saved searches and more" or something. Thoughts?

Great suggestion, thanks! Added and it looks like this.
<details>

image

</details>

> Can we move the CTA button to the bottom of the square

Regarding this, I thought specifically to put it on the top, because otherwise, it will be outside the visible area, and the user has to scroll down to see it. Also, this CTA is only visible only when the user finishes/clicks all steps, so I think it will not intervene with onboarding. WDYT?

**Comment by a-bergevin** [comment]
I didn't realize about the issue with scrolling, good point Erzhan. this looks great.

**Review by a-bergevin — APPROVED** [review]
Great improvements Erzhan, excited to see how users interact with this simple change.

**Pull request merged**
