### PR TITLE
Make fuzzy finder modal wide again

### PR DESCRIPTION
**Pull request by olafurpg**
The width of the fuzzy finder modal recently became very narrow. I wasn't able to track down the exact PR that impacted the width, but at some point the priority of the Wildcard `Modal` component overwrote the custom `width: 80vw` style we defined specifically for the fuzzy finder. This commit fixes the priority by use an `id` attribute instead of `class`.

Before
CleanShot 2022-09-19 at 15 30 39

After
CleanShot 2022-09-19 at 15 29 46

## Test plan

Manually tested the PR locally and posted screenshots in the PR description.

## App preview:

- [Web](https://sg-web-olafurpg-wider-fuzzy-finder.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-difkjjhsfe.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by olafurpg** [comment]
Added the 4.0 label since this is a bugfix, not a new feature.

**Comment by olafurpg** [comment]
> 3:1  ✖  Expected "#modal" to have no more than 0 ID selectors  selector-max-id

Any advice on how to fix the priority without using `id`?

**Review by valerybugakov — COMMENTED** [review]
It should not be happening — the Wildcard styles should have low priority than component styles. This bug surfaces the fundamental issue with CSS rules order in the production environment that is different from what we have in the development env. 

Let me look into the root cause. If the fix takes a lot of time, we can fix this side-effect to get it into the 4.0 release.

**Comment by olafurpg** [comment]
@valerybugakov have you been able to investigate the root cause of this issue?

**Review by valerybugakov — APPROVED** [review]
Hey @olafurpg, sorry for the delay! 

Here's [the Slack investigation thread](https://sourcegraph.slack.com/archives/C03JMRKLJHZ/p1663661972699879) if you're interested in more context and [the tracking issue](https://github.com/sourcegraph/sourcegraph/issues/42217) to address the underlying problem. I pushed the update to this PR that patches the side-effect.

**Comment by olafurpg** [comment]
Thank you @valerybugakov ! 🙏🏻

**Pull request merged**
