### PR TITLE
wolfi: cadvisor entrypoint

### PR DESCRIPTION
**Pull request by davejrt**
Fixes the cadvisor entry point, which was being split onto new lines, meaning we were dropping some metrics like memory as reported by @michaellzc. 

As part of the testing I tried just downloading the binary from github, rather than building it from scratch. That didn't turn out to the final solution so that's an OPTIONAL leave in, but to me seems like an easier approach than compiling ourselves. 

With a rebuild of the base image we're also now running cadvisor 0.47.3

Old (working):
```
            "Entrypoint": [
                ....
                "-enable_metrics=cpu,diskIO,memory,network",
                ....
            ],
```            

New (broken):
```
 "Entrypoint": [
                "/usr/bin/cadvisor",
                ....
                "-enable_metrics=cpu",
                "diskIO",
                "memory",
                "network",
                ....
```                

Closes https://github.com/sourcegraph/devx-support/issues/68

## Test plan

Tested on scaletesting.sgdev.org

image

vs sourcegraph.com

image

### CODE REVIEW

**Comment by willdollman** [comment]
The current wolfi-images/cadvisor.yaml actually uses the [chainguard cadvisor package](https://github.com/wolfi-dev/os/blob/main/cadvisor.yaml) rather than our built-from-source version. I switched it during development as Chainguard added cadvisor to their repo but didn't remove our custom config. 

If you want to switch back to our custom package, you can change [this line](https://github.com/sourcegraph/sourcegraph/blob/main/wolfi-images/cadvisor.yaml#L10) to `cadvisor@sourcegraph`

**Review by willdollman — APPROVED** [review]
See note about Sourcegraph vs Wolfi cadvisor package, but if it's working as-is then I guess it doesn't need to be changed. Thanks for investigating @davejrt 🎉

**Comment by davejrt** [comment]
> See note about Sourcegraph vs Wolfi cadvisor package, but if it's working as-is then I guess it doesn't need to be changed. Thanks for investigating @davejrt 🎉

Both with the same result...so it's better we continue using the chainguard version. They released 0.47.3 yesterday so I've rebuilt and upgraded us, retested and everything looks good. 

I'm removing the reference to the package to avoid any confusion going forward.

**Comment by michaellzc** [comment]
thank you!

can we backport this to 5.1 as well?

**Pull request merged**
