### PR TITLE
Cody pro icon was squashed in the upgrade banner

### PR DESCRIPTION
**Pull request by rrhyne**
The Cody PRO icon is now not squashed. 
The Cody PRO icon was squashed in the upgrade banner as it was incorrectly specified in Figma. 

## Test plan
I will manually test to ensure the icon is not squashed in width or height.

### CODE REVIEW

**Comment by rrhyne** [comment]
@chrsmith Q: does this NEED a changelog entry? Is the domain correct? There is no listing of domains in the template.

**Review by chrsmith — APPROVED** [review]
LGTM. For reference, this is what the "squashed" version looks like.

image

**Comment by chrsmith** [comment]
> @chrsmith Q: does this NEED a changelog entry? Is the domain correct? There is no listing of domains in the template.

I would just ignore it. This doesn't seem important enough to warrant calling out in the changelog.

**Comment by rrhyne** [comment]
Gracias!

**Pull request merged**
