### PR TITLE
Cody: Simplify command related UI

### PR DESCRIPTION
**Pull request by umpox**
## Description

| BEFORE             | AFTER             |
:-------------------------:|:-------------------------:
image | image
image | image
image | image (No change)

Uses [category](https://code.visualstudio.com/api/references/contribution-points#contributes.commands) to simplify how our commands appear in VS Code. Docs

> Presentation of contributed commands depends on the containing menu. The Command Palette, for instance, prefixes commands with their category, allowing for easy grouping. However, the Command Palette doesn't show icons nor disabled commands. The editor context menu, on the other hand, shows disabled items but doesn't show the category label.

## Test plan

Run locally
Check command related UX:
- Hover
- Menus
- Quick Picks

### CODE REVIEW

**Review by beyang — APPROVED** [review]

**Review by abeatrix — APPROVED** [review]

**Comment by toolmantim** [comment]
Yesss… love that you're cleaning this up.

Can we use this as a chance to move away from "Ask Cody" and just have either the following for the editor context menu:

- Cody
  - Fixup
  - Recipes
    - xxx
    - yyy
    - zzz
  - Touch

or:

- Cody
  - Fixup
  - Recipe: xxx
  - Recipe: yyy
  - Recipe: zzz
  - Touch

**Comment by toolmantim** [comment]
Also I don't think "Touch" is meant to appear in that editor context menu? I just tested, and it doesn't do anything for me.

**Comment by umpox** [comment]
> Also I don't think "Touch" is meant to appear in that editor context menu? I just tested, and it doesn't do anything for me.

Looks like a bug, should only show when inline assist is enabled - I'll fix that

**Comment by umpox** [comment]
image

**Comment by umpox** [comment]
Will merge to push this forward, feel free to comment if you want to change anything!

**Pull request merged**
