### PR TITLE
dev/gqltest/README.md: Update 1password link for aws credentials, fix typos and add suggestions

### PR DESCRIPTION
**Pull request by indradhanush**

### CODE REVIEW

**Review by unknwon — APPROVED** [review]
Are credentials from this 1password link actually work for you? If so, please merge. If not, please don't... there are abnormal things going on about AWS credentials right now.

**Comment by indradhanush** [comment]
Most of the tests pass, while some of them are skipped:

```
 ✘ dhanush@tpd  ~/sourcegraph/sourcegraph/dev/gqltest   ig/gqltest-update-one-password-link
 $ go test -long -v
2021/04/14 18:10:42 Site admin has been created: gqltest-admin
=== RUN   TestAccessToken
=== RUN   TestAccessToken/create_a_token_and_test_it
=== RUN   TestAccessToken/use_an_invalid_token_gets_401
--- PASS: TestAccessToken (0.04s)
    --- PASS: TestAccessToken/create_a_token_and_test_it (0.04s)
    --- PASS: TestAccessToken/use_an_invalid_token_gets_401 (0.00s)
=== RUN   TestExternalService
    external_service_test.go:15: Environment variable GITHUB_TOKEN is not set
--- SKIP: TestExternalService (0.00s)
=== RUN   TestExternalService_AWSCodeCommit
    external_service_test.go:72: Environment variable AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_CODE_COMMIT_USERNAME or AWS_CODE_COMMIT_PASSWORD is not set
--- SKIP: TestExternalService_AWSCodeCommit (0.00s)
=== RUN   TestExternalService_BitbucketServer
    external_service_test.go:127: Environment variable BITBUCKET_SERVER_URL, BITBUCKET_SERVER_TOKEN, or BITBUCKET_SERVER_USERNAME is not set
--- SKIP: TestExternalService_BitbucketServer (0.00s)
=== RUN   TestOrganization
=== RUN   TestOrganization/settings_cascade
=== RUN   TestOrganization/auth.userOrgMap
--- PASS: TestOrganization (3.48s)
    --- PASS: TestOrganization/settings_cascade (0.05s)
    --- PASS: TestOrganization/auth.userOrgMap (3.42s)
=== RUN   TestRepository
    repository_test.go:15: Environment variable GITHUB_TOKEN is not set
--- SKIP: TestRepository (0.00s)
=== RUN   TestRepository_NameWithSpace
    repository_test.go:78: Environment variable AZURE_DEVOPS_USERNAME or AZURE_DEVOPS_TOKEN is not set
--- SKIP: TestRepository_NameWithSpace (0.00s)
=== RUN   TestSearch
    search_test.go:18: Environment variable GITHUB_TOKEN is not set
--- SKIP: TestSearch (0.00s)
=== RUN   TestSiteConfig
=== RUN   TestSiteConfig/builtin_auth_provider:_allowSignup
--- PASS: TestSiteConfig (2.12s)
    --- PASS: TestSiteConfig/builtin_auth_provider:_allowSignup (2.12s)
PASS
ok  	github.com/sourcegraph/sourcegraph/dev/gqltest	5.764s
```

**Comment by unknwon** [comment]
Cool, but we should use https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/zpxz7vl3ek7j3yxbnjvh6utrei instead.

The current link changed in PR does not have credentials for AWS code commit.

**Comment by indradhanush** [comment]
I made some additional updates and have updated the PR title to reflect that.

**Review by unknwon — APPROVED** [review]
Thanks!

**Pull request merged**
