### PR TITLE
search results redesign: change display to grid

### PR DESCRIPTION
**Pull request by limitedmage**
This is required to implement #20776 (responsive layout for search results).

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
Not sure if it's relevant here, but I recently learned that CSS grids have a maximum member count. https://github.com/sourcegraph/sourcegraph/issues/20823

**Comment by limitedmage** [comment]
> Not sure if it's relevant here, but I recently learned that CSS grids have a maximum member count. #20823

Interesting! (and frustrating). Here we only have 3 components (sidebar, infobar and results) so we should be ok :)

**Comment by eseliger** [comment]
Good! Yeah indeed frustrating, the performance also gets really bad when getting close to the limit..

**Comment by felixfbecker** [comment]
Yeah it should be okay for almost anything, as long as it's not an unbounded dynamic number of elements and e.g. has infinite scroll pagination (think Pinterest)

**Pull request merged**
