### PR TITLE
dev: only support watchman

### PR DESCRIPTION
**Pull request by keegancsmith**
Maintaining three different ways to watch files leads to unneccessary
bugs. Instead lets pick just one, Watchman:

- Cross-platform
- Built for performance
- Battle tested
- Git integrates into it to speed up git status/etc
- Powerful expression language

### CODE REVIEW

**Comment by felixfbecker** [comment]
> Not against this change, but @mrnugget usually reported issues that I didn't have using chokidar.

I think it's good for that reason to standardize on one solution so those issues actually get fixed or we move everyone to an alternative that works better :)

**Comment by felixfbecker** [comment]
One note I'll add is that there are still non-watchman watchers running as part of the web build process that we can't change. Still in favor of this change though.

**Comment by keegancsmith** [comment]
Funny enough the issues that @mrnugget had where fixed by chokidar because chokidar wasn't watching everything! We have "watchdirs.sh" which is only supposed to list dirs with go files. We do this because watching node_modules is slow (unless you are watchman, so we don't limit watchman). However, it doesn't have our new top-level dir monitoring, which has go files in it. So we just wouldn't watch changes in it. The bug @mrnugget had was a bad build process which triggered changes in monitoring constantly. If everyone had the same watcher this wouldn't be so hard to debug :)

**Comment by keegancsmith** [comment]
> One note I'll add is that there are still non-watchman watchers running as part of the web build process that we can't change. Still in favor of this change though.

Yeah, every once in a while I need to do `yarn add fsevents` so gulp doesn't kill my computer. It would be amazing to switch to a watchman capable watcher in gulp.

**Comment by keegancsmith** [comment]
@sqs @chayim @gbrik I believe you all use linux. How easy is it for you to use watchman? Ubuntu doesn't seem to have a blessed package for some reason, but other distros like Arch do. Watchman provides static binaries, do those work for you? If so I can add some automation around installing a static bin: https://github.com/facebook/watchman/releases/tag/v2020.07.13.00

**Comment by sqs** [comment]
I am happy to use watchman.

**Pull request merged**
