### PR TITLE
improve extension registry list UI

### PR DESCRIPTION
**Pull request by sqs**
See commit messages for more details.

- Add categories and enabled/disabled filters to extension registry list.
- Remove extension titles; always use the extension ID. See the relevant commit message in this PR for the reason.
- Remove complexity around WIP extensions since #1508 will reduce the need for WIP extensions overall. (There were bugs here anyway; remote WIP extensions were still being shown even if `includeWIP=false` in the GraphQL query.)

Ready to review.

screenshot from 2019-01-02 03-22-17
screenshot from 2019-01-02 03-22-06

### CODE REVIEW

**Comment by sqs** [comment]
@ryan-blunden FYI extension no longer have titles (as of this PR); the extension ID is used. Check the PR description and relevant commit message for the reason why.

**Comment by francisschmaltz** [comment]
@sqs let’s go over this UI and refine it today

**Comment by francisschmaltz** [comment]
@sqs The category "Other" should show results for both the category "other" and for extensions that don't have a category.

**Comment by sqs** [comment]
@francisschmaltz Good call re: Other, pushed a commit to do that. Please approve or reject with changes requested if you have more.

**Comment by sqs** [comment]
@francisschmaltz 	Going to merge now, assuming you don't have any more things that block merging this.

**Pull request merged**
