### PR TITLE
Disable eslint autofix on save

### PR DESCRIPTION
**Pull request by philipp-spiess**
I am really unhappy with the current state of our frontend VS Code setup and it seems [others are too](https://sourcegraph.slack.com/archives/C01C3NCGD40/p1659431879407129). Whenever I save a file in VS Code, it takes a couple of seconds, sometimes even much longer depending on how many files I have open, to prettify the code and save the file. Most of the time is spent in eslint's autofix implementaiton.

The worst part is that a user config can not override a workspace config so the only workaround I have at the moment is to disable the `eslint` VS Code extension which of course removes all linter warnings in the editor, something I don't want either.

Take a look at this example. This is after a fresh VS Code restart and all I do is save the file. Notice how long it takes to run the eslint step:

https://user-images.githubusercontent.com/458591/194905685-e413b926-9509-486f-ba81-519ca97186ca.mov

I propose that we remove this default to improve the feedback cycle. People who want to enable this feature can still do this using user-level config files.

If you have auto-fixeable errors in a file, you can still use the VS Code command to fix them for you:

Screenshot 2022-10-10 at 17 59 37

## What is the impact?

I would argue that the impact of this change is rather small. There are already linter issues that are not auto-fixable that can stay unnoticed until the change hits CI. With this change, our autofixeable rules (and I am mainly looking at the import ordering?) would behave the same way now.

If there are shared concerns that this could slow us down because we push more invalid code to our CI servers, I suggest we look into setting up [husky](https://typicode.github.io/husky/#/) and force linter checks to pass in a pre-commit hook instead. This would only happen once per logical change and already be a great improvement to the current workflow.

## Test plan

I can haz instant save.

https://user-images.githubusercontent.com/458591/194906710-8c3970d2-d65d-4dd5-8763-dab0c3e4de24.mov

### CODE REVIEW

**Review by limitedmage — APPROVED** [review]

**Review by valerybugakov — APPROVED** [review]
It sounds good to me since it's possible to keep the auto-fix enabled via user settings, and I know it's disturbing for folks. It's sad that [it's still impossible to override workspace settings locally](https://github.com/microsoft/vscode/issues/40233). 

I propose waiting a day to two before merging this, so folks have more time to chime here if they have concerns about this change.

> If there are shared concerns that this could slow us down because we push more invalid code to our CI servers, I suggest we look into setting up [husky](https://typicode.github.io/husky/#/) and force linter checks to pass in a pre-commit hook instead. This would only happen once per logical change and already be a great improvement to the current workflow.

Sharing a bit of historical context here: there was a poll created by Jean du Plessis half a year ago and a discussion about this topic in the #dev-chat channel about pre-commit/pre-push hooks. The sentiment was that most people would find it annoying and would disable these hooks locally because their workflow is built around committing/pushing code frequently without interruptions.

**Comment by kopancek** [comment]
> It sounds good to me since it's possible to keep the auto-fix enabled via user settings, and I know it's disturbing for folks. It's sad that [it's still impossible to override workspace settings locally](https://github.com/microsoft/vscode/issues/40233).
> 
> I propose waiting a day to two before merging this, so folks have more time to chime here if they have concerns about this change.
> 
> > If there are shared concerns that this could slow us down because we push more invalid code to our CI servers, I suggest we look into setting up [husky](https://typicode.github.io/husky/#/) and force linter checks to pass in a pre-commit hook instead. This would only happen once per logical change and already be a great improvement to the current workflow.
> 
> Sharing a bit of historical context here: there was a poll created by Jean du Plessis half a year ago and a discussion about this topic in the #dev-chat channel about pre-commit/pre-push hooks. The sentiment was that most people would find it annoying and would disable these hooks locally because their workflow is built around committing/pushing code frequently without interruptions.

Maybe instead of being opinionated, we could provide 2 workflows and make everyone happy.

1. Workflow with the fix-on-save in VS Code. Make it possible to opt-out but keep the ESLint warnings
2. Workflow with the fix-on-pre-commit-hook. Make it possible to opt-in.

For me, I would prefer the pre-commit hook strategy, but am too lazy to set it up myself. Having this documented instead as a possible configuration would go a long way IMO. With the pre-commit hook it should be possible to modify the commit message, so that we can even track how many people use the hook vs the other strategy.

**Comment by philipp-spiess** [comment]
@kopancek I like the idea of giving others well defined workflows and let everyone choose what works for them.   

> Workflow with the fix-on-save in VS Code. Make it possible to opt-out but keep the ESLint warnings

The only problem with your approach is that right now, it's not possible to _opt-out_ from ES Lint fixing on saving because the VS Code workspace setting always takes precedence  over any user configs unfortunately 😞 

With `husky` (A popular library to set up pre-commit hooks) it seems that _opt-in_ has become the default though! https://blog.typicode.com/husky-git-hooks-autoinstall/ so if we add the setup for this, it would not automatically register for everyone working with our repo.

**Review by olafurpg — APPROVED** [review]
ESLint on save is making my workflow with VS Code close to unbearable. I regularly have to manually trigger "Format document" and "Save without formatting" to get a decent edit/debug feedback loop.

**Pull request merged**
