### PR TITLE
all: use httpcli.DefaultExternalClient instead of http.DefaultClient

### PR DESCRIPTION
**Pull request by keegancsmith**
This commit audited all our direct uses of http.Client and replaced them with
httpcli.DefaultExternalClient if they communicated with external services (ie
outside of cluster / docker container services). Additionally we also audited
uses of ctxhttp since passing in nil uses http.DefaultClient.

This can still miss some uses. In particular it will miss uses of
http.DefaultClient inside of dependencies. There are some likely sources of
this already, but this will get us most of the way there. We can follow-up
with these issues as they come up / with testing in the cycle.

Potential http.DefaultClient:

- openidconnect auth doesn't take in a client, it looks like it relies on the
  client created by oauth2. This is a general oauth2 problem due to the
  encouragement of using a custom Transport.
- AWS CodeCommit.

Note: We introduce httpcli.Client to simplify the call sites which currently
use ctxhttp or http.DefaultClient.

Part of #71 
Part of #4652

### CODE REVIEW

**Comment by tsenart** [comment]
> openidconnect auth doesn't take in a client, it looks like it relies on the
client created by oauth2. This is a general oauth2 problem due to the
encouragement of using a custom Transport.

I feel like supporting custom CAs with OAuth providers is going to be a frequent things (i.e. login with GitHub Enterprise).

How hard would it be to solve this?

**Comment by keegancsmith** [comment]
> > openidconnect auth doesn't take in a client, it looks like it relies on the
> > client created by oauth2. This is a general oauth2 problem due to the
> > encouragement of using a custom Transport.
> 
> I feel like supporting custom CAs with OAuth providers is going to be a frequent thing (i.e. login with GitHub Enterprise).
> 
> How hard would it be to solve this?

See my latest comment in https://github.com/sourcegraph/sourcegraph/issues/4652. It needs to be solved to fix that issue. I plan on tackling it more tomorrow.

**Comment by tsenart** [comment]
Found a rogue while investigating our `httputil.CachedClient`: https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/internal/app/go_symbol_url.go#L78

**Comment by keegancsmith** [comment]
> Found a rogue while investigating our `httputil.CachedClient`: [/cmd/frontend/internal/app/go_symbol_url.go@`master`#L78](https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/internal/app/go_symbol_url.go#L78) [](/sourcegraph/sourcegraph/blob/HEAD@{2020-01-29T14:40:12Z}/cmd/frontend/internal/app/go_symbol_url.go#L78)

Thanks, pushed a commit to remove httputil.CachedClient and make everyone go through DefaultExternalClient (which was already backed by the same cache)

**Comment by slimsag** [comment]
Silly and definitely hacky question, but: http.DefaultClient is a global var.. what if we `http.DefaultClient = httputil.Client`?

**Comment by sfllaw** [comment]
@slimsag Your idea to replace `http.DefaultClient` with a more paranoid version is not a bad idea, since that would prevent third-party libraries from doing the wrong thing.

**Comment by keegancsmith** [comment]
Closing due to age, can resurrect when we tackle this again.

**Pull request closed without merging**
