### PR TITLE
Don't detach merged/closed changesets on update

### LINKED ISSUE #8981: Existing merged changesets are “closed” and hence removed from the tracking campaign
- **Sourcegraph version:** master
- **Platform information:** Dogfood

#### Steps to reproduce:

1. Have a campaign with some changesets already merged
2. Run src-cli again to create the newest patches (I wanted to expand the scope)
3. See them marked as "to be closed" (pr for a "unchanged" tab is up)
4. Click update, see them disappear

#### Expected behavior:

The 4 merged changesets would have been skipped, retaining them in the campaign.

#### Actual behavior:

The 4 merged changesets were interpreted as "to be closed" and are removed from the campaign. Lost tracking progress of them.

### PR DESCRIPTION
**Pull request by eseliger**
This closes #8981 by doing two things:

When we previously updated a Campaign that had a patch set with patches for repositories A, B, C to use a patch set with patches for repositories A, B and D, we would remove the patch for repository C and if a changeset was already created on the code host, we would close it and detach it from the campaign.

Now we check whether the changeset we're about to close & detach has already been merged or closed (signifying a success!) and if so, we don't detach it, but keep it around.

That means you can keep re-running an `src action exec` command with the same action definition while the changesets in the campaign are being merged or closed. If a repository doesn't produce a patch anymore (because the requested changes have been accepted!) you can still update your campaign with the new patch set without the merged changeset being lost.

The other thing this PR does is to change our "clean up of old patch sets"-behavior. Previously we deleted old PatchSets that weren't attached to a Campaign. Now we  delete PatchSets that are either (a) not attached to a campaign and (b) don't have patches that are associated with ChangesetJobs/Changests that are associated with another campaign.

We had to add the second condition, (b), because if we keep closed/merged changesets around a Campaign can now contain changesets that originate from different PatchSets.

### CODE REVIEW

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
@sourcegraph/campaigns-core I've updated the PR description to include an explanation of _why_ this is a desired change and what that changes in our data model. Please read it before/after/while looking at the code.

I've also thought some more about whether we might run into problems when we have a Campaign with Changesets originating from multiple PatchSets, but I don't think there's a problem with that (besides this association being slightly implicit, which we should fix if we need to use it more in the future).

Let me know if you can think of a problem resulting from the changes here.

And a question: should we introduce a proper many-to-many association between Campaign<->PatchSets before we do this?

**Comment by eseliger** [comment]
> And a question: should we introduce a proper many-to-many association between Campaign<->PatchSets before we do this?

This looks like a good improvement to me, also performance-wise probably much better

**Comment by christinaforney** [comment]
Thinking about the complexities of this data, and what we're actually wanting to represent to the user, the mental model that comes to mind for me as follows (WARNING: I have no idea what I'm talking about when it comes to the current implementation, good properties of data modeling, performance, etc, etc., but I found this thought exercise helpful when thinking about the information users care about):

After creating the first PatchSet (a list/collection of ChangeSets), the PatchSet seeds a map/collection of stacks, where each stack is an individual ChangeSet with a key of a unique representation for that repository (perhaps just repo name? this gets trickier when thinking about multiple patches per repo e.g. monorepo cases). 

When a new PatchSet is created from the CLI, each Patch/ChangeSet is pushed onto the stack (so the top of the stack is always the current state of the campaign). If no new patch is generated for that change, the stack is retained. This way, the first item in each stack represents the current state. of the Campaign. In this representation, a PatchSet is a temporary piece of information, only used to update the campaign current state.

Something that feels important to distinguish is when a patch is not included due to a scopeQuery change (closure of the patch, but should remain as part of the "history") vs. a patch not being included because the user is simply trying to add a new ChangeSet in a faster way (with reduced scopeQuery). 

I think the take away for me when thinking about what I care about as a user is:
- The collection of changes that has been applied to this Campaign. I should be able to filter out ChangeSets that have been "removed"/closed due to reduced scopeQueries vs. active changes that are still open, or that have been successfully merged.
- State/status of each change, able to filter on this
- MAYBE: Review ChangeSets as they were added, similar to reviewing commits individually on a PR. I'm not convinced this is a requirement, but thinking about the review process of a PR, this feels like a nice property. I'm not sure how my map/stack model works in this case, perhaps it breaks that model.

**Comment by mrnugget** [comment]
Thanks for the input. I think I understand what you mean, although I cannot see yet how it translates to practice, have to think about this some more.

But there's one clear thought I already have: it sounds like it would help us and the users if we separate the current `updateCampaign` into two operations: `updateCampaign` switches the PatchSet (and works as it currently does) and `mergeCampaignPatchSets` which would merge the patches/changesets contained in two PatchSets.

**Comment by mrnugget** [comment]
I've been thinking about this some more (spoiler: I've not yet reached a conclusion), but I've played around with illustrations of this that I think I should keep here.

#### A Campaign with a single PatchSet

This is the status quo, what every non-manual campaign right now looks like:

Screen Shot 2020-03-26 at 08 07 50

**Note**: the `Campaign` points to the `PatchSet`, but it also has associations to the Changesets.

#### Keep merged/closed changesets around

If we merge the changes _in this PR_ and keep the merged/closed changesets (originating from the PatchSet 1) around and update the campaign to have a new PatchSet, it will look like this:

Screen Shot 2020-03-26 at 08 11 45

**Note**: the `Campaign` points to the new `PatchSet`, but it has associations to _all `Changesets`_.

The tricky point, that I'm unsure about, is that we now have an implicit association to the old `PatchSet 1`.

But my current thinking is that this shouldn't be a problem, since we only need the `Campaign->PatchSet` association for two things:

1. Detecting whether the Campaign is a manual campaign or not (`manual = campaign.PatchSetID == 0`)
2. When a Campaign has been created as draft, we need the association to later create the necessary ChangesetJobs that create Changesets.

**Comment by mrnugget** [comment]
I decided that it's fine if we keep this "implicit" for now. We still have the `ChangesetJob` associations and the `Campaign` pointing to `Changesets`. It changes the meaning of `Campaign.PatchSetID` from "the patch set that has the patches underlying all these changesets" to "the current patch set that has patches for the current state of all these changesets".

**Pull request merged**
