### PR TITLE
Don't display the context CTA banner for org members

### PR DESCRIPTION
**Pull request by artemruts**
### Description

Don't display the context CTA banner if a user is an org member.
[Link](https://sourcegraph.atlassian.net/browse/CLOUD-114) to the issue in Jira.

### Tests

The fix was tested locally with two users and a demo organization.

### CODE REVIEW

**Review by novoselrok — APPROVED** [review]

**Review by limitedmage — APPROVED** [review]
This is related to #25270 (FYI @benvenker)

**Comment by benvenker** [comment]
ok, thanks for the heads up @limitedmage. Does it impact that PR at all?

**Comment by limitedmage** [comment]
> ok, thanks for the heads up @limitedmage. Does it impact that PR at all?

Possibly. Do we want to show the (now dismissable) CTA even to users that are part of orgs? Maybe @artemruts  or @ryphil can chime in.

**Comment by benvenker** [comment]
@ryphil opinions on this?

**Comment by ryphil** [comment]
If the user is part of an org, which has code hosts & repositories connected, then no we do not want to show it to them. The only time we want to show this is if the user does not have personal repos connected and is not part of an org with code connected. 

cc: @quinnkeast

**Comment by limitedmage** [comment]
@ryphil  Thanks, this makes sense. I'll keep this functionality (don't show CTA at all, even a dismissable one, for org members) for when I get back to #25270.

**Pull request merged**
