### PR TITLE
internal: Add base configuration object

### PR DESCRIPTION
**Pull request by efritz**
This PR introduces an abstract store that has allows an idiom over `env.Get` in a way that makes an application's envvars easily searchable and contained in a single place.

This is a bit of an experiment to see if this does buy us some code clarity in application setup. This will be first used in the code intelligence and user-code-execution services. This is a pre-step to the effort tracked in https://github.com/sourcegraph/sourcegraph/issues/14822.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
Cool, interesting approach!

**Review by pecigonzalo — APPROVED** [review]
Nice! This is making ways into this stale (my bad) [RFC](https://docs.google.com/document/d/1s0gdKsCNegym6z1HGB53i3U_2HGwZwyvjiuv5HNWmH8/). This looks really clean, but I wonder if there is an opportunity to use one of the existing libs for this as well.

**Review by mrnugget — APPROVED** [review]

**Comment by efritz** [comment]
@pecigonzalo Maybe, but this is a very low-effort change to experiment with and will save a bunch of local vars in the interim regardless if we keep this long-term. I'd like to move to something standard and I'm just using this as a stop-gap/learning experience.

If you do revisit this RFC in the future please remember this (and tag me in if you'd like).

**Review by keegancsmith — COMMENTED** [review]
LGTM. Neat.

Drive by comment since you are improving this ancient package :) An idea I have used elsewhere is to make it possible to set the `os.Environ()`. Useful for tests. You can then end up using the same "API" that our users would use for configuring.

**Pull request merged**
