### PR TITLE
test: move to dev/ci

### PR DESCRIPTION
**Pull request by bobheadxi**
Feel free to reject, but this seems like a better home for it - helps avoid top-level repo clutter maybe?

### CODE REVIEW

**Review by daxmc99 — CHANGES_REQUESTED** [review]
Can we delay on merging this? 
My cluster-qa work currently depends on some of these scripts being in these locations 😅

**Comment by bobheadxi** [comment]
Sure thing @daxmc99 !

**Review by unknwon — APPROVED** [review]
👍

**Review by davejrt — APPROVED** [review]
LGTM, once you've resolved merge conflicts and re-factored what Dax is working on I like this idea. No need to seek any further approvals from me

**Comment by bobheadxi** [comment]
I'm going to let https://github.com/sourcegraph/sourcegraph/pull/15678# get merged first and resolve the conflicts on this end before merging this

**Review by daxmc99 — APPROVED** [review]
LGTM, happy to help move these over as well

**Pull request merged**
