### PR TITLE
Add audit logs for invalid token events

### PR DESCRIPTION
**Pull request by willdollman**
Add audit logs for the following cases related to token-based auth:

* Invalid token is used
* Sudo access token used by user who is no longer an admin

- [ ] Need to find a solution for the case where the `sourcegraphAnonymousUid` cookie isn't set when an invalid token is used. Currently this effectively allows the user to disable database-based logging simply by removing the cookie. [e7f9ea8](https://github.com/sourcegraph/sourcegraph/commit/e7f9ea86c6a1da34c45d03dffa6db59d9481e41e#diff-cc3dcdfaa1b2810734330a8eb47a065edbcc443af9fa6aae2cde7b0e6839cd0eR90) contains a temporary workaround, but we either need to:

* remove the db constraint
* populate AnonymousUserID [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@will-michal/sudo-access-token/-/blob/internal/database/security_event_logs.go?L114) when UserID and AnonymousUserID are both zero values

This problem also affects failed sign-in attempts.

## Test plan

- [x] Unit tests
- [ ] Manual testing

### CODE REVIEW

**Review by vrto — COMMENTED** [review]
So far, so good; I think we should also log any case when this succeeds? Something like, "Will impersonating Michal for this request?"

**Comment by willdollman** [comment]
> So far, so good; I think we should also log any case when this succeeds? Something like, "Will impersonating Michal for this request?"

I've augmented @unknwon's existing logging of successful token use to grab the following fields, this should cover most cases:

```
 id |          name           |      url      | user_id | anonymous_user_id | source  |                                                           argument                                                           |  version  |           timestamp
----+-------------------------+---------------+---------+-------------------+---------+------------------------------------------------------------------------------------------------------------------------------+-----------+-------------------------------
 34 | AccessTokenImpersonated | /.api/graphql |       2 |                   | BACKEND | {"sudo_user": "userForImpersonation", "sudo_user_id": 3, "token_subject_user_id": 2, "token_subject_user_name": "will-test"} | 0.0.0+dev | 2022-11-28 14:43:44.553007+00
```

I've started adding unit tests, but hitting a crash when running the tests which is what's causing the CI to fail. The crash is triggered when `db.SecurityEventLogs().LogEvent(...)` is called on lines [93](https://github.com/sourcegraph/sourcegraph/pull/44843/files#diff-cc3dcdfaa1b2810734330a8eb47a065edbcc443af9fa6aae2cde7b0e6839cd0eR93) and [161](https://github.com/sourcegraph/sourcegraph/pull/44843/files#diff-cc3dcdfaa1b2810734330a8eb47a065edbcc443af9fa6aae2cde7b0e6839cd0eR161) but isn't triggered by the call on [175](https://github.com/sourcegraph/sourcegraph/pull/44843/files#diff-cc3dcdfaa1b2810734330a8eb47a065edbcc443af9fa6aae2cde7b0e6839cd0eL175).

 I initially thought it could be caused by r.Context() not being set or a nil parameter, but haven't been able to narrow it down by excluding those. Should be reproducible on the current branch when running `auth.go:TestAccessTokenAuthMiddleware` if anyone else wants to take a look.

**Comment by vrto** [comment]
@willdollman the https://github.com/sourcegraph/sourcegraph/pull/44843/commits/7238ca4dbe1757b33331875fbd027258966b5e30 has fixed the failing tests

**Review by vrto — APPROVED** [review]

**Comment by willdollman** [comment]
After discussing with @vrto, merging the schema changes is a lot of effort (they're not backcompatible so would need to span two releases).
As we want to get this branch merged faster, created https://github.com/sourcegraph/sourcegraph/pull/44951 which contains changes up to that point.

I'll close this PR; we can revisit it if we think it's worth modifying the schema in the future.

**Pull request closed without merging**
