### PR TITLE
web: Fork cloud sign-up page for VS Code users

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes https://github.com/sourcegraph/sourcegraph/issues/29703

__**🚨 This is a preview PR until we have a final copy**__

The idea here is that for users coming via the VS Code extension, we likely want a custom copy. 

Right now, we are already a couple of different versions of the sign-up flow:

- A regular cloud signup flow
- A regular on-prem signup flow (which does not contain marketing copy)
- ~~A `signup-optimized` flow that is currently being tested.~~ We can disregard this [as it's going away soon](https://github.com/sourcegraph/sourcegraph/pull/29728/files)
- An `?invitedBy=username` that is being worked on by @slimsag 

For the VS Code sign-up copy I decided to make a cleaned up fork of the regular cloud signup flow. I decided to remove the invited by logic because when users get an invite link, it should take precedence over their VS Code referrer. I also ignored the on-prem signup since it currently does not have any marketing text so an adjustment for VS Code won't make sense.

Screenshot 2022-01-18 at 16 25 42

The new page can be opted into by including `vs-code` in the query search params, e.g.:

```
https://sourcegraph.test:3443/sign-up?vs-code=1&showEmail=true
```

## Outstanding Issues

- I need access to the Figma account so that I can extract the proper VS Code icon.
- The subtitle breaks to two lines with the font that we use on the signup page. Should we change something there?

### CODE REVIEW

**Comment by jjinnii** [comment]
@philipp-spiess Designs available[ here](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1638%3A4590)! Let me know if you have any questions. This variation of the signup page is taken from the user invitations work that Rob has done -- perhaps there's some code reuse opportunity there?

**Comment by philipp-spiess** [comment]
@jjinnii I updated the PR. Take a look at the screenshots and the outstanding questions I mentioned above.

**Comment by philipp-spiess** [comment]
Updated the icon as well now.

**Comment by jjinnii** [comment]
@philipp-spiess Thanks for the fast work on this! 

- On the Figma account, I don't believe you need any special permissions to create a Figma account with your SG email and access my files. But I'm not entirely sure, so I'd reach out to #it-tech-ops in Slack about it if you are running into issues!
- Once you do get access to Figma, please check the width of the container for the copy on the left. I increased it so that we shouldn't have the subtitle wrap to two lines anymore!
- Please also double-check the line height, as the font seems a bit more densely packed than mine.

Thanks again!

**Review by slimsag — APPROVED** [review]

**Comment by philipp-spiess** [comment]
> Looks pretty good to me @philipp-spiess ! I am currently working on simplifying the Cloud Signup page code a lot, should make it easier to integrate this one into that (so we only have one copy) soon.

Awesome! Yeah my idea is to do a quick and dirty fork first and then we can clean up afterwards when the changes stabilize. I'll "rebase" (= fork again) with your changes though since the design seems pretty similar to what we want here.

**Comment by philipp-spiess** [comment]
I updated the fork to contain @slimsag's responsive fixes from https://github.com/sourcegraph/sourcegraph/pull/29896 and changed some margins/paddings/etc to better match the Figma. I also updated the path to use `?editor=vscode`

@jjinnii Do you mind taking another look? 🙂 

Screenshot 2022-01-19 at 14 41 52

**Comment by jjinnii** [comment]
@philipp-spiess Looks great! Just one super small nit -- maybe the container size for the copy is slightly wider than my designs, but for the second bullet point for "Reference and re-use code from all your projects without leaving VS Code", can we have the line wrap after "without"?. Other than that looks perfect!

**Review by jjinnii — APPROVED** [review]

**Comment by philipp-spiess** [comment]
Screenshot 2022-01-19 at 17 06 10

There we go 🙂

**Pull request merged**
