### PR TITLE
web: update generate license description

### PR DESCRIPTION
**Pull request by unknwon**
Add the link to our handbook for the complete guide of license tags.

Before:

Screen Shot 2020-10-12 at 4 53 22 PM

After:

Screen Shot 2020-10-12 at 5 09 48 PM

Part of #14022

### CODE REVIEW

**Comment by unknwon** [comment]
Could anyone from @sourcegraph/web guide me how to update the snapshot in web tests? 🙇

**Comment by felixfbecker** [comment]
@unknwon see https://docs.sourcegraph.com/dev/background-information/testing#react-component-snapshot-tests :)

The instructions are also printed at the bottom of the build output:

```
Snapshot Summary
  › 1 snapshot failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.
```

https://buildkite.com/sourcegraph/sourcegraph/builds/76113#76c465c2-04e1-4aad-bab0-adcef2b41d8a/101-952

(this is not meant as "RTFM", just to make it easier for you to find it in the future and not be blocked :))

**Comment by unknwon** [comment]
> @unknwon see [docs.sourcegraph.com/dev/background-information/testing#react-component-snapshot-tests](https://docs.sourcegraph.com/dev/background-information/testing#react-component-snapshot-tests) :)
> 
> The instructions are also printed at the bottom of the build output:
> 
> ```
> Snapshot Summary
>   › 1 snapshot failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.
> ```
> 
> [buildkite.com/sourcegraph/sourcegraph/builds/76113#76c465c2-04e1-4aad-bab0-adcef2b41d8a/101-952](https://buildkite.com/sourcegraph/sourcegraph/builds/76113#76c465c2-04e1-4aad-bab0-adcef2b41d8a/101-952)
> 
> (this is not meant as "RTFM", just to make it easier for you to find it in the future and not be blocked :))

@felixfbecker Thanks! Was looking for a README in the directory and tried `yarn gulp generate` but no luck 🤦‍♂️

**Comment by dadlerj** [comment]
Can we list the full list of "meaningful" tags here? I see we have `dev` and `true-up`, but there are more, and it would be helpful to list them for the sake of consistency if multiple people will be generating licenses.

I'm picturing a table or bulleted list below that first paragraph. What do you think @unknwon ?

**Comment by unknwon** [comment]
> Can we list the full list of "meaningful" tags here? I see we have `dev` and `true-up`, but there are more, and it would be helpful to list them for the sake of consistency if multiple people will be generating licenses.
> 
> I'm picturing a table or bulleted list below that first paragraph. What do you think @unknwon ?

@dadlerj Ideally I would love to delete the first paragraph entirely... and guide everyone to use the linked handbook page as the single source of truth for what tags to put. This page is very easy to overlook and it seems very outdated to me.

If I understand correctly, as we evolve our tiers, the list of tags that is up-to-date or even appropriate is complicated and different from time to time, and in the worst case it is an ever growing list. For example, `enterprise-0` could have a different list of add-ons than `enterprise-1`.

In case you missed, the sister PR to update our handbook is here: https://github.com/sourcegraph/about/pull/1747

**Comment by dadlerj** [comment]
Thanks, I did miss that other update!

>@dadlerj Ideally I would love to delete the first paragraph entirely... and guide everyone to use the linked handbook page as the single source of truth for what tags to put. This page is very easy to overlook and it seems very outdated to me.

Please delete it then, I agree with you.

**Review by dadlerj — APPROVED** [review]
Approved with comment

**Pull request merged**
