### PR TITLE
symbols: replace pcre lib with a Go function

### PR DESCRIPTION
**Pull request by chrismwendt**
Previously, the symbols service used [sqlite3-pcre](https://github.com/ralight/sqlite3-pcre) for the `REGEXP` function, which doesn't work on a Mac M1 (not entirely sure why, but `REGEXP` is simply not found at query time) and requires a lot of incantations to fit into Sourcegraph's build processes.

After this change, the symbols service will register a Go function that uses the [regexp package](https://pkg.go.dev/regexp) for the `REGEXP` function in SQLite queries. Surprisingly it's **3.5x faster** ⚡ I verified it works on a fresh Ubuntu machine and on a Mac M1.

## Benchmark results BEFORE

```
[nix-shell:~/sourcegraph]$ env CGO_ENABLED=1 go test -v -bench=. -test.run=sdfsfd ./cmd/symbols/internal/symbols
goos: linux
goarch: amd64
pkg: github.com/sourcegraph/sourcegraph/cmd/symbols/internal/symbols
cpu: Intel(R) Xeon(R) CPU @ 2.30GHz
BenchmarkSearch
BenchmarkSearch/indexing_go-langserver@391
BenchmarkSearch/indexing_go-langserver@391-16         	      30	  36438669 ns/op
BenchmarkSearch/indexing_moby@6e5
BenchmarkSearch/indexing_moby@6e5-16                  	       1	2924069406 ns/op
BenchmarkSearch/searching_go-langserver@391_^sortedImportRecord$
BenchmarkSearch/searching_go-langserver@391_^sortedImportRecord$-16         	    1473	    770081 ns/op
BenchmarkSearch/searching_go-langserver@391_1234doesnotexist1234
BenchmarkSearch/searching_go-langserver@391_1234doesnotexist1234-16         	    1562	    787795 ns/op
BenchmarkSearch/searching_moby@6e5_^fsCache$
BenchmarkSearch/searching_moby@6e5_^fsCache$-16                             	    1495	    796550 ns/op
BenchmarkSearch/searching_moby@6e5_1234doesnotexist1234
BenchmarkSearch/searching_moby@6e5_1234doesnotexist1234-16                  	    1530	    766157 ns/op
PASS
ok  	github.com/sourcegraph/sourcegraph/cmd/symbols/internal/symbols	9.396s
```

## Benchmark results AFTER

```
[nix-shell:~/sourcegraph]$ env CGO_ENABLED=1 go test -v -bench=. -test.run=sdfsfd ./cmd/symbols/internal/symbols
REGISTER
goos: linux
goarch: amd64
pkg: github.com/sourcegraph/sourcegraph/cmd/symbols/internal/symbols
cpu: Intel(R) Xeon(R) CPU @ 2.30GHz
BenchmarkSearch
BenchmarkSearch/indexing_go-langserver@391
BenchmarkSearch/indexing_go-langserver@391-16         	      31	  35134148 ns/op
BenchmarkSearch/indexing_moby@6e5
BenchmarkSearch/indexing_moby@6e5-16                  	       1	2885099785 ns/op
BenchmarkSearch/searching_go-langserver@391_^sortedImportRecord$
BenchmarkSearch/searching_go-langserver@391_^sortedImportRecord$-16         	    5198	    219659 ns/op
BenchmarkSearch/searching_go-langserver@391_1234doesnotexist1234
BenchmarkSearch/searching_go-langserver@391_1234doesnotexist1234-16         	    4472	    232458 ns/op
BenchmarkSearch/searching_moby@6e5_^fsCache$
BenchmarkSearch/searching_moby@6e5_^fsCache$-16                             	    4720	    237519 ns/op
BenchmarkSearch/searching_moby@6e5_1234doesnotexist1234
BenchmarkSearch/searching_moby@6e5_1234doesnotexist1234-16                  	    5226	    218710 ns/op
PASS
ok  	github.com/sourcegraph/sourcegraph/cmd/symbols/internal/symbols	8.828s
```

PCRE was added in https://github.com/sourcegraph/sourcegraph/pull/2418

cc @sourcegraph/distribution

### CODE REVIEW

**Comment by chrismwendt** [comment]
@rvantonder Could you skim the diff to see if this breaks comby in a way I might not know about? I verified it works with regexes on a fresh Ubuntu machine:

CleanShot 2021-09-24 at 23 57 01@2x

comby didn't work on my Mac M1. In case you're curious what the error was:

```
[searcher] INFO structural search, repo: github.com/sourcegraph/src-cli
[searcher] INFO running comby, args: Printf(:[_])  -json-lines -f (64 file patterns) -match-only -jobs 4 -matcher .go -zip /tmp/searcher-archives/764b74b4512d0ee61ff005b9331b1336b956f15440d5caf3594582fdb6d8f83b.zip
[searcher] ERROR failed to execute comby command, error: Uncaught exception:
[searcher]
[searcher]   (Failure "Not supported")
[searcher] Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
[searcher] Called from Pipeline.run in file "lib/app/pipeline/pipeline.ml", line 304, characters 37-91
[searcher] Called from Dune__exe__Main.base_command_parameters.(fun) in file "src/main.ml", line 263, characters 6-32
[searcher] Called from Core_kernel__Command.For_unix.run.(fun) in file "src/command.ml", line 2453, characters 8-238
[searcher] Called from Base__Exn.handle_uncaught_aux in file "src/exn.ml", line 111, characters 6-10
```

**Comment by rvantonder** [comment]
will review later, but what version of comby? latest release works on M1 via brew update. However, the same latest version is not yet compatible with Sourcegraph or tests. So its basically safe to assume this is OK. if you want tests to pass locally then either: don't run on M1 machine (since AFAIK, we dont support Sourcegraph on M1 officially yet anyway?) or disable comby tests (set some CI env var i forget, which will skip them)

**Comment by chrismwendt** [comment]
I'm on comby 1.7.0. `comby --help` works, so the binary at least starts, but some functionality doesn't work (from my previous comment). Yeah, M1 is not really supported, so it's OK that it doesn't work on an M1 👌

**Comment by rvantonder** [comment]
OK we can debug that separately some time. brew should be installing the M1 compatible version...

**Review by keegancsmith — APPROVED** [review]
This is amazing! I can't believe it is faster, wtf. Is it faster on non-m1 as well?

The amount of hacks and weird things we do in our builds due to this CGO dep is large, so I'm so happy to see it go away. Thank you again!

**Comment by keegancsmith** [comment]
> PCRE was added in #2418

I love that you are the author of that PR :P The circle of life.

**Review by eseliger — APPROVED** [review]

**Comment by chrismwendt** [comment]
@keegancsmith It's faster on non-m1 (that's the benchmark). I actually can't test the speed of PCRE on an M1 because I couldn't get the it to work 😅

**Comment by daxmc99** [comment]
Awesome! Great work!

**Pull request merged**
