### PR TITLE
Add notes on file permission in gitserver

### PR DESCRIPTION
**Pull request by abeatrix**

### CODE REVIEW

**Comment by abeatrix** [comment]
@davejrt is there any more info we should add?

**Comment by davejrt** [comment]
We should have an example of what the permissions should be. If you actually set this up and document fully how to do that...I think this would be very helpful to customers.

**Comment by abeatrix** [comment]
Please ignore me, 700 was working 😓

**Review by daxmc99 — APPROVED** [review]

**Review by davejrt — APPROVED** [review]

**Comment by abeatrix** [comment]
Thank you for your help on this @davejrt @daxmc99 👏

**Pull request merged**
