### PR TITLE
Add CTA for sales on rate limit errors.

### PR DESCRIPTION
**Pull request by rrhyne**
## Test plan

Manually test the response to ensure:
* the link to sales properly sends the user to the about site in the same browser window
* the text displays in two paragraphs

### CODE REVIEW

**Review by kalanchan — APPROVED** [review]
only thing I'm unsure of is the anchor tag, not sure if it will render in the UI properly. we can try this and see if it works

**Review by eseliger — COMMENTED** [review]
This message will also render on non-dotcom instances, where this wording feels a bit off. I think the best way to augment that would be to special case 429 errors in the cody client and render something nicer, like what you suggested here.

**Review by eseliger — COMMENTED** [review]
@rrhyne this has been stale for a while, can we close it?

**Comment by eseliger** [comment]
Closing as it's become stale. Feel free to reopen.

**Pull request closed without merging**
