### PR TITLE
internal/gitserver: Improvement  to RepoInfo method

### PR DESCRIPTION
**Pull request by indradhanush**
This PR makes two functional improvements to the RepoInfo client method and a semantic one. 

The functional improvements are:

1. Limit length of map to max number of shards
2. Do not hide response body for failed HTTP reqs

The semantic improvement is:

1. Add comment and rename shard -> repoInfoReq

**Note to reviewers**

It's recommended to look at each commit sequentially to view the changes in an isolated way. This should make it easier to understand the changes in this PR vs looking at the entire diff at the same time.

The pain point with no response body for non 200 errors was first observer in this [customer issue](https://github.com/sourcegraph/customer/issues/1049) which also led to the other improvements as I was reading and understanding this code.

## Test plan

- Added tests. 
- Did end to end UI testing. Applied the following diff to the code to simulate 500 HTTP response.

image

**UI should now look like this:**

image

**VS current behaviour without this PR:**

image

## Note for time travellers

**Without strings.TrimSpace**

image

**With strings.TrimSpace**

image

### CODE REVIEW

**Review by mollylogue — APPROVED** [review]
lgtm, thx for the detailed breakdown of the changes

**Review by sashaostrikov — APPROVED** [review]
LGTM!

**Review by mollylogue — COMMENTED** [review]
Quick question: have you tested what this looks like in the error scenario? Does the error now show up in the UI in addition to the status code?

**Comment by indradhanush** [comment]
> Quick question: have you tested what this looks like in the error scenario? Does the error now show up in the UI in addition to the status code?

@mollylogue I noticed that this method doesn't have any tests at all. I'm holding off merging until I write some tests. Yeah, at the moment only the 500 status code is seen.

**Comment by indradhanush** [comment]
@mollylogue Now added tests with what we expected to see in the UI. I haven't tested the UI itself but the test should be sufficient since we're not changing the core behaviour.

**Comment by sashaostrikov** [comment]
> I haven't tested the UI itself but the test should be sufficient since we're not changing the core behaviour.

@indradhanush I suggest spending a bit extra time and test the UI too, more thorough testing is something we can do better as a team, especially taking BB Projects sync project's lessons learned into consideration 😅

**Review by sashaostrikov — COMMENTED** [review]
New changes LGTM!

Additional thanks for adding tests 🙏

I've added a note about testing the UI as well, for the sake of testing completeness :)

**Comment by indradhanush** [comment]
@sashaostrikov That's a good callout! Thank you. The UI test was fruitful as well. Made a small tweak to the error message and error message handling. 😄

**Pull request merged**
