### PR TITLE
Migrate to ESLint 🔧

### LINKED ISSUE #2461: Use ESLint
ESLint has TypeScript support and is the future of TypeScript linting (TSLint will eventually be deprecated). It has a bunch of rules (like not referencing `this.state` in `setState()`) that I would like to enable because they keep coming up in code review.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #2461 🎉 

Very excited about this one as ESLint has support for a bunch of new rules that we can now check for that often came up in code reviews, e.g. referencing `this.state` inside `setState()` and many more.

I recreated our TSLint config in https://github.com/sourcegraph/eslint-config and made https://github.com/sourcegraph/tslint-config/tree/eslint contain only the few TSLint rules ESLint doesn't have.

Migratingwas more work than expected but it's a huge improvement to our codebase, e.g. finally refactored all usages of async-unsafe `componentWillReceiveProps()` to `componentDidUpdate()`, removing unused state properties, ...

Also like the better configurability of ESLint - configuring rules for glob patterns or overriding severity in comments.

I also noticed we were not typechecking our code in CI! So this fixes it. 

cc @JoshuaKGoldberg

### CODE REVIEW

**Comment by felixfbecker** [comment]
It would be great to get a timely review from someone frontend (currently @chrismwendt or @sqs) since this very prone to merge conflicts. At the same time I could have messed up a refactor somewhere. :)

**Comment by JoshuaKGoldberg** [comment]
Heh, the GitHub editor keeps freezing up my Chrome tab because of how many files there are _(have you considered splitting out source file changes where possible?)_.

But, this brings up a super cool idea: would it have been convenient to have a tool that converts `tslint:disable` comments to `eslint-disable` equivalents? 😮

**Comment by felixfbecker** [comment]
> But, this brings up a super cool idea: would it have been convenient to have a tool that converts tslint:disable comments to eslint-disable equivalents? 😮

Yes, 100%!

**Comment by felixfbecker** [comment]
> Do we no longer disallow submodule imports?

We didn't allow submodule imports with TSLint because a package's `index.ts` should export the public API. Importing from deep files is importing internals - if we do that then we cannot confidently evolve our packages anymore. This has been a problem with internal packages in the past.

> Is ?(x) valid glob syntax? See lsif/server/package.json

Yep, see https://github.com/isaacs/node-glob#glob-primer. What do you mean with "See lsif/server/package.json"?

**Pull request merged**
