### PR TITLE
repo-updater: properly register Bitbucket Server repositoryQuery migration

### LINKED ISSUE #3591: repo-updater 3.3 auto migration: Bitbucket Server external service missing `repositoryQuery` after upgrade
See #3594 for details (ctrl+f on that page for this issue #)

### PR DESCRIPTION
**Pull request by slimsag**
Fixes #3591 
Helps #3594

Test plan:

### CODE REVIEW

**Comment by slimsag** [comment]
(please take ownership of this PR)

**Comment by tsenart** [comment]
Wow, thanks for helping out with this!

**Comment by tsenart** [comment]
The CHANGELOG was already updated:

```
The new required bitbucketserver.repositoryQuery setting in Bitbucket Server external service configuration allows you to use Bitbucket API repository search queries to select repos to be synced. Existing configurations will be migrate to have it set to ["?visibility=public", "?visibility=private"] which is equivalent to the previous implicit behaviour that this setting supersedes.
```

**Comment by keegancsmith** [comment]
@tsenart this makes me think we need to much more logic out of `main.go` and put it somewhere we can test it easily. For example in this case the migrations to run could instead be a slice of migrations in the `repos` package. Then we don't need to export each migration function + we can update our tests to just run all the migrations rather than specific migrations.

**Comment by tsenart** [comment]
@keegancsmith: The issue is that each migration needs to be instantiated with different dependencies. What we might be able to do is to factor out the whole repo updater to a `repos.Updater` type that runs all the stuff in main, in a more testable way.

**Pull request merged**
