### PR TITLE
Cody: Inline assist remove ID label

### LINKED ISSUE #54048: Cody: Inline assist don't show the ID with prompt and response
In Inline Assist, a dummy ID is shown, like `Me #56321565632` with the response and prompt. It would be good not to show this ID with the text.

CC: @abeatrix @toolmantim WDYT?

iScreen Shoter - Code - 230623175035

### PR DESCRIPTION
**Pull request by deepak2431**
This PR fixes #54048. 

## Test plan
Tested it manually. 
All the tests have passed. 

Before:

iScreen Shoter - Code - 230627131437

After:
iScreen Shoter - Code - 230627131222

### CODE REVIEW

**Comment by deepak2431** [comment]
@abeatrix @philipp-spiess Can I have a review please?

**Comment by philipp-spiess** [comment]
@deepak2431 Hmm did you look into this API that Tim linked in the issue that is using the label to infer the ID?

https://github.com/sourcegraph/sourcegraph/blob/e46aea53002bac8c9c1999e52ad2e21016e2061d/client/cody/src/services/InlineController.ts#L131-L134

**Comment by deepak2431** [comment]
@philipp-spiess Yeah, I looked into that. What I understood is that it is using the label as ID from the threads, not from the individual comment. But I think maybe I am wrong there. Will look into it again once here!

**Comment by deepak2431** [comment]
You're right @philipp-spiess we can't remove the label as that is being used as thread ID. Can we use the ID property from the comment directly?
Will wait for @abeatrix to confirm this!

**Comment by sqs** [comment]
<kbd>*semi-automated message*</kbd> Cody's source code has moved to a new repository, https://github.com/sourcegraph/cody. If you intend to merge this change, please reopen the PR there.

In case it's helpful, here are some of the path mappings from the old repository (https://github.com/sourcegraph/sourcegraph) to the new repository (https://github.com/sourcegraph/cody):

- `client/cody/ -> vscode/`
- `client/cody-shared/ -> lib/shared/`
- `client/cody-ui/ -> lib/ui/`

Thank you for the PR, and sorry for the inconvenience!

**Pull request closed without merging**
