### PR TITLE
jc/remove-repos-mock: Fix go-mockgen in CI

### PR DESCRIPTION
**Pull request by efritz**
Fix CI for `jc/remove-repos-mock`.

### CODE REVIEW

**Comment by efritz** [comment]
@unknwon Please merge this if it helps :)

**Review by camdencheek — APPROVED** [review]

**Comment by unknwon** [comment]
@efritz Thanks so much for helping out! ❤️ 

Super wondering what is the magic part here though 😂

**Comment by efritz** [comment]
From all I could tell the go.mod and the mockgen.sh versions weren't the same

**Comment by unknwon** [comment]
> From all I could tell the go.mod and the mockgen.sh versions weren't the same

Ahh! That makes sense.

**Pull request merged**
