### PR TITLE
Link list of extensions repos to architecture overview

### PR DESCRIPTION
**Pull request by Joelkw**
Link a list of Sourcegraph-maintained extensions repos (not all of them are owned by Sourcegraph). 

Is there a better place for this info? I notice we don't have a "Developing extensions" section [on this page ](https://docs.sourcegraph.com/dev/background-information) (perhaps we should eventually make one cc @jeanduplessis ? Or is this information well-covered in other sections?)

### CODE REVIEW

**Comment by jeanduplessis** [comment]
@Joelkw I think the "developing extensions" content is probably covered under https://docs.sourcegraph.com/extensions/authoring

That said it does I do like the idea of adding it into the list there even if links to the authoring section and doesn't need separate content.

/cc @sourcegraph/extensibility

**Review by jeanduplessis — APPROVED** [review]
thought (non-blocking): is it worth having this list of repos in the actual documentation rather than a separate Google Doc?

**Review by tjkandala — APPROVED** [review]

**Comment by Joelkw** [comment]
> @Joelkw I think the "developing extensions" content is probably covered under https://docs.sourcegraph.com/extensions/authoring
> 
> That said it does I do like the idea of adding it into the list there even if links to the authoring section and doesn't need separate content.
> 
> /cc @sourcegraph/extensibility

@jeanduplessis I think that the page you linked is geared towards a third-party audience on "how to develop your own extension" and I was primarily looking for a "you're a Sourcegraph teammate, what repos do you need to be aware of" place, the big difference being the confidence/quality level of the code in all these repos. 

Long term, I would love all these extensions to be at the point where a third-party dev could refer to the most relevant one as a good example when building their own, but at the moment some of our extensions are known to be broken (e.g. editor extensions and search export) and others are old/not recently updated. My question for @marekweb and @tjkandala would be –– how confident would you be in giving this list to a third-party developer knowing they could pick an example to use at random from it? Beyond known bug fixes, are there updates we want to do to these extensions before we'd be happy to offer every one of them as a good example for external devs to refer to? 

Building a friendlier+more encouraging environment for third-party developers to build extensions is in our long term goals, but isn't an immediate priority, so if the work is significant I would prefer to leave v1 as google docs on an internally-oriented page and then return to this and document as a list of example repos.

**Comment by tjkandala** [comment]
@Joelkw I wouldn't be confident in giving this list to a third-party developer who hasn't written a Sourcegraph extension before.

1) A lot of extensions on that list were written before we implemented DX features like side-loading. I can imagine that a user could copy such an extension and be frustrated when side-loading doesn't work properly. A lot of old extensions also use deprecated APIs.

2) Neither the editor extensions nor most of the Sourcegraph extensions are properly tested at the moment. We're going to write unit tests for Sourcegraph extensions this iteration, which will help demonstrate to third-party developers how they should go about testing extensions.

3) The API is complex. Most of our actively maintained extensions depend heavily on RxJS in order to mitigate bugs that are easy to write when dealing with multiple streams of data. RxJS isn't very commonly used, and many developers, including those at Sourcegraph, complain that _it_ is complex as well. We should refactor these extensions to not rely on RxJS, and/or simplify our API where needed.

As you stated, all of these issues should be tackled, but not in the short-term. The first step in ensuring these extensions are high quality examples is for the extensibility team to actively maintain them. This involves keeping dependencies up to date, reviewing PRs, and fixing bugs as they are reported. Making these repositories easily accessible to extensibility team members so that they can set up a notification workflow is the top goal for this PR, right? Maybe we should link to this doc on the [team page](https://about.sourcegraph.com/handbook/engineering/web#extensibility-sourcegraph-extensions-and-code-host-integrations)?

**Comment by Joelkw** [comment]
In light of TJ's thoughtful feedback and agreement, I think the move is not to link this in the authoring section.

As for linking on the team page, I think "where do I find some code" is probably best kept in our docs since it's about the code rather than our team process. (Not against linking to it from the docs page.) 

I think the proper place for this might actually be a "Developing extensions" page like the ones listed [here](https://docs.sourcegraph.com/dev/background-information) – note how the [code intel page](https://docs.sourcegraph.com/dev/background-information/codeintel) lists their repos (anchor is "extensions"). 

Plan: merge this so it's at least documented somewhere for now, and then start a discussion/plan in our slack channel to create a developing extensions page and understand why we don't have one yet. At that point, to Jean's thought, I agree we should convert this doc to a list of repos on that page.

**Comment by Joelkw** [comment]
On second thought, I didn't see a reason to merge this "incomplete" and decided that a list of extensions in the page I suggest above makes sense and I might as well go ahead and do that instead. We still should flush out the rest of the "developing extensions" page I think. That PR is now here #18259, so I'm closing this.

**Pull request closed without merging**
