### PR TITLE
[a11y] web: fix tree page reflow

### LINKED ISSUE #35239: [Accessibility]: Tree page UI (header, buttons, history) does not reflow
### Audit type

Mobile device navigation

### User journey audit issue

https://github.com/sourcegraph/sourcegraph/issues/34420

### Problem description

**Issue 1**
Repo header is unusable:
image

**Issue 2**
Tabs are difficult to read
image

**Issue 3**
Commit messages are unreadable
image

### Expected behavior

**Issue 1**
We should try to break this out onto new lines if possible. Note: this could be quite complex, we should break this out into a different issue if required

**Issue 2**
We can use `flex-direction: column` here to just render the tabs vertically. That should improve UX for mobile significantly.

**Issue 3**
We should break the message out onto new lines, rather than truncate it here on mobile

### Additional details

_No response_

### Assigning labels

- [X] Please give this issue an estimate by applying a label like `estimate/Xd`, where X is the estimated number of days it will take to complete.
- [X] If this issue is specific to a specific Sourcegraph product, please assign the appropriate team label to this issue.
- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.
- [ ] If you are confident that this issue should be fixed by GitStart, please assign the label `gitstart`.

### Owner

This issue will be fixed by my team, I have assigned a relevant member to it, or I will do so in the near future.

### PR DESCRIPTION
**Pull request by limitedmage**
Closes #35239

## Test plan

Verify at 320px width

| Before | After |
| - | - |
| image |  image |
| image | image | 

## App preview:

- [Web](https://sg-web-jp-treenavwrap.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.00% (-0.01 kb) | 0.01% (+2.00 kb) | 0.02% (+2.01 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/jp/treenavwrap/compare-report.html;tab=live_object) for a full comparison between the commits 87b0d4e and 167924f or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by eseliger — APPROVED** [review]
Should we remove the rounded corners, or add `gap` between the lines, and make all rows rounded instead?

This is a good improvement, so definitely approving but maybe we can get a little more polish in here? :) Only if it fits the time budget.

**Comment by felixfbecker** [comment]
Also wondering if the toolbar repo button should shrink with ellipses instead of wrapping, since it is sticky and otherwise takes up even more vertical space. But we should definitely merge this week, as-is is fine too!

**Comment by limitedmage** [comment]
@felixfbecker I think we should remove the sticky navbar altogether, the experience on small screens is not good, especially with the taller mobile-friendly searchbox.

**Comment by felixfbecker** [comment]
Yeah agree the search box is the big offender here. To be clear, I think it should only be non-sticky on small viewports.

**Comment by limitedmage** [comment]
I'd argue it should be unsticky everywhere, it causes issues with sticky sidebars and other complex layouts.

**Comment by limitedmage** [comment]
I'll merge this as-is since this is a quick stopgap. Adding ellipsis would be more involved work. Code Exploration team can work on polishing this after.

**Review by valerybugakov — APPROVED** [review]
I often use Sourcegraph from my phone for some reason — 💜 that!

**Pull request merged**
