### PR TITLE
gomod: update zoekt

### PR DESCRIPTION
**Pull request by keegancsmith**
- https://github.com/sourcegraph/zoekt/commit/145fe82 Upgrade pcre2 package
- https://github.com/sourcegraph/zoekt/commit/b61c934 indexData: experimental ngram map via binary search
- https://github.com/sourcegraph/zoekt/commit/aacaf0c gomod: downgrade datadog
- https://github.com/sourcegraph/zoekt/commit/2eec411 gomod: bump ctags to avoid zombie procs
- https://github.com/sourcegraph/zoekt/commit/b744e52 Convert regexp capture groups to non-capture groups
- https://github.com/sourcegraph/zoekt/commit/a174ad6 fix inaccurate comment
- https://github.com/sourcegraph/zoekt/commit/7a91c48 Split `lineBounds` out into its own method
- https://github.com/sourcegraph/zoekt/commit/f846f01 Create `newlines` type
- https://github.com/sourcegraph/zoekt/commit/5c5f94b improve descriptions of entries on /debug endpoint
- https://github.com/sourcegraph/zoekt/commit/25fa2fa builder.go: have incremental builds update latest commit date information
- https://github.com/sourcegraph/zoekt/commit/15dc905 indexserver: remove debug commands
- https://github.com/sourcegraph/zoekt/commit/6c563dc tests: fix alignment for number hints like "--0123"
- https://github.com/sourcegraph/zoekt/commit/0cafd7b all: stop using the deprecated package io/ioutil
- https://github.com/sourcegraph/zoekt/commit/c16eb04 tests: replace ioutil.TempDir with testing.T.TempDir
- https://github.com/sourcegraph/zoekt/commit/6ca5909 go.mod: fix a cve in a transitive dependency to make Dependabot happy
- https://github.com/sourcegraph/zoekt/commit/f2bb82f debug: add debug score for line matches
- https://github.com/sourcegraph/zoekt/commit/a3e0a5f indexserver: support SG_PRIORITY file for FS fake
- https://github.com/sourcegraph/zoekt/commit/fce3356 indexserver: always cleanup if index fails
- https://github.com/sourcegraph/zoekt/commit/794ad6c debug: new pages for List and listIndexed
- https://github.com/sourcegraph/zoekt/commit/c85ca2f ranking: boost base filename matches

Test Plan: CI

### CODE REVIEW

**Review by andreeleuterio — APPROVED** [review]
ty!

**Review by stefanhengl — APPROVED** [review]

**Comment by keegancsmith** [comment]
@jac I have ported your optimizeRegexp via copy pasta, since it broke tests. This way we get your perf benefits :D But please follow-up and do the query changes you wanted to do to make this re-useable. It almost feels like zoekt's parseRegexp function needs to be exported?

**Comment by jac** [comment]
> It almost feels like zoekt's parseRegexp function needs to be exported?

Yeah, Zoekt's [regexpQuery](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/query/parse.go?L226-251) is practically identical to Sourcegraph's [parseRe](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/zoekt/zoekt.go?L34-57) so I think it would make sense to export `regexpQuery` and call it from `parseRe`.

**Comment by bobheadxi** [comment]
Unfortunately had to revert this in https://github.com/sourcegraph/sourcegraph/pull/37226 due to test regressions in main - guessing from the test failure, the capture group optimizations were too good, and scenarios where previously the search would return an alert no longer return an alert 😛

**Pull request merged**
