### PR TITLE
regression e2e: test fixes 3.15

### PR DESCRIPTION
**Pull request by uwedeportivo**
can you guys go over these test edits and look if they're correct. even with these edits i get 5 failures for

```
SLOWMO=10 KEEP_BROWSER=true yarn run test:regression:search
```

Screen Shot 2020-04-16 at 6 49 54 PM

run the instance like so:

```
IMAGE=sourcegraph/server:3.15.0-rc.3 ./dev/run-server-image.sh
```

and make yourself a .envrc before you run the tests as described here:
( you need at least a sourcegraph sudo token, a github token etc, change the sourcegraph base url to your setup)

Follow [README.md](https://github.com/sourcegraph/sourcegraph/blob/master/web/src/regression/README.md) to set up your e2e environment. 
        Run the tests from the `web` directory. A more complete set of env vars can be found in this
        [1password](https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/gm5dfflq6sfclmotneuayfdj5q) entry.

### CODE REVIEW

**Comment by uwedeportivo** [comment]
i think the windowLocation changes are correct. i tested all of them by hand

**Comment by uwedeportivo** [comment]
@rvantonder tested the count:1000 with graphql api and he gets 1k+ results. maybe something changed in the UI handling there. if i click "more" a couple of times i can get close to 700-800 results

**Comment by rvantonder** [comment]
> @rvantonder tested the count:1000 with graphql api and he gets 1k+ results. 

I also tested against the web UI, not just the API, to rule out any possibility of approximateResultCount or some other value being used. I see 1073 results in UI and via CLI.

**Comment by uwedeportivo** [comment]
update: using the corpus of test repos (from @rvantonder , thanks !) i got it down to 4 failures. all of these failures look like the tests need to be updated and not actual functionality failure (i tested by hand). the 1k+ test passes now

Screen Shot 2020-04-16 at 8 00 22 PM

three of the failures are probably due to some css selector changes and it doesn't find the html element

**Comment by attfarhan** [comment]
@uwedeportivo for the interactive search mode test, I believe you just need to replace `textContents.includes('repo:auth0/go-jwt-middleware$')` with `textContents.includes('repo:"auth0/go-jwt-middleware$"') &&

**Comment by uwedeportivo** [comment]
got it, cool. thanks for looking 👍

**Comment by attfarhan** [comment]
@uwedeportivo actually all those 3 values probably need quotes around them, so 
```
textContents.includes('repo:auth0/go-jwt-middleware$') &&
                        textContents.includes('file:README') &&
                        textContents.includes('lang:markdown')
```
becomes 
```
textContents.includes('repo:"auth0/go-jwt-middleware$"') &&
                        textContents.includes('file:"README"') &&
                        textContents.includes('lang:"markdown"')
```

**Comment by uwedeportivo** [comment]
right, ok

**Pull request merged**
