### PR TITLE
server: use p4-fusion multi-stage build

### PR DESCRIPTION
**Pull request by keegancsmith**
This is a follow-up from us converting p4-fusion into a multi-stage build for gitserver #31066. This now uses the same shared script for building.

Test Plan: CI with integration testing will exercise building and running the server image.

### CODE REVIEW

**Review by sashaostrikov — APPROVED** [review]
LGTM!

**Comment by ryanslade** [comment]
Looks good, but worth still manually testing that running `p4-fusion` actually works. IIRC this is what happened last time. Everything built successfully, but the resulting binary was not runnable.

**Comment by keegancsmith** [comment]
> Looks good, but worth still manually testing that running `p4-fusion` actually works. IIRC this is what happened last time. Everything built successfully, but the resulting binary was not runnable.

We now share the build script with gitserver, so you know it will work on both. If you just run that script inside of a fresh alpine container the produced binary works. The only runtime dependency is documented in that script and I added to the container (`   libstdc++`). However, given that whole spiel I'll download the image produced in this CI run and check :P

On that note, I wonder if we should add some lightweight tests to docker images to test things like "does this binary run and is on the $PATH".

**Comment by keegancsmith** [comment]
```
❯ docker run -it --rm=true --entrypoint /bin/bash us.gcr.io/sourcegraph-dev/server:2e19c07faf29f4dea902d0b5b5f3ebd51d65e240_131206_candidate -il
16b71e52cdb1:/# ldd `which p4-fusion`
	/lib/ld-musl-x86_64.so.1 (0x7fa08d236000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fa08cb6b000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fa08cb57000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fa08d236000)
16b71e52cdb1:/# p4-fusion > /dev/null; echo $?
0
```

**Review by ryanslade — APPROVED** [review]
LGTM, I confirmed locally too

**Pull request merged**
