### PR TITLE
monitoring: panel refactor, introduce ObservablePanelOption

### PR DESCRIPTION
**Pull request by bobheadxi**
Closes https://github.com/sourcegraph/sourcegraph/issues/17061

This PR drafts up a possible API for introducing custom options, `ObservablePanelOption`, and completely refactors the internals of the existing `ObservablePanelOptions` type to leverage these new options. Learn more about it in the [API documentation](https://github.com/sourcegraph/sourcegraph/blob/panel-redux/monitoring/monitoring/README.md#type-observablepaneloption). ~This design requires no migration of existing panel options usage.~ requires a slight change as of c584c3c02061753388c4455cbd9495fe5f176f7e, renames `PanelOption` -> `Panel`

We also add `ObservablePanelOptions.With(ObservablePanelOption)` to apply custom options, with a few shared options available (OpinionatedDefaults and AlertThresholds, both already applied in the default `PanelOptions`, though separated out so users of `PanelOptionsMinimal` can use them as well).

This is the result of a pairing session with @davejrt and a bit of cleanup I did after.

#### lingering thoughts

**update** see https://github.com/sourcegraph/sourcegraph/pull/17112#issuecomment-758523390

The only thing I'm iffy on is naming of the options, but maybe it doesn't really matter?

* I don't want `Panel...` because that will make autocomplete when trying to find `ObservablePanelOptions` constructors a bit crowded
* `OptionAlertThresholds` doesn't feel particularly elegant (but maybe it is fine?)

I considered introducing a `panel` package to house shared options, but in order for certain options to be available by default in `PanelOptions`, we will have an import cycle. Ultimately I think just having this all hear is probably better because some panel options will depend on Observable internal fields (for example, `OptionAlertThresholds()`).

### CODE REVIEW

**Review by pecigonzalo — APPROVED** [review]
LGTM!

> I considered introducing a panel package to house shared options

How about we "house" them in a struct or similar so it is still provides a `options.AlertThresholds` "like" sort of interface?

**Comment by bobheadxi** [comment]
> How about we "house" them in a struct or similar so it is still provides a options.AlertThresholds "like" sort of interface?

Brilliant! c584c3c02061753388c4455cbd9495fe5f176f7e implements this under `PanelOptions`, and now the options builder is just called `Panel() ObservablePanel`. Syntactically I think this is a lot nicer:

```go
{
    Name:        "some_metric_behaviour",
    Description: "some behaviour of a metric over 5m",
    Query:       `histogram_quantile(0.99, sum by (le)(rate(search_request_duration{status="success}[5m])))`,
    Panel:       monitoring.Panel().LegendFormat("duration").With(monitoring.PanelOptions.MyCustomization()),
}
```

**Comment by bobheadxi** [comment]
@davejrt I think I'm pretty happy with the implementation + docs here, would you like to review this before merge?

**Comment by bobheadxi** [comment]
Merged to avoid conflict with some work I'm doing on https://github.com/sourcegraph/sourcegraph/issues/17158

**Review by daxmc99 — COMMENTED** [review]
Looks good

**Pull request merged**
