### PR TITLE
Cody: Rename extension to Cody AI by Sourcegraph

### PR DESCRIPTION
**Pull request by philipp-spiess**
RFC to rename the extension and the tab form "Sourcegraph Cody" to just "Cody AI by Sourcegraph"

The intention is that we show up in the search first :) Sourcegraph is mentioned as the author anyways so I don’t think it’s super useful here.

image

## Test plan

- Should be fine? No way to test until we submit 😬 
- I initially wanted to rename the in-editor Tab as well but that was really annoying so I reverted it:
Screenshot 2023-05-11 at 12 47 29

Now we're back at

Screenshot 2023-05-11 at 12 51 34

### CODE REVIEW

**Comment by vdavid** [comment]
I like it. Not sure who's the decision-maker in this. @malomarrec maybe?
(If we want to keep our company name there, "Cody by Sourcegraph" is another option to still move it up a bit in lists, but in the above case, I guess we'd still be 4th with that name.)

**Comment by mrnugget** [comment]
Also @iskyOS and @ebrodymoore here, because it's important from a marketing perspective whether we call it "Cody" or "Sourcegraph Cody"

**Comment by abeatrix** [comment]
I think there was a thread where we switched from Cody to Sourcegraph Cody because there are multiple "Cody" on the marketplace.

**Comment by philipp-spiess** [comment]
We can also put Sourcegraph as the first word in the description, something like "

```
Cody 
Sourcegraph's AI code assistant that writes code ..
Sourcegraph
```

But to be honest I think the author name is pretty prominent already. 

I’m more worried that people are confused this way because we appear fourth in the list. "Is this even legit?"

**Comment by philipp-spiess** [comment]
cc @gwestersf too

**Comment by philipp-spiess** [comment]
Decision as per [this internal thread](https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1683718154408839) is to call it "Cody AI by Sourcegraph"

**Comment by philipp-spiess** [comment]
Paging @sourcegraph/cody for review now that we have a conclusion on the name!

**Review by eseliger — APPROVED** [review]

**Pull request merged**
