### PR TITLE
Revert "gomod: update zoekt"

### PR DESCRIPTION
**Pull request by bobheadxi**
Reverts sourcegraph/sourcegraph#37213 - we appear to have a regression on this upgrade in https://buildkite.com/sourcegraph/sourcegraph/builds/154519:

```
    --- FAIL: TestSearch/graphql (4.62s)
        --- FAIL: TestSearch/graphql/structural_search (1.22s)
            --- FAIL: TestSearch/graphql/structural_search/Structural,_index_only,_nonzero_result (0.01s)
                search_test.go:732: Want non-zero results but got 0
        --- FAIL: TestSearch/graphql/And/Or_queries (1.29s)
            --- FAIL: TestSearch/graphql/And/Or_queries/Literals,_not_and_and_keyword_inside_group (0.01s)
                search_test.go:930: Alert mismatch (-want +got):
                      (*gqltestutil.SearchAlert)(
                    - 	nil,
                    + 	&{
                    + 		Title:       "Too many files to search for expression",
                    + 		Description: "One expression in the query requires a lot of work! This can happen with negated text searches like '-content:', not-expressions"...,
                    + 	},
                      )
```

Test plan: https://buildkite.com/sourcegraph/sourcegraph/builds/154545

### CODE REVIEW

**Comment by keegancsmith** [comment]
backend integration tests look happy

**Comment by bobheadxi** [comment]
https://buildkite.com/sourcegraph/sourcegraph/builds/154545 just went green

**Review by indradhanush — APPROVED** [review]

**Comment by bobheadxi** [comment]
> Are these consistent failures? IIRC, I've seen these flake at least once before.

It failed 2x in recent branch lock (https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1655222510765919), but yeah possible it's not strictly related - looks like Keegan's working on a follow-up here: https://github.com/sourcegraph/sourcegraph/pull/37230

**Comment by keegancsmith** [comment]
Yeah I couldn't really understand how my PR did this, but couldn't rule it out. I've basically done the PR again with just the gomod update. I already had a backend integration test run with it and it worked.

**Comment by camdencheek** [comment]
We've already got a few flaky backend integration tests disabled. It's probably worth spending some time trying to shore up those tests since they are very valuable, but also pretty unreliable.

**Pull request merged**
