### PR TITLE
Move compute Elm component to more generic location

### PR DESCRIPTION
**Pull request by limitedmage**
Part of #35906

Move the compute Elm component currently used only in Notebooks to a more generic location, as we'll be using it in the search results page as well.

## Test plan

Moving files only, all existing tests/CI should pass.

## App preview:

- [Web](https://sg-web-jp-movecompute.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ikxflzycdr.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
Works for me! Any upcoming plans to use TS graph/visualizations on the results page?

**Comment by limitedmage** [comment]
> Works for me! Any upcoming plans to use TS graph/visualizations on the results page?

I'm going to state by reusing this component and then consider using TS.

**Comment by rvantonder** [comment]
@limitedmage OK, if it helps, I can add things to the component to not display the query text inputs, just LMK. I want to use CodeMirror for query input down the line anyway so it's been part of the plan, just not urgent enough yet

**Comment by limitedmage** [comment]
Thanks @rvantonder!

**Pull request merged**
