### PR TITLE
Cody: Open files in workspace

### PR DESCRIPTION
**Pull request by abeatrix**
Close https://github.com/sourcegraph/sourcegraph/issues/52863

Loom: https://www.loom.com/share/62c920c3c2e94d67b2f6266689a2e4fc

Open validated file paths from Cody's response as workspace file, excluding directories (opening a path to directory would create a new workspace for the directory).

path

## Test plan

Locally tested. All tests have passed. See video:

https://github.com/sourcegraph/sourcegraph/assets/68532117/7c098ea7-b7d5-467d-be4d-9802a478ac4c

### CODE REVIEW

**Review by philipp-spiess — APPROVED** [review]
We have an issue where sometimes paths are detected inside single backtick inline code blocks which means that it will escape the HTML tag which renders oddly.

```
Basically like this `foo <span blabla>bar/quz</span>`
```

I am worried that adding more HTML will make this experience worse. On the other hand, it works for 80% of the cases and there, not being able to click it is really bad, so let's go ahead with it.

**Comment by toolmantim** [comment]
Does this make #52029 redundant? There's been some design improvements on there…

**Comment by abeatrix** [comment]
> We have an issue where sometimes paths are detected inside single backtick inline code blocks which means that it will escape the HTML tag which renders oddly.

Oh that's a good thing to know. I will keep this in mind and yea let's go ahead with this and get more feedback before we decide how to improve this! Thanks for the review!

**Comment by abeatrix** [comment]
> Does this make #52029 redundant? There's been some design improvements on there…

I didn't change anything regarding the styles so it'd be nice to have your changes too! The style for the hallucinated path in your PR looks so cute :D

**Pull request merged**
