### PR TITLE
cody: beta notice on site configuration

### PR DESCRIPTION
**Pull request by novoselrok**
Adds Cody beta notice to site configuration when completions are enabled.

## Demo

https://user-images.githubusercontent.com/6417322/222157226-b8fd298d-2ffa-44c2-aa7e-bc32d0e39855.mov

## Test plan

* Disable or delete completions from site config
* Enable completions in site config
* You should see a notice appear above the editor containing the Cody beta information

## App preview:

- [Web](https://sg-web-rn-cody-beta-notice.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.58 kb) | 0.00% (+0.58 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/rn/cody-beta-notice/compare-report.html;tab=live_object) for a full comparison between the commits 647c1bf and e06ddae or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by malomarrec — APPROVED** [review]

**Comment by malomarrec** [comment]
Question: in this video, we enable embeddings (open AI)
What if we only enable cody (so just the anthropic key)?

**Comment by novoselrok** [comment]
> Question: in this video, we enable embeddings (open AI) What if we only enable cody (so just the anthropic key)?

In the video, I enable the completions config (Anthropic). That is the minimum requirement for Cody to work. Embeddings are technically optional for Cody.

**Review by tammy-zhu — APPROVED** [review]

**Comment by malomarrec** [comment]
https://github.com/sourcegraph/sourcegraph/pull/48290

**Pull request merged**
