### PR TITLE
remove deprecated register{TypeDefinition,Implementation}Provider and related types

### PR DESCRIPTION
**Pull request by sqs**
Extensions should use registerLocationProvider instead. The removed functions were rarely used and too specific (usually languages have their own custom notions of concepts like type definition and implementation, and there is no useful one-size-fits-all approach).

Stubs remain so that extensions calling these functions will not break (a message is logged and a noop unsubscribable is returned).

Related:
- https://github.com/sourcegraph/sourcegraph-go/pull/47
- https://github.com/sourcegraph/sourcegraph-typescript/pull/132

### CODE REVIEW

**Comment by felixfbecker** [comment]
This will require changes to multiple extensions and the LSP client lib.
How is the label for the button determined when using `registerLocationProvider`?
Will we ever have a use case where we want to execute a "definition" provider or some other provider with a specific semantic?

**Comment by sqs** [comment]
> This will require changes to multiple extensions and the LSP client lib.

I will update lang-go and lang-typescript to be compatible.

> How is the label for the button determined when using `registerLocationProvider`?

The extension needs to contribute an action to the hover menu (which was made possible ~1.5 months ago). There is currently no button shown for "Find implementations" in the hover, and it is OK to continue to not show one.

> Will we ever have a use case where we want to execute a "definition" provider or some other provider with a specific semantic?

Yes. That is why registerDefinitionProvider and registerReferenceProvider both remain. Only the lesser-used registerXyzProvider funcs were removed.

**Comment by sqs** [comment]
@lguychard 	Thanks for approving #2733, which is based on this PR's branch. Could you please also review this PR?

**Comment by sqs** [comment]
> > This will require changes to multiple extensions and the LSP client lib.

> Has this been taken care of?

Yes:

- https://github.com/sourcegraph/sourcegraph-go/pull/47
- https://github.com/sourcegraph/sourcegraph-typescript/pull/132

**Comment by felixfbecker** [comment]
@sqs how should `lsp-client` generate the ID?

**Comment by sqs** [comment]
Language name (eg go or csharp), dot, “impl”

**Pull request merged**
