### PR TITLE
fix: build essential Go tools before updating GOBIN

### PR DESCRIPTION
**Pull request by creachadair**
PR #8912 pointed GOBIN to a temp directory, so that the target binaries can be compared to the installed set to avoid unnecessary restarts.  However, that change applies to ALL the Go tools built by this script, including dlv and the Zoekt indexer binaries that are not updated in this way.
    
That means in a clean checkout (or in any other case where .bin has been purged), the .bin directory never receives the zoekt binaries at all, and the service cannot start up.
    
The key change here is to move the update of GOBIN until after those core tools are built and installed. Then the target commands are built with GOBIN pointed to a temp directory, as before.
    
Along the way, I also cleaned up some of the formatting in the file (tabs to spaces, fixed indentation). There is more that could be done.

### CODE REVIEW

**Comment by creachadair** [comment]
> Thank you for catching this! And sorry for breaking it in the first place 😬

I will say for the record, it was an act of great restraint on my part not to completely rewrite this script. 👀

**Comment by mrnugget** [comment]
> I will say for the record, it was an act of great restraint on my part not to completely rewrite this script. 👀

Add to the same record: I would very much applaud you if you did that!

**Comment by creachadair** [comment]
> > I will say for the record, it was an act of great restraint on my part not to completely rewrite this script. 👀
> 
> Add to the same record: I would very much applaud you if you did that!

I may yet. But for now I wanted to unblock my own testing. 😉

**Comment by unknwon** [comment]
I can' read BASH, but I can give you an emoji ❤️

**Pull request merged**
