### PR TITLE
pkg/db: move a few DB-related packages to here + add pkg/db/globalstatedb

### PR DESCRIPTION
**Pull request by slimsag**
### Part one: code location refactor

Prior to this change we had:

- `pkg/conf/confdb`
- `pkg/dbconn`
- `cmd/frontend/db/testing`

This was confusing because e.g. it was hard to find all DB related logic AND because `pkg/conf/confdb` would import `cmd/frontend/db/testing`.

After this change we have:

- `pkg/db/confdb`
- `pkg/db/dbconn`
- `pkg/db/dbtesting`

### Part two: exposing global_state DB table (`pkg/db/globalstatedb`)

The management console needs somewhere in the database to store the basic auth password ([spec](https://github.com/sourcegraph/sourcegraph/issues/965#issuecomment-441552016)), and the `global_state` DB table seems like the right place to do it. This means that the management console service must access that table; therefor moving it into its own package which the management console can import makes sense.

### CODE REVIEW

**Comment by slimsag** [comment]
@nicksnyder @beyang No need to review the actual changes here since they are mostly mechanical, but please review the general concept / PR description here. I will merge soon and follow up on any comments.

**Comment by nicksnyder** [comment]
PR description lgtm

**Comment by slimsag** [comment]
I considered that, but decided against it. Here's how I think of this:

- `dbconn` -> connection to the DB
- `dbtesting` -> stuff for testing against the DB
- `confdb` -> the actual database for configuration
- `globalstatedb` -> the actual database for global state

`dbconf` may be misinterpreted as "configuration _for_ the DB", same with `dbglobalstate` being misinterpreted as "global state _for_ the DB", whereas using `db` suffix has no such issue and makes a nice distinction between the two I think

**Comment by slimsag** [comment]
Helped #965

**Pull request merged**
