### PR TITLE
tracking-issue: Order finished work chronologically

### PR DESCRIPTION
**Pull request by efritz**
Order the list of finished work chronologically and say how many days have elapsed since the issue was closed or the PR was closed/merged. This is useful for determining what you did in the last week for status updates.

Screen Shot 2020-09-23 at 5 09 56 PM

### CODE REVIEW

**Review by tsenart — APPROVED** [review]

**Comment by tsenart** [comment]
Seems like we're showing both the PR and the Issue it fixes. Is this intended?

**Comment by efritz** [comment]
> Is this intended?

@tsenart Yeah the completed list is a flat list of all completed work. I'm open to alternatives though.

**Comment by tsenart** [comment]
Seems duplicative to show the PRs too, when the issue is there with the list of PRs inline.

**Comment by efritz** [comment]
I'll make a new PR on top of this one as this isn't new behavior in this change set.

**Pull request merged**
