### PR TITLE
Render `QueryExamplesHomepage` for dotcom logged in users

### PR DESCRIPTION
**Pull request by st0nebraker**
This PR allows dotcom logged in users to view the query samples brought in on #39987.

__ will you let us know if you see an issue in bringing this into dotcom? I'm assuming it was left out for initial rollout.

## Test plan
- Ensure all tests pass
- Ensure visiting `/search` home page logged in on dotcom shows the same search query samples on k8s and s2
- Observe no breaking changes on logged out state in this view for all env's

## App preview:

- [Web](https://sg-web-becca-dotcome-search-query-samples.onrender.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.00 kb) | -0.00% (-0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/becca/dotcome-search-query-samples/compare-report.html;tab=live_object) for a full comparison between the commits 52e64da and 1a34521 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by st0nebraker** [comment]
@cla-bot check

**Comment by st0nebraker** [comment]
@cla-bot check

**Comment by st0nebraker** [comment]
@cla-bot check

**Comment by st0nebraker** [comment]
@cla-bot check

**Comment by st0nebraker** [comment]
@cla-bot check

**Comment by st0nebraker** [comment]
@cla-bot check

**Pull request closed without merging**
