### PR TITLE
gitserver: metric for removing repo due to disk space

### PR DESCRIPTION
**Pull request by keegancsmith**
See individual commits. This adds a prometheus metric so we can track if we remove repositories due to disk pressure.

### CODE REVIEW

**Comment by keegancsmith** [comment]
@tsenart do you think warnings that golanglint-ci is giving are useful? Can we start with a smaller set of checks which point to real problems (rather than style advice).

image

image

**Comment by tsenart** [comment]
@keegancsmith: As mentioned in the PR that introduced this, the linter selection isn't set in stone. I agree these two aren't always useful, so happy to remove them from the config. :+1:

**Comment by tsenart** [comment]
@keegancsmith: Do you want me to open a PR or will you?

**Comment by keegancsmith** [comment]
> @keegancsmith: Do you want me to open a PR or will you?

will do one quick and be brutal :)

**Pull request merged**
