### PR TITLE
allow having an empty list of zoekt replicas (means just use unindexed)

### PR DESCRIPTION
**Pull request by sqs**
If the env var INDEXED_SEARCH_SERVERS is the empty string, then indexed search (Zoekt) will not be used. (If it is merely unset, then it will be used, so the default behavior is unchanged.)

This is useful when running Sourcegraph in environments where indexed search is not needed or desirable. (In particular, the single-program experimental distribution method, but this fix seems useful even on its own.)

## Test plan

Unset `INDEXED_SEARCH_SERVERS` env var. Run a search `a index:only`; it should have no results. Run `a`; it should have results.

### CODE REVIEW

**Comment by gl-srgr** [comment]
1 config test added. In the current behavior we would not reach the `if sc.Zoekts != nil` assert of this test since it would panic before that point.

**Comment by ggilmore** [comment]
Looks decent so far. One non-blocking question, is there a reason that we're using error equality checks (err == endpoint.IntentionallyEmpty) instead of `errors.Is(err, endpoint.IntentionallyEmpty)`?

**Comment by sqs** [comment]
@ggilmore Good call, I just made it use `errors.Is`.

**Comment by sqs** [comment]
@ggilmore Friendly ping on this 😸 or is there someone else who should review it?

**Comment by ggilmore** [comment]
@sqs ah sorry, I didn't catch that this was ready for review. I am afk, but I can review it on Monday if that's alright.

**Comment by keegancsmith** [comment]
I need to take a deeper look, but making every call site handle that error seems a bit clunky, especiallt since they just seem to treat it as an empty map. Is there a way for us to not return an error but instead just allow empty maps?

FYI you recently we removed the ability to disable zoekt, which sounds like what you are wanting to reintroduce?

**Review by slimsag — APPROVED** [review]
From my POV this looks good to go.

I don't think it will harm our codebase, so it'd be good to just merge it as-is and reduce the `sqs/single-program` branch size.

I will also say I like the fact that it differentiates between "intentionally empty" and "empty", because that means we could provide a better error message to e.g. k8s customers that have somehow messed up the env var vs. single binary where this is intentional behavior.

**Comment by sqs** [comment]
@keegancsmith:

> FYI you recently we removed the ability to disable zoekt, which sounds like what you are wanting to reintroduce?

Yeah, I removed that old way of disabling Zoekt that was broken/ineffective while I was trying to figure out how to do it. This way seemed better, but I'm totally open to a different way. @slimsag is running with this now as part of the single-binary work.

**Review by keegancsmith — COMMENTED** [review]
There are some sites where the handling is in the wrong place. Additionally I think the pattern of communicating something which isn't an error as an error will lead to bugs in the future / is clunky. I would prefer adjusting the return values to have something like an (ok bool), or maybe some other design. I'll take advantage of the fact that you all are sleeping (or should be :P) and update this PR so you can land it when ya wake up.

**Comment by keegancsmith** [comment]
Instead of adjusting this PR, here is an alternative: https://github.com/sourcegraph/sourcegraph/pull/46280/files

**Pull request closed without merging**
