### PR TITLE
Tree: add "go up" the tree button (second merge)

### PR DESCRIPTION
**Pull request by oleggromov**
As the [previous merge](https://github.com/sourcegraph/sourcegraph/pull/39138) was [reverted](https://github.com/sourcegraph/sourcegraph/pull/39234), I am making the new one.

## Description
Part of the [Tree improvements](https://github.com/sourcegraph/sourcegraph/issues/38667), it adds the option to [navigate up the tree](https://github.com/sourcegraph/sourcegraph/issues/38663).

The tree still retains the "confusing behaviour", which is the inconsistency between:

1. Navigating to the root of the repo - which opens up the entire tree at root, as expected
2. Going to a deeply nested file, which only opens the subtree - which is confusing

This part will be fixed later on, with a bigger refactoring of the entire `Tree` component, including data fetching, tree processing, and rendering.

## Test plan
1. Check out the branch
4. Open up a few repos:
    1. A regular one with lots of subfolders: https://sourcegraph.test:3443/github.com/sourcegraph/code-intel-extensions
    2. Something with a deeply nested single children: https://sourcegraph.test:3443/github.com/sgtest/java-pom-with-deps-javaconfig/-/blob/src/main/java/com/sourcegraph/depuser/ApacheCommonsUser.java
    5. A single-file one: https://sourcegraph.test:3443/github.com/sgtest/head-branch/-/blob/foo
3. Make sure that ".." is shown and navigates up the tree
6. Make sure that tests are passing

https://user-images.githubusercontent.com/2196347/180196529-e712b6cb-2fef-4185-8079-2b12a328b4fb.mov

## App preview:

- [Web](https://sg-web-og-tree-nav-up.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-hjmdhwxsqg.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by olafurpg — APPROVED** [review]

**Review by jjinnii — APPROVED** [review]
Thanks @oleggromov ! Preemptively approving, but would still like to see that loading state centered. 😄

**Comment by oleggromov** [comment]
@jjinnii I think now it's align properly.

https://user-images.githubusercontent.com/2196347/181586091-ebb8ed64-f36f-4826-b76a-cb5cd854ae03.mov

**Comment by oleggromov** [comment]
> [Codenotify](https://github.com/sourcegraph/codenotify): Notifying subscribers in CODENOTIFY files for diff [6c1d161...912c4c2](https://github.com/sourcegraph/sourcegraph/compare/6c1d161151cdd0612f471bfe5cec13ee5cc42c42...912c4c24a417cd238a4281583bb242f6055b07bc).
> 
> Notify	File(s)
> @indradhanush	cmd/gitserver/server/cleanup_test.go
> @ryanslade	cmd/gitserver/server/cleanup_test.go

Irrelevant, was due to an unrelated commit to the branch which was removed.
cc @mrnugget

**Comment by oleggromov** [comment]
[This build](https://buildkite.com/sourcegraph/sourcegraph/builds/163991) was initiated manually and e2e tests are now passing:
Screenshot 2022-07-28 at 18 33 09

**Pull request merged**
