### PR TITLE
search: Add Fork() method to query.Q

### PR DESCRIPTION
**Pull request by camdencheek**
Adds a well-typed Fork() method to query.Q

Depends on #18949

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
Nice--I looked at this carefully and think we're good here :-) It should help with some other refactoring to make it easier to work with yes/no/only later too.

**Comment by rvantonder** [comment]
Oh, I just noticed this isn't guarded by the `validate` function like you do in https://github.com/sourcegraph/sourcegraph/pull/18949--I assumed this was already happening. We will panic if this change is merged before that one and someone enters an invalid value: https://github.com/sourcegraph/sourcegraph/pull/18950/files#diff-7dc072bbb94430c3d38e446cab3891b4507c6ee390cbcf662e30a18d7a4daf09R145-R146. Could you put that validate change here for fork?

**Comment by rvantonder** [comment]
Oh I see this is stacked. OK!

**Comment by camdencheek** [comment]
Oh, yep. Sorry, that snuck into the wrong commit. My bad!

**Pull request merged**
