### PR TITLE
TELEMETRY_HTTP_PROXY env var to proxy telemetry requests

### PR DESCRIPTION
**Pull request by sqs**
The env var TELEMETRY_HTTP_PROXY, if set, causes all telemetry requests (update checks and pings) to be proxied through an HTTP proxy.

cc @toddherskovitz 

## Test plan

@DaedalusG 
Testing using the following light weight proxy, and an `sg` dev environment
```
package main

import (
	"github.com/elazarl/goproxy"
	"log"
	"flag"
	"net/http"
)

func main() {
	verbose := flag.Bool("v", false, "should every proxy request be logged to stdout")
	addr := flag.String("addr", ":8080", "proxy listen address")
	flag.Parse()
	proxy := goproxy.NewProxyHttpServer()
	proxy.Verbose = *verbose
	log.Fatal(http.ListenAndServe(*addr, proxy))
}
```

### CODE REVIEW

**Comment by slimsag** [comment]
neat! I assume some HN conversation spawned this idea :)

maybe consider respecting `TELEMETRY=false` too as an opt-out env var?

**Comment by sqs** [comment]
@slimsag This is actually a customer request so they can send telemetry to us.

@camdencheek Someone told me you wanted to take this one or had already? Or did I hear wrong?

**Comment by camdencheek** [comment]
@sqs I don't remember hearing about this, but I am working on [a different fix for the same customer](https://github.com/sourcegraph/sourcegraph/pull/47497), so maybe that's what you heard?

**Comment by sqs** [comment]
@camdencheek Ah, that must have been the source of confusion.

@DaedalusG Do you want to take this fix from here? I can help.

**Comment by DaedalusG** [comment]
Yes please @sqs , I've been working to test this one, was hoping to make more progress Monday but got swamped with issues 😅

**Comment by DaedalusG** [comment]
It looks like we actually honor the [standard](https://pkg.go.dev/net/http@go1.20.1#ProxyFromEnvironment) `HTTPS_PROXY`

sg.config.overwrite.yaml
```yaml
commands:
  frontend:
    env:
      # TELEMETRY_HTTP_PROXY: "http://127.0.0.1:8080"
      HTTPS_PROXY: "http://127.0.0.1:8080"
      # NO_PROXY: *.company.com
```

sg logs
```
[       frontend] !!! USING REGULAR PROXY ENV VAR !!!
[       frontend] INFO frontend cli/serve_cmd.go:261 ✱ Sourcegraph is ready at: https://sourcegraph.test:3443
[       frontend] !!! Response Status Code  200 !!!
[       frontend] INFO frontend.updatecheck updatecheck/client.go:755 telemetry proxy {"TELEMETRY_HTTP_PROXY=": ""}
```

goproxy
```
λ ~/proxy-test/goproxy/ go run ./main.go -v
2023/02/21 00:25:26 [001] INFO: Running 0 CONNECT handlers
2023/02/21 00:25:26 [001] INFO: Accepting CONNECT to sourcegraph.com:443
```

**Comment by DaedalusG** [comment]
The new `TELEMETRY_HTTP_PROXY` also works

sg.config.overwrite.yaml
```
commands:
  frontend:
    env:
      TELEMETRY_HTTP_PROXY: "http://127.0.0.1:8080"
      # HTTPS_PROXY: "http://127.0.0.1:8080"
      # NO_PROXY: *.apple.com
```

sg logs
```
[       frontend] !!!!!! USING PROXY FOR TELEMETRY !!!!!!
[       frontend] !!! Response Status Code  200 !!!
[       frontend] INFO frontend.updatecheck updatecheck/client.go:755 telemetry proxy {"TELEMETRY_HTTP_PROXY=": "http://127.0.0.1:8080"}
```

proxy logs
```
λ ~/proxy-test/goproxy/ go run ./main.go
2023/02/21 01:00:10 [001] INFO: Running 0 CONNECT handlers
2023/02/21 01:00:10 [001] INFO: Accepting CONNECT to sourcegraph.com:443
2023/02/21 01:36:54 [002] INFO: Running 0 CONNECT handlers
2023/02/21 01:36:54 [002] INFO: Accepting CONNECT to sourcegraph.com:443
2023/02/21 03:19:13 [003] INFO: Running 0 CONNECT handlers
2023/02/21 03:19:13 [003] INFO: Accepting CONNECT to sourcegraph.com:443
```

**Comment by DaedalusG** [comment]
After mulling it over even though setting `HTTPS_PROXY` will send the frontend traffic through a proxy and this will likely work, plus during testing I didnt see any unexpected requests go to the test proxy server -- its probably better to keep this discrete and stick with `TELEMETRY_HTTP_PROXY` to avoid any unexpected side effects

**Review by keegancsmith — APPROVED** [review]
LGTM. I still would prefer relying on the generic http_proxy envvars. If the customer doesn't like that idea, then lets ship this. But I would assume that if the customer in question was worried about doing too much external traffic, they can configure there proxy to lock us down.

**Pull request merged**
