### PR TITLE
extensibility: update registry extension sorting parameters

### LINKED ISSUE #21572: Extensions registry order is not deterministic
The extensions on the extension registry don't show up deterministically. Enabling/disabling & refreshing changes the orders and it's confusing. 

https://sourcegraph.com/extensions?category=All

Extensions registry order of extensions should be deterministic such that: 
- Anything I have enabled should show up first
- Then the remaining extensions in alphabetical order

### PR DESCRIPTION
**Pull request by tjkandala**
Fix #21572.

Registry extensions now sorted first sorted by name first.

Sort order:
- By name (`{host}/{publisher}/{name}` ID format)
- non-WIP extensions before WIP extensions
- "Prioritized" extensions first (this used to be all extensions included in user settings, but now it only includes enabled extensions)

Example:
Screenshot from 2021-06-08 13-56-24

### CODE REVIEW

**Comment by Joelkw** [comment]
@tjkandala @muratsu might be a dumb question but if we're sorting by name as defined (`{host}/{publisher}/{name}`) does that mean that an extension like sourcegraph/sourcegraph-lightstep is going to appear before an extension like z-name-company/z-name-company-asana (even if to the user that'd display as order: Lightstep, Asana)? Said another way, can we sort (or are we already) but just the `name` field in the package.json? 

A user's expectations are likely that it's an alphabetical order – even a deterministic order that a user can't quickly understand is going to appear random unless they're visiting the page a lot. (Here, it looks correct, but I know these are all our extensions, so I wasn't sure if it was just because publisher/name = sourcegraph/sourcegraph- for all of them.)

**Comment by tjkandala** [comment]
> @tjkandala @muratsu might be a dumb question but if we're sorting by name as defined (`{host}/{publisher}/{name}`) does that mean that an extension like sourcegraph/sourcegraph-lightstep is going to appear before an extension like z-name-company/z-name-company-asana (even if to the user that'd display as order: Lightstep, Asana)? Said another way, can we sort (or are we already) but just the `name` field in the package.json?

We sort by `name` in this PR: `sourcegraph/sourcegraph-lightstep` is the conventional repo name, not the extension ID, which is constructed from [publisher and name](https://github.com/sourcegraph/sourcegraph-lightstep/blob/master/package.json#L2-L3). We don't do any sort of formatting to remove "stuttering" from extension IDs, just split publisher and name along the `/`. So if those two extensions had the names `sourcegraph-lightstep` and `z-name-company-asana`, the Lightstep extension would unfortunately be shown before the Asana extension, but we don't encourage authors to name their extensions like that IIRC.

> A user's expectations are likely that it's an alphabetical order – even a deterministic order that a user can't quickly understand is going to appear random unless they're visiting the page a lot. (Here, it looks correct, but I know these are all our extensions, so I wasn't sure if it was just because publisher/name = sourcegraph/sourcegraph- for all of them.)
> 
> Otherwise, the ordering of non-WIP > WIP and enabled > all others is great! Confirming that it's enableds > enabled WIPs > disabled > disabled WIPs (not enableds > disableds > enabled WIPs > disabled WIPs).

Yes! We alphabetize first, then sort by WIP, then sort by enablement (all stable sorts)
Screenshot from 2021-06-11 11-07-14

**Comment by Joelkw** [comment]
@tjkandala how difficult would it be to use the actual "display name" / "name" field from the package.json? Especially because all of the extensions we've built have been named sourcegraph-{actual name}, anyone who publishes extensions to those categories will see things like our lightstep extension being ordered with the "S's", for example.

**Comment by tjkandala** [comment]
@Joelkw Apologies for my miscommunication, we do sort by `Name` [here](https://github.com/sourcegraph/sourcegraph/pull/21893/files#diff-ff0d9dfa9f3b97e84084e2e303fc66ba7e1ed2a0dbf5391ce450f7e0c7a4e489R95), which is the name field from the manifest

**Pull request merged**
