### PR TITLE
search: Add dashboard panels for sentinel queries

### PR DESCRIPTION
**Pull request by camdencheek**
This adds two panels to Grafana for monitoring sentinel queries. Quite
minimal right now. Just one that has the 90th percentile for all
sentinel queries, and one that has it split up by query. The first one
has an alert attached to it, the second is just for debugging if the
alert fires.

Followup work includes adding panels for error rates from sentinel
queries.

Screen Shot 2021-03-31 at 15 15 46

### CODE REVIEW

**Comment by stefanhengl** [comment]
Do we want to roll this out to customers already? Does that mean we roll out Search-blitz for customers too? Why don't we use the dedicated Grafana/Prometheus instead.

**Comment by camdencheek** [comment]
Can I modify sourcegraph.com grafana  without modifying these templates?

**Comment by stefanhengl** [comment]
Camden and I just discussed on zoom. Let's add these pannels in a collapsed form with a disclaimer/explanation why there is no data on Server per default.

**Comment by stefanhengl** [comment]
> Can I modify sourcegraph.com grafana without modifying these templates?

Not as far as I know.

**Review by stefanhengl — APPROVED** [review]

**Comment by pecigonzalo** [comment]
@stefanhengl Yes, its possible https://about.sourcegraph.com/handbook/engineering/observability/monitoring#creating-cloud-only-grafana-dashboards

**Comment by camdencheek** [comment]
That seems like the better solution until we want to make this available to customers. Closing this in favor of a cloud-only dashboard.

**Pull request closed without merging**
