### PR TITLE
sg: Install GNU find on macOS.

### PR DESCRIPTION
**Pull request by varungandhi-src**
At the moment, this is needed by the ./dev/generated.sh script,
since it uses GNU find's printf flag which is not supported
by BSD find.

## Test plan

Manually tested that it works. Still need to fix the script which uses `find` though.

Before:
before picture showing findutils being missing

After `sg` magic:
after picture showing GNU find being installed

### CODE REVIEW

**Review by bobheadxi — APPROVED** [review]

**Comment by varungandhi-src** [comment]
@jhchabran or @bobheadxi do you know which part of the code replaces `sed` invocations with `gsed` (I'd assumed we'd need to do something similar for `find` and `gfind`)? I searched for `gsed` and `gnu-sed`, but not getting any relevant hits...

**Comment by bobheadxi** [comment]
> Fixed by manually picking the right find in that one script for now.

IIRC this is the way, there's some code in the release tool that does this

**Comment by varungandhi-src** [comment]
Right, but not all uses of `sed` are doing that right now. 😞

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%5E%5Cs%2Bsed+-file:.*.md&patternType=regexp

**Comment by mrnugget** [comment]
(Sidenote: ideally we'd move `./dev/generate.sh` into `sg generate` completely, before we invest more time into `./dev/generate.sh`)

**Pull request merged**
