### PR TITLE
Move campaigns docs to batch_changes docs (no content changes)

### PR DESCRIPTION
**Pull request by mrnugget**
PREVIEW: https://docs.sourcegraph.com/@mrn-rename-docs-batch-changes/batch_changes

Note: Redirects only work locally, not on that preview

TODOs:

- [x] Move `doc/campaigns` to `doc/batch_changes`
- [x] Add redirects for files
- [x] Change content of docs to use "Batch change" & "Batch spec" instead of "Campaign" and "Campaign spec"

### CODE REVIEW

**Comment by malomarrec** [comment]
@mrnugget The CLI docs still references "campaigns" as a folder. Is that intended?

**Comment by malomarrec** [comment]
Should we merge this?

**Comment by mrnugget** [comment]
> Should we merge this?

I'll fix the build first.

**Comment by mrnugget** [comment]
I've just rebased, let's see if that helps.

**Comment by malomarrec** [comment]
Hang on, I forgot to add the "changed name" notice.

**Comment by LawnGnome** [comment]
I forgot to hit approve before merging — if anyone outside :badger: is interested, we did discuss this at sync this morning and agreed that it was ready to go after a final pass over the content.

**Pull request merged**
