### PR TITLE
Remove `start.sh` and switch to `sg` to run dev environment

### PR DESCRIPTION
**Pull request by mrnugget**
2 weeks ago, in #24988, we announced that we'll remove `start.sh` in 2 weeks. Time's up.

This the majority of `start.sh` but leaves a message in it saying that we switched to `sg` and where to find documentation.

It also removes all the shell scripts that `start.sh` used to boot up the dev environment that we don't need anymore, either because they're built into `sg` (such as the watchman configuration, wrapper, helper scripts) or because they're now in `sg.config.yaml` (where we'll step-by-step reduce them by building more into `sg`).

### CODE REVIEW

**Review by jeanduplessis — APPROVED** [review]
🚀

**Comment by mrnugget** [comment]
Side note to @bobheadxi @jhchabran: see 8fd2d88. I had to restore `dev/docsite.sh` because we use `docsite check` in CI. That's fine for now, I think, but ideally we'd use `sg` in CI to run this kind of stuff too so it's easy to reproduce locally if something fails. Maybe we can do something like `sg install-all && .bin/docsite check` or `sg run docsite -- new-args` etc.

**Comment by jhchabran** [comment]
> (...) ideally we'd use `sg` in CI to run this kind of stuff too so it's easy to reproduce locally if something fails. Maybe we can do something like `sg install-all && .bin/docsite check` or `sg run docsite -- new-args` etc.

I really like the idea and ideally I believe that the CI should be build on top of clearly identified interface that we use also locally as opposed to custom shell scripts that are made only for the CI (make it harder to maintain and it silos the knowledge). (RFC 484 broach that topic). 

It totally ties `sg` to the main repo though, which is something we probably want to keep in mind.

**Review by jhchabran — APPROVED** [review]

**Comment by mrnugget** [comment]
> It totally ties `sg` to the main repo though, which is something we probably want to keep in mind.

Yep, but I don't think it's bad. We _do_ have a monorepo and there are disadvantages that come with pulling something out of the repository.

**Review by eseliger — APPROVED** [review]

**Pull request merged**
