### PR TITLE
Fix(search): querying event logs breaks when "id" column value > int32

### PR DESCRIPTION
**Pull request by peterguy**
When querying `SearchResultsQueried` events on dotcom, got the error:

```
{
  "errors": [
    {
      "message": "sql: Scan error on column index 0, name \"id\": converting driver.Value type int64 (\"2524326457\") to a int32: value out of range",
      "path": [
        "node",
        "eventLogs",
        "nodes"
      ]
    }
  ],
  "data": {
    "node": null
  }
}
```

Turns out [the Event struct's ID column is `int32`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2c7d217730574575032ec9c88b656249cbdc00b8/-/blob/internal/database/event_logs.go?L206), while [the underlying database column is `bigint`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2c7d217730574575032ec9c88b656249cbdc00b8/-/blob/migrations/frontend/1648195639_squashed_migrations_unprivileged/up.sql?L885), which corresponds to Go's `int64`.

Changed the Event struct's `ID` column to `int64`.

Added a test to check handling of 64-bit integers.

## Test plan

Automated tests should pass.

New test should pass.

run this GraphQL query using a valid user ID (can be gotten from a `currentUser` query)

```
{ "query": "query EventLogsData($userId: ID!, $first: Int, $eventName: String!) {
    node(id: $userId) {
        ... on User {
            __typename
            eventLogs(first: $first, eventName: $eventName) {
                nodes {
                    argument
                    timestamp
                    url
                }
                pageInfo {
                    hasNextPage
                }
                totalCount
            }
        }
    }
}",
"variables": {
  "userId":"<base64-encoded user id>",
  "first":15,
  "eventName":"SearchResultsQueried"
},
"operationName": "EventLogsData"
}
```

## Changelog

- Address "value out of range" errors when querying the event logs

### CODE REVIEW

**Review by camdencheek — COMMENTED** [review]
Not a full review, but do we expose this via the GraphQL int type? IIRC, those must be int32 per GraphQL spec.

**Comment by peterguy** [comment]
> do we expose this via the GraphQL int type?

The ID field [is not exposed in the GQL API](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2c7d217730574575032ec9c88b656249cbdc00b8/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L9011-9044)

**Review by camdencheek — APPROVED** [review]
Thanks for the fix! 

While we're at it, we might want to change [AfterID](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e880a74850b609e17e31b8fd9b083d173191978f/-/blob/internal/database/event_logs.go?L390-390) to be an explicit `int64` since it refers to the same column

**Comment by peterguy** [comment]
Hmm, good point about `AfterID`, @camdencheek. It appears to be used [just once](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@79773e57ebb38c8b34e0de8a645782a4323f3ea9/-/blob/internal/own/background/recent_views.go?L50), and the [inputs for it](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@79773e57ebb38c8b34e0de8a645782a4323f3ea9/-/blob/internal/database/event_logs_scrape_state_own.go?L24-46) come from [a database table](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@79773e57ebb38c8b34e0de8a645782a4323f3ea9/-/blob/migrations/frontend/1682683129_add_recent_view_ownership_signal/up.sql?L16-23) whose column is defined as `int`.

I think I'll leave it alone for now, but create a followup issue to document it.

**Comment by camdencheek** [comment]
We expect that indexer job to also be broken then, right? Because the jobs it's storing will overflow the bookmark column type?

**Comment by peterguy** [comment]
>  that indexer job to also be broken
On certain systems, yes, it's probably broken.

**Pull request merged**
