### PR TITLE
repo-updater: Implement GitLab source

### PR DESCRIPTION
**Pull request by tsenart**
Part of #2025

- [ ] GitLab support
   - [x] --> **THIS PR** <-- Implement GitLabSource and enable new syncer for GitLab external services
   - [ ] Implement `gitlab.projects` to support enabled state deprecation.
   - [ ] Implement `gitlab.exclude` to support enabled state deprecation.
   - [ ] Change default `gitlab.projectQuery` to `["none"]`
   - [ ] Extend enabled state deprecation migration with GitLab external services

---
This change is [Reviewable](https://reviewable.io/reviews/sourcegraph/sourcegraph/3008)

### CODE REVIEW

**Comment by tsenart** [comment]
@keegancsmith: Please take a look.

**Comment by keegancsmith** [comment]
Argh sorry I thought reviewable.io would post a github review not a comment. Won't use it going forward.

**Comment by keegancsmith** [comment]
> rather than using a sync.WaitGroup of 1 here, just close(ch) inside of the above go func()

I see in a later PR you add more go routines, so nevermind

**Comment by tsenart** [comment]
> This actually has less chance than the others of being uppercase given it comes from a request from the frontend.

An external service kind is always upper case. I sometimes lower-case it for convenience only. We should normalize all of this at some point so that we don't have to switch around.

The reason the kinds are upper case is silly: Because the related original GraphQL constants were upper case. We should migrate.

**Pull request merged**
