### PR TITLE
Improve Cody's preamble to support multi-repo context

### PR DESCRIPTION
**Pull request by thenamankumar**
Improves Cody's context to clearly tell what repos are in the context and ask cody to suggestion the user add additional repos using the repo selector below the input box.

Also with each context files code snippet, include name of the repo the files belongs to. 
closes: #54002

## Test plan

- start a new chat
- Ask cody "explain sourcegraph/sourcegraph repo"
- Cody should apologise and ask to add additional repos to the context using the repo selector below the input box.
- Add sourcegraph/sourcegraph repo using the repo selector
- Again, ask cody to "explain sourcegraph/sourcegraph repo."
- Cody should reply correctly this time.
- Now, continue the same conversation by asking the same question for a different repo.

### CODE REVIEW

**Comment by mrnugget** [comment]
@thenamankumar how does this fare with the original prompts reported here? https://sourcegraph.slack.com/archives/C05AQ5LPAH1/p1687359093114659

**Comment by thenamankumar** [comment]
@mrnugget It correctly answers the question, "What does the repo `rrhyne/pageflow-figma-plugin` do?".

But if you extend the question to "What does the repo `rrhyne/pageflow-figma-plugin` do? If you don't know, remind me to select the repo in the context selector.", Cody gets confused and says it does not have enough context.

**Comment by mrnugget** [comment]
screenshot_2023-06-23_12 18 13@2x

Sweet

**Review by mrnugget — APPROVED** [review]

**Comment by almeidapaulooliveira** [comment]
Fantastic! Thanks, Naman.

**Pull request merged**
