### PR TITLE
Add (back) the ability to share links to code intel popover locations

### LINKED ISSUE #30698: Add (back) the ability to share links to code intel popover locations
#### Feature request description

Add back the ability to generate a shareable link to an identifier (code intel tooltip). As a user, I would like the ability to share a link to a specific code intel popover so that I can better communicate with my peers or document a specific token identifier. This contributes to our use cases for helping developer onboarding. 

Internal feedback: 
* [missing ability to send link to popover](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1642694595303100)
* [missing ability to generate URL](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1638880544350500?thread_ts=1638858834.347800&cid=CHXHX7XAS) prevents users from being able to share to token locations

How might we incrementally improve the j2d feature to incorporate back the ability to share URLs to a code intel popover?

#### Additional context

Prior to the token click-to-def implementation, users could click on a token, which would change the URL to be specific to the popover location. Since the [ j2d implementation](https://github.com/sourcegraph/sourcegraph/pull/28520), clicking now takes a user directly to the definition location and no longer generates a URL.

### PR DESCRIPTION
**Pull request by Numbers88s**
Add (back) the ability to share links to code intel popover locations 

CleanShot 2022-05-19 at 17 53 52

(note from Chris) There's a tiny 🐛  remaining: using browser back/forward to add/remove the `?popover=pinned` URL param should also show/hide the popover, but it currently remains hidden. If anyone finds this annoying, we can dig further to and fix it.

Resolves #30698

## Test plan
Manually tested

## App preview:

- [Web](https://sg-web-cesar-chris-30698-add-share-link.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-nctnzgjxma.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by chrismwendt — APPROVED** [review]
Cesar and I paired on this:

- Cesar created the UI button with the link icon
- I implemented the React/hoverifier/URL-params logic

**Comment by chrismwendt** [comment]
@valerybugakov Could we get your 👀  on this PR to make sure Cesar and I didn't do anything disastrous to the UI code?

**Review by Numbers88s — COMMENTED** [review]
LGTM 🚀

**Comment by jjinnii** [comment]
@chrismwendt @Numbers88s Couple items of feedback:

- See[ this thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1653469155353199) on implementing a success state
- It also looks like the horizontal divider isn't extending to the new copy link button
Screen Shot 2022-05-25 at 6 57 09 PM

Thank you for working on this! 
cc: @macraig

**Pull request merged**
