### PR TITLE
WIP gerrit FetchUserPerms function

### PR DESCRIPTION
**Pull request by mollylogue**
WIP implementation of gerrit FetchUserPerms function

I figured that this was going to be a sizable amount of code to review, so I wanted to get 👀  on it sooner rather than later.  I welcome any thoughts about the approach. I based my implementation off of the info in the [doc](https://docs.google.com/document/d/1tZ7L-bJOzjuzYWHmOfeg08LPVNhS_Z1p11KbRV56kWA/edit#heading=h.1y26xlp8rcjz) as well as the gerrit api docs

Outstanding questions:
- How should we paginate/batch when requesting the list of projects? (Keeping in mind that this will also be the size of the list of projects we request access info for at a time)
- I've just ignored the `"Revision"` field of the project access info for now. I'm assuming this will be a part of the sub-repo/branch-based permissions, so I figured we could handle it later on when we tackle the sub-repo perms?

Notable TODOS:
- caching on the provider is likely something we want to do to avoid a ton of redundant requests. Things to cache include list of all projects and project access info. 
- We'll want some metrics around this function, though I propose we create a separate issue for that and do it in a different PR.

## Test plan
- Full unit test suite to cover various cases
- Local testing against Gerrit api

### CODE REVIEW

**Comment by varsanojidan** [comment]
Hey Molly, just a question for my understanding, would FetchUserPerms get used for how we are currently working with Gerrit? It seems like its only used in perm_syncer [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go?L384:20&subtree=true). Which syncs UserPermissions for external accounts (i.e. OAuth) which atm I don't believe we are supporting OAuth user connections to Gerrit, just a master username/password in the config. Its also very possible I'm completely missing something here though 😅 .

**Comment by mollylogue** [comment]
> Hey Molly, just a question for my understanding, would FetchUserPerms get used for how we are currently working with Gerrit? It seems like its only used in perm_syncer [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go?L384:20&subtree=true). Which syncs UserPermissions for external accounts (i.e. OAuth) which atm I don't believe we are supporting OAuth user connections to Gerrit, just a master username/password in the config. Its also very possible I'm completely missing something here though 😅 .

So, it fetches the list of repos that the user has access to, which we end up storing in the DB in the user_permissions table. We'll also eventually want to fetch sub-repo permissions here. We aren't getting any actual authentication information here, just determining which repos this particular user has access to. Does that make sense?

**Comment by varsanojidan** [comment]
> > Hey Molly, just a question for my understanding, would FetchUserPerms get used for how we are currently working with Gerrit? It seems like its only used in perm_syncer [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go?L384:20&subtree=true). Which syncs UserPermissions for external accounts (i.e. OAuth) which atm I don't believe we are supporting OAuth user connections to Gerrit, just a master username/password in the config. Its also very possible I'm completely missing something here though 😅 .
> 
> So, it fetches the list of repos that the user has access to, which we end up storing in the DB in the user_permissions table. We'll also eventually want to fetch sub-repo permissions here. We aren't getting any actual authentication information here, just determining which repos this particular user has access to. Does that make sense?

Yeah I think that all makes sense. I think my only concern is that as far as I can see FetchUserPerms currently only gets called during the method fetchUserPermsViaExternalAccounts, and that method seems to use login connections created by things like OAuth in order to make requests to query for that user's accessible private repos (at least I think thats what the [github provider](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/authz/github/github.go?L320) is doing) which is different than how we currently set up the Gerrit connection. It could be very likely that im missing something though, so if we use FetchUserPerms elsewhere that would make a lot of sense.

**Comment by mollylogue** [comment]
> > > Hey Molly, just a question for my understanding, would FetchUserPerms get used for how we are currently working with Gerrit? It seems like its only used in perm_syncer [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go?L384:20&subtree=true). Which syncs UserPermissions for external accounts (i.e. OAuth) which atm I don't believe we are supporting OAuth user connections to Gerrit, just a master username/password in the config. Its also very possible I'm completely missing something here though 😅 .
> > 
> > 
> > So, it fetches the list of repos that the user has access to, which we end up storing in the DB in the user_permissions table. We'll also eventually want to fetch sub-repo permissions here. We aren't getting any actual authentication information here, just determining which repos this particular user has access to. Does that make sense?
> 
> Yeah I think that all makes sense. I think my only concern is that as far as I can see FetchUserPerms currently only gets called during the method fetchUserPermsViaExternalAccounts, and that method seems to use login connections created by things like OAuth in order to make requests to query for that user's accessible private repos (at least I think thats what the [github provider](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/authz/github/github.go?L320) is doing) which is different than how we currently set up the Gerrit connection. It could be very likely that im missing something though, so if we use FetchUserPerms elsewhere that would make a lot of sense.

For Github, yes, `FetchUserPerms` basically calls `FetchUserPermsByToken` for an individual user. But if you look at the perforce implementation, for example, we're using a single admin login on the code host connection and making calls to get permissions for each individual user in `FetchUserPerms`. `fetchUserPermsViaExternalAccounts` basically just uses an external account object (which we've created in the `FetchAccounts` function) to get the list of repos that user has access to. For Gerrit (and similarly for Perforce) we use a code host connection with an admin user. For Gerrit the external account object has the user's Gerrit account id, which we use within this `FetchUserPerms` function to get the list of groups this user belongs to. I do think you're right that we do things differently for Github, but this `Provider` interface is set up in such a way that it gives room to interpret the implementation of each function, as long as it satisfies the requirements. The only requirements here is that this function takes an external service account object (which we create in the `FetchAccounts` function so we can determine what info we need for Gerrit there), and returns a list of repos that this account has access to.

**Comment by eseliger** [comment]
As part of #wg-delete-week I am going to close this PR. If it’s still needed, feel free to reopen and restore the branch.

**Pull request closed without merging**
