### PR TITLE
Squash migrations for 3.16

### PR DESCRIPTION
**Pull request by efritz**
I like deleting code.

### CODE REVIEW

**Comment by keegancsmith** [comment]
Just check with distribution before merging this. I think they are considering changing our upgrade policy.

**Comment by efritz** [comment]
This leaves the last two releases of migrations alone.

**Comment by unknwon** [comment]
Just an idea, I'm interested in seeing how many migrations were squashed in each of these PRs to see some (possibly useless) trends. :D

**Comment by efritz** [comment]
> Just an idea, I'm interested in seeing how many migrations were squashed in each of these PRs to see some (possibly useless) trends. :D

cc @felixfbecker for squash insights!

**Pull request merged**
