### PR TITLE
dev/sg: allow providing list of lints to run

### PR DESCRIPTION
**Pull request by bobheadxi**
Allow `sg lint [lint] [lint] [lint]` - will be useful for https://github.com/sourcegraph/sourcegraph/issues/33363

## Test plan

Tab on first arg for full autocompletions:

Screenshot 2022-05-09 at 4 54 37 PM

Tab on second to continuously get autocompletions for other available checks:

Screenshot 2022-05-09 at 4 54 43 PM

Specify exactly the lint targets you want to run:

Screenshot 2022-05-09 at 4 54 50 PM

Default behaviour is still to run all:

Screenshot 2022-05-09 at 4 55 16 PM

### CODE REVIEW

**Comment by bobheadxi** [comment]
Current dependencies on/for this PR:
* main
  * **PR #35157** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/35157" target="_blank">Graphite</a> 
    * **PR #35199** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/35199" target="_blank">Graphite</a> 
      * **PR #35200** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/35200" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/35200?utm_source=stack-comment).

**Review by mrnugget — APPROVED** [review]
That's pretty cool!

**Review by jhchabran — APPROVED** [review]
Man, fixing the bash autocompletion, that's so nice 🙏

**Comment by bobheadxi** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/35200?utm_source=stack-comment).


Job Reference: gMG3cNPszcDFq0Xdjhqx

**Pull request merged**
