### PR TITLE
tenant: Introduce tenant_id to every table

### PR DESCRIPTION
**Pull request by eseliger**
We introduce the tenant_id column to every table without any magic enforcement or magic default value. Instead we default to NULL and plan to have an out of band migration. From out testing this change is instant since it is only a table metadata change. According to the documentation this sort of ALTER TABLE is instant since Postgres 11.

Test Plan: ran this migration against a clone of the s2 database.

### CODE REVIEW

**Comment by eseliger** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/64323?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#64323** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/64323?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#64322** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/64322?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#64271** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/64271?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @eseliger and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by keegancsmith** [comment]
This is on a clone of S2 DB. I had a few misstarts, but I ended up making sure the tenant_id column didn't exist (by manually running downgrades and using the downto subcommand). When watching the output of the migrator, the vast majority of time is actually spent in the migrator tool just checking for drift/etc and not the actual migration. (note I am in South Africa so its slow likely due to roundtrip time).

```
❯ SRC_LOG_LEVEL=debug time sg migration up --db all
⚠️ Running sg with a dev build, following flags have different default value unless explictly set: skip-auto-update, disable-analytics
✅ Connection to frontend succeeded
✅ Connection to codeintel succeeded
✅ Connection to codeinsights succeeded
INFO migrations.runner runner/options.go:98 Desugaring `upgrade` to `targeted up` operation {"schema": "codeinsights", "leafVersions": [1723117231, 1723127349]}
INFO migrations.runner runner/run.go:110 Checked current schema state {"schema": "codeinsights", "appliedVersions": [], "pendingVersions": [], "failedVersions": []}
INFO migrations.runner runner/run.go:121 Schema is in the expected state {"schema": "codeinsights"}
INFO migrations.runner runner/options.go:98 Desugaring `upgrade` to `targeted up` operation {"schema": "frontend", "leafVersions": [1723016879]}
INFO migrations.runner runner/run.go:110 Checked current schema state {"schema": "frontend", "appliedVersions": [], "pendingVersions": [], "failedVersions": []}
INFO migrations.runner runner/run.go:131 Schema is not in the expected state - applying migration delta {"schema": "frontend", "targetDefinitions": [1723016879], "appliedVersions": [], "pendingVersions": [], "failedVersions": []}
INFO migrations.runner runner/runner.go:307 Acquired schema migration lock {"schema": "frontend"}
INFO migrations.runner runner/runner.go:261 Checked current schema state {"schema": "frontend", "appliedVersions": [], "pendingVersions": [], "failedVersions": []}
INFO migrations.runner runner/run.go:189 Applying migrations {"schema": "frontend", "up": true, "count": 1}
INFO migrations.runner runner/run.go:357 Applying migration {"schema": "frontend", "migrationID": 1723016879, "up": true}
INFO migrations.runner runner/runner.go:313 Released schema migration lock {"schema": "frontend"}
INFO migrations.runner runner/run.go:160 Schema is in the expected state {"schema": "frontend"}
INFO migrations.runner runner/options.go:98 Desugaring `upgrade` to `targeted up` operation {"schema": "codeintel", "leafVersions": [1723117227, 1723127341]}
INFO migrations.runner runner/run.go:110 Checked current schema state {"schema": "codeintel", "appliedVersions": [], "pendingVersions": [], "failedVersions": []}
INFO migrations.runner runner/run.go:121 Schema is in the expected state {"schema": "codeintel"}
✅ Schema(s) are up-to-date!
       31.79 real         0.22 user         0.16 sys
```

**Review by eseliger — COMMENTED** [review]
Can’t approve as author but LGTM

**Comment by keegancsmith** [comment]
Busy auditing all "select *". using this command to find hits `git grep -n -i 'SELECT \*' -- '*.go'`

**Review by keegancsmith — APPROVED** [review]

**Pull request merged**
