### PR TITLE
enable CodeMirror file view by default

### PR DESCRIPTION
**Pull request by taras-yemets**
Follow-up on https://github.com/sourcegraph/sourcegraph/pull/47563

## Test plan
- CI passes
- `sg ci build main-dry-run` e2e tests pass: [buildkite](https://buildkite.com/sourcegraph/sourcegraph/builds/200836)

## App preview:

- [Web](https://sg-web-taras-yemets-enable-cm-blob-view.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by philipp-spiess — APPROVED** [review]
This needs a change log entry :)

**Comment by taras-yemets** [comment]
> This needs a change log entry :)

@philipp-spiess, we already have [this one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5380d0c887e484a15c3c96783f3b49187687addf/-/blob/CHANGELOG.md?L55&subtree=true&view=code) (it's a follow-up PR). Do you think we need another one?

**Comment by philipp-spiess** [comment]
Oh. Frogot about that one. Nope I think one mention is enough :D But didn't the other one go out in 4.5? 🤔

**Comment by taras-yemets** [comment]
> But didn't the other one go out in 4.5? 🤔

@philipp-spiess, unfortunately I forgot about these two. So probably, I'll add a note that CodeMirror is now a default editor for a references panel too.

**Comment by taras-yemets** [comment]
@philipp-spiess,  are you OK with explicitly disabling `enableCodeMirrorFileView` experimental setting for tests to pass so that we include this PR in the upcoming release?

I created a folllow-up issue:
- https://github.com/sourcegraph/sourcegraph/issues/48049

**Comment by philipp-spiess** [comment]
@taras-yemets Lets do that, sounds good!

**Pull request merged**
