### PR TITLE
web: move `HoverOverlay` styles out from the `.theme-redesign`

### PR DESCRIPTION
**Pull request by valerybugakov**
## Changes

- Moved `HoverOverlay` and `WebHoverOverlay` styles out from the `.theme-redesign`.
- Removed `useRedesignToggle` usage from the same components.

Part of the https://github.com/sourcegraph/sourcegraph/issues/20847.

### CODE REVIEW

**Review by tjkandala — APPROVED** [review]
Code looks good and manual testing on the webapp and browser extension went well.

Unrelated nit: `flash` class for badges doesn't look right with our new hover overlay styles
Screenshot from 2021-06-09 15-57-46

**Comment by valerybugakov** [comment]
Thanks for the find @tjkandala! Could you share a way you test the `HoverOverlay` UI on the code hosts with local changes? 

@felixfbecker [asked](https://github.com/sourcegraph/sourcegraph/pull/21347#pullrequestreview-668850458) about adding `flash` as a `badgeClassName` but in the [original issue](https://github.com/sourcegraph/sourcegraph/issues/19899) `label` class is mentioned. `label` looks great, I'm updating it now.

**Comment by felixfbecker** [comment]
I must have confused the two, my bad. `flash` is the alert class, `label` is the badge class.

**Comment by valerybugakov** [comment]
@felixfbecker, my bad that I didn't check it 🙂. Good, that we caught this issue. 

Maybe you have some insight on how to test local changes on code hosts? What I've been doing — is just opening hover overlay on the code host and manually adding classes to the relevant element, which is time-consuming.

**Comment by felixfbecker** [comment]
You can build the browser extension locally in dev/watch mode and sideload it into your browser: https://github.com/sourcegraph/sourcegraph/blob/main/client/browser/README.md#development
Then you can test it on any PR on different code hosts.

**Pull request merged**
