### PR TITLE
Include code insights from the backend in the webapp

### PR DESCRIPTION
**Pull request by felixfbecker**
This merges both insights from the backend and views from extensions and displays them both.

Didn't really test this cause I wasn't sure how to add data to the DB for testing.

- [x] TODO: constrain the timeframe.

### CODE REVIEW

**Comment by slimsag** [comment]
How I tested this:

1. Enable feature flag in **Global settings** `"experimentalFeatures": {"codeInsights": true}` TODO(slimsag): send PR to enable by default in dev environments
2. In **Global settings** add:

```
  "insights": [
    {
      "title": "fmt usage",
      "description": "fmt.Errorf/fmt.Printf usage",
      "series": [
        {
          "label": "fmt.Errorf",
          "search": "errorf",
        },
        {
          "label": "printf",
          "search": "fmt.Printf",
        }
      ]
    }
  ]
```

3. Open psql prompt and run the following to add fake data:

```
docker exec -it codeinsights-db psql -U postgres
```

```sql
WITH e AS(
    INSERT INTO repo_names(name)
    VALUES ('github.com/gorilla/mux-original')
    ON CONFLICT DO NOTHING
    RETURNING id
)
SELECT * FROM e
UNION
    SELECT id FROM repo_names WHERE name='github.com/gorilla/mux-original';
WITH e AS(
    INSERT INTO repo_names(name)
    VALUES ('github.com/gorilla/mux-renamed')
    ON CONFLICT DO NOTHING
    RETURNING id
)
SELECT * FROM e
UNION
    SELECT id FROM repo_names WHERE name='github.com/gorilla/mux-renamed';
WITH e AS(
    INSERT INTO metadata(metadata)
    VALUES ('{"hello": "world", "languages": ["Go", "Python", "Java"]}')
    ON CONFLICT DO NOTHING
    RETURNING id
)
SELECT * FROM e
UNION
    SELECT id FROM metadata WHERE metadata='{"hello": "world", "languages": ["Go", "Python", "Java"]}';
 INSERT INTO series_points(
     time,
     series_id,
     value,
     metadata_id,
     repo_id,
     repo_name_id,
     original_repo_name_id)
SELECT time,
    0,
    random()*80 - 40,
    (SELECT id FROM metadata WHERE metadata = '{"hello": "world", "languages": ["Go", "Python", "Java"]}'),
    2,
    (SELECT id FROM repo_names WHERE name = 'github.com/gorilla/mux-renamed'),
    (SELECT id FROM repo_names WHERE name = 'github.com/gorilla/mux-original')
    FROM generate_series(TIMESTAMP '2020-02-16 00:00:00', TIMESTAMP '2021-02-16 00:00:00', INTERVAL '720 min') AS time;
```

4. Navigate to http://localhost:3080/insights and see:

image

**Comment by slimsag** [comment]
With 1 data point per 12h, and showing the last 1mo of data it looks like this:

image

**Comment by slimsag** [comment]
So I think even with 1 point/day, there will be cases where we want to display a larger timeframe without necessarily showing each data point. e.g. we have 365 data points to show, but only want to actually show 12 (1 per month) to the user. One option is obviously do to this on the frontend, but better would be if we could not request that data in the first place. I will start looking into options here with ways we can support querying that (I think we can do something like offer less granular querying).

In the meantime, I have pushed up a commit which makes the backend assume the last 30d of data if no `from` parameter is specified. This is good to have in place for the backend anyway ("give me EVERYTHING" is a bad default.)

I will merge this now as-is so we can iterate on this.

**Review by slimsag — APPROVED** [review]

**Comment by felixfbecker** [comment]
> So I think even with 1 point/day, there will be cases where we want to display a larger timeframe without necessarily showing each data point. e.g. we have 365 data points to show, but only want to actually show 12 (1 per month) to the user. One option is obviously do to this on the frontend, but better would be if we could not request that data in the first place.

Agree. There is some "resolution" that makes sense for each graph, i.e. the interval between each returned data point between from and to, or in other words the amount of data points returned. This would be ideally controlled through an API parameter, because graphs can be resized and you need more data points the larger the graph is on screen. Whether the parameter is a count, or an interval shouldn't matter as much. The campaigns burndown chart has an API that supports this I think.

**Pull request merged**
