### PR TITLE
[fixes #2761] Update remote selection to prefer 'upstream' and 'origin'

### LINKED ISSUE #2761: VS Code extension opens to incorrect remote
Open on Sourcegraph action of the VS Code extension picks the wrong remote.

It picks the first remote alphabetically instead of "origin"

### PR DESCRIPTION
**Pull request by potterbm**
## Test plan

- Add a new remote to the git repo `git remote add`
- Observe that the remotes list now returns two results and that `origin` is preferred

### CODE REVIEW

**Comment by jdorfman** [comment]
@potterbm when it's ready please tag me if there is no movement on our end. =)

**Comment by philipp-spiess** [comment]
@cla-bot check

**Comment by philipp-spiess** [comment]
Hey @potterbm, thanks a ton for this contribution! The change looks great, I see that the PR is marked as a draft-was this on purpose or an oversight? I think we can merge it otherwise and I'll see to get a release out as quickly 🙂 

cc @sourcegraph/code-exploration-devs

**Comment by potterbm** [comment]
@philipp-spiess It was only marked as a draft because I didn't have a test plan yet. I made this change after looking into the code to see why this behavior was happening, so I figured I should at least run it locally once.

That said, it's a super simple change so if you're okay with the eye test I'm happy to skip that step (I'll probably have time for it Thursday or Friday)

**Comment by philipp-spiess** [comment]
@potterbm No worries! It's a bit late right now in Vienna but I can test it locally tomorrow. I need to see if the build scripts still work anyway (😅). I'll go ahead and merge it then if it's good. Thanks again!

**Review by philipp-spiess — APPROVED** [review]

**Comment by philipp-spiess** [comment]
(This is ready to merge, I’m just trying to get CI to agree with me)

**Comment by philipp-spiess** [comment]
Thanks again @potterbm :)

**Comment by potterbm** [comment]
@philipp-spiess Thanks for the update! If I can do anything to help, let me know!

**Comment by philipp-spiess** [comment]
@potterbm The update is out now :)

**Pull request merged**
