### PR TITLE
[config] Refactor conf.Get().ExternalURL to globals.ExternalURL

### PR DESCRIPTION
**Pull request by cesrjimenez**
As part of our ongoing effort to streamline the admin onboarding while improving the runtime update process, I'm proposing an update that involves replacing all instances of `conf.Get().ExternalURL` with `global.ExternalURLString`. With the previous `conf.watch()` on `global.ExternalURLString`, this change allows us to instantly see modifications without needing a server restart.

## Key Changes

1. **Direct References Update**: All the places where `conf.Get().ExternalURL` was directly referenced have now been updated to `globals.ExternalURL`.
2. **Function Calls**: Updated function signatures and implementations where `conf.Get().ExternalURLString` was being used.
3. **Tests Updated**: Modified unit tests to reflect this change. Ensured all related tests pass.
4. **Documentation**: Updated relevant documentation and comments to reflect this change.

## Benefits

- **Performance:** By leveraging `conf.watch()`, we no longer need to interrupt services or deal with potential downtimes that come with server restarts just to see configuration changes related to ExternalURL.
- **Code Clarity:** A single source of truth (`globals.ExternalURLString`) is always easier to maintain and less prone to bugs.
- **Scalability:** Future configurations that require real-time updates can benefit from this setup, making our configuration management more scalable.

## Test plan

1. Ran the entire test suite to ensure no regressions.
2. Manually tested areas heavily reliant on ExternalURL to ensure there are no unforeseen side effects.
3. Checked other configurations to ensure they don’t behave unexpectedly due to this change.

## Feedback

Would appreciate eyes on this, especially those familiar with modules heavily dependent on ExternalURL. Let's ensure we haven't overlooked any potential edge cases.

### CODE REVIEW

**Comment by cesrjimenez** [comment]
One question I have which I haven't decided on yet is, should I move the globals file off of `cmd/` directory and into `internal/`?  

It's a larger change, but I'm wondering what y'all think?

**Comment by camdencheek** [comment]
Does `WatchExternalURL` get called in all services? Otherwise, I don't think this will get set consistently.

**Comment by cesrjimenez** [comment]
> Does `WatchExternalURL` get called in all services? Otherwise, I don't think this will get set consistently.

`WatchExternalURL` gets called in `repo-updater` and `frontend`.

The updated references are contained to 
- frontend
- internal/batches
- internal/codemonitors

Is there any other service you think I'm missing and I should include for the references above?

**Review by BolajiOlajide — APPROVED** [review]
My knowledge of how this change affects other services is limited. However, from a code PoV it looks good to me. I also pulled and tested locally with Batch Changes and it works.

**Comment by camdencheek** [comment]
@cesrjimenez, mostly I'm just concerned that adding a reference looks harmless, but will actually just silently not work. Can we maybe just start the watcher behind a sync.Once?

**Comment by cesrjimenez** [comment]
> @cesrjimenez, mostly I'm just concerned that adding a reference looks harmless, but will actually just silently not work. Can we maybe just start the watcher behind a sync.Once?

Absolutely @camdencheek same here for sure. Currently the `WatchExternalURL` is using this `watchExternalURLOnce` which is a `sync.Once`. See [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/globals/globals.go?L31).

Unless I'm missing something, which I might be so please let me know ✌️

**Review by unknwon — APPROVED** [review]
nothing stands out to me

**Comment by camdencheek** [comment]
Yes! I'm thinking that we should start the watcher inside `ExternalURLString` so the caller doesn't have to check that the watcher is set up in their service.

**Comment by camdencheek** [comment]
(I'm not at a computer, so my descriptions may be a bit incomplete. No need to block on my comments though)

**Comment by cesrjimenez** [comment]
> Yes! I'm thinking that we should start the watcher inside `ExternalURLString` so the caller doesn't have to check that the watcher is set up in their service.

Happy to discuss further and potentially address it in a follow up PR 👍

**Comment by keegancsmith** [comment]
I'm a bit confused how this is any different. conf.Get() is updated as the config is updated. Additionally there is now the footgun that we have to call Watch in each service that needs this. For example I can imagine subtly depending on this behaviour in a worker with some random other change. I think at minimum we should atleast automatically start up the watcher as Camden suggests, but at the same time I don't really understand the purpose of this change given conf.Get is always up to date.

**Comment by cesrjimenez** [comment]
> I'm a bit confused how this is any different. conf.Get() is updated as the config is updated. Additionally there is now the footgun that we have to call Watch in each service that needs this. For example I can imagine subtly depending on this behaviour in a worker with some random other change. I think at minimum we should atleast automatically start up the watcher as Camden suggests, but at the same time I don't really understand the purpose of this change given conf.Get is always up to date.

It was my understanding that if the externalURL is updated in the site config page then we would need to restart the server in order for those changes to be reflected. Which is why there was [this line](https://github.com/sourcegraph/sourcegraph/pull/56916/files#diff-02de42f3502454a51559dda612207e637b02c921e3303521fb151cf0c96218e3L45). This [comment](https://github.com/sourcegraph/sourcegraph/pull/56916/files#diff-5d6cf90ff543c3bfd72279aeb6c76168a8c55a76d4fb830512fad5041034770dL29) was largely contributing to my assumptions.

**Comment by keegancsmith** [comment]
The variable you are creating is still backed by the same site config. The reason that variable was originally listed in that list was because something would read the value of ExternalURL near startup then never read it again leading to an issue. This change I don't believe fixes that if that indeed is still a problem.

So unfortunetly this PR doesn't resolve that issue :(

**Comment by cesrjimenez** [comment]
> The variable you are creating is still backed by the same site config. The reason that variable was originally listed in that list was because something would read the value of ExternalURL near startup then never read it again leading to an issue. This change I don't believe fixes that if that indeed is still a problem.
> 
> So unfortunetly this PR doesn't resolve that issue :(

I see. I just talked to Camden about his comment. Ideally we would use conf.Get() everywhere instead of the globals.ExternalURL, specifically to avoid having to call and rely on the Watch + global variable. I'll be on the lookout where an additional syncOnce is used to find the reason why we would need to restart the server if externalURL changes (if there is still a reason to do so).

Let me know what you think of the approach.

**Pull request merged**
