### PR TITLE
Enable Zoekt ranking by default

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

**Comment by olafurpg** [comment]
Good idea, I added an entry to the changelog

**Comment by keegancsmith** [comment]
Pushed a fix for es-lint, lets hope we get a green circle now

**Comment by olafurpg** [comment]
I forgot this PR hadn't landed yet. The last commit should fix the last eslint error

**Comment by keegancsmith** [comment]
@olafurpg it looks like the UI review picked up a real change. I can't tell if the new results are correct or not, what do you think? It looks like we now sometimes add in a "1 more result", even though in both the old and new view the result count is the same (12). Hard to tell, it seems it doesn't render all the matching hunks in those test?

**Comment by olafurpg** [comment]
The failing tests are using hand-written results. I'm investigating if the results are wrong or if the rendering is buggy

**Comment by keegancsmith** [comment]
> I'm investigating if the results are wrong or if the rendering 
> is buggy

Thanks

**Comment by olafurpg** [comment]
Short update: I'm still investigating and I suspect the storybook has buggy data. I'm unable to reproduce the same behavior with real-world data

CleanShot 2022-01-18 at 11 40 29@2x

Looking into the storybook data now.

**Comment by olafurpg** [comment]
The UI diff origins from the fact that zoekt ranking displays 5 hunks by default while line ranking displays 10. Updating the zoekt default to 10 hunks removes the UI diff.

The golden data for the tests in `searchTestHelpers.ts` is outdated, I can't even reproduce the current storybook UI with line ranking against real-world data. The empty hunks should not be part of the UI

 Updating the golden data should fix the issue but I'm inclined to accept the UI diff and merge without changing the code.

**Comment by olafurpg** [comment]
Clicking on the "1 more" button for zoekt ranking displays one more empty hunk.

CleanShot 2022-01-18 at 12 38 41

I don't consider it a bug in the zoekt ranking, it's more a quirk with the input data.

**Comment by olafurpg** [comment]
OK, merging this. I reduced the number of hunks from line ranking and got the same UX as with zoekt ranking

CleanShot 2022-01-18 at 13 33 41

The golden data is outdated and should be updated, but I don't think we should block this PR because of that.

**Comment by keegancsmith** [comment]
Thank you for investigating! Long live actual ranking.

**Pull request merged**
