### PR TITLE
security: enable public access of our GraphQL/Search/etc APIs from any domain/origin

### LINKED ISSUE #18847: Bug: Using Sourcegraph.com GraphQL API from other websites is broken
Problem: If you try to use `https://sourcegraph.com/.api/graphql` from another website, it is blocked due to CORS ~because we're not setting any `Content-Security-Policy` for responses from that URL, it defaults and is thus blocked:~

~Content Security Policy: The page’s settings blocked the loading of a resource at https://sourcegraph.com/.api/graphql?SearchContexts (“default-src”).~

**Are you ready for some history?**

* Based on my memory, we have always intended for the Sourcegraph.com GraphQL API to be used as broadly and accessibly as possible - including by other websites, by unauthenticated users on https://sourcegraph.com/api/console, via the `src` CLI, and literally everywhere else.
* We explicitly designed the CORS handling of the GraphQL API to _only ever allow cookie-based session auth_ [_if on the same domain_ (in so-called "non-simple" CORS requests)](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/session/session.go#L299-337)
* This is closely related to this old issue I have open about [removing our redundant CSRF cookies #7658](https://github.com/sourcegraph/sourcegraph/issues/7658) and if you're wondering "how is that secure?" see [my detailed write-up here back in 2018](https://github.com/sourcegraph/sourcegraph/issues/227#issuecomment-426482380) which is still true today - or this more brief explanation of [OWASP: using custom request headers to prevent CSRF](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#use-of-custom-request-headers).

In short:

1. ~https://sourcegraph.com/.api/graphql should have a `Content-Security-Policy` which allows requests from any origin.~
2. ~This should be completely safe and secure to enable, and was the original intended behavior - but **obviously** needs verification.~

### LINKED ISSUE #23140: no CORS header for streaming API
No CORS header is set for streaming API, in particular, lack of `Access-Control-Allow-Origin` means browser requests from domains other than sourcegraph.com are blocked. Here's where most of our streaming headers are set:

https://github.com/sourcegraph/sourcegraph/blob/099c4418d881924f912b770004a3b8ca56845cf4/internal/search/streaming/http/writer.go#L32-L40

I think it makes sense to support for other web apps to use (related to https://github.com/sourcegraph/sourcegraph/issues/18847.  I'm not sure whether we confirmed that we allow GQL requests from other origins since that was posted though--I'll see if I can confirm)

### PR DESCRIPTION
**Pull request by slimsag**
This PR enables public access of Sourcegraph APIs from any domain / origin securely, and  without enabling CSRF attacks against Sourcegraph. This works for all Sourcegraph instances (Sourcegraph.com, on-prem, etc.) Here's how:

* Requests to our API may now be made from any domain/origin (jsfiddle.net, attacker.com, friendly.com, trusted.com, etc.) which would've previously been blocked by our CORS policies unless it was a trusted domain (e.g. in `corsOrigin` allow list)
* Through our CORS policies, browsers are permitted to include authorization (session cookies, access tokens, etc.) in all requests to our API in order to authenticate with Sourcegraph, even if the request came from an untrusted origin.
* Iff the request came from an untrusted origin (e.g. not in the `corsOrigin` allow list), then session-based authentication (cookies) sent with the request are NOT respected even if present: the request will be treated as unauthenticated. This is what protects our API from CSRF attacks while still allowing public usage both anonymously and with e.g. access tokens.
* All requests still go through our regular authorization mechanisms, e.g. most on-prem customers do not have anonymous access enabled in their site configuration and so for them the only way to use their Sourcegraph instance API from an untrusted domain would be to supply an access token.

See also the diagrams added in https://github.com/sourcegraph/sourcegraph/pull/27937 which cover this. I suggest reviewing the commits in this PR individually, the first one makes the simple code change and all subsequent ones just add detailed explanations for why this is secure.

Fixes #18847
Fixes #23140

### CODE REVIEW

**Comment by slimsag** [comment]
I will add a CHANGELOG entry tomorrow, but PTAL!

**Review by rvantonder — APPROVED** [review]
My review wasn't requested but I'm subscribed to the issue and am approving on behalf of team #FixCORS 😄

**Review by andreeleuterio — APPROVED** [review]
So happy for this improvement! @slimsag 🦸

**Comment by slimsag** [comment]
Merging, once deployed I will put together some demos that show off using our API from e.g. jsfiddle.net

**Pull request merged**
