### PR TITLE
Fix Simple UI loading flashes

### LINKED ISSUE #39740: Performance: Eliminate flicker when navigating from file blob -> search results
### Description

Our application tends to flicker when navigating back in the browser to search results. The browser isn't making any new network requests, it just seems that we re-render some critical elements that the browser can't reuse.

Example from @quinnkeast: https://share.cleanshot.com/C0UEod

Note: This may be partially related to a bug in the simple UI where it flickers unnecessarily: [Slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1658935242055789)

### PR DESCRIPTION
**Pull request by novoselrok**
Fixes #39740

## Old

https://user-images.githubusercontent.com/6417322/184857371-ae7eaf61-297c-4349-be28-f057ebd5d351.mov

## New

https://user-images.githubusercontent.com/6417322/184857410-9ab8e925-c4c2-4214-81f0-9585cfcd97a0.mov

## Test plan

* Enable Simple UI
* Do a search
* No old UI flash should happen
* Go to the file page
* Again, no old UI should flash

## App preview:

- [Web](https://sg-web-rn-fix-core-workflow-enabled.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-shlsgchimq.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by vovakulikov — APPROVED** [review]
LGTM
Minor: I'm wondering about the `useTemporarySetting` hook improvements. I thought that the GQL backend for useTemporarySetting manager uses the apollo client, and this means we could use apollo client cache to avoid multiple fetches for one flag in different places.

**Comment by novoselrok** [comment]
> LGTM Minor: I'm wondering about the `useTemporarySetting` hook improvements. I thought that the GQL backend for useTemporarySetting manager uses the apollo client, and this means we could use apollo client cache to avoid multiple fetches for one flag in different places.

I think we already use the Apollo client for temporary settings. The issue is that each time the `useTemporarySetting` hook was called, the returned observable had to be resolved, and that takes a small amount of time, even if the temporary settings were already cached/loaded.

**Comment by vovakulikov** [comment]
@novoselrok, yeah, this is what I meant and as I said, I think this solution fixes the problem with flashing for the search screen but the `useTemporary` hook in general has some core problem with data loading and fetching and caching. I'm wondering how could we fix this problem in general. Should we introduce our own level of cache in the temporary setting manager or we can read apollo cache in a sync way and change the API from async to sync observables or sync values?  

cc @limitedmage

**Comment by vovakulikov** [comment]
By the way, just for the record, this is not the first problem with temporal settings caching. I recently found a similar to this PR problem around sidebar state in the simple UI mode https://github.com/sourcegraph/sourcegraph/issues/39434

**Comment by novoselrok** [comment]
I guess this PR makes sense as a temporary solution because the flashing UI is really annoying. If a more general solution is possible we could explore that separately.

**Pull request merged**
