### PR TITLE
[SG-43144]: Tables in code excerpts should use headers for line numbers

### PR DESCRIPTION
**Pull request by gitstart-sourcegraph**
## Description
ArcToolkit says the tables used for search results are confusing because a11y tools can't tell if the table is tabular data or used for layout purposes. We need to clarify this.

## Ref
[SG Issue](https://github.com/sourcegraph/sourcegraph/issues/43144)
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-43144)

## Success criteria
The table should switch the line numbers from being `<td>` to `<th>`. This will clarify that this is indeed a table with tabular data. ArcToolkit should not show alerts about tables.

## Test plan
- The issue mentioned above should be fixed

## App preview:

- [Web](https://sg-web-contractors-sg-43144.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/contractors/SG-43144/compare-report.html;tab=live_object) for a full comparison between the commits cb3ebdc and fd199d7 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by gitstart-sourcegraph — COMMENTED** [review]
Hi @umpox @limitedmage
Since layout and html structure of the `line-number` and `code` has been formulated on the backend part of the codebase, want to confirm with you before making the change in the following files to update the HTML tag used.
- `cmd/frontend/internal/highlight/highlight.go`
- `cmd/frontend/internal/highlight/html.go`

Screenshot 2022-10-21 at 2 55 57 PM (1)

WDYT?

**Comment by limitedmage** [comment]
Yes, looks like fixing this does require backend changes. Let's go ahead and do them. If you need help with this let me know.

**Comment by limitedmage** [comment]
I'm running this locally but the line numbers still seem to be rendered as `td` for me? 
image

**Comment by gitstart-sourcegraph** [comment]
@limitedmage Sorry, we missed the required changes in `syntax-highlighter` image, for testing this we have to build it to get the updated image locally and run `sg start oss` with it.

These are steps:

- Run `docker build -t sourcegraph/syntax-highlighter:local .` in `docker-images/syntax-highlighter` directory (it would take much time)
- In `sg.config.yaml > syntax-highlighter > cmd` change `sourcegraph/syntax-highlighter:insiders` to `sourcegraph/syntax-highlighter:local`
- Run sg start oss 

Could you please help to recheck?

**Comment by limitedmage** [comment]
@camdencheek or @slimsag can you please review the backend code for this? Thanks!

**Review by camdencheek — APPROVED** [review]
Backend looks good to me 👍

**Comment by limitedmage** [comment]
@gitstart-sourcegraph I'm running the change and it works great in search results, but it breaks line numbers in the blob view: 
image

It looks like [we have quite a few places where we look for `td.line`](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+td.line&patternType=lucky). I think these need to be updated to `th.line` to match this new layout.

**Comment by limitedmage** [comment]
@gitstart-sourcegraph  Looks like there are some regressions in the Percy tests, can you take a look?

**Comment by gitstart-sourcegraph** [comment]
@limitedmage we updates PRs to fix UI diffs. Could you please help to check if we missed anything else?

**Review by limitedmage — APPROVED** [review]
Thank you for your thoroughness with this larger-than-expected change. I tested it locally and it looks good!

**Review by valerybugakov — APPROVED** [review]
LGTM!

**Pull request merged**
