### PR TITLE
Adding reset (new) chat button to Cody sidebar

### PR DESCRIPTION
**Pull request by almeidapaulooliveira**
Add the reset (new) chat button to the Cody sidebar. This is useful when users want to reset the conversation entirely.

## Test plan
- The reset button should reset the entire chat and display recommendations when clicked. When a new prompt it's submitted, the conversation can't display old messages.
- The reset button should appear only when the chat isn't presenting errors, isn't loading, and embeddings are available.

Screenshot 2023-04-15 at 10 47 25 AM

- The reset button shouldn't appear when a loading state is visible.

Screenshot 2023-04-15 at 10 47 39 AM

- The reset button shouldn't appear when embeddings aren't available.

Screenshot 2023-04-15 at 10 46 58 AM

- The reset button shouldn't appear when an error is visible.

Screenshot 2023-04-15 at 10 51 40 AM

## App preview:

- [Web](https://sg-web-paulo-cody-new-chat-button.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by almeidapaulooliveira** [comment]
@cla-bot check

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.38 kb) | 0.00% (+0.38 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/paulo/cody-new-chat-button/compare-report.html;tab=live_object) for a full comparison between the commits 917be86 and e20017e or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by almeidapaulooliveira** [comment]
@cla-bot check

**Comment by almeidapaulooliveira** [comment]
@cla-bot check

**Comment by almeidapaulooliveira** [comment]
@cla-bot check

**Comment by almeidapaulooliveira** [comment]
@cla-bot check

**Comment by almeidapaulooliveira** [comment]
@cla-bot check

**Review by philipp-spiess — APPROVED** [review]

**Pull request merged**
