### PR TITLE
Small UI Fixes

### PR DESCRIPTION
**Pull request by francisschmaltz**
Small UI Fixes

### CODE REVIEW

**Comment by francisschmaltz** [comment]
@dadlerj @sqs This removed the search banner for installing Sourcegraph. After looking at analytics, it accounts for 5-6% of the install clicks from Sourcegraph.com while searching. I think that this banner doesn't provide enough value and should be removed.

screen shot 2018-11-12 at 1 48 12 pm

screen shot 2018-11-12 at 12 06 57 pm
screen shot 2018-11-12 at 12 07 19 pm

**Comment by dadlerj** [comment]
5% isn't much, but at the same time that is still ~50 clicks per month. The goal here was to make people realize that it's possible to get this for their private code right when they're getting value from sourcegraph.com. I'm curious, do you have any ideas for how to make this clear, without it being ugly/taking that real estate?

**Comment by sqs** [comment]
It serves an informational purpose - it addressed confusion by users “how do I search across private code?”

So you should find a way to still address that problem in this PR. For example, just make it dismissible.

**Comment by francisschmaltz** [comment]
These changes are stale and were address in `fs/ui-fix-round-3` and `4`

**Pull request closed without merging**
