### PR TITLE
Cody Web: Fix no embeddings use case

### PR DESCRIPTION
**Pull request by philipp-spiess**
Reported here: https://github.com/sourcegraph/sourcegraph/pull/51072#issuecomment-1521295540

Right now, Cody web simply crashes when encountering a repo that has no embeddings. This is because it falls back to the keyword based implementation which throws on the web (we won't have it there for a while, because the vs code extension uses a native library to implement that).

Since Cody is now useful even for unindexed repos (because we add the currently viewed file into the context automatically), I think making it gracefully handle this situation is better than disabling Cody for these views.

## Test plan

Screenshot 2023-04-25 at 12 15 13

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.02 kb) | 0.00% (+0.02 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/cody-web-fix-no-embeddings-use-case/compare-report.html;tab=live_object) for a full comparison between the commits 05c16fa and b6f6629 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by abeatrix — APPROVED** [review]
LGTM thanks for the quick turnaround 🐐

**Comment by almeidapaulooliveira** [comment]
The 'react-component' in red at the bottom indicates a lack of embedding error (or warning)? I'm wondering how to better communicate this to users.

**Comment by mrnugget** [comment]
I think red might be too agressive (here and in VS Code), since it's "normal" that some repositories don't have embeddings (and Cody in VS Code should work without Sourcegraph and not yell "error error!")

**Comment by philipp-spiess** [comment]
@mrnugget Yeah, agree! I think this also needs a better explaination, maybe a tooltip on the icon that explains what this even means (as a user, I might have no idea what embedding or keyword even means). I'll do this as a follow-up improval.

**Pull request merged**
