### PR TITLE
Use npmjs.org instead of yarnpkg.com

### PR DESCRIPTION
**Pull request by nicksnyder**
This is an attempt to fix the recurring flakiness that we have been seeing in our builds by switching to npmjs.org

```
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/mdi-react/-/mdi-react-4.0.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/buildkite/builds/buildkite-agent-797f4d46cb-slr2l-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

see https://github.com/yarnpkg/yarn/issues/2508#issuecomment-283655600

### CODE REVIEW

**Comment by nicksnyder** [comment]
hmm, build still fails with a similar message. I don't understand why it is hitting yarnpkg.com

https://buildkite.com/sourcegraph/sourcegraph/builds/23218#c75c5814-bba5-45de-8c04-8ee6f713e6b9

**Comment by felixfbecker** [comment]
But the log now says npm:
```
error An unexpected error occurred: "https://registry.npmjs.org/date-fns/-/date-fns-2.0.0-alpha.25.tgz: ESOCKETTIMEDOUT".

```

**Comment by sqs** [comment]
Possible reason why yarn is flakier than npm: https://github.com/yarnpkg/yarn/issues/5706#issuecomment-421509620

**Comment by nicksnyder** [comment]
> But the log now says npm:

Oops, I could have sworn it still said yarn.

The next thing I will try is increasing the timeout

**Comment by nicksnyder** [comment]
Are you in favor of merging this even though it doesn't solve our flakiness problem?

**Comment by felixfbecker** [comment]
Yes definitely. Useless Facebook proxy

**Pull request merged**
