### PR TITLE
codemirror blob view: Add support for reference panel (and fix some things)

### PR DESCRIPTION
**Pull request by fkling**
This commit adds support for using the blob view in the reference
panel. Besides handling the reference panel specific props
(`disableStatusBar`, `disableDecorations`), I also had to make some
changes to make selecting lines and scrolling them into view work
properly.

The biggest change is which selection information is sent to the
extension host. Instead of sending the editor's cursor position, I'm now
sending the selected lines, which is what the old blob view does. This
also fixes the issue with showing line decorations for selected
lines (instead of just line where the current cursor is).

Having a real cursor is still enabled because we need that for search
(Meta+f) to work.

Demo: (the first part shows how line decorations are updated as the user selects additional lines)

https://user-images.githubusercontent.com/179026/183598410-b361f3ba-fef0-4446-abbf-8ef0af96302b.mp4

## Test plan

- Enable CodeMirror file view, enable the new references panel.
- Open a file, hover over a symbol and click "find references"
- Click on a couple of entries in the reference panel. The preview appears, scrolled to the selected line.
  - Clicking on other entries in the same file doesn't give the impression that the preview reloads.

## App preview:

- [Web](https://sg-web-fkling-cm-blob-view-reference.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-gwwvodgwsp.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by umpox — COMMENTED** [review]
Comment super helpful, looks good but I noticed some off behaviour when I did a quick test:

RefPanel

Current ref panel supports the HoverOverlay _within_ the panel view too

**Comment by fkling** [comment]
@umpox Thanks for catching that, I didn't test that :-/

**Comment by fkling** [comment]
I disabled hovercards for the reference panel.

**Review by umpox — APPROVED** [review]
Thanks!

**Pull request merged**
