### PR TITLE
Frontend: allow requests from browser extension origins by default

### PR DESCRIPTION
**Pull request by chrismwendt**
Before this change, the frontend responded to the `OPTIONS` request of cross-origin (e.g. browser extension) requests with the `Access-Control-Allow-Origin` header set to the value of `corsOrigin` from site config. That behavior prevented the browser extension from communicating with the Sourcegraph instance in the situation where the browser extension did not have permission to the Sourcegraph URL for two reasons:

- The frontend did not special case the browser extension IDs, which meant that a site admin would need to enter the bundle ID into the `corsOrigin` in site config
- Chrome only allows one value in the `Access-Control-Allow-Origin` header, not a space-separated list

Neither of these problems would have been caught in the "Test plan" section of https://github.com/sourcegraph/sourcegraph/pull/2689 (which removed the browser extension bundle IDs) unless all sites were disabled (they probably weren't) because Chrome only makes a preflighted cross-origin request instead of a simple cross-origin request when the browser extension doesn't have permission on the remote origin. cc @sqs Does this make sense?

After this change, the frontend will respond to cross-origin requests by echoing the `Origin` request header in the `Access-Control-Allow-Origin` response header and always allow the browser extension bundle IDs as a special case.

@lguychard I'd like your review on this because this is relevant to https://github.com/sourcegraph/sourcegraph/issues/2799

Fixes https://github.com/sourcegraph/sourcegraph/issues/3056

### CODE REVIEW

**Comment by sqs** [comment]
Makes sense. But don’t rely on me here for anything. 

BTW does this work on Firefox? I know we ask for all sites on FF now but that will ideally change.

**Comment by chrismwendt** [comment]
It works on Firefox, but I didn't see any `OPTIONS` requests, so I'm guessing Firefox considers them all simple cross-origin requests and not preflighted cross-origin requests.

**Comment by sqs** [comment]
Does it work on FF because we ask for perms to all sites? Because that will change soon hopefully.

**Comment by chrismwendt** [comment]
> Does it work on FF because we ask for perms to all sites?

Yes. When I remove `<all_urls>`, FF preflights requests to any origin that isn't listed in the manifest permissions.

The `Origin: moz-extension://<some random UUID here>` header appears to be a random UUID, so there is no stable ID to hard-code in the frontend. 
https://stackoverflow.com/questions/47042507/can-a-firefox-addons-internal-uuid-value-be-made-stable

Perhaps we could whitelist `moz-extension://*`?

**Comment by felixfbecker** [comment]
> Whitelisting all moz-extension://* requests sounds very permissive though.

I don't see a reason why other extensions should not be allowed to use our API? Don't we want to enable full CORS?

**Comment by chrismwendt** [comment]
> I don't see a reason why other extensions should not be allowed to use our API? Don't we want to enable full CORS?

Not on private instances! Otherwise any malicious Firefox addon could read private code.

**Pull request merged**
