### PR TITLE
Streaming: better client-side errors

### PR DESCRIPTION
**Pull request by lguychard**
I noticed while working on https://github.com/sourcegraph/sourcegraph/pull/15522 that when the `error` event fired on the event source, we would error on the observer with the whole `Event` object as the error.

When trying to identify how to correctly map events to proper `Error` objects, I found out that:
- `EventSource` has a built-in `error` event, that fires when connecting to the source fails with `Event | ErrorEvent`
- We also emit `error` as a named event from the server, where `event.data` is a string containing the error message

TODO: actually test this.

### CODE REVIEW

**Comment by limitedmage** [comment]
Should we consider renaming our server side `error` event so that there are no name clashes?

**Review by rvantonder — APPROVED** [review]
Approving as "I trust you" and will leave the TODO testing for you to tackle in this PR or later, since streaming is feature flagged :-)

**Review by keegancsmith — APPROVED** [review]
LGTM. By the way the protocol is up for changing. Given we are using server side events, I think the better solution here is to change the event name from `error` to something else? I suggest `failed`? Error feels like the right word, so maybe we can call it `errors` and have a list of errors? `exception`?

**Comment by rvantonder** [comment]
Sorry @lguychard I'm force closing these, they are cluttering my app.graphite.dev review queue
Screen Shot 2021-11-16 at 3 31 37 PM

**Pull request closed without merging**
