### PR TITLE
fix: use of ioutil package

### PR DESCRIPTION
**Pull request by yagikota**
Fix usage of the deprecated ioutil package as described [here](https://golang.org/doc/go1.16#ioutil)

## Test plan
unit tests

### CODE REVIEW

**Comment by yagikota** [comment]
@philipp-spiess 

I am new to soucegraph and have just put up my first PR.
Then, I have a question about CI.
When will `buildkite/sourcegraph`  be executed? It has not been running for a long time.

**Comment by philipp-spiess** [comment]
@yagikota Yooo thank you so much for the contribution! I'll get this in front of our backend experts to review :) 

> When will buildkite/sourcegraph be executed? It has not been running for a long time.

We do not start CI runs for open-source contributions automatically. This is because they run in a trusted environment that has access to some CI related secrets so we need to vet the code before running it. Yours looks good to me though, so I'll start a run 💪

**Review by sashaostrikov — APPROVED** [review]
Nice!

**Comment by keegancsmith** [comment]
triggered a build

**Pull request merged**
