### PR TITLE
chore: Update go-mockgen

### PR DESCRIPTION
**Pull request by efritz**
Update go-mockgen to contain @keegancsmith 's update of x/tools.

## Test plan

Existing lints.

### CODE REVIEW

**Review by Strum355 — COMMENTED** [review]
Any reason not to go to 1.2.0? It ran fine on my machine

**Comment by efritz** [comment]
@Strum355 It requires go 1.18

**Review by Strum355 — APPROVED** [review]

**Comment by unknwon** [comment]
With this PR merged, does it mean I can upgrade my local Go version to 1.18?

**Comment by efritz** [comment]
I was running Go 1.18 locally before this was merged 🤷 .

**Pull request merged**
