### PR TITLE
Adds dynamic filter info to search tips page

### PR DESCRIPTION
**Pull request by donavonelli**

### CODE REVIEW

**Review by virginiaulrich — APPROVED** [review]
From my vantage appoint, approved! I think it's a nice idea to invite the team responsible for this part of the code to take a look, too. @abeatrix do you invite folks at random or do you use the team handle?

**Comment by abeatrix** [comment]
>  invite the team responsible for this part of the code to take a look

I agree! 

> do you invite folks at random or do you use the team handle? 

I usually use the team handle and/or also tag individuals that I have talked to from that team

**Review by rvantonder — APPROVED** [review]
Looks good. What's the context for this change (could we put it in the PR description?)

**Comment by virginiaulrich** [comment]
> Looks good. What's the context for this change (could we put it in the PR description?)

@donavonelli for this, you can share the Slack link from the thread with the customer :)

**Comment by donavonelli** [comment]
@rvantonder Context: https://sourcegraph.slack.com/archives/C01FG5LUWUU/p1627820133002000

**Pull request merged**
