### PR TITLE
codeintel: Remove ErrMalformedBundle

### PR DESCRIPTION
**Pull request by efritz**
Do not throw a 500 error from the bundle manager if there is a missing identifier or document in the database. This tends to block code intel from pages in which document references exist to documents that were not indexed (imports of json files, in one specific example).

### CODE REVIEW

**Comment by aidaeology** [comment]
Are we saying that missing identifiers/documents in database is an acceptable or valid result? (as in its not an issue but is one of the acceptable results we can expect). If it is an issue or an undesirable result but not a blocking one - then we should at least log it for future debugging, i.e. add in any !exists|!ok block: `log15.Warn("Malformed bundle: unknown %s %s", e.Name, e.)`

**Comment by efritz** [comment]
My original assumption was that it was invalid, but for at least documents _in some circumstances_ it seems like it can happen without being malformed.

I can add warnings just in case, and hope they're not very noisy for some codebases.

**Comment by aidaeology** [comment]
Is there anyway way in this context that we are able to tell the difference between an invalid (error) or valid (expected) missing documents?

**Comment by efritz** [comment]
No, the json document thing was news to me. And it's better not to completely fail on weird indexer output (especially if we want to encourage community-driven indexer development) if we can help it.

**Pull request merged**
