### PR TITLE
search: Remove repogroup from code and docs

### PR DESCRIPTION
**Pull request by fkling**
This commit removes references to the repogroup filter from code and docs.

## Test plan

Enter `repo` in search query input and observe that `repogroup` is not suggested.

## App preview:

- [Web](https://sg-web-fkling-hide-deprecated-filters.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-rhmesjavof.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by rvantonder — CHANGES_REQUESTED** [review]
looks like we published that this filter is removed in V3.34 so we can just remove it

https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md#removed-9

**Review by rvantonder — APPROVED** [review]
I will just approve to unblock but yeah just delete it :3

**Comment by fkling** [comment]
So if we get a query that contains `repogroup:` we just don't recognize it as a filter anymore?

**Comment by rvantonder** [comment]
> Query filter repogroup (deprecated in 3.33) is now removed. https://github.com/sourcegraph/sourcegraph/issues/24277

If we say it was removed it's removed 😄 It's removed in the backend (there's [a few old references](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:Go+repogroup) we should get rid of, but this filter is very much gone).

**Comment by fkling** [comment]
@rvantonder FYI I updated the PR to remove repogroup from code and the documentation

**Comment by rvantonder** [comment]
sweet! looks like the previous PR didn't wipe everything :-)

**Pull request merged**
