### PR TITLE
Interactive search: better styling 

### PR DESCRIPTION
**Pull request by attfarhan**
- Reduce the height of filter inputs using Bootstrap's `form-control-sm`, thereby reduce the padding in the selected filters row
- Use circle icons for negation, so the minus sign doesn't look like its always applied

image

Context: https://sourcegraph.slack.com/archives/CMT39K56Z/p1579189378074900?thread_ts=1579101752.056000&cid=CMT39K56Z

### CODE REVIEW

**Comment by eseliger** [comment]
what I recently saw, and looks like it's still in the screenshot, there is a slight border radius between the checkmark and the input, isn't it? 🤔

**Comment by christinaforney** [comment]
I love the resizing and padding improvement!

There is a very slight bit of extra padding below the filter buttons that comes from the entire header area:
image
image

From other issue: Can we add a bit of padding between the filter name and colon and the input field? The active state glow bleeds over the top of the colon:
image

As for the negation symbol, this is an improvement but still doesn't feel quite right. I wonder if using a changing icon and swapping to a + circle when it is inclusive and - when it is exclusive could be more effective? The question I still have is if that will be a clear signal that it is something that can be toggled. It also is a departure from our current on/off toggle states that we use for case and regexp, but I think it's more important to be clear in this case. What are your thoughts on this idea? We could also try with the previous symbol and just use a + and - without the circle too. I'm not sure what will feel the most natural.

**Comment by attfarhan** [comment]
@christinaforney I think using + and - icons seems best for now: 

image

**Comment by attfarhan** [comment]
Merging this to get into 3.12. This change is purely cosmetic.

**Pull request merged**
