### PR TITLE
dev: Update comby version.

### PR DESCRIPTION
**Pull request by varungandhi-src**
1.7.0 is the latest release (Jun 07 2021).
It includes a bunch of fixes not present in 0.18.1 (Aug 24 2020).

## Test plan

Covered by existing tests.

### CODE REVIEW

**Review by rvantonder — CHANGES_REQUESTED** [review]
Unfortunately I'm 99% sure this will break things :sad-cowboy:. Because of Sourcegraph limitations, we do some shenanigans with emitting multiline matches (we split them on newlines) so that they can conform to our result type. Some of the comby output was changed around JSON encoding of newlines and `\r\n`. We/I need to make the corresponding changes in Sourcegraph and then test first to make sure it works. If you run `backend-integration/vg/update-comby` it will probably break on the integration tests. If it doesn't break there, it still doesn't mean we're OK: you will probably get janky line highlighting even though tests don't reveal it.

In general we also want to update the released version along with dev updates like this renovate PR: https://github.com/sourcegraph/sourcegraph/pull/13938.

**Comment by rvantonder** [comment]
Feel free to abandon, I'm not suggesting to invest effort in all that. If there's a particular fix you want in the upstream code I'm happy to bump urgency/priority for this.

**Comment by varungandhi-src** [comment]
Nope, there isn't a specific fix I needed. I just noticed a big difference between the version I had installed locally and the one I saw in this script, so I figured I might as well "fix" it.

**Comment by rvantonder** [comment]
> I just noticed a big difference between the version I had installed locally

Gotcha. Unfortunately it's possible you'll see those bad/broken highlighting artifacts I talked about locally :( I'll try jump into this when I have some free cycles 🙏

**Pull request closed without merging**
