### PR TITLE
db: add expired_at and last_valid_at columns to user_external_accounts table

### PR DESCRIPTION
**Pull request by unknwon**
Adds two columns to the `user_external_accounts` table:

- `expired_at` indicates when the token stored in the `auth_data` has been detected expired.
- `last_valid_at` indicates when was the last successfully used, later will be used for `workerutil` package (@ryanslade could you confirm the `workerutil` package requires naming convetions of the column or it is OK to customize the column name for workers to pick up?).

This two columns are not yet used but will be when addressing both https://github.com/sourcegraph/sourcegraph/issues/14899 and https://github.com/sourcegraph/sourcegraph/issues/15176.

### CODE REVIEW

**Comment by tsenart** [comment]
What's the expected write rate to the `last_valid_at` column (i.e. how often is it updated)?

**Comment by unknwon** [comment]
> What's the expected write rate to the `last_valid_at` column (i.e. how often is it updated)?

@tsenart: Every sync of user permissions (currently would be 10 writes per minute) and listing repos of a user-added external service (@ryanslade: how many sync workers would we have for external services per minute?).

**Comment by tsenart** [comment]
OK, sounds like it's not super high frequency, which should be fine.

**Comment by ryanslade** [comment]
Currently we run up to 3 syncers concurrently. They run whenever the `next_sync_at` column on `external_services` is in the past so it depends on how often they change. We back off when we sync and there were no changes and our minimum sleep time for each external service is two minutes.

So I guess worst case would be that we sync once every two minutes for each external service but in reality it'll be a lot lower than that.

**Review by ryanslade — APPROVED** [review]

**Pull request merged**
