### PR TITLE
db: delete external services upon user deletion

### PR DESCRIPTION
**Pull request by unknwon**
Soft deletes rows from `external_services` table with matching `namespace_user_id` when a user is soft deleted.

Cascading deletion is already in place with foreign key constraint.

Part of #12699

### CODE REVIEW

**Comment by tsenart** [comment]
I think using triggers for this sort of things tends to be more robust. Any reason to do this in application code?

**Comment by unknwon** [comment]
> I think using triggers for this sort of things tends to be more robust. Any reason to do this in application code?

@tsenart: Good idea, do we have examples to do cascading soft-delete using triggers?

**Comment by tsenart** [comment]
We used to do something similar in campaigns: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/migrations/1528395650_squashed_migrations.up.sql?subtree=true#L283

**Comment by tsenart** [comment]
And https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/migrations/1528395650_squashed_migrations.up.sql?subtree=true#L1445:16

**Comment by asdine** [comment]
@unknwon There is one example here as well, you just need to change the table names I think:

https://github.com/sourcegraph/sourcegraph/pull/12789/files#diff-75755e9470427fed1ec94c8a3121efa5R41-R74

**Pull request merged**
