### PR TITLE
Fix CSS injection of Phabricator native extension

### LINKED ISSUE #42555: Sourcegraph phabricartor extension blocked by CORS policy
- **Sourcegraph version:** 4.0.0 (enterprise)
- **Platform information:** kubernetes deployment, Chrome Version 105.0.5195.125

#### Steps to reproduce:

1. Install phabricator sourcegraph extension within phorge instance as per https://github.com/sourcegraph/phabricator-extension
2. set corsOrigin correctly on sourcegraph instance
3. set sourcegraph.enabled to true on phorge
4. set sourcegraph url to self hosted sourcegraph instance

#### Expected behavior:
extensions shows data from sourcegraph

#### Actual behavior:
extension cant conntect to sourcegraph as it is blocked by CORS policy
```
[phorge-url]/:1 Access to fetch at 'https://[sourcegraph-url]/.assets/extension/css/style.bundle.css?v=0.0.0' from origin 'https://[phorge-url]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM376:1          GET https://[sourcegraph-url]/.assets/extension/css/style.bundle.css?v=0.0.0 net::ERR_FAILED 200
(anonymous) @ VM376:1
(anonymous) @ codeHost.tsx:720
DT @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
codeHost.tsx:720 Error initializing Phabricator integration TypeError: Failed to fetch
    at <anonymous>:1:876
    at codeHost.tsx:720:1
    at DT (codeHost.tsx:720:1)
    at Array.map (<anonymous>)
    at codeHost.tsx:720:1
    at codeHost.tsx:720:1
    at codeHost.tsx:720:1
    at codeHost.tsx:720:1
(anonymous) @ codeHost.tsx:720
Promise.catch (async)
(anonymous) @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
[phorge-url]/:1 Access to fetch at 'https://[sourcegraph-url]/.assets/extension/css/style.bundle.css?v=0.0.0' from origin 'https://[phorge-url] has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM376:1          GET https://[sorucegraph-url]/.assets/extension/css/style.bundle.css?v=0.0.0 net::ERR_FAILED 200
(anonymous) @ VM376:1
(anonymous) @ codeHost.tsx:720
DT @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
(anonymous) @ codeHost.tsx:720
```

This used to happen on the chrome browser extension too so suspect the latest version of the extension hasn't been bundled with sourcegraph.

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes #42555

The Phabricator native extension injected the same CSS file twice instead of injecting both `style.bundle.css` and `inject.bundle.css` 😐. 

Once the PR is merged, this will require waiting for a new Sourcegraph release.

## Other issues

The hover menu looks a bit gross, I'll verify how it is supposed to look in our browser extension before merging this PR.

## Test plan

Screenshot 2022-11-03 at 15 05 28

## App preview:

- [Web](https://sg-web-ps-fix-phabricator-native.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by valerybugakov — APPROVED** [review]
Good catch!🔥

**Comment by philipp-spiess** [comment]
Added some docs as well to the browser extensions README so that we have an easier time reproducing this the next time :slightly_smiling_face:

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/fix-phabricator-native-extension/compare-report.html;tab=live_object) for a full comparison between the commits 55e6581 and c8ca297 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by vdavid — APPROVED** [review]
Wow, great docs!

**Comment by philipp-spiess** [comment]
Apparently this is the expected styling, this is from the browser extension: 

Screenshot 2022-11-03 at 15 34 02

**Pull request merged**
