### PR TITLE
search: Distinguish file content matches from path matches in the UI when `select:file` is present

### PR DESCRIPTION
**Pull request by tbliu98**
Stacked on #41296

`select:file` restricts result rendering to only show file paths. These results can be either:
1) A match on the literal file path string, or 
2) A file containing a content match, but not necessarily a match on the file path 

Regardless, `select:file` will cause all results to be converted to path matches.

Currently, we always label a result with "Path match" when it is rendered as a path match. This is confusing when a result is a content match that has been converted to a path match, because the label "Path match" implies that the file path itself contains a match, when this is not always the case. 

Now that path match ranges are available in the client, we can make the distinction between a "natural" path match and a "converted" path match in the UI in a way that's informative to users. 

Before:
Screen Shot 2022-09-04 at 6 20 55 PM

After:
Screen Shot 2022-09-06 at 11 43 08 AM

## Test plan
Visually confirm the change in the UI

### CODE REVIEW

**Review by camdencheek — COMMENTED** [review]
I agree that it's confusing that we call the results of `select:file` a "path match", but this change doesn't quite fit my mental model of what's happening here. 

A couple of statements:
1) `type:file abc` will return both _content matches_ and _path matches_
2) `type:file abc select:file` will convert any _content matches_ into _path matches_, and pass through any _path matches_ unmodified
3)  _Path matches_, _content matches_, and _symbol matches_ are all represented by the `FileMatch` backend type, with `len(fm.ChunkMatches) == 0 && len(fm.Symbols)` indicating it's a _path match_.

(1) is confusing because `type:file` will return two different result types
(2) is confusing because, even though we use `type:file` to mean "path matches and content matches", `select:file` means "select the path from any type of file match"
(3) is confusing because we don't have a dedicated type for path matches, which means we have no way distinguish between path matches and content matches with zero matched ranges. I [tried to fix this](https://github.com/sourcegraph/sourcegraph/pull/29948) at one point, but there were many edge cases that I didn't have time to track down. [Some more history](https://github.com/sourcegraph/sourcegraph/pull/22996)

So...why does this change feel wrong? Because `access_token select:file` _does_ actually return a "path match" by this definition. It _converts_ content matches into path matches -- those content matches are _no longer content matches_. Similarly, if you did `select:repo`, even if we started with content matches, they become repo matches via selection. All that to say, I think it's inaccurate to say that `access_token select:file` returns content matches.

**Comment by tbliu98** [comment]
@camdencheek  So, it wasn't my intent to label these matches as being content matches, because what we're presenting is a path match. That hasn't changed. My intent was to indicate more specifically to the user _why_ certain results are included when `select:file` is used. I realize now I used "path match" and "content match" incorrectly in my PR description, so I'll update that to be more specific 😅

I think that adding path match highlighting is going to affect how users interpret the label "Path match." If I'm a user, and I see a path match result, I see that 1) the matching part of the file path is highlighted, and 2) it's labeled as a "Path match." So I think, "A path match is where the file path itself matches my query and the matching part will be highlighted." I think the label "Path match" implies that the file path itself contains a match on the query, but this is not always true. (I actually have always felt this way, way before working on the highlighting.)

Now if I see a result like `CHANGELOG.md` in the results when my query was `access_token select:file` -- clearly `CHANGELOG.md` doesn't match any part of my query, yet it's still present as a result and labeled as a "Path match." Now this conflicts with my notion of what a path match is. So I want to make it clear to the user why the file path `CHANGELOG.md` is showing up for the query `access_token select:file`. 

Would it be better to phrase it as something like "File contains matching content"? Instead of "File content match," which implies that the match itself is a content match.

**Comment by tbliu98** [comment]
Updated the displayed message to be more specific

**Review by limitedmage — APPROVED** [review]

**Comment by limitedmage** [comment]
Updated wording seems clear to me and I think would make using `select` a lot less confusing. Really like this!

**Pull request merged**
