### PR TITLE
remove search scope pages (/search/scope/:id)

### PR DESCRIPTION
**Pull request by sqs**
The search scope page was a page at `/search/scope/:id` (where `:id` is the ID of a search scope in settings) that displayed the name and description of the scope, plus a search bar that searched within the scope.

It was never documented (other than in the settings JSON Schema), usage was very low on Sourcegraph.com (not surprisingly, because it was disabled in 2018), and we only used it at in-person conference booths more than a year ago. We don't have any data on whether customers use this feature, but given these factors, we can assume that they do not (and if we find out otherwise before the release, we can plan accordingly).

### CODE REVIEW

**Review by limitedmage — APPROVED** [review]
There are no plans to remove the search scope feature altogether, just the dedicated page, correct? 

We should in the near future re-evaluate the value of keeping search scopes in light of upcoming work such as the separation of saved searches from alerts and the addition of saved searches in the homepage. These seems to be a lot of feature overlap there.

**Comment by sqs** [comment]
@limitedmage:

> There are no plans to remove the search scope feature altogether, just the dedicated page, correct?
>
> We should in the near future re-evaluate the value of keeping search scopes in light of upcoming work such as the separation of saved searches from alerts and the addition of saved searches in the homepage. These seems to be a lot of feature overlap there.

In https://github.com/sourcegraph/sourcegraph/pull/14128 I propose not showing search scopes on the homepage anymore.

If that PR is also merged, then search scopes are just a way to show user-defined suggested search filters on the search results page. That has some value and there is no alternative way to achieve that yet, so I think that will remain (until we find a better alternative, or measure and see that usage is low enough to remove that too).

But the homepage will not suffer from the feature overlap confusion anymore.

**Comment by rrhyne** [comment]
Should we 301 redirect to the homepage?

**Comment by sqs** [comment]
@rrhyne i don’t think so. The 404 is correct and it is easy for people to navigate to our homepage.

**Review by attfarhan — APPROVED** [review]

**Pull request merged**
