### PR TITLE
Insights/revert compute changes

### PR DESCRIPTION
**Pull request by coury-clark**
Reverts https://github.com/sourcegraph/sourcegraph/pull/37952 and https://github.com/sourcegraph/sourcegraph/pull/37974

See discussion https://github.com/sourcegraph/sourcegraph/pull/37952 and https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1656577955764189

## Test plan

coming as soon as I can start my local

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
Approving only the revert for https://github.com/sourcegraph/sourcegraph/pull/37952 / 4f862631ea0a554dfc386df5944968b66236a34d

**Comment by coury-clark** [comment]
@rvantonder I agree, we will most likely keep some of this code. It's just cleaner / easier to revert both and reestablish this on a new branch once we have something else in place, rather than do a partial revert.

**Comment by rvantonder** [comment]
OK, sounds good, your call on that ofc.

**Review by CristinaBirkel — APPROVED** [review]
I read over the thread; this makes sense. 👍

**Pull request merged**
