### PR TITLE
core workflow: First pass on inlining symbols in the file tree

### PR DESCRIPTION
**Pull request by fkling**
Addresses #38662

This builds on top of Rok's symbol tag work.

It's a very rudimentary first pass to inline symbols. I basically
duplicated the logic for the symbols sidebar with some changes:

- No pagination, I'm requesting a high number of symbols from the server
  and hope that this will suffice to load all symbols.
- Only show top level symbols. I don't know how reliable the
  `containerName` data is but if its set I assume it's not a top level
  symbol.

I had to thread some additional values through to the File component to
be able to fetch symbols (I guess another alternative would be to also
ask for symbol information when we fetch the file information in the
first place, but that feels very wasteful).

It takes a moment to load the data, but I found it too distracting to
immediately show a loading indicator. I added some logic to only show it
after 800ms. If there are no symbols or there is an error a
corresponding message will be shown.

A big drawback of this first solution is that it will show "No symbols
found." for files that _cannot_ have symbol information, such as
Markdown files. This feels weird, but I don't know of a good way to
handle that.

Lastly I'm currently keep using the Tab component because that allows me
to keep using the "sidebar collapse" button without additional changes.

https://user-images.githubusercontent.com/179026/180432432-cad4fee9-0ad3-409f-b340-f70715c70a82.mp4

**CAVEAT:** Our symbol data is very low quality for some files, and 
using single character labels doesn't improve that either in this case
(additional [Slack](https://sourcegraph.slack.com/archives/C07KZF47K/p1658487725681349) thread).

## Test plan

Open file, enable core workflow simple UI. See inline symbols.

## App preview:

- [Web](https://sg-web-fkling-38662-symbol-treeview.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-avmowzbsuc.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by benvenker — COMMENTED** [review]
@fkling nice! Quick question just because I don't think you actually clicked on a symbol in the video: does clicking a symbol still take you to that symbol in the file view?

**Comment by fkling** [comment]
@benvenker Yep! Sorry, forgot to show that in the demo.

**Review by benvenker — APPROVED** [review]

**Comment by benvenker** [comment]
@fkling are you good to merge this or did you still want more feedback?

**Comment by fkling** [comment]
@benvenker If you don't have any additional feedback I'll merge it tomorrow.

**Comment by benvenker** [comment]
OK, sounds good!

**Pull request merged**
