### PR TITLE
source: fix username input validation

### LINKED ISSUE #54702: password input validation: console shows error related to regex
On a fresh Sourcegraph instance I setup a new user and get these errors in the console:

screenshot_2023-07-07_08 20 36@2x

Seems like it's coming from here: https://github.com/sourcegraph/sourcegraph/blob/c836d6a333e62f5c0e86a89dc585e4708353021b/client/web/src/user/index.ts#L4

Note: I could create the user

/cc @sourcegraph/source/iam

### PR DESCRIPTION
**Pull request by BolajiOlajide**
Closes #54702

I'm still trying to figure out when this started happening or why it started happening. However, according to the error message it looks like there's an invalid character within the character class (usually denoted by the [] brackets)

image

In the given regular expression `/^\w(?:\w|[.-](?=\w))*-?$/`, the invalid character class is [.-]. Escaping the hyphen character within the character class `[.\-]` fixes the error.

## Test plan

Spin up a fresh instance of Sourcegraph, entering the username and password shouldn't trigger the error in the console anymore.

CleanShot 2023-07-07 at 12 16 25@2x

### CODE REVIEW

**Comment by mrnugget** [comment]
Do the errors still pass in `client/web/src/user/index.test.ts`? It's really weird that this started to show up...

**Review by sashaostrikov — APPROVED** [review]
LGTM! Did you check that this regex works as expected in other places it is used (if any)?

**Comment by BolajiOlajide** [comment]
> Do the errors still pass in `client/web/src/user/index.test.ts`? It's really weird that this started to show up...

Yes, the tests are passing in there. It has to do with how HTML processes the regex passed to it. 
I initially tried wrapping the regex in a `new RegExp` call to see if that would change anything

```ts
export const VALID_USERNAME_REGEXP = new RegExp(/^\w(?:\w|[.-](?=\w))*-?$/).source
```

However, upon reading more about it, it seems HTML doesn't takes the value of `-` literally, so escaping it helps HTML understand it.

CleanShot 2023-07-07 at 12 23 24@2x

**Comment by mrnugget** [comment]
Before we merge, I'd really love to know why it breaks now

**Comment by BolajiOlajide** [comment]
> LGTM! Did you check that this regex works as expected in other places it is used (if any)?

Yes, I tested in a couple of places where that Regex is being used like [create a new org page](https://sourcegraph.test:3443/organizations/new).

**Comment by BolajiOlajide** [comment]
> Before we merge, I'd really love to know why it breaks now

I'll do a `git bisect` but so far I think the error might have always been in the console and we probably didn't notice. I'll do a bisect to confirm.

**Comment by pjlast** [comment]
@mrnugget I checked on 5.0.0 and the error was present there as well, so I think @BolajiOlajide is correct in that the error has been there for a long time

**Comment by mrnugget** [comment]
Okay, I just ran `4.1.0` for fun (`docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:4.1.0`) and yes, error is also in that. Let's get it in then (if the tests pass and if we don't need another test to make sure it works)

**Comment by mrnugget** [comment]
@BolajiOlajide can we get this in?

**Comment by BolajiOlajide** [comment]
> @BolajiOlajide can we get this in?

Yes, we can.

**Pull request merged**
