### PR TITLE
[src-expose] Add flag for not recursively serving repos

### PR DESCRIPTION
**Pull request by dadlerj**
Requested by https://app.hubspot.com/contacts/2762526/company/768958891

See discussion starting at https://sourcegraph.slack.com/archives/CTJCMDCCS/p1593043754316900?thread_ts=1593010018.312200&cid=CTJCMDCCS for context

Short story: they have a lot of large monorepos, which are causing [our dockerized src-expose](https://hub.docker.com/r/sourcegraph/src-expose/tags?page=1) to fail K8s health checks in their deployment.

As far as I can tell this fix doesn't actually work 🤦  but I've never built Go CLIs before... I just get the error:

```
flag provided but not defined: -recurse
```

Can either of you help take this on? Or let me know if you believe something else is the issue here.

### CODE REVIEW

**Comment by keegancsmith** [comment]
Alternatively they could use bare git repos. We don't need a checkout. I'll finish up this PR now incase it helps.

**Comment by keegancsmith** [comment]
@dadlerj I'm confused now :) We don't do recursing into a git repo, I think this may be the customer I did a special build for? So if you just use normal src-expose we don't recurse into a git repo.

To make it clearer. If your filetree is
```
foo
foo/subfoo
bar
bar/.git
bar/subgit
```

we will visit `foo`, `foo/subfoo` and `bar`. We don't recurse further into `bar` due to it being a repo (the `.git`). However, we fully recurse foo since in the above example it has no repos.

There are some assumptions in src-expose that the tree won't require much recursing to find everything, so it doesn't do any caching of walking the tree etc. This assumption could be revisited, but I'd like to understand more about the customer and what _exactly_ the tree looks like (maybe there are some other file/dirs?) and version they are using.

**Comment by dadlerj** [comment]
Interesting! I assumed this was the default behavior now from reading the code. They have a disk with a series of repos in a parent dir, so:

```
dir
dir/repo1
dir/repo1/.git
dir/repo1/README.md
dir/repo1/cmd
dir/repo1/pkg
...
dir/repo2
dir/repo2/.git
...
```

etc. You're saying that we would start in dir, drop into each of the repos, find a .git directory, and then stop descending? If that's the case, then the 2 minute timeout on a /list-repos API call (see the slack thread with them above for logs) could be due to something else. This was just my initial hunch!

That said, I agree that we did build a custom version at one point that did this, and I'm wondering if it's possible that Ryan used THAT binary when building our `sourcegraph/src-expose` Docker image :/. I have no way to check this, unfortunately (let me know if you do).

I'll tag you into the thread so you can help ask questions. At this point, though, building a new Docker image with the latest src-expose might be the next thing to try. Do you have any recollection of how/when Ryan built it (for the purpose of https://github.com/sourcegraph/src-expose-demo)?

**Comment by keegancsmith** [comment]
> You're saying that we would start in dir, drop into each of the repos, find a .git directory, and then stop descending?

Yup.

> If that's the case, then the 2 minute timeout on a /list-repos API call (see the slack thread with them above for logs) could be due to something else. This was just my initial hunch!

`/list-repos` should mainly just be recursing, I don't expect anything else to take time. So your hunch is likely correct. One has to assume it is the special version in the docker image?

> That said, I agree that we did build a custom version at one point that did this, and I'm wondering if it's possible that Ryan used THAT binary when building our `sourcegraph/src-expose` Docker image :/. I have no way to check this, unfortunately (let me know if you do).

This would be quite a bit of work, but possible (if the binary in the docker image itself wasn't built by hand). Maybe we can add some extra debug logging to help debug this? If that sounds good ping me and I'll ship a tiny PR tomorrow morning :)

> At this point, though, building a new Docker image with the latest src-expose might be the next thing to try. Do you have any recollection of how/when Ryan built it (for the purpose of [sourcegraph/src-expose-demo](https://github.com/sourcegraph/src-expose-demo))?

I assume it was for the demo repo originally. I can build it again.

**Comment by keegancsmith** [comment]
@dadlerj I pushed a new version of the docker image and the binaries:

- `sourcegraph/src-expose:latest@sha256:e9d4adabd2f0fb22b84a2e5e1b3e6fcb0031394741bd6d5c57420b85ea2c5b84`
- `file://src-expose/99b661b5b7b00b77149b938fe675ddb00777e7cf/darwin-amd64/src-expose`
- `file://src-expose/99b661b5b7b00b77149b938fe675ddb00777e7cf/linux-amd64/src-expose`

Now if you pass `-verbose` as a global flag it will log every directory it considers. eg `src-expose -verbose serve foo/bar`

**Comment by dadlerj** [comment]
Thank you! 🎉

**Pull request closed without merging**
