### PR TITLE
Add usage metrics and RED client

### PR DESCRIPTION
**Pull request by notjrbauer**
Took a stab and wrapped each dependency call in its own function in order to pump out some metrics. I opt'd out of using `RequestMeter` because some service dependencies rely on different transports. As a result, I tried writing a RED client for these lower service-level calls to use, while taking care of durations, req counts, and error counts automatically.

Ref #9867

### CODE REVIEW

**Comment by slimsag** [comment]
Whoa nice, thanks for the contribution! I'll review this soon (likely early next week).

Just curious what made you interested in taking a stab at this?

**Comment by tsenart** [comment]
Ping @slimsag.

**Comment by slimsag** [comment]
Super sorry for reviewing this so late.. Actually most of the comments I was going to make would've brought this in the direction of this: https://github.com/sourcegraph/sourcegraph/pull/10297

Would you be willing to update this PR to use the `metrics.OperationMetrics` type added in #10297 ? I think that would be most ideal

**Comment by notjrbauer** [comment]
Sure I can reopen this once I use `metrics.OperationMetrics`

**Pull request closed without merging**
