### PR TITLE
Revert switch to redigo.

### PR DESCRIPTION
**Pull request by keegancsmith**
This is currently causing issues in production. Will need to investigate
further. For now just revert.

Revert "rcache: Remove helper cmd"

This reverts commit fa71fba909cadaf15da28b8c07fd7255c31670a4.

Revert "rcache: Remove redisPool helper"

This reverts commit c0008742fdfbe3d21987e1f8bfb1094531244b2f.

Revert "rcache: Remove unused error return for redisPool"

This reverts commit 5af4557fec97af1b4ee25deba90ed31c7a0cf6f9.

Revert "rcache: Switch to redigo library"

This reverts commit 943842d31c0b96379dfe9cc22e3e7f35380be18d.

Revert "vendor: Replace radix with redigo"

This reverts commit 97b1ac6b950ad2f237d7f7ce7ad284f7b90ce896.

### CODE REVIEW

**Comment by beyang** [comment]
LGTM

**Comment by samlavery** [comment]
LGTM, fwiw both clients have the coveted smiley face **and** gold star according to [redis](http://redis.io/clients) 😄.

**Comment by keegancsmith** [comment]
Given no one has tried to roll out a new feature to production, I'll hold of landing this unless someone needs to ship something. That way it will be much easier for me to investigate on Monday morning.

**Comment by keegancsmith** [comment]
abandon ship

**Pull request closed without merging**
