### PR TITLE
Clarify mount maturity and point to issue

### PR DESCRIPTION
**Pull request by malomarrec**
Also, any reason for this to be experimental?
Experimental features need to be feature flagged off by default, which doesn't make sense for this.
How about we make it GA, but add a note that we're iterating on this and feedback is very welcome? @Piszmog 

## Test plan

Just a docs change.

### CODE REVIEW

**Comment by eseliger** [comment]
sounds good to me

**Comment by Piszmog** [comment]
Do we want to update the/remove the experimental tag in this PR?

**Comment by malomarrec** [comment]
@Piszmog I'll do it right now

**Comment by malomarrec** [comment]
Done

**Comment by Piszmog** [comment]
@malomarrec I just remembered we have the experimental tag on the [YAML reference](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/batch_changes/references/batch_spec_yaml_reference.md?L423-425) as well

**Review by Piszmog — APPROVED** [review]

**Review by adeola-ak — APPROVED** [review]

**Comment by courier-new** [comment]
We also had the badge on the links from our index pages -- I've removed them there as well.

**Pull request merged**
