### PR TITLE
migrator: Do not require explicit transactions in migration definitions

### PR DESCRIPTION
**Pull request by efritz**
The explicit `BEGIN` and `COMMIT` wrapper around migration definitions were an artifact of golang-migrate. We can now make the transaction implicit **only when performing migrations with no concurrent index creation**. Now that we can discern the two cases, we can wrap only the one that can handle it.

## Test plan

Unit tests and QA tests should give good confidence.

### CODE REVIEW

**Review by unknwon — APPROVED** [review]

**Comment by slimsag** [comment]
Just thinking: what about ‘CREATE extension’?--
Follow me on twitter @slimsag <https://twitter.com/slimsag>.

**Review by eseliger — APPROVED** [review]
Did you check in our existing migrations if there were only concurrent indexes that require this special handling?

**Comment by efritz** [comment]
@slimsag `CREATE EXTENSION` is valid within a transaction (we currently wrap them today explicitly).

Also, Follow me on twitter @ericfritz <https://twitter.com/ericfritz>.

**Comment by efritz** [comment]
@eseliger Each concurrent migration creation is explicitly tagged and handled specially.

**Pull request merged**
