### PR TITLE
Remove migration that always produces deadlock

### PR DESCRIPTION
**Pull request by mrnugget**
Apparently we can't drop a trigger on `repo` without causing a deadlock.

So this removes the migration introduced in #40899.

## Test plan

- Ran into production deadlocks, removing this migration.

### CODE REVIEW

**Comment by mrnugget** [comment]
Turned it into a noop migration instead of removing the files, after @efritz suggested that.

**Review by eseliger — COMMENTED** [review]
LGTM but will approve tomorrow so we don't auto-merge this overnight when we both cannot look into problems, if any arise.

**Comment by mrnugget** [comment]
Pretty sure this is now replaced by https://github.com/sourcegraph/sourcegraph/pull/41038

**Comment by mrnugget** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/pull/41038

**Pull request closed without merging**
