### PR TITLE
web: debug RR6 migration issue

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context

I discovered two issues with the `CompatRoute`:
1. `path="*"` doesn't work correctly because of https://github.com/remix-run/react-router/blame/4d915e3305df5b01f51abdeb1c01bf442453522e/packages/react-router-dom-v5-compat/lib/components.tsx#L18
2. Nested routes in Switch don't work properly because RR6 and RR5 paths
should be different before migration. It seems that the CompatRoute
still renders the element if the RR5 path is not specified. See implementation here:
https://github.com/remix-run/react-router/blob/4d915e3305df5b01f51abdeb1c01bf442453522e/packages/react-router-dom-v5-compat/lib/components.tsx#L21

More context:
1. https://github.com/remix-run/react-router/issues/9558#issuecomment-1315168000
2. https://github.com/remix-run/react-router/discussions/9509

We can implement an ugly migration keeping both RR5 and RR6 path props. On migration completion, we can remove `path` and rename `pathV6` or whatever seems the best combination.

## Test plan

`sg start web-standalone`

## App preview:

- [Web](https://sg-web-vb-debug-switch-compat-route.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -13.13% (-368.25 kb) 🔽 | 0.65% (+93.65 kb) 🔺 | 4.01% (+461.90 kb) 🔺 | 12.17% (+87) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vb/debug-switch-compat-route/compare-report.html;tab=live_object) for a full comparison between the commits 91db538 and 7027cb6 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by philipp-spiess** [comment]
> path="*" doesn't work correctly because of https://github.com/remix-run/react-router/blame/4d915e3305df5b01f51abdeb1c01bf442453522e/packages/react-router-dom-v5-compat/lib/components.tsx#L18

Yeah I noticed this but I don't think this is the primary cause of my issues since I also changed the routes to be marked as `exact`.

> Nested routes in Switch don't work properly because RR6 and RR5 paths
should be different before migration. It seems that the CompatRoute
still renders the element if the RR5 path is not specified. See implementation here:
https://github.com/remix-run/react-router/blob/4d915e3305df5b01f51abdeb1c01bf442453522e/packages/react-router-dom-v5-compat/lib/components.tsx#L21

I’m not sure yet how your example fixes this. It seems like they do something very similar to what <CompatRoute> does in the case `exact` is set to a non-truthy value. 

Or is the difference that V6 paths _need_ to be relative and our V5 paths are not? https://github.com/sourcegraph/sourcegraph/pull/46909/files#diff-d096551e879ace6f185938ab39d6a8d01007695e1e23c70b5d450a3fb0b24133R72

**Comment by valerybugakov** [comment]
> Or is the difference that V6 paths need to be relative and our V5 paths are not?

@philipp-spiess, we need to specify both paths (v5 and v6) because the `CompatRoute` render two routes internally, and as you mentioned, paths should be different (absolute and relative). It fixes the issue for Routes nested inside the `Switch` component.

**Comment by philipp-spiess** [comment]
Yeah I see. This is going to be a pretty nasty migration than, we'll have to manually fix all of the nested routes (and there are a lot) and test them properly, only to finish the first step (to render the compat route).

**Pull request closed without merging**
