### PR TITLE
bext: make 'Configure on Sourcegraph' button navigate to manage repositories page when on default Sourcegraph URL

### PR DESCRIPTION
**Pull request by taras-yemets**
Closes [#3066](https://github.com/sourcegraph/sourcegraph/issues/3066)

https://user-images.githubusercontent.com/25318659/155352705-537b6d6b-5394-4af8-ab1d-f7c041882d3d.mp4

| Before | After |
| ---------- | ------ |
| browser - Options - OptionsPage - All Options Pages ⋅ Storybook 2022-02-23 17-40-07 | browser - Options - OptionsPage - All Options Pages ⋅ Storybook 2022-02-23 17-41-53 |

## Test plan

- `sg run bext`
- `SOURCEGRAPH_API_URL=https://sourcegraph.com sg start web-standalone`
- replace `sourcegraphURL` with your local development server URL (_https://sourcegraph.test:3443_ on my machine) [here](https://github.com/sourcegraph/sourcegraph/blob/070afb3a785d3e152db6f68badf7184fd2383a27/client/browser/src/browser-extension/scripts/optionsPage.main.tsx#L162) and [here](https://github.com/sourcegraph/sourcegraph/blob/683a207c174c676aaaf5e09e8d19c10e26692440/client/browser/src/shared/code-hosts/shared/codeHost.tsx#L818)
- make sure you're logged in to Sourcegraph in browser extension and local development server instance
- open private repository which is not synchronized with your Sourcegraph account and:
  - click 'Configure on Sourcegraph' button and check if you were redirected to Sourcegraph manage repositories page _with repository name entered as a filter query_
  - open browser extension popup and check if private repository message is there with a link to manage repositories page _without any filter queries_

### CODE REVIEW

**Comment by taras-yemets** [comment]
The previous private repository note (with ordered list) was shown in case if:
- private repo is not synced with Sourcegraph
- Sourcegraph instance is _https://sourcegraph.com_

These instructions seem out of date at the moment. To sync repositories with _https://sourcegraph.com_ the user only needs to select such repositories for syncing on the manage repositories settings page.

We've updated this note to reflect the current process (see screenshots in the description), but I'm not sure if it fits well. What do you think?

cc: @jjinnii @rrhyne @ryankscott

**Comment by jjinnii** [comment]
@taras-yemets Thanks Taras! For clarification, the private repository note that you have in "before" are instructions to set up a private _sourcegraph instance_ for bext, not how to set up private repositories on a Cloud account.

That being said, now that I'm seeing the conditions (private repo is not synced with Sourcegraph, and 
Sourcegraph instance is https://sourcegraph.com/)  laid out, I see how we could provide _either_ instructions to set up a private sourcegraph instance _or_ instructions to sync private repos to Cloud.

For historical context @ryankscott, the original instructions for setting up a private sourcegraph instance were created when Cloud had not yet launched. 

We do have instructions under the input field for private instance users saying "Enther the URL of your sourcegraph instance to use the extension on private code", so I think updating the banner instructions to be for Cloud makes sense to me, but @ryankscott  would love your thoughts here.

**Comment by erzhtor** [comment]
@jjinnii To add, there are outdated instructions on other places as well (after install page, docs), so we probably need to tackle them as well, but we are not sure what their priority is.

**Comment by jjinnii** [comment]
Thanks @erzhtor! If they're captured in issues, would you be able to share them so I can understand the full scope of instruction changes that are needed?

Also a side question -- is adding the verbiage of "configure on Sourcegraph" a part of this issue as well? I believe in current implementation, we only have the Sourcegraph icon.

**Review by david-sandy — APPROVED** [review]
I think that is fine.  As long as we verify that the authenticated user has access to the repos/settings we should be fine.

**Comment by ryankscott** [comment]
I'm not sure if we can detect if someone has an account and for on-prem or cloud or not. Assuming we can I imagine we'd want:

1. Has cloud account - redirect to "Manage my repositories"
2. Has on-prem account - redirect to "Manage my repositories"
3. Has no account - ??? 

For option 3 we could:

a. Redirect them directly to sign up to cloud (https://about.sourcegraph.com/get-started/cloud)
b. Redirect them to https://about.sourcegraph.com/get-started so that they can make the choice of self-hosted or cloud? 

Personally I think option a. makes the most sense, worst case we can do some identification of the user to see if they're likely part of an enterprise (e.g. email domain etc.) and if required create a lead for SDR to qualify.

Please let me know if my assumptions are incorrect, and if you have a preference for option 3.

**Comment by erzhtor** [comment]
Hey @ryankscott, thanks for the review!
> 1. Has cloud account - redirect to "Manage my repositories"

This PR change is exactly about it.
> 2. Has on-prem account - redirect to "Manage my repositories"

I believe, users on on-prem accounts don't have "manage my repositories", since admins only can configure repositories to sync. So currently we show "Repo not found" badge.

> 3. Has no account - ???
> 
> For option 3 we could:
> 
> a. Redirect them directly to sign up to cloud (https://about.sourcegraph.com/get-started/cloud) 
> b. Redirect them to https://about.sourcegraph.com/get-started so that they can make the choice of self-hosted or cloud?
> 
> Personally I think option a. makes the most sense, worst case we can do some identification of the user to see if they're likely part of an enterprise (e.g. email domain etc.) and if required create a lead for SDR to qualify.
> 

We already show the "sign in to cloud" button, which opens the sign-in page. Please, let us know if you have any other questions.

With that said, I think we are good to merge this PR. Let me know if not?

**Comment by jjinnii** [comment]
My concern with the banner is that a private instance user who hasn't yet changed the URL and navigates to a private repo will get the same instructions for "manage my repositories". Which then if they click, based on @erzhtor 's recent comment, they'll get a "Repo not found" page. Maybe it's an edge case, and like I said in my earlier comment that we do have dedicated instructions on the UI for private instance users, so I'm OK with these changes. 

@ryankscott My secondary concern is that the "change URL to use on private code" and "sync private repos to view private code" is not an obvious nuance. (on-prem v. Cloud). Does that read that way to you? Maybe I'm too focused on copy and concerned about something that's not an issue.

**Comment by erzhtor** [comment]
@jjinnii,
> Thanks @erzhtor! If they're captured in issues, would you be able to share them so I can understand the full scope of instruction changes that are needed?

Sorry, I somehow missed this question. I've created an issue to update instructions/docs regarding private repository support. https://github.com/sourcegraph/sourcegraph/issues/31843

> Also a side question -- is adding the verbiage of "configure on Sourcegraph" a part of this issue as well? I believe in current implementation, we only have the Sourcegraph icon.

Nope, it was there already, it was just linking/opening the browser extension "Options" page previously, and in this PR we are changing it to link/open the "manage repositories" page on the web.

To be clear, "Configure Sourcegraph" button shows up only in case if user is using Cloud URL and signed in web/cloud.

**Comment by erzhtor** [comment]
@jjinnii, @ryankscott, 
> My concern with the banner is that a private instance user who hasn't yet changed the URL and navigates to a private repo will get the same instructions for "manage my repositories". 

"private instance user who hasn't yet changed the URL" is treated as a cloud user because the source of truth for browser extension is the URL set in the input.

> Which then if they click, based on @erzhtor 's recent comment, they'll get a "Repo not found" page. Maybe it's an edge case, and like I said in my earlier comment that we do have dedicated instructions on the UI for private instance users, so I'm OK with these changes.
>
> @ryankscott My secondary concern is that the "change URL to use on private code" and "sync private repos to view private code" is not an obvious nuance. (on-prem v. Cloud). Does that read that way to you? Maybe I'm too focused on copy and concerned about something that's not an issue.

So, to make it clear, the following are all cases of buttons/links that appear when repository is not found:
<details>
<summary> Screenshots</summary>

| Case | Button | Previous link/page | Current link/page (changed in this PR) |
| --: | :-- | :-- | :-- |
| 1. When using self-hosted URL | image| image | Did not change. |
| 2. When using Cloud URL and NOT signed in | image | image | Did not change. |
| 3. When using Cloud URL and signed in | image | image | image | 

</details>

So in the scope of this PR, we are only changing "case 3" as described + updating instructions in options page:
<details>
<summary> Screenshots </summary>

| Before | After |
| --: | :-- |
| image |  image |
</details>

Hope this makes it more clear.

Also, let us, please, know if you are good with these particular PR change or not? Maybe suggestions on button and options page instructions copy.

**Comment by ryankscott** [comment]
Just to wrap this up, the changes for the button and redirects seem good so let's definitely roll those out. The banner changes need a bit more thinking to ensure we give a good user experience for both cloud and on-prem users. Let's spin this off to another issue so we can give it the attention it needs.

**Review by erzhtor — APPROVED** [review]
Great job! Looks good to me. 👍

**Pull request merged**
