### PR TITLE
dev/sg: try to update dev-private if used

### PR DESCRIPTION
**Pull request by bobheadxi**
This steps is optional, and will continue with a warning if it fails.

https://sourcegraph.slack.com/archives/C01N83PS4TU/p1664904839499469

## Test plan

```
$ go run ./dev/sg start
⚠️ WARNING: failed to update dev-private:

exit status 128: error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

💡 Running 4 checks...
✅ Check "docker" success!
✅ Check "redis" success!
✅ Check "postgres" success!
✅ Check "git" success!

💡 Installing 15 commands...
```

### CODE REVIEW

**Review by burmudar — APPROVED** [review]
image

**Comment by mrnugget** [comment]
This "breaks" my local [workflow](https://xkcd.com/1172/): I now always get this warning, because I have local changes in my `dev-private` (which is still the easiest way to ensure your site-config and local code host connections are setup in a specific way):

screenshot_2022-10-05_15 32 12@2x

**Comment by burmudar** [comment]
Possible improvements here I think:
* Add this pull to the auto update mechanism in sg 
* Add a .sgignore file to dev-private
* Add a commandset flag

**Comment by mrnugget** [comment]
> In my mind that seems like desired behaviour, though the messaging could be improved - i.e. "hey there's an update, but we couldn't update you"

Yeah, if it's an INFO message that says that, that's fine. Although `git pull` failing doesn't guarantee that there _is_ an update. `git fetch` and then checking whether there's something new in `origin/main` compared to `main` would be a good improvement. "Hey, there's new stuff in dev-private, stash your changes and `git pull` buddy" would be good info.

**Pull request merged**
