### PR TITLE
debt: make `authz.SubRepoPermissionChecker` a second parameter of all gitserver client methods.

### PR DESCRIPTION
**Pull request by sashaostrikov**
Test plan:
It is refactoring, existing tests should pass.

Closes https://github.com/sourcegraph/sourcegraph/issues/44782

### CODE REVIEW

**Review by ryanslade — APPROVED** [review]
Very cool. I tried to do this the other day but I couldn't get `sg generate` to work... glad you managed to figure it out.

**Comment by sashaostrikov** [comment]
> It seems though, that there is one implementation besides testing and no-op. Does that mean, we could aim at moving the checker to `New` and save one parameter from every method?

Hmm, I don't remember implementation details now, but I think we considered some options and move forward with setting a global `DefaultSubRepoPermsChecker`.

@ryanslade do you remember anything from those times and do you have any reservations against moving the checker to gitserver client?

I need to think more about this idea and it would be nice to have some additional input :)

**Comment by sashaostrikov** [comment]
[Main-dry-run](https://github.com/sourcegraph/sourcegraph/tree/main-dry-run/subrepo-checker-refactoring) branch just in case.
https://buildkite.com/sourcegraph/sourcegraph/builds/190563

**Comment by ryanslade** [comment]
> > It seems though, that there is one implementation besides testing and no-op. Does that mean, we could aim at moving the checker to `New` and save one parameter from every method?
> 
> Hmm, I don't remember implementation details now, but I think we considered some options and move forward with setting a global `DefaultSubRepoPermsChecker`.
> 
> @ryanslade do you remember anything from those times and do you have any reservations against moving the checker to gitserver client?
> 
> I need to think more about this idea and it would be nice to have some additional input :)

It would definitely make the interface easier to use and we already do this with `db`. I think the only downside is that it's difficult for the caller to know whether sub-repo permissions could be applied. By requiring it as a param it makes it very explicit which I think is often worth the overhead.

**Comment by sashaostrikov** [comment]
well, only frontend tests failed, I think I'm good to merge

**Pull request merged**
