### PR TITLE
Web: Move use feature flag to the shared package

### PR DESCRIPTION
**Pull request by vovakulikov**
## Background 
In the https://github.com/sourcegraph/sourcegraph/pull/40772 we encountered a need to use useFeatureFlag outside of web package. Prior to this PR this wans't possible because all logic around useFeatureFlag was stored inside of the web package. This PR moves useFeatureFalg and the requestGQL method inside of the shared package in order to import them in different packages (search, search-ui, web, ...)

## Test plan
- Make sure that CI is green 

## App preview:

- [Web](https://sg-web-vk-make-use-feature-flag-shared.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-xbggrptokg.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by vovakulikov** [comment]
Discussed this PR and its changes with @valerybugakov. 
Concerns 
- We don't want to move the `graphql.ts` file in the shared because the shared package, by its definition, should have only platform-agnostic shared logic. But `graphql.ts` has parts ( like `window?.context?.xhrHeaders`) that depend on web types or conventions. 

If we want to migrate useFeatureFlag into the shared package, we should decouple feature flag manager logic and `requestGraphQL`. Use the Apollo client instead and leave `requestGraphQL` in the web package. 

cc @erzhtor, do you remember there were any problems with using apollo for fetching feature flag information? Why did you pick `requestGraphQL`?

**Review by valerybugakov — COMMENTED** [review]
Sharing for visibility: we discussed the issue with @vovakulikov on a quick Zoom call and decided to make changes that would allow us to:

1. Keep web-application-specific code in the `web` package. (e.g., `window.context` access, `getWebGraphQLClient`, etc.)
2. Potentially keep the `requestGraphql` function in the `web` package and access it in the `FeatureFlagClient` via `props` or `context`.

Eventually, we want to eliminate the `shared` package in favor of smaller, well-documented packages with a clear purpose. It's helpful to avoid adding new modules to this package if we can keep them in other, more relevant places.

**Comment by valerybugakov** [comment]
Ha, it took us the same time to write a summary comment 🙂

**Comment by vovakulikov** [comment]
Since this PR https://github.com/sourcegraph/sourcegraph/pull/40381 solves problems with aggregation components and we no longer need to import useFeatureFlag in that PR (and also because it turned out that moving feature flag logic into the shared is not so obvious as I thought), I think we can close this PR and focus on merging https://github.com/sourcegraph/sourcegraph/pull/40381 

cc @unclejustin

**Comment by erzhtor** [comment]
> Discussed this PR and its changes with @valerybugakov. Concerns
> 
> * We don't want to move the `graphql.ts` file in the shared because the shared package, by its definition, should have only platform-agnostic shared logic. But `graphql.ts` has parts ( like `window?.context?.xhrHeaders`) that depend on web types or conventions.
> 
> If we want to migrate useFeatureFlag into the shared package, we should decouple feature flag manager logic and `requestGraphQL`. Use the Apollo client instead and leave `requestGraphQL` in the web package.
> 
> cc @erzhtor, do you remember there were any problems with using apollo for fetching feature flag information? Why did you pick `requestGraphQL`?

Sorry for the late reply. @vovakulikov, it was not a specific decision to use requestGraphQL. I think we just reused [existing feature flag retrieval logic which used requestGraphQL](https://github.com/sourcegraph/sourcegraph/pull/35531/files#diff-b869d12d425a03656ea2b8b568531979d602842a0933b6c281ea4476eda43d56L34-L66).
I think we can safely migrate to an apollo client if that is needed to move the hook into a shared package.

**Pull request closed without merging**
