### PR TITLE
Code intel index configuration: Split protected policies and improve messaging

### PR DESCRIPTION
**Pull request by umpox**
Follow up on https://github.com/sourcegraph/sourcegraph/pull/47551 from @efritz 

## Description

Main goals here are:

- Avoid giving users the impression that policies are already configured (because they see 3 policies in the list when they scan it)
- Better introduce new users into the flow of creating a new policy. No custom policies -> Docs or CTA -> Create policy (pls)

Changes:

- Splits protected and unprotected policies into "Default" and "Custom" ones in the UI
- Updates empty policies UI:
  - Better links to documentation for both data retention and indexing. Links differ based on if the user is viewing from a repo or from site admin
  - Introduce CTA, to help encourage users that there is stuff they can do here (!). Also helped that the default policies are sectioned off. 
- Updates wording from "No policies defined" to "No policies found" (as this UI will also show if a user tries to filter by a nonexistent policy)

### Screenshots - (Admin)

image

image

### Screenshots - (non admin)

image

## Test plan

Tested locally

## App preview:

- [Web](https://sg-web-tr-index-config-updates.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by efritz — APPROVED** [review]
Is it odd that the same control is rendered twice? I think it would _also_ be odd to hide it since it would be an inconsistent header then, though.

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.00 kb) | 0.01% (+2.16 kb) | 0.02% (+2.16 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/tr/index-config-updates/compare-report.html;tab=live_object) for a full comparison between the commits f5337a5 and 2e60c06 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by umpox** [comment]
@efritz Yeah I thought about omitting it from the header but that feels odd too. Feels better on an actual page though, rather than squashed in the screenshot.

Do you know if we have any marketing resources for precise code intel? It'd be great to be able to show some copy, or even embed a video that "sells" this a bit more. Right now we basically have the feature, docs for the feature, but not much about what the feature enables!

**Comment by umpox** [comment]
(Will merge, might re-address later)

**Pull request merged**
