### PR TITLE
security: Log raw event when we fail to store in db

### PR DESCRIPTION
**Pull request by ryanslade**

### CODE REVIEW

**Comment by ryanslade** [comment]
Need this to investigate some logs we're seeing where access is granted to private repos with no user info

**Review by tsenart — APPROVED** [review]
Could it be repo-updater? I think we do authzBypass there?

**Comment by ryanslade** [comment]
> Could it be repo-updater? I think we do authzBypass there?

The logs you pointed at are coming from frontend which is really odd

**Comment by ryanslade** [comment]
I'm going to merge https://github.com/sourcegraph/sourcegraph/pull/23391 so that we don't need to check for internal actor or authzbypass

**Pull request merged**
