### PR TITLE
App setup: Lock window size in the setup flow

### PR DESCRIPTION
**Pull request by vovakulikov**
[Desings ](https://www.figma.com/file/ZkJFUvVzZW9TgFg7k9w9Oq/App-%5BMAIN%5D?type=design&node-id=62-661&t=PZMjaLVAmJdI4ZIx-0)

Based on setup flow designs, we have to lock the window size when we are in the setup flow (the window should be fixed-sized and shouldn't be able to resize); right after the setup flow is finished, we should reset the setup flow to a fixed size and unlock resize. 

@danielmarquespt note that I used a bit increased height value here because the suggested 540 was too small for steps with the progress bar below. I can reevaluate the height value after we get the progress bar UI in place. 

## Test plan
- Check that in the setup flow, you can't resize the window, and it has a fixed 940x640 size
- Check that after setup flow window has standard 1024x768

### CODE REVIEW

**Review by limitedmage — COMMENTED** [review]
I'm not sure if it's a good idea to limit the size of the window. I'm concerned about users trying to run the app on small displays; it's not generally a problem on Mac but might be on Linux and Windows, depending on the monitor and device used. This is potentially also an accessibility issue if the user has a large level of zoom or desktop scaling set.

**Comment by vovakulikov** [comment]
@limitedmage I also thought about this as a potential problem, but I also think that 940x640 is a relatively small size. I can't imagine that someone has lees resolution that this window wouldn't fit. Note that resize is available when the setup flow is finished 

But good point, I'm not against not having lock size, UI there  is already adaptive cc @danielmarquespt

**Comment by limitedmage** [comment]
FWIW, WCAG 2.1 AA requires supporting down to 480px in width.

**Comment by danielmarquespt** [comment]
Desktop apps have minimum sizes for their windows. Even with accessibility in mind 960px seems like its plenty. MacOS doesn't allow resolutions lower than 960px wide.

@limitedmage those guidelines make sense for websites that need to be functional on multiple devices, specially with thin viewports. I don't think those guidelines are applicable to Desktop environments.

**Review by danielmarquespt — APPROVED** [review]

**Pull request merged**
