### PR TITLE
Enhancement: CloudInfo icon for No Repo alert

### PR DESCRIPTION
**Pull request by st0nebraker**
Small enhancement following up [this feedback](https://sourcegraph.slack.com/archives/C04J6HSHVJ5/p1679320207795339). Changes the No Repo alert icon to **info** status instead of **warning**.

### BEFORE
image

### AFTER
image

## Test plan
- Run `EXTSVC_CONFIG_ALLOW_EDITS=1 sg start`
- Remove any connected code hosts
- Ensure No Repo alert icon in upper right nav reflects as expected

## App preview:

- [Web](https://sg-web-becca-cloud-status-info.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.04% (+1.12 kb) | 0.01% (+1.12 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/becca/cloud-status-info/compare-report.html;tab=live_object) for a full comparison between the commits f7ef843 and 3ea53b5 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by vovakulikov** [comment]
@almeidapaulooliveira, a few visual points from me
- Do you think the Setup code hosts link is too faded out? 
- Curios about this turquoise colour for the dot next to the cloud icon. Should it be the same colour that we have for info icons within the popover?

**Comment by st0nebraker** [comment]
> > @almeidapaulooliveira, a few visual points from me
> > 
> > * Curios about this turquoise colour for the dot next to the cloud icon. Should it be the same colour that we have for info icons within the popover?
> 
> It should be. Can you check the colors on [this Figma](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=1366-168&t=9f7RqBHL294wflac-4)? I'm using the `Semantyc/Icon`... colors.

That color isn't high contrast enough to be accessible for the link & info icon, as a dot I think it's okay. But to make them uniform, I propose we make all 3 colors here [primary-01](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=5601-64976&t=yOmRZChZJpYfYQWp-0)

image

**Comment by almeidapaulooliveira** [comment]
> That color isn't high contrast enough to be accessible for the link & info icon, as a dot I think it's okay. But to make them uniform, I propose we make all 3 colors here [primary-01]
Oh, sorry. I didn't understand that you were referring to the link as well. I think the link should use the standard link style. Wdyt?

**Comment by almeidapaulooliveira** [comment]
>  I propose we make all 3 colors here

I would follow the semantic color palette for the icon. So we're aligned with the other 'info' components colors in the system.

**Comment by st0nebraker** [comment]
> > I propose we make all 3 colors here
> 
> I would follow the semantic color palette for the icon. So we're aligned with the other 'info' components colors in the system.

That color is in violation of color contrast accessibility when run against the ARC Toolkit test is my only gripe. It's not implemented in our code base yet which is why it hasn't come up yet. What do you think @vovakulikov ? And accessibility champion @limitedmage ? Would you be okay with this color used on `mdiInfoOutline`?

image

**Comment by st0nebraker** [comment]
> * Do you think the Setup code hosts link is too faded out?

Fixed in [215a645](https://github.com/sourcegraph/sourcegraph/pull/49809/commits/215a645fa10d99030a87ccca0a5244131cb54506), there was a global hover style that doesn't suite dark mode

**Comment by vovakulikov** [comment]
@st0nebraker @almeidapaulooliveira in light of a11y problem, I think we can keep the original blue colour for the icon and this turquoise blue for the cloud dot,  but ideally, I would fix our Figma colour because it's clear that we violate contrast in the light theme. Maybe it should be a separate issue 

cc @limitedmage

**Comment by vovakulikov** [comment]
@almeidapaulooliveira just noticed this, should the new info state also has this vertical line below the icon?

**Comment by almeidapaulooliveira** [comment]
> just noticed this, should the new info state also has this vertical line below the icon?

@vova, did you forget to upload a screenshot? ;-)

**Comment by vovakulikov** [comment]
Screenshot 2023-03-21 at 20 39 27

**Comment by st0nebraker** [comment]
> Screenshot 2023-03-21 at 20 39 27

Good eye, fixed!
image

**Comment by mrnugget** [comment]
Very cool!

**Comment by limitedmage** [comment]
Re: a11y color contrast, you can use https://webaim.org/resources/contrastchecker/ to check the contrast; in this case, because this is a non-text graphical object, the minimum contrast should be at least 3:1. The screenshot shown in the description has a contrast of 1.6:1 which is way too low; was that color updated before merging the PR?

**Comment by st0nebraker** [comment]
> Re: a11y color contrast, you can use https://webaim.org/resources/contrastchecker/ to check the contrast; in this case, because this is a non-text graphical object, the minimum contrast should be at least 3:1. The screenshot shown in the description has a contrast of 1.6:1 which is way too low; was that color updated before merging the PR?

That's a great resource, thanks @limitedmage. The [info](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=5601-64976&t=oKlw2c1FMuojZJvu-0) color was used here. It looks like all the info color shades on light theme fail the WCAG contrast standard ([here](https://webaim.org/resources/contrastchecker/)). @sourcegraph/design should there be an audit/revamp on the Figma's color palette to make sure they all have proper contrast? What color should I swap for here? `primary` ?

Component in question:
image

**Comment by almeidapaulooliveira** [comment]
- @st0nebraker, `primary` it's Ok. I'm not sure if this audit wasn't done in the past, @rrhyne should have some context.

**Pull request merged**
