### PR TITLE
WIP: monitoring: define grafana dash with python code

### PR DESCRIPTION
**Pull request by uwedeportivo**
Define grafana dashboards in a parametrized high level declarative  python script. Enables definition sharing.

All these files will move to a more appropriate place where they can be used/shared by all columns in our deploy matrix.  If we're comfortable with https://github.com/weaveworks/grafanalib we can integrate this with a generate step and CI.

### CODE REVIEW

**Comment by uwedeportivo** [comment]
The script generated json did not pass "prettier". I will add a step to run it through prettier in generate.sh/CI.

**Comment by uwedeportivo** [comment]
This is how the script-produced json dashboard looks like:

frontend_services
ext_services

**Comment by uwedeportivo** [comment]
I'm happy with the python defined grafana dashboards but I'm going to hold off merging this in until I have a plan on how to share prometheus rules and grafana provisioning configs across the deploy matrix.

**Comment by uwedeportivo** [comment]
Feel free to ignore this PR until then.

**Comment by slimsag** [comment]
I'd like to inquire a bit more about two aspects of this

1. Is the aim here that (a) we have a variation of the following dashboard for each service (frontend, gitserver, repo-updater, searcher, etc.) _in addition to_ the existing hand-made dashboards for those services, OR is the idea that (b) we would use this code generation approach to eventually replace e.g. https://github.com/sourcegraph/sourcegraph/blob/a97318c2378c6e1017322130349ad25ec7c39e10/dev/grafana/provisioning/dashboards/sourcegraph/gitserver.json



- If the answer is A, I think that makes sense and am happy to go forward with this.
- If the answer is B, I am a bit worried that writing these dashboards in Python will be a barrier to having each service owner actually maintain these dashboards and include better per-service metrics in them. Grafana's web editing UI is quite nice.

2. Does it make more sense to have "API calls to external services" be in a per-service dashboard? After all, the service making the requests is probably an important aspect. e.g. if repo-updater is making lots of API calls to GitHub, that is reasonable but if the frontend is doing it then it could be an issue.

**Comment by uwedeportivo** [comment]
> 1. Is the aim here that (a) we have a variation of the following dashboard for each service (frontend, gitserver, repo-updater, searcher, etc.) _in addition to_ the existing hand-made dashboards for those services, OR is the idea that (b) we would use this code generation approach to eventually replace e.g. https://github.com/sourcegraph/sourcegraph/blob/a97318c2378c6e1017322130349ad25ec7c39e10/dev/grafana/provisioning/dashboards/sourcegraph/gitserver.json
> 
> 
> 
> * If the answer is A, I think that makes sense and am happy to go forward with this.
> * If the answer is B, I am a bit worried that writing these dashboards in Python will be a barrier to having each service owner actually maintain these dashboards and include better per-service metrics in them. Grafana's web editing UI is quite nice.
> 

I'm still exploring things. I'm not ready to replace any existing stuff :-). No matter how we generate the dashboard json files, they will be checked into a repo somewhere. It doesn't really matter how they get created. It's more convenient for graphs that are repeated a lot to have a script generate the json for them. That's why I chose http client qps and latency for this. Practically every node makes these and we would be interested in them.

> 1. Does it make more sense to have "API calls to external services" be in a per-service dashboard? After all, the service making the requests is probably an important aspect. e.g. if repo-updater is making lots of API calls to GitHub, that is reasonable but if the frontend is doing it then it could be an issue.

Yeah, for sure. We can partition it out anyway we want. 

Sorry, all of this is experimenting still. Didn't want to waste your time.

**Comment by beyang** [comment]
Please add us back as reviewers once this is ready to review :)

**Comment by uwedeportivo** [comment]
this is obsolete. we decided to use jsonnet and grafonnet

**Pull request closed without merging**
