### PR TITLE
Users should not see private repositories that they have not added on Cloud

### PR DESCRIPTION
**Pull request by indradhanush**
COREAPP-151 #done

### CODE REVIEW

**Review by ryanslade — APPROVED** [review]
LGTM 😄

**Comment by indradhanush** [comment]
Will hold off on merging until Monday. It's Friday after all and this is an important change.

**Comment by coury-clark** [comment]
What is the context here? I don't think I have access to read that Jira ticket.

**Comment by unknwon** [comment]
@coury-clark For code insights, this PR is fixing a test setup issue, where any repo should have a corresponding row in the `external_service_repos` table, which our authz SQL query would be looking at.

**Review by unknwon — APPROVED** [review]

**Pull request merged**
