### PR TITLE
grpc: symbols: convert gRPC Cancelled/DeadlineExceeded errors to corresponding "context" errors

### PR DESCRIPTION
**Pull request by ggilmore**
fixes https://sourcegraph.slack.com/archives/C04HCK4K3DL/p1686110895682199

## Test plan

CI

### CODE REVIEW

**Comment by camdencheek** [comment]
LGTM 👍

**Review by camdencheek — APPROVED** [review]

**Review by mucles — APPROVED** [review]
Nice 👍

**Comment by ggilmore** [comment]
@cla-bot check

**Comment by ggilmore** [comment]
@cla-bot check

**Pull request merged**
