### PR TITLE
Repo page: Add new repo link picker UI

### PR DESCRIPTION
**Pull request by vovakulikov**
This PR simply extends existing UI about repository button/breadcrumb. With new repository picker it should be very easy to switch between different repositories. 

https://github.com/sourcegraph/sourcegraph/assets/18492575/c4f18276-77a2-487c-ab43-0976d9dacd6d

## Test plan
- Check that main repository button is still a link and steal leads to the repository root page
- Check that you can quickly switch repositories with newly added picker UI

### CODE REVIEW

**Review by fkling — APPROVED** [review]

**Review by camdencheek — APPROVED** [review]
Nice! I honestly didn't realize it didn't do this already.

**Comment by sqs** [comment]
I don't think this is working as intended.

At https://sourcegraph.com/github.com/sourcegraph/sourcegraph if I use it, here's what I see:

image

The results are not relevant or ranked correctly.

Then if I delete the `sourcegraph` text in the input, it does not reload the search.

I don't know if we have telemetry here on this to see if people use it (or the previous incarnation of it). I haven't seen anyone use it personally.

I'd propose removing this, or making it open the fuzzy search (Ctrl+P).

cc @taiyab

**Comment by jasonhawkharris** [comment]
@sqs I'm not aware of what telemetry we currently have to measure the use of the picker, but I too suspect that it is not used very often. I wouldn't be opposed to removing it either. It seems like overkill 🤷🏼

**Comment by taiyab** [comment]
@sqs I think having it open the fuzzy finder under the repos tab is probably a good bet (for now at least).

Ultimately though, we need to rethink the purpose of that whole menu.

IMO, it should be focused on being a great way to discover and traverse the repos within a given org (think about the Code Search LHS repo list concept but extending that ad infinitum). It'll need to be reworked quite a bit before it can do that.

**Comment by sqs** [comment]
Idea: add the fuzzy finder to the top nav with a `Go to...` label or icon or something like that. And then remove it as a dropdown from the repo header altogether.

**Comment by taiyab** [comment]
@sqs That moves in the direction of essentially merging the fuzzy finder + search query into one input/function (which I'm a big fan of if done correctly).

How's this?

image

**Comment by sqs** [comment]
@taiyab Ah, I do like that as an idea! We could do something in between as an incremental step, though, and I think that would still be an improvement.

**Pull request merged**
