### PR TITLE
src-expose: Add README.md with usage info

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by keegancsmith** [comment]
We generally would like to document this in our main docs, rather than a readme. Additionally we have plans in the next month or two to graduate this tool into our official src-cli tool. Given this information is present from the tool itself, I'd like to avoid adding in things like this for now (since it will invariably get out of date)

**Comment by keegancsmith** [comment]
We did move to src-cli, so closing out.

**Comment by abitrolly** [comment]
Is that `src serve-git`? https://github.com/sourcegraph/src-cli#usage

**Comment by keegancsmith** [comment]
> Is that `src serve-git`? 
> https://github.com/sourcegraph/src-cli#usage

Yup

**Pull request closed without merging**
