### PR TITLE
Fix inaccessible links in documentation

### LINKED ISSUE #261: Inaccessible references to sgdev.org in documentation
There are many references to `sgdev.org` in the documentation contained in this repo that are not accessible to people outside of Sourcegraph. The [architecture.md](https://github.com/sourcegraph/sourcegraph/blob/master/docs/architecture.md) page is particularly bad.

I believe all of `sourcegraph.sgdev.org/github.com` links could be replaced with their `github.com` equivalents. I'd be happy to submit a PR if that is the case.

### PR DESCRIPTION
**Pull request by ianlopshire**
> This PR does not need to update the CHANGELOG because it does not include any user-facing changes.

closes #261

### CODE REVIEW

**Comment by ianlopshire** [comment]
https://sourcegraph.sgdev.org/github.com/sourcegraph/website/-/blob/STYLEGUIDE.md in [style.md](https://github.com/sourcegraph/sourcegraph/blob/master/docs/style.md) is still inaccessible. Perhaps that document should be pulled into this repo somewhere else publicly accessible.

**Comment by beyang** [comment]
@ianlopshire thanks for this PR! Could you sign [the CLA](https://goo.gl/forms/x6Am2wAgriiUyAYE3) so we can merge this?

**Comment by keegancsmith** [comment]
I believe for smaller changes such as this, we don't need the CLA signed. We will be updating our automation and policy soon. As such I am going to merge this. If I am incorrect, lets revert until signed. cc @dadlerj @sqs

**Comment by felixfbecker** [comment]
This broke CI

**Comment by keegancsmith** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/commit/6ebd417c77d9fd01312bf0199585e2db2fbd3065

**Pull request merged**
