### PR TITLE
web: enable import/order ESLint rule

### PR DESCRIPTION
**Pull request by valerybugakov**
### Description

I've seen discussions about import ordering in multiple PRs and Slack threads, so I went ahead and enabled the [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) ESLint rule in our config. I haven't fixed all the errors produced by the rule yet. If nothing stops us from enabling this rule, I will create PR to our https://github.com/sourcegraph/eslint-config package with this update and run the auto-fix on this repo.

### Changes

- Enabled [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) ESLint rule

### CODE REVIEW

**Comment by umpox** [comment]
Nice! Any reason not just to add this straight to `eslint-config` and skip this step?

**Comment by valerybugakov** [comment]
@umpox just wanted to get feedback here first. After that, I will run auto-fix in this PR if no one sees any blockers.

**Comment by eseliger** [comment]
I like it, but agree with @umpox. Other than that LGTM :)

**Comment by limitedmage** [comment]
> I like it, but agree with @umpox. Other than that LGTM :)

+1

**Comment by felixfbecker** [comment]
FYI, not a big deal: we usually use the imperative mood in PR titles and commit messages (as opposed to past tense like here and in some other PRs I saw). See https://docs.sourcegraph.com/dev/background-information/commit_messages (applies to PR titles too because they become commit messages when squashing to `main`)

**Review by limitedmage — APPROVED** [review]

**Review by eseliger — APPROVED** [review]

**Pull request merged**
