### PR TITLE
telemetry-export: include interaction.traceId on events

### PR DESCRIPTION
**Pull request by bobheadxi**
This change will add OpenTelmetry trace IDs, which can be propagated from clients to Sourcegraph backends, to all events as they get exported if the trace ID is valid. This trace ID is then reported to Telemetry Gateway and our BigQuery data, allowing us to get per-interaction matching across different data sets, such as Cody Gateway's data, as was asked about [here in the "Gateway to eventlogger mapping" doc](https://docs.google.com/document/d/1V5MK_SI7OnvzVSi1AnhuX5RzvIZTNIZ3MdHACTBz0tE/edit?disco=AAAA67cXdpM).

I think standardizing on trace IDs for tracking user interactions is a good idea because it's an open standard for describing interactions already, and integrates with common observability tooling through trace exports, so investments made to track interactions for telemetry benefit observability and vice versa.

Trace IDs can be propagated via https://opentelemetry.io/docs/instrumentation/js/propagation/ - this was already set up in the web app in the past.

Multiple events can correspond to the same trace ID, so this is different from event ID.

## Test plan

Unit tests

### CODE REVIEW

**Comment by bobheadxi** [comment]
If this seems useful I can request a backport for it as well

**Review by rafax — APPROVED** [review]
Idea and code LGTM, from Cody Gateway POV - do we need to extract the TraceID and add it to `events` metadata?

**Comment by bobheadxi** [comment]
> Idea and code LGTM, from Cody Gateway POV - do we need to extract the TraceID and add it to events metadata?

Yeah, here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/cody-gateway/internal/httpapi/handler.go?L93-105

We configure endpoints to accept incoming traces as _links_ only, so the Cody Gateway trace != the incoming trace - we added this because when traces are missing spans, Cloud Trace was prone to some weird behaviour.

Sadly, it also doesn't look like the OpenTelemetry SDK gives us the ability to see these spans after the fact. Looking at the source code, of the OpenTelemetry HTTP instrumentation though, it seems we can extract the incoming trace again using:

```go
// ctx will have incoming trace
ctx := h.propagators.Extract(r.Context(), propagation.HeaderCarrier(r.Header))
```

Our default propagators are configured in `internal/tracer/oteldefaults`

**Comment by bobheadxi** [comment]
Manual backport at https://github.com/sourcegraph/sourcegraph/pull/57962

**Pull request merged**
