### PR TITLE
RFC Use python for shell scripts

### PR DESCRIPTION
**Pull request by keegancsmith**
I got started down a path of making the zoekt shell script very complicated, so first I converted it to python. I've stopped that path for now since I started getting into over-engineering territory. But I was really enjoying using a cleaner and more powerful language.

Things you get:
- Testability
- A REPL
- Easy to use data structures (maps, sets, etc)
- Batteries included.

This PR is for others to comment on the idea of using python (or another "OS default" scripting language) for our dev scripts. This is just the initial commit I did to show the basic setup replacing a very simple shell script. WDYT?

Note: I do not intend on landing this PR, it exists for discussion.

### CODE REVIEW

**Comment by unknwon** [comment]
I like Python over Bash (sorry I born too late to know Bash well).

Maybe also worth considering, https://blog.cloudflare.com/using-go-as-a-scripting-language-in-linux/. Don't know if we had discussion of this option before I joined.

**Comment by keegancsmith** [comment]
We already use go quite often when things get more complicated, but not as a shebang. Instead we just call `go run`. A while ago there was some typescript written for a more complicated shell script, but we weren't all on agreement on that being a good idea. I think python is nicer than TS for this since it doesn't require any dependencies and is a more "traditional" replacement for shell scripts. Basically I like python since I think it would be faster to write than go and bash, and be easier to read for shell script like tasks.

**Comment by tsenart** [comment]
I like Python too! Wouldn’t mind it being our go to for medium complexity scripts.

**Comment by mrnugget** [comment]
👍 on using a proper scripting language. My Python experience is limited and probably less than Bash, but I'd be willing to learn. Ruby, just so it's mentioned, would be my go-to, but I do know that it's not as common as Python.

**Comment by keegancsmith** [comment]
> I think bash scripts are great for simple stuff that is just running a series of commands. This diff is an example where I think the bash script is better.

I agree, I wrote something much more complicated at first which I threw away. This is more of a skeleton. But you get unit tests and data structures!

> I do think there are scripts that would benefit from a higher order language for the reasons you described, such as go-install.sh. Why not use go run in more sophisticated cases instead of something like Python?

I think go is the default, but it is more of a PITA for when you wanna be a bit more of a cowboy. But I think that does make more sense.

**Comment by rvantonder** [comment]
I think Python could work well for "medium complexity" scripts, while at the same time highly encouraging (1) optional type annotations (see mypy, pyre) :P and (2) Black for consistent formatting. 

And no, I don't think type annotations go against the grain of being scripty/cowboy-y :)

**Comment by ggilmore** [comment]
I've also thought about python while working on https://github.com/sourcegraph/sourcegraph/pull/5745, but I got scared off by python 2 / 3 compatibility issues (i.e. the same script could break depending on the environment that it was running in and whatever `/usr/bin/env python` is pointing to). This would be an issue when writing scripts that need to run in dev (mac, Linux) and in CI (whatever Linux distro the buildkite agent is running).

https://magefile.org/ might also be something that we should look into. 

Example: https://github.com/gohugoio/hugo/blob/master/magefile.go

**Comment by keegancsmith** [comment]
I too was worried about py 2 vs 3. But Mac still ships python 2, and I suspect most linux distros do as well? But that may be naive, and instead we default to py3 (and include the brew incantation in our setup guide).

Given the number of people who have wanted to use python for some scripting, I feel good about introducing it the next time I am tempted to use it.

**Comment by lguychard** [comment]
Defaulting to Python 3 would probably be the most sensible choice considering that we're only a couple of months away from the [Python 2 sunset date](https://www.python.org/dev/peps/pep-0373/).

I love Python and am significantly more familiar with it than with Bash, so this gets my 👍

**Comment by nicksnyder** [comment]
Shell scripts are not currently documented in tech_stack.md. @keegancsmith can you propose an update to that document that reflects the current state of affairs?

**Comment by uwedeportivo** [comment]
I keep getting Pull Reminders for it so I guess I should say something :-)

I used python a lot in the past. It's definitely convenient and powerful. That's the upside. The downside is dealing with dependencies, setting up virtualenvs and the like in uncounted many ways etc.

If we decide to use it I recommend being very disciplined and constraint about our python toolchain. Otherwise it's a big headache.

**Comment by slimsag** [comment]
I am strongly in favor of `go run` scripts when `bash` gets more complicated than if/while loops.

I don't like the idea of Python being yet another language to learn and narrowing the number of people who can effectively maintain our dev scripts.

**Comment by unknwon** [comment]
I'm closing this PR to stop bugging by the pull reminder. We can continue to discuss/reopen once @keegancsmith is back from vocation.

**Pull request closed without merging**
