### PR TITLE
insights: Use less precision when aggregating series points

### PR DESCRIPTION
**Pull request by CristinaBirkel**
Closes https://github.com/sourcegraph/sourcegraph/issues/37345

## Description

Outlined the problem here: https://github.com/sourcegraph/sourcegraph/issues/37345#issuecomment-1185711980

I thought to maybe fix it with lowering precision on the way into the database, but that doesn't actually fix the bug for existing insights. I wonder if we should actually round a bit higher. Maybe to the hour? But this will at least match what we're sending the frontend.

## Test plan

I tested this by running the old SQL query vs the new SQL query against the buggy series on the demo environment. It removed the duplicated series.

### CODE REVIEW

**Comment by coury-clark** [comment]
> but that doesn't actually fix the bug for existing insights

Hmm - I wonder if it would be better to eat the one time pain of doing a migration here (could do an in-band migration) instead of adding this to the query path in perpetuity. WDYT?

**Comment by CristinaBirkel** [comment]
@coury-clark We could alter the column structure to be of type `timestamptz(0)` which cuts off the milliseconds. It's quite permanent though! Seems a little more risky somehow, where-as this change is easily reversible if needed. I'd lean towards just using this fix, but I'm not opposed to doing the migration either.

**Comment by chwarwick** [comment]
> @coury-clark We could alter the column structure to be of type `timestamptz(0)` which cuts off the milliseconds. 

I remember reading once to not use `timestamptz(0)` because it rounds instead of truncating so you can use now() and end up saving a time thats slightly in the future.  I don't see why that would be an issue for us but it's one of those odd behaviors I'd probably try to avoid.

**Review by coury-clark — APPROVED** [review]

**Comment by coury-clark** [comment]
Please don't forget a changelog entry

**Pull request merged**
