### PR TITLE
Removed reference to replacer service

### PR DESCRIPTION
**Pull request by alexAtSourcegraph**

### CODE REVIEW

**Comment by daxmc99** [comment]
Could you link to the other PR you created?

**Comment by alexAtSourcegraph** [comment]
@daxmc99 Here is the PR for the change in the resource-estimator project (https://github.com/sourcegraph/resource-estimator/pull/7) Excuse the latest commit message. My wires were crossed and I called the deprecated service "replica" instead of "replacer"

**Review by daxmc99 — APPROVED** [review]
LGTM
The CI failures are unrelated to this PR

**Comment by daxmc99** [comment]
@alexAtSourcegraph is this ready to merge?

**Comment by alexAtSourcegraph** [comment]
Hey, there @daxmc99 totally ready to merge. Sorry for the delay. I was OOO.

**Review by abeatrix — APPROVED** [review]
lgtm

**Comment by lguychard** [comment]
@alexAtSourcegraph this PR should target `main`, not `master`. Could you change the base branch?

**Pull request closed without merging**
