### PR TITLE
cody: fix build, add feedback buttons and debug view

### PR DESCRIPTION
**Pull request by abeatrix**
Close https://github.com/sourcegraph/cody/issues/93

RE: [Slack thread](https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1678715069914879) & continue of https://github.com/sourcegraph/cody/pull/91

- Fix builds [Slack thread](https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1678715069914879)
- add feedback buttons
- add debug view

## Test plan

To launch Cody in VS Code Debug mode:

1. Run `pnpm i` at the root of this repository in this branch
2. Select `Launch Cody Extension` from the dropdown menu in the `RUN AND DEBUG` sidebar in VS Code

To start unit test (WIP - does not work): 

```
pnpm i
cd client/cody
pnpm build:common
cd ../vscode-codegen
pnpm test 
```

## App preview:

- [Web](https://sg-web-bee-cody.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by abeatrix** [comment]
@valerybugakov do you mind taking a look at this PR regarding the pnpm setup for cody?

**Comment by BolajiOlajide** [comment]
Hey!

We noticed this PR was merged after the branch cut and before the Release Protect GH action was active. 
If you are 100% sure your changes should get released or provide no risk to the release, add the backport 5.0 label your PR.  This will backport the changes here into the 5.0 branch.

To learn more about backporting, see the handbook https://handbook.sourcegraph.com/departments/engineering/dev/tools/backport/#how-should-i-use-the-backporting-tool

If you don't intend to backport to 5.0, no action needed! This is just a quick reminder to make sure nothing was missed while we turned the Release Protector on.

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.01% (-0.17 kb) | -0.01% (-0.86 kb) | -0.01% (-0.69 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/bee/cody/compare-report.html;tab=live_object) for a full comparison between the commits ca61fc1 and 1fc50a2 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by novoselrok** [comment]
> File structure

Agreed. The current file structure is only temporary due to the move from the `sourcegraph/cody` to this repo. We will remove the server, common, and embeddings folders, and the contents of the `vscode-codegen` folder will be moved to `client/cody`. This should ensure that we have a familiar structure.

> Would it be possible to start using jest as a test runner in the long term and gradually migrate existing tests to jest APIs?

I don't see a reason why not. I'm looking into adding unit tests for Cody, and I can do the migration to Jest as well.

**Pull request merged**
