### PR TITLE
add checks pipeline

### PR DESCRIPTION
**Pull request by burmudar**
## Test plan
Running this new pipeline on this branch

### CODE REVIEW

**Comment by sourcegraph-buildkite** [comment]
### Check failures
* Check `that my plugin works` failed ❌ - [View logs](https://buildkite.com/sourcegraph/sourcegraph-checks/builds/139#018b3d43-f781-4f36-9660-18044327b2b4)

**Comment by sourcegraph-buildkite** [comment]
### Check failures
* Check `that my plugin works` failed ❌ - [View logs](https://buildkite.com/sourcegraph/sourcegraph-checks/builds/147#018b3d63-3433-45f7-8b0a-f8e588710dca)

**Comment by sourcegraph-buildkite** [comment]
<div class="flex mb1">
    <div class="ml-auto">":clipboard: General Checks"</div>
    <ul>
      <li>* Check `that my plugin works` failed ❌ - <a href=https://buildkite.com/sourcegraph/sourcegraph-checks/builds/148#018b3d66-67b6-4253-8f65-a8fabada9acf>View logs]</a></li>
    </ul>
    </div>
  </div>

**Comment by sourcegraph-buildkite** [comment]
<div class="flex mb1">
    Some checks have failed
    <div class="ml-auto">:clipboard: General Checks</div>
  </div>
  <ul>
    <li>* Check <code>that my plugin works</code> failed ❌ - <a href=https://buildkite.com/sourcegraph/sourcegraph-checks/builds/151#018b3d6d-9a98-40f4-b4d1-670d6a85ea4f>View logs</a></li>
  </ul>

**Comment by jhchabran** [comment]
@burmudar we can close this right?

**Comment by burmudar** [comment]
> @burmudar we can close this right? 

I think so yeah. I don't think it will provide the value I thought it would 😁

**Pull request closed without merging**
