### PR TITLE
searcher: TMPDIR on CACHE_DIR

### LINKED ISSUE #34828: searcher: not respecting on disk cache limit
There are instances of searcher being evicted at customers by kubernetes. We believe the root cause is searcher not respecting the cache limits. The purpose of this issue is to track the root causing of this, provide work arounds and ultimately resolve this issue.

Some related issues:
- Gracefully handle limited shared cache space #627
- searcher and symbols deployments should switch to statefulsets #32279
- Unindexed search archive cache is not monitored #9796
- Searcher pod getting evicted https://github.com/sourcegraph/customer/issues/740

### PR DESCRIPTION
**Pull request by keegancsmith**
Structural search writes to $TMPDIR, leading to evictions since that is
just the normal ephemeral storage on a pod (not tuned). We move
TMPDIR to CACHE_DIR and update diskcache to evict based on all
file sizes, not just zips. Structural writes zips, and it should be safe to
evict those files even if comby is reading them due to it having an open
file descriptor.

Kubernetes evicts searchers if they go too far over the cache size. This
means we need to maintain our cache size for all files, not just zip
files. We can only safely remove zip files, so we still only remove
those. But when making eviction decisions, it is now based on the total
size of the cache dir, not just the size of zip files within.

Test Plan: added a unit test. It was useful since info.Size() works on a
directory but we want to ignore that.

Fixes #34828

### CODE REVIEW

**Comment by efritz** [comment]
@keegancsmith What are in these diskcache directories _besides_ zip files that weren't getting counted before?

**Comment by keegancsmith** [comment]
To be honest, it's a gut feeling. At one point we had structural search unzipping files (cc @camdencheek for context). This was motivated by me investigating why searcher gets evicted, and this seems like a plausible explanation given k8s will check the full dir size and not just the zip files.

But to be honest, I'm not convinced. If this doesn't feel good to you either, I'm happy with just keeping the test I wrote but not the logic changes.

**Comment by keegancsmith** [comment]
@efritz I think the root cause is likely this comment here https://github.com/sourcegraph/sourcegraph/issues/34828#issuecomment-1139643575 TL;DR kubernetes evicting before evict runs. This PR came out of me trying to debug this and reading the source code (and noticing this possible gap).

I'm not sure on next steps here, this feels like the correct thing to do even though it might not be the root cause.

**Comment by camdencheek** [comment]
Any chance [this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6626ec8ce600a4fd1b38a5675b4a20b33bff4778/-/blob/cmd/searcher/internal/search/search_structural.go?L326-331) could be related? Structural search with Zoekt creates a request-scoped zip file that is not tracked by the disk cache. 

When doing unindexed structural search, we reuse the existing cached zipfile, so there is no new untracked disk usage.

**Comment by keegancsmith** [comment]
Yes that is very likely the problem and why I haven't noticed it when I investigated. It is writing to TMPDIR which isn't necessarily a disk with any space at all (unlike cache_dir). I thought structural search might be the issue, but I just investigated a pod after structural search rather than reading code. Always read the src, Luke. I'll send a change soon.

**Comment by keegancsmith** [comment]
Alright we now want this behaviour since I have included TMPDIR under CACHE_DIR. See the comment in the code for justification. Additionally I believe @tbliu98 is working on not writing the zip file, and instead writing to comby via a tarball over stdin. This will remove the intermediate zip file entirely which is ideal.

**Review by camdencheek — APPROVED** [review]

**Comment by keegancsmith** [comment]
Updated PR title and description as well as including a changelog entry. Thanks.

**Pull request merged**
