### PR TITLE
dbtest: Always re-create template database

### PR DESCRIPTION
**Pull request by tsenart**
I spent hours debugging an issue where the latest migration I was
working on didn't get applied properly. The issue was that the template
database was being re-used, and it was previously created off of my
local default database, so the schema_migrations version was already the
latest. That meant no migrations were applied, even though the content
of the migrations had changed.

### CODE REVIEW

**Review by camdencheek — APPROVED** [review]
Wouldn't this same issue apply to any local env? It seems more like an issue with our migration logic

**Comment by tsenart** [comment]
> Wouldn't this same issue apply to any local env? It seems more like an issue with our migration logic

Yes, but in the local env you can easily `./dev/db/drop-local-database.sh` and `./dev/db/migrate.sh up frontend`. Not so with the template database created by tests.

**Comment by camdencheek** [comment]
FYI, this is the PR that started re-using the template DB: https://github.com/sourcegraph/sourcegraph/pull/21355/files

Removing it will cause a few seconds of additional overhead for each tested package, but that's not a terrible cost to pay for more predictable tests. 

Another option I can see as an alternative is making `./dev/db/drop-local-database.sh` also drop all the test databases, so that cost is only paid when we change a schema during dev.

**Comment by mrnugget** [comment]
> Removing it will cause a few seconds of additional overhead for each tested package, but that's not a terrible cost to pay for more predictable tests.

A few seconds per package is significant, I think. If the other option is possible and feasible I think we should investigate that.

**Comment by tsenart** [comment]
> Another option I can see as an alternative is making ./dev/db/drop-local-database.sh also drop all the test databases, so that cost is only paid when we change a schema during dev.

Even better would be for our migration code to be smarter than just relying on incremental sequence numbers, and instead take into account its contents (via hashing).

**Comment by camdencheek** [comment]
> take into account its contents (via hashing).

I actually looked into that briefly! It would require forking the migration library we use though, and I didn't want to own that at the time.

**Pull request merged**
