### PR TITLE
Cody App update notice+install experience

### PR DESCRIPTION
**Pull request by nelsonjr**
Implements the update notice in the Cody App home page and Admin Update page.

### Previous Behavior

When the Cody App launches, it checks for updates. If there's an update, it pops up a modal dialog and asks the user, once, if they want to upgrade. If the user declines, only restarting the application allows the popup to reappear.

This can be challenging to keep it up to date, as the Cody App does not usually quit but instead keeps running in the background to provide data to extensions [VScode, IntelliJ, etc.], and the user will never be notified an update exists unless they proactively close the app.

### New Behavior

Implements periodic checks in the background and user-controlled upgrade checks. The UI updates whenever there's an upgrade available. Allows for version check and installation directly from within the application at any time.

## Test plan

- Storybook for all visual components

- Functionality tested on Windows and MacOS

- Ensures the app can handle
  - No updates
  - Update available
  - Start install
  - Display errors if the download/install process failed

- Update strategies
  - Periodic
  - User check for updates

- Display information about current and new builds correctly

- Implemented Storybook stories for all states, state transitions, and UI placement.

### User Interface

Refer to Storybook @ cody-ui > Updater for visuals.

### CODE REVIEW

**Comment by slimsag** [comment]
In general this looks pretty good to me, but a few thoughts:

1. Does the app still check for updates on startup? I think it should
2. I think we will need to have design take a look at this before we can land it. cc @danielmarquespt 
  * In particular, I am worried about how distracting it could be to have some of those error/update-available states of the UI push the entire rest of the page down - especially with how frequently we release updates (like weekly or every few days) and it being on a timer.
3. Can I still check for updates via the system tray (the feature Chris added)? I think we should retain that functionality

**Comment by nelsonjr** [comment]
> In general this looks pretty good to me, but a few thoughts:
> 
> 1. Does the app still check for updates on startup? I think it should

No. It is mutually exclusive. If we enable it, Tauri will not check by itself. The API is only enabled when the built-in mechanism is turned off (reference: ___.) We must implement our pop-up mechanism.


> 2. I think we will need to have design take a look at this before we can land it. cc @danielmarquespt

Yes!


> * In particular, I am worried about how distracting it could be to have some of those error/update-available states of the UI push the entire rest of the page down - especially with how frequently we release updates (like weekly or every few days) and it being on a timer.

PM+Design could make a call here. I see no difference between various applications like WhatsApp, Signal, and Google Chrome. The notice is there, and it is up to the user's convenience to click whenever they're ready.

We could also make it more discreet, how it for a little bit and dismiss, or any other UX we feel would be more appropriate. In Signal, it occupies the exact size of one contact; similarly, in WhatsApp: 

image


> 3. Can I still check for updates via the system tray (the feature Chris added)? I think we should retain that functionality

I put a "check now" button in the admin UI already. We could send them to that page. WDYT?

**Comment by nelsonjr** [comment]
> In general this looks pretty good to me, but a few thoughts:
> 
> 1. Does the app still check for updates on startup? I think it should
> 2. I think we will need to have design take a look at this before we can land it. cc @danielmarquespt
> 
> * In particular, I am worried about how distracting it could be to have some of those error/update-available states of the UI push the entire rest of the page down - especially with how frequently we release updates (like weekly or every few days) and it being on a timer.
> 
> 3. Can I still check for updates via the system tray (the feature Chris added)? I think we should retain that functionality

https://github.com/sourcegraph/sourcegraph/pull/54812 will implement a startup checker + alert dialog

**Comment by nelsonjr** [comment]
> 2. I think we will need to have design take a look at this before we can land it. cc @danielmarquespt
> 
> * In particular, I am worried about how distracting it could be to have some of those error/update-available states of the UI push the entire rest of the page down - especially with how frequently we release updates (like weekly or every few days) and it being on a timer.

Design Team made a nicer UX that does not have issue anymore

**Comment by slimsag** [comment]
Looks great to me, I'm excited to test these changes out & see how it works myself :) Overall I am happy with the approach here, thanks for being so receptive to my feedback early on in this!

**Pull request merged**
