### PR TITLE
Update pnpm version to 8.*

### PR DESCRIPTION
**Pull request by vovakulikov**
## Test plan
- CI is green

### CODE REVIEW

**Comment by fkling** [comment]
I guess I can read about the changes elsewhere but anything that stands out that is useful to us?

**Comment by vovakulikov** [comment]
@fkling I didn't check this properly, but I was dragged by more smart peer deps dedupe https://github.com/pnpm/pnpm/releases/tag/v8.0.0 option.

**Review by jhchabran — CHANGES_REQUESTED** [review]

**Review by jhchabran — APPROVED** [review]
Should be better now 😊 

Could you rename the PR as well ?

**Comment by vovakulikov** [comment]
@jhchabran Just FYI, I tried 8.1 and 8.0 and it seems like it still fails with the same problem about pnpm version. I don't think this PR has a big priority so feel free to ignore if you don't have time.

**Pull request closed without merging**
