### PR TITLE
App: Change system tray icon

### PR DESCRIPTION
**Pull request by marekweb**
Update to the black-and-white version of the tray icon at the correct size (32x32px)

Rendering on light and dark wallpaper:

Screenshot 2023-05-01 at 4 50 38 PM
Screenshot 2023-05-01 at 4 50 29 PM

Note that the light and dark versions are rendered depending on whether the wallpaper itself is light or dark, not based on the light or dark UI mode.

The light and dark modes are automatically enabled by the "template icons" feature (`iconAsTemplate: true`)

## Test plan

- Launch app and check icons
- Switch between a light and dark wallpaper to trigger change

### CODE REVIEW

**Review by chwarwick — APPROVED** [review]

**Comment by marekweb** [comment]
> @marekweb just curios, is it intentionally that png image isn't asymmetric?

Good observation. It's intentional because the icon is part of a series that has multiple variants with loading indicators. So the extra space is to allow the indicators to fit and not shift their position when switching between them. That being said, we're not currently using the loading variants and I'm not sure how we'll end up using them.

Screenshot 2023-05-03 at 2 50 41 PM

cc @almeidapaulooliveira came up with this approach and did the designs.

**Comment by almeidapaulooliveira** [comment]
> It's intentional because the icon is part of a series that has multiple variants with loading indicators.
@marekweb solved the puzzle 😄.

**Comment by limitedmage** [comment]
Hmm not sure if I'm a fan of the left shift. I think in most cases, the icon will be in the state without a status indicator; we shouldn't sacrifice icon alignment in the primary case so that the logo doesn't shift around in the temporary states.

**Comment by almeidapaulooliveira** [comment]
> Hmm not sure if I'm a fan of the left shift. I think in most cases, the icon will be in the state without a status indicator; we shouldn't sacrifice icon alignment in the primary case so that the logo doesn't shift around in the temporary states.

Another solution it adds equal transparent space on both sides. Having different variations in different positions would make the icon 'dance', which will look unpolished.

**Comment by almeidapaulooliveira** [comment]
Thanks, Marek.

**Pull request merged**
