### PR TITLE
FilteredConnection: Split out generic UI components

### PR DESCRIPTION
**Pull request by umpox**
Splits out the UI elements from `<FilteredConnection />` into their own, exported, components.

This means we can **compose** FilteredConnection using UI elements and the `useConnection` hook.

It also means that we can continue refactoring to use `useConnection` whilst maintaining the same UI and design that we currently have. Although in many places we won't want to continue to use these elements (e.g. areas where we show a custom summary, areas where we `hideSearch` and so on.).

### CODE REVIEW

**Comment by umpox** [comment]
Note: Most of this diff is from a very large snapshot. It's only due to adding component wrappers, I'd recommend `Hide whitespace changes` when viewing that diff!

**Review by eseliger — APPROVED** [review]
Nice 🧹

**Review by courier-new — APPROVED** [review]
Awesome work!! Only suggestion, as the resident JSDoc police 🚨👮‍♀️🚓, I'd love to see every UI component outfitted with a one-sentence summary string and a comment for every prop key.

**Review by valerybugakov — APPROVED** [review]
✅

**Pull request merged**
