### PR TITLE
[DO NOT MERGE] repo-updater: Enable new syncer in development mode

### PR DESCRIPTION
**Pull request by keegancsmith**
We may want to hold off doing this until the UI work is complete.

Part of #2025

### CODE REVIEW

**Comment by tsenart** [comment]
Yep, let's merge this once the UI changes are done.

**Comment by keegancsmith** [comment]
Before we can land this we need to handle the external-service-override.json we use when running `./enterprise/dev/start.sh`. I couldn't work out why, but the new syncer was cloning a shit tonne of repos. It was due to this. I still haven't investigated why it did weird behaviour.

**Comment by keegancsmith** [comment]
Nevermind, it was a bug in the new syncer logic https://github.com/sourcegraph/sourcegraph/pull/3343

**Comment by keegancsmith** [comment]
Gonna just flip the feature flag to on instead :)

**Pull request closed without merging**
