### PR TITLE
Add ExcludeForks to GitHub external service configuration and client.

### PR DESCRIPTION
**Pull request by jmcampanini**
This allows you to exclude forks from being cloned and indexed.

### CODE REVIEW

**Comment by jmcampanini** [comment]
just signed the CLA :)

**Comment by keegancsmith** [comment]
Hi @jmcampanini thanks for the submission. There are a few more steps to get this  over the finish line, I'm not sure if you have the bandwidth to do that. We could also pick this up and finish it soon (always nice motivation when someone makes a change like this :) )

Things needed:
- Try use our existing `exclude` property on the github configuration.
- Think about how this would work if we wanted to exclude by other properties (like archived or other properties github may introduce)
- Update it via the json schema.
- Tests

Looking forward to hearing back from you.

**Comment by jmcampanini** [comment]
I'll work on the Tests + updating the JSON schema.

I'm not sure I understand your first point about using the existing `exclude` property. My understanding of that feature is that it's name based and not GH Repo property based - so unless I knew the name of all of my forks I wouldn't be able to use it. Am I missing something there?

I thought about the other properties and made sure to name the new method `filtered` and not `excludeForks` or something very specific to forks, since it could be used for all sort of filtering for GH when/if the need arises. I stayed away from adding extra features since I don't have those use cases so I wouldn't be the best advocate/designer of them.

I do think additional filters may be helpful, but a fork feels distinct enough from archive/etc. since it's signaling a copy of existing data - which could make searching harder/noiser, while archive felt like something you'd still want to search against. I had this exact dilemma when deciding what repos to exclude in our enterprise deployment. We ended up keeping archived repos.

**Comment by jmcampanini** [comment]
updated the schema and added a test around the `githubService.filtered` function

**Comment by dadlerj** [comment]
@jmcampanini check out #8974, an alternative implementation that adds a `forks` option to the `exclude` list.

**Comment by jmcampanini** [comment]
closing in favor of #8974

**Pull request closed without merging**
