### PR TITLE
remove hierarchical search changes

### PR DESCRIPTION
**Pull request by ijt**

### CODE REVIEW

**Comment by ijt** [comment]
@felixfbecker , this PR was a work in progress that was meant to only revert some changes related to hierarchical search. After talking it over with @nicksnyder , we're going close this PR since he was saying a lot of the changes @keegancsmith made are already in active use by customers.

**Comment by felixfbecker** [comment]
kk - if a PR is WIP, please use a draft PR so code owners don't get review requests per email :)

**Comment by ijt** [comment]
Sure, got it.

**Comment by ijt** [comment]
Does that mean I should make a PR on my own fork of sourcegraph?

**Comment by felixfbecker** [comment]
No, it's a GitHub feature: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by ijt** [comment]
Ah, ok.

**Pull request closed without merging**
