### PR TITLE
sg: Remove go.mod

### PR DESCRIPTION
**Pull request by efritz**
**Proposal**: Remove the go.mod/go.sum file from ./dev/sg so that sg can import things from `internal/` in this repository. I talked with @mrnugget on slack and he didn't have a problem with this as long as install and binary releases still work. I built locally and with the install script (seems fine), but haven't checked binary release workflow yet (not sure how to check yet).

Currently I'm working on rewriting our db migration infrastructure. We will no longer have a dependency on a third-party library, which means we either need to move database connection, migration, and basestore utilities into `lib/`, which seems to encourage direct access to our database from non-sg utilities **(NOT INTENTIONAL)**, or have sg subprocess something inside of `cmd/migrator`, which seems a bit clunky.

Combining the dependencies/import visibility of sg makes sense as it's a _blessed_ app that should be able to do nasty things in development environments we wouldn't want to encourage or perform on live instances. This feels like the most correct solution to me today.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]

**Comment by jhchabran** [comment]
@efritz QA'ing the release scripts, stay tuned :)

**Review by jhchabran — APPROVED** [review]

**Comment by mrnugget** [comment]
> sg makes sense as it's a _blessed_ app

**Comment by efritz** [comment]
@mrnugget Isn't it? It's literally _how_ we should do a bunch (maybe all in the future?) changes to a dev environment. Let it have access to internal knowledge.

**Comment by mrnugget** [comment]
Of course, I just wanted to highlight what I'll put on my CV as a testimonial/my next tattoo/the screenshot I'm going to frame and put in our living room.

**Comment by efritz** [comment]
_our_ living room 😻

**Pull request merged**
