### PR TITLE
dev: support switching our default branch to main

### PR DESCRIPTION
**Pull request by keegancsmith**
This mostly updates our dev CI/helpers which hardcoded master to instead
hardcode main. In the case of CI we treat both main and master as the
default branch.

Part of https://github.com/sourcegraph/sourcegraph/issues/11464

### CODE REVIEW

**Comment by tsenart** [comment]
I wasn't familiar with the "main" branch. Links to documentation?

**Comment by tsenart** [comment]
Oh, I see the issue that this refers to. I am not 100% sure I agree with this change. There are [multiple meanings to the word master](https://www.merriam-webster.com/dictionary/master), and I'm pretty sure that the one that the git master branch alludes to is more:


> 5a: a master mechanism (see MECHANISM sense 1) or device
> b: an original from which copies can be made
> especially : a master recording (such as a magnetic tape)

Than anything with racist historical meaning.

**Comment by nicksnyder** [comment]
@tsenart Did you read the thread in Keegan's comment on the issue? https://twitter.com/mislav/status/1270388510684598272

**Comment by tsenart** [comment]
@nicksnyder: I hadn't. I read it now. Makes sense, so approving.

**Comment by keegancsmith** [comment]
I'm out this week, so someone may want to takeover this.

**Comment by keegancsmith** [comment]
Plan for tomorrow morning:

1. Merge this.
2. Push latest master to main.
3. Update GitHub settings to make main the default.
4. Mark main branch as protected.
5. Run this [script](https://github.com/liyanchang/default-branch-migration/blob/main/entrypoint.sh) to update open PRs to point to main.
6. Announce in #dev-announce: **Action Required**: Our default branch has been renamed from `master` to `main`. Please update your local clones by running `git fetch && git checkout origin/main && ./dev/2020-08-update-default-branch-to-main.sh`. Report any issues you find in #dev-chat.
7. I'll look for things that may have broke.
8. In a day or two I'll look for any accidental commits to master and rebase and push to main.

There is no step 9. delete master. I think I'll leave it there since it doesn't hurt to keep around for old links.

**Comment by nicksnyder** [comment]
Is it possible to use branch protection rules to prevent anyone from pushing to `master` in the future (just to avoid accidents)?

**Comment by keegancsmith** [comment]
Yes, I'll update the plan above to limit pushes to master to just me :) Any other admin can add themselves to that list if needs be.

**Comment by keegancsmith** [comment]
I ended up working late last night so got a late start today. I'm gonna do this tomorrow morning eu-timezones rather.

**Comment by keegancsmith** [comment]
FYI this was the script I ran to update all our open PRs to merge into main. It was modified from the action to run locally + use netrc for auth.

```shell
#!/bin/sh -l

PREVIOUS_DEFAULT="master"
NEW_DEFAULT="main"
GITHUB_API_URL="https://api.github.com"
GITHUB_REPOSITORY="sourcegraph/sourcegraph"

echo "Migrating from '$PREVIOUS_DEFAULT' to '$NEW_DEFAULT'"
echo "Repo Name: $GITHUB_REPOSITORY"

# Check the API to see what the current default branch is
CURRENT_DEFAULT=$(curl -n --silent $GITHUB_API_URL/repos/$GITHUB_REPOSITORY | jq -r .default_branch)
echo "Default branch: $CURRENT_DEFAULT"

if [ "$CURRENT_DEFAULT" = "$NEW_DEFAULT" ]; then
	echo "Default has changed to $NEW_DEFAULT"
	# Check all existing PRs to see if we should change their base
	PRS=$(curl -n --silent "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls?base=$PREVIOUS_DEFAULT&state=open")

	# TODO: PATCH /repos/:owner/:repo/pulls/:pull_number
	for row in $(echo $PRS | jq -r 'map(select(.locked == false)) | .[].url'); do
		echo "Attempting to update $row"
		curl -n --silent --show-error -w "Status Code: %{http_code}\n" --request PATCH --data '{"base": "'$NEW_DEFAULT'"}' "$row"
	done

	exit
fi;
```

**Pull request merged**
