### PR TITLE
Troubleshooting incorrect logins for non-site admin users

### PR DESCRIPTION
**Pull request by airamare01**
This PR aims to provide a troubleshooting solution for non-site admin users who get authenticated into the site admin's account

### CODE REVIEW

**Comment by ryanslade** [comment]
cc @flying-robot as you're looking into this.

**Comment by davejrt** [comment]
I'm not entirely sure we should publish this, as a how-to to work around what is essentially a security risk. I'd much prefer it be addressed on a case by case basis until we have a solution...which should be a high priority

**Comment by airamare01** [comment]
Thanks for the feedback on this @davejrt.

**Comment by unknwon** [comment]
I am also not comfortable treating this as a "troubleshooting guide" at least. To me, it feels more like a playbook for how to revoke site admin using the DB (vs. doing it via web UI)

**Comment by ryanslade** [comment]
Agreed, let's close this. Do we have a ticket to track the investigation / fix?

**Comment by airamare01** [comment]
Currently nothing on GitHub, most of the debugging was done on Slack

**Pull request closed without merging**
