### PR TITLE
Update session tracker to prefer GTM managed cookies

### PR DESCRIPTION
**Pull request by dadlerj**
Addresses this issue https://sourcegraph.slack.com/archives/C0678ATBXCG/p1702597178459279?thread_ts=1702596966.233179&cid=C0678ATBXCG

Do not merge until updates have been made to GTM.

## Test plan

Functionality to be tested using existing e2e tests that are output in the #alerts-data-marketing channel.

### CODE REVIEW

**Comment by dadlerj** [comment]
Not sure who to tag for a review, so I went with GitHub's recommendation, sorry @bobheadxi !

**Review by bobheadxi — APPROVED** [review]
I think someone else on the data analytics team will have more context, but I did refactor this recently, and fewer of these cookie things sounds like a good thing to me :) Thanks for the docstrings as well

**Comment by dadlerj** [comment]
Good point, added Addy as well

**Review by akalia25 — APPROVED** [review]
LGTM! Thank you for this change!

**Pull request merged**
