### PR TITLE
bazel: fix `patch_args`

### PR DESCRIPTION
**Pull request by mrnugget**
Does this fix the build? https://buildkite.com/sourcegraph/sourcegraph/builds/239640#018a1cdb-c03c-4ed1-a99c-5c1bcb8d59e1

## Test plan

- Started `main-dry-run` build: https://buildkite.com/sourcegraph/sourcegraph/builds/239679

### CODE REVIEW

**Review by BolajiOlajide — APPROVED** [review]
Hopefully, it does - it's blocking one of my PRs.

However, I wonder why the change.

**Comment by mrnugget** [comment]
Seems like it fixes it. I'll merge.

**Comment by jhchabran** [comment]
@mrnugget thanks, I don't understand how this went through, the original PR should have caught it.

**Comment by jhchabran** [comment]
Better late than never, this was caused by https://buildkite.com/sourcegraph/sourcegraph/builds/239596#018a1c0d-01a6-4e77-81f6-512ddf9f7444/38-39 

Which is a bug that got fixed in 133113b208637e790dedf3f4cc3dabb6a2563377 but the base branch from the PR that introduced was older than this commit, so it slipped in.

**Pull request merged**
