### PR TITLE
grpc: gitserver: exec: change EnsureRevision field to be bytes instead of string

### PR DESCRIPTION
**Pull request by ggilmore**
On sourcegraph.com, we're seeing gRPC errors like the following pop up.

```jsonc
// https://console.cloud.google.com/logs/query;cursorTimestamp=2023-09-06T14:26:13.613057343Z;duration=P7D;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.location%3D%22us-central1-f%22%0Aresource.labels.cluster_name%3D%22cloud%22%0Aresource.labels.namespace_name%3D%22prod%22%0AjsonPayload.InstrumentationScope%3D~%22gRPC.internal.error.reporter%22%0Atimestamp%3D%222023-09-06T14:26:13.613057343Z%22%0AinsertId%3D%22iwhctcc7bu8zuxig%22?project=sourcegraph-dev
{
  "jsonPayload": {
    "Attributes": {
      "grpcService": "gitserver.v1.GitserverService",
      "nonUTF8StringFields": [
        "ensure_revision"
      ],
      "grpcCode": "Internal",
      "messageJSON": "{\"repo\":\"github.com/apache/superset\",\"ensure_revision\":\"f2523b26fa140febe838624ae8508136d01d1389/\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd/\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd/etc/passwd^0\",\"args\":[\"cmV2LXBhcnNl\",\"ZjI1MjNiMjZmYTE0MGZlYmU4Mzg2MjRhZTg1MDgxMzZkMDFkMTM4OS/CLsIuL8Iuwi4vwi7CLi/CLsIuL8Iuwi4vwi7CL8Iuwi4vwi7CLi/CLsIuL8Iuwi4vwi7CLi/CLsIvZXRjL3Bhc3N3ZF4w\"]}",
      "grpcMethod": "Exec",
      "initialRequestJSON": "{\"repo\":\"github.com/apache/superset\",\"ensure_revision\":\"f2523b26fa140febe838624ae8508136d01d1389/\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd/\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd/etc/passwd^0\",\"args\":[\"cmV2LXBhcnNl\",\"ZjI1MjNiMjZmYTE0MGZlYmU4Mzg2MjRhZTg1MDgxMzZkMDFkMTM4OS/CLsIuL8Iuwi4vwi7CLi/CLsIuL8Iuwi4vwi7CL8Iuwi4vwi7CLi/CLsIuL8Iuwi4vwi7CLi/CLsIvZXRjL3Bhc3N3ZF4w\"]}"
    },
    "InstrumentationScope": "gitserver.client.gRPC.internal.error.reporter.streamingMethod.postMessageSend",
    "SeverityText": "ERROR",
  
    "Function": "github.com/sourcegraph/sourcegraph/internal/grpc/internalerrs.doLog",
    "Body": "grpc: error while marshaling: string field contains invalid UTF-8"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "container_name": "frontend",
    }
  },
}
```

The EnsureRevision field in gitserver.Exec requests ensures that the specified branch / commit is fetched in the repository before running the command.

In protobuf, all [strings must be utf-8 encoded](https://protobuf.dev/programming-guides/proto3/#scalar). However, it's valid to have non-utf8 branch names in a git repository ([nothing in the specification explicitly forbids this](https://git-scm.com/docs/git-check-ref-format)). 

So, this issue is fixed by relaxing the protobuf type to accept an arbirary byte slice. Our application code then casts this to a string. I have also added comments to warn users that the revision might not be utf-8 encoded.

I do think there is an argument to be made that we need centralized logic for handling branch / commit specifiers (e.g. should we enforce that all names must be utf-8 encoded, have centralized logic for sanitizing non-uft8 names into utf-8 ones, create a new type for branch names were we can encapsulate logic for operating against a branch name (ranging over a branch name, etc.) - but this seems outside the scope of this PR. 

## Test plan

CI

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
It seems like improper use to me to have a revision that's not utf-8, but maybe I'm wrong here. Anyhow, this seems to fix an issue so lgtm.

**Comment by ggilmore** [comment]
> It seems like improper use to me to have a revision that's not utf-8, but maybe I'm wrong here. Anyhow, this seems to fix an issue so lgtm.

https://github.com/sourcegraph/sourcegraph/issues/56518

**Comment by keegancsmith** [comment]
This is a bug on the client side surely? This type is a string. Look at the example payload, it is a revision hash (which is what it has to be), but for some reason is including other data.

**Comment by mrnugget** [comment]
Considering that it ends in `/etc/passwd` I'd say this is not a bug but an attempt:

`"ensure_revision\":\"f2523b26fa140febe838624ae8508136d01d1389/\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd/\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd./\\ufffd.\\ufffd/etc/passwd^0\"`

I don't think that's a valid usecase for which we should loosen our constraints :)

**Comment by keegancsmith** [comment]
Yeah, I think this PR should be reverted. The alternative fix if you don't like your grpc metrics being affected is to add some extra client side validation on the ensure revision field. This certainly used to exist client side back in the days before everyone was using an arm64 laptop.

**Comment by ggilmore** [comment]
@keegancsmith @mrnugget @eseliger 

So a couple of things:

1) It's possible to create a branch in git that has non-utf8 characters in it. Take a look at the branches on https://github.com/ggilmore/csi/. This has strange behavior in github, but you can push and pull from it. (Note that you can't do this on a mac as its character set for its file system doesn't allow this - I had to use a linux machine with ext4. 

Screenshot 2023-09-12 at 2 11 37 PM

2) This isn't just a metrics issue. This is a behavior that was allowed in REST (because we didn't enforce any string encoding) that breaks in GRPC if the `EnsureRevision` type is a `string` (since it enforces utf-8 encoding). 

3) Because of the above two, I think this PR is valid - since I don't want to regress on old behavior with just the gRPC migration. However, I do think that it's worth having an explicit validation layer in our app (gitsever?) that either santizes user-input like git branch and commit names or rejects / ignore unexepected input (like non-uft8 names). However, I think this should be an explicit descion that we make with careful design (since we want to protect our entire app from this kind of input, and its a change in behavior).  This is why I opened https://github.com/sourcegraph/sourcegraph/issues/56518 for explicit tracking for this.

**Comment by keegancsmith** [comment]
Ensure revision should only get commit shas.

**Comment by mrnugget** [comment]
> 3\. Because of the above two, I think this PR is valid - since I don't want to regress on old behavior with just the gRPC migration.

As discussed yesterday: this convinced me. We never enforced "should only be a SHA" before, so doing it while switching to gRPC seems like the wrong move. It should be a separate change (which we should make!).

**Pull request merged**
