### PR TITLE
iam: Isolate oobmigrations

### LINKED ISSUE #39508: RFC 697: Isolate out-of-band migrations (iam)
See [RFC 697: Multiple version upgrades](https://docs.google.com/document/d/1eNiwzWZmfpvzFhs9IDcM7Sbchv_Hm8Uj-6bI-3TDlvg).

Update out of band migrations [#15](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b4bb2d2586e7c87fb1e2ba08c5c2ab4d610632ad/-/blob/enterprise/internal/productsubscription/migrations.go?L57) and [#16](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b4bb2d2586e7c87fb1e2ba08c5c2ab4d610632ad/-/blob/enterprise/internal/productsubscription/migrations.go?L98) so that they do not require code outside of a specific allow-list (which excludes things that transitively include `internal/conf`).

### PR DESCRIPTION
**Pull request by efritz**
This PR *isolates* oobmigrations [#15](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b4bb2d2586e7c87fb1e2ba08c5c2ab4d610632ad/-/blob/enterprise/internal/productsubscription/migrations.go?L57) and [#16](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b4bb2d2586e7c87fb1e2ba08c5c2ab4d610632ad/-/blob/enterprise/internal/productsubscription/migrations.go?L98) so that it does not need any _behavioral_ imports that can change over time. This is in preparation for its deprecation, where it will run only as part of the migrator for historic upgrades. We want to *freeze* this migration as much as possible, because we want to treat it with consistent behavior over time to allow the migrator to make some assumptions (like the registered code for an oobmigration is valid at any point in its lifetime).

This PR fixes #39508.

Feel free to review by-commit which should make the refactoring a bit more clear.

## Test plan

Existing unit tests.

### CODE REVIEW

**Comment by efritz** [comment]
@sourcegraph/iam Would you like to deprecate these oobmigrations? I believe it would allow you to make `license_version `, `license_tags`, `license_user_count`, and `license_expires_at` on the `product_licenses` table non-nullable, as well as `account_number` on the `product_subscriptions` table.

**Comment by efritz** [comment]
Follow-up PRs will include isolation of the tests.

**Review by unknwon — APPROVED** [review]
Thanks!

> Would you like to deprecate these oobmigrations after the 3.43 release?

Yes!

Side: I'm still working with Sales teams for some column they want to be derived (similar to `license_user_count`), so there will probably be more similar OOB migrations and I might only make these columns non-NULL much later on.

**Comment by efritz** [comment]
> Side: I'm still working with Sales teams for some columns they want to be derived (similar to license_user_count), so there will probably be more similar OOB migrations and I might only make these columns non-NULL much later on.

@unknwon No problem! Make as many as you want, and post-deprecation the constraints are up to you (no rush on making them non-nullable). These two migrations were the easiest to isolate so far (I've also done batches and repo-management ones so far, but still have codeintel and insights). I'm only asking to see which ones we can deprecate now to help exercise upgrade paths to 4.0.

**Comment by efritz** [comment]
@unknwon I've deprecated the oobmigrations in #40758. Feel free to add new ones anytime. For the ones that were deprecated, code on or after the 4.0 can assume 100% completion. Feel free to update the database schema/code to reflect that.

**Pull request merged**
