### PR TITLE
Cody: Fix button border display issue & update webview UI toolkit

### PR DESCRIPTION
**Pull request by abeatrix**
Close https://github.com/sourcegraph/sourcegraph/issues/51719
Unblock https://github.com/sourcegraph/sourcegraph/pull/51246

Thanks @eseliger and @philipp-spiess for the help with [upgrading the packages](https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1683728783413159) 🙇 

## Issues

There was an issue with VS Code Webview buttons displaying a light border due to max-width set to 300 in the upstream package, which was then fixed in https://github.com/microsoft/vscode-webview-ui-toolkit/issues/384

image

Text is squeezed to the side due to max width issue:
image

## Fixs

After updating the package, there is still a border for the height, but the width constrain has been removed which solve the issue where the text is squeezed to the side:
image

Overriding the border color manually worked:

image

## Test plan

Package updated and working fine locally. See screenshots above

### CODE REVIEW

**Comment by sourcegraph-buildkite** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.03 kb) | -0.00% (-0.06 kb) | -0.00% (-0.09 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/bee/cody-webviewkit/compare-report.html;tab=live_object) for a full comparison between the commits 16190ed and 7cf2a50 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by philipp-spiess** [comment]
The focus border is new 👀 

Screenshot 2023-05-10 at 17 37 09

**Review by philipp-spiess — APPROVED** [review]
Looks like an easy fix, nice!

**Comment by abeatrix** [comment]
> Looks like an easy fix, nice!

Hardest part was to reload VS Code 🤣  Going to remove the focus border, thanks again for catching that <3

**Pull request merged**
