### PR TITLE
syntax-highlighter: bump to 1.68.0 for sparse checkout

### PR DESCRIPTION
**Pull request by Strum355**
_Massively_ improves the time to run `cargo fetch` in CI. And everyone loves saving time : )

## Test plan

Everthing compiles, tests pass, and runtime issues were fixed in the other PR :laff:

### CODE REVIEW

**Comment by tjdevries** [comment]
we need to change the asdf stuff too maybe?

**Comment by Strum355** [comment]
> we need to change the asdf stuff too maybe?

Probably actually yea

**Comment by tjdevries** [comment]
k, i rebased off of main so we could test the changes from the build stuff.

**Comment by varungandhi-src** [comment]
Closing this since turning this on in `.cargo/config.toml` (in https://github.com/sourcegraph/sourcegraph/pull/49149) should also enable it here.

**Pull request closed without merging**
