### PR TITLE
docs: replace \| with | inside a backtick code block in a table

### LINKED ISSUE #3869: docs: search query shows up as `(open\|close)file`
https://docs.sourcegraph.com/user/search/queries

Screen Shot 2019-05-06 at 5 42 14 PM

The root cause appears to be https://github.com/russross/blackfriday/issues/207, an issue that has been there since 2015. One possibility might be to use https://gitlab.com/golang-commonmark/markdown instead within docsite.

### PR DESCRIPTION
**Pull request by ijt**
Fixes #3869 

This change depends on https://github.com/sourcegraph/docsite/pull/18 being deployed.

Test plan: Check https://docs.sourcegraph.com/@doc-fix/user/search/queries and see if the first row of the table looks reasonable.

Before:
Screen Shot 2019-05-08 at 3 43 58 PM

After:
Screen Shot 2019-05-08 at 1 59 46 PM

### CODE REVIEW

**Comment by ijt** [comment]
@sqs, PTAL

**Comment by ijt** [comment]
CC @ryan-blunden

**Comment by felixfbecker** [comment]
I am pretty sure that GitHub requires escaping pipes with a backslash in tables. If this removes all the backslashes, that would mean we can't review PRs to docs in rendered format on GitHub anymore, which would be unfortunate. Why don't we modify our markdown renderer instead to handle `\|` correctly?

**Comment by ijt** [comment]
Good point, @felixfbecker. I fixed docsite to handle `\|` within backticks in tables and the fix is live now.

**Pull request closed without merging**
