### PR TITLE
Fix typos across sourcegraph repo

### PR DESCRIPTION
**Pull request by yohix**
:writing_hand: **Fix typos across sourcegraph repo**

**Files that have typos**

```
sourcegraph/browser/README.md:109:43: "begining" is a misspelling of "beginning"
sourcegraph/browser/src/browser/README.md:3:340: "psuedo" is a misspelling of "pseudo"
sourcegraph/browser/src/extension/scripts/background.ts:231:100: "transfering" is a misspelling of "transferring"
sourcegraph/browser/src/platform/extensionHost.ts:96:3: "transfering" is a misspelling of "transferring"
sourcegraph/browser/src/shared/components/OpenDiffOnSourcegraph.tsx:38:91: "occuring" is a misspelling of "occurring"
sourcegraph/browser/src/shared/components/OpenDiffOnSourcegraph.tsx:99:25: "specfic" is a misspelling of "specific"
sourcegraph/cmd/frontend/graphqlbackend/repository_git_refs.go:44:8: "seperate" is a misspelling of "separate"
sourcegraph/cmd/frontend/graphqlbackend/search_results.go:860:46: "explicitely" is a misspelling of "explicitly"
sourcegraph/cmd/frontend/graphqlbackend/search_suggestions.go:344:9: "explicitely" is a misspelling of "explicitly"
sourcegraph/cmd/frontend/internal/session/session.go:265:23: "reponse" is a misspelling of "response"
sourcegraph/cmd/gitserver/main.go:60:62: "accidently" is a misspelling of "accidentally"
sourcegraph/cmd/gitserver/server/list-gitolite_test.go:60:25: "repsonse" is a misspelling of "response"
sourcegraph/cmd/gitserver/server/lock.go:17:26: "maintance" is a misspelling of "maintenance"
sourcegraph/cmd/gitserver/server/patch.go:199:26: "commiting" is a misspelling of "committing"
sourcegraph/cmd/gitserver/server/repo_info_test.go:110:8: "mutliple" is a misspelling of "multiple"
sourcegraph/cmd/gitserver/server/serverutil.go:565:15: "gaurenteed" is a misspelling of "guaranteed"
sourcegraph/cmd/repo-updater/repos/bitbucketserver.go:352:13: "seperately" is a misspelling of "separately"
sourcegraph/cmd/repo-updater/repos/gitolite.go:119:49: "satisfiy" is a misspelling of "satisfy"
sourcegraph/cmd/repo-updater/repos/purge.go:30:46: "accidently" is a misspelling of "accidentally"
sourcegraph/cmd/repo-updater/repos/scheduler_test.go:1343:51: "futher" is a misspelling of "further"
sourcegraph/cmd/repo-updater/repos/store.go:127:40: "commited" is a misspelling of "committed"
sourcegraph/cmd/repo-updater/repos/testing.go:340:49: "existant" is a misspelling of "existent"
sourcegraph/cmd/server/shared/shared.go:178:47: "dieing" is a misspelling of "dying"
sourcegraph/cmd/server/shared/shared.go:180:5: "dieing" is a misspelling of "dying"
sourcegraph/dev/ci/go-build.sh:5:2: "Seperate" is a misspelling of "Separate"
sourcegraph/dev/ci/go-test.sh:13:2: "Seperate" is a misspelling of "Separate"
sourcegraph/doc/admin/migration/3_7.md:95:21: "compatability" is a misspelling of "compatibility"
sourcegraph/doc/api/graphql/search.md:49:345: "recieved" is a misspelling of "received"
sourcegraph/doc/dev/architecture/life-of-a-search-query.md:19:757: "becuase" is a misspelling of "because"
sourcegraph/doc/dev/architecture/life-of-a-search-query.md:31:173: "respositories" is a misspelling of "repositories"
sourcegraph/doc/dev/tech_stack.md:28:279: "maintance" is a misspelling of "maintenance"
sourcegraph/doc/integration/bitbucket_server.md:62:43: "noticable" is a misspelling of "noticeable"
sourcegraph/doc/user/campaigns.md:322:9: "defintion" is a misspelling of "definition"
sourcegraph/enterprise/cmd/frontend/auth/oauth/cookie.go:18:31: "compatability" is a misspelling of "compatibility"
sourcegraph/enterprise/cmd/frontend/internal/authz/bitbucketserver/store_test.go:187:31: "immediatelly" is a misspelling of "immediately"
sourcegraph/enterprise/cmd/frontend/internal/licensing/features.go:26:71: "explictly" is a misspelling of "explicitly"
sourcegraph/enterprise/cmd/frontend/internal/licensing/features.go:50:41: "explictly" is a misspelling of "explicitly"
sourcegraph/enterprise/internal/campaigns/store.go:178:40: "commited" is a misspelling of "committed"
sourcegraph/internal/campaigns/types.go:259:65: "succesfully" is a misspelling of "successfully"
sourcegraph/internal/conf/server.go:133:9: "initalizes" is a misspelling of "initializes"
sourcegraph/internal/endpoint/endpoint.go:40:54: "seperated" is a misspelling of "separated"
sourcegraph/internal/ratelimit/rate_limit_test.go:68:15: "remaing" is a misspelling of "remaining"
sourcegraph/migrations/1528395630_repo_external_always.up.sql:15:49: "accidently" is a misspelling of "accidentally"
sourcegraph/packages/sourcegraph-extension-api/src/sourcegraph.d.ts:1213:17: "transfomers" is a misspelling of "transforms"
sourcegraph/packages/sourcegraph-extension-api/src/sourcegraph.d.ts:1245:40: "wih" is a misspelling of "with"
sourcegraph/shared/src/components/completion/CompletionWidget.tsx:18:60: "explictly" is a misspelling of "explicitly"
sourcegraph/shared/src/notifications/NotificationItem.tsx:46:77: "occured" is a misspelling of "occurred"
sourcegraph/shared/src/util/types.ts:4:38: "explicitely" is a misspelling of "explicitly"
sourcegraph/web/src/api/APIConsole.tsx:205:7: "Foward" is a misspelling of "Forward"
sourcegraph/web/src/api/graphiql-theme.scss:8:42: "unfortunetly" is a misspelling of "unfortunately"
sourcegraph/web/src/components/SearchResultMatch.tsx:92:72: "maintaing" is a misspelling of "maintaining"
sourcegraph/web/src/search/results/SearchResultsInfoBar.tsx:55:71: "thier" is a misspelling of "their"
sourcegraph/web/src/search/results/SearchResultsList.tsx:89:8: "Refrence" is a misspelling of "Reference"
sourcegraph/web/src/tree/Tree.tsx:69:48: "avialable" is a misspelling of "available"
```

**PS:** I use [**client9/misspell**](https://github.com/client9/misspell) to scan typos :heart:

### CODE REVIEW

**Comment by keegancsmith** [comment]
@yohix thanks for this change. You just needed to run `go generate ./migrations`. I pushed a commit to another branch. Could you merge it in to yours / cherry-pick it? https://github.com/sourcegraph/sourcegraph/commit/90a37a70ce67f9e8ee8c42cf0f6e5d3ee43a9299

**Comment by felixfbecker** [comment]
@keegancsmith FYI GitHub allows you to do that yourself :) I went ahead and pushed it :)

**Comment by yohix** [comment]
Thanks, @felixfbecker :heart:

**Comment by keegancsmith** [comment]
Thanks @yohix

**Pull request merged**
