### PR TITLE
web: use CopyableText in WebhookInformation.

### PR DESCRIPTION
**Pull request by sashaostrikov**
Test plan:
Storybook.

Closes https://github.com/sourcegraph/sourcegraph/issues/45150

## App preview:

- [Web](https://sg-web-ao-ui-webhooks-use-copyabletext.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.17 kb) | -0.00% (-0.17 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ao/ui/webhooks/use-copyableText/compare-report.html;tab=live_object) for a full comparison between the commits 18a3f6d and 623cd1d or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by cbart** [comment]
When reviewing this, I tried to access the UI at app-preview. Here's what I found:

1. In trying to see this used I was searching for [SiteAdminWebhookPage](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9c041c8193d87442a828a0f1c0596e563a1d24cc/-/blob/client/web/src/site-admin/routes.tsx?L102-111) which hopefully would be linked from SiteAdminWebhook**s**Page. I have not found a way to get there through the UI. What am I missing?
1. When I just hit the URL https://sg-web-ao-ui-webhooks-use-copyabletext.onrender.com/site-admin/webhooks I found there were no webhooks and clicking a _+ Add Webhook_ button does nothing.

**Comment by sashaostrikov** [comment]
> When reviewing this, I tried to access the UI at app-preview. Here's what I found:
> 
> 1. In trying to see this used I was searching for [SiteAdminWebhookPage](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9c041c8193d87442a828a0f1c0596e563a1d24cc/-/blob/client/web/src/site-admin/routes.tsx?L102-111) (singular) which hopefully would be linked from SiteAdminWebhook**s**Page (plural). I have not found a way to get there through the UI. What am I missing?
> 2. When I just hit the URL https://sg-web-ao-ui-webhooks-use-copyabletext.onrender.com/site-admin/webhooks I found there were no webhooks and clicking a _+ Add Webhook_ button does nothing.

Well, you need at least one webhook to go to `SiteAdminWebhookPage` and creating webhooks via UI is only implemented in the [neighbour PR](https://github.com/sourcegraph/sourcegraph/pull/45159) :)

So I can only see the change by running storybook or sg locally for now.

**Review by mollylogue — APPROVED** [review]
👍

**Pull request merged**
