### PR TITLE
search: Whitelisted repohascommitafter to get repo type

### PR DESCRIPTION
**Pull request by Akarshit**
Closes: #6759
The parameter was missing from the whitelist so I just added it back. To test use the following 3 queries:
1. `source repo:^github.com/sourcegraph/  type:repo`
2. `source repo:^github.com/sourcegraph/  type:repo repohascommitafter:"1 day ago"`
3. `source repo:^github.com/sourcegraph/  type:repo repohascommitafter:"0 day ago"`

### CODE REVIEW

**Comment by unknwon** [comment]
Looks like the CI failed because this file isn't gofmt'ed, please do that :)

**Comment by keegancsmith** [comment]
@Akarshit ^^

**Comment by Akarshit** [comment]
@unknwon I have updated the file now. Should be good.

**Comment by unknwon** [comment]
I don't know why webhook failed to trigger the build, but I manually started one.

**Comment by keegancsmith** [comment]
@Akarshit thanks so much and this looks good to merge. Before we can merge your code though you need to sign our CLA: https://docs.google.com/forms/d/e/1FAIpQLSeoH8uJii-17uHUMlbsM2LKwfOh2kXRYNcQlURIZ8qeDiDl8w/viewform?usp=send_form

**Comment by unknwon** [comment]
All look good, thank you! Merging.

**Pull request merged**
