### PR TITLE
all: rename types.RepoName to types.MinimalRepo

### PR DESCRIPTION
**Pull request by tsenart**
This is big search and replace to rename our types.RepoName to
types.MinimalRepo, now that it contains a few different fields.

### CODE REVIEW

**Review by mrnugget — APPROVED** [review]
TIL that `types.RepoName` was a struct.

**Review by unknwon — APPROVED** [review]
I trust Go compiler for this.

**Comment by tsenart** [comment]
> TIL that types.RepoName was a struct.

@mrnugget: Yes, but we also have api.RepoName which is a string.

**Comment by mrnugget** [comment]
Yep, just trying to say: this PR makes a lot of sense :)

**Pull request merged**
