### PR TITLE
updatecheck: include aggregated repository statistics in pings

### PR DESCRIPTION
**Pull request by keegancsmith**
We want to start including the number of lines of code indexed by
Sourcegraph as well as the total size of all git repositories stored on
Sourcegraph.

This commit was created by copying the structure of the saved searches
pings commit.

Depends on https://github.com/sourcegraph/sourcegraph/pull/13763

Fixes https://github.com/sourcegraph/sourcegraph/issues/13713

### CODE REVIEW

**Review by dadlerj — APPROVED** [review]

**Review by unknwon — APPROVED** [review]
Thanks! LGTM.

@ebrodymoore Do we need to update schema in this case? (reading through https://about.sourcegraph.com/handbook/engineering/adding_ping_data#adding-data-to-pings)

**Comment by keegancsmith** [comment]
> Do we need to update schema in this case? (reading through https://about.sourcegraph.com/handbook/engineering/adding_ping_data#adding-data-to-pings)

Thanks for that link. I haven't read that yet either! So we probably do
need to update the schema. I'll follow-up with this on Monday.

**Comment by keegancsmith** [comment]
Analytics PR is at https://github.com/sourcegraph/analytics/pull/49

**Review by ebrodymoore — APPROVED** [review]
Looks good! You can merge this whenever you'd like, I've updated the db schemas

**Pull request merged**
