### PR TITLE
Buildifier fixes

### PR DESCRIPTION
**Pull request by gregmagolan**
This resolves the buildifier failures we hit when running buildifier on Aspect Workflows for the demo.

Test plan: CI

## App preview:

- [Web](https://sg-web-aspect-buildifier-fixes.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by jbedard — APPROVED** [review]

**Comment by jhchabran** [comment]
This is breaking something in our tests, (the `cmd/symbols/squirrel` part, I'll take a look and report back.

**Review by jhchabran — CHANGES_REQUESTED** [review]
breaking go tests in cmd/symbols/squirrel

**Comment by jhchabran** [comment]
@gregmagolan can we make buildifier ignore those file entirely? These are not to be built, they are just tests we're running against Starlark so we can resolve symbols in the Sourcegraph app itself.

**Comment by gregmagolan** [comment]
> 

I took those changes out from this PR. When buildifier gets added in the future I believe you can just configure `exclude_patterns` on the targets like so,


```
buildifier(
    name = "buildifier",
    exclude_patterns = ["cmd/symbols/squirrel/"],
)
```

from: https://github.com/bazelbuild/buildtools/issues/801#issuecomment-926134912

**Review by jhchabran — APPROVED** [review]

**Pull request merged**
