### PR TITLE
Set default references page size

### PR DESCRIPTION
**Pull request by efritz**
Ensure there is a default limit for reference requests. Without this, we try to fetch a zero-size page and will return a cursor that will request another zero-size page indefinitely.

### CODE REVIEW

**Comment by efritz** [comment]
I think it's appropriate to fix on the edge of the service. What would you expect to happen if you request -1 or 0 results from an API?

**Comment by gbrik** [comment]
whoops, annoying you can't do threads in top level comments. I'd expect a cursor API to error on a request for -1 or 0 elements, sacrifices a small amount of convenience but ensures mixups like this don't happen. nbd either way

**Comment by efritz** [comment]
The top level **is** the thead.

I'll add an error at the API evel as well, but that shoudn't be hit given proper input validation.

**Comment by gbrik** [comment]
does Go do asserts that are elided in production builds?

**Comment by efritz** [comment]
Not that I know of. Isn't not an expensive check to do at runtime.

**Comment by efritz** [comment]
Since we plan to merge the API directly to the GraphQL resolvers eventually the check should exist here anyway.

**Pull request merged**
