### PR TITLE
feat(vscode): Prompt to get an access token when authentication fails

### PR DESCRIPTION
**Pull request by steverice**
If connecting to the sourcegraph instance returns a 401, give the user two actions to take. The first will take the user to sourcegraph to create a new token, using the token callback flow added in #35826 if available. The second will open the workbench settings to allow the user to paste in a token.

This is particularly useful when distributing a `sourcegraph.url` setting as part of the workspace/repository to point to a private instance. Since the URL is already set, the user does not get the first-time setup view when activating the sourcegraph extension. Instead, they will get this error dialog:

Access Token Error

## Test plan

- [x] Ran existing unit tests with `yarn test`
- [x] Ran existing integration tests with `yarn test-integration`
- [x] Walked through the flow of installing the vscode extension in a fresh instance with no settings, with a URL and token already set, with only a URL set, against both sourcegraph.com and a private instance

### CODE REVIEW

**Review by markjm — APPROVED** [review]

**Comment by steverice** [comment]
@sourcegraph/contribution-reviewers I have signed the CLA.

**Comment by jdorfman** [comment]
@cla-bot check

**Comment by jdorfman** [comment]
> @sourcegraph/contribution-reviewers I have signed the CLA.

@steverice confirmed. cla-bot isn't working, looking into why!

cc @bobheadxi

**Comment by bobheadxi** [comment]
@cla-bot check

**Review by slimsag — APPROVED** [review]
LGTM, this looks great, thanks so much for sending this change!

**Review by jdorfman — APPROVED** [review]

**Comment by jdorfman** [comment]
Don't merge yet, `sg lint -fix docs` made a lot of changes that need to be verified.

**Comment by steverice** [comment]
Thanks @markjm @jdorfman @slimsag ! Let me know if there is anything I can do to help.

**Comment by slimsag** [comment]
All good - I'm working on getting this merged today (something funky is up with our CI) :)

**Comment by jdorfman** [comment]
@slimsag seems to still fail after #40836 was merged

**Comment by slimsag** [comment]
Thanks a ton for this - should roll out soon, sorry for the delay in getting our CI stuff sorted out! :)

**Comment by jdorfman** [comment]
Thanks @steverice you rock!

**Pull request merged**
