### PR TITLE
multiline search query field (textarea not input)

### PR DESCRIPTION
**Pull request by sqs**
This makes the global and per-repo search query field support multiple lines (in the UI only; this is not a backend change). When the query is too long to fit on one line, the input automatically expands down one line to fit it. This is similar to how the message field in Slack, etc., works. It is nicer than requiring the user to scroll left and right to see their full query.

Users can also force a new line by pressing Shift+Enter. (NOTE: This is currently disabled, but it can be reenabled by changing the props to MultilineTextField, and it probably should be enabled when search supports newlines.)

This is NOT about supporting queries that match across multiple lines.

q2
q1

### CODE REVIEW

**Comment by sqs** [comment]
@felixfbecker That’s a good point. Could you please still review for the code (so that when we decide the product stuff we don’t need to wait for another code review cycle)?

**Comment by ijt** [comment]
> I am worried about the product implications of this. As a user, if I am able to use shift+⮐ to insert a new line in the input, I would expect it to do a multi-line search (this is exactly how it works in VS Code). If it doesn't do that, that feels like a bug. Imo we should add this behaviour, but only when we start supporting multi-line search.

@felixfbecker We already do support multi-line search, as of https://github.com/sourcegraph/zoekt/pull/8.

**Comment by felixfbecker** [comment]
Well according to Quinn it doesn't work with this?

**Comment by ijt** [comment]
That might be because the backend expects the string `\n` for newlines rather than actual newline characters. I'd have to check...

**Comment by ijt** [comment]
When I tried this change locally, Shift+Enter didn't do anything.

**Comment by ijt** [comment]
However, I was able to get it to expand by writing a bunch of verbiage.

Screen Shot 2019-06-17 at 19 44 21

**Comment by sqs** [comment]
I just changed it to not do anything but still auto-grow to try to address the user confusion point above. That’s why.

**Comment by sqs** [comment]
@ijt I'm going to put this PR on the backburner. Feel free to pick it up when search (including non-indexed search) supports `\n`.

**Comment by ijt** [comment]
Sure, makes sense.

**Comment by christinaforney** [comment]
@ijt - does the input box parse a ⮐ as a `\n` in the search query? Since we'll have both indexed and non-indexed multi-line (with `\n`) working soon, is there anything else that would need to be implemented on the backend to support this?

**Comment by ijt** [comment]
> @ijt - does the input box parse a ⮐ as a `\n` in the search query? Since we'll have both indexed and non-indexed multi-line (with `\n`) working soon, is there anything else that would need to be implemented on the backend to support this?

@christinaforney I think that's the only thing remaining. 

As far as the way we present this to users, I think it would be a better user experience if literal newlines in the query box matched with literal newlines in the search results, and if the two character sequence `\n` in queries would match with the same two-character sequence in the code being searched.

**Comment by christinaforney** [comment]
### Ponderings/Questions
Hmmmm, I wonder if selective use of regexp patterns would actually be _more_ confusing since we respect most, but not all (`\n`).

To confirm I'm understanding how this works, it will line wrap when the query line exceeds the width of the text box, and you can _also_ add ⮐ which we would want to be interpreted as a `\n`? 

Another use case to consider: I'm want to better format my query so that my filters are on the first line, and then my regexp is on the second line for readability. In this case we wouldn't want to interpret the ⮐ as a `\n` character 

The VSCode example is valid, but also different since they don't have the same complexity with search filters that we do. 
 
### Suggestion
Interpret both ⮐ and `\n` as the newline character until we have a more clear solution for literal vs. regexp search.

**Comment by ijt** [comment]
@christinaforney that's a fair point. It may turn out to work better if we have separate search fields for regex search and structural search. The regex search field could be single line, interpreting `\n` as a newline, and the structural search field could be multiline, treating `\n` as two characters.

**Comment by slimsag** [comment]
This PR has been open for a very long time with no progress, closing. Reopen if desired.

**Pull request closed without merging**
