### PR TITLE
fix duplicate migration

### PR DESCRIPTION
**Pull request by camdencheek**
This migration conflicted with a few others that had been created since, causing migrations on main to fail.

### CODE REVIEW

**Review by efritz — APPROVED** [review]

**Review by eseliger — APPROVED** [review]

**Comment by efritz** [comment]
@sourcegraph/backend-devs Should we require branches to be up-to-date before merging?

**Comment by camdencheek** [comment]
Honestly, I don't think that's doable with how long our CI takes right now. By the time CI passes after I rebase, new commits will have been merged to main.

**Comment by eseliger** [comment]
Agree with @camdencheek

**Comment by camdencheek** [comment]
Maybe we should look into something like [bors](https://github.com/bors-ng/bors-ng)?

**Comment by efritz** [comment]
@camdencheek I thought it was infeasible but thought I'd throw it out in case someone was offended enough that they had a better idea 😋

**Comment by coury-clark** [comment]
Thanks for fixing this. I picked a bad time to talk away :(

**Comment by camdencheek** [comment]
No problem 😄 These happen often enough now that I'm getting good at fixing them

**Pull request merged**
