### PR TITLE
Hide Shepherd tour if reference element is not visible

### LINKED ISSUE #21828: sourcegraph homepage "GET STARTED" tooltip is buggy/bad
when I scroll to the bottom of the new homepage, the search tooltip "follows" and overlays the top navbar. Oddly, when I click on search a language" it doesn't scroll me up to the search bar either. (firefox)

image

image

If I scroll up, it also obscures the logo text (does not return to being placed under neath the search bar)

image

### LINKED ISSUE #21990: Tour displays improperly on mobile
image

### PR DESCRIPTION
**Pull request by novoselrok**
Fixes #21828
Fixes #21990

This PR hides all Shepherd tours (onboarding tour, search contexts, code monitor) if reference element is not visible (scrolled-away). It also reduces the font size of search onboarding tour to make it fit better on smaller screens.

### CODE REVIEW

**Comment by rrhyne** [comment]
@novoselrok Can I get a screengrab of this on mobile? I felt the font size was ok before but the spacing didn't adjust for the responsive screen size. I can provide a comp for this if required!

**Comment by novoselrok** [comment]
With reduced font size:
Screenshot 2021-06-11 at 16 57 04

With reduced padding/margin between elements:
Screenshot 2021-06-11 at 17 04 04

It's tough providing a better tour experience in such a small space.

**Comment by rrhyne** [comment]
Reduced padding was the main problem!

If it helps on mobile we could drop the two links to a new list, but I think we should just ship this and see how it works out before playing with anything else.

**Review by rrhyne — APPROVED** [review]
Ship it! :D

**Review by limitedmage — APPROVED** [review]

**Comment by novoselrok** [comment]
I'm going to merge this into the base PR: https://github.com/sourcegraph/sourcegraph/pull/21863

**Pull request merged**
