### PR TITLE
scip: symbol reference occurrence owning scope

### PR DESCRIPTION
**Pull request by Strum355**
## Motivation and Approach

Call-hierarchy has been a long (but somewhat lesser) requested code-intelligence feature (see: https://github.com/sourcegraph/sourcegraph/issues/2881 and https://github.com/sourcegraph/sourcegraph/issues/2882). This is a feature most prevalent in IntelliJ n co, but is also finding its way through various Language Servers (slowly but surely). It is not currently in the LSIF spec, and this PR will only tackle its addition into LSIF Typed :smugcat:

This PR attempts to plug the gap by introducing a new field to the `Occurrence` type, preliminarily called `owner`, of type `string` (denoting a `Symbol` but alas protobuf doesn't have type aliases 😢).
This field would contain the `Symbol` value of the most logical/intuitive next higher-scoped `Symbol`. For example:

```kotlin
package com.sourcegraph.lsif-kotlin

fun banana() {
 // ^^^^^^ maven ... com/sourcegraph/lsif-kotlin/File#banana()
	sundae()
 // ^^^^^^ ... com/sourcegraph/lsif-kotlin/File#sundae()
 // This occurrence would have the `owner` field as `maven ... com/sourcegraph/lsif-kotlin/File#banana()`
}

fun sundae() { ... }
```

From a database schema and backend implementation perspective, it would likely be almost identical to the way the existing Find References capability is serviced by LSIF typed , for both local and cross-repo intelligence.. 

### Call Hierarchy Examples

<details>
<summary>IntelliJ</summary>

image

</details>

<details>
<summary>Visual Studio Code</summary>

image

</details>

### BNF Grammar highlighting
<details>
<summary>Screenshot</summary>

### Before:
image

### After:
image

</details>

## Test plan

N/A docs addition

### CODE REVIEW

**Comment by varungandhi-src** [comment]
One of the key things that View Call Hierarchy does is that it _shows_ you the functions/methods in a tree-like fashion. This is meaningfully different from GtD+FR+FI functionality, where we only surface file names in the UI, and care about source ranges. For GtD+FR+FI, the symbol strings are an implementation detail that can be indexer-specific; all we'd care about in the backend is that they are consistent, so that we can use them as keys in some maps. However, for View Call Hierarchy the "owner" needs to be bubbled up to the user (maybe after some transformations) in a side bar or something. This means that the owner data type needs to be parsed in a consistent way across indexers.

Technically, nothing stops us from copy-pasting the string literally, but I think we shouldn't do that because it will likely lead to an inconsistent experience across languages.

Also, as it stands, I think this isn't considering the various edge cases:
1. What is the expected result if the occurrence is inside a lambda? Should the owner be the lambda? Or should it be skipped?
2. What is the expected result if the occurrence is inside a local function? Some languages distinguish these from lambdas by not allowing local functions to perform captures. Should the local function be the owner, or should it be skipped?
3. What is the expected result when the call happens in an initialization expression? Consider something like this in Swift:
    ```swift
    struct S {
        var x = 3 * f()
    }
    ```
    Should the owner be something special like `<initialization expression>x` (i.e. something we can understand and potentially show in the UI if desired)? Should it be the property declaration itself? Should it be the struct `S`? Should the occurrence for `f` not have an owner?
4. What happens if the call happens in a type expression? For example, in Rust:
    ```
    const fn double(x: usize) -> usize { return x * 2; }
    fn main() { _ = [0, 1] as [usize; double(1)] }
    ```

(This is not meant as an exhaustive list of edge cases; I haven't had breakfast yet.)

I think we should at least have clear recommendations on what should be done in such situations, so that the behavior of View Call Hierarchy is consistent across languages.

**Comment by Strum355** [comment]
> One of the key things that View Call Hierarchy does is that it _shows_ you the functions/methods in a tree-like fashion. This is meaningfully different from GtD+FR+FI functionality, where we only surface file names in the UI, and care about source ranges. For GtD+FR+FI, the symbol strings are an implementation detail that can be indexer-specific; all we'd care about in the backend is that they are consistent, so that we can use them as keys in some maps. However, for View Call Hierarchy the "owner" needs to be bubbled up to the user (maybe after some transformations) in a side bar or something. This means that the owner data type needs to be parsed in a consistent way across indexers.
>
> Technically, nothing stops us from copy-pasting the string literally, but I think we shouldn't do that because it will likely lead to an inconsistent experience across languages.

Assuming you mean the LSIF Typed symbol string here:
1. The symbol string format is protocol-defined, and should hence be consistent across indexers.
2. If that shouldn't be relied upon (I'm not sure why it couldn't be though), then Id make a strong recommendation that an `identifier` string field be added to either `Occurrence` or `SymbolInformation`. 

In addition to the identifier, I believe we should have more contextual information displayed alongside the identifier name. Rust-analyzer displays the function signature, gopls the package name + filename, IntelliJ the signature + package name. But what we surface can be another point of discussion. Personally 

---
 
> Also, as it stands, I think this isn't considering the various edge cases:
> 
>   1. What is the expected result if the occurrence is inside a lambda? Should the owner be the lambda? Or should it be skipped?

There's differing prior art on this, but mostly leaning towards "the lambda is not the owner": 

<details>
<summary><b>Kotlin in IntelliJ:</b> the lambda is not the owner, the method in which the lambda resides is the owner</summary>

image

</details>

<details>
<summary><b>Rust-analyzer in VSCode:</b> the lambda is not the owner, the method in which the lambda resides is the owner</summary>

image

</details>

<details>
<summary><b>Typescript in VSCode:</b> the lambda is not the owner etc etc</summary>

image

</details>

<details>
<summary><b>Gopls in VSCode:</b> the lambda _is_ the owner</summary>

image

</details>

---

> 
>   2. What is the expected result if the occurrence is inside a local function? Some languages distinguish these from lambdas by not allowing local functions to perform captures. Should the local function be the owner, or should it be skipped?
> 
>   3. What is the expected result when the call happens in an initialization expression? Consider something like this in Swift:
>        ```swift
>        struct S {
>            var x = 3 * f()
>        }
>        ```
>        Should the owner be something special like `<initialization expression>x` (i.e. something we can understand and potentially show in the UI if desired)? Should it be the property declaration itself? Should it be the struct `S`? Should the occurrence for `f` not have an owner?


<details>
<summary><b>IntellIJ for Kotlin makes it be the constructor for the class</b>, but see at the bottom for my thoughts on how I believe implementation in other languages should be done</summary>

image

</details>

---

>   4. What happens if the call happens in a type expression? For example, in Rust:
>        ```rust
>        const fn double(x: usize) -> usize { return x * 2; }
>        fn main() { _ = [0, 1] as [usize; double(1)] }
>        ```

<details>
<summary><b>According to rust-analyzer, `fn main` is the owner,</b> which is the most logical and "useful" in my opinion</summary>

image

</details>

---

> I think we should at least have clear recommendations on what should be done in such situations, so that the behavior of View Call Hierarchy is consistent across languages.

I generally agree, with consideration for familiarity from prior art, unless its the common consensus is that the prior art is ineffective/inferior, so I'd put emphasis on it only being a "recommendation".

**Comment by varungandhi-src** [comment]
> The symbol string format is protocol-defined, and should hence be consistent across indexers.

My bad. 🤦 I thought it wasn't standardized; I should've double-checked. Thanks for testing out the different editors. 👍

**Comment by olafurpg** [comment]
I'd love to enable call hierarchies! This feels like this is a high-impact feature we should be able to implement with relatively little effort.  I am concerned with the `Occurrence.owner` encoding is 1) quite bloated and 2) too special-cased for this use-case.

I wonder if we could achieve the same effect by adding a new field `repeated int32 SymbolInformation.definitionRange`, which is the source position enclosing the entire definition of that symbol 🤔 @Strum355 do you think that would be enough to implement call hierarchies?

Meta comment: the best way to iterate on LSIF Typed would be to make diffs to `lsif.proto` only. Once we are happy with the encoding, we can generate the associated files (Go/TS/Rust/Markdown/...)

**Comment by Strum355** [comment]
> I'd love to enable call hierarchies! This feels like this is a high-impact feature we should be able to implement with relatively little effort. I am concerned with the `Occurrence.owner` encoding is 1) quite bloated and 2) too special-cased for this use-case.

I agree that its quite hefty given the amount of information being encoded in the one string. Im not sure I fully agree on it being too special cased (or rather, that thats a bad thing), but there is possibly more general-cased which we can hopefully discover. Only other prior art I can see is from Kythe where the symbol name is used.

> I wonder if we could achieve the same effect by adding a new field `repeated int32 SymbolInformation.definitionRange`, which is the source position enclosing the entire definition of that symbol 🤔 @Strum355 do you think that would be enough to implement call hierarchies?

Heres how I understand your suggestion (and if its completely out of the park, let me know):
`SymbolInformation`'s would have two ranges: the ident token range (`range`) and the statement/block range (`definitionRange` or otherwise). Finding the owner could involve having a tree of ranges with children based on enclosing ranges and then traversing up one node. Assuming for a `SymbolInformation` on `x` such as `let x = call()`, the `definitionRange` would (in my opinion) logically encompass the entire statement, so looking up one in the ranges tree would resolve the statement instead of the function that this statement resides in.

**Comment by varungandhi-src** [comment]
We have some support for this in SCIP now because of the `enclosing_range` field. https://github.com/sourcegraph/scip/blob/main/scip.proto#L718

**Pull request closed without merging**
