### PR TITLE
Fixed a broken link to the relevant community issue

### PR DESCRIPTION
**Pull request by bmarcaur**
## Test plan

Tested the above configuration locally

### CODE REVIEW

**Review by jdorfman — APPROVED** [review]
Good catch

**Review by beyang — APPROVED** [review]

**Comment by jdorfman** [comment]
@cla-bot

**Comment by jdorfman** [comment]
@cla-bot check

**Comment by bmarcaur** [comment]
Being fixed here: https://github.com/sourcegraph/sourcegraph/pull/41461/files#diff-d06cc97b1197326e45b75efefcffb4052ababb34bb85230d5c9c8cf51afb51bfR659

**Pull request closed without merging**
