### PR TITLE
update trusted dependencies

### PR DESCRIPTION
**Pull request by slimsag**
Updates dependencies whose authors are trusted.

Test plan:

### CODE REVIEW

**Comment by nicksnyder** [comment]
Is it possible to configure renovate to auto merge deps from golang.org?

**Comment by slimsag** [comment]
No clue, but we need to make sure these changes only land near the start of a release cycle for effective regression catching.

**Comment by felixfbecker** [comment]
Is this safe?

@slimsag Renovate is configured to only create PRs the first week of each month

**Comment by slimsag** [comment]
Is what safe?

**Comment by felixfbecker** [comment]
Sorry, commented on wrong PR

**Pull request closed without merging**
