### PR TITLE
release: generate tags and close milestones on release:close

### PR DESCRIPTION
**Pull request by bobheadxi**
Expands `release:close` functionality:

* Create release tags in `deploy-sourcegraph` and `deploy-sourcegraph-docker` (closes https://github.com/sourcegraph/sourcegraph/issues/15323)
* Create a comment on release tracking issue noting the release and reminding captain to conduct post-release steps
* ~Close the milestone preemptively (nothing new should be added anyway)~ -> milestones "deprecated": https://github.com/sourcegraph/sourcegraph/pull/15743#issuecomment-726728634

Some other minor tweaks:

* Ignore newlines in cached release responses
* Better error message for failed version confirmation
* Refactor release-issue and release-milestone queries
* Refactor temporary repo clones
* Refactor tag creation
* Rename tracking issue label to `release-tracking` (to align with the existing `tracking` label)
* Tag creation now has a dryRun option

### CODE REVIEW

**Review by pecigonzalo — APPROVED** [review]
LGTM, but I would remove the closing milestones part, as we dont each team has its own milestone right now tracking their sprints, the general version milestone is likely going to be deprecated for most teams.

**Comment by bobheadxi** [comment]
> the general version milestone is likely going to be deprecated for most teams.

Hm this makes sense actually, and if we're moving towards "snapshots" of `main` as releases, it doesn't make sense anymore to have "X remaining issues in this milestone" - we will only have `release-blockers`

@pecigonzalo  How does completely removing milestones sound?

**Comment by pecigonzalo** [comment]
> @pecigonzalo How does completely removing dependence on release milestones sound?

What depends on it at the moment? I like the idea, Im just not sure I know what Im agreeing with 😂

**Comment by bobheadxi** [comment]
> What depends on it at the moment?

In theory, we should be clearing all release milestone issues (it gets posted in the status update), but in practice I don't really think it happens. This has been heavily de-emphasized recently too (the issue pings removed, etc), so I think I'll just go ahead and remove the remaining mentions.

**Pull request merged**
