### PR TITLE
Lazily init upload store to not block frontend bootup

### PR DESCRIPTION
**Pull request by mrnugget**
This Slack thread has more information: https://sourcegraph.slack.com/archives/C07KZF47K/p1605097556396300

Short version: when `./enterprise/dev/start.sh` was started `frontend`
initialized the bucket on `minio`, even when the code-intel services
weren't started.

And if `minio` hasn't booted up yet, `frontend` would wait for `minio`
to boot up. And other services, waiting for `frontend`, would also wait.

This could take between 1 and 25 seconds. 1-3 if `minio` was up, 3-25 if
`minio` needed to be started.

Since I (nor @tsenart who I was pairing with) don't know much about
code-intel architecture, this is just a rough attempt.

It does fix the problem, but might not be the proper thing in the
context of code intel.

### CODE REVIEW

**Comment by efritz** [comment]
This fix is problematic.

- Never initializes for the worker (the other use of Create).
- If it fails initialization due to timing issues, it will never connect properly.

I'm going to tackle it now a different way.

**Review by eseliger — APPROVED** [review]
Code LGTM, but would defer to @efritz for an actual approval

**Review by efritz — CHANGES_REQUESTED** [review]
Wait for new commits from me.

**Review by efritz — APPROVED** [review]
Pushed commits I'm good with.

**Review by mrnugget — COMMENTED** [review]
Looks good to me (can't approve, since it's my own PR)

**Review by eseliger — APPROVED** [review]

**Pull request merged**
