### PR TITLE
search: Fix code monitors paging

### LINKED ISSUE #16723: Code monitors page info is wrong at end of list
When looking at the list of 1 code monitors I have configured so far, it shows a "Show more" button, that doesn't do anything when I click it. That is because the pageInfo is wrong, it still points to something at the end of the list, but should be

```
pageInfo: {
  hasNextPage: false,
  endCursor: null
}
```

image

### PR DESCRIPTION
**Pull request by camdencheek**
The PageInfo returned by the GraphQL resolver for monitors was always
indicating that there were more pages after the first query because it
simply checked if the last result was empty.

This change adds logic to query the number of remaining code monitors so
that HasNextPage is set only if asking for another page would result in
more code monitors.

Fixes #16723

### CODE REVIEW

**Review by keegancsmith — APPROVED** [review]
LGTM. The way this has been done in other parts of our codebase is to just ask for N+1, but only return N. That way if you get N+1 you know there is more pages. This avoids doing an extra query, a larger DB API and coupling on ordering between fetching monitors and asking for more. However, this looks good to me.

If you want to over-optimize this idea, all you really need is an existence check, not the actual remaining count. That would make the DB do less work, but in practice an unnecessary change :)

**Comment by camdencheek** [comment]
@keegancsmith Thanks for the context! Could you point me to the place you were mentioning where this is done elsewhere in the codebase? I was struggling to find another normal example of paging

**Comment by camdencheek** [comment]
@keegancsmith I took your suggestion and removed the extra database call. Mind taking another look-over?

**Review by keegancsmith — APPROVED** [review]
LGTM. Nice and clean :)

**Pull request merged**
