### PR TITLE
database: quiet external service migration errors

### PR DESCRIPTION
**Pull request by LawnGnome**
The OOB migrator added in #26759 to populate the `has_webhooks` field of external services would error if the JSON configuration in the external service record was invalid. It turns out that we have at least one external service on cloud that has invalid JSON, as this wasn't always enforced, so this means the OOB migration will never succeed.

Instead, we'll demote that to a log message and complete the migration anyway.

### CODE REVIEW

**Review by courier-new — APPROVED** [review]
Looks great!

**Review by eseliger — APPROVED** [review]
Good change, I think the error in prod we saw was about a bad value for `kind`, but this should fix both, I think. Should we be worried about that bad entry in the DB though? 🤔

**Comment by LawnGnome** [comment]
> Good change, I think the error in prod we saw was about a bad value for `kind`, but this should fix both, I think.

Yep, but it's ultimately only hit because of the new configuration parsing required for `has_webhooks`, hence this fix. (I'd be lying if I said I was _completely_ surprised by this one.)

> Should we be worried about that bad entry in the DB though? thinking

Honestly, I have no idea. But if there's a bad entry in our database, I bet at least one or two customers are in the same boat, so we might as well deal with it.

**Comment by eseliger** [comment]
Oh yeah totally. I was just thinking we should remove the entry maybe.

**Comment by LawnGnome** [comment]
> Oh yeah totally. I was just thinking we should remove the entry maybe.

I don't have a lot of confidence in my knowledge of that environment, so I'm inclined towards not touching it. :grimacing:

**Pull request merged**
