### PR TITLE
monitoring: add fs_io_operations alert for gitserver, zoekt

### PR DESCRIPTION
**Pull request by bobheadxi**
Add monitoring for gitserver and zoekt-* services read and write operations. We use a sum of reads and writes rates over 1h to get a picture of sustained IO usage, and set the alert very high since it's currently unclear how we might want to alert on this at the moment.

Closes https://github.com/sourcegraph/sourcegraph/issues/12163 , which also describes why we are using a sum of reads and writes here.

Queries:

* [gitserver](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum%20by(name)%20(rate(container_fs_reads_total%7Bname%3D~%5C%22.*gitserver.*%5C%22,name!~%5C%22.*(_POD_%7C_jaeger-agent_).*%5C%22%7D%5B1h%5D)%5Cn%2B%20rate(container_fs_writes_total%7Bname%3D~%5C%22.*gitserver.*%5C%22,name!~%5C%22.*(_POD_%7C_jaeger-agent_).*%5C%22%7D%5B1h%5D))%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
* [zoekt-indexserver](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum%20by(name)%20(rate(container_fs_reads_total%7Bname%3D~%5C%22.*zoekt-indexserver.*%5C%22,name!~%5C%22.*(_POD_%7C_jaeger-agent_).*%5C%22%7D%5B1h%5D)%5Cn%2B%20rate(container_fs_writes_total%7Bname%3D~%5C%22.*zoekt-indexserver.*%5C%22,name!~%5C%22.*(_POD_%7C_jaeger-agent_).*%5C%22%7D%5B1h%5D))%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
* [zoekt-webserver](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum%20by(name)%20(rate(container_fs_reads_total%7Bname%3D~%5C%22.*zoekt-webserver.*%5C%22,name!~%5C%22.*(_POD_%7C_jaeger-agent_).*%5C%22%7D%5B1h%5D)%5Cn%2B%20rate(container_fs_writes_total%7Bname%3D~%5C%22.*zoekt-webserver.*%5C%22,name!~%5C%22.*(_POD_%7C_jaeger-agent_).*%5C%22%7D%5B1h%5D))%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

### CODE REVIEW

**Review by keegancsmith — APPROVED** [review]
You have been adding great alerts so I'm happy to accept this. My only concern is its using a hardcoded threshold on the number of reads. It seems that on a shard that has been horizontally scaled up 5000 may not be an issue.

Also could this trigger on large instances which deploy twice in an hour? IE on startup we do a lot of reads.

**Comment by bobheadxi** [comment]
> My only concern is its using a hardcoded threshold on the number of reads. It seems that on a shard that has been horizontally scaled up 5000 may not be an issue.

@keegancsmith  442505a40ebff2195f57a70747f6c123f06bbf15 clarifies that this alert is by instance - does that help? Presumably, even in a horizontally scaled environment, per-shard (aka per-instance?) read/writes should not be crazy high

This ties into my comment in the issue (https://github.com/sourcegraph/sourcegraph/issues/12163#issuecomment-672767617) where I bounced around the idea of some measure relative to "deployment size", but I'm not sure if there is a good measure of "deployment size" available in our current Prometheus metrics

> Also could this trigger on large instances which deploy twice in an hour? IE on startup we do a lot of reads.

The queries in the PR description indicates that we don't exceed the (admittedly arbitrarily set) threshold used in this PR, so I think we're safe for now

**Comment by keegancsmith** [comment]
>> My only concern is its using a hardcoded threshold on the number of reads. It seems that on a shard that has been horizontally scaled up 5000 may not be an issue.
>
> @keegancsmith  442505a40ebff2195f57a70747f6c123f06bbf15 clarifies that this alert is by instance - does that help? Presumably, even in a horizontally scaled environment, per-shard (aka per-instance?) read/writes should not be crazy high

I probably should have used the word replica or pod. We have some
customers who have seriously vertically scaled one pod. This is my
concern around a hardcoded number.

**Comment by bobheadxi** [comment]
I think I'll go ahead and merge this:

* current threshold is a reference that seems safe for Cloud
* edge cases (big pods) probably won't notice the warning alert, or will be able to disable it
* it seems this is a useful metric from the discussions that prompted https://github.com/sourcegraph/sourcegraph/issues/12163 
* PR approvals

Though one follow-up thought is - in general, it seems we're discouraged from creating panels without alerts, but what I've done here is pretty much do that by setting an arbitrarily high threshold, is this something we want to keep doing?

I'd like to come around to this again at some point with a better pass at improving the metric / threshold. It also seems we frequently run into issues where "this threshold works for X, but not for Y deployments" - I'm starting to think dynamic thresholds (where the threshold itself is also a query) might be useful? That might get real gnarly real fast, however :/

**Pull request merged**
