### PR TITLE
Suppress docker-on-mac message unless it's a single container deployment

### PR DESCRIPTION
**Pull request by kevinwojo**
Addresses this issue: https://github.com/sourcegraph/sourcegraph/issues/28405

### CODE REVIEW

**Comment by kevinwojo** [comment]
Doing some research on how to fingerprint host environment.

**Comment by kevinwojo** [comment]
There doesn't appear to be a lot we can do besides detect the hostname docker.internal from within the container. 
See: https://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container

**Comment by kevinwojo** [comment]
Using the `sourcegraph/server` image on my macbook pro:

Screen Shot 2021-12-10 at 4 00 18 PM

From my linux workstation:
Screen Shot 2021-12-10 at 4 00 10 PM

**Review by valerybugakov — APPROVED** [review]
✅

**Pull request merged**
