### PR TITLE
LSIF: Remove cors middleware.

### PR DESCRIPTION
**Pull request by efritz**
CORS was added to the lsif-server backend to support swagger-ui, but this isn't a hard requirements.

Until we stop proxying, we'll remove the CORS middleware here, as it causes the frontend to return two sets of header values, which messes up downstream clients.

See https://gitlab.com/gitlab-com/gl-infra/production/issues/1385#note_248611373 for details.

### CODE REVIEW

**Comment by efritz** [comment]
Swagger UI hits the lsif server directly and was only running in a dev environment.

I’ll look at replacing the header in another PR. Do we have anything else that just straight proxies like we do got LSIF (for now)?

**Comment by felixfbecker** [comment]
Uhm, [`search-badger`](https://github.com/sourcegraph/search-badger) I think

**Comment by felixfbecker** [comment]
If swagger talks to the LSIF server directly I don't understand why it needs CORS

**Comment by efritz** [comment]
> If swagger talks to the LSIF server directly I don't understand why it needs CORS

Swagger UI runs in its own container in dev.

Screen Shot 2019-11-21 at 12 22 11 PM

**Comment by felixfbecker** [comment]
Oh, I thought it was exposed by the LSIF server.

**Pull request merged**
