### PR TITLE
API console update styles

### LINKED ISSUE #23499: UI style is broken on the API console
Examples:

image

(weird color of buttons)

image

(indistinguishable selection highlight)

_[Original Slack thread](https://sourcegraph.slack.com/archives/C07KZF47K/p1627900016024700)_

### PR DESCRIPTION
**Pull request by 5h1rU**
Styles were updated to be aligned with the design refresh.

Closes #23499 

**Before**
Screen Shot 2021-08-05 at 6 10 40 PM

**After**
Screen Shot 2021-08-05 at 6 56 53 PM

### CODE REVIEW

**Comment by eseliger** [comment]
In the screenshot, the search bar seems a bit misaligned. It has margin on the left, but none on the right. Plus it doesn't exactly look like our other `<input>` elements with that `background-color` and `border-bottom`, does it? 

The "QUERY VARIABLES" pane label is very low contrast.

**Comment by 5h1rU** [comment]
> In the screenshot, the search bar seems a bit misaligned. It has margin on the left, but none on the right. Plus it doesn't exactly look like our other `<input>` elements with that `background-color` and `border-bottom`, does it?
> 
That's right, thanks for the observation.

> The "QUERY VARIABLES" pane label is very low contrast.

Unfortunately, this is using a hardcoded background value.

**Review by eseliger — APPROVED** [review]
Good improvements 👍

**Review by umpox — APPROVED** [review]
Looks much better!

FYI I noticed this when I pulled the branch, maybe a regression from the last commit?
image

We should think about adding a Percy snapshots to this page at some point, it might be quite straightforward without having to mock much

**Pull request merged**
