### PR TITLE
cody: Improve chat history from pull/52904

### PR DESCRIPTION
**Pull request by abeatrix**
closes https://github.com/sourcegraph/sourcegraph/issues/52544, https://github.com/sourcegraph/sourcegraph/issues/52848, https://github.com/sourcegraph/sourcegraph/issues/52889 and https://github.com/sourcegraph/sourcegraph/issues/52890 by @deepak2431 

Trying to merge changes from https://github.com/sourcegraph/sourcegraph/pull/52904 due to the failing CI build

not sure if this is the right way so please let me know 

## Test plan

included in the PR changes

### CODE REVIEW

**Review by eseliger — APPROVED** [review]

**Comment by deepak2431** [comment]
@abeatrix Is this all good now?

**Comment by abeatrix** [comment]
@deepak2431 still trying to get buildkit to pass 😅

**Comment by deepak2431** [comment]
> @deepak2431 still trying to get buildkit to pass 😅

Oh no, I thought it passed now.  Can you share any logs/screenshots as to what the issue is, if something is related to the code, then I can try to fix it.

**Comment by abeatrix** [comment]
@deepak2431 its the same error on both PRs 😅 
image

**Comment by deepak2431** [comment]
> @deepak2431 its the same error on both PRs 😅 image

@abeatrix  Not sure what's happening 🥲. As no E2E tests are failing locally. I saw that one integration test failed because of my latest changes(sorry for noticing this too late), so I have fixed that. If it still shows the same error, @philipp-spiess, can you have a look and help please 😅

**Comment by philipp-spiess** [comment]
@abeatrix Yeah the error seems unrelated to the changes in this PR. Let's bring this discussion back to original PR. I'll take a look. (I don't think we have to make a new PR for this btw, it's enough if you just push the specific SHA onto a branch inside the `sourcegraph/sourcegraph` repo).

**Pull request closed without merging**
