### PR TITLE
feat(ci): add grafana link to annotations

### LINKED ISSUE #37758: ci: add a grafana loki link to the failure annotation
Currently when a annotation for a job failure gets printed we have a link to the logs

image

We can add a extra link which would take you to the grafana logs for that build

ie. [grafana logs](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22buildkite%5C%22,%20build%20%3D%20%5C%22156672%5C%22%7D%20%7C%3D%20%5C%22FAIL%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D)

### PR DESCRIPTION
**Pull request by burmudar**
Typically an annotation for a failed job looks like the following:
image

In this change the heading is changed to have two links:
* logs -> View job output
* add View Grafana logs

image

Closes #37758 
## Test plan
Test manually with main dry run

### CODE REVIEW

**Review by jhchabran — APPROVED** [review]
@burmudar don't forget to add a line about this in this month newsletter !

**Comment by burmudar** [comment]
> @burmudar don't forget to add a line about this in this month newsletter !

Let me add it now before I forget! Thanks 👍🏼

**Review by sanderginn — COMMENTED** [review]
I have a feeling this will make a lot of people happy 🙂

**Comment by bobheadxi** [comment]
This is beautiful and it has made me very happy

**Pull request merged**
