### PR TITLE
Remove sign out page

### PR DESCRIPTION
**Pull request by tjkandala**
Part of [RFC 213](https://docs.google.com/document/d/1HoGEL9tgi92ru2Gel681dNEfhM0zcqFIFcZauQQwdD4/)  ([Context](https://github.com/sourcegraph/sourcegraph/issues/13440#issuecomment-694155278)).

New behavior:
- User is redirected to `/search` on sign out.

### CODE REVIEW

**Comment by unknwon** [comment]
I believe this chunk of code can be removed as well:

https://github.com/sourcegraph/sourcegraph/blob/16a0c7b3da8c09b5fda22bf4c07a0a7336a6a6d2/cmd/frontend/internal/app/sign_out.go#L10-L26

**Comment by felixfbecker** [comment]
@unknwon would you mind pushing the change you have in mind to the branch? 🙇‍♂️

**Comment by unknwon** [comment]
> @unknwon would you mind pushing the change you have in mind to the branch? 🙇‍♂️

@felixfbecker pushed in https://github.com/sourcegraph/sourcegraph/pull/14226/commits/c6410c7b30904670041f2e9cdd4923d120e92db0.

**Review by unknwon — APPROVED** [review]

**Comment by tjkandala** [comment]
@unknwon I didn't remove the call to [`ssoSignOutHandler`](https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/auth/init.go#L31:6) because the sign out functions for some providers seem to do more than return a sign out URL. For example, [here is the sign out function for OpenID Connect](https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/auth/openidconnect/session.go#L23). Is it ok to remove calls to these functions?

**Comment by unknwon** [comment]
> @unknwon I didn't remove the call to [`ssoSignOutHandler`](https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/auth/init.go#L31:6) because the sign out functions for some providers seem to do more than return a sign out URL. For example, [here is the sign out function for OpenID Connect](https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/auth/openidconnect/session.go#L23). Is it ok to remove calls to these functions?

@tjkandala Hmm, for those specific sign out functions, I would keep them for now. It makes senses to only remove any sign out page related logic, since the page gone entirely.

**Pull request merged**
