### PR TITLE
Ownership file panel

### PR DESCRIPTION
**Pull request by cbart**
Adds a button in the blob page that opens a new panel showing ownership information. The ownership info is fake for now (shows the person that last committed to the repo).

Feature flag `search-ownership` must be enabled for this the button and panel tab to show.

Note that the button to open the panel will be [replaced with a banner in a future PR](https://github.com/orgs/sourcegraph/projects/307/views/1?pane=issue&itemId=19315518).

CleanShot 2023-02-17 at 08 17 42

## Test plan

Tested manually with feature flag on and off, and also tested error state by disconnecting the network.

Storybook tests have been added for the panel contents.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.20 kb) | 0.01% (+1.20 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/cbart/codeowners-file-prototype/compare-report.html;tab=live_object) for a full comparison between the commits 70a4bf1 and 8b4ef91 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by eseliger — APPROVED** [review]

**Review by leonore — COMMENTED** [review]
can you add a description/test plan? I wanted to review but wasn't even sure where to start 😄

**Comment by limitedmage** [comment]
> can you add a description/test plan? I wanted to review but wasn't even sure where to start 😄

Thanks for the callout here, done :)

**Review by leonore — APPROVED** [review]
this looks great! tested with the feature flag on and off. the mailto button even works with correct data :D

**Pull request merged**
