### PR TITLE
Correct typo: start a Sourcegraph trial

### PR DESCRIPTION
**Pull request by abschu**

### CODE REVIEW

**Review by abeatrix — APPROVED** [review]
Thanks for catching this!

**Comment by abschu** [comment]
@abeatrix - can you please help me merge this? Thank you!

**Comment by abeatrix** [comment]
@abschu it's been corrected on main so feel free to close the PR: https://docs.sourcegraph.com/

**Comment by eseliger** [comment]
As part of #wg-delete-week I am going to close this PR. If it’s still needed, feel free to reopen and restore the branch.

**Pull request closed without merging**
