### PR TITLE
feat(sg): add version=auto for `sg release cut`

### PR DESCRIPTION
**Pull request by Chickensoupwithrice**
Previously, the version number had to be specified explicitly during the `sg release cut` command. Now we can optionally pass `--version=auto` to query release-registry for the next version. 
We need this in both places, since on main cut releases, this is the first step that happens, but during patch releases, the first step is `sg release create` which also has `--version=auto`.

## Test plan

Tested manually

## Changelog

- Add `--version=auto` to `sg release cut`

### CODE REVIEW

**Review by BolajiOlajide — APPROVED** [review]
This looks good to me.
Thank you @Chickensoupwithrice .

~However, it seems like we have this logic duplicated now. It might be helpful to have this in a function and call it in the "sg release cal" and "sg release create" command which accepts the "--version=auto" flag.~

We don't have to do this now, I just thought to share here.

**Comment by BolajiOlajide** [comment]
Ignore me

**Comment by Chickensoupwithrice** [comment]
It seems like it might still be a good idea to have a function to parse version across all the different subcommands

**Comment by Chickensoupwithrice** [comment]
Testing: 
image

**Pull request merged**
