### PR TITLE
3.0 retrospective

### PR DESCRIPTION
**Pull request by nicksnyder**
I personally dislike start/stop as separate questions because I don't think there is a meaningful difference (you can usually frame a single idea either way).

We combined them into a single question in Lattice reviews (e.g. "In the next 3 months– what should you change, stop, or start?") and I think we should combine them here too.

### CODE REVIEW

**Comment by tsenart** [comment]
This is an improvement in my opinion as well. But I think that we can do better still in the future by allowing for different sets of questions on each retro, to keep things contextual and fun.

Lots of different ideas here: http://www.funretrospectives.com/

**Comment by nicksnyder** [comment]
> I really dislike trying to conform to these questions in their specific phrasing ("Continue... We should continue doing good things we are already doing, obviously!?") as it changes my frame of mind.

I am curious how it changes your frame of mind and why you think that is a bad thing. In my mind, one function of these prompts is exactly to provoke/guide certain kinds of thought.

> In reality, all that actually matters is that we talk around points we all feel are the most important. If someone strongly feels we should continue doing something we've recently begun doing -- they'll mention it without a specific prompt asking them to do so.

I think it is too easy for people to skip over things that went well and talk only about things that could be improved. It is important to acknowledge things that went well, both to set the right tone, and because in a given situation future success may be more correlated with not regressing on good habits rather than trying to optimize the 1% that didn't go perfectly.

For example, I think if we had been doing retrospectives every month last year and if every month people praised our regular releases, we may have thought differently about 3.0.

The questions as-worded are very tactical and are framed in a way to provoke thought about a solution. I would be open to different phrasing of these two questions if you think this would be better:
- "What went well?" or "What did you like?"
- "What didn't go well?" or "What didn't you like?"

The above might provoke more problem statement answers (which can then be discussed as a group to find solutions).

> * What feedback do you have? (i.e. things we should start/stop/continue doing, ways we could improve, etc) 

My concern with a single prompt is that it wouldn't actually provoke any deep thoughts. It is easy to write down surface thoughts and feel like you have completed the survey, even if you skipped over thinking about things worth thinking about (e.g. "what went well", "what did I learn", etc.).

> http://www.funretrospectives.com/

We can definitely iterate on these questions, especially for the first couple retros, but I would like to aim for a default set of questions for each retro for consistency. I like the "Liked/Learned/Lacked" grouping for example.

I am not sure if you are suggesting this, but I would be hesitant to add contextual questions for each retro as that would feel like the leading the witness.

**Comment by tsenart** [comment]
> I am not sure if you are suggesting this, but I would be hesitant to add contextual questions for each retro as that would feel like the leading the witness.

Not suggesting that. With "contextual", I meant that we'd pick the set of well established questions (e.g. Liked, Learned, Lacked) that we thing are better suited for a given retrospective event, not that we come up with our own biased questions.

**Comment by nicksnyder** [comment]
I have updated this PR with the 3.0 retrospective document and made changes to the process discussed in that retrospective

**Pull request merged**
