### PR TITLE
chore(appliance): make a function less misleading

### PR DESCRIPTION
**Pull request by craigfurman**
isNamespaced was implemented the opposite way to its name, returning true when a resource was _not_ namespaced. We could have renamed it to isNotNamespaced, but then most callsites would look like a double negative. So this commit inverts the implementation to match the name, and also its callers.

Draft until base branch merged but can be reviewed independently.

@Chickensoupwithrice I noticed this while we were looking at your other PR. Somehow, when I had introduced that function, I wrote it backwards but also all wrote its callers backwards, so everything works 😂
This refactor is just to minimise confusion. 

## Test plan

All tests still pass, this is a refactor

### CODE REVIEW

**Comment by Chickensoupwithrice** [comment]
There's a lot of commits and files changed here that are unrelated to the changes specified in the PR. I think a lot of them have also been merged already? Maybe rebase on main? 😓

**Comment by Chickensoupwithrice** [comment]
fuck it I pulled out the last commit from this branch, into it's own [PR](https://github.com/sourcegraph/sourcegraph/pull/63994/) feel free to review that and merge in it's stead. (didn't want to clobber this PR with force push changes)

**Comment by craigfurman** [comment]
@Chickensoupwithrice sorry about that, the extra commits were a result of github auto-rebasing on main after the base branch (one of your PRs) merged. It looks super weird to reviewers when that happens, pre-rebase. Please take a look now 🙏

**Comment by craigfurman** [comment]
Approved your other one, please merge one of these then close the other 😁

**Comment by Chickensoupwithrice** [comment]
No worries at all, thought it must be something odd like that. 
Anyways I merged the other one, I'm closing this one :)

**Pull request closed without merging**
