### PR TITLE
doc:how-to-restart-a-managed-instance

### PR DESCRIPTION
**Pull request by airamare01**
Step by step process on how to restart frontend services in a docker compose deployment for managed instances

### CODE REVIEW

**Review by virginiaulrich — CHANGES_REQUESTED** [review]
I think this great to write down! But I think since a customer can't do this themselves, this perhaps better in the handbook?

**Comment by davejrt** [comment]
> I think this great to write down! But I think since a customer can't do this themselves, this perhaps better in the handbook?

I'd say expanding on this section here would be the most appropriate place

https://sourcegraph.com/github.com/sourcegraph/about@main/-/blob/handbook/engineering/distribution/managed/operations.md#restarting-for-configuration-updates

**Comment by airamare01** [comment]
Thanks @davejrt

**Comment by bobheadxi** [comment]
It seems these instructions are already available in the page @davejrt linked - I'll close this for now :)

**Pull request closed without merging**
