### PR TITLE
migrations: handle empty metadata for repo.private

### PR DESCRIPTION
**Pull request by keegancsmith**
metadata column can be empty. If that is the case, we assume the repository is
private to avoid leaking it. There are many repos without metadata on
sourcegraph.com. Additionally there are likely cases where metadata is empty on
customer instances (for example deleted repositories).

Previously if metadata was empty the migration failed. This lead to some downtime on sourcegraph.com

### CODE REVIEW

**Comment by tsenart** [comment]
@unknwon Actually intended for the default to be public, since that’s the default behavior of Sourcegraph without authz configured.

**Comment by rvantonder** [comment]
@keegancsmith you'll have to rebase this PR on top of current master to pass CI (or I can do it for you). Unfortunately this PR was branched off broken master.

**Comment by rvantonder** [comment]
@keegancsmith you'll have to rebase this PR on top of current master to pass CI (or I can do it for you). Unfortunately this PR was branched off broken master.

**Comment by keegancsmith** [comment]
> @unknwon Actually intended for the default to be public, since that’s the default behavior of Sourcegraph without authz configured.

but if you do have authz configured and for some reason we don't have the metadata, won't we leak the data? Isn't it safer to assume not visible.

I can update to assume visible. Either way the previous migration was broken if metadata was empty (lead to downtime on sourcegraph.com). I have manually mended sourcegraph.com, so no rush to merge this.

**Pull request merged**
