### PR TITLE
dev: add shfmt for shell script consistency

### PR DESCRIPTION
**Pull request by ggilmore**
[shfmt](https://github.com/mvdan/sh) is `gofmt` for shellscripts. I've been using it successfully on a few other repos and I thought it'd be nice to introduce it here too to ensure that all our scripts have consistent formatting. 

This PR adds:

- A new VSCode recommended extension: https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format
- A new set of editor configurations
- A new CI check to enforce this formatting

You can tell `shfmt` to format all files in-place by running `shfmt -w .` in the root of this repository.

--- 

I've configured the formatter to use [the formatting guidelines in Google's shell style guide](https://google.github.io/styleguide/shellguide.html#formatting). Look at this PR's diff to see what our scripts look like with this formatting.

### CODE REVIEW

**Comment by ggilmore** [comment]
Is this the first PR to request reviews from every member of the team?

**Comment by unknwon** [comment]
Bring consistency to the universe 🎉

**Comment by felixfbecker** [comment]
I noticed that Buildkite does not run the check all step for changes that only affect shell scripts: https://buildkite.com/sourcegraph/sourcegraph/builds/61283

**Comment by felixfbecker** [comment]
This is also how this PR got merged that is now failing master: https://buildkite.com/sourcegraph/sourcegraph/builds/61184 (hadolint is also failing in there)

**Comment by felixfbecker** [comment]
Fixed root cause in https://github.com/sourcegraph/sourcegraph/pull/9940, actually only affected changes to `docker-images/`

**Pull request merged**
