### PR TITLE
Use fromFetch() instead of ajax()

### LINKED ISSUE #5539: Migrate from rxjs ajax() to rxjs fromFetch()
This newer API is only a thin wrapper around `fetch()` and accepts the same options, instead of the ajax wrapper around xhr.

This would allow us to polyfill `fetch()` in tests and reuse `requestGraphQL` functions instead of having to use a full JSDOM environment, with emulated CORS restrictions etc (see #5457)

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #5539

### CODE REVIEW

**Comment by felixfbecker** [comment]
Sorry, forgot to link #5539

**Comment by beyang** [comment]
This breaks the regression tests in their current state, because `fetch` is undefined in the JSDOM environment. Tests fail with the following error: `fetch is not defined`. What's the fix? Switch the jest.config.json to use a Node environment, instead of JSDOM?

**Comment by felixfbecker** [comment]
Yes, that was the idea behind doing this. API tests shouldn't need a JSDOM environment (and all the CORS stuff that came with it). They can just polyfill with `node-fetch`. I am surprised though that JSDOM doesn't have fetch yet, I assumed it did. Sorry for breaking.

**Comment by beyang** [comment]
I attempted to switch to the jest node environment and polyfill fetch in c820415cbc2bb8dc8a08456a51146d2f8963fce4, but was unsuccessful. The error I get is `Underlying error: AbortController is not defined`. I've tried several fetch polyfill libraries and also `abortcontroller-polyfill` without success.

This is blocking me from making further progress on the regression tests, which I'd like to wrap up before EOW, so I'm going to revert this for now.

What I'm running is `yarn run test-regression` from the `web/` directory. (If you run on your machine, you'll have to set some environment variables. The test will fail and print the environment variables you'll need to set.)

**Comment by felixfbecker** [comment]
Can you give me an hour to find a solution?

**Comment by beyang** [comment]
I'll revert it on my branch (`bl/regression-onboarding-site-admin`), instead of `master`. That'll unblock me for now. Hit me up if you have any questions about the regression tests.

**Pull request merged**
