### PR TITLE
all: replace regexp with grafana/regexp

### PR DESCRIPTION
**Pull request by keegancsmith**
grafana/regexp's speedup branch contains the stdlib regexp with multiple patches applied to speed up regexp. The benchmark improvements are quite impressive across the board. The series of patches are being considered for inclusion in golang. I took a look over them, and they look legit enough for us to start using it.

This commit replaces all uses of regexp with grafana/regexp. This
replacement was done via a simple string replace on

```
^\s*"regexp"
```

Followed by goimports -w across the repository. I then manually
inspected each result to ensure it was on an import.

I considered adding a depguard rule. However, it would then also include regexp/syntax and would be a pain to use since we interact with dependencies using it. Additionally I couldn't get the lint exclusion rules working in the few places we require the stdlib regexp package.

Here is an example PR to prometheus which does the same thing. In that case the benefit was for making regex matching rules in the PromQL faster. https://github.com/prometheus/prometheus/pull/10251

Test Plan: backend integration tests

### CODE REVIEW

**Review by indradhanush — APPROVED** [review]
Changes look good. Can we add a CI check to discourage importing `regexp` in the future? We have a block list for some packages [here](https://github.com/sourcegraph/sourcegraph/blob/main/.golangci.yml#L20-L30).

**Comment by keegancsmith** [comment]
> Changes look good. Can we add a CI check to discourage importing `regexp` in the future? We have a block list for some packages [here](https://github.com/sourcegraph/sourcegraph/blob/main/.golangci.yml#L20-L30).

@indradhanush  See my description :) I'll quote the relevant part here:

> I considered adding a depguard rule. However, it would then also include regexp/syntax and would be a pain to use since we interact with dependencies using it. Additionally I couldn't get the lint exclusion rules working in the few places we require the stdlib regexp package.

It would be nice to reach a solution here, since I do want to prevent future uses of stdlib regexp unless needed.

**Review by eseliger — APPROVED** [review]
Nice! Sad we can't somehow guard regressions here :(

**Comment by indradhanush** [comment]
> @indradhanush See my description :) I'll quote the relevant part here:

Ouch. I must be going blind. I totally missed that. :disappointed:

**Comment by indradhanush** [comment]
> It would be nice to reach a solution here, since I do want to prevent future uses of stdlib regexp unless needed.

@keegancsmith Maybe a bash script based check that is invoked from `go-lint.sh`? :thinking: 
This might be hard to get 100% right though.

**Comment by keegancsmith** [comment]
> > It would be nice to reach a solution here, since I do want to prevent future uses of stdlib regexp unless needed.
> 
> @keegancsmith Maybe a bash script based check that is invoked from `go-lint.sh`? thinking This might be hard to get 100% right though.

I'll spend a little more time here to see if I can get depguard working. Otherwise I'd rather reap the performance benefits now. In general we don't actually need everyone using this. It is most important in places like searcher and zoekt which can be bounded by regexp perf.

Either way I'll land this monday morning. Rather not land a large scale replace on a friday afternoon :)

**Review by camdencheek — APPROVED** [review]
Wow! Those _are_ some impressive benchmarks. Curious to see if this helps. Good find

**Review by LawnGnome — APPROVED** [review]
image

**Comment by keegancsmith** [comment]
Don't know what I did wrong before, but managed to get depguard with exclusions working now. Will land once CI is happy.

**Pull request merged**
