### PR TITLE
dev/sg: remove bitfield/script for sourcegraph/run

### PR DESCRIPTION
**Pull request by bobheadxi**
Introduces https://github.com/sourcegraph/run so we can start experimenting!

Also fixes the analytics flag to disable analytics in dev builds, and fixes the repo state differ which wasn't including unstaged/uncommitted changes

## Test plan

image

### CODE REVIEW

**Comment by bobheadxi** [comment]
Current dependencies on/for this PR:
* main
  * **PR #35157** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/35157" target="_blank">Graphite</a>  👈
    * **PR #35199** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/35199" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/35157?utm_source=stack-comment).

**Comment by bobheadxi** [comment]
Licenses check failing, requires https://github.com/sourcegraph/run/pull/7

**Comment by mrnugget** [comment]
Is the goal with `sourcegraph/run` to replace `dev/sg/internal/run`? Because if _not_ then the naming could end up being tricky to work with.

Also: any particular reason why this is a separate repo and not in `lib`?

**Review by jhchabran — APPROVED** [review]

**Comment by jhchabran** [comment]
> Is the goal with `sourcegraph/run` to replace `dev/sg/internal/run`? Because if _not_ then the naming could end up being tricky to work with.

No it's not, as the `sg/internal/run` package focuses on running commands as defined in `sg.config.yaml` whereas `sourcegraph/run` aims at providing sane and simple defaults for running shell commands in the context of writing Go code that replaces scripts. 

We overlooked when picking the name the clash with the existing `run` package. 

> Also: any particular reason why this is a separate repo and not in lib?

There is no hard stop to have it under `lib`. That being said, it's easier to have it as a separate repo because as we're gradually replacing bash scripts here and here with Go code, it's just a small dependency that we can carry around without pulling in our huge repo.  

It's also a way to enforce that we're not pulling in any dependencies from `sourcegraph/sourcegraph` as this is aimed to be free from details context-specific to Sourcegraph. 

And it's a pet project of the team if you will. That being said, nothing is set into stone, this is an experiment :)

**Comment by mrnugget** [comment]
Makes sense to me, thanks! I'm interesting to see how this experiment goes. (In Batch Changes we did have a separate repository but updating the versions in `sourcegraph/sourcegraph` and in `src-cli` became a chore quite fast and then we got `lib` as a separate Go project so we used that and removed one step to update it... That's also why I'm asking, because I'm genuinenly curious how this'll work out)

**Comment by bobheadxi** [comment]
> Is the goal with sourcegraph/run to replace dev/sg/internal/run? Because if not then the naming could end up being tricky to work with.

One idea was to rename `dev/sg/internal/run` to `sgrun` and re-orient it to focus on "running things in the `sg` repo", but that's still TBD - we decided the clash was worth it for now for the clean name 😛 Everything else JH says holds here though - the goal is to introduce an alternative to `exec` for the most part!

> it's just a small dependency that we can carry around without pulling in our huge repo. [...] It's also a way to enforce that we're not pulling in any dependencies from sourcegraph/sourcegraph as this is aimed to be free from details context-specific to Sourcegraph.

This is especially true in the context of other initiatives that introduce some more complex tooling to in CI, where the standalone Sourcegraph-agnostic package will come in useful. It also encourages us to keep the module lean!

> And it's a pet project of the team if you will. That being said, nothing is set into stone, this is an experiment :)

😛 

> I'm interesting to see how this experiment goes. (In Batch Changes we did have a separate repository but updating the versions in sourcegraph/sourcegraph and in src-cli became a chore quite fast and then we got lib as a separate Go project so we used that and removed one step to update it... That's also why I'm asking, because I'm genuinenly curious how this'll work out)

We're hoping this will be not too painful for the reasons mentioned above, and IIRC there's been some improvements in Go's multi-module tooling that we could try out as part of this. We'll try to track thoughts on our experience working with the multiple modules!

**Pull request merged**
