### PR TITLE
authz: Tighten security and enable syncing for site admins

### PR DESCRIPTION
**Pull request by ryanslade**
This change disables some endpoints for site admins that they could have used
to get the names of private repos they should not have access to.

It also ensure that we sync repo permissions for site admins correctly.

### CODE REVIEW

**Review by tsenart — APPROVED** [review]
Disabling the entire resolver, as you suggested, sound better! What's the best way to do that, technically?

**Comment by ryanslade** [comment]
I think we might be able to just add a .com check around this:
https://github.com/sourcegraph/sourcegraph/blob/108a15da31fff5ba2153138eac3c226ebf1e81ce/enterprise/cmd/frontend/internal/authz/init.go#L146

**Comment by tsenart** [comment]
@ryanslade: Nice, go for it.

**Comment by ryanslade** [comment]
Just waiting for 👍 from @unknwon in case there's something we're missing.

**Comment by unknwon** [comment]
Thanks @ryanslade! The approach LGTM, but on a second thought I do not think we can disable the resolver entirely because it would break "Permissions" page under both user settings and repository settings page.

**Comment by ryanslade** [comment]
@joe I noticed that once I enabled the permissions endpoints you mentioned and then visited the user permission page I see this when authz is enforced for site admins: 

Screenshot 2021-05-19 at 10 16 28

Is there something more we need so that site admin permissions are synced now?

**Comment by unknwon** [comment]
> @joe I noticed that once I enabled the permissions endpoints you mentioned and then visited the user permission page I see this when authz is enforced for site admins:
> 
> Screenshot 2021-05-19 at 10 16 28
> 
> Is there something more we need so that site admin permissions are synced now?

Good call, should just be one-line of change: https://github.com/sourcegraph/sourcegraph/blob/1ff4074962e52a0847be7b184d1816fcca7c13fb/enterprise/internal/database/perms_store.go#L1241

**Comment by ryanslade** [comment]
@unknwon PTAL

**Review by unknwon — APPROVED** [review]

**Pull request merged**
