### PR TITLE
otel: add zipkin exporter

### LINKED ISSUE #56220: Add zipkin exporter to OpenTelemetry bundled integrations
#### Feature request description

Requested by: https://github.com/sourcegraph/accounts/issues/565

Extend the bundled OpenTelemetry Collector in Sourcegraph to include a Zipkin exporter, allowing the emitted traces to be compatible with systems that ingest Zipkin-formatted traces.

### PR DESCRIPTION
**Pull request by burmudar**
Requested by #56220

Closes #56220 https://github.com/sourcegraph/devx-support/issues/266
## Test plan
1. `sg wolfi package opentelemetry-collector`
2. point `wolfi-image/opentelemetry-collector.yaml` to `opentelemetry@local`
3. `sg wolfi image opentelemetry-collector`
4. `docker run -it --entrypoint /bin/sh -v /Users/william/code/sourcegraph/docker-images/opentelemetry-collector/configs:/otel-collector/configs sourcegraph-wolfi/opentelemetry-collector-base:latest-amd64`
5. `otelcol-sourcegraph --config configs/jaeger.yaml`
```
2023-09-29T09:12:16.035Z        info    service/telemetry.go:81 Setting up own telemetry...
2023-09-29T09:12:16.042Z        info    service/telemetry.go:104        Serving Prometheus metrics      {"address": ":8888", "level": "Basic"}
2023-09-29T09:12:16.043Z        debug   extension@v0.81.0/extension.go:135      Beta component. May change in the future.       {"kind": "extension", "name": "health_check"}
2023-09-29T09:12:16.043Z        debug   extension@v0.81.0/extension.go:135      Beta component. May change in the future.       {"kind": "extension", "name": "zpages"}
2023-09-29T09:12:16.050Z        debug   exporter@v0.81.0/exporter.go:273        Beta component. May change in the future.       {"kind": "exporter", "data_type": "traces", "name": "zipkin"}

```

### CODE REVIEW

**Review by Strum355 — APPROVED** [review]

**Comment by willdollman** [comment]
@burmudar you'll need to bump the `epoch` field in the `opentelemetry-collector.yaml` file for it to build a new version of the package.

**Comment by burmudar** [comment]
> @burmudar you'll need to bump the `epoch` field in the `opentelemetry-collector.yaml` file for it to build a new version of the package.

AH thanks. I was just about to lookup in the docs on what I should do 😆

**Review by willdollman — APPROVED** [review]

**Comment by willdollman** [comment]
> 1. sg wolfi package opentelemetry-collector
> 2. point wolfi-image/opentelemetry-collector.yaml to opentelemetry@local
> 3. docker run -it --entrypoint /bin/sh -v /Users/william/code/sourcegraph/docker-images/opentelemetry-collector/configs:/otel-collector/configs sourcegraph-wolfi/opentelemetry-collector-base:latest-amd64

You also need to run `sg wolfi image opentelemetry-collector` between 2 and 3 to build the image, otherwise you'll just be running an image that you built a while ago.

As an alternative to building the package + image locally you can also test the image that buildkite builds for you, as it includes your updated package. There's an info block at the top of the [build page](https://buildkite.com/sourcegraph/sourcegraph/builds/244791):

image

**Comment by burmudar** [comment]
> > 1. sg wolfi package opentelemetry-collector
> > 2. point wolfi-image/opentelemetry-collector.yaml to opentelemetry@local
> > 3. docker run -it --entrypoint /bin/sh -v /Users/william/code/sourcegraph/docker-images/opentelemetry-collector/configs:/otel-collector/configs sourcegraph-wolfi/opentelemetry-collector-base:latest-amd64
> 
> You also need to run `sg wolfi image opentelemetry-collector` between 2 and 3 to build the image, otherwise you'll just be running an image that you built a while ago.
> 
> As an alternative to building the package + image locally you can also test the image that buildkite builds for you, as it includes your updated package. There's an info block at the top of the [build page](https://buildkite.com/sourcegraph/sourcegraph/builds/244791):
> 
> image

Oh that is a typo (which I'll fix now) I did run `sg wolfi-image opentelemetry-collector` :D

**Pull request merged**
