### PR TITLE
serch: Prevent flash of content in search sidebar

### PR DESCRIPTION
**Pull request by fkling**
Before: 

https://user-images.githubusercontent.com/179026/129422685-263a3dc0-8851-4f10-82a0-c7ec7de4b5e2.mp4

After:

https://user-images.githubusercontent.com/179026/129422695-265dc6cd-af17-4a1a-9515-46dee8fb4cdf.mp4

Also fixes the issue that the wrong ID is used for the search snippets section.

### CODE REVIEW

**Comment by limitedmage** [comment]
I'm trying to test this locally but I only get a blank sidebar 🤔
Maybe something is wrong with my setup since TypeScript and Node versions have been updated since this PR was created. When you're back from vacation, can you sync with main and I'll take a second look?

**Comment by fkling** [comment]
Looks like if you never closed a section then `collapsedSection` will always be `null` or `undefined`? I assumed it would at least be an empty object...

**Comment by fkling** [comment]
I worked around this issue by adding the option to specify a default value. Please let me know what you think about that.

**Review by limitedmage — APPROVED** [review]
Looks great and works great for me now. Like the solution of giving temporary settings an initial "default value".

**Comment by fkling** [comment]
I didn't notice that this didn't get merged. It seems my updates somehow cause an infinite loop. I'll investigate.

**Pull request merged**
