### PR TITLE
bazel: wildcard jest tests

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context

1. Use the `.tsx` extension for all jest snapshot tests.
2. Enable wildcard jest tests on CI.

## Test plan

CI

## App preview:

- [Web](https://sg-web-vb-bazel-jest-snapshots.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by valerybugakov** [comment]
@jbedard a couple of issues here:

1. Bazel says that all snapshot files are obsolete after running `bazel test //client/wildcard:test`.
2. `bazel test //client/wildcard:test` fails despite all the tests being green.
3. `bazel run //client/wildcard:test_update_snapshots` fails with babel transpilation errors:
```
λ bazel run //client/wildcard:test_update_snapshots
INFO: Analyzed target //client/wildcard:test_update_snapshots (0 packages loaded, 1384 targets configured).
INFO: Found 1 target...
ERROR: /Users/val/Desktop/sourcegraph-root/sourcegraph/client/shared/dev/BUILD.bazel:45:11: Compiling client/shared/dev:mock_ts_transpile [for tool] failed: (Exit 1): mock_ts_transpile_lib__js_binary.sh failed: error executing command (from target //client/shared/dev:mock_ts_transpile_lib) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/client/shared/dev/mock_ts_transpile_lib__js_binary.sh client/shared/dev --config-file ../../../bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/babel.config.js ... (remaining 7 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
SyntaxError: /private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/client/shared/dev/mock_ts_transpile_lib__js_binary.sh.runfiles/__main__/node_modules/.aspect_rules_js/@ampproject+remapping@2.1.2/node_modules/@jridgewell/trace-mapping/dist/types/trace-mapping.d.ts: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference. (5:41)

  3 | export type { SourceMapSegment } from './sourcemap-segment';
  4 | export type { SourceMapInput, SectionedSourceMapInput, DecodedSourceMap, EncodedSourceMap, SectionedSourceMap, InvalidOriginalMapping, OriginalMapping as Mapping, OriginalMapping, InvalidGeneratedMapping, GeneratedMapping, EachMapping, } from './types';
> 5 | export declare const LEAST_UPPER_BOUND = -1;
    |                                          ^
  6 | export declare const GREATEST_LOWER_BOUND = 1;
  7 | /**
  8 |  * Returns the encoded (VLQ string) form of the SourceMap's mappings field.
    at instantiate (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:67:32)
    at constructor (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:364:12)
    at TypeScriptParserMixin.raise (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:3365:19)
    at TypeScriptParserMixin.parseVarStatement (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:9201:14)
    at TypeScriptParserMixin.parseStatementContent (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:13039:23)
    at TypeScriptParserMixin.parseStatementContent (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:9223:18)
    at TypeScriptParserMixin.parseStatementLike (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:12952:17)
    at TypeScriptParserMixin.parseStatementListItem (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:12937:17)
    at TypeScriptParserMixin.parseExportDeclaration (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:14246:17)
    at TypeScriptParserMixin.parseExportDeclaration (/private/var/tmp/_bazel_val/b74f98c07c1f7901aeeb711da373452f/sandbox/darwin-sandbox/832/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@babel+parser@7.20.5/node_modules/@babel/parser/lib/index.js:9378:85) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'ConstInitiailizerMustBeStringOrNumericLiteralOrLiteralEnumReference',
  syntaxPlugin: 'typescript',
  loc: Position { line: 5, column: 41, index: 643 },
  pos: [Getter/Setter]
}
```

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.01% (+0.37 kb) | 0.00% (+0.37 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vb/bazel-jest-snapshots/compare-report.html;tab=live_object) for a full comparison between the commits b9ec9a7 and f79e640 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by jbedard** [comment]
Bazel runs the tests on pre-compiled .js files so we have no way of knowing if the original test was .ts or .tsx. Jest requires mapping from the test file name (.js in bazel, .ts[x] in non-bazel) to the snapshot file name (.ts[x].snap) without any additional information - if we only know the .js name we don't know if the snapshot is .ts or .tsx.

While we need to support non-bazel we can't update the existing snapshots to `.js.snap`, so I think we agreed the easiest thing to do was make all snapshot tests use tsx extensions for now.

**Comment by limitedmage** [comment]
Thanks makes sense, thanks! Can we add a linter rule for this? (if `expect(...).toMatchSnapshot` is used, make sure file is `.tsx`)?

**Comment by jbedard** [comment]
Once bazel tests are on CI that should catch it. Is that enough?

**Comment by valerybugakov** [comment]
@jbedard, thanks for sharing the reasoning! I'm adding your comment to the jest resolver file.

**Review by burmudar — APPROVED** [review]

**Pull request merged**
