### PR TITLE
Update free tier limits

### PR DESCRIPTION
**Pull request by chenkc805**
Updating the Free tier limits. Context: https://linear.app/sourcegraph/issue/CODY-2553/update-cody-free-tier-to-make-it-more-appealing

## Test plan

manual review

### CODE REVIEW

**Review by chrsmith — APPROVED** [review]
As far as updating the copy on the page, this seems fine. But have we already updated the places where we _enforce_ those free tier limits? Off the top of my head, I don't know exactly where that logic is.

But somewhere we have `500` and `200` hard-coded and would need to update those too. Ideally before we update the text on the page.

**Comment by chenkc805** [comment]
@chrsmith can I get your re-review? Thank you

**Comment by chrsmith** [comment]
The Copy is still fine, but we shouldn't merge this until we are ready to actually change the values. (Since as-is this just says we'll give users limit X, but it will remain Y.)

After looking a bit harder, it appears that these settings are defined in the Sourcegraph dotcom site configuration. Here:
https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go?L235-273

So let's just coordinate on when we're ready to make the config change, and then we can merge this PR and everything will "just work".

**Review by chrsmith — APPROVED** [review]
Actually you already made the site config changes. And they are totally live. So we can safely merge this now!
https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/18643/files
image

**Pull request merged**
