### PR TITLE
Use go embedded files for ui/assets and template packages

### PR DESCRIPTION
**Pull request by eseliger**
This also led to some simplifications in the template code.

Co-authored-by: Keegan Carruthers-Smith <keegan.csmith@gmail.com>

### CODE REVIEW

**Review by mrnugget — APPROVED** [review]
I like this new world we're entering

**Review by unknwon — APPROVED** [review]
I guess there is nothing to review as long as it works 🤷‍♂️

**Review by LawnGnome — APPROVED** [review]

**Comment by keegancsmith** [comment]
> I like this new world we're entering

I love go embed. So well designed, especially with the new `io/fs` pkg.

**Review by keegancsmith — APPROVED** [review]

**Review by asdine — APPROVED** [review]
😲

**Pull request merged**
