### PR TITLE
permissions-center: fix GraphQL types after renaming them in other commit.

### PR DESCRIPTION
**Pull request by sashaostrikov**
Test plan:
CI.
Storybook.

## App preview:

- [Web](https://sg-web-ao-fix-types.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by sanderginn — APPROVED** [review]
TY 🙌

**Review by burmudar — APPROVED** [review]
🤞🏼

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.83% (+22.67 kb) 🔺 | -0.04% (-5.32 kb) | -0.23% (-27.99 kb) 🔽 | -1.66% (-13) 🔽 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ao/fix-types/compare-report.html;tab=live_object) for a full comparison between the commits c2a8d33 and e5912f4 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).

**Note:** We do not have exact data for c8378f4. So we have used data from: e5912f4.
The intended commit has no frontend pipeline, so we chose the last commit with one before it.

<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by sanderginn** [comment]
Found a few non-breaking incorrectly named references:
1. [GQL docstring 1](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ao/fix-types/-/blob/cmd/frontend/graphqlbackend/authz.graphql?L357)
2. [GQL docstring 2](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ao/fix-types/-/blob/cmd/frontend/graphqlbackend/authz.graphql?L362)

**Comment by sashaostrikov** [comment]
> Found a few non-breaking incorrectly named references

Will fix them later in order not to retrigger this build

**Comment by sanderginn** [comment]
Great idea 😄

**Pull request merged**
