### PR TITLE
own: Trigger alert when some results don't have ownership data

### PR DESCRIPTION
**Pull request by eseliger**
When there are no rules for a given file result, we want to trigger an alert in search to inform that the result set is not complete.

I hated that I couldn't make the `-file:has.owner()` clickable in the alert, so I decided to implement a custom renderer. WDYT? You can collapse it to a very small version, and that "collapse preference" is stored.

Screenshot 2023-03-10 at 02 18 54@2x

Screenshot 2023-03-10 at 02 20 12@2x

Closes https://github.com/sourcegraph/sourcegraph/issues/48594

## Test plan

Added storybook and test coverage, and verified manually things feel alright.

### CODE REVIEW

**Comment by limitedmage** [comment]
I think we can return Markdown here? If so, I would format the link instead of showing a URL. Content looks good otherwise.

**Comment by eseliger** [comment]
Yep I returned it as markdown already, but the other alerts used URLs interestingly so I aligned with that.. thought there must’ve been a reason 😅 perhaps not, I can change it

**Comment by leonore** [comment]
maybe PM/designer can better advise here, but is there any worry about the banner being a big distraction? I feel like it's likely going to happen for many owner searches

**Comment by eseliger** [comment]
TODO: Should we add a "add -file:has.owners() to your query to see unowned resources"?

**Comment by eseliger** [comment]
I hated that I couldn't make the `-file:has.owner()` clickable in the alert, so I decided to implement a custom renderer. WDYT? You can collapse it to a very small version, and that "collapse preference" is stored.

Screenshot 2023-03-10 at 02 18 54@2x

Screenshot 2023-03-10 at 02 20 12@2x

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.70 kb) | 0.01% (+1.70 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/es/select-job-alert-no-owner/compare-report.html;tab=live_object) for a full comparison between the commits 61d705a and 07aada2 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by malomarrec** [comment]
Cool addition!

**Pull request merged**
