### PR TITLE
Fix underscores not rendering in search bar on Linux

### LINKED ISSUE #11880: bug: underscores not appearing in search bar
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Firefox 77.0.1

#### Steps to reproduce:

1. Navigate to sourcegraph.com/search
2. Type '_' in the search bar

#### Expected behavior:
An underscore appears.
#### Actual behavior:
An underscore does not appear (but if you copy paste the textbox contents, you can see that there is an underscore there).

cc @sourcegraph/web

### LINKED ISSUE #16595: Underscores are rendering as spaces
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** Ubuntu 20.04, Google Chrome 86

#### Steps to reproduce:

1. Type in a search term containing an underscore

#### Expected behavior:

Underscores should render as underscores.

#### Actual behavior:

Underscores render as spaces (in this screenshot, `http_response_size` is rendering as `http response size`. Please ignore the highlighted "http"). The issue happens in both Dark Mode and Light Mode.

image

IMO this is a huge usability issue since there's a lot of code out there that contains underscores

### PR DESCRIPTION
**Pull request by bduffany**
Fixes #16595
Fixes #11880

### CODE REVIEW

**Comment by limitedmage** [comment]
Thanks @bduffany for submitting this patch!
@sourcegraph/search or @sourcegraph/web  can someone with Linux try to repro this bug and verify this fix?

**Review by tjkandala — APPROVED** [review]
Looks good for me:

<details open>
<summary>Before</summary>

</details>

<details open>
<summary>After</summary>

</details>

**Comment by limitedmage** [comment]
Thanks @tjkandala! @bduffany Feel free to merge this PR (the failing checked are not required).

**Comment by keegancsmith** [comment]
@bduffany I merged in for ya. Just noticed you are not part of the sourcegraph org. Thanks so much for your contribution!

**Pull request merged**
