### PR TITLE
Split resolveRepositories code

### PR DESCRIPTION
**Pull request by asdine**
With the addition of version contexts, the [`resolveRepositories`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a25a93ab1843c41d4deab41701084b83a16bf712/-/blob/cmd/frontend/graphqlbackend/search.go#L370) function became bloated and hard to read.
This PR tries to simplify it by splitting it into multiple functions, but since all of these functions require and modify the same variables, I instead created a type containing all of the shared state and created methods.
Let me know if you have ideas for improvement or even other design ideas.

### CODE REVIEW

**Comment by slimsag** [comment]
I am probably not the person best-suited to review due to time constraints on my end.

That said, this function is notoriously difficult to edit and has been broken with simple refactors in the past, leading to major search regressions. I'd say we need a completely exhaustive test suite to be able to be confident about this change

**Comment by asdine** [comment]
@keegancsmith Yeah it makes sense, the changes are pretty heavy. I have updated the branch, now there are multiple small incremental commits. Let me know if you need more granularity or if you have any question.

**Comment by unknwon** [comment]
Thanks for the improvement :) I won't have time review this PR but just want to mention this is a good chance to add more tests around these methods.

**Comment by rvantonder** [comment]
Disclaimer: I didn't review this code. But, echoing what Keegan says: `findPatternRevs` behavior made prototyping https://github.com/sourcegraph/sourcegraph/pull/9425 really difficult. The tests did pick up violations when I was working on it, but I'd be cautious about changes here that aren't extremely well tested. Could it help to our e2e search tests before this is merged (since we don't do that in CI I believe)?

**Comment by tsenart** [comment]
This PR seems like is not going to land. Please close.

**Comment by asdine** [comment]
Sorry, it didn't focus on this one for a while, I kept pushing it because I was focused on other tasks and didn't really know how to write these new tests. 
If you think It's worth it I can try to finish it this week, otherwise I'll close it.

**Comment by tsenart** [comment]
> If you think It's worth it I can try to finish it this week, otherwise I'll close it.

What's your estimate for this?

**Comment by asdine** [comment]
Most of the work is done, what's left is to rebase and write some tests to make sure it's solid. I'd really want to not spend more than a day on this + review

**Comment by tsenart** [comment]
If you can time box one day for this I'd say go for it.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by asdine** [comment]
I'm closing this PR as it has become too desynchronised from master and it's painful to rebase. I'm open to any suggestion on a potential improvement of this function

**Pull request closed without merging**
