### PR TITLE
Fix typos across sourcegraph repository

### PR DESCRIPTION
**Pull request by kittenking**
:blue_heart: Fix typos across **sourcegraph** repository

### Fixed files :wrench: 

<details><summary>See all fixed files</summary>
<p>

```
sourcegraph/browser/README.md:109:43: "begining" is a misspelling of "beginning"
sourcegraph/browser/src/browser/README.md:3:340: "psuedo" is a misspelling of "pseudo"
sourcegraph/browser/src/extension/scripts/background.tsx:320:100: "transfering" is a misspelling of "transferring"
sourcegraph/browser/src/platform/extensionHost.ts:93:3: "transfering" is a misspelling of "transferring"
sourcegraph/browser/src/shared/components/OpenDiffOnSourcegraph.tsx:37:91: "occuring" is a misspelling of "occurring"
sourcegraph/browser/src/shared/components/OpenDiffOnSourcegraph.tsx:98:25: "specfic" is a misspelling of "specific"
sourcegraph/browser/src/types/chrome/index.d.ts:978:102: "occured" is a misspelling of "occurred"
sourcegraph/browser/src/types/chrome/index.d.ts:2521:118: "occured" is a misspelling of "occurred"
sourcegraph/browser/src/types/chrome/index.d.ts:3062:136: "manfiest" is a misspelling of "manifest"
sourcegraph/browser/src/types/chrome/index.d.ts:5053:54: "everthing" is a misspelling of "everything"
sourcegraph/cmd/frontend/graphqlbackend/search_results.go:732:46: "explicitely" is a misspelling of "explicitly"
sourcegraph/cmd/frontend/graphqlbackend/search_suggestions.go:247:9: "explicitely" is a misspelling of "explicitly"
sourcegraph/cmd/frontend/internal/session/session.go:263:23: "reponse" is a misspelling of "response"
sourcegraph/cmd/gitserver/main.go:57:62: "accidently" is a misspelling of "accidentally"
sourcegraph/cmd/gitserver/server/cleanup.go:590:26: "psuedo" is a misspelling of "pseudo"
sourcegraph/cmd/gitserver/server/list-gitolite_test.go:60:25: "repsonse" is a misspelling of "response"
sourcegraph/cmd/gitserver/server/lock.go:21:26: "maintance" is a misspelling of "maintenance"
sourcegraph/cmd/gitserver/server/patch.go:131:28: "commiting" is a misspelling of "committing"
sourcegraph/cmd/gitserver/server/repo_info_test.go:109:8: "mutliple" is a misspelling of "multiple"
sourcegraph/cmd/gitserver/server/serverutil.go:379:15: "gaurenteed" is a misspelling of "guaranteed"
sourcegraph/cmd/management-console/web/src/MonacoEditor.tsx:86:63: "neccessary" is a misspelling of "necessary"
sourcegraph/cmd/repo-updater/repos/gitolite.go:122:49: "satisfiy" is a misspelling of "satisfy"
sourcegraph/cmd/repo-updater/repos/purge.go:30:46: "accidently" is a misspelling of "accidentally"
sourcegraph/cmd/repo-updater/repos/scheduler_test.go:1240:51: "futher" is a misspelling of "further"
sourcegraph/cmd/repo-updater/repos/store.go:125:40: "commited" is a misspelling of "committed"
sourcegraph/cmd/repo-updater/repos/testing.go:318:49: "existant" is a misspelling of "existent"
sourcegraph/doc/_resources/templates/doc.html:197:53: "Adminstration" is a misspelling of "Administration"
sourcegraph/doc/_resources/templates/doc.html:198:65: "Adminstration" is a misspelling of "Administration"
sourcegraph/doc/admin/auth/index.md:259:84: "conatiner" is a misspelling of "container"
sourcegraph/doc/admin/faq.md:1:2: "Adminstration" is a misspelling of "Administration"
sourcegraph/doc/admin/install/docker/index.md:65:8: "adminstration" is a misspelling of "administration"
sourcegraph/doc/admin/troubleshooting.md:1:2: "Adminstration" is a misspelling of "Administration"
sourcegraph/doc/dev/code_reviews.md:57:175: "Futher" is a misspelling of "Further"
sourcegraph/doc/dev/product/index.md:112:62: "alotted" is a misspelling of "allotted"
sourcegraph/doc/dev/releases.md:99:16: "commited" is a misspelling of "committed"
sourcegraph/enterprise/cmd/frontend/auth/oauth/cookie.go:18:31: "compatability" is a misspelling of "compatibility"
sourcegraph/enterprise/cmd/frontend/internal/licensing/features.go:26:71: "explictly" is a misspelling of "explicitly"
sourcegraph/enterprise/cmd/frontend/internal/licensing/features.go:50:41: "explictly" is a misspelling of "explicitly"
sourcegraph/migrations/1528395575_.up.sql:45:19: "accidently" is a misspelling of "accidentally"
sourcegraph/packages/sourcegraph-extension-api/src/sourcegraph.d.ts:1175:17: "transfomers" is a misspelling of "transforms"
sourcegraph/packages/sourcegraph-extension-api/src/sourcegraph.d.ts:1207:40: "wih" is a misspelling of "with"
sourcegraph/pkg/conf/computed.go:46:15: "compatability" is a misspelling of "compatibility"
sourcegraph/pkg/conf/server.go:133:9: "initalizes" is a misspelling of "initializes"
sourcegraph/pkg/endpoint/endpoint.go:40:54: "seperated" is a misspelling of "separated"
sourcegraph/pkg/ratelimit/rate_limit_test.go:68:15: "remaing" is a misspelling of "remaining"
sourcegraph/shared/src/components/completion/CompletionWidget.tsx:18:60: "explictly" is a misspelling of "explicitly"
sourcegraph/shared/src/notifications/NotificationItem.tsx:42:77: "occured" is a misspelling of "occurred"
sourcegraph/web/src/api/APIConsole.tsx:204:7: "Foward" is a misspelling of "Forward"
sourcegraph/web/src/api/graphiql-theme.scss:8:42: "unfortunetly" is a misspelling of "unfortunately"
sourcegraph/web/src/components/SearchResultMatch.tsx:92:72: "maintaing" is a misspelling of "maintaining"
sourcegraph/web/src/search/results/SearchResultsList.tsx:76:8: "Refrence" is a misspelling of "Reference"
sourcegraph/web/src/tree/Tree.tsx:69:48: "avialable" is a misspelling of "available"
```

</p>
</details>

**FYI:** I used [**Go Spellchecker**](https://github.com/liamzdenek/go-spellcheck) :smile_cat:

### CODE REVIEW

**Comment by keegancsmith** [comment]
I just manually pushed your code to our repo so we get a CI job running. If that looks good I'll merge in. Thanks!

**Comment by keegancsmith** [comment]
@kittenking can you merge in https://github.com/sourcegraph/sourcegraph/tree/spelling to get our CI to pass?

**Comment by kittenking** [comment]
@keegancsmith I don't understand, can you please elaborate the process?

**Comment by keegancsmith** [comment]
Out CI is failing, I pushed a commit to the `spelling` branch which contains a fix. Your changes made our CI fail due to it needing to run `go generate` to include one of the spelling fixes. So before I can merge this you need to include that commit.

**Comment by beyang** [comment]
> @keegancsmith I don't understand, can you please elaborate the process?

@kittenking We want you to get credit for these commits. However, (1) our process is to squash-merge commits and (2) @keegancsmith added [this commit](https://github.com/sourcegraph/sourcegraph/pull/5003/commits/5099779944a49b0225437ee2cc9e7e93371cad6e) on top of your branch to make our CI pass. If we squash-merge that branch, then Keegan would be marked as the author of the squashed commits. To ensure you receive credit, could you cherry-pick that commit (or merge the `spelling` branch from the upstream github.com/sourcegraph/sourcegraph repository into yours)? That way we can squash-merge this PR into upstream and you'll be marked as the author of the squash commit.

**Pull request closed without merging**
