### PR TITLE
Browser extension nightly DOM checks

### PR DESCRIPTION
**Pull request by eseliger**
This works on #7980
I added a new pipeline to Buildkite that runs on a schedule (every day at midnight) and failures are posted to #web, so we get notified. 
After we finally managed to fix the tests, this tests for DOM changes on github.com and gitlab.com (browser extension, not native integration).
For an example run see here: https://buildkite.com/sourcegraph/browser-extension-nightly/builds/1

TODO after merge: Need to set the target branch for the scheduled build to master

### CODE REVIEW

**Comment by felixfbecker** [comment]
Can we upload this coverage to codecov (under the `e2e` flag)? It won't exist for every commit of course but I don't think that should cause problems (I also saw some codecov.yml config for this that may help in case it does).

**Comment by felixfbecker** [comment]
Should probably not be blocking this PR though

**Comment by eseliger** [comment]
It would probably mess around with the coverage graph though, going up and down depending on whether the suite ran or not 🤔 
I'll add it to the tracking issue that we should figure out a solution

**Comment by felixfbecker** [comment]
I think this would do it: https://docs.codecov.io/docs/carryforward-flags

**Pull request merged**
