### PR TITLE
authz: various fixes to `PermsSyncer`

### PR DESCRIPTION
**Pull request by unknwon**
This PRs fixes two minor things:
1. Exclude site admins from the list of users with no permissions.
2. Fix wrong form of argument passed to `QueryContenxt`.
3. Set `dbconn.Global` synchronously.

Stacked on #8927

### CODE REVIEW

**Comment by tsenart** [comment]
The diff looks wonky. Let me know when it's good to review.

**Comment by unknwon** [comment]
@tsenart sorry about that, just fixed, please review :)

**Comment by lguychard** [comment]
It looks like @sourcegraph/web doesn't own any files here, removing the review request.

**Comment by unknwon** [comment]
@lguychard Sorry, was a merge/rebase mess from `master`.

**Pull request merged**
