### PR TITLE
Reintroduce ordering of auth providers

### PR DESCRIPTION
**Pull request by kopancek**
## Description

This PR reintroduces the changes that were reverted in 
- #50450

Also fixes a problem where I did not handle correctly the case when certain fields have zero value.

## Test plan

- [x] New unit test added for the fixed changes.
- [x] [main-dry-run can be seen here](https://buildkite.com/sourcegraph/sourcegraph/builds/213015)

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+2.12 kb) | 0.02% (+2.12 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/milan/order_login_items_again/compare-report.html;tab=live_object) for a full comparison between the commits ad691b3 and c9ddb0d or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by vdavid — APPROVED** [review]
Nice! I only looked at the second commit (the fix) as the rest was already reviewed. Makes sense, and thanks for the thorough testing!

**Comment by kopancek** [comment]
[Previous main-dry-run failed](https://buildkite.com/sourcegraph/sourcegraph/builds/212936), so I added some more changes and more unit tests to make sure this time it will succeed.

**Comment by willdollman** [comment]
This is one of a few PRs where the SonarCloud Code Analysis check is stuck on "Expected — Waiting for status to be reported". Seems to be a problem on either the github or sonarcloud end as [the check](https://sonarcloud.io/summary/new_code?id=sourcegraph_sourcegraph&pullRequest=50586) passed.

Hopefully it's a transient issue and will fix itself if the checks are rerun (pushing a new commit or rerunning them manually), but let me know if not.

**Pull request merged**
