### PR TITLE
compute: ensure streaming for dev

### PR DESCRIPTION
**Pull request by rvantonder**

### CODE REVIEW

**Comment by camdencheek** [comment]
Lol. Is this another "we thought we were streaming" situation?

**Review by camdencheek — APPROVED** [review]
LGTM. I pulled up the [original PR](https://github.com/sourcegraph/sourcegraph/pull/25635/files) to compare.

**Comment by rvantonder** [comment]
Nah, I was aware of this gotcha and did the thing in my feature branch, just upstreaming the change now before doing client side stuff. Also I'm not 100% sure I could reproduce the blocking but am fine just doing the conservative thing here and making sure it's open. Makes me wonder if `/.api/search/stream` also needs to be uncorked, but I'm not aware of clients using it in our dev environment.

**Comment by rvantonder** [comment]
Haha wait I just realized something I think... in that PR the conditional compression was factored out, but the code is still this on main:

> // Disable default DevServer compression. We need more fine grained compression to support streaming search.
 compress: false,

[link to code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f7b2939011066a56c1a5fbf5c790b69a9db1f885/-/blob/client/web/gulpfile.js?L112&subtree=true)

introduced in https://github.com/sourcegraph/sourcegraph/pull/25404.

Maybe this is why I didn't see stream blocking? Maybe we're doing the conditional thing, and then unconditionally not compressing still, so it's effectively a no-op?

Can you confirm @umpox ?

**Comment by rvantonder** [comment]
As far as dev server stuff goes it seems weird to do the `onBeforeSetupMiddleware` to disable compression without undoing the `compress: false,` addition in https://github.com/sourcegraph/sourcegraph/pull/25404 😄 @umpox to confirm. Gonna merge since we'll need this either way, esp if my observation is right.

**Pull request merged**
