### PR TITLE
Add community landing page for Backstage

### PR DESCRIPTION
**Pull request by jdorfman**
## Test plan

1. Go to `/backstage`
2. Make sure it loads
3. Run an example query

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.01% (+0.26 kb) | 0.08% (+11.18 kb) 🔺 | 0.09% (+10.92 kb) 🔺 | 0.14% (+1) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/jd/add-backstage/compare-report.html;tab=live_object) for a full comparison between the commits 0334636 and 01a97b6 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by Joelkw — APPROVED** [review]
Looks good! Thank you.

**Comment by jdorfman** [comment]
@Joelkw holding until you test it locally just to be sure.

**Review by novoselrok — APPROVED** [review]

**Comment by jdorfman** [comment]
Thanks @novoselrok

**Pull request merged**
