### PR TITLE
repo-updater: Drop repo trigger set_repo_name and unused repo columns

### PR DESCRIPTION
**Pull request by keegancsmith**
This trigger was part of a backcompat migration from a long time ago. It was
from when we renamed the URI column to Name column. It is no longer needed.

The indexed_revision columns are no longer used.

Test plan: unit tests

Part of https://github.com/sourcegraph/sourcegraph/issues/462
Fixes https://github.com/sourcegraph/sourcegraph/issues/644

### CODE REVIEW

**Comment by tsenart** [comment]
I feel like this would be a good chance to take care of https://github.com/sourcegraph/sourcegraph/issues/644 as well.

**Comment by keegancsmith** [comment]
> I feel like this would be a good chance to take care of #644 as well.

Pushed and updated title.

**Comment by tsenart** [comment]
Thanks. Is `pushed_at` sill populated / used?

**Comment by keegancsmith** [comment]
> Thanks. Is `pushed_at` sill populated / used?

:D will purge that as well.

**Pull request merged**
