### PR TITLE
Search contexts: context filter suggestions

### LINKED ISSUE #16363: Support context: keyword in the search frontend
Includes:
- Highlighting
- Autocompletion
- Hovers

### PR DESCRIPTION
**Pull request by novoselrok**
Show suggestions for context filter (backend currently only returns global and `@user` contexts).

Fixes #16363.

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]

**Comment by limitedmage** [comment]
How can I test this? I checked it out locally but when I press Ctrl+Space after typing `context:`, I get `No suggestions`. Do I need to run in `SOURCEGRAPHDOTCOM_MODE` for this to work? (Having issues with that right now)

**Comment by novoselrok** [comment]
> How can I test this? I checked it out locally but when I press Ctrl+Space after typing `context:`, I get `No suggestions`. Do I need to run in `SOURCEGRAPHDOTCOM_MODE` for this to work? (Having issues with that right now)

Yep, I have to set `SOURCEGRAPHDOTCOM_MODE=true` and `SRC_DISABLE_PROFILER=true` to get it to work.

**Review by limitedmage — APPROVED** [review]

**Pull request merged**
