### PR TITLE
Upgrade to node.js 16

### PR DESCRIPTION
**Pull request by eseliger**
Node.js 14 will transition into maintenance mode in 2 months. Also, node upgrades come with v8 upgrades, which in return bring us all the good new stuff in ECMAScript and performance improvements 😎
CI seems to pass, local dev works, so I guess we're good?

### CODE REVIEW

**Review by courier-new — APPROVED** [review]
Feels so easy... almost... **too** easy... 😂

**Review by umpox — APPROVED** [review]

**Review by vovakulikov — APPROVED** [review]
I think the 16 version also has arm64 support - Finally, I don't need to turn on the rosetta compatibility tool for running node js processes.

**Comment by keegancsmith** [comment]
@eseliger Do we need to be on 16.7, or can any 16.x work? Right now we are enforcing 16.7 or higher.

**Comment by eseliger** [comment]
Likely any can, but the ones below I didn't test if there's any quirks in there so something doesn't work or such. Do you think we should ease the constraint?

**Comment by keegancsmith** [comment]
just being lazy and was hoping we would support a version in my package manager (16.4.1). But easy enough to do a custom version.

**Pull request merged**
