### PR TITLE
code intel: Remove search context from search based code intel

### LINKED ISSUE #58006: "No hover information available" for search based code intel and custom search context
#### Steps to reproduce:

1. Go to https://sourcegraph.com/contexts, set a custom default context.
2. Open a link to a file in a repo that is not covered by the custom default context.
3. Hover over any token that triggers search based code intel.

#### Expected behavior:

See search based code intel information.

#### Actual behavior:

"No hover information available"

This is because the code intel search query includes the currently selected search context, which defaults to the default search context (obviously). This causes issues when opening links to repos that are outside this context.

https://github.com/sourcegraph/sourcegraph/assets/179026/669d9ce9-6abe-44fa-a16a-3f2b7e865fbc

### PR DESCRIPTION
**Pull request by fkling**
Fixes #58006 

Using search context is problematic when viewing a file/repo that is not part of the selected search context, which can happen when a custom default context is set.

It doesn't seem necessary to include the search context. The query I looked at now doesn't have the context set anymore. Example:

    ^append$ type:symbol patternType:regexp count:50 case:yes file:\.(go)$ repo:^github.com/sourcegraph/sourcegraph$ index:only

I wasn't able to verify all code paths though.

### Test plan

Hover over `append` in https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/own/resolvers/resolvers.go?L145:9 and see that the request doesn't contain a search context.

### CODE REVIEW

**Comment by olafurpg** [comment]
Tagging @keynmol @varungandhi-src for review instead of myself

**Comment by varungandhi-src** [comment]
> Using search context is problematic when viewing a file/repo that is not part of the selected search context, which can happen when a custom default context is set.

So should we avoid setting the search context only in the specific situation when a custom default context is set?

Consider the situation where someone navigated to a file with an explicit search context where the search is limited only to certain subdirectories (say because they work in a large monorepo). Then they perform a hover on a symbol. Is your point that for code intel, we should ignore their context and show results in other directories too for the sake of completeness?

**Comment by fkling** [comment]
@varungandhi-src

> Consider the situation where someone navigated to a file with an explicit search context where the search is limited only to certain subdirectories (say because they work in a large monorepo). Then they perform a hover on a symbol. Is your point that for code intel, we should ignore their context and show results in other directories too for the sake of completeness?

Yes, although it's less about completeness for me and more about predictably/reproducibility. E.g. in your scenario if I refreshed the page my default context would be set and I would get different search based code intel information. I think it's not obvious to users that their currently selected search context affects search based code intel results and that it's not too difficult to get into a situation where this can even lead to "not results".

**Review by varungandhi-src — APPROVED** [review]

**Review by camdencheek — APPROVED** [review]
Looks good to me! Thanks for the find and the fix

**Pull request merged**
