### PR TITLE
Do not use knobs outside of stories

### PR DESCRIPTION
**Pull request by felixfbecker**
Knobs must be called inside stories.
When calling them globally, it leads to race conditions between stories and knobs are wrong.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Actually, doesn't seem to fix it. Still seems worthwhile to merge though.

**Review by eseliger — APPROVED** [review]
LGTM I think I do the same for campaigns btw 😁

**Comment by felixfbecker** [comment]
> I think I do the same for campaigns btw 😁

I went through all campaigns stories and didn't see any problematic uses

**Comment by eseliger** [comment]
[That one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/enterprise/campaigns/apply/CampaignApplyPage.story.tsx#L53:1-53:5) seems similar? 

Not sure though

**Review by eseliger — APPROVED** [review]
Nice. Is it fixed now?

**Comment by felixfbecker** [comment]
No, the bad knobs are from OptionsPage.story.tsx, which I had fixed in the original commit.

**Pull request merged**
