### PR TITLE
Implement container wildcard component for redesign

### PR DESCRIPTION
**Pull request by eseliger**
Implements the new container component designed in https://github.com/sourcegraph/sourcegraph/issues/20177.

I have converted some pages locally to the new container and so far I was able to achieve what is in the designs, so I would consider this component "usable" at this point. I will create PRs using it in a follow-up though, so it's easier to review and get approved.

### CODE REVIEW

**Comment by 5h1rU** [comment]
Is there a difference between this and Page component? https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/components/Page.tsx

**Comment by eseliger** [comment]
> Is there a difference between this and Page component? https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/components/Page.tsx

The difference is that the container is non-opinionated and really just provides a grouping mechanism for UI elements. It has no `. container` set and adds the visual "white box" in the redesign, which we will be using in various places. 
I think `Page` should only be used _once_ per page (lol), while there can be multiple `Container` elements in one view at a given time. See the screenshot in the PR description for how the white box around it looks like. It won't change the behavior in non-redesign environments, for now.

**Comment by rrhyne** [comment]
This seems like it might be better served by a card component?

**Comment by felixfbecker** [comment]
I agree, what's the difference between this and a `card`?
Having both `<Container>` and `.container` may also be confusing

**Comment by eseliger** [comment]
> This seems like it might be better served by a card component?

We talked about this and I was confused by the designs. What you see in the screenshot above should have been a _card_. A container is used in pages where we wrap stuff together.
The difference to a card is the padding, that it only has an effect when the redesign is enabled, and the semantic meaning, so I think having it exposed as an additional wildcard component makes sense.
We currently call it a `Container` in the design, @rrhyne should we rename it? I was not confused by `.container` and `Container`, but maybe others would be. 

I will update the example and add an explanation to the components story, so it is more clear what this is supposed to do.

**Comment by rrhyne** [comment]
I think container is the correct name. Lets educate instead of rename?

**Review by limitedmage — APPROVED** [review]

**Review by rrhyne — APPROVED** [review]
Lgtm!

**Pull request merged**
