### PR TITLE
Keyboard navigation support for search results page

### PR DESCRIPTION
**Pull request by novoselrok**
Adds support for keyboard navigation on the search results page.

## Demo

https://user-images.githubusercontent.com/6417322/203963778-dae0d178-fc6d-4378-8ebf-43ca074ccf90.mp4

## Test plan

* First, enable the feature flag by going to the `/site-admin/feature-flags` page and create the `search-results-keyboard-navigation` flag
* Open Sourcegraph homepage and do a search
* On the search results page
  * The first result should be automatically selected
  * Pressing Arrow up/down or j/k should move the selection up/down
  * Pressing Arrow left/right or h/l should collapse/expand file match groups
  * Pressing alphanumeric characters while focused on a search result should show a message which informs the user to press `/` to focus the search input
  * Pressing CMD/Ctrl + Arrow down should focus the first result
  * Pressing Enter should navigate to the result
  * Pressing CMD/Ctrl + Enter should open the result in a new tab
  * When collapsing a file matches group, it should select the last visible result if the previously selected result is not visible anymore.

## App preview:

- [Web](https://sg-web-rn-search-results-keyboard.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.15% (-4.41 kb) | 0.02% (+2.98 kb) | 0.06% (+7.40 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/rn/search-results-keyboard-navigation/compare-report.html;tab=live_object) for a full comparison between the commits a5285bd and 9659e7c or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by olafurpg — APPROVED** [review]
@novoselrok thank you so much for doing this PR! I love this new workflow for searching ❤️ A few notes that can be addressed separately:

* It would be nice if the focused result is persisted across the sequence of steps: press enter to open result, go back in browser history to search page again. Currently, the focus reverts to the top result making it cumbersome to iterate through results that are not at the top.
* Probably unrelated to this PR, but the search bar gets auto-focused when opening a search result with the steps: type query, press enter to trigger search, press enter to open first result, press Cmd+ArrowLeft with intention to go back in browser history but it moves the cursor instead inside the search bar because it's autofocused. This auto-focus makes it difficult to iterate quickly through the results with the keyboard alone.
* Minor thing, but if I press `Tab` then the focus moves to the code host icon and the up/down arrow keys stop working. I need to press `Tab` six times again to focus on the next search result (or shift-tab to go back). It would be nice if I can use up/down arrow keys to focus on the next search result even if focus is on other result-related elements like the repo name. CleanShot 2022-11-29 at 10 42 00
* Unrelated to this PR, but we should really get on-demand syntax highlighting working with the new blob view because it makes the workflow much faster when iterating through results with the keyboard.

**Comment by olafurpg** [comment]
> Pressing Arrow left/right or h/l should collapse/expand file match groups

I love this feature 👍🏻

**Comment by quinnkeast** [comment]
I am super excited that we've almost got this in the product!

I've explored the behaviour locally while thinking about the overall system we're finally getting in place with [RFC 345](https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#), and I have some changes in mind that would make it overall more predictable / consistent as a sytem.

- [Loom video](https://www.loom.com/share/6e98c5677c0f4834b115eabee572d3c2)
- [Figma link](https://www.figma.com/file/SFxkUErsZNYDPQZMG8nBK6/%2319021-%E2%80%93%C2%A0Keyboard-navigation-underpinnings-audit?node-id=1824%3A174&t=q8V30pMT9oNeIx8n-1)

**Proposed changes:**

- A "search result" should be considered a single "item." At the top-most level, a user should always be able to switch between active search result items. `j` and `k` make sense as single-key shortcuts to move between search result items.
- On the search results, when no result is selected, pressing `j` should make the first search result active.
- When a search result item becomes "active," focus should always be given to the link to source in the result header (e.g. the repo for a repo result, the file for a file result, etc). 
- The above two points are changes to the current behaviour to solve two problems:
  - Sometimes focusing on the header, and sometimes focusing on the first code block, creates unpredictability. Moving from search result to search result should always be predictable.
  - Moving from search result to search result, no matter how many code blocks may be in the result, will make navigation through search results faster.
 - When the link in the header is focused, `left` and `right` arrow keys / `tab` and `shift`+`tab` should move between header items.
 - When a search result item is active, `down` and `up` arrows / `l` and `h` should move through code blocks within that search result item. (The `l` and `h` shortcuts make logical sense as additional shortcuts so that the user doesn't need to move much on the keyboard while quickly going from search result → specific code block.)
 - While a search result item is active, a single key such as `e` should **toggle** showing or hiding additional results.

From your original notes:

- The first result should be automatically selected → **Yes!**
- Pressing alphanumeric characters while focused on a search result should show a message which informs the user to press / to focus the search input → **Nice!**
- Pressing `Enter` should navigate to the result → **According to which element within the result is focused**
- Pressing `CMD/Ctrl` + `Enter` should open the result in a new tab → **Similar to the above, according to which element is focused**

**Comment by felixfbecker** [comment]
(I left a [comment on the Figma](https://www.figma.com/file/SFxkUErsZNYDPQZMG8nBK6?node-id=1819:81#316916025) too with similar thoughts)

@quinnkeast it seems like yo're proposing to make the search results a _widget_ with strict keyboard control and <kbd>tab</kbd> overrides (only arrow keys). I wonder if we're trying to forcefully shoehorn this area into a widget role in a way that doesn't really make sense.

The pattern for widgets would be that the widget itself is focused and usually only a selection moves within. The widget itself has a focus outline and <kbd>tab</kbd> will move to the next focusable after the widget.

What I'm asking myself is: If I try to apply that to the search results, where would that outer focus outline go? There isn't really a "box" here containing the search results, the search results are kind of intentionally designed to look like free-floating main content. 

Considering that, having <kbd>tab</kbd> move focus to the _next_ widget as opposed to _within_ this area seems rather unintuitive. If we do use normal focus within the results area, arrow left/right keys moving focus between two side-by-side links also doesn't seem intuitive or beneficial over <kbd>tab</kbd>.

It feels like we're maybe overthinking the interaction pattern for the search results area.

What I'm leaning towards for the search results page is something more pragmatic, that actually basically is what @novoselrok implemented in this PR (which is a benefit for implementation complexity too):
- The search results area is just a landmark region, not a widget. You can jump to it (to the first result), but it's not focused itself.
- You can continue to use <kbd>tab</kbd> everywhere in the area
- Arrow keys (without modifier) are added _on top_ of <kbd>tab</kbd> support, jumping directly between results (skipping over the tabbable links in each result title). They simply move the focus.
  - But you _can_ use <kbd>shift</kbd>+<kbd>tab</kbd> after jumping to a result to move focus backwards into the result title, for example.
- <kbd>enter</kbd> etc simply work as default browser behavior for focused links

So this area would be a simple landmark region, but with keyboard controls _on top_, not a full widget.

@quinnkeast wdyt?

**Comment by fkling** [comment]
Is the result list a *feed*? https://www.w3.org/WAI/ARIA/apg/patterns/feed/

**Comment by quinnkeast** [comment]
I think you're correct that I'm proposing for each search result to be a widget in itself (and thus the "search results" represents a set of widgets), or at least something conceptually similar to a widget.

Without an approach along these lines, navigation isn't conceptually happening between "search results," but rather "all of the elements that appear on the search results view." For keyboard-driven navigation, having to go through each "element" instead of each "search result" feels like the wrong level of granularity.

I wouldn't want us to force it into a widget if that's the wrong type of implementation; unlike a widget where the containing widget receives _focus_ and provides internal _selection_, the idea here is that a given result item is _active_ while an item within has _focus_. What would best align with this?

>What I'm asking myself is: If I try to apply that to the search results, where would that outer focus outline go? There isn't really a "box" here containing the search results, the search results are kind of intentionally designed to look like free-floating main content.

A parallel here: the blob view may or may not be a widget, but the blob needs a visual state to indicate it's _active_ while elements inside will have _focus_.  This visual state doesn't have to the same explicit focus outline as everywhere else, because it conveys an active state, rather than a focus state. 

I was working with Tom on refining the visual styles around the blob / keyboard navigation, and one of the things that we'd landed (but apparently didn't get merged ahead of his leave) was a combination of style changes to convey when the blob is is active or inactive, without being visually disruptive like the blue outline. This in turn conveys where keyboard shortcuts would act within. Screenshots of basically what we'd landed on:

Blob not active:
CleanShot 2022-11-29 at 20 28 14@2x

Blob active:
CleanShot 2022-11-29 at 20 28 29@2x

I could see search results behaving similarly: an inactive result's "box" could have a slightly scaled back background, and when active, the "box" could then have the full-intensity background with a non-intrusive border. This, in combination with a prominent and visible focus outline, would convey what's happening where.

@fkling got a comment in while I was writing this, but I think the "feed" concept is actually closer to the intention here. I note that it says:

>The feed pattern is not based on a desktop GUI widget so the feed role is not associated with any well-established keyboard conventions. Supporting the following, or a similar, interface is recommended.

This would make the proposed pattern aligned with the intent of a feed.

All this being said said, if there's another approach that would solve the same problems (jump between search result items as a whole, navigate internally in a way that's consistent with how we'd implement similar navigation elsewhere in the product), I'd love to keep iterating on this line of thought!

**Comment by felixfbecker** [comment]
The comparison to `feed` is very interesting @fkling! I think this section particularly aligns with my thinking:

> a feed is a structure, not a widget. Consequently, assistive technologies with a reading mode, such as screen readers, default to reading mode when interacting with feed content.

I don't know if it should be an actual `feed` since it's not actually infinite, semantically it's more similar to Google or YouTube search results (note YouTube search results also has scroll-based pagination). But certainly seems like a good inspiration.

> I think you're correct that I'm proposing for each search result to be a widget in itself (and thus the "search results" represents a set of widgets), or at least something conceptually similar to a widget.

@quinnkeast When we say "search result", what do we mean? Is this a result? 

CleanShot 2022-11-29 at 11 58 20@2x

That's what I was thinking of, and so the keyboard shortcuts would be there to jump between these **results**. Declaring these "widgets" doesn't make as much sense, because they are already a `link` role with just one possible interaction, while a widget is composite.

Or do you consider a "result" as all the matches grouped for one _file_?

CleanShot 2022-11-29 at 12 00 08@2x

I feel like that adds a bit of needless hierarchy, because I imagine users care more about jumping between each match. In this case I would still not see an intuitive way where we would draw the visual "active"/focus boundary box.

**Comment by felixfbecker** [comment]
A whole another idea would be to consider it a `tree` (with non-collapsible nodes), given results are grouped by file. That adds the file headers into the focus/selection hierarchy and defines a widget role for the entire page.

That feels a bit of a misuse though and I'm still leaning towards @novoselrok's original simple model.

**Comment by quinnkeast** [comment]
>When we say "search result", what do we mean? Is this a result?

I'm glad you asked this, because I didn't realize we were thinking about it differently!

I think about it as it's represented in the UI:

CleanShot 2022-11-30 at 09 33 36@2x

For me, each code block is a subset of a search result.

It sounds to me like the real question we're asking is: do we want to enable users to jump between *search results* as a whole unit (as in my screenshot), or *matches* as individual units?

My thinking is that by jumping between search results as a whole unit, we represent jumping between the actual grouped UI unit on the page, enable further shortcuts specific to that unit, and better future-proof the system, because then it doesn't matter how a search result's design may change in the future, because conceptually it will still have the same bones and the keyboard navigation will jump from result to result.

If we're jumping between *matches* as individual units, there's two issues I worry about:

- What ends up being focused is inconsistent from result to result. For some search results, it'll be an element in the result header; for other search results, we're skipping the header and going directly to the first code block.



- Since code blocks are within a (file), it creates a level of hierarchy in the matches. If the user recognizes the file isn't a match to their search, then all of those code blocks are also not a match. If the actual result they're looking for is the fourth result, that could mean they have to jump 12+ times to get to the code block that _is_ what they're looking for, instead of 4 times. In other words, jumping between individual matches is likely cumulatively less efficient.

https://share.cleanshot.com/RjTdpy

**Comment by quinnkeast** [comment]
Update: I think there may actually be a path here that brings these two approaches together—when it comes to actually _using_ it (regardless of the implementation), we aren't talking about mutually exclusive ideas. I can sum what we're trying to do as:

- Provide a way to navigate between "matches" (what a user can follow to another page).
- Provide a way to navigate between "search results" (the whole UI unit).
- Provide a way to trigger shortcuts specific to a "search result" (e.g. showing or hiding more matches for that result).
- Make the combination of these things feel intuitive and frictionless.

It seems like we can do this by:

- Using arrow keys to navigate up and down through matches, including the header
- Using `n` and `p` (or whatever makes sense) and `cmd+down` and `cmd+up` to navigate up and down through search results
- Using an active state for whichever search result presently has the focus
- Giving focus to the header when navigating to the next search result, either with arrow keys or the next/previous result shortcut
 
I've brought these thoughts together in a Figma prototype.

- Here's a [Loom recording walking through it](https://www.loom.com/share/900e534f827546db83c177a9c7c3b423).
- Here's a [Figma prototype you can step through yourself]https://www.figma.com/proto/IGEsAryrJzJ9IyJ9IZh52b/Untitled?page-id=0%3A1&node-id=0%3A2065&viewport=731%2C-654%2C0.49&scaling=min-zoom&starting-point-node-id=0%3A2065] 

I assume this is incomplete/needs further specification for a11y, but it feels like we should be able to find a way to implement this effectively. What do you think?

**Comment by jjinnii** [comment]
Just passing by, I tend to agree with @quinnkeast that we should support the ability to navigate between search results, without having to arrow through every element on the search result page! This is for a couple of reasons: 

* Scalability. Outside of the search results page, most of our pages have some form of sections or panels; thinking through the ability to navigate through not just elements but some form of section/panel/widget/etc, I think is important. 
* Agreed that the UX of certain result types changing focus state is a bit confusing. If users aren't closely looking at what the result types are, it first comes across as inconsistent. 
* If users get unlucky and the first (or first few) results all have a few code blocks within the result before they get to a result that users care about, that's quite a more number of arrow presses. 😄 

That being said, I really like Quinn's most recent best-of-both-world solution! It doesn't make it a hard requirement that users navigate between results first, before being able to navigate within a search result, which I agree could be overly prescriptive.

**Comment by limitedmage** [comment]
@fkling alerted me to the existence of the [ARIA feed role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/feed_role), what do you think about following that and using the recommended keyboard shortcuts from that (page up/page down, and we can probably keep use of j/k)?

**Comment by novoselrok** [comment]
> @fkling alerted me to the existence of the [ARIA feed role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/feed_role), what do you think about following that and using the recommended keyboard shortcuts from that (page up/page down, and we can probably keep use of j/k)?

I think PgUp/PgDown will be awkward, given that none of my keyboards (Macbook + magic keyboard) have those keys 😄

**Comment by quinnkeast** [comment]
Agreed. A feed feels like a valid overall choice, but PgUp/PgDown aren't intuitive or usable. Thankfully, the specification there says that:

>The feed pattern is not based on a desktop GUI widget so the feed role is not associated with any well-established keyboard conventions. Supporting the following, **or a similar**, interface is recommended

**Comment by novoselrok** [comment]
@quinnkeast I adjusted the keybindings according to your latest comment. I did not implement everything because I didn't want the scope of this PR to get away from us.

* I added cmd+down/up and n/p to navigate between header links.
* arrow up/down now always includes header links (does not skip them for file matches)
* e toggles expanding/collapsing file matches
* When the focus is on the file matches header or file matches themselves, there is a gray border around the file matches container

**Comment by quinnkeast** [comment]
This feels **so good**. I cannot wait to start using it every day.

Non-blocking followups we should tackle in a separate issue(s):

- Left / right arrow key navigation between header elements.
- The ability to go up/down from other header elements, as @olafurpg identified.
- Persisting the focused result so that navigation from results → new pages → returning to results is faster, as @olafurpg identified.
- Removing autofocus (this will be important for the search input reboot at some point soon anyway).
- Visual refinements for the various focus states (what's in this PR works well enough that this isn't a blocker).

Is there any additional accessibility consideration/implementation needed around ARIA roles and such?

**Review by quinnkeast — APPROVED** [review]

**Comment by olafurpg** [comment]
I've tried the latest build locally and think the UX has one big regression compared to the original PR: pressing enter on the first content results now opens the file at line 0, not the line with search results. It's not obvious how to find the actual search results after after you've opened the file, you have to go back in history, press down to focus on the hunk and then enter.

CleanShot 2022-12-02 at 10 15 52

We should not treat the filename link above content matches as a search result, users can access it with the standard browser `Tab` navigation for the rare cases they want to reach this link (I personally find it mostly helpful to copy-paste the filename).

Another smaller considerations:

* We should consider removing the Cmd+Down/Up shortcuts because it's inconsistent with how those shortcuts are conventionally used: move to the top/bottom of a list, document, or page. If we keep the shortcut, then I'd expect it to focus on the first/last search result, which is tricky to implement when we support streaming results (but might be doable). 
* The `e` shortcut can be removed because we already support the same functionality with left/right and h/l. We should be conservative about adding adding non-arrow/non-enter/non-space shortcuts because they are difficult to teach so they must ideally follow very strong conventions from other apps AND provide exceptionally high user value (which I think is the case for the fuzzy finder shortcuts and `/` to focus on the search bar). Another important element for unconventional shortcuts is that they should ideally be universally enabled (one  common complaint with Cmd+K in the original fuzzy finder is that it was only active under repo pages and it wasn't obvious when it worked and when it didn't work).

**Comment by quinnkeast** [comment]
Regarding the regression: it sounds to me like this is more a problem with the link to the result (in the case of a file) not showing the matches when you go to the file. Take this result:

CleanShot 2022-12-02 at 11 07 03@2x

When going through the header link, I would expect the file to then show the matches, so that the "act of searching" is carried through to the file itself.

That said, I don't see why we couldn't have the header link take the user to the first match for the time being, if the "copy path" action remains the same.

>We should consider removing the Cmd+Down/Up shortcuts...

@novoselrok any thoughts here? I'm not against it given we have another set of keys in `n` and `p` for achieving "jump to next/previous result," it just means users won't be able to keep their hands on the arrow keys while doing so.

>The e shortcut can be removed because we already support the same functionality with left/right and h/l. 

I disagree with this. A couple of points:

- The system we're defining for keyboard interactions [RFC 345](https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#) affords that an "active" UI element can capture shortcuts specific to that element. This will be more and more important as part of the overall system. Here, `e` is only available when a search result is active, and provides specific functionality in that moment.
  - This contradicts _"important element for unconventional shortcuts is that they should ideally be universally enabled."_ If that's the case, then we're very limited in what shortcuts we can provide, because they must be univerally unique across the app. Whether or not a shortcut should be universally enabled is connected to the **functionality they enable**, not the **form of the shortcut**. The fuzzy finder, as an example, is functionality that should be universally available.
- We can surface the shortcut to "toggle" showing and hiding more results in the UI more easily than we can surface two distinct shortcuts (← and → depending on current state).

**Comment by novoselrok** [comment]
At this point, I wouldn't want to derail the discussion any further. We need to put this in the hands of Sourcegraphs on S2, let them evaluate, and we can incorporate the feedback before GA-ing the feature. We'll have to collect feedback anyways, so let's do it sooner rather than later. I think we need to be pragmatic here and go with what the majority is comfortable with rather than finding a one-size-fits-all solution.

**Comment by felixfbecker** [comment]
Agree with merging!

Just want to respond to https://github.com/sourcegraph/sourcegraph/pull/44806#issuecomment-1331825708 @quinnkeast, because I think there are some useful principles we should think about for other contexts too (like blob navigation).

> It sounds to me like the real question we're asking is: do we want to enable users to jump between search results as a whole unit (as in my screenshot), or matches as individual units?

> Since search results are inherently a hierarchical structure, code blocks there's an implicit level of hierarchy in the overall search results. All matches are not equal; if the user recognizes the file represented by a result isn't a match to their search, then all of the code blocks within that result are also not a match. This means that if the actual thing they're looking for is a code block within the fourth search result, that could mean they have to jump 12+ times to get to the code block that is what they're looking for, instead of 4 times. In other words, jumping between individual matches is likely cumulatively less efficient.

I think we generally should be **pragmatic** with keyboard shortcuts.

I think that users don't actually think of search results as a hierarchical structure, but really just want a way to cycle through matches directly. As a user, a bottom match in a file could still be what I want even if a match at the top wasn't what I was looking for, the fact they're in the same file doesn't really change the evaluation. I still need to go through every result. They are actually more often equal to me as a user than not. The file name is really just metadata _for display_, less something I interact with.

And since result groups have a low UI limit (with "Show more" button) I think it'll never be that many matches to skip over that it would become annoying – I think it will feel quite fluid and natural to just hit <kbd>↓</kbd><kbd>↑</kbd> in quick succession, compared to switching to the <kbd>⌘</kbd>+<kbd>↓</kbd><kbd>↑</kbd> combo intermittently.

I also don't find it useful to have the file name part of this cycle sequence (if it's not a path result), because going to the first match is effectively the same as going to the file directly, it just goes to a different line instead of line 1. If I ever want to go to line 1 (it would be very rare), I can just scroll up afterward. I agree with @olafurpg:

> We should not treat the filename link above content matches as a search result, users can access it with the standard browser Tab navigation for the rare cases they want to reach this link (I personally find it mostly helpful to copy-paste the filename).

The fact that this would be inconsistent with path results doesn't really bother me as a user, because in that case the file is obviously what I would want to navigate to. As a user I'm more after something _sensible_ than something "structurally correct".

**The second principle** I think we need to think about is that **it's hard to teach and remember keyboard shortcuts, so the highest priority should be assigned to optimizing the experience of the most intuitive/basic keyboard shortcuts, which are usually the arrow keys** (or sometimes <kbd>tab</kbd>).

Bindings for vim-style navigation are great for vim users, but they are added on top and can never replace arrow key navigation, arrow key navigation always needs to work well.

Even <kbd>⌘</kbd>+<kbd>↓</kbd><kbd>↑</kbd> is nice for power users (besides @olafurpg's valid point that it's unconventional), but we need to assume most users will not learn about that modifier or remember it. They will likely just try the arrow keys, see they work, and always use those.

What that means is we really need to optimize the default arrow key experience, and for example still try to minimize the number of unnecessary focus steps, like the file header. It's nice to have <kbd>⌘</kbd>+<kbd>↓</kbd><kbd>↑</kbd> on top to hop between result groups, but we should assume most people just use normal arrow keys.

We also should, I think, try to avoid adding additional steps to "enter" and "exit" widgets  (with <kbd>⏎</kbd> and <kbd>esc</kbd>) if not necessary as was proposed in the chart navigation proposal because that is yet another keyboard control a user needs to learn and we need to teach before they can use the UI with a keyboard. It's always better if a user can just land in a widget with tabbing and immediately start using it with arrow keys, then <kbd>tab</kbd> out of it again.

Another way to say this is: **Avoid introducing/exposing hierarchy in the keyboard controls if it's not absolutely necessary** (because it adds more mental complexity and more keybindings to learn). E.g. the file tree obviously needs hierarchy, but the search results do not really, the blob view doesn't (flat 2D token navigation is better than nested navigation where you first focus the line, then the tokens within the line), charts don't strictly need it either.

**Comment by quinnkeast** [comment]
I agree with the principles you're proposing, even as I interpret their application a bit differently. For example, in relation to the principle:

>Avoid introducing/exposing hierarchy in the keyboard controls if it's not absolutely necessary

I believe hierarchy is already and inherently present in keyboard controls: consider the use of `Cmd+C` and `Cmd+Shift+C` – these are hierarchical in that they expand the base command to do a related, but "deeper," action.

> We also should, I think, try to avoid adding additional steps to "enter" and "exit" widgets (with ⏎ and esc) if not necessary

I agree strongly with this.

As to the focus behaviour/between-results navigation/etc.: at this point I'll disagree and commit. Please go ahead and make changes to the behaviour as described.

**Pull request merged**
