### PR TITLE
home: update total number of searchable repositories

### PR DESCRIPTION
**Pull request by unknwon**
According to our [gitserver_repos and external_service_repos table](https://console.cloud.google.com/bigquery?sq=527047051561:c471943b73c74b6bb5675b168e0dba9c) on Cloud, we are actually having 5M+ repositories cloned.

## Test plan

Text change.

### CODE REVIEW

**Comment by rafax** [comment]
While it seems we have more repos than we mention, I'm not 100% sure we want to publicly "advertise" that - it sets the expectations higher + I'm not 100% sure if the query counts everything correctly (ex. doesn't count duplicates across different external_services).

**Review by limitedmage — APPROVED** [review]

**Comment by limitedmage** [comment]
Maybe @sourcegraph/search-core  can also double-check that we want this "advertised".

**Review by stefanhengl — COMMENTED** [review]
Historically, this number comes from the number of indexed repos. At some point we stopped displaying the number of searched repos (actually we hid it behind a tooltip) on the search results page and just updated the number here once we reached the 2M indexed repos for the first time.

As of today, we have 2.9m (and rising) repos in our index, you can follow the numbers here: 
https://sourcegraph.com/-/debug/grafana/d/zoekt/zoekt?orgId=1

Changing the message to 5M+ changes the semantics, which is ok , we just have to agree on what that number actually means.

**Comment by unknwon** [comment]
> Changing the message to 5M+ changes the semantics, which is ok , we just have to agree on what that number actually means.

My observation is that the message we have is for "open source repositories", not explicitly mentioning indexed.

**Comment by jjeffwarner** [comment]
I'm inclined to stay with the indexed count. I think a fast search across 2.9M indexes repos is a better user experience that a slow search across 5M repos.

**Comment by unknwon** [comment]
> I'm inclined to stay with the indexed count. I think a fast search across 2.9M indexes repos is a better user experience that a slow search across 5M repos.

Thanks for the input, I'd also like to be on the conservative side this time, pulling off.

**Pull request closed without merging**
