### PR TITLE
Improve FilteredConnection summary for redesign

### PR DESCRIPTION
**Pull request by eseliger**
| **Before** | **After** | 
| --- | --- |
| image | image |

Requested by @rrhyne, because it was too hidden at the end of the list before.

### CODE REVIEW

**Comment by rrhyne** [comment]
Looks great. Merge whenever from a design perspective.

**Review by rrhyne — APPROVED** [review]
Looks great.

**Comment by umpox** [comment]
@eseliger This will cause regressions on 'compact' versions of FilteredConnection, e.g. the revisions selector

Before
image

After
image

Would it be possible to scope these changes only to `--noncompact`?

**Comment by eseliger** [comment]
Oh yeah! I forgot we had the compact thingy 🙈 Will do :)

**Comment by eseliger** [comment]
After talking to @umpox, this component feels to brittle to change globally. I am instead going with an explicit approach, I'll open up for review again once done.

**Review by umpox — APPROVED** [review]

**Pull request merged**
