### PR TITLE
Search jobs: add limit job

### PR DESCRIPTION
**Pull request by camdencheek**
This adds a new `LimitJob`, which cancels its child job when the result
count sent down its stream is hit.

Stacked on #30076

### CODE REVIEW

**Comment by rvantonder** [comment]
didnt check why build fails but I'm sure you'll sort that

**Comment by rvantonder** [comment]
(oraube this draft PR is defunct?)

**Comment by camdencheek** [comment]
Not defunct, just getting unexpected, reproducible failures in the backend integration tests. Something about too many and-ed files.  Not sure why yet, thus the draft status 🙂

**Comment by rvantonder** [comment]
Ah sorry I found my way here from a reference in the stacked PR. Will ignore till ready

**Comment by camdencheek** [comment]
This is weird. I can't reproduce the failure locally, but it is consistently failing in CI

**Comment by camdencheek** [comment]
Closing for a more focused PR in #30122

**Pull request closed without merging**
