### PR TITLE
docs: add jq installation to local setup

### PR DESCRIPTION
**Pull request by bobheadxi**
very minor but since `jq` is used in the NVM setup instructions, might be good to have this included in the big list of things to `brew install`?

### CODE REVIEW

**Comment by bobheadxi** [comment]
@nicksnyder I've updated the ubuntu section to use jq as well in d5229f7

Also, do I need to fill out the CLA form from the bot? It doesn't seem mentioned in the handbook

**Comment by nicksnyder** [comment]
You don't need to sign the CLA. Not sure why it asked. Had you already accepted the invite to the Sourcegraph org when you opened the PR?

**Comment by bobheadxi** [comment]
> Had you already accepted the invite to the Sourcegraph org when you opened the PR?

🤔 Yep - also this change is from a branch inside the repo (and not a fork), so it seems I have write permissions and all

**Comment by eseliger** [comment]
> You don't need to sign the CLA. Not sure why it asked. Had you already accepted the invite to the Sourcegraph org when you opened the PR?

That's a bug in the CLA bot, it doesn't refresh the list of org members regularly but only on startup..

**Pull request merged**
