### PR TITLE
own: guard resolver endpoints by feature flag and implement NodeByIDFunc for ingested files

### PR DESCRIPTION
**Pull request by leonore**
follow-up on leftover comments in https://github.com/sourcegraph/sourcegraph/pull/48182

## Test plan

Manually tested:

```gql
mutation add {
  addCodeownersFile(input: {fileContents: "* @leonore", repoName: "github.com/sourcegraph/sourcegraph"}) {
    id  
    repository {
      id 
      name 
      diskSizeBytes
    }
  }
}

query list {
  codeownersIngestedFiles(first: 2) {
    totalCount
    nodes {
      id
    }
  }
}
```
Manual tests made me notice it wasn't clear when an error came from unmarshalling repository ID so added a wrap there!

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
Might be good to have some unit tests for these resolvers eventually🙂

**Comment by leonore** [comment]
> Might be good to have some unit tests for these resolvers eventually🙂

@eseliger yep, I can add them with this PR, especially since the tests are failing- unless we want this landed quickly, in which case I'll open a issue + separate PR.

**Comment by eseliger** [comment]
no rush, either way works :)

**Review by cbart — APPROVED** [review]

**Comment by leonore** [comment]
opened a draft ticket on the board to tackle this while I focus on getting the last MVP critical bits in

**Pull request merged**
