### PR TITLE
E2e tests: wait for external service to be added

### PR DESCRIPTION
**Pull request by chrismwendt**
Fixes the e2e test error from https://buildkite.com/sourcegraph/sourcegraph/builds/31724

### CODE REVIEW

**Comment by keegancsmith** [comment]
Can you post the video here once CI has run?

**Comment by chrismwendt** [comment]
Sure can 👍

**Comment by chrismwendt** [comment]
Go to https://buildkite.com/sourcegraph/sourcegraph/builds/31742#91e7f7cc-4590-4e3f-b12a-f08af91ff6a3 then click on the mp4 (external service creation happens at ~0:16)

image

**Comment by keegancsmith** [comment]
That was the first time I watched our e2e video! Its awesome! I used to work on the e2e infra at FB and the videos werent as cool. FB's tests were more self contained so the videos were quick. But watching everything in one go jump all over the place is so fun.

**Pull request merged**
