### PR TITLE
release/bug: generate a new stitched migration graph

### PR DESCRIPTION
**Pull request by DaedalusG**
This will correct6 upgrade path for mvu plan creation

## Test plan

CI test

### CODE REVIEW

**Review by Chickensoupwithrice — APPROVED** [review]

**Comment by jhchabran** [comment]
@clabot check

**Comment by jhchabran** [comment]
@clabot check

**Comment by jhchabran** [comment]
@clabot check

**Comment by jhchabran** [comment]
@cla-bot check

**Comment by Chickensoupwithrice** [comment]
@cla-bot check

**Pull request merged**
