### PR TITLE
clean up internal api

### PR DESCRIPTION
**Pull request by camdencheek**

### CODE REVIEW

**Comment by camdencheek** [comment]
@eseliger I went through some of the internal endpoints and deleted ones that don't seem to be used, but I don't have a lot of confidence that they're not used outside the `sourcegraph/sourcegraph` repo. For example, `/search/configuration` is only used by zoekt. Any ideas to more confidently determine whether these endpoints are used?

**Comment by eseliger** [comment]
Hmm not so much. My best bet was checking for references on the apiclient methods. But as you said, zoekt hits one of those as well. 
Maybe we can try to find all that don't have references and then we post publicly that every team should check out this PR briefly?

**Comment by camdencheek** [comment]
>  My best bet was checking for references on the apiclient methods

Yeah, that's what the removed ones in this PR are. But we have quite a few endpoints that don't seem to have methods associated with them, and at least a couple I saw that are referenced outside of the sourcegraph repo (like in zoekt). 

> Maybe we can try to find all that don't have references and then we post publicly that every team should check out this PR briefly?

That seems reasonable to me. I feel like if we don't do something like that, the internal API will continue to bloat with unused code.

**Comment by eseliger** [comment]
Yeah same. Also it's currently very hard to tell what the frontend is being talked to for.

**Pull request closed without merging**
