### PR TITLE
Cody: Filter duplicate context files

### LINKED ISSUE #53652: Cody shows duplicate files in context
For most Cody interactions in the VS Code extension, I am seeing it claim to have read some files multiple times:

image

### PR DESCRIPTION
**Pull request by deepak2431**
This PR closes #53652.

## Test plan

I tested it manually, and it shows the correct response without any duplicates.
Attached screenshot of the results:

Before:
iScreen Shoter - Code - 230619154919

After:
iScreen Shoter - Code - 230619154941

### CODE REVIEW

**Comment by deepak2431** [comment]
@abeatrix @philipp-spiess Can I have a review, please?

**Review by philipp-spiess — APPROVED** [review]
LGTM, thanks! Do you mind adding a change log entry while I run tests?

**Comment by deepak2431** [comment]
@philipp-spiess Thanks for the quick review. I have added the changelog. 
I think you need to restart the tests again, as my recent commit to changelog has restarted the tests.

**Comment by philipp-spiess** [comment]
@deepak2431 Did you validate that in the case of duplicate links we _do not include the same context in the prompt twice_? I was just thinking that we should probably fix the underlying issue that creates multiple duplicates instead of fixing the symptom in the UI to avoid other issues downstream (like the one I outlined)

**Comment by deepak2431** [comment]
> @deepak2431 Did you validate that in the case of duplicate links we _do not include the same context in the prompt twice_? I was just thinking that we should probably fix the underlying issue that creates multiple duplicates instead of fixing the symptom in the UI to avoid other issues downstream (like the one I outlined)

@philipp-spiess No, I didn't validate that because I thought of it as a server response issue in which it is mentioning the files. As if that would be the case if we are including the same prompt twice Cody's response would also be affected but that's not the case.
Anyway, let me check that and update you here!

**Comment by philipp-spiess** [comment]
@deepak2431 Yeah I think what I feared is true 😬 

We'll need to fix this in the `local-keyword-context-fetcher.ts`: 
Screenshot 2023-06-19 at 15 16 00

**Comment by philipp-spiess** [comment]
@deepak2431 I’m glad that my comments are helpful. Thank you so much for all these fixes ❤️

**Comment by deepak2431** [comment]
> @deepak2431 I’m glad that my comments are helpful. Thank you so much for all these fixes ❤️

@philipp-spiess Always!

For the issue we discussed, I have figured out the cause of why the context of the same file is sent to the prompt multiple times. Consider the query "Write me the test to perform the e2e test", so when we are using this type of query or any other, the LLM context fetcher adds the same file searched for different keywords twice. So, for the term `test` it identifies the file `A, B`.  Again, for the `e2e test`, if the identified file is `A, B.` So, because of this now there are two copies each of `A and B` so we have duplicates received as a result of it.

Going to fix it and update the PR soon.

**Comment by philipp-spiess** [comment]
@deepak2431 Thanks for looking into it. This makes sense yeah. I think it's fine if we move the unique filter from the renderer into `local-keyword-context-fetcher` and then, I think the rest makes sense as-is, we should just make sure that we don't include the same result twice.

**Comment by deepak2431** [comment]
@philipp-spiess I have implemented the same solution which you suggested here. I have added the filtered method [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody/src/local-context/local-keyword-context-fetcher.ts?L110) before creating the message pairs, but it's not working. 
I might be wrong, but getting a sense that there are some other bugs too.

**Comment by philipp-spiess** [comment]
@deepak2431 Do you mind to push your changes? This is kind-of a high profile bug we want to iron out so if you can push this and allow me to maybe commit into your PR we can maybe squash this one a bit sooner :)

**Comment by deepak2431** [comment]
@philipp-spiess For sure, you can take this forward. I will follow up on this PR to see what the bug was and the solution that worked.
For now, I was looking into this method [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-shared/src/chat/transcript/index.ts?L154)

**Comment by philipp-spiess** [comment]
@deepak2431 Thanks! Can reproduce, it seems that there are more steps before that we all need to make sure are unique results. Looking into it :)

**Comment by philipp-spiess** [comment]
@philipp-spiess Ohh so I noticed that we have a bunch of more codepaths that didn't properly unique the list but also it seems that the current file might be added as context now which it wasn't before so this is something I need to still fix

I also fixed some other issues in this PR. Dinner now, might check back in later to fix the last issue or otherwise tomorrow morning

**Comment by deepak2431** [comment]
@philipp-spiess Great, Looked over your recent commit, and the fixes make complete sense. Good to handle the case of opening binary files too. Take your time to fix the left fix of this issue.

Just a thought, as we should check later if there's any case that this kind of behaviour can originate from other parts of the codebase.

**Comment by philipp-spiess** [comment]
@deepak2431 With the last change I think I've removed all duplicated-context problems :) I also confirmed that the current file content is still being added.
 
Screenshot 2023-06-19 at 21 03 52

**Comment by deepak2431** [comment]
@philipp-spiess I looked over the code by taking a pull, and it looks good. But on testing, I am still getting the duplicates:


iScreen Shoter - Code - 230620005107

**Comment by philipp-spiess** [comment]
@deepak2431 argh what. Which file did you have open for that query? And was that a repo with or without embeddings?

**Comment by philipp-spiess** [comment]
@deepak2431 Do you mind including the (verbose) request log so we know what's added to the context?

**Comment by deepak2431** [comment]
I have opened a` localstack `project, which is embedded. Also, see this SS when I am trying to see the prompt messages in log which are being sent out there are duplicate files in it but with different content:
iScreen Shoter - Code - 230620005702

**Comment by philipp-spiess** [comment]
@deepak2431 The fixed I added were only for local keyword context, I suppose we have to employ a same unique check somewhere in the embeddings search code.

**Comment by philipp-spiess** [comment]
@deepak2431 I suppose we have to do a unique check after this: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ps/os/53553-2/-/blob/client/cody-shared/src/codebase-context/index.ts?L121%3A1-122%3A1 

It's getting quite late for me so I think I'll look into this tomorrow if you don't get to it. Thank you for your help trying to decipher all of this!

**Comment by deepak2431** [comment]
@philipp-spiess No problem. yeah, the other reasons for duplicates are caused by there. I will add the unique method there and update this PR so you can check in the morning if it's all good, and then we can do a final test for all of this.

Thanks for making the fix to the local-keyword-context.

**Comment by deepak2431** [comment]
@philipp-spiess I added the unique method there, but it doesn't work. Both the contextFiles and the prompt have duplicate. Maybe we can try adding [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-shared/src/chat/transcript/index.ts?L179)

But I think this won't be a good fix as the main thing I can notice is that in the prompt message, the content is different when the files are the same. So, if we restrict the results by not passing extra details of the user query they won't receive a better response from Cody. We might need to look around a bit more and see if there are other places duplicates can occur.

**Comment by deepak2431** [comment]
@philipp-spiess I have added a filter in this [commit](https://github.com/sourcegraph/sourcegraph/pull/53662/commits/8b76c54029c4ec2ba665dc0639e41b8ae93c7c9a) that fixes the other issue. When we get the context files from the truncated messages, the same file with different content can be added twice, causing duplicate files. So, adding a filter there fixes that.  Do have a look, and LMK what you think?

iScreen Shoter - Code - 230620102517

**Comment by philipp-spiess** [comment]
> @philipp-spiess I have added a filter in this [commit](https://github.com/sourcegraph/sourcegraph/pull/53662/commits/8b76c54029c4ec2ba665dc0639e41b8ae93c7c9a) that fixes the other issue. When we get the context files from the truncated messages, the same file with different content can be added twice, causing duplicate files. So, adding a filter there fixes that. Do have a look, and LMK what you think?

Gotcha, yeah I think in that case it's very much expected that we do push different snippets into the prompt so I think I'd revert that. It is however confusing if the UI just shows two identical file paths. So what if we remove your last addition and instead bring back the UI client side check in the React component as an additional guard?

**Comment by philipp-spiess** [comment]
I'll be looking into this and update your PR if you don't mind :)

**Comment by philipp-spiess** [comment]
@deepak2431 Okay this seems like it works well now, wdyt @deepak2431?

**Comment by deepak2431** [comment]
@philipp-spiess Agreed with you that it would be good a add check on the UI side instead of adding multiple filters for search results, embedding messages etc. As the same file always have a different content context.

I will take a pull and do a final test here now!

**Comment by deepak2431** [comment]
@philipp-spiess This looks all perfect to me. We are good to go here as the primary fix of the local-context fetcher we took care of which was vital as it can affect other results too. And the other one can be handled by the UI check we added.

It was nice collaborating with you on this PR, as I didn't expected the reported bug to be caused by some of the core logic and be this challenging 😅

**Comment by abeatrix** [comment]
@deepak2431 @philipp-spiess do you know what recent changes caused this behavior that I can take a look?

**Comment by philipp-spiess** [comment]
@abeatrix I think it's that plus Beyang's changes that now combines multiple local context providers and passes that through the LLM to rank.

**Pull request merged**
