### PR TITLE
dev: remove nginx

### PR DESCRIPTION
**Pull request by keegancsmith**
We already have Caddy running for HTTPS support. We can use just Caddy
to remove the need to have nginx in our dev environments. This does mean
we won't be using the same reverse proxy as we do in production and for
customers. However, I do not think that changes much in practice.

This was inspired by a conversation I had with @mrnugget. Not completely sold on the idea though after implementing the change (especially since we have caddy -> webpack -> caddy -> frontend now).

@felixfbecker is this still an issue for you? https://github.com/sourcegraph/sourcegraph/pull/10021

### CODE REVIEW

**Comment by slimsag** [comment]
> This does mean we won't be using the same reverse proxy as we do in production and for customers.

Production/customer environments run various reverse proxies:

- Managed instances: Google Cloud Load Balancer
- Kubernetes: k8s ingress OR nginx-svc
- Docker Compose: Caddy
- Pure Docker: Apache
- Server: nginx(?)

**Review by mrnugget — APPROVED** [review]
I'm all for it. Less processes, less config files and while the reverse-reverse-proxy-stuff is not the prettiest, I like how you documented it now — much clearer than what we had before.

**Comment by felixfbecker** [comment]
> We already have Caddy running for HTTPS support.

Caddy with HTTPS still doesn't work for me and using an extra workaround nginx config file with HTTPS config is still the only way I can get a functioning dev environment. See https://github.com/sourcegraph/sourcegraph/issues/10103. Unfortunately I have zero experience with Caddy (as opposed to nginx) and because I get no error messages from Caddy I have no idea how to solve this by myself. How can I keep a functioning dev environment after this PR?

**Comment by keegancsmith** [comment]
@felixfbecker can you try out this branch? We bump the caddy version, which might help resolve the issue.

**Comment by mrnugget** [comment]
@felixfbecker Could you try this again? It would be cool if we can get rid of one of two services.

**Comment by mrnugget** [comment]
Works for me!

**Comment by felixfbecker** [comment]
This is still not working for me, however now I at least seem to get an error message. I have no idea how to resolve this though, Caddy feels like a blackbox to me 😬 

```
11:03:13                     caddy | {"level":"error","ts":1613556193.239407,"logger":"tls.renew","msg":"will retry","error":"open /Users/felix/Library/Application Support/Caddy/certificates/local/sourcegraph.test/sourcegraph.test.crt: no such file or directory","attempt":2,"retrying_in":120,"elapsed":60.004151059,"max_duration":2592000}
```

**Comment by mrnugget** [comment]
Does the rest of the path exist? `/Users/felix/Library/Application Support/Caddy/certificates/local/sourcegraph.test`?

What happens if you delete the whole folder, `/Users/felix/Library/Application Support/Caddy`, and start with `./dev/caddy.sh trust` and then `./dev/caddy.sh run --watch --config=dev/Caddyfile`?


(btw. side note: if you're not using Caddy, how do you use HTTPS?)

**Comment by keegancsmith** [comment]
@felixfbecker also see our troubleshooting guide https://github.com/sourcegraph/sourcegraph/blob/97c9b9b62a1ad319e437f17c28b891ebac3f20b0/doc/dev/how-to/troubleshooting_local_development.md#caddy-2-certificate-problems

**Review by eseliger — APPROVED** [review]
seems to work on my machine, so LGTM
nice job cleaning up this mess a bit 😁

**Review by felixfbecker — APPROVED** [review]
@mrnugget's steps worked for me. Thanks!

**Comment by felixfbecker** [comment]
> (btw. side note: if you're not using Caddy, how do you use HTTPS?)

I had a custom gitignored nginx config with a certificate generated by `mkcert`. I added support for sourcing custom nginx configs right when we switched to Caddy as a workaround because Caddy was just not working for me (meaning my dev env was broken and I needed an immediate solution) and nobody could help me 🤷‍♂️.

**Comment by mrnugget** [comment]
Sweet! Happy to hear that!

**Pull request merged**
