### PR TITLE
Don't include exhaustive rxjs internals on campaigns test

### PR DESCRIPTION
**Pull request by eseliger**
With all the internals in the snapshot, we had cases of failing CI
when rxjs was updated, this removes the coupling.

### CODE REVIEW

**Comment by lguychard** [comment]
> configure the serialization to skip any Observables (we might even already do something like this somewhere)

We didn't seem to have a concrete solution last time we had this discussion: https://sourcegraph.slack.com/archives/CMT39K56Z/p1579868140053400

**Comment by felixfbecker** [comment]
I had forgotten about that thread, thanks for refreshing my memory. `enzyme-to-json` + enzyme instead of `react-test-renderer` should work (mentioned in the thread)

**Comment by eseliger** [comment]
Opened an issue here https://github.com/sourcegraph/sourcegraph/issues/9040 as I currently don't have the time to exchange our test renderer. I think this is still a worthwhile improvement for the meantime, WDYT?

**Comment by mrnugget** [comment]
Removed myself as reviewer because I can't really comment on the internals here and defer to @sourcegraph/web.

**Pull request merged**
