### PR TITLE
Eslint fix type imports

### PR DESCRIPTION
**Pull request by fkling**
This PR adds the eslint rules `@typescript-eslint/consistent-type-imports` and `@typescript-eslint/no-import-type-side-effects`. Having type imports be explicitly declared as such makes it easier for modern bundlers to strip those imports which is useful if e.g. a module is sent directly to the browser.

I added both rules as a warning because `@typescript-eslint/consistent-type-exports` is also a warning.

Autofixing all the occurrences took a while, mainly because my machine ran out of memory at the beginning. What I did:

1. Increase node memory limit to ~50GB: `export NODE_OPTIONS=--max_old_space_size=51200`
2. Temporarily changed the warnings to errors.
3. Edited `package.json` to include the `--fix` flag in the `lint:js:all` command. ,
4. Ran `pnpm lint:js:all`
5. Switched to `client/web/.
6. First processed sub directories of batch changes with 

       find ./src/enterprise/batches -depth -maxdepth 2 -mindepth 1 -type d | \
       xargs -I '{}' -t pnpm eslint --fix --quiet '{}/**/*.[tj]s?(x)'
8. Process all remaining directories: 

       find ./src -depth -maxdepth 2 -mindepth 1 -type d | \
       xargs -I '{}' -t pnpm eslint --fix --quiet '{}/**/*.[tj]s?(x)'

If we agree to move forward with this we should add the `"importsNotUsedAsValues": "error",` compiler option to the TypeScript configuration.

## Test plan

CI

### CODE REVIEW

**Comment by vovakulikov** [comment]
@fkling If we change import linting, maybe we also could improve our import order a bit. At the moment, it seems like this 

``
// React import always goes first
import { ... } from 'react'

// Separate group for external packages
import visx from '@visx'
import package from 'package'

// Group for our internal packages 
import {} from "@sourcegraph/wildcard"
import {} from "@sourcegraph/common"

// Group for local files 
import {} from './hello-path/HelloPath.tsx'

// and finally group for styles
import styles from './Style.module.scss'

```

So this works fine but it looks a bit awkward when we have only one import from group for example

```
import { FC } from 'react'

import visx from '@visx/axis'

import {asError} from '@sourcegraph/common'

import helper from './helper'

import styles from 'styles.module.scss'

```

So I think that we can group "groups" if they have only one import and they are siblings like this

```
import { FC } from 'react'
import visx from '@visx/axis'
import {asError} from '@sourcegraph/common'
import helper from './helper'
import styles from 'styles.module.scss'
```

In case if there were two imports let's say in local file group it would be like this

```
import { FC } from 'react'
import visx from '@visx/axis'
import {asError} from '@sourcegraph/common'

import helper from './helper'
import helper2 from './helper2'

import styles from 'styles.module.scss'
```

I'm not sure that we can do it easily but if there is an option for it I would take it, I will check the order prettier rule we use for it

**Comment by fkling** [comment]
@vovakulikov It looks like the grouping is explicitly defined, it doesn't seem like it "collapses" single-item groups. But with the new version we could at least put react and third party modules into the same group. https://github.com/IanVS/prettier-plugin-sort-imports#3-add-spaces-between-import-groups

**Review by philipp-spiess — APPROVED** [review]
LGTM

**Review by philipp-spiess — APPROVED** [review]
LGTM

**Comment by fkling** [comment]
A couple of updates:
- Adding the lint rules don't seem to impact eslint performance. I ran `time pnpm lint:js` in `client/web/` (after deleting the cache) before adding the rules (current main) and after adding the rules (and fixing the existing code). Before: `3:11.41 total`, after: `3:14.06 total`. The difference of 3s is likely normal error margin.
- I kept the rules as warnings. Bazel/CI reported errors that don't happen when running `pnpm lint...` locally and it appears that bazel isn't taking `.eslintignore` files into account.
- Adding `"importsNotUsedAsValues": "error"` to the tsconfig(s) would be good for getting error reporting in the editor from the language server, but this option is deprecated in favor of `verbatimModuleSyntax`. I can't add that option though because it conflicts with `module: "commonjs"` which we have in all our tsconfigs. (can't use `import/export` syntax and that option with compiling to commonjs).

So for now this will be a one-off fix and we'll have to figure out how exactly we want to enforce `type` imports (if any).

**Pull request merged**
