### PR TITLE
monitoring: remove repo-updater: syncer_synced_repos

### PR DESCRIPTION
**Pull request by alexAtSourcegraph**
Hello all! This is an update to the documentation based on correspondence from Engineering that says the metric behind the following warning is not working at the moment. 

See here: https://sourcegraph.slack.com/archives/C02BQBNJVL0/p1630668528003600?thread_ts=1629833888.058300&cid=C02BQBNJVL0

This update is related to the customer issue found here: https://sourcegraph.zendesk.com/agent/tickets/2936

### CODE REVIEW

**Comment by unknwon** [comment]
Hmm, I think this markdown file is generated, the source line for this change should be https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/definitions/repo_updater.go?L119

**Review by bobheadxi — CHANGES_REQUESTED** [review]
If it's not working we should just remove the observable entirely, and revert this PR when the metric has been fixed. The old observable will still be available in git history and versioned docsite e.g. https://docs.sourcegraph.com/@v3.31.0

**Comment by alexAtSourcegraph** [comment]
> If it's not working we should just remove the observable entirely, and revert this PR when the metric has been fixed. The old observable will still be available in git history and versioned docsite e.g. https://docs.sourcegraph.com/@v3.31.0

Just to make sure we're on the same page @bobheadxi. You are suggesting that the actual definition of the alert be removed from monitoring/definitions/repo-updater.go correct?

**Comment by bobheadxi** [comment]
> You are suggesting that the actual definition of the alert be removed from monitoring/definitions/repo-updater.go correct?

Yep! And then run `go generate ./monitoring/...` to update the docs and all

**Review by DaedalusG — APPROVED** [review]
Glad to see someone is working on this! Common source of confusion. Theres a public issue:
https://github.com/sourcegraph/sourcegraph/issues/20911

**Comment by alexAtSourcegraph** [comment]
Not entirely sure what's making the build process fail @bobheadxi. It seems there is a step in the process that's checking to see if the alert_solutions.md was changed in any way. It doesn't seem like one can just pull the alert out based on the tests that are in place. 

I may however be reading this incorrectly so I would love your eyes on this.

**Comment by bobheadxi** [comment]
@alexAtSourcegraph I ran the following:

```
~/Projects/sourcegraph/sourcegraph ajb-cs-doc-update
❯ go generate ./monitoring/...

~/Projects/sourcegraph/sourcegraph ajb-cs-doc-update* 9s
❯ git st
On branch ajb-cs-doc-update
Your branch is up to date with 'origin/ajb-cs-doc-update'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   doc/admin/observability/alert_solutions.md
        modified:   doc/admin/observability/dashboards.md

no changes added to commit (use "git add" and/or "git commit -a")
```

> It seems there is a step in the process that's checking to see if the alert_solutions.md was changed in any way.

Yep! It looks at whether or not additional changes to the generated docs have been made and fails if non-generated changes exist. In this case, after the `go generate` there are still diffs, which means the CI will fail on unexpected changes. Here's what was missing: https://github.com/sourcegraph/sourcegraph/pull/24678/commits/8a2458f383295c68b4c1a51cc5c988a5fbf2e334

**Review by bobheadxi — APPROVED** [review]

**Comment by ryanslade** [comment]
I think we should revert this change as we fixed the metric here: 
https://github.com/sourcegraph/sourcegraph/pull/24582

**Pull request merged**
