### PR TITLE
monitoring: drop variables from alert queries

### PR DESCRIPTION
**Pull request by bobheadxi**
Observable queries that are also used for alerts _and_ make use of Grafana dashboard variables have never worked in the past, since nothing will be interpolated and the variable key will not match against anything.

For example, previously for  `critical_executor_executor_handlers`, we would render an alert query like the following:

```promql
min(((sum(src_executor_processor_handlers{queue=~"${queue:regex}",sg_job=~"^sourcegraph-executors.*"})
      or vector(0)) == 0 and (sum by(queue) (src_executor_total{job=~"^sourcegraph-executors.*"}))
      > 0) <= 0)
```

`queue=~"${queue:regex}"` works in Grafana because variable interpolation is a Grafana feature, but to Prometheus this is interpreted as a regular expression for `${queue:regex}`, which matches nothing, so this query never evaluates to anything. 

This change simply drops selectors that include variables from alert queries when generating them, since I think this will work for most cases. If one needs custom behaviour, `alert.CustomQuery` is available. In this case, the above query becomes:

```
min(((sum(src_executor_processor_handlers{sg_job=~"^sourcegraph-executors.*"})
      or vector(0)) == 0 and (sum by(queue) (src_executor_total{job=~"^sourcegraph-executors.*"}))
      > 0) <= 0)
```

From the generated diff, it seems the affected alerts are:

- `gitserver: running_git_commands` (repo-management)
- `executor: executor_handlers` (code-intel)
- `executor: executor_processor_error_rate` (code-intel)

## Test plan

Tests, review `alerts.md` changes

### CODE REVIEW

**Comment by bobheadxi** [comment]
Current dependencies on/for this PR:
* main
  * **PR #41956** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/41956" target="_blank">Graphite</a> 
    * **PR #41957** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/41957" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/41957?utm_source=stack-comment).

**Comment by Strum355** [comment]
Change to the executor alert seems to have disappeared 👀

**Comment by bobheadxi** [comment]
one sec I'm wrangling with Graphite :lolsob:

**Comment by bobheadxi** [comment]
@Strum355 the changes are in now!

**Review by danieldides — APPROVED** [review]

**Comment by Strum355** [comment]
Will review asap :+1:

**Review by ryanslade — APPROVED** [review]

**Review by burmudar — APPROVED** [review]

**Review by Strum355 — APPROVED** [review]
lotta code, output seems  OK though :+1:

**Pull request merged**
