### PR TITLE
do not show search scopes on main/repogroup search pages

### PR DESCRIPTION
**Pull request by sqs**
Search scopes are still suggested as filters on the search results page, but they are no longer shown underneath the center search input on the main `/search` page or on repogroup search pages.

These were not very useful. The default ones on Sourcegraph.com were: "Test code", "Non-test files", "JSON files", "Text documents", "Non-vendor code", and "Vendor code". If a user clicked on these from the `/search` page, they would get a bunch of fairly arbitrary results; none were useful as the first step in a search. Usage was low.

Also, they conflicted with the much more useful repogroups and other search examples, which are much more effective at helping a user start their first search.

On self-hosted instances, the recommended replacement (mentioned in the CHANGELOG.md) is better because it lets you define useful links to show on the homepage without also showing those links as suggested filters on every search (where they are unlikely to be relevant).

image

### CODE REVIEW

**Comment by dadlerj** [comment]
Can we hold off on merging this until the enterprise homepage pieces are available on cloud? I absolutely rely on these to make cloud usable—I use custom search scopes literally every day. I find it very painful to have to type in the repo scope that I care about every time I do a search.

**Comment by sqs** [comment]
@dadlerj do you use them on the homepage or the search results page? If the former, does my workaround in the changelog work for you? If the latter, that’s unchanged.

**Comment by dadlerj** [comment]
Sure, that'll work for me. My typical UX is:

- `cmd`-`l` to get to the URL bar in Chrome
- type "src"-`tab`-`enter` to go to Sourcegraph.com/search
- click on the search scope I care about (e.g. `r:github.com/sourcegraph/sourcegraph` or `r:github.com/sourcegraph/` or `r:github.com/sourcegraph/about` etc.)
- type my actual query in the search bar

I'm mostly just excited to get the enterprise homepage and didn't want to lose this until that was ready!

**Review by attfarhan — APPROVED** [review]

**Comment by AlicjaSuska** [comment]
I've prepared a solution for filters not fitting in one line on search results pages. I would like to add a simple carousel that can be used to reveal the filters that are cut off now. All the details are added to [Figma](https://www.figma.com/file/Aa5qBTB9bLLEj5LElk6zGJ/Scroll-filters-and-repositories-14128?node-id=246%3A11)

As search scopes are no longer visible on the home page, I've skipped this part in the designs. 

scroll

@lguychard - as per our call before Christmas
@rrhyne could you please take a look and review the designs as well? Thank you!

**Pull request merged**
