### PR TITLE
github: turn `Client` into an interface

### PR DESCRIPTION
**Pull request by unknwon**
Think this PR more like a proposal of "how to avoid global state mocks", this is a concrete example for GitHub API client.

Things happens:
1. Turned `github.Client` into an interface, the previous client now became `*client` and implements the new `github.Client` interface.
2. Created a `*github.MockClient` that also implements the new `github.Client` interface, but with fields could be used to inject with mock implementations in tests.
3. Updated [`github_test.go`](https://github.com/sourcegraph/sourcegraph/pull/9655/files#diff-7e1e555e56c67495f208903db68c2b7b) to mock a client by assign values to the fields of `MockClient`. (could have updated other places, but not in this PR)

**NOTE**: 
- No functional change should happen in this PR.
- Other than the big `github.Client` interface, I'm pretty happy with this approach.

Any feedback is welcome!

### CODE REVIEW

**Comment by keegancsmith** [comment]
Looks cool! Before moving to this approach I'm gonna play a bit of a devils advocate. Out of interest what motivated you to add mocks instead of the approach used in other tests (passing a different HTTP client)? I see the existing global mocks are only used in one or two places and are quite easy to replace with a custom http client. The downside to the interface approach is the amount of repeated code it requires to setup and the huge size of it. Another approach is smaller interfaces in the callers of the code that need the mocks.

**Comment by tsenart** [comment]
>  Another approach is smaller interfaces in the callers of the code that need the mocks.

Yeah, this is what I initially suggested to you @unknwon. Have an `authz.GithubClient` interface that captures the methods you need only (you told me 2). Then you just create a `fakeGithubClient` in your tests that implements those two methods only. Sure, you can have a reusable `github.FakeClient` for tests which implements all of the methods, but in general, it's good to have entities depend only what they need — this is called the [interface segregation principle](https://en.wikipedia.org/wiki/Interface_segregation_principle).

**Comment by ryanslade** [comment]
👍 To smaller interfaces where the caller specifies only what they require from the implementation.

As we do here for example:
https://github.com/sourcegraph/sourcegraph/blob/master/enterprise/internal/campaigns/syncer.go#L21

**Comment by unknwon** [comment]
Thanks the feedbacks!



> Another approach is smaller interfaces in the callers of the code that need the mocks.

The blocker of this approach is how do I mock `WithToken` method, which suppose to return a copy of the client (and return a copy of mock client in tests)? Any tricks to make that possible?

This won't work because it returns a concrete type makes subsequent methods to a real client not a mock client in tests:
```go
type Client interface {
	WithToken(token) *github.Client
}
```

**Comment by unknwon** [comment]
@keegancsmith 
> Out of interest what motivated you to add mocks instead of the approach used in other tests (passing a different HTTP client)?

Good question! We could do that (in fact it was what I did for same set of tests for GitLab), but the reasons I choose not to in this layer are:
1. As we don't mock DB results in application layer, we trust/ensure DB methods/functions do correct things by having tests in the DB layer that talks to a real DB.
2. Mock response body of RESTFul APIs are still OK, but I can imagine the headache to mock response body of GraphQL APIs (TBH I really don't like it). Nevertheless, API requests/responses with code host are internal details of API client implementation, and I think contracts between application layer and the API client are the methods and their return values.

**Comment by keegancsmith** [comment]
> The blocker of this approach is how do I mock `WithToken` method

Two approaches come to mind. First is notice how the official GitHub go
client doesn't have any methods to do with authentication on the
client. The HTTP Transport that is passed in is presumed to have dealt
with that. Maybe there is something you can do with the layers to make
that nice.

Alternatively is to use a smaller interface, but you write an adapter
for what you pass in.

  type githubSmall interface {
    APICall(...) ...
    WithTokenString(...) githubSmall
  }

  type githubAdapter struct { *Github }
  func (g githubAdapter) WithTokenString(...) { return g.Github.WithToken(...) }

>> Out of interest what motivated you to add mocks instead of the approach used in other tests (passing a different HTTP client)?
>
> Good question! We could do that (in fact it was what I did for same set of tests for GitLab), but the reasons I choose not to in this layer are:
> 1. As we don't mock DB results in application layer, we trust/ensure DB methods/functions do correct things by having tests in the DB layer that talks to a real DB.
> 2. Mock response body of RESTFul APIs are still OK, but I can imagine the headache to mock response body of GraphQL APIs (TBH I really don't like it). Nevertheless, API requests/responses with code host are internal details of API client implementation, and I think contracts between application layer and the API client are the methods and their return values.

Yeah GraphQL will be annoying. The REST ones are quite easy
thankfully. In both cases you can provide a `MockGitHubTransport` or
something which makes it easy to mock responses.

I think to move forward I'd suggest two things. Try smaller interfaces
on the little bit of code using the global mocks. See how that
feels. Additionally try convert more tests to use the mocking structs
you added. How does that feel? How do you think it would feel apply this
to every code host client?

Once you get a good feeling about that, I'm happy to go with whatever
decision you have.

**Comment by unknwon** [comment]
@keegancsmith thanks, appreciated! 
> Alternatively is to use a smaller interface, but you write an adapter for what you pass in. type githubSmall interface { APICall(...) ... WithTokenString(...) githubSmall } type githubAdapter struct { *Github } func (g githubAdapter) WithTokenString(...) { return g.Github.WithToken(...) }

👍 This idea feels really nice to me! I'll experiment with this.

**Comment by unknwon** [comment]
Closed in favor of https://github.com/sourcegraph/sourcegraph/pull/9808, thanks everyone!

**Pull request closed without merging**
