### PR TITLE
doc: mention setting NameID in SAML pages

### PR DESCRIPTION
**Pull request by unknwon**

### CODE REVIEW

**Comment by emchap** [comment]
Looks good—I am also, for context, suggesting a reorganization of the docs to Product: https://docs.google.com/document/d/1JaKcdMU2rzuBnqVGeoU1Hd7zGyyaL5YNL7idt5fDUqg/edit. It may be worth making explicit in these docs that the info we're getting from the source of truth also needs to be the email address, but I defer to you.

**Review by emchap — APPROVED** [review]

**Comment by unknwon** [comment]
> Looks good—I am also, for context, suggesting a reorganization of the docs to Product: [docs.google.com/document/d/1JaKcdMU2rzuBnqVGeoU1Hd7zGyyaL5YNL7idt5fDUqg/edit](https://docs.google.com/document/d/1JaKcdMU2rzuBnqVGeoU1Hd7zGyyaL5YNL7idt5fDUqg/edit). It may be worth making explicit in these docs that the info we're getting from the source of truth also needs to be the email address, but I defer to you.

This PR is a quick-fix-style thing, please feel free to make suggestions or send PRs to improve docs :)

**Comment by emchap** [comment]
Oh totally, yes! This is a good quick fix. :) I just wanted to highlight that if we reorganize more generally we may be able to make it more explicit generally, and to let you know that was being proposed.

**Comment by unknwon** [comment]
@emchap I totally feel the need to overhaul our auth docs. If we will have a plan or guide from CE (who are much more closer to customers), we're happy to collaborate on the effort.

**Comment by emchap** [comment]
@unknwon I wrote the doc I linked to (it's a CE proposing to Product) so if you happen to have spare time at some point and an interest in reviewing it, I'd love your thoughts. Product hasn't had a chance yet, I don't think, but I will nudge them this week.

**Pull request merged**
