### PR TITLE
fix issue where management console password would reset on user account creation

### PR DESCRIPTION
**Pull request by slimsag**
This fixes a highly annoying (but NOT a security risk) issue where the management
console password would incorrectly be reset to a newly generated secure password
each time a user account was created.

This issue accurately describes the problem in detail: https://github.com/sourcegraph/sourcegraph/issues/3201

The fix here is the quick and easily verifiable one: we carry over the result from
the prior row, so that all rows in the table have the same mgmt console password
fields.

A separate issue (and higher risk to make, which is why I am not doing it now) is
to correct this code such that it does not create duplicate entries in the
`global_state` table. This is tricky to do because there is a high risk of
introducing performance regressions as every Sourcegraph action goes through this
initalization check. If memory serves me correctly, duplicate entries was a known
property of the implementation at the time this code was written in order to avoid
locking the table and harming perf but thought to not be a concern (clearly
incorrectly, as we the site_id field also changes regularly which harms our metrics
in small various ways according to Dan).

I am confident this is a safe, good, incremental change to make (famous last words).

Helps #3201

After merge, that issue will become:

- "Cleanup global_state DB code to remove duplicate entries and prevent site_id from changing"

Test plan: Tested manually and against existing tests for this code (which caught one bug in my first implementation)

### CODE REVIEW

**Comment by beyang** [comment]
https://app.hubspot.com/contacts/2762526/company/464956351 also noticed this.

**Comment by slimsag** [comment]
Honestly most people who have set up Sourcegraph have noticed it, I'm a bit ashamed I didn't fix it sooner.

**Comment by slimsag** [comment]
So, order doesn't matter in this absolutely awful state that this code is in today.

Customers today will have something like:

```
select * from global_state;
               site_id                | initialized | mgmt_password_plaintext | mgmt_password_bcrypt 
--------------------------------------+-------------+-------------------------+----------------------
 1cec5e56-2508-421e-b42c-85b1989da4a1 | t           | abc                     | 123
 1cec5e56-2508-421e-b42c-85b1989da4e2 | t           |                         | 
 1cec5e56-2508-421e-b42c-85b1989da4e3 | t           |                         | 
 1cec5e56-2508-421e-b42c-85b1989da4e1 | t           | abc                     | 123
 1cec5e56-2508-421e-b42c-85b1989da4e4 | t           |                         | 
 1cec5e56-2508-421e-b42c-85b1989da4e5 | t           |                         | 
```

There are two possibilities of what occurs first after a customer upgrades to this:

1. A new user account is created
    - In this case, the current value of mgmt_* fields will be retained from a randomly chosen field above. This has following affects:
        1. Password remains empty / unset (as it was before this change), admin has to visit site admin page to get it.
        2. It is set to an old value (e.g. what was generated when the instance was created). Site admin would just [follow the documented steps to reset it](https://docs.sourcegraph.com/admin/management_console#how-can-i-reset-my-management-console-password)

2. A site admin visits the site admin page OR management console page
    - In this case, new mgmt_* fields will be generated and ALL rows in the table will be set to these new values.

This behavior is the same reason that despite the current unordered state of this table, site initialization doesn't randomly toggle and lock every user out.

This PR is an improvement over the status quo currently, but this entire situation is absolute madness and we should clean this up ASAP because we're basically relying on undefined postgres read order to not have a race where the instance thinks it is not initialized.

**Comment by slimsag** [comment]
Another way to describe this change that is more brief:

Before this change there was no chance the existing password would be retained.

After this change there is a high probability the existing password will be retained, and over time that probability becomes absolute certainty.

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/issues/3201#issuecomment-492456915 for the next steps here (long term plan)

**Pull request merged**
