### PR TITLE
JetBrains: 223.* compatibility

### PR DESCRIPTION
**Pull request by vdavid**
Plugin was not officially compatible with IntelliJ 2022.3.*.

In this PR, I've done the necessary updates to make this compatible.

## Test plan

I did the manual tests and everything works fine. If JetBrains's CI passes we'll be good to go and the new version will be available.

## App preview:

- [Web](https://sg-web-dv-jetbrains-223-compatibility.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by philipp-spiess — APPROVED** [review]

**Comment by philipp-spiess** [comment]
@vdavid JetBrains CI did not pass for my PR though 😐

**Comment by philipp-spiess** [comment]
The error is full of `class file has wrong version 61.0, should be 55.0` which seems like a java version thing

**Comment by philipp-spiess** [comment]
@vdavid Maybe it's just the test runner on CI having the wrong Java version. I'll try to run the scripts locally

**Comment by philipp-spiess** [comment]
```
α jetbrains (ps/jetbrains-2022.3) ./gradlew test

Welcome to Gradle 7.3.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

Starting a Gradle Daemon, 2 busy and 2 stopped Daemons could not be reused, use --status for details

> Task :verifyPluginConfiguration
[gradle-intellij-plugin :Sourcegraph:verifyPluginConfiguration] The following plugin configuration issues were found:
- The 'since-build' property is lower than the target IntelliJ Platform major version: 211.0 < 223.
- The Java configuration specifies sourceCompatibility=11 but IntelliJ Platform 2022.3 requires sourceCompatibility=17.
See: https://jb.gg/intellij-platform-versions

BUILD SUCCESSFUL in 8s
16 actionable tasks: 10 executed, 6 up-to-date
```

@vdavid test look good locally

**Comment by philipp-spiess** [comment]
@vdavid Seems like CI uses the wrong version of gradle (7.3.3-bin.zip) but the gradle file uses 7.4.2

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/dv/jetbrains-223-compatibility/compare-report.html;tab=live_object) for a full comparison between the commits f8ac69b and 4a54ce2 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by philipp-spiess** [comment]
It looks like the [gradle wrapper](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/jetbrains/gradle/wrapper/gradle-wrapper.properties?L3) and the [config](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/jetbrains/gradle.properties?L23) are out of sync but none of that changed recently 😅

**Comment by vdavid** [comment]
@philipp-spiess it was a weird series of trial and error, but I've finally got a working combination. Turns out I had to set `platformVersion=2021.1` (to the _earliest_ version we support). What's weird is that JetBrains still accepted the version with the warnings, and it works fine, too. 🤷

**Pull request merged**
