### PR TITLE
change \| to | in search query examples

### PR DESCRIPTION
**Pull request by ijt**
I'm not sure why the docs use it but `\|` doesn't seem to work.

Test plan: Tried the queries.

### CODE REVIEW

**Comment by ijt** [comment]
Got it. I'll try `<code>`...

**Comment by ijt** [comment]
`<code>` didn't work...

**Comment by ijt** [comment]
Found something else to try: https://stackoverflow.com/questions/17319940/how-to-escape-a-pipe-char-in-a-code-statement-in-a-markdown-table.

**Comment by ijt** [comment]
Hmm, that doesn't work either, although it looked okay in my local preview within Goland.

**Comment by ijt** [comment]
Okay, it seems to be fine now in  https://docs.sourcegraph.com/@fix-search-examples/user/search/saved_searches. PTAL.

**Comment by sqs** [comment]
Great. Can you please also fix https://docs.sourcegraph.com/user/search/queries? (And any other doc pages that might have this problem, but I can't think of any others.)

**Comment by ijt** [comment]
Filed an issue for that one. It seems to look better as a table so we might want to use another markdown renderer.

**Pull request merged**
