### PR TITLE
browser-extension: fall back to static info when resolveRev fails

### PR DESCRIPTION
**Pull request by chrismwendt**
`ensureRevisionsAreCloned` can fail when the current repository is private and the configured Sourcegraph URL is Sourcegraph.com (we block requests that could leak private info).

When the call fails for that reason, this change falls back to the `FileInfo` obtained directly from the page.

I also removed a redundant copy of this function.

Related: https://github.com/sourcegraph/sourcegraph/issues/852 (this PR doesn't resolve that issue)

> This PR does not need to update the CHANGELOG because

### CODE REVIEW

**Comment by ijsnow** [comment]
So we don't ensure revisions on private repos? How can we be sure that they are there?

**Comment by chrismwendt** [comment]
The request is only blocked when the destination is Sourcegraph.com. The request is allowed when the destination is a private Sourcegraph instance.

**Comment by ijsnow** [comment]
We still need to ensure revisions on sourcegraph.com. I'd imagine that that's where most of the stale repos live meaning that when we're looking at OSS code we'll most likely never have the correct revision.

**Comment by ijsnow** [comment]
Is it possible for the new language server extensions to ensure revisions? If that were possible, we wouldn't need to do this in the browser extension.

**Comment by chrismwendt** [comment]
Interesting idea, yes, Sourcegraph extensions can make GraphQL requests (including ensure revisions).

**Pull request merged**
