### PR TITLE
JetBrains: Add popup open action to main menu

### PR DESCRIPTION
**Pull request by vdavid**
Was not on our roadmap but I realized this was missing and would be cool to add.

CleanShot 2022-07-01 at 13 27 30@2x

Also changed the action label to match the native action.

## Test plan

See it work: [20-sec Loom](https://www.loom.com/share/f60b2ece210d45c2a0b0e6f009a2fac7)

## App preview:

- [Web](https://sg-web-dv-jetbrains-add-popup-to-main.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-lopebwdqrq.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by vdavid** [comment]
@jjinnii @ryankscott do you agree that this should be a useful addition?

**Comment by ryankscott** [comment]
LGTM

**Review by philipp-spiess — APPROVED** [review]

**Review by jjinnii — APPROVED** [review]
LGTM. Small nit, I _think_ following our [copy guidelines](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/#product-names), we say "Find with Sourcegraph" rather than on/in.

**Comment by vdavid** [comment]
> LGTM. Small nit, I think following our [copy guidelines](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/#product-names), we say "Find with Sourcegraph" rather than on/in.

Ah, that's a great insight. I'm so happy that a native speaker reviewed this; I felt a bit unsure which one was the best version, but I always forgot to ask. I'll modify it everywhere then!

**Comment by vdavid** [comment]
Hmm, after looking at the code, this looks a bit more difficult than I thought. We have several contexts where we mention Sourcegraph. I’ve created a separate issue for this: https://github.com/sourcegraph/sourcegraph/issues/38144

**Pull request merged**
