### PR TITLE
gitlab: Always set token in clone URL even if public

### PR DESCRIPTION
**Pull request by mrnugget**
This change was triggered by a customer running into an error when
trying to use campaigns on a public repository. `gitserver` couldn't
push the commit because the credentials in the remote URL were missing.

Turns out that we don't save the token for public GitLab repositories,
_even if we have one available_.

The problem is that users can't use campaigns with public Gitlab
repositories until we add user tokens and they then add a separate token.

That problem doesn't exist with GitHub or Bitbucket Server where we
always set the token.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
LGTM but we should await approval from someone who might know why this was in here.

**Comment by tsenart** [comment]
Have you tested this? Particularly, I'd make sure that existing public repos work after this change.

**Review by tsenart — APPROVED** [review]

**Comment by mrnugget** [comment]
> Have you tested this? Particularly, I'd make sure that existing public repos work after this change.

Yeah, we tested this locally by trying to reproduce the customer's issue where we cloned a private repo, flipped it to public, recloned it, etc. I just tested it again by accessing a public repository (gitlab.com/beyang/thyme) cloned on this branch. Works.

Do you have a specific test scenario in mind?

(FYI: If we roll this out, then gitserver will keep using the old non-token-including remote url until the repository is garbage collected.)

**Review by chrispine — APPROVED** [review]
LGTM, thanks!

**Review by LawnGnome — APPROVED** [review]

**Review by unknwon — APPROVED** [review]

**Comment by tsenart** [comment]
> (FYI: If we roll this out, then gitserver will keep using the old non-token-including remote url until the repository is garbage collected.)

So, after this change is rolled out, customers **have** to reclone the repo for campaigns to be able to authenticate as the user? If so, how do we communicate that?

**Comment by mrnugget** [comment]
> So, after this change is rolled out, customers **have** to reclone the repo for campaigns to be able to authenticate as the user?

Well, yes, but also:
- it will be recloned after... 45 days: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/cleanup.go#L33-34
- we're shipping user-tokens this release, which will be the recommended way to use credentials with campaigns and fixes this issue
- it's only a problem when pushing to public GitLab repositories, which is rare

I think the changelog entry is enough. It's not like we have hundreds of campaigns users in the wild.

**Comment by tsenart** [comment]
> I think the changelog entry is enough. It's not like we have hundreds of campaigns users in the wild.

:+1:

**Pull request merged**
