### PR TITLE
Delete CODEOWNERS

### PR DESCRIPTION
**Pull request by nicksnyder**
I think CODEOWNERS is broken. I see PRs where tons of reviewers get added, and I see PRs where the wrong reviewers get added. It isn't expressive enough to actually capture the right set of reviewers. Worse, it is unclear whose approvals are needed to actually merge. Without CODEOWNERS, GitHub will suggest reviewers but won't automatically add them. This puts the responsibility on the author to determine who is the best reviewers (e.g., who wrote the file? who last edited the file? who last reviewed a change to this file), which I think is a good thing.

If you have feedback on this PR, please submit it using this anonymous form: https://docs.google.com/forms/d/e/1FAIpQLSfjDJxP1wdfEuTZdeNqTsCxfXD2HIYx_5aiTC17B6LyXwYorw/viewform?usp=sf_link

### CODE REVIEW

**Comment by abitrolly** [comment]
Is `sourcegraph` smart enough of making own reviewer suggestions through GitHub API?

**Comment by keegancsmith** [comment]
I agree! GitHub already provides a suggested reviewers based on who actually touched code (recently?). Adding 1 or 2 actual people as reviewers is much higher signal on the reviewer to do something. If you are new to a code area looking at blame/history is not only useful to discover reviewers, but probably also useful to inform you on code / design.

I can imagine some people may miss the utility of "watching" PRs in areas they own. There is probably tooling to help with this. Alternatively you can get a feel for changes to areas you care about with just a "git log" or dogfooding our saved search product :P

**Comment by abitrolly** [comment]
I am interested to read the dogfooding tutorial for codeowners. )

**Comment by keegancsmith** [comment]
@nicksnyder so should we land this?

**Comment by nicksnyder** [comment]
Summary of responses: https://docs.google.com/forms/d/1caaUCzaaVzd7-iMAyrhZzZV-zEfHa7fjGv3BOxs9YHY/edit#responses

**Comment by abitrolly** [comment]
image

**Comment by nicksnyder** [comment]
This form and its responses are only available to teammates working at Sourcegraph.

**Comment by abitrolly** [comment]
I would say that for pushing SourceGraph further into adoption, this one a very good use case. Not everyone wants to depend on MS owned GitHub, and that opens a door for opportunities.

**Comment by keegancsmith** [comment]
I think the concerns around blame not being good for ownership are not a reason to keep code owners. As you get familiar with a new part of the codebase you will likely be talking to someone about it. Finding out who owns it is quite easy via viewing git history / PR reviews / asking someone. All of these are good things to do anyways. This applies irrespective of being a new or tenured employee, and is a valuable skill to have. Once you are regularly contributing to something, you know who to add as a reviewer and who to cc.

Not being notified of changes to code you are interested in is an issue, but we should find another solution (dogfood saved searches? finally make it as good as phabricator's herald). Personally if I didn't get notified about some code I care about and only find out later, I am fine with that. I'd rather benefit developer productivity/velocity and retroactively address issues.

My opinions are that we shouldn't have code ownership at all, and codifying it + trying to gate keep code changes via tooling like this is the wrong approach and has weird side effects. We should encourage everyone to feel free to change any part of the product / codebase if they think it is broken / could be better. If they are doing it responsibly they will get input from someone who has more context on why it is the way it is.

I would at least like to trial one release cycle without codeowners :) If someone is frustrated at the lack of it after a week, they can add rules just for them to the file (but not for teams).

**Comment by abitrolly** [comment]
> If they are doing it responsibly they will get input from someone who has more context on why it is the way it is.

Experience tells me that these *if* and *will* do not work well together without some tooling. That someone is likely to miss the event that his help is needed, and people who are contributing may not possess the communicative skills that we find quite obvious. Especially first time contributors and people who are not used to bit gatherings.

**Comment by nicksnyder** [comment]
This PR is replaced by https://github.com/sourcegraph/sourcegraph/pull/13838

**Pull request closed without merging**
