### PR TITLE
Add structural search usage docs

### PR DESCRIPTION
**Pull request by rvantonder**
This is a first draft. I need to go through it for polish/phrasing/wording and will do so by Dec 19, 11 PM PT. At this stage I would appreciate feedback on the general layout and flow of the examples and usage in `structural.md`. I'm also putting this up for earlier so that is visible for things that will go in the release post.

Notes:

- Add a bullet in `Code search overview`
- Added `patterntype:structural` to Search query syntax section. I lowercased `patterntype` because I'm not sure if the change to allow capitalization (`patternType`) made it into the release cut (cc @attfarhan  any idea?)
- Add structural search as it's own section in the left hand side nav bar, and put a 'new' pill next to it
- Add `structural.md`. I would appreciate a look through for flow and structure.

### CODE REVIEW

**Comment by rvantonder** [comment]
Self reminder: add a changelog entry and describe feature flag

**Comment by rvantonder** [comment]
- added the changelog entry linking to docs
- added a note on disabling with a feature flag in the configuration
- confirmed that the release image has structural search enabled by default, and that the site configuration option to disable it actually disables it

**Comment by sqs** [comment]
These are a great start, but we should get a lot more better examples. See https://github.com/sourcegraph/about/pull/472#discussion_r360327673 for several ideas I had.

**Comment by rvantonder** [comment]
Agree. Those those are good additional examples. We can either include them in the usage doc page, or https://docs.sourcegraph.com/user/search/examples

**Pull request merged**
