### PR TITLE
Redact Coursier credentials from configuration

### PR DESCRIPTION
**Pull request by varungandhi-src**
- First commit is a no-op cleanup that enables the second commit; the commit message explains the rationale behind the refactoring.
- Second commit is a small tweak and the main change I wanted to make.

### CODE REVIEW

**Review by olafurpg — COMMENTED** [review]
Is the first commit needed if you make it a required field in jvm-packages.schema.json? If we make the field required then the generated `Maven` field is no longer a pointer. Then it becomes  the same as `AWSCodeCommitConnection.GitCredentials`

**Review by olafurpg — APPROVED** [review]
The changes look good to me 👍 It's nice that the new logic handles nested pointer fields!

**Comment by varungandhi-src** [comment]
> Is the first commit needed if you make it a required field in `jvm-packages.schema.json`? If we make the field required then the generated `Maven` field is no longer a pointer.

Yep, I thought of doing that first, but I think combining the code from two places into one place is a useful simplification regardless of that. If I remove the first commit, the problem is that someone unsuspecting might hit the same issue when adding a test case for a new connection type. Or you refactor some other fields for another connection type, and introduce a pointer in between, tweak the test in the "obvious" way but the test starts failing.

**Comment by varungandhi-src** [comment]
Merging this for now; happy to do any cleanup in case you have any post-commit comments @efritz.

**Pull request merged**
