### PR TITLE
mv cmd/frontend/db/dbconn to pkg/dbconn

### PR DESCRIPTION
**Pull request by slimsag**
With the introduction of the management console, the frontend will no longer be
the only service which talks to the database. Therefor, sharing the logic to
connect to and migrate the database makes sense. This change does just that.

It was also sharable before, but it would have meant importing
`cmd/frontend/db/dbconn` from the management console which does not make sense
logically as they are separate services.

Migration logic still lives in pkg/dbconn, because we only have one database
(not multiple).

Helps #965

### CODE REVIEW

**Comment by keegancsmith** [comment]
Do we want more services than the frontend speaking to the DB and running migrations? We sometimes have services out of sync, but within a single service the only disparity is during rollout. We avoided it in the past by adding the internal API endpoint which was usually just a light wrapper around the backend/db pkg. I believe we made this package importable was due to enterprise, not so that other services could use it.

**Comment by slimsag** [comment]
I added a disclaimer to pkg/dbconn that warns most services should be using the frontend for DB access

**Comment by keegancsmith** [comment]
Ok, I'm still a bit wary about that. But if you do wanna go that route, can you add a check like I did for enterprise imports? See `dev/check/go-enterprise-import.sh`. I am guessing you should only check command entry points and check the `Deps` for imports of the db package.

**Comment by slimsag** [comment]
Yeah I'll look into that, thanks for the pointer! If you have anything specific you are wary of, let me know.

**Comment by beyang** [comment]
Maybe it's better to have the management console import `cmd/frontend/db/dbconn` than to move the package out of `cmd/frontend/`? Because the fact that the mgt console can access the DB is more "exceptional" and the "common case" is that other binaries shouldn't talk to the DB directly. We could even call management console main package `cmd/frontend-management-console` or something like that to make it even clearer.

**Comment by slimsag** [comment]
IMO that is not better, and `cmd/frontend-management-console` kind of implies that there are other relationships with the frontend: authentication, port exposure, frontend JS code sharing, etc. when in reality there are not any, the only exception is the DB access.

Keegan's script idea should make it obvious that others cannot use this package unless they too have an exceptional case

**Comment by slimsag** [comment]
I added the script to check for failure + this change itself is simple / will have zero regression so I am going to merge. If we have ideas on how to improve things I can do those in follow up PRs :)

**Pull request merged**
