### PR TITLE
singleprogram: use localhost for gitserver

### PR DESCRIPTION
**Pull request by keegancsmith**
Using the hostname isn't gaurenteed to work, it depends on how the machine is configured. For example on my linux desktop this fails. We only start the services on localhost and we use ipv4 localhost address for all other services.

Test Plan: sg start app doesn't spam my logs with failing to connect to gitserver.

### CODE REVIEW

**Comment by keegancsmith** [comment]
I see why this was done, I now have these error logs:

```
[    sourcegraph] WARN gitserver server/cleanup.go:193 current shard is not included in the list of known gitserver shards, will not delete repos {"current-hostname": "habitat", "all-shards": ["127.0.0.1:3178"]}
```

**Comment by keegancsmith** [comment]
Alright it is fixed, we needed to set another envvar to inform gitserver what its address is. This PR is ready for review/landing :)

**Comment by keegancsmith** [comment]
nevermind not fixed. Will actually fix now :D

**Comment by keegancsmith** [comment]
@sourcegraph/repo-management I've made a more fundemental change to how gitserver picks its identity which is why I am requesting your review. I didn't go so far as to rename the "Server.Hostname" field, but indeed it is not (nor has it ever actually just been) a hostname. Renaming it to external address or identity in another PR should be done.

Context: previously HOSTNAME was abused as the name we could look up in SRC_GIT_ADDRS. But having a port in a hostname is just wrong. This lead to issues in sourcegraph app were the HOSTNAME wouldn't match up. I suspect the same is true in sourcegraph/server, but I don't wanna change that in this PR because that requires more thought (ie some people would have a stable hostname, so changing it would break stuff).

**Review by sashaostrikov — APPROVED** [review]
LGTM!

**Review by mrnugget — APPROVED** [review]
Did you make sure it works with `sg start` and the two gitserver instances running?

**Comment by keegancsmith** [comment]
> Did you make sure it works with `sg start` and the two gitserver instances running?

yup

**Pull request merged**
