### PR TITLE
web: `Team Labeler` Github action

### PR DESCRIPTION
**Pull request by valerybugakov**
### Description

@sourcegraph/frontend-platform uses a couple of Slack integrations based on the team label. It would be great if robots could add team labels for us based on the configuration file and PR owner. This PR introduces such Github action. It uses [Team Labeler](https://github.com/marketplace/actions/team-labeler-action) action. `.github/teams.yml` was created based on Github [teams](https://github.com/orgs/sourcegraph/teams) in Sourcegraph org.

Tested here: https://github.com/sourcegraph/sourcegraph/pull/19742.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Would this mean that any PR that a member of a certain team opens is implied to be _for_/_in the domain of_ that team? That doesn't seem generally correct - e.g. if someone from batch changes or code insights was to make a PR that improves our webpack build, refactors general web app code or updates ESLint, I wouldn't consider that a "code insights" or "batch changes" PR? Could be manually fixed easily, but in a way this communicates that those kinds of PRs are _not_ expected/encouraged and unusual (and there is an implication that it might immediately create Slack notifications based on this mapping, even if you fix it immediately in the GitHub UI).

**Comment by pdubroy** [comment]
I can definitely see how this could be useful... @valerybugakov, maybe you can explain what we'll use this for on the Frontend Platform team? Then maybe it will be clearer if it makes sense to proactively do this for other teams, or let them opt-in if desired.

**Comment by valerybugakov** [comment]
@felixfbecker valid concern, I didn't think about team labels as indicators of the domain. If this automation looks like a distraction for other teams, I can definitely make it optional.

I think about the team label more as a _changes ownership_ indicator. Then labels like `web` and `api` can be used to indicate a PR _domain_. If I create a PR with code-insights improvements, I would still want it to appear in #frontend-platform-github-feed. It's useful in a couple of ways:

1. It makes it easier to keep track of what your teammates are working on. It's good to at least flip through the PR description.
2. Easier to follow your team's pull requests that require your review.

@sourcegraph/frontend-platform, what do you think?

**Comment by felixfbecker** [comment]
I'd be fine with you doing it for your team, just not sure if I'd want it for my own PRs/my team. Also do agree with labels being nice in general. But I did see them as domain labels too, e.g. there is no independent `code-insights` label, only `team/code-insights`.

**Comment by valerybugakov** [comment]
@felixfbecker got it. I will remove all other teams from the workflow and will post a message about this functionality in #dev-chat.

**Review by pdubroy — APPROVED** [review]

**Pull request merged**
