### PR TITLE
Try to get Chromatic components to react to theme changes

### LINKED ISSUE #20687: Monaco not changing theme in storybook snapshots
Monaco should change theme when setting storybook to dark mode

image

See also https://github.com/hipstersmoothie/storybook-dark-mode/issues/124

### PR DESCRIPTION
**Pull request by limitedmage**
Fixes #20687

Note that this is NOT working yet. Storybook snapshots are still published with incorrect dark mode handling :(

### CODE REVIEW

**Comment by valerybugakov** [comment]
Hey @limitedmage, after looking into the issue, I found a couple of things:

1. `<Story forceDarkMode={isDarkModeEnabled} />` passes `forceDarkMode` into a story context that can be accessed in our stories in a couple of ways:

As a second argument of the Storybook `ClientApi` methods: 

```ts
// `StoryContext` contains `forceDarkMode` property.
storiesOf(x)
  .addDecorator((StoryFn, StoryContext) => StoryFn) 
  .add((StoryArgs, StoryContext) => StoryFnReturn)
```

As a return value from the `useStoryContext` hook

```ts
import { useStoryContext } from '@storybook/client-api'

// This hook can only be called inside decorators and story functions.
const { forceDarkMode } = useStoryContext()
```

2. The `useStoryContext` hook cannot be used inside of the `WebStory` or `BrandedStory` functions because we don't use them as decorators via the `addDecorator` method. Ideally, `WebStory` should be passed into the `addDecorator` method to access the `StoryContext` and stories should rely on `Args` and `StoryContext`. Then it would be easy to integrate everything together:

```ts
const { add } = storiesOf(x, module).addDecorator(UpdatedWebStory)

add('default', (args, contextWithPropertiesFromTheUpdatedWebStory) => (
  <SearchBox isLightTheme={contextWithPropertiesFromTheUpdatedWebStory.isLightTheme} />
)
```

In the current implementation, we need to add additional logic to make `StoryContext` available in the `WebStory` or use it manually in each story from the second argument, which will require a lot of manual work because we won't rely on `isLightTheme` provided by the `WebStory`.

**Comment by limitedmage** [comment]
@valerybugakov  Thanks for looking into this, it makes sense. Any idea why the other approach ([using events](https://github.com/sourcegraph/sourcegraph/pull/21000/commits/df3f4be4955378a686586dd73b0aa0c03c51e9d4)) is not working?

**Comment by valerybugakov** [comment]
@limitedmage, I didn't have a chance to look into it today — busy Monday 🙃. 
I will check events approach my tomorrow morning, curios why it didn't work.

**Comment by limitedmage** [comment]
Closed in favor of #21596

**Pull request closed without merging**
