### PR TITLE
Remove "quick start tour for authenticated users" / "create team" step

### PR DESCRIPTION
**Pull request by erzhtor**
Closes https://github.com/sourcegraph/sourcegraph/issues/33901.

## Test plan
- `SOURCEGRAPH_API_URL=https://sourcegraph.com SOURCEGRAPHDOTCOM_MODE=true sg -skip-auto-update=true start web-standalone`
- Open https://sourcegraph.test:3443/search?feature-flag-key=quick-start-tour-for-authenticated-users&feature-flag-value=true and sign in
- Check that the "Create team" step is not in the quick start tour
- Check that the rest for tour works as previously

## Screenshots
| BEFORE | AFTER |
| --: | :-- |
| image | Screen Shot 2022-04-15 at 16 34 41 |
| image | image |

## App preview:

- [Link](https://sg-web-erzhtor-remove-quick-start-tour.onrender.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by taras-yemets** [comment]
@erzhtor, I have fewer steps than on the screenshot in the description. 
image
Reverting your change doesn't introduce the "create team" step for me too.

**Comment by erzhtor** [comment]
> @erzhtor, I have fewer steps than on the screenshot in the description. 

Hey @taras-yemets, I think you are not signed in. There are two versions of the quick start tour for visitors and authenticated users.

**Review by taras-yemets — APPROVED** [review]

**Comment by taras-yemets** [comment]
> I think you are not signed in

My bad, @erzhtor 😅 I somehow missed this note in the description.

**Comment by erzhtor** [comment]
> My bad, @erzhtor 😅 I somehow missed this note in the description.

No, you didn't miss it. I actually added it after your question). Sorry for the confusion, and thanks for the review! 👍

**Pull request merged**
