### PR TITLE
insights: fix query runner worker metrics

### LINKED ISSUE #39838: insights: query runner metrics are not being emitted
It appears the query runner metrics were accidentally removed in a a refactor, and are no longer emitted.

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/a36bacb3bd1c84a99b3fc9962810d1c9a9645036?visible=4

### PR DESCRIPTION
**Pull request by leonore**
closes #39838

the issue was that the metrics identifier name was changed, and that was actually associated to the metrics themselves.
if we change the metrics name now though, we can get visibility into the past.

## Test plan
locally:
```bash
sg start enterprise-codeinsights &
sg start monitoring
```

create some insights to trigger some queue activity

navigate to https://sourcegraph.test:3443/-/debug/grafana/d/worker/worker?orgId=1

| before | after |
| ------ | ----- |
| image | image |

also changing the metrics name on dogfood, [for example](https://k8s.sgdev.org/-/debug/grafana/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum%20%20by%20(le)(rate(src_query_runner_worker_processor_duration_seconds_bucket%7Bjob%3D~%5C%22%5Eworker.*%5C%22%7D%5B5m%5D))%22,%22format%22:%22heatmap%22,%22datasource%22:%22Prometheus%22,%22exemplar%22:true,%22requestId%22:%22Q-ea397826-0a54-4913-b8f7-e2f36777cc8b-0A%22%7D%5D) shows this works

### CODE REVIEW

**Review by coury-clark — COMMENTED** [review]
Since these metrics have actually been emitted all this time I think maybe we should explore just changing the dashboard to use the proper metric name. Just quickly testing it on demo shows that the data is all available with this metric name.

**Comment by leonore** [comment]
> Since these metrics have actually been emitted all this time I think maybe we should explore just changing the dashboard to use the proper metric name. Just quickly testing it on demo shows that the data is all available with this metric name.

we can do that, if we're happy with sticking with the name `query_runner_worker` for all our observability for this, e.g. `src_query_runner_worker_total`. just a shame it doesn't have `insights` or `queue` in it, but `insights_search_queue` isn't ideal either, since we do searches and computes.

it's just a find and replace operation: https://sourcegraph.sourcegraph.com/search?q=context:global++repo:%5Egithub%5C.com/sourcegraph/sourcegraph+insights_search_queue&patternType=standard

**Comment by coury-clark** [comment]
@leonore I think the name is fine. This would make it so we actually have data for the last 6 months. If we change the name, we will still need to update our dashboards to union the two metrics together.

**Comment by leonore** [comment]
@coury-clark I'm assuming you mean that if we'd change the name, we still have to make that dashboard change to get observability into the past. so I've reverted back to `query_runner_worker` and have updated the actual metrics names.

let me know if that's _not_ what you meant.

**Review by coury-clark — APPROVED** [review]

**Comment by coury-clark** [comment]
yes exactly, sorry for long approval!

**Pull request merged**
