### PR TITLE
batches: add close batch change link to SSBC screens

### LINKED ISSUE #39446: Add "Close" as an action from menus on server-side workflow screens
- Should be accessible from `ActionsMenu` on editor, execution, and read-only configuration screens
  - (Ideally preview too but I don't remember if we have a menu there or if it's just the Apply button in the banner right now)
  - Some of the screens might have a single CTA right now. We should convert the CTA to a menu in these cases
- Should use the red X close icon
- Should link to the batch change close page

### PR DESCRIPTION
**Pull request by LawnGnome**
This PR extends the _Actions_ menu that appears in several places in the execution UI (always on the Preview tab, and when an execution is incomplete or failed on the other tabs) to include a _Close batch change_ item. For batch changes that have been executed, this means that the user can now close a batch change more directly from the batch change list.

Additionally (see the previous version of this PR description and Kelli's comment below for context), the _Actions_ menu has been added to the _Configuration_ tab when creating a new batch spec, replacing the _Run batch spec_ CTA, thereby allowing a user who hasn't yet executed a batch spec (slightly) more immediate access to 

Compared to the original #39446, this descopes converting the preview CTA to a dropdown button in other places. Since that button takes you to the _Preview_ tab, which then has the full actions menu including the close batch change item, this felt unnecessary.

### A note on iconography

We already have a cross icon in the actions dropdown, so I've used a circled close to distinguish closing the batch change:

image

It also turns out that we used `mdiDelete` for the close button on a batch change, so I've updated that to `mdiClose` so it's at least closer.

Closes #39446.

## Test plan

I've run through the various permutations of this, including unexecuted batch specs, batch specs that are being executed, and batch specs that are complete.

Our automated storybook coverage here isn't zero, but it's also not complete, as far as I can tell. Manually using the storybook helps to validate this flow. I've restructured the `ActionsMenu` storybook to handle the new way it handles its various modes.

## App preview:

- [Web](https://sg-web-aharvey-ssbc-close.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-bemvoenqfv.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by courier-new** [comment]
Thanks for the write-up, Adam! I think I agree with your rationale about leaving the Preview CTA alone -- coming to that execution from the batch changes list would take the user directly to the preview screen, anyway, so it makes sense to keep it simple and only expose "Close" from there.

That being said, I realized while thinking about your point that we might want to have the "Close" action be available in one other place, too: the configuration screen for a draft batch change that has never been executed on. This is the other case users are most likely to hit from the batch changes list -- they just created a test draft, they don't intend to execute anything, and now they want to get rid of it. Right now, we just show the same "Run batch spec" CTA on both tabs of the edit screen:

https://user-images.githubusercontent.com/8942601/181169636-0bdfa378-14dc-41dd-8f25-059c034b780d.mov

I think it might make more sense if the user switches to the "Configuration" tab to switch to the actions menu, with "Close" being the only available action. In the future this might be where a "Modify configuration" option would also belong.

**Comment by courier-new** [comment]
Also, 👍 to your iconography decisions. 🙂

**Comment by LawnGnome** [comment]
OK, with the changes @courier-new and I discussed above now incorporated, this is even more ready (ripe?) for review than before.

**Review by eseliger — APPROVED** [review]
🍷 🚀

**Review by Piszmog — APPROVED** [review]

**Pull request merged**
