### PR TITLE
rockskip: Replace second long-running process with gRPC API

### LINKED ISSUE #62100: gitserver: Move LogReverseEach to new gRPC pattern

### PR DESCRIPTION
**Pull request by eseliger**
We want to migrate the LogReverseEach call to gRPC methods as well.
However, it isn't a great practice to have to keep this process running for potentially hours, as any server restart will have to make the entire process start over.

With one call per commit, we're not occupying a process slot on gitserver, and rollouts of gitserver should much less affect rockskip, as individual commits can be retried before being returned to the rockskip code.

One thing: I reimplemented what ChangedFiles does so that we can still implement integration tests on this level, but since gitserver is a separate service, a go unit test is likely long-term not the best test bed for these kinds of tests. Ideally we would spin up a small gitserver with that repo cloned, and a small program that runs the rockskip index function.
Unfortunately I think we have little precedence for these things, but that would be the highest confidence that things actually work E2E in production.

Closes #62100

Test plan:

Existing tests still pass, I let it index a repo locally and compared it to the results I got on main with a fresh index there.

### CODE REVIEW

**Comment by eseliger** [comment]
* **#62734** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/62734?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @eseliger and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by jtibshirani** [comment]
This looks good to me!

>  Ideally we would spin up a small gitserver with that repo cloned, and a small program that runs the rockskip index function.

Indeed! I have a TODO to add a couple backend integration tests for Rockskip, that will at least give some coverage here (https://github.com/sourcegraph/sourcegraph/issues/62550)

Did we ever resolve @keegancsmith 's question here: https://github.com/sourcegraph/sourcegraph/pull/62260#pullrequestreview-2053060862 ? Maybe we were waiting on the perf numbers he mentioned?

**Comment by eseliger** [comment]
> Did we ever resolve @keegancsmith 's question here: https://github.com/sourcegraph/sourcegraph/pull/62260#pullrequestreview-2053060862 ? Maybe we were waiting on the perf numbers he mentioned?

Ah! No, curious to hear what the numbers are :) src-cli indexed in about the same time locally vs main, but it's a very small repo.

**Review by ggilmore — APPROVED** [review]
Approved, but @sourcegraph/search-platform should review

**Review by jtibshirani — APPROVED** [review]
This looks good to me! I feel the test coverage is as good as possible given our lack of end-to-end tests -- we've covered the ChangedFiles logic, Rockskip indexing and search, and done manual checks.

**Comment by jtibshirani** [comment]
> Did we ever resolve @keegancsmith 's question here: https://github.com/sourcegraph/sourcegraph/pull/62260#pullrequestreview-2053060862 ? Maybe we were waiting on the perf numbers he mentioned?

@eseliger and I chatted offline and decided we don't have a big concern here. I do think there's room to improve observability here, to be able to debug what's slow if we observe slow index times.

**Comment by eseliger** [comment]
### Merge activity

* **May 21, 9:22 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/62734) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Pull request merged**
