### PR TITLE
DRAFT: Play around with sqlc

### PR DESCRIPTION
**Pull request by mrnugget**

### CODE REVIEW

**Comment by mrnugget** [comment]
In 726c108 I migrated one of the more "complex" models we have (`Changeset` with `json.RawMessage` columns for marshalling structs but also to marshall a `[]int64`) to make use of the auto-generated code.

I think a lot of that remaining boilerplate could be delegated to `sqlc` if it would offer more hooks for code generation (so we can hook into the marshaling/unmarshaling of custom types).

Some of the code is there because I want to keep the same interface for now to make use of tests. But we could just as well use `sql.ErrNoRows` instead of our `ErrNoResults`.

The dynamic dispatch to the underlying methods based on what's specified in `opts` is

a) not something that `sqlc` supports right now. You need to generate methods for different argument combinations right now. Which is fine, because they're easy to write.
b) not something we definitely need, since we can use separate methods for separate use cases.

The biggest reason for there still being a lot of custom code is that we need to convert between the generated models in `queries` and our `*a8n` models.

**Comment by mrnugget** [comment]
The last commit, 223c254, needs https://github.com/kyleconroy/sqlc/pull/164 to work. One of the reasons why we need that is because we used `integer` as the database type but `int64` in Go. If we were to change `integer` to `bigint` then `sqlc` would generate the correct without having to specify an override in `sqlc.json`

**Comment by mrnugget** [comment]
Closing this after a discussing it with @tsenart. With the current state of `sqlc` we wouldn't gain a lot (vs. the effort it takes to migrate).

Here's a list of things that are missing/things that we still need to do in custom code:

- Conditional predicates in `Get*` methods (e.g.: only append `WHERE campaign_id = $1` if `arg.CampaignID` is set).
- Setting of `CreatedAt` and `UpdatedAt`.
- There's no easy way to put the type definitions of the models in an OSS package but the store/queries in enterprise.
- You cannot set a custom type for a "dynamic query column" (e.g. `my_foo` in `SELECT id, (SELECT foo FROM bar WHERE id = blub.bar_id) AS my_foo FROM blub;`).
- Support for "scan types" that are only used when scanning database rows. e.g. we use `dbutil.NullTime` and others only in our `scan*` methods to wrap an existing type in the model definition. `sqlc` on the other hand requires the "scannable" type to be set on the model.
- Custom queries like our in `CreateChangesets` and `UpdateChangesets` would still be custom code.
- Custom "deserializing" logic, as in `queryBackgroundProcessStatus`, would still need to live in a wrapper.

As you can see in the last few commits that I pushed to this branch, it's possible to use the generated code as the lower level in our `a8n.Store` and only talk through that to the database, but there's still a lot fo custom code necessary to keep our APIs.

Some of that can be fixed by changing the API (e.g. instead of the ability to combine multiple conditionals in SELECT queries, we create separate methods for different combinations) and some of that can probably be implemented in `sqlc` itself, but at the present time, the payoff is not that big yet.

**Comment by tsenart** [comment]
Thanks for experimenting with this! Good learnings.

**Pull request closed without merging**
