### PR TITLE
bump syntect_server: add TOML, Zig, DreamMaker + update Kotlin

### LINKED ISSUE #13937: Add syntax highlighting for TOML files (develop an open-source grammar for it)
The syntax definition we used for highlighting TOML files before was found to have no license and not be open-source so we had to remove it. See #13933

We should develop and open-source grammar for it following what was said in #13933 - please see that issue if you are interested in taking a shot at this. We are looking for volunteers :)

### PR DESCRIPTION
**Pull request by slimsag**
Thanks to @rvantonder we get TOML and Zig syntax highlighting on Sourcegraph
now: https://github.com/slimsag/Packages/pull/5

Thanks to @Strum355 we get updated Kotlin syntax highlighting (and support for `.kts` file extension) plus support for DreamMaker https://github.com/slimsag/Packages/pull/6 https://github.com/slimsag/Packages/pull/7

(I am just updating a dependency here)

Fixes #13937

### CODE REVIEW

**Comment by slimsag** [comment]
(will merge once CI passes, no review needed)

**Review by rvantonder — APPROVED** [review]
`/giphy ziggy`

(there are no good gifs)

**Comment by Strum355** [comment]
Im working on adding DreamMaker support as well, do we want to bundle that into this PR? https://github.com/slimsag/Packages/pull/7

**Comment by slimsag** [comment]
Can do!

**Comment by slimsag** [comment]
Should be all good now, feel free to hit merge once CI is green - otherwise I will later tonight / tomorrow morning (gotta run for now.)

**Pull request merged**
