### PR TITLE
Refresh: Update code host, repositories and account security setting pages

### PR DESCRIPTION
**Pull request by umpox**
Updates the code host, repositories and account security setting pages to match new refresh designs.

Issue: https://github.com/sourcegraph/sourcegraph/issues/21567

## Screenshots
image

image

image

### CODE REVIEW

**Review by eseliger — APPROVED** [review]

**Review by rrhyne — APPROVED** [review]
I have not had a chance to review this interactively as I haven't figured out how to toggle these screens when starting in .com mode, but based on these screenshots, the implementation looks great. 

Thanks for getting to this and for including screengrabs in the PR.

**Comment by rrhyne** [comment]
QA: https://www.figma.com/file/PGorahH15wPOQ6WgYlzmBY/?node-id=15%3A19

@quinnkeast, you might want to have a look at the above!

**Comment by umpox** [comment]
Thanks @rrhyne I'll add these updates in a follow up PR shortly

**Comment by umpox** [comment]
@rrhyne @quinnkeast PR with further updates: https://github.com/sourcegraph/sourcegraph/pull/21728

**Pull request merged**
