### PR TITLE
Open "Help" and "About" in new tabs

### LINKED ISSUE #11460: Remove reliance of NavLinks test on DOM structure
We have a test for `NavLinks` for its render output (important since it has a lot links that need to have the right URL).

This test is [coupled to the DOM structure to produce a list of text labels](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@50a1633f136e3ace68fd366630aac24b80a3b65f/-/blob/web/src/nav/NavLinks.test.tsx#L16-43). This is bad, because changes to the DOM structure break the test and require manual updates, which is against [our testing goals](https://about.sourcegraph.com/handbook/engineering/web/testing#general-goals).

Currently there's an [`[object Object]` in the test](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@50a1633f136e3ace68fd366630aac24b80a3b65f/-/blob/web/src/nav/__snapshots__/NavLinks.test.tsx.snap#L7:4).

To prevent this in the future, we should just make it a snapshot test of the render output. The output of this small component should be readable enough to not warrant the downsides of reliance on the structure.

### LINKED ISSUE #12286: 'About Sourcegraph' and 'Help' pages should be opened in the separate tab
Current state:
- Authorized users: 'Help' and 'About Sourcegraph' links, accessible from the 'Profile' dropdown, opens in the new tab
- Un-authorized users: 'Help' and 'About' links, accessible from the top navigation, opens in the same tab.

Proposed changes:
- **Open Help and About links in the separate tab for all users.** We would avoid taking them out of the context of the app.
- **Add 'open in the new tab' icon** in the dropdown menu visible for authorized users.

@rrhyne @felixfbecker please, review. Thank you!

See in [Figma](https://www.figma.com/file/iXNTQ4rsggVtH8ASe3Vnzg/About-Sourcegraph-and-Help-pages-should-be-opened-in-the-separate-tab?node-id=0%3A1)

Menu-icon

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #12286
Closes #11460

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
What a snapshot 😐

**Comment by AlicjaSuska** [comment]
@felixfbecker thank you for updating the menu. I reviewed the Chromatic:
- 'open in new tab' icon color should be different (secondary link color)
- also, I can't access the dark mode

In addition, could you please change the Figma link to new components file. The current one is outdated.

https://www.figma.com/file/HWLuLefEdev5KYtoEGHjFj/Sourcegraph-Components-Contractor?node-id=1346%3A0

Thank you!

**Comment by felixfbecker** [comment]
Hm, in other places where we use this icon it adapts the text color of the link/button, e.g. the "Find references" button if it opens a new tab. I think if it's a different color, it looks a bit like the icon is the only clickable part, but really it's the entire item. I'll change it though if you think it's better.

With "secondary link color", do you mean I should simply apply the `secondary` color? (we don't have a concept of "secondary link", but we can put `text-secondary` on a link).

**Comment by AlicjaSuska** [comment]
It makes sense - let's keep the icon color as you proposed.

I didn't realize we have exactly the same pattern in 'Find references'. My bad.

Two more things here:
- how can I access the dark mode?
- could you please add this Figma link to the Storybook:
https://www.figma.com/file/HWLuLefEdev5KYtoEGHjFj/Sourcegraph-Components-Contractor?node-id=1346%3A0

Thank you!

**Comment by felixfbecker** [comment]
@AlicjaSuska updated Figma link and dark mode should now be viewable in Chromatic through the bottom panel.

**Comment by AlicjaSuska** [comment]
Thank you @felixfbecker All approved

**Pull request merged**
