### PR TITLE
executors: Add Maven to Bundled Executor

### PR DESCRIPTION
**Pull request by Piszmog**
Add Maven 3.6.3 with Java 11.

Also add a `README.md` to help give context for the image.

## Test plan

Local testing.

Screenshot 2023-06-07 at 09 56 27

### CODE REVIEW

**Comment by Piszmog** [comment]
How do I run with trivy?

For wolfie, seems that image is bare bones - doesn't even have python. So I am assuming we are going with the regular image over wolfie.

**Comment by eseliger** [comment]
@willdollman are we going to migrate/fixup the bundled-executor for wolfi or should we just stay with the regular dockerfile here?

---

`trivy image <imagename>` I think

**Comment by willdollman** [comment]
> @willdollman are we going to migrate/fixup the bundled-executor for wolfi or should we just stay with the regular dockerfile here?

The Wolfi [bundled-executor image](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/wolfi-images/bundled-executor.yaml) should have all the same packages as the existing bundled-executor Dockerfile - you can test it out with `docker.io/sourcegraph/bundled-executor:bazel-insiders`. Ignore the `Dockerfile.wolfi` which might be causing confusion - that's outdated and will be removed.

I'll push a quick change to this PR to add maven to the wolfi image - the wolfi repo has a newer version (3.9.2) available - is that an issue?

**Comment by Piszmog** [comment]
@willdollman is it possible to build the wolfie image locally?

I can just add the packages to the YAML file.

**Comment by Piszmog** [comment]
Also trivy reports

```
sourcegraph/bundled-executor:insiders (alpine 3.14.8)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

**Comment by willdollman** [comment]
👍 Worst case we can package the older version ourselves, let me know.

I've pushed a couple of commits to add these packages and update the bundled-executor base image. The process of updating base images is currently a bit clunky.

Not sure if it's github caching but I'm not seeing the commits on this PR, but do see them on https://github.com/sourcegraph/sourcegraph/compare/main...rc/bundled-executor-maven

**Comment by Piszmog** [comment]
Yea GitHub caching is messed up. I see the changes locally. Even push a tweak I made to the README and that isn't showing up.

**Comment by Piszmog** [comment]
https://github.com/sourcegraph/sourcegraph/compare/main...rc/bundled-executor-maven

**Comment by Piszmog** [comment]
Since caching is messed up and wont trigger a new build, I am going to close and reopen the PR.

**Pull request closed without merging**
