### PR TITLE
codeintel: Add missing authz conds for xrepo results

### PR DESCRIPTION
**Pull request by efritz**
I think the current state of code intel can allow for certain data (positions within source files, so repo names and paths within them) to be leaked about private repositories. This PR adds missing authz conditions to these queries

- `DefinitionDumps` is called on xrepo go to definition to find the upload that provides a certain dependency version. This will now filter out any uploads defined in a repository that's not visible to the current user.
- `ReferenceIDsAndFilters` is called on xrepo find reference operations to find the set of uploads to search in for a particular moniker. This will also now filter out any uploads defined in a repository that's not visible to the current user.

### CODE REVIEW

**Review by Numbers88s — APPROVED** [review]
LGTM 👍

**Review by unknwon — APPROVED** [review]

**Comment by unknwon** [comment]
Additionally, you could also add some backend integration tests to our `authtest` suite for code-intel: https://github.com/sourcegraph/sourcegraph/blob/main/dev/authtest/code_intel_test.go

**Review by ryanslade — APPROVED** [review]

**Comment by efritz** [comment]
@unknwon Tracking auth tests in https://github.com/sourcegraph/sourcegraph/issues/29185.

**Pull request merged**
