### PR TITLE
Separate "steps" into separate lines

### PR DESCRIPTION
**Pull request by yevbar**
Right now the site comes out reading "Creating a Sourcegraph extension Local development" in one line so adding bullet points improves readability and changing verbs for consistency?

Test plan: 
No need for testing - documentation change

### CODE REVIEW

**Comment by yevbar** [comment]
I feel personally accomplished for getting PR number "four fours"

**Comment by sqs** [comment]
@ryan-blunden or @beyang  Can you figure out how to get this merged and document how to handle 3rd-party contributors (for which Buildkite won't run due to security issues)?

**Comment by sqs** [comment]
@ryan-blunden @beyang Ping

**Comment by beyang** [comment]
Merged in https://github.com/sourcegraph/sourcegraph/pull/4771.

**Pull request closed without merging**
