### PR TITLE
graphql: remove discussions

### PR DESCRIPTION
**Pull request by keegancsmith**
This was deprecated in 3.15 for removal in 3.16. Most of the code still
exists, this is just removing it from the GraphQL backend.

Will need to follow-up with configuration and other parts of the codebase
which have discussions code. Will also confirm that there are no calls to the
graphql endpoint on Sourcegraph.com before merging.

Part of https://github.com/sourcegraph/sourcegraph/issues/9649

### CODE REVIEW

**Comment by felixfbecker** [comment]
Keep in mind the site config feature flag also needs to be removed

**Comment by keegancsmith** [comment]
Can't merge just yet, we are still getting requests to it: [dashboard](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum%20by%20(field)(delta(src_graphql_field_seconds_count%7Bfield%3D~%5C%22(%3Fi:.*discussion.*)%5C%22%7D%5B5m%5D))%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

image

I think once #10262 is merged we can likely merge this.

**Comment by felixfbecker** [comment]
How about we start by removing the site config flag from dotcom? We need to do that anyway and it's opt-in. Without the config, the webapp won't make requests afaik.

**Comment by keegancsmith** [comment]
> How about we start by removing the site config flag from dotcom? We need to do that anyway and it's opt-in. Without the config, the webapp won't make requests afaik.

I just tried to do that, but I think there is a bug in the code when we switched to storing configuration in a file. I can't update the sourcegraph org settings (which are in the DB, not a file). You reported this issue here https://sourcegraph.slack.com/archives/C07KZF47K/p1588097266080900

**Comment by felixfbecker** [comment]
@keegancsmith I think site config now needs a PR to be updated because it is tracked in git

**Comment by keegancsmith** [comment]
Since disabling discussions in the sourcegraph org, there has been zero traffic to it. I can't merge this though due to CI. @felixfbecker looks like this PR depends on #10262 since removing it from the graphql schema causes test failures in the webapp.

**Comment by felixfbecker** [comment]
Yeah, we generate TypeScript types from the GraphQL schema that are referenced in the web code and now missing. Merged the PR so this is good to go!

**Pull request merged**
