### PR TITLE
campaigns: remove misleading encryption text

### PR DESCRIPTION
**Pull request by LawnGnome**
In light of #16008, this is _extra_ not true right now until we have
Vault support.

### CODE REVIEW

**Review by chrispine — APPROVED** [review]
Thanks, LGTM

**Review by eseliger — APPROVED** [review]
LGTM but I wonder if this is going to be used at customer instances as well?

**Comment by LawnGnome** [comment]
> LGTM but I wonder if this is going to be used at customer instances as well?

I have no idea. [This Slack thread](https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1605624304224800) is the most recent discussion I'm aware of on this, but I figure we're better off not making any promises at all until we know what the plan is. We can reintroduce this behind a dot-com check if that makes sense once this is underway.

**Comment by mrnugget** [comment]
Good branch name!

**Pull request merged**
