### PR TITLE
doc: regenerate architecture diagrams

### PR DESCRIPTION
**Pull request by LawnGnome**
As cut, the `3.19` branch appears to fail the `dev/check/go-generate.sh` check due to out of date architecture diagrams. These were updated as a whole in #12949, but this missed the 3.19 cut and we might not want to cherry pick the whole thing: this is the minimal PR to get things green again, I believe.

cc: @marekweb @eseliger

### CODE REVIEW

**Comment by efritz** [comment]
This is my mistake. I'll update this branch so that the relevant parts that fix the build will be available in the tag.

**Comment by LawnGnome** [comment]
> This is my mistake. I'll update this branch so that the relevant parts that fix the build will be available in the tag.

Thanks!

**Comment by efritz** [comment]
This should fix it.

**Comment by efritz** [comment]
For reference: https://github.com/sourcegraph/sourcegraph/pull/12949/files#diff-b5f031167c74f74c827ee076ade86a32R1

**Comment by LawnGnome** [comment]
Ah, that makes sense. Thanks again!

**Pull request merged**
