### PR TITLE
Build and upload binaries of executor to GCP bucket

### PR DESCRIPTION
**Pull request by mrnugget**
This is modelled after `dev/src-expose/release.sh`: https://github.com/sourcegraph/sourcegraph/blob/main/dev/src-expose/release.sh

But it's split into two: build & release process.

The **build step** creates a directory/file structure that looks like this and uploads it to GCP:

```
$ tree enterprise/cmd/executor/artifacts
.
└── executor
    ├── 010b133ece7a79187cad209b27099232485a5476
    │   ├── info.txt
    │   └── linux-amd64
    │       ├── executor
    │       └── executor_SHA256SUM
```

The **release step** then deletes the current `latest` folder and copies the last release folder to `latest`:

* https://storage.googleapis.com/sourcegraph-artifacts/executor/latest/info.txt
* https://storage.googleapis.com/sourcegraph-artifacts/executor/latest/linux-amd64/executor
* https://storage.googleapis.com/sourcegraph-artifacts/executor/latest/linux-amd64/executor_SHA256SUM

### CODE REVIEW

**Review by eseliger — APPROVED** [review]

**Comment by eseliger** [comment]
Would this close https://github.com/sourcegraph/sourcegraph/issues/27540?

**Comment by mrnugget** [comment]
Yes. Next step is then to write docs :)

**Comment by eseliger** [comment]
That's a separate ticket though :)

**Comment by mrnugget** [comment]
Yep, that's what I meant. So this would close #27540

**Review by efritz — APPROVED** [review]

**Pull request merged**
