### PR TITLE
oobmigrations: Add metadata column

### PR DESCRIPTION
**Pull request by ryanslade**
Add a metadata column so that extra information can be stored with migrations
marshalled as JSON.

### CODE REVIEW

**Review by indradhanush — APPROVED** [review]
I'm not familiar with this part of the codebase. While I understand the changes after reviewing and they look good, I'm curious to know more about the historical motivation behind this change.

**Comment by slimsag** [comment]
@efritz should review before landing I think, he’s got most context in this

**Comment by ryanslade** [comment]
> I'm not familiar with this part of the codebase. While I understand the changes after reviewing and they look good, I'm curious to know more about the historical motivation behind this change.

This will allow us to store more than just a percentage progress with a migration. For example, with our work to migrate repo sharding for gitserver we'll be performing the migration on all repos, ordered by repo name. It's useful for us to store the most recently migrated repo name so that the migration code knows what to work on next. We need to track this somewhere and tracking it as part of the migration itself feels the most natural.

**Review by efritz — APPROVED** [review]
Thank you for making this pattern more generally useful, this is awesome!

**Pull request merged**
