### PR TITLE
Customize colors for JSON syntax highlighting

### PR DESCRIPTION
**Pull request by olafurpg**
Previously, we used the same syntax highlighting color for JSON keys and
values. This commit overrides the color for keys so that it's easier to
distinguish them from values.

**Before (current behavior on Cloud)**
CleanShot 2022-01-24 at 15 20 44

**After (this PR)**
CleanShot 2022-01-24 at 15 20 58
CleanShot 2022-01-24 at 15 20 54

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
There are a few generated files in here that should be deleted :)

**Review by olafurpg — COMMENTED** [review]
Let me fix the gigantic diff first

**Review by olafurpg — COMMENTED** [review]
Added an entry to the changelog

**Review by mrnugget — APPROVED** [review]
Cool!

**Pull request merged**
