### PR TITLE
Remove gitserver ResolveRevision mock

### PR DESCRIPTION
**Pull request by mollylogue**
- Remove gitserver ResolveRevision mock
- perform appropriate refactoring.

## Test plan
Ensure existing unit tests pass, do a main-dry-run to ensure nothing is broken

### CODE REVIEW

**Comment by mollylogue** [comment]
If someone from @sourcegraph/batchers could take a look at the most recent [commit](https://github.com/sourcegraph/sourcegraph/pull/43012/commits/80f81f31a2f0917a19151f9e5c25bbebfe8b4e38) and help me figure out why some tests are still failing, that would be super helpful. From what I can tell the new mock gitserver client is returning what the old one was, and that's the main difference between this and main. 

Context on why this is changing: This section of code contained a usage of the gitserver.ResolveRevision mock, which we are deprecating in favor of threading through the actual gitserver client and using a proper mock client in tests. This meant that a lot of the structs here would have to contain both a `gitserver.Client` and a `GitserverClient`, so I opted to remove the `GitserverClient` and just use the `gitserver.Client`. In refactoring the tests I haven't been able to figure out why they're still failing.

**Comment by eseliger** [comment]
👀

**Comment by eseliger** [comment]
Took a brief look, I think the issue is that in `mock_sync_state` we still use another gitserver mock `gitserver.Mocks.ExecReader` that is now not executed anymore that we use the `gitserver.MockClient` instead, so the ExecReader would return `nil, nil` by default, causing the panics we're seeing in the Diff iterator.
Feels like the best path forward would be do remove that mock (at least for batch changes) as well and things should stop to panic.

**Comment by mollylogue** [comment]
> Took a brief look, I think the issue is that in `mock_sync_state` we still use another gitserver mock `gitserver.Mocks.ExecReader` that is now not executed anymore that we use the `gitserver.MockClient` instead, so the ExecReader would return `nil, nil` by default, causing the panics we're seeing in the Diff iterator. Feels like the best path forward would be do remove that mock (at least for batch changes) as well and things should stop to panic.

Thanks for looking, you were 100% correct 🎉

**Review by sashaostrikov — APPROVED** [review]
Very nice!
I began the same struggle to remove ExecReader mock (unfinished in a feature branch currently) and felt the same pain putting gitserver client in new places.

Thanks for doing that! 🙏🏻
:shipit:

**Comment by sashaostrikov** [comment]
@mollylogue merged your PR because it is awesome and needs to be merged (and also my other PR depends on it 😅)

**Comment by mollylogue** [comment]
@sashaostrikov Thanks! 🙏

**Pull request merged**
