### PR TITLE
Add hidden option to configure context size

### PR DESCRIPTION
**Pull request by eseliger**
This is useful to evaluate larger contexts.

## Test plan

Verified that large numbers of files are included in context when this setting is set.

### CODE REVIEW

**Comment by sourcegraph-buildkite** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.10 kb) | 0.00% (+0.10 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/es/large-context/compare-report.html;tab=live_object) for a full comparison between the commits 70914ae and 61b3436 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by abeatrix** [comment]
Lgtm. Can we make it available for other recipes as well other than chat, or is this more for testing purpose atm?

**Review by mrnugget — APPROVED** [review]

**Comment by eseliger** [comment]
> Lgtm. Can we make it available for other recipes as well other than chat, or is this more for testing purpose atm?

Yes, probably. This is just meant for testing out the 100k context window of claude right now, but other recipes could also make use of this if we want to. I just wanted something quick to unblock testing, not even sure if we need to merge this PR of if people can just work off of this branch 🤔

**Comment by sqs** [comment]
<kbd>*semi-automated message*</kbd> Cody's source code has moved to a new repository, https://github.com/sourcegraph/cody. If you still intend to merge this change, please reopen your PR on that new repository.

The following are some of the path mappings from the old repository (https://github.com/sourcegraph/sourcegraph) to the new repository (https://github.com/sourcegraph/cody):

- `client/cody/ -> vscode/`
- `client/cody-shared/ -> lib/shared/`
- `client/cody-ui/ -> lib/ui/`

Thank you for the PR, and sorry for the inconvenience!

**Pull request closed without merging**
