### PR TITLE
Remove erroneous console.log statement

### PR DESCRIPTION
**Pull request by fkling**
Don't know who left that there 🤷🏻‍♂️

### CODE REVIEW

**Review by novoselrok — APPROVED** [review]

**Review by umpox — APPROVED** [review]
:)

**Review by eseliger — APPROVED** [review]

**Comment by limitedmage** [comment]
That was probably me 🤦‍♀️

**Comment by fkling** [comment]
@limitedmage Nope, it was me 😉

**Comment by limitedmage** [comment]
I think we all do it at some point 🤣

**Pull request merged**
