### PR TITLE
search: Only show no resolved repos alert when there are no results

### PR DESCRIPTION
**Pull request by tsenart**
## Context

I need some guidance on how to best approach this. Currently, searching for `r:deps(foo) someresults` returns both `type:file` results and a no resolved repos alert for the converted`r:deps(foo) r:someresults`.

Ideally we only want to show a no resolved repos alert when there are no results across *all* jobs. This PR is an attempt to do that, but it's currently breaking queries such as `r:noresults or someresults`.

This is also an area of the code that has been changing a lot recently, so I'd like to collaborate on a solution here.

### CODE REVIEW

**Comment by tsenart** [comment]
Here's a link to a problematic query: https://sourcegraph.com/search?q=context:global+repo:deps%28%5Egithub%5C.com/sourcegraph/sourcegraph%24%403.37%29+Observable+cannot+be+called+as+a+function&patternType=literal&trace=1

**Comment by camdencheek** [comment]
So, I fixed the specific query, but there are still many bad alerts (see backend integration tests). Looking at it closer, I think moving alerting outside the `NewOrJob` is going to take some serious dedicated effort. Our alert-to-error translation is pretty closely tied to a single basic query, which is why `NewAlertJob` was under `NewOrJob` before (it kept refactors semantically unchanged).

**Comment by tsenart** [comment]
Ah that's too bad. Thank you for looking into it!

**Comment by camdencheek** [comment]
I've logged a note to come back to this once I get to cleaning up alerts. Anyways, thanks for uncovering a bug  😄

**Pull request closed without merging**
