### PR TITLE
Remove noop extension controler

### PR DESCRIPTION
**Pull request by philipp-spiess**
We want to ship the removal of the extension API with the next release. To get as much time to dog fooding these changes as possible, let's remove the noop extension controller from dotcom already. After my changes in #45811 and @sqs's changes in #45920 this should work well enough in case the following three conditions are true (which they are on dotcom):

- Usage of new reference panel
- CodeMirror
- Selection-based code-navigation

## Test plan

Tested locally, e.g.:

Screenshot 2022-12-22 at 12 03 20

## App preview:

- [Web](https://sg-web-ps-disable-extension-api-on-dotcom.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -1.38% (-38.67 kb) 🔽 | -0.27% (-38.98 kb) 🔽 | -0.00% (-0.31 kb) | -0.14% (-1) 🔽 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/disable-extension-api-on-dotcom/compare-report.html;tab=live_object) for a full comparison between the commits 39b5df7 and 657fea8 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by valerybugakov — APPROVED** [review]
Nice!

**Comment by cbart** [comment]
Hi! 

I feel tooltip does not appear when using sourcegraph locally (`sg start`) after this pull request was merged.

`git checkout e909f63efb` -> the PR merged before this one (_bazel: rename generate_graphql_operations(output) to out (#45946)_) - tooltip works fine on hover.

`git checkout a0facbe1e0` -> the commit for this pull request - tooltip does not appear.

I'm not very familiar with that part of the front-end codebase. Do you know what am I doing wrong?

**Comment by philipp-spiess** [comment]
@mrnugget Created an issue here: https://github.com/sourcegraph/sourcegraph/issues/46240

**Pull request merged**
