### PR TITLE
Search onboarding tour QA updates

### PR DESCRIPTION
**Pull request by attfarhan**
Fixes https://github.com/sourcegraph/sourcegraph/issues/13944.

This PR includes two changes: 

1. The "Filter language" and "Filter repository" steps will now be advanced when a user chooses a suggestion from the dropdown after the `repo:` or   `lang:` filters are inserted.
1. The structural search examples are removed from the "Add query term" step. This step just prompts the user to add a query term now. As a result, the structural search informational step is also removed.

### CODE REVIEW

**Comment by lguychard** [comment]
Meta before I do a full review: for ease of reviewing, it would have been nice to split 1. and 2. into separate PRs 🙂

**Comment by limitedmage** [comment]
This seems to be an issue with the Monaco editor and not the search tour *per se*: selecting a repo with autocomplete from the `repo:` filter adds a space, but selecting a language from autocomplete from the `lang:` filter does not. This is an incredibly minor issue but adds a small inconsistency in the onboarding tour.

**Review by limitedmage — APPROVED** [review]

**Comment by rrhyne** [comment]
The language path works really, really well. 

When I attempt to filter the repository list to select sourcegraph/sourcgraph, it advances the tour to 'enter code' when I type the '/'.

**Comment by attfarhan** [comment]
@rrhyne this is because we have a debounce time of 500ms. We not only have to handle the case where a user selects a suggestion, but also if they were to type their own repo that does not appear in the suggestion dropdown. So, if you type `sourcegraph`, wait the dropdown, decide not to select an option, and then start typing again 500ms after your previous keystroke, we'll advance. 

If we don't handle this case, a user could type `github.com/sourcegraph/sourcegraph`, and never select an option from the dropdown, and we would not advance the tour.

The solution I propose is keeping the end with whitespace requirement for this use case. If a user types their own repo or lang query, and not select an option from the dropdown, they'll need to press space to advance the tour. Pushing up a commit to implement this.

**Comment by rrhyne** [comment]
Your change seems to have fixed the issue. Nice job! Let's merge this asap so I can run the user testing again.

**Review by rrhyne — APPROVED** [review]

**Review by lguychard — COMMENTED** [review]
I'm glad this fixed the Tour issue 👍  Added a few comments that would be great to address in a follow-up PR.

> Selecting a language from autocomplete from the lang: filter does not. This is an incredibly minor issue but adds a small inconsistency in the onboarding tour.

This was an oversight on my part a long time ago, here is [where the trailing space is inserted for repository completions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b872f78d5f68a70a76f861c4c1aa4da1b7af045c/-/blob/shared/src/search/parser/completion.ts?subtree=true#L66:19), the same would need to be done for the `insertText` of [language completions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b872f78d5f68a70a76f861c4c1aa4da1b7af045c/-/blob/shared/src/search/parser/completion.ts?subtree=true#L137:1).

**Pull request merged**
