### PR TITLE
changelog: cut sourcegraph@5.3.0

### PR DESCRIPTION
**Pull request by keegancsmith**
## Test plan

N/A

### CODE REVIEW

**Comment by keegancsmith** [comment]
These are the commits which touched the changelog since 5.3 branch was cut:

```
8c1df6956c * Update CHANGELOG.md to announce gRPC as the only internal comunication method (#60237)
48fdc63346 * Update Access token defaults (#60190)
daf29d1412 * cody web: do not include ignored files in context (#59907)
```

@ggilmore gRPC change I assume was the big one you backported?

@taras-yemets cody web change was not backported. Is this an oversight, or should it wait for the next minor release? For now I am assuming you won't backport it so I have moved it into the unreleased section.

Update Access token defaults was backported.

**Review by BolajiOlajide — APPROVED** [review]

**Comment by taras-yemets** [comment]
>@taras-yemets cody web change was not backported. Is this an oversight, or should it wait for the next minor release? For now I am assuming you won't backport it so I have moved it into the unreleased section.

@keegancsmith, it's an oversight and I'd like this change to be backported (it's a companion PR to https://github.com/sourcegraph/sourcegraph/pull/59836). Should I create a backport PR manually?

**Comment by keegancsmith** [comment]
> Should I create a backport PR manually?

@taras-yemets yup. You should be able to use the `backport 5.3` label. If that automation fails, then go ahead and do it manually. Thanks!

You may need to do some manual cleanup to ensure the changelog entry is in the right place.

**Comment by taras-yemets** [comment]
@keegancsmith, backport label worked:
- https://github.com/sourcegraph/sourcegraph/pull/60256 

The changelog entry is in `## Unreleased 5.3.0 (planned release date: 15th February, 2024)` section. Is it the correct one?

**Comment by taras-yemets** [comment]
>The changelog entry is in ## Unreleased 5.3.0 (planned release date: 15th February, 2024) section. Is it the correct one?

@keegancsmith, now it seems to be in the right place 😅 
- https://github.com/sourcegraph/sourcegraph/pull/60260

**Pull request merged**
