### PR TITLE
fix(appliance): transpose state to configmap when possible

### PR DESCRIPTION
**Pull request by craigfurman**
PR to https://github.com/sourcegraph/sourcegraph/pull/64042 with some suggestions to get it over the line. This does a few things, so I recommend going one commit at a time (since there are merges):

- merge main in and resolve conflict
- merge https://github.com/sourcegraph/sourcegraph/pull/64096 in since that was blocking testing on the base branch
- See last commit for the meat of this: try to set the configmap status on every state transition that reaches the backend, tolerating cases in which the configmap doesn't exist yet.

I'm not sure if this combined with the base PR closes https://linear.app/sourcegraph/issue/REL-291/wait-for-admin-ui-integrates-with-backend, because I am not 100% sure what the desired behaviour of the frontend on refresh state should be.

I would have guessed it should keep refreshing the page, which in a real system where we're going via the ingress and therefore the service, will whisk the user away to the code search console. Of course we can't tell fore sure without kicking the tires via a real ingress, not just accessing the appliance frontend directly. I am not sure this is working, and it's certainly not working on a frontend reboot - it offers the install page. Maybe the final piece is to read the initial status from the configmap at appliance boot, if it exists?

## Test plan

- Started the frontend and backend
- Accessed the appliance web UI on localhost
- Installed Sourcegraph
- Clicked wait-for-admin button
- `kubectl get configmap sourcegraph-appliance -o yaml` shows that its status annotation has changed
- logs show that the healthchecker was unblocked by this event
- the frontend ingress-facing service has been repointed to frontend

### CODE REVIEW

**Review by DaedalusG — APPROVED** [review]
Looks like this is an amalgam of a few PRs but it looks good to me where it refers the appliance 👍🏼

**Comment by craigfurman** [comment]
It contains some merges @DaedalusG , see description 🙏

**Comment by craigfurman** [comment]
I pushed one more small commit relating to https://linear.app/sourcegraph/issue/REL-293/appliance-is-packaged-in-containers-for-production. I think we should probably merge some stuff in now, all these branches are getting messy. See comment in https://github.com/sourcegraph/sourcegraph/pull/64042.

**Comment by craigfurman** [comment]
Rolled into https://github.com/sourcegraph/sourcegraph/pull/64042

**Pull request closed without merging**
