### PR TITLE
pkg/db/globalstatedb: choose appropriate bcrypt cost + document why + add mocking

### PR DESCRIPTION
**Pull request by slimsag**

### CODE REVIEW

**Comment by slimsag** [comment]
Please post-merge review. :)

**Comment by slimsag** [comment]
Helped #965

**Comment by nicksnyder** [comment]
Question: Management console passwords are always randomly generated, right? (i.e. a user can't select their own?)

**Comment by slimsag** [comment]
They are randomly generated by default, but we allow users to pick their own by running a DB query (we will provide instructions). However, in those instructions I will be very strict about any < 128 character password being insecure due to no rate limiting done on our part.

**Pull request merged**
