### PR TITLE
clarify nature of Phabricator integration in docs

### PR DESCRIPTION
**Pull request by sqs**
Addresses confusion in https://github.com/sourcegraph/sourcegraph/issues/3490#issuecomment-487866373.

### CODE REVIEW

**Comment by keegancsmith** [comment]
@beyang do our phabricator customers actually use a phabricator external service? I thought they only used the gitolite phabricator fields?

**Comment by beyang** [comment]
I am not aware of any customer use of the Phabricator external service.

**Comment by sqs** [comment]
https://app.hubspot.com/contacts/2762526/company/565067980 uses it, or at least used it. @dadlerj Can you ask them if they use the Phabricator external service (i.e., if **Site admin > External services** has a Phabricator entry)? Can we determine from pings if anyone else uses the Phabricator external service?

**Comment by dadlerj** [comment]
I'll reach out, but I'm quite certain they do (given discussion at https://sourcegraph.slack.com/archives/CHPC7UX16/p1556045468008800?thread_ts=1556029947.001200&cid=CHPC7UX16). @tsenart @keegancsmith would you like to chat with https://app.hubspot.com/contacts/2762526/company/565067980 about their usage? Or do you have any questions?

@sqs We don't capture external services in pings, but we can add them. Intuitively, I think it would be fine to do so, and wouldn't be any more revealing than, e.g., the category of auth provider used (which we also capture). LMK if you agree and I'll add it for 3.4.

**Comment by sqs** [comment]
@dadlerj Got it. If you know for sure, no need to ask. 

Yes, that’d be great info to collect in pings.

**Pull request merged**
