### PR TITLE
chore: Rename uploadstore packages for clarity

### PR DESCRIPTION
**Pull request by varungandhi-src**
- The `internal/uploadstore` package is renamed to `object` indicating
   that it is meant to provide a generic object storage wrapper.
- The `search/exhaustive/uploadstore` package is used in very few places
   so I've merged into the `internal/search` package similar to `internal/embeddings`.

There are a few reasons to do the renaming.
1. The word `upload` in a more general context is ambiguous (just in `internal/`) - in the codeintel context,
    it means "SCIP index" but it can also be interpreted generically ("upload of _some_ data").
2. Better readability - `kv.Store` is much shorter than `uploadstore.Store`. Additionally, we
    use the term `Store` A LOT in the codebase, and usually, these refer to wrappers over some
    tables in some DB. However, we don't use key-value stores in lots of places, so previously
    one needed to do extra mental-bookkeeping that "oh, uploadstore.Store is different from the other stores".

    Making things worse, some of our code also has:

    ```
	uploadsstore "github.com/sourcegraph/sourcegraph/internal/codeintel/uploads/internal/store"
    ```

    And code which says `uploadsstore.Store` (notice the extra `s` 😢), which is actually a wrapper
    over some key DB tables like `lsif_uploads`.

## Test plan

Covered by existing tests

### CODE REVIEW

**Review by eseliger — COMMENTED** [review]
I’m not sure I like this a lot - KV is already taken for redis in our codebase (search KeyValue symbol)

Also, searchkv to me sounds like the search metadata which is key value pairs.

**Comment by keegancsmith** [comment]
Is KV really the right name for this? A more common name for the stores this abstracts over is a blobstore. Or even just s3 like. uploadstore is a bad name to be fair. Also search's convenience package around this doesn't need to match whatever name we pick here, it should probably match what search cares about in this case, which is a result store or blob store.

**Comment by eseliger** [comment]
I could very well live with `blobstore`, uploadstore does indeed seem to be too focused on uploads (which it was, LSIFUploads were the reason this was made) 😬

**Comment by varungandhi-src** [comment]
@eseliger @keegancsmith thanks for the feedback, I did not consider the conflict with the redis-associated packages. I don't want to re-use `blobstore` here because we already have the `blobstore` service elsewhere. Since we're storing "objects" in both S3 and GCS terminology, how about this alternate proposal:

1. Use `object` as the package name instead of `uploadstore`. For functions/types in the package which are too ambiguous, we can add `Store` appropriately.
2. Inline the contents of the inappropriately named `searchkv` package into `internal/search`? We do the same for embeddings today, where there is an `uploadstore.go` in `internal/embeddings` instead of in a separate `uploadstore` package.

**Comment by eseliger** [comment]
`object` feels overly broad to me, I could be convinced otherwise but my initial inclination is to rather call it `objectstore` if we have to go with object - but I also wouldn't mind the overload of `blobstore` here, since `cmd/blobstore` hosts the API, and `internal/blobstore` provides the client to it. That feels in line with what `cmd/gitserver` and `internal/gitserver` are meant for, for example. 

No strong opinion on (2)

**Comment by varungandhi-src** [comment]
> but my initial inclination is to rather call it objectstore if we have to go with object

The most common usage in code referring to this package is referring to the `Store` type, so I don't want to have `objectstore.Store` in the name. This kind of guideline is also mentioned in [Effective Go](https://go.dev/doc/effective_go#package-names):

> The importer of a package will use the name to refer to its contents, so exported names in the package can use that fact to avoid repetition. (Don't use the import . notation, which can simplify tests that must run outside the package they are testing, but should otherwise be avoided.) For instance, the buffered reader type in the bufio package is called Reader, not BufReader, because users see it as bufio.Reader, which is a clear, concise name

**Comment by eseliger** [comment]
we could rename to `{blob|object|store.Client` perhaps?

**Comment by varungandhi-src** [comment]
AFAICT, we use the "Store" convention when it involves CRUD operations and "Client" when talking to 1st party and 3rd party services, so it would make sense for a _Store_ to internally contain a _Client_ based on whether it's talking to S3/GCS/blobstore.

I want to avoid the name punning/duplication because that has been cited as a frequent source of confusion whenever we've had someone new join the team and on-board onto the backend codebase, as it's hard to keep track of the same name meaning different things in different parts of the code as you're jumping around.

There's also this bit in [Effective Go](https://go.dev/doc/effective_go#package-names)

>  It's helpful if everyone using the package can use the same name to refer to its contents, which implies that the package name should be good: short, concise, evocative. By convention, packages are given lower case, single-word names; there should be no need for underscores or mixedCaps. Err on the side of brevity, since everyone using your package will be typing that name

**Comment by kritzcreek** [comment]
Thoughts:
- `uploadstore.Store` is a silly name, and `uploadsstore` definitely tripped me up
- `Store` is taken to mean db table wrapper in a lot of places, so I'd rather not reuse it here
- `blob.Storage` might be a way to keep the connection with the non-db "blobstore" concept, and still give a hint that something different is going on?

**Comment by varungandhi-src** [comment]
I don't think there is a single solution which will satisfy everyone, so I'm going to pick something in-between and merge it unless someone complains loudly.

1. Using `object` for the package name, with `object.Storage` for the main interface (instead of `object.Store` or `objectstore.Store` or `blobstore.Store`)
2. I've inlined the search related wrapper into internal/search in a new file `object_storage.go`
3. I've changed the names in the embeddings code to be similar to the search related code.

This fixes the poor `uploadstore` naming which I think we all agree on. I've also avoided the key-value terminology as requested.

**Review by kritzcreek — APPROVED** [review]

**Review by eseliger — COMMENTED** [review]
Not that comfortable with `object` as that reminds me too much of JS's `object` and doesn't really convey to me that this is related to storage (and really, access to blobstore), but I'm happy to agree to disagree :)

**Pull request merged**
