### PR TITLE
Improve toggle usability by allowing a clickable label

### PR DESCRIPTION
**Pull request by pjlast**
Solves #17133 

This adds 4 additional properties to the Toggle component, namely:
label
offLabel
helpText
offHelpText

If only label/helpText is supplied, it will be the text next to the Toggle. If offLabel/offHelpText is supplied in addition to label/helpText, label/helpText will be used when the toggle is on, and offLabel/offHelpText used when the toggle is off.

First draft used a clickable div for the label, but upon further reading it seems that clickable divs don't play well with screen readers, so I opted to resize the button itself instead. This required me to make some changes to the bar and knob css, but it keeps the final component to having 1 element with which a user can interact, which I think is most friendly to screen readers (altho my knowledge here is admittedly very limited, so take it with a pinch of salt).

### CODE REVIEW

**Comment by pjlast** [comment]
https://user-images.githubusercontent.com/6427795/142980452-37f84595-bd89-465d-9fb6-ced6221bc924.mov

Adding a quick recording just to show the result

**Comment by vanesa** [comment]
Hi @pjlast  thank you so much for your contribution! This PR fell through the cracks as we weren't notified about it. Please tag us with @sourcegraph/contribution-reviewers (as mentioned in our [contributing.md](https://github.com/sourcegraph/sourcegraph/blob/main/CONTRIBUTING.md) 😉 ) so we don't miss out on your awesome contributions in the future. I requested a review from a teammate. Thank you!

**Review by valerybugakov — COMMENTED** [review]
@pjlast just found it in my stack of unreviewed PRs 🙂. Do you think we can still update it to the mergeable state, or is it better to close it since it's quite old?

**Comment by pjlast** [comment]
Haha yes this is incredibly old. I'm going to rather close it. If we still want/need this, I'd rather reimplement it.

**Pull request closed without merging**
