### PR TITLE
searcher: remove unused dependency on dbconn pkg

### PR DESCRIPTION
**Pull request by keegancsmith**
In a recent incident it was bought up that hot fixing searcher had a risk since it speaks to the DB. I investigated and noticed it doesn't actually connect, but does have dbconn as an unused transitive dep.

This commit refactors out the bit of logic used by searcher into a pure package. To do so I did a few renames, but functionally there is no change in logic other than the searcher binary shedding some heavy dependencies.

Additionally I updated the go-dbconn-import check to ensure searcher isn't accidently using the database again.

Test Plan: CI

### CODE REVIEW

**Comment by keegancsmith** [comment]
@michaellzc FYI searcher doesn't speak to the DB. Are there deployment assets that we need to update to avoid db sidecars/etc?

@burmudar out of interest is `dev/check/go-dbconn-import.sh` still run in CI or do I need to update some bazel magic?

**Comment by burmudar** [comment]
> @michaellzc FYI searcher doesn't speak to the DB. Are there deployment assets that we need to update to avoid db sidecars/etc?
> 
> @burmudar out of interest is `dev/check/go-dbconn-import.sh` still run in CI or do I need to update some bazel magic?

@keegancsmith I believe we have a `nogo` linter that does that but let me double check and confirm

**Comment by burmudar** [comment]
> > @michaellzc FYI searcher doesn't speak to the DB. Are there deployment assets that we need to update to avoid db sidecars/etc?
> > @burmudar out of interest is `dev/check/go-dbconn-import.sh` still run in CI or do I need to update some bazel magic?
> 
> @keegancsmith I believe we have a `nogo` linter that does that but let me double check and confirm

@keegancsmith confirmed! see [dbconn nogo linter](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@748e8b226b4cf02f0610f7638ef268b3f72000eb/-/blob/dev/linters/dbconn/dbconn.go) and it is registered with `nogo` [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/BUILD.bazel?L304)

**Review by stefanhengl — APPROVED** [review]

**Comment by michaellzc** [comment]
> FYI searcher doesn't speak to the DB. Are there deployment assets that we need to update to avoid db sidecars/etc?

No sidecar, but we do have network policy in place to permit who can talk to db on Cloud.

The source of truth is here:

https://github.com/sourcegraph/sourcegraph/blob/1c5f545a4597a03a2b9df066017ef8351d0ad7b8/lib/servicecatalog/service-catalog.yaml#L46-L58

**Pull request merged**
