### PR TITLE
Design Refresh: Enable site-wide

### PR DESCRIPTION
**Pull request by umpox**
Checklist copied from https://github.com/sourcegraph/sourcegraph/issues/20846
  - [x] Migrate Bootstrap required SCSS variables like `$primary` and `$indigo` to our redesign variants `$redesign-primary`, `$redesign-indigo`: remove the `@if` statement from the `variables-redesign.scss` file.
  - [x] Disable redesign toggle. We can append `theme-redesign` to the DOM for the initial release, and we don't want anyone using the old design whilst we haven't yet removed those styles
  - [x] Change the implementation of the `useRedesignToggle` to always return `[true, ()=>{}]`.
  - [x] Fix search tests to pass when streaming search is enabled permanently
  - [x] Fix GlobalNavBar.test.tsx failing when redesign is enabled
  - [x] Fix Percy theme changing to work on pages where the search bar is not displayed
  - [x] Remove Percy redesign variants.
  - [x] Remove Chromatic redesign variants in Chromatic.story.tsx.

### CODE REVIEW

**Comment by umpox** [comment]
State of play:

- Failing integration tests in `client/web/src/integration/search-contexts.test.ts`
- Failing integration tests in `client/web/src/integration/search-onboarding.test.ts`
- Failing integration tests in `client/web/src/integration/search.test.ts`
- Failing unit tests in `client/web/src/nav/GlobalNavbar.test.tsx`

Note I have temporarily disabled Chromatic tests whilst fixing some problems here, to avoid the additional cost of 2k+ snapshots per commit

**Comment by umpox** [comment]
In preparation for fully enabling the refresh this PR is ready for review. 

Relevant Slack message: https://sourcegraph.slack.com/archives/C01TFNBHYCV/p1622634577169800

I'm keeping this in draft status for now, just to avoid somehow accidentally merging this!

**Review by eseliger — APPROVED** [review]
Very exciting! We should make sure to regularly rebase this PR onto main as changes for the redesign are still being merged.

**Review by valerybugakov — APPROVED** [review]
🚀

**Review by pdubroy — APPROVED** [review]
image

**Pull request merged**
