### PR TITLE
web: Add file static suggestions

### LINKED ISSUE #6837: Search suggestions: add common, static suggestions
#### Feature request description

In [RFC 14](https://github.com/sourcegraph/sourcegraph/pull/6836#pullrequestreview-322509521) and [RFC 15](https://github.com/sourcegraph/sourcegraph/pull/6836#pullrequestreview-322509521), it is shown that certain search filters would return commonly used suggestions. This is already done for the `lang:` filter. 

In particular, the `file:` filter is shown to suggest our default search filters such as "test files", "non-test files", "markdown files", etc.

cc @christinaforney

### PR DESCRIPTION
**Pull request by hadrian-git**
- Add `file` static suggestions, recommendations from #6837

Will look like the following after #6835 is merged:

Screenshot from 2019-11-26 13-20-52

Close #6837

### CODE REVIEW

**Comment by attfarhan** [comment]
Code LGTM.

But, there's one thing that doesn't quite match the RFC, which is understandable to me, but I think good to bring up as the current implementation feels a little bit incomplete: 

We have suggestions for excluding test files. This group would be called "Non-test files" and the value would be `-file:(test|spec)`, but I don't think we suggest negated filters at all. Should we add negated filters and corresponding suggestions?

@christinaforney would like to hear your thoughts on this!

**Comment by hadrian-git** [comment]
> Code LGTM.
> 
> But, there's one thing that doesn't quite match the RFC, which is understandable to me, but I think good to bring up as the current implementation feels a little bit incomplete:
> 
> We have suggestions for excluding test files. This group would be called "Non-test files" and the value would be `-file:(test|spec)`, but I don't think we suggest negated filters at all. Should we add negated filters and corresponding suggestions?
> 
> @christinaforney would like to hear your thoughts on this!

Sorry, I didn't understand. Are you not getting the static suggestion for `-file:`? or do we need to add other suggestions for negated filters?

**Comment by hadrian-git** [comment]
> Code LGTM.
> 
> But, there's one thing that doesn't quite match the RFC, which is understandable to me, but I think good to bring up as the current implementation feels a little bit incomplete:
> 
> We have suggestions for excluding test files. This group would be called "Non-test files" and the value would be `-file:(test|spec)`, but I don't think we suggest negated filters at all. Should we add negated filters and corresponding suggestions?
> 
> @christinaforney would like to hear your thoughts on this!

@attfarhan Sorry, I didn't understand, are you not getting the static suggestion for `-file:`? or do we need to add other suggestions for negated filters?

**Comment by attfarhan** [comment]
What I initially meant was that I'd expect `-file:` to have a different set of static suggestions, one of which would be "Non test files". But I think it's actually fine, since `-file:` will have "Text files" and "Test files" as suggestions, which serves the same purpose.

Sorry for the delay on this, I think it's good to merge!

**Pull request merged**
