### PR TITLE
authz: Add extra sub-repo test cases

### PR DESCRIPTION
**Pull request by ryanslade**
Add many more example protection table and confirm the paths we filter out
are what we expect.

## Test plan

Only tests were added

### CODE REVIEW

**Review by mollylogue — COMMENTED** [review]
This looks great! Thanks for doing this 🙏 How did you decide which test cases to include? Are you planning to add more/expand this to include other cases?

**Comment by ryanslade** [comment]
> This looks great! Thanks for doing this 🙏 How did you decide which test cases to include? Are you planning to add more/expand this to include other cases?

It looks like fewer tests since a few of them are combined into a single tests in our code because we can check more than one path per test. I think I covered all the path matching tests. The only ones we don't have here are for commit filtering and directory browsing which we'll have separate tests for anyway.

**Comment by mollylogue** [comment]
> > This looks great! Thanks for doing this 🙏 How did you decide which test cases to include? Are you planning to add more/expand this to include other cases?
> 
> It looks like fewer tests since a few of them are combined into a single tests in our code because we can check more than one path per test. I think I covered all the path matching tests. The only ones we don't have here are for commit filtering and directory browsing which we'll have separate tests for anyway.

Awesome. That makes sense 🙏

**Comment by ryanslade** [comment]
@mollylogue Can I get a ✅ if you're happy?

**Review by mollylogue — APPROVED** [review]
Thanks for doing this 👍

**Pull request merged**
