### PR TITLE
Update stalebot config

### PR DESCRIPTION
**Pull request by nicksnyder**
I am going to re-enable stalebot (we had this on our enterprise repo but have not re-enabled since we open sourced).

I have made the daysUntilStale more conservative and also removed exempt labels.

### CODE REVIEW

**Comment by slimsag** [comment]
I definitely won't oppose this because we've had this discussion in the past and I don't want to derail here.. but just for the record I feel I need to state I _really_ dislike stale bots _closing_ issues. https://twitter.com/sindresorhus/status/1082145283285250048 is one read that describes some of the problems

**Comment by nicksnyder** [comment]
I agree that closing an issue after only 30 days of inactivity is way too aggressive and annoying. With our current config it takes 120 days of inactivity before an issue is actually closed. 30 days before that happens (i.e. 90 days of inactivity), anyone involved in the issue will get a reminder because the bot will post on the issue, so if any human doesn't think the issue is stale then they can just remove the stale label or perform any other action. The lack of such action after 30 days is implicit confirmation that the issue is indeed stale/obsolete/unimportant.

I am happy to increase these constants if you think there is a better threshold to set (e.g. `daysUntilStale: 150` or `daysUntilClose: 90`) but I do think it is reasonable to straight up close issues if they have been inactive for a period of time despite everyone being reminded.

Having a bunch of old/unimportant issues open that we will never get to is just noise in our issue tracker.

Stalebot forces people to confront the uncomfortable reality that time is finite and certain things just aren't important enough to ever get done.

**Comment by slimsag** [comment]
Just to reiterate, I don't want to block this PR. We have discussed this in the past and I think fundamentally it boils down to a disagreement about how development should be done, and I think more people on the team agree with your viewpoint so I am 100% happy to concede.

My thoughts on the matter is that the problem arrises when you start searching across issues, only to find that the issue you ran into was already reported (sometimes multiple times) and closed without any resolution. You don't know if someone thought:

- "This is fine to be closed because it's no longer an issue."
- "This is fine to be closed because we don't plan to fix this because we don't care about it currently."

instead you just get:

- "This issue was closed by a bot <no explanation>."


I fully recognize time is finite and having a bunch of issues open that we never plan to work on is noisy, especially on GitHub's poor issue UX.

My suggestion would be that if we want someone to actually **do something** about an issue, we should aggressively notify them about it. Send the team an email every 7d about that issue until one of us finally does something about it. Otherwise, we neglect it and it is closed without any human involvement (which, personally, I think reflects very poorly on a project).

**Comment by slimsag** [comment]
Is it possible to determine which issues are closed by the bot and not a human?

**Comment by nicksnyder** [comment]
I don't feel blocked, but while we am thinking about it I do want to make it as good as it can be :)

I agree that it is better if a human takes an action (by either posting an update or closing the issue with an explanation) so I updated the stale text with an explicit call to action.

> instead you just get: "This issue was closed by a bot ."

I think it is clear in this case that it was closed for no particular reason and would be appropriate to re-open (or file a new issue).

> if we want someone to actually do something about an issue

One reminder should be enough to do something if it is important; otherwise we are just training people to ignore notifications. Ignoring a reminder is an implicit indication of something not being important.

> Is it possible to determine which issues are closed by the bot and not a human?

yes

image

**Comment by slimsag** [comment]
I mean to get a list of them, i.e. through search. I don't think it's possible unless we turn on `closeComment: true` and add something searchable

**Comment by slimsag** [comment]
Unfortunately looks like stale bot can't add a label when closing issues. How about adding a close comment like:

> Stale bot here, I am closing this issue due to inactivity.

Then I can find them with a query like:

```
is:closed is:issue in:comments "Stale bot here, I am closing this issue due to inactivity." 
```

**Comment by slimsag** [comment]
Thanks!

**Pull request merged**
