### PR TITLE
Fix: filters bar appearing when there are no filters

### PR DESCRIPTION
**Pull request by attfarhan**
Fixes https://github.com/sourcegraph/sourcegraph/issues/1764.

To fix the issue, I simplified how filters contributed from extensions are rendered by requesting `Contributions` in the `SearchResults` component and removing the `SearchFiltersContainer` component. The `empty` prop that `SearchFiltersContainer` had did not serve its purpose, as we cannot check whether a child component renders null from a parent component. Also, we never passed in the `scope` prop, so we didn't need to observe `scopeChanges`, which made the separate component unnecessary. LMK if I missed something @vanesa @slimsag.

### CODE REVIEW

**Comment by vanesa** [comment]
Thank you for simplifying the filters bar. Your fix would hide the filters bar if there are no filters contributed from the settings or extensions. However, I feel like we might be missing out on an opportunity to show the user that these filters exist. What do you think about adding some buttons that encourage to `add filters`, `activate extension filters` or `hide filters bar` instead whenever there are no filters? 
Adding this mockup to visualize my suggestion:

image


If `hide filters bar` is chosen, this choice would be saved in the user local storage. The filters bar would appear again as soon as the user adds filters later on.

**Comment by felixfbecker** [comment]
^ the suggestion to add a filter shouldn't look like a filter itself

**Comment by vanesa** [comment]
Yes I would ask @francisschmaltz to get UX right.

**Comment by attfarhan** [comment]
How is this a regression?

**Pull request merged**
