### PR TITLE
add postcss rule to transform px to rem

### PR DESCRIPTION
**Pull request by 5h1rU**
## Overview
Currently, **94 .scss files** on our codebase are using `px` as the unit of measurement. The `px` units do not scale according to the width of the browser window. Our focus is to convert all those px to their `rem` equivalent.

This approach uses a [postCSS plugin](https://github.com/cuth/postcss-pxtorem) that replaces those `px` to the equivalent `rem` value on compile time.

### Example Before
Screen Shot 2021-02-02 at 1 39 12 PM

### Example After
Screen Shot 2021-02-02 at 1 41 17 PM

## Progress
- [ ] Approved by a frontend engineer
- [ ] Approved by a designer

Closes https://github.com/sourcegraph/sourcegraph/issues/16602

### CODE REVIEW

**Comment by felixfbecker** [comment]
Using a PostCSS plugin seems to be a bit round-about - why not update our code instead?
Here are some disadvantages I see with using a PostCSS plugin:
- The values in the SCSS files and in the browser dev tools would use different units (with no immediately visible indication why)
- `rem` scales relative to the font size of the root element. The PostCSS plugin has no knowledge of the root font size, so if we ever change that, it would start behaving weirdly. It probably only works because we happen to use 16px.
- We already use Stylelint to enforce specific units depending on the props, which is confusing if we then actually transform it to a different unit.
- It adds one more transformation step to check that could be the cause of a bug when debugging.
- What if there's a situation in which we actually want to use `px` because it should not scale with the root font size? For example, borders or horizontal divider lines I guess should generally be a 1px hairline, not scale with the root font size.
- It masks the fact that these elements may be scaled according to the root font size in the code (which is a bit counter to our goal of intentionally designing for accessibility and actively thinking about it when writing the code, making sure it doesn't break).
- `rem` might not be the best choice for all current instances of `px`. E.g. for `<code>`, it will probably actually be better to convert it to `em`, so that it can be used inside larger or smaller text too (`<h2>` or `<small>`) and will scale proportionally, not always jump to 12px. While a `line-height` is ideally not set at all (inherited) or also set to a unitless value to scale proportionally.

> The px units do not scale according to the width of the browser window.

Note that `rem` doesn't scale to the width of the bowser window either (that's the `vw` unit), it scales to the root font size (which is why it is important for accessibility, because the default root font size can be changed in browser settings).

**Comment by 5h1rU** [comment]
Thanks @felixfbecker

1. I think this is a good option and less error-prone for this kind of change. Modify 92 files by hand needs some extra attention.

2. I agree this shouldn't be forever as part of our workflow. This can be a solution while I do the modifications manually.

3. I'm not again to modify the code, but I see this implementation as a quick win.

4. Many of the disadvantages mentioned can be addressed with the [config options](https://github.com/cuth/postcss-pxtorem#options). (e.g., use ```propList: ['font', 'font-size'],``` as part of the config and keep the other units without modification would be better.)

Another solution that is more aligned with the final purpose is to run a script before compile-time, rewrite the .scss files instead of the compiled file, and push those changes as part of the PR.

Thoughts?

**Comment by 5h1rU** [comment]
After thinking more about a better approach, I decided to open [this PR.](https://github.com/sourcegraph/sourcegraph/pull/17933). Please take a look.

**Comment by 5h1rU** [comment]
Since #17933 is easier to review and closer to our goals, I'm closing this.

**Pull request closed without merging**
