### PR TITLE
Always enable indexed search

### PR DESCRIPTION
**Pull request by keegancsmith**
# How-to Enable Indexed Search

Set the environment variable `INDEXED_SEARCH=t`.

This can be done by adding the flag `-e INDEXED_SEARCH=t` to your `docker run` for Sourcegraph.

Fixes https://github.com/sourcegraph/enterprise/issues/13516

### CODE REVIEW

**Comment by keegancsmith** [comment]
I am slightly concerned that this may increase our memory requirements for sourcegraph server. But clearly having indexed search is a win. At the same time normally the smaller scale of a single docker image doesn't usually need indexed search.

**Comment by dadlerj** [comment]
Interesting. My default answer is it's better to have in. In your opinion, would it make sense to wait to release until we can add some config option that lets admins disable it? 

Perhaps it makes sense to just merge, and for you to write up a comprehensive test plan in @attfarhan's release doc so we can see impact (e.g. for us to try on all of our laptops, on VMs with varying specs, or whatever else)?

This is more of a question for the eng team than for me though, so I leave the ultimate call on next steps up to you!

**Comment by beyang** [comment]
Agree we should test this in the release plan (something along the lines of add 50 repositories to your instance, trigger a search index, and look at RAM usage). If that's not doable, I think adding an escape hatch flag would be fine.

**Comment by dadlerj** [comment]
@keegancsmith do you think this can go in/be tested before release?

**Comment by keegancsmith** [comment]
Sorry about the slow reply. Yeah this will have to be tested. I should essentially revert this PR and invert the conditional so we always enable indexed search, but can opt out of it. I don't feel comfortable landing this change with one day left until release. I'll rather wait until after the release (it can be included in a point release). Personally I'd like to actually measure the difference, rather than only relying on the more binary process of testing.

BTW do we have any metrics on number of enabled repositories in server instances? It would help the measurement + guess at impact great.

**Comment by dadlerj** [comment]
Sounds good. For the metrics, no, that's not [something we capture](https://about.sourcegraph.com/docs/usage#server-pings). You are interested in getting a sense for averages?

**Comment by francisschmaltz** [comment]
Will the message `This Sourcegraph site doesn't support indexed search. SeePR #239for information on how to enable it.` Be in the release or should it change to reflect this has been pushed back?

**Comment by francisschmaltz** [comment]
> Is it better to link to this PR, create an issue, or directly mention in the message how to enable it?

I think we should just reword it. The wording now makes it seem like there is a way to turn it on – not a PR for a future feature.

**Comment by keegancsmith** [comment]
I see we directly link to this PR. So I have updated the description to include instructions on how to enable.

**Comment by francisschmaltz** [comment]
@keegancsmith when adding the flag to docker run I still don't have indexing enabled. 
screen shot 2018-10-11 at 2 04 36 pm

**Comment by soggysec** [comment]
Using the -e INDEXED_SEARCH=t worked for me. Complete CLI:

```bash
docker run --publish 7080:7080 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph --volume /var/run/docker.sock:/var/run/docker.sock -e INDEXED_SEARCH=t sourcegraph/server:2.11.2
```

**Comment by keegancsmith** [comment]
Thanks @soggysec. I see enabling indexed search did give you memory issues like I feared above :) https://github.com/sourcegraph/sourcegraph/issues/435

A good indicator that we need to add some sort of memory pressure detection/etc before enabling by default.

**Comment by soggysec** [comment]
@keegancsmith I think you're right. I do have a fairly large repo, which is probably a good part of the problem. Is there a good way of seeing the indexing container's mem usage?

**Comment by beyang** [comment]
This PR is 15 days old--can we merge it yet?

**Comment by keegancsmith** [comment]
Superseded by https://github.com/sourcegraph/sourcegraph/pull/502

**Pull request closed without merging**
