### PR TITLE
notebooks: auto-fill inputs from file url

### PR DESCRIPTION
**Pull request by novoselrok**
This PR adds support for parsing the Sourcegraph file URL and auto-filling the file block inputs. ~~The file URL is ephemeral and it is removed after the inputs are saved. This is done to simplify the implementation, otherwise we would need to introduce bidirectionality between the file URL and the block inputs.~~

Instead of the previous implementation we opted to detect the paste event on the block itself. This should reduce the confusion about the additional input.

Demo:

https://user-images.githubusercontent.com/6417322/151921631-e51494da-ad3c-4339-85e3-2b262dcef3db.mov

### CODE REVIEW

**Comment by novoselrok** [comment]
@marisak @benvenker I have `Paste a Sourcegraph file URL to auto-fill the inputs above` as the input label. What do you think? It might feel a bit clunky, but I can't come up with anything more succinct.

**Comment by marisak** [comment]
> @marisak @benvenker I have `Paste a Sourcegraph file URL to auto-fill the inputs above` as the input label. What do you think? It might feel a bit clunky, but I can't come up with anything more succinct.

There are a couple ways we can go here, depending on the amount of detail that would help someone understand how the file URL field will behave. 

Right now, the `Paste a Sourcegraph file URL...` text is styled like help text rather than a label. If we were to keep it styled as-is, I would suggest something like `Or, paste a Sourcegraph file URL to auto-fill the repository and path.` This is longer than what Rok currently has, but I think it gives more insight into the behavior. 

Another option would be to give the URL input a label like `Sourcegraph file URL (optional)`. 

Or, we could have both a label and help text! The label could be as above (`Sourcegraph file URL (optional)`) and the help text could be `Paste a Sourcegraph file URL to auto-fill the repository and path.` Illustration of what this could possibly look like [here](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=1580%3A9256). 

Again, this comes back to the level of detail that would be most helpful. One thing that I noticed while testing this change is that it's not clear how to change the file once one has been selected; since the URL is "ephemeral" it can no longer be edited via URL - you have to use the repo/path inputs. More on that [here](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=1580%3A9256).

**Comment by marisak** [comment]
Additional comments: 
- Are we displaying error messages? I tried pasting in a few non-Sourcegraph-file URLs and didn't see any messages. Happy to contribute copy if that would be helpful. 
- Is it possible to remove a line range?

**Comment by novoselrok** [comment]
@marisak, thanks for the comments. Some thoughts:

> Paste a Sourcegraph file URL to auto-fill the repository and path.

We would need to mention the revision and line range inputs as well. Then it would be something like: `Or, paste a Sourcegraph file URL to auto-fill the repository, file path, revision, and line range.` 

> One thing that I noticed while testing this change is that it's not clear how to change the file once one has been selected; since the URL is "ephemeral" it can no longer be edited via URL - you have to use the repo/path inputs.

Yeah, this is what I expected the flow to be. You paste the URL -> You edit the auto-filled outputs -> Save. The file URL should be seen as the starting point (or the initialization step) and not _the_ editing experience. All editing should be done through the 4 provided inputs (repository name, file path, revision, line range). I also considered deleting the file URL input value immediately after pasting, but that seemed too aggressive. User could also decide to override the existing inputs by pasting a new URL.

> Is it possible to remove a line range?

Yes, but through the block menu.

> Are we displaying error messages?

Not right now, because there is only 1 possible error: Invalid file URL. It seemed kind of redundant to add this on every error, but I can if it'll make it more clear.

**Comment by novoselrok** [comment]
One additional behaviour we can explore: instead of having a dedicated input for pasting the url, we can try and do it without. Instead, the user would select the file block and then press (CMD/CTRL + v) to paste the url. We can intercept the paste event, see if it contained a file URL, and auto-fill the inputs. We would still need to add some helper text to indicate that this is possible. I think this would be an elegant solution, but I'm sure not everyone will agree 😄

**Comment by benvenker** [comment]
Sorry to be late to the game. I have a few thoughts:
1. I'm not sure it's super likely that I'm pasting in a URL and then want to make changes to it right after, which makes me think having a Sourcegraph URL block type might make sense. I do see how you might want to change it after you've pasted it in at some point, and so keeping the edit menu working makes sense, but it might simplify this UX to just make it clear we're parsing a URL and remove configuration options unless they're asked for by the user clicking edit. We should validate that if we went this way though.
2. I like @novoselrok's latest idea, though it probably would be something users would have to be educated on.
3. If we keep the UX as-is, the (seemingly) small change I would suggest is to move the URL input to the top, since the parsed URL "flows" into the inputs. But that just feels more natural to me from an "understanding what's going" perspective.

**Comment by novoselrok** [comment]
@benvenker The more I think about it, the more I like the pasting solution. What do you think about including a small info snippet at the top to make the user aware of this? We can tweak the exact text.

Screenshot 2022-01-31 at 08 18 50

If this seems confusing, we can keep the existing file URL input and just move it to the top.

**Comment by benvenker** [comment]
I think this looks great. For the text, maybe:
"Enter file and range info, or select the block and paste in a Sourcegraph URL containing a range (Cmd+v)"

(but use the fancy mac Cmd symbol)

**Comment by novoselrok** [comment]
Converting to draft while I update with the latest changes. @limitedmage You can hold off on the code review for now.

**Comment by novoselrok** [comment]
@benvenker @marisak I updated the PR description and added a new video.

@limitedmage Ready for review 🙂

**Review by limitedmage — APPROVED** [review]
This works great except for one issue I noticed: Is there a way to stop the autocomplete dropdowns from appearing on paste? It's a bit annoying 
image

**Pull request merged**
