### PR TITLE
redispool: Wait SRC_REDIS_WAIT_FOR before quitting sysreq check

### PR DESCRIPTION
**Pull request by tsenart**
This commit makes our `redispool` sysreq check wait for `90s` by
default instead of `5s` and allows admins to set a `SRC_REDIS_WAIT_FOR`
environment variable to control this timeout if it turns out the new
default isn't enough.

Addresses part of #2904. The next step is make Redis start-up faster by
ensuring it maintains a small AOF file that is short to process on
startup (#3300).

Additionally, repo-updater also uses redis, but doesn't currently
integrate with the sysreq package. I'll be reviewing whether we still need
to use redis at all in it (it's currently used for caching GitHub API
responses). If we still need it, I'll run sysreq checks in repo-updater,
otherwise, I'll get rid of the redis dependency there.

### CODE REVIEW

**Comment by tsenart** [comment]
@beyang: While investigating if we still need Redis as a dependency in repo-updater, I came found that we introduced Redis backed caching in our `github.Client` in https://github.com/sourcegraph/sourcegraph/pull/988.

I'm confused as to what the intent of that caching layer was relative to the caching of the computed permissions in the `github.Provider`. Could you elaborate on how these two cache layers play together and whether we can get rid of the `github.Client` caching?

**Comment by tsenart** [comment]
OK, so it seems that we still need caching in the external clients used in repo-updater because of the repo lookups we do in sourcegraph.com:

https://github.com/sourcegraph/sourcegraph/blob/d928a7caac7d2df3ff074c295db78edb3677dfa2/cmd/repo-updater/repoupdater/server.go#L423

The question remains, though, do we need multiple caching layers? The custom github client caching layers seems to have been added for authz only, not for this use case of sourcegraph.com which was already covered with our use of `httpcli.CachedTransportOpt` as part of our default client.

**Comment by tsenart** [comment]
@keegancsmith: PTAL again

**Comment by tsenart** [comment]
> If we still need it, I'll run sysreq checks in repo-updater,
otherwise, I'll get rid of the redis dependency there.

We can just rely on the already present `WaitForFrontend`, since the frontend itself waits for Redis.

**Comment by beyang** [comment]
> I'm confused as to what the intent of that caching layer was relative to the caching of the computed permissions in the github.Provider. Could you elaborate on how these two cache layers play together and whether we can get rid of the github.Client caching?

The authz provider cache caches entries specifically for the purposes of computing permissions. The reason this exists is because (1) we want to be efficient about how we compute permissions (minimize the # of API requests necessary) as computing permissions often happens on-demand when a user issues a search query and (2) we want the cache TTL to obey whatever the site admin sets in authz config (setting a longer TTL will reduce the API request volume, which is often necessary for larger installations).

The GitHub client cache just caches requests to GitHub. My understanding is that it mainly uses shorter term caching. I believe if you want to remove the dependency of repo-updater on redis, you just need to create a cache-less GitHub client.

**Comment by tsenart** [comment]
> The GitHub client cache just caches requests to GitHub. My understanding is that it mainly uses shorter term caching. I believe if you want to remove the dependency of repo-updater on redis, you just need to create a cache-less GitHub client.

All of our external http clients already have HTTP caching using https://github.com/sourcegraph/sourcegraph/blob/d928a7caac7d2df3ff074c295db78edb3677dfa2/internal/httpcli/client.go#L73

What was the reasoning for changing the `github.Client` to do its own internal caching when that was already in place? I guess we can remove the special internal caching from the `github.Client` (and `gitlab.Client` if there's any)?

**Pull request merged**
