### PR TITLE
codeintel: Update index UI pages

### PR DESCRIPTION
**Pull request by efritz**
Redesign and clean-up of the code intel administration UI.

Screen Shot 2020-10-23 at 2 11 36 PM

Screen Shot 2020-10-23 at 2 11 39 PM

### CODE REVIEW

**Review by Strum355 — APPROVED** [review]
A casual +1638 -1762

img

**Comment by efritz** [comment]
> A casual +1638 -1762

Just eric doing eric things

**Comment by felixfbecker** [comment]
And it's bug-free too according to Sonarcloud!

**Comment by efritz** [comment]
You heard it here first. Anything that seems wrong is a feature.

**Review by tjkandala — APPROVED** [review]

**Pull request merged**
