### PR TITLE
executor/apiclient/queue: submit `PrometheusMetrics` on multi-queue heartbeat

### PR DESCRIPTION
**Pull request by sanderginn**
- Closes https://github.com/sourcegraph/sourcegraph/issues/53092

That'll do it.

## Test plan
- [ ] Deploy nightly image to dogfood and confirm metrics submitting + autoscaling

### CODE REVIEW

**Comment by sanderginn** [comment]
Current dependencies on/for this PR:
* main
  * **PR #53183** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/53183" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/53183?utm_source=stack-comment).

**Review by Piszmog — APPROVED** [review]
Good catch! Thank you for the quick fix!

**Comment by sanderginn** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/pull/53197

**Comment by sanderginn** [comment]
(the branch name was too long and graphite isn't letting me update the pr)

**Pull request closed without merging**
