### PR TITLE
migrations: move privileged sql to separate files

### PR DESCRIPTION
**Pull request by kevinwojo**
Some of our customers have some security restrictions around their Postgres DB deployments where an application user should have the minimal set of permissions.

I think it's reasonable to grant the service account users `ALL` on their `DATABASE` but having the ability to managed the instance may become problematic.
``` sql
GRANT ALL PRIVILEGES ON DATABASE sourcegraph TO sourcegraph_user;
```

In our pre-packaged deployments, we run CodeIntel DB and the Sourcegraph DB (pgsql) with `SUPERUSER` privileges which allows our migrations to fully manage the respective `DATABASE`s. This is convenient but falls down when a customer requires a dedicated application user for the database instance.

I'm [currently drafting some instructions](https://github.com/sourcegraph/sourcegraph/pull/30124) on how to have a database administrator setup a dedicated service user and database as `SUPERUSER` and delegate access to the `DATABASE` to the service user.

The goal is to have some light tooling around to assist the customer on setting up the databases. This (not yet created) tooling would skip the first migration of each DB (put an entry in `schema_migrations` with "dirty=false"). 

An unprivileged service account need to skip these migrations:

 | DB | Migration | Reason |
 | ----| -----------| -------- |
 | frontend | 1528395833_privileged_initialization.up | Creates extensions and comments on the extensions. This can only be done by a superuser. |
 | frontend | 1528395862_remove_sg_service_role.up | Attempts to drop a ROLE if it exists. This can only be done by a superuser as it's an instance-wide structure. |
 | codeintel | 1000000014_privileged_initialization.up |  Creates extensions and comments on the extensions. This can only be done by a superuser. |

### CODE REVIEW

**Comment by efritz** [comment]
@kevinwojo Some of the effort I'm doing in https://github.com/sourcegraph/sourcegraph/pull/29831 will help make this a lot easier. We can mark certain migrations as "skippable" if there's a SKIP_SUPERUSER_MIGRATION envvar set in the `migrator` instance (or on app startup while they still perform migrations).

**Comment by kevinwojo** [comment]
Hey @efritz

> @kevinwojo Some of the effort I'm doing in #29831 will help make this a lot easier. We can mark certain migrations as "skippable" if there's a SKIP_SUPERUSER_MIGRATION envvar set in the `migrator` instance (or on app startup while they still perform migrations).

Groovy! I think this would be a really nice to have feature.

In the interim, is it worth trying to get _this_ PR merged? I was hoping to have a near-term solution to ease this burden from our CS/CE folks. 

Right now I'm running up against [`ErrMultipleRoots` ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d182c62eac4c9552fac913cd2f0aafecc712f13c/-/blob/internal/database/migration/definition/read.go?L393) which pokes a hole through my understanding of how our flat-file migration system works. I assumed that the first file in sort-order becomes the "root". Out of curiosity what is the behavior here?

**Comment by efritz** [comment]
@kevinwojo 

The only issue here I see (or thing that makes me immediately uncomfortable) is that you're redefining historic migrations. This will interfere with the squash operation (which I think is currently broken anyway), but we'll have to teach it how to separate these migrations otherwise we'll just merge them back into one SQL file the next time we clean up our migration chains. I'm not sure if there other downstream effects of doing this (it might be safe because it's specifically the _first_ one).

How near-term would you like? I'm targeting the upcoming release for all this work, if that's soon enough.

**Comment by efritz** [comment]
> I assumed that the first file in sort-order becomes the "root". Out of curiosity what is the behavior here?

That was the _implicit_ assumption, which is now required in the metadata preamble of every `*.up.sql` file (except the first one). Open up the second migration and see a block surrounded by `-- +++` declaring its parents.

For now it's redundant based on the same information in the filename, but we'll eventually get rid of having a single order of migrations so that two developers merging new migrations at similar times don't crash into each other so easily.

**Comment by kevinwojo** [comment]
@efritz I got up to speed with where we are at (sorry took me a while 😆) . I am okay moving forward with your plan. Next release is totally fine. We **_have_** a process now, it's just not as smooth. This is totally fine!

**Pull request closed without merging**
