### PR TITLE
search: remove ad-hoc Empty check

### PR DESCRIPTION
**Pull request by rvantonder**
Stacked on https://github.com/sourcegraph/sourcegraph/pull/22940.

There is inline logic to check whether a pattern is "empty". What this is really checking is that the absence of a pattern and file patterns returns no results, when we run a text search. Removing this naively [breaks things](https://buildkite.com/sourcegraph/sourcegraph/builds/101957#d4175d74-b34e-4b40-8bf1-1f02196b3df4/2088). 

This PR promotes this logic and removes the inline check.

### CODE REVIEW

**Comment by camdencheek** [comment]
What about a query like `type:file repo:sourcegraph/sourcegraph@v3.27.0`?

- The linked code only returns early if the whole query is empty (I think), so this doesn't get caught by the parser.
- The `IsEmpty()` appears to only check for empty pattern and file filters, so would return early for this query (I think)

I think those together mean we'd now be returning results for this query when previously we wouldn't be

**Comment by rvantonder** [comment]
@camdencheek hang on, I haven't requested review yet :-)

**Comment by camdencheek** [comment]
lol whoops. Recently added myself to codenotify and forgot how that works

**Comment by rvantonder** [comment]
Need to approach this a different way.

**Pull request closed without merging**
