### PR TITLE
chore: Use httpserver package in frontend startup

### PR DESCRIPTION
**Pull request by efritz**
Cleaning up the frontend startup by replacing the ad-hoc httpServers implementation with the internal/httpserver package.

### CODE REVIEW

**Review by unknwon — APPROVED** [review]

**Review by keegancsmith — APPROVED** [review]
LGTM. Mini code review on httpserver pkg:

- Looks clearer to me to rather have a `httpserver.New(net.Listener, *http.Server)`. Seems redundant to have a `httpserver.Options`.
- I would of expected `NewFromAddr` to not return an error, and rather only error out once `Start` is called. However, I see how that makes thing more complicated. A tip to making it possible in a clean way is store `func() (net.Listener, error)` instead of `net.Listener` on `server`.
- You should document that the handler is wrapped in `ot.Middleware`. It looks like we have `ot.Middleware` twice now, since `make*API` functions here already include it. Any negative effects from that?

**Comment by efritz** [comment]
@keegancsmith Applied your suggestions, could you take another look?

**Review by keegancsmith — APPROVED** [review]
LGTM. Thanks for changing, nice to have less need for error handling everywhere. Was the `ot.Middleware` in `httpserver` unintentional? I see that is gone now. Also did you rebase/merge in main? I think there might be a new user of `httpserver` pkg introduced yesterday.

**Comment by efritz** [comment]
> Was the ot.Middleware in httpserver unintentional? I see that is gone now.

I removed it implicitly but kept it back where it mattered (non-health-endpoint-only servers).

**Pull request merged**
