### PR TITLE
add code folding support

### PR DESCRIPTION
**Pull request by taras-yemets**
Makes use of the CodeMirror language packages to support code folding.

https://user-images.githubusercontent.com/25318659/215511464-7a7ba1a9-5112-46b9-84c6-7b66c3fb280d.mov

## Test plan
Tested manually (video attached).

## App preview:

- [Web](https://sg-web-taras-yemets-code-folding.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.17% (+4.87 kb) | 7.02% (+0.99 mb) 🔺 | 8.68% (+0.99 mb) 🔺 | 15.77% (+114) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/taras-yemets/code-folding/compare-report.html;tab=live_object) for a full comparison between the commits 15756b2 and 7e7805d or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by taras-yemets** [comment]
> ## Bundle size report 📦
>| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.17% (+4.87 kb) | 7.02% (+0.99 mb) 🔺 | 8.68% (+0.99 mb) 🔺 | 15.77% (+114) 🔺 |



1. We can probably reduce the initial footprint dynamically [importing `languages`](https://github.com/sourcegraph/sourcegraph/blob/15756b2ba3d0c50d5f137d36b0d18bfbbfa7eccc/client/web/src/repo/blob/codemirror/code-folding.ts#L2).
2. The list of added language packages is extensive, but [only one language package is fetched per file](https://github.com/sourcegraph/sourcegraph/blob/15756b2ba3d0c50d5f137d36b0d18bfbbfa7eccc/client/web/src/repo/blob/codemirror/code-folding.ts#L57).

**Comment by philipp-spiess** [comment]
Interesting, thanks for investigating, @taras-yemets!

It'd really be a shame if we had to pull in custom language parsing information when we already use tree-sitter on the backend and run over the file anyways, but I do understand the constraints in which we have to work here.

I wonder how big the difference is between treesitter supported languages and codemirror supported languages?

Also, what's the usual size of a single language package? All blob views will become slower since they now need to download these packages (maybe they can be lazily loaded though?)

**Comment by taras-yemets** [comment]
Thanks for your feedback, @philipp-spiess! 

>It'd really be a shame if we had to pull in custom language parsing information when we already use tree-sitter on the backend and run over the file anyways

Totally agree. This PR is a prototype of minimum developer effort for adding code folding support. It's not intended to be merged (I should have added this to the description).

> I wonder how big the difference is between treesitter supported languages and codemirror supported languages?

Tree-sitter has a much longer [list support of supported languages](https://tree-sitter.github.io/tree-sitter/#parsers). 

> Also, what's the usual size of a single language package?

E.g., `@codemirror/lang-cpp` is 303.3kB minified and 98.4kB minified and gzipped.

> All blob views will become slower since they now need to download these packages (maybe they can be lazily loaded though?)

In this prototype we load one language package per file (https://github.com/sourcegraph/sourcegraph/pull/47108#issuecomment-1408855445).

**Pull request closed without merging**
