### PR TITLE
[Search Jobs]: Add special zero state for the initial empty state

### PR DESCRIPTION
**Pull request by vovakulikov**
[Designs](https://www.figma.com/file/H4ezuXmEvVeoC6UaiNSbEa/Search-jobs-UI?type=design&node-id=1757-14620&mode=design&t=lcQ7R42aABKQGzA0-0)

This PR adds a special zero state when we have no filters and have no items in the search jobs list page. See screenshots below

| Type | Light | Dark | 
| --- | ------ | ------ |
| No items |  Screenshot 2023-09-11 at 17 42 03 | Screenshot 2023-09-11 at 17 41 54 |
| No items because of filters | Screenshot 2023-09-11 at 17 42 12 | Screenshot 2023-09-11 at 17 42 19 |

## Test plan
- Run local sourcegraph client by running `sg start`
- Go to the `/search-jobs` (note that you have to have `searchJobs:true` in your experimental feature flags section in the settings)
- Check different zero states in both dark and light themes

### CODE REVIEW

**Comment by vovakulikov** [comment]
@rrhyne we've discussed previously that we will use SVG version of the new zero state but I found it difficult to fight with wrapped SVG text and used just compressed PNG version (it's ~20kb, even smaller compared to SVG with text so there should be no size problem).

**Comment by rrhyne** [comment]
@vovakulikov let's remove the lighthouse. It doesn't fit with anything else in the application. 

Also, the header should be body-color and the header can be an h2. I think this is a custom size?

**Comment by vovakulikov** [comment]
>@vovakulikov let's remove the lighthouse

@rrhyne Just to be clear, what do you suggest to use instead? Just text without icon? 

**Side note:** We don't have any standard zero state pattern really, every place in the app does it differently. I tried to standardise some zero state in the app but didn't get any big feedback about it. My personal feedback that our current zero states are very boring and don't have any structure. (boring in this case doesn't mean good unfortunately, this understandable because nobody had time/love for this part of UI), if you can help me / guide me to come up with a better zero state I would be very appreciated. 

> Also, the header should be body-color and the header can be an h2

Got it about color, I used h3 because in Figma we use h3, I will adjust colors and change it to h2, thanks

**Review by valerybugakov — APPROVED** [review]

**Comment by vovakulikov** [comment]
I adjusted zero state heading size and going to merge this, if there will be any changes about this we can always make them in a follow up PR

**Pull request merged**
