### PR TITLE
added documentation button to site-admin panel

### PR DESCRIPTION
**Pull request by coury-clark**
Based on some customer [feedback](https://sourcegraph.slack.com/archives/C0W2E592M/p1631545290120100) it seems like the official Sourcegraph docs aren't necessarily intuitive or obvious that they are hosted separately from the installation.

This just adds a button to the site-admin panel that directs them to `docs.sourcegraph.com`.

cc @rrhyne Any issues from design perspective?

CleanShot 2021-09-13 at 11 38 13

### CODE REVIEW

**Comment by bobheadxi** [comment]
We should point them to `/help` instead (also linked to from the user dropdown), which will lead them to a versioned version of the docs. For example, https://demo.sourcegraph.com/help goes to https://docs.sourcegraph.com/@v3.31.0

image

**Review by bobheadxi — APPROVED** [review]
Nice!

**Comment by rrhyne** [comment]
That's fine, but it's going to get missed there. We include it in the top-right menu for unauthed users. It should probably appear there for authed users as well.

image

**Comment by coury-clark** [comment]
> That's fine, but it's going to get missed there. We include it in the top-right menu for unauthed users. It should probably appear there for authed users as well.

@rrhyne the thought here was just to group it with the other admin tools just for those users, not necessarily that this would be the best place in general. Happy to defer to the owning team for anything else, but barring any problems I'm going to merge this on the off chance this can help out any admins!

**Review by eseliger — APPROVED** [review]

**Comment by 5h1rU** [comment]
Since this is an external link, should we open it as an external page?

**Pull request merged**
