### PR TITLE
fix bad link

### PR DESCRIPTION
**Pull request by DaedalusG**
This is being interpreted as an active hyperlink -- as a result users will be directed to an insecure site

I wonder if other such bad links exist in the docs 🤔 

## Test plan
locally tested

### CODE REVIEW

**Comment by DaedalusG** [comment]
https://www.loom.com/share/cf8d3ccc600a477fa532c26971f0c0e5

**Comment by sqs** [comment]
Because it uses example.com, which is a domain that is specifically reserved for example purposes and can't be owned by anyone (including a bad actor), this is not actually insecure. As long as we use example.com or subdomains of example.com, it's fine. If we use something else like sourcegraph.mycompany.com, then it would indeed be insecure because some bad actor could own `mycompany.com`. (Let me know if you are seeing something different here.)

But it can be confusing. I see other places it is used at https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+repo:sourcegraph/sourcegraph%24+f:%5Edoc/+%5Cshttps://sourcegraph.example.com&patternType=regexp&sm=0&groupBy=repo. Overall, I don't think it's that confusing, and it does make it easy to right-click on the link and copy it, then paste it with your actual domain replaced.

My vote would be to keep it as-is, but I don't feel strongly here and would love to hear what you think.

**Comment by DaedalusG** [comment]
@sqs I was worried someone might nerd snipe me with Sourcegraph itself! -- I can go through and fix these 👍 -- will add the changes to this branch. _Or maybe use a batch change_

**Comment by DaedalusG** [comment]
Nice use of insights, I didnt realize it had the capture group function 🔥

**Comment by DaedalusG** [comment]
Used this to practice my NeoVim @sqs 😈 (_I'm still not fast at it 😆, but I feel cool_)

**Comment by sqs** [comment]
@cla-bot check

**Pull request merged**
