### PR TITLE
build: remove circular imports in client/*

### PR DESCRIPTION
**Pull request by jbedard**
Circular dependencies won't work when compiling with bazel. I found these pretty quick, I assume there's more to come.

## Test plan

CI

## App preview:

- [Web](https://sg-web-bazel-circular-imports.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.01 kb) | 0.00% (+0.01 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/bazel-circular-imports/compare-report.html;tab=live_object) for a full comparison between the commits d9d6dc9 and 6f9fff6 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by valerybugakov — APPROVED** [review]
Thanks! We probably need to enable/implement an ESLint that would ban such imports.

**Comment by jbedard** [comment]
I've fixed the merge conflicts and lint issue (import ordering).

**Comment by jbedard** [comment]
I've added some more fixes to `client/wildcard`, I'm not sure why I didn't see those earlier.

**Review by valerybugakov — APPROVED** [review]

**Pull request merged**
