### PR TITLE
App: Add new steps (setup pages) to the app setup flow

### PR DESCRIPTION
**Pull request by vovakulikov**
Closes https://github.com/sourcegraph/sourcegraph/issues/52414
Closes https://github.com/sourcegraph/sourcegraph/issues/52418

This PR simply adds a few new steps to the app setup flow. It also updates previous steps' layouts in order to make them accessible from small size/tablet screens (I know that Sourcegraph app won't likely be running on tablets, but just in case if a user doesn't have a big screen)

About Sourcegraph extension step → VSCode → Connect to app → auth page → VS code → next step. It turned out that we currently don't read any query param in web view. It makes me think that there is a limitation in vs code review about this. If this is correct, we can't redirect to the final screen automatically. I will keep working on this in a follow-up PR. 

## Test plan
- Check the setup flow screens/UI (check that all screens look ok on big/middle/small viewports)

### CODE REVIEW

**Comment by sourcegraph-buildkite** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.04% (+5.92 kb) | 0.05% (+5.92 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vk/update-app-setup-flow/compare-report.html;tab=live_object) for a full comparison between the commits bc3e37d and 27dc944 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by almeidapaulooliveira** [comment]
Thanks, Vova. Is it possible to use the same font family we use on the About site for wizard titles and text? I know isn't usual for the product, but since this visual is very much related to Cody's and Sourcegraph's visual identity, it would make more sense visually.

**Comment by vovakulikov** [comment]
@almeidapaulooliveira Oh, sorry, I missed this part. Yeah, I think the answer to this is - this is possible, but we would like to avoid this. Historically we don't use any custom fonts in the app, even for advertising purposes. Custom fonts require a good preparation step (strip all non-used letter sets, and font-weight variation) in order to avoid big bundle size (even if we load them in an async way, we would notice a font flash when the custom font is loaded), Also, in this case, we would like to load custom font only when it's needed (when setup isn't finished and rendered), I think at the moment we don't have good helpers for this.

If the standard native Apple font is problematic for the setup steps, I can take a look at this.

**Comment by almeidapaulooliveira** [comment]
I understand. Good point about native fonts. Let me check if another standard font looks similar.

**Review by marekweb — APPROVED** [review]
I tried the new screens and it's working and looking good. Nice!

**Pull request merged**
