### PR TITLE
Move scim package to frontend

### PR DESCRIPTION
**Pull request by eseliger**
Only imported in frontend, to simplify the dependency graph I'm moving it into the cmd/frontend/internal/auth package.

## Test plan

Just code moved, CI will find any issues.

### CODE REVIEW

**Comment by eseliger** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/61678?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#61678** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/61678?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#61677** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/61677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @eseliger and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by camdencheek — APPROVED** [review]

**Comment by eseliger** [comment]
### Merge activity

* **Apr 11, 11:59 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/61678) rebased this pull request as part of a merge.

**Comment by vdavid** [comment]
Thanks, @eseliger, and sorry, the original location was my choice, happy that it didn't cause you too much trouble to move it to a better place.

**Comment by eseliger** [comment]
No issue at all! It makes sense IMO to start out in internal, and git mv is always cheap and preserves history :)

**Pull request merged**
