### PR TITLE
Wildcard: Add `<Popover />`

### PR DESCRIPTION
**Pull request by umpox**
## Description

Adds the `@reach/popover` wrapper to Wildcard.

This is an initial implementation to unblock any migration work. We want to start migrating the codebase to this new approach, this will help us understand any problems better and come up with a solution.

@vovakulikov I know you mentioned wanting to revisit how we position our Popovers, maybe using [floating-ui](https://floating-ui.com/). I agree that we should do this, would be keen to know if you've looked into this any further since our conversation? For now, I'm preserving the current behavior to unblock other work.

### CODE REVIEW

**Comment by vovakulikov** [comment]
@umpox thanks that you remember about floating ui solution. I should have told you this early so you wouldn't waste your time. Here is my version of the wildcard popover component. 
https://github.com/sourcegraph/sourcegraph/pull/29488 Please have a look. It decently doesn't support all possible cases but perhaps it's good enough for the first version of it and unblocking further work. 

I haven't tested this component in a composition with other wildcard components where we use reach popover component (like Combobox or menu button) but it should be fine I guess otherwise I will take a look at this shortly when we will integrate it with other components

**Comment by umpox** [comment]
@vovakulikov No worries, this is great! This PR was just moving the existing code, so low effort and we'd likely have to implement a better positioning system anyway so this takes us a step further.

I'm curious if you considered using `@reach/popover`? As I know we currently use it in some places (both directly through the package and indirectly through things like our `Menu` components).

We want to primarily ensure that these new components are:
1. Straightforward to migrate the entire codebase to (similar/identical styles and functionality). As it'll be difficult to get other teams involved in the migration, and it has to be feasible for our team to do.
2. Fully accessible. This is especially important this year as we look to hit WCAG AA compliance across the webapp

I'll take a look your branch and have a play around!

**Comment by vovakulikov** [comment]
@umpox I agree with you about your migration and a11y points these are important criteria for a component like this one. I have nothing against adopting `@reach/popover` (well maybe positioning logic isn't perfect because I was writing this only for the code insights dashboard page) first and then after thinking about proper API adopt floating UI component. 

I'm still trying to figure out what is the best API here to provide a flexible enough and composition-friendly API to cover all cases that we have or will have in the future. 

For example, adoption popover for code insights drill-down filters is a good example because where we have to use `auto-placement` and `autosize` approaches instead of standard popover flipping logic. And I don't have a good API to fit all cases for it in one component at the moment (I'm pointing this out just to show that this can take a while to come up with a good API here) 

So feel free to play with PR with floating UI maybe you have thoughts on this API problem as well.

**Comment by umpox** [comment]
@vovakulikov I see what you mean. I was thinking a good middle ground would be to use the positioning logic of floating UI with the accessibility benefits of `@reach/popover`. I originally looked into this, but I remember having some difficulties accessing the popover element so that floating UI could calculate the position. Maybe it needs further investigation

**Comment by vovakulikov** [comment]
@umpox Just to be sure that I fully understand this when you're saying 
> with the accessibility benefits of @reach/popover
what exactly do you mean by that?

**Comment by vovakulikov** [comment]
@umpox Got it. I also have seen this part of the popover in the reach UI package. And actually, I'm not so sure about the need for this logic. I assume that by default we always should loop focus inside of popover element. 
WAI Aria spec about this component https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal (dialog is a bit different but this spec doesn't have an explicit description of popup/popover elements) 

>Like non-modal dialogs, modal dialogs contain their tab sequence. That is, Tab and Shift + Tab do not move focus outside the dialog. However, unlike most non-modal dialogs, modal dialogs do not provide means for moving keyboard focus outside the dialog window without closing the dialog.

So based on that we actually don't need to change focus order we just need to lock focus inside of the popover element and bring the focus back to the target element when the popover has been closed. 

Example of this logic in radix popover here https://www.radix-ui.com/docs/primitives/components/popover

**Comment by umpox** [comment]
FYI: Closing this

@vovakulikov is working on an improved solution that solves much of the positioning issues we have when using `@reach/popover` by itself: https://github.com/sourcegraph/sourcegraph/pull/29518

Hopefully we can reuse `@reach/popover` in that PR so we still get any accessibility benefits and easier integration with other `@reach` components but with much improved positioning - which should make migration a lot easier.

Future updates will be in that PR!

**Pull request closed without merging**
