### PR TITLE
Add support for Claude Instant 1.2

### PR DESCRIPTION
**Pull request by philipp-spiess**
https://www.anthropic.com/index/releasing-claude-instant-1-2
 
## Test plan

-  I connected the VS Code instant to the local instance and configured the dev server to use Claude instant 1.2 for code completions. It works

### CODE REVIEW

**Comment by philipp-spiess** [comment]
@eseliger How do I enable this model on the LLM gateway? 👀

**Comment by eseliger** [comment]
We'll also need to allow it for the subscription plans by default here:
https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fsourcegraph&branch=main&file=internal%2Flicensing%2Fcodygateway.go&editor=VSCode&version=2.2.16&start_row=26&start_col=1&end_row=26&end_col=1
https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fsourcegraph&branch=main&file=internal%2Flicensing%2Fcodygateway.go&editor=VSCode&version=2.2.16&start_row=60&start_col=1&end_row=60&end_col=1
and here for app: https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fsourcegraph&branch=main&file=enterprise%2Fcmd%2Ffrontend%2Finternal%2Fdotcom%2Fproductsubscription%2Fcodygateway_dotcom_user.go&editor=VSCode&version=2.2.16&start_row=211&start_col=1&end_row=214&end_col=10

One thing that's a bit ugly is that when a subscription has a model override on dotcom, it won't automatically get the new models added, because we assume that you excluded it on purpose, so we might want to enable this model manually in the DB for all subscriptions that have an override set, and claude-instant-1 enabled already, post rollout. When this is merged, ping me and I can roll out the new gateway version to dev and then prod. 

FWIW, since we use `claude-instant-1` vs `claude-instant-1.1` for all current version instances, we get their latest stable model always, which [according to docs](https://docs.anthropic.com/claude/reference/selecting-a-model) is 1.2, also tested in postman to verify: 

Screenshot 2023-08-11 at 11 26 33@2x

So sounds like we're already using those model for up-to-date instances :) 

Anyways, if you want to allow this specific model version, too, the above things should do it :)

**Comment by philipp-spiess** [comment]
@eseliger Ohh okay, gotcha. This is good news so it sounds like dotcom is already using the latest and greatest anyways! Since we do allow `claude-instant-v1.1` right now, I think we should add `claude-instant-v1.2` explicitly too, so let me make the changes you suggested.

**Comment by eseliger** [comment]
> @eseliger Ohh okay, gotcha. This is good news so it sounds like dotcom is already using the latest and greatest anyways! Since we do allow claude-instant-v1.1 right now (at least in the config?), I think we should add claude-instant-v1.2 explicitly too, so let me make the changes you suggested.

Yeah we allow it _when someone has it in their override_, I think this list was mostly for completeness, not because anyone is currently actually allowed to use it directly 😆 Do you think we need to allow the users to use the 1.2 model directly? It would mean that we might have instances that are stuck on the 1.2 quality for a long time

**Comment by philipp-spiess** [comment]
@eseliger Gotcha! Yeah I think the override still makes sense but it's not worthy of a change log. But maybe we to move back from a future 1.3 to 1.2 at some point to fix some regression so I'd keep it in the overwrite.

**Review by eseliger — APPROVED** [review]
> @eseliger Ok looking at this closer, I'm not sure if we really need minor versions inside the subscription plan specifically? We don't seem to have done that before either 🤔 I think if a license allows you to use claude-instant-v1 you should probably be able to use any minor version of that model too, WDYT?

Yeah might, but that's upstream provider specific knowledge, so we didn't implement any of such so far. For models that might release in the future that are more expensive, a "allow access to all" might be undesirable, if they don't bump the major for that. For example, when they released the 100k versions of these models, we were initially scared that they are driving cost up significantly (which turned out to be false, since claude 2 is now 100k by default 😬).  

> i.e. there's an inconsistency between the models in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/licensing/codygateway.go?L27 and https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/cody-gateway/shared/config.go?L85-104

This inconsistency is on purpose, kind of. By default, we only give instances access to a very limited set of models, so we don't have too many of those used in the wild (anthropic provides rate limiting based on what models you use the most, so staying with few specific ones will be beneficiary), and on the gateway side we allowlist most alterations of it, so we can easily spin up a dev instance with an allowed models override in the subscription. So adding 1.2 explicitly at the very least in the gateway config and the `ModelBadges.tsx` files will be useful I think. So the diff we got here currently is good I think! 

Unless you really want instances to by default use 1.2 explicitly vs implicitly?

**Comment by philipp-spiess** [comment]
> Unless you really want instances to by default use 1.2 explicitly vs implicitly?

I don't think that'll be necessary for now, we can alway revisit though! 

Thanks for the review 🤗

**Pull request merged**
