### PR TITLE
incorporate graphql-go patch to fix union/interface inline fragments

### PR DESCRIPTION
**Pull request by sqs**
Incorporates https://github.com/graph-gophers/graphql-go/pull/409.

### CODE REVIEW

**Comment by tsenart** [comment]
@sqs: Is this still relevant? If so, I'll add reviewers.

**Comment by sqs** [comment]
@tsenart Yes, it is. It's not used now, but it is helpful to avoid adding extra layers of indirection in our GraphQL API for common use cases (eg "why do we need `namespace(id: ID!): Namespace` when we could do `node(id: ID!) { ... on Namespace { } }`? this PR makes the latter possible)

**Review by keegancsmith — CHANGES_REQUESTED** [review]
This update doesn't include `e542e8956484`, which was an important performance fix. Luckily, they merged it into master upstream 2 days ago. So just update your fork to include the latest master and we are good to go :)

**Review by keegancsmith — APPROVED** [review]
whoops, I looked at the wrong commit. This is good :)

**Pull request merged**
