### PR TITLE
Update link on SignInPage.tsx

### PR DESCRIPTION
**Pull request by iskyOS**
Updating a link on the dotcom login page that currently points to sourcegraph.com, while it should point to about.sourcegraph.com

## Test plan

Single link change; no new tests.

### CODE REVIEW

**Review by camdencheek — APPROVED** [review]
LGTM!

**Comment by camdencheek** [comment]
@iskyOS, just an FYI that you don't need to merge `main` in every time there is a change. The "This branch is out-of-date" message is just there to make it easy in case you _do_ want to integrate something on main. GitHub will block you from merging if there is a conflict.

**Comment by camdencheek** [comment]
That said, it looks like CI was whining because of some unrelated change that you got unluck and caught in your branch. I went ahead and rebased on `main` to catch that fix. Sorry for the annoyance

**Comment by iskyOS** [comment]
Oh - thanks, @camdencheek! I thought I did have to update the branch 😅

It looks like Buildkite is still failing though. Is there anything else I can do other than re-running it until it works?

**Comment by camdencheek** [comment]
I'm AFK today, so I don't have access to the build failure. I know we've had some issues with our frontend builds the last few days. I'd recommend reaching out to #discuss-dev-infra -- they should be able to help ya!

**Comment by iskyOS** [comment]
Made irrelevant by the recent marketing site migration, so I am closing 👍

**Pull request closed without merging**
