### PR TITLE
search: factor out conf.Get() call

### PR DESCRIPTION
**Pull request by rvantonder**
Follow up of https://github.com/sourcegraph/sourcegraph/pull/22711#discussion_r666699477. Is this what you had in mind @keegancsmith? Is there an ideal way to expose conf besides this (e.g., would it help if we called this further up the stack and passed down everywhere, or is this fine? I'm not sure what the stateful dependencies are on `conf.Get`.)

### CODE REVIEW

**Comment by rvantonder** [comment]
Hmm it seems tests fail hard with this change and I'm not sure why (some mocking?). Will wait for comments and not investigate further because this suggests it's not a simple change

> FAIL: TestResolveRepositoriesWithUserSearchContext (33.55s) | 0s
-- | --
  | FAIL: TestResolveRepositoriesWithSearchContext (0.02s) | -0s
  | dbtest.go:81: failed to exec "CREATE DATABASE \"sourcegraph-test-6634913646406807872\" TEMPLATE \"sourcegraph-test-template--6997032839301961717\"": ERROR: template database "sourcegraph-test-template--6997032839301961717" does not exist (SQLSTATE 3D000)
  | dbtest.go:84: failed to connect to database "postgres://postgres@127.0.0.1:5432/sourcegraph-test-6634913646406807872?sslmode=disable&statement_timeout=30s&timezone=UTC": DB not available: FATAL: database "sourcegraph-test-6634913646406807872" does not exist (SQLSTATE 3D000)
  | FAIL

**Review by keegancsmith — APPROVED** [review]
Yup this is what I had in mind. I agree, if we just did conf.Get once per search request that would be cool and much easier to understand :) Then at some point we don't use conf.Unified, and instead have search.Conf or something with just the fields from conf.Unified we care about.

**Comment by keegancsmith** [comment]
Merged in main in the hopes the tests now pass.

**Comment by rvantonder** [comment]
TY!!

**Pull request merged**
