### PR TITLE
Cody JetBrains: allow new-style access tokens

### PR DESCRIPTION
**Pull request by olafurpg**
Previously, the settings UI didn't accept access tokens using the new
`sgp_` prefix.

## Test plan

- Open Cody settings
- Paste in a new-style access token that starts with `sgp_`, for example sgp_f20349d34e331cc511fa1949791ab680f552b627 (this is not an actual token)
- Confirm that you can save the settings

### CODE REVIEW

**Review by vdavid — APPROVED** [review]
Note: Would be cool to apply this fix to our other plugin's SettingsComponent.java as well. If you feel like including that in this PR, that's great, otherwise I'll take a note and do it later

**Comment by vdavid** [comment]
Ah, automerge. Taking note then :)

**Comment by olafurpg** [comment]
> Would be cool to apply this fix to our other plugin's SettingsComponent.java as well

Which file? There's only one `SettingsComponent.java` in the project 🤔

**Comment by vdavid** [comment]
There are two:
1. Sourcegraph: 
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java?L1
1. Cody:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/SettingsComponent.java?L1

**Comment by vdavid** [comment]
A portion of the Cody codebase is a copy-paste right now. I've added the `jetbrains-shared` folder to create an option for code reuse, but the code must be reorganized to avoid duplications.

**Pull request merged**
