### PR TITLE
Revert "Revert "Migrate admin area <Switch/> to RR6 (#47276) (#47389)"

### PR DESCRIPTION
**Pull request by philipp-spiess**
This reverts the revert of #47276 (basically re-landing #47276).

We need to find out why E2E tests failed though 😐 

## App preview:

- [Web](https://sg-web-ps-reland-47276.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by philipp-spiess** [comment]
```
Polling for build for branch main-dry-run/ps/reland-47276 at 553c1671701269f561c67cdbb62bc8e87dee8de5...
✅ Created build: https://buildkite.com/sourcegraph/sourcegraph/builds/197581
```

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.05% (+1.35 kb) | 0.01% (+1.50 kb) | 0.00% (+0.14 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/reland-47276/compare-report.html;tab=live_object) for a full comparison between the commits 553c167 and 93bb511 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by valerybugakov** [comment]
I looked into it here:
- https://github.com/sourcegraph/sourcegraph/pull/47414

**Comment by philipp-spiess** [comment]
Dupe of #47414

**Pull request closed without merging**
