### PR TITLE
Setup Wizard: Add built in repositories UI support

### PR DESCRIPTION
**Pull request by vovakulikov**
Closes https://github.com/sourcegraph/sourcegraph/issues/49152

This PR adds automatically discovered and added repositories to the first setup wizard state about local repositories (built-in repositories). Previously we didn't show anything, which may confuse users because they do have local repositories if they run their sourcegraph CLI in the local folder where they have .git repositories.

| Initial state | Picked some local repositories (render built-in repos below) |
| --------- | ---------- |
| Screenshot 2023-03-17 at 17 56 29 | Screenshot 2023-03-17 at 17 56 44 |

## Test plan
- Run Sourcegraph App from the terminal 
- You should see a list of repositories that CLI has resolved 

## App preview:

- [Web](https://sg-web-vk-add-built-in-repositories-ui.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by vovakulikov** [comment]
@taylorsperry @almeidapaulooliveira, can you take a look at the description copy for the built-in repositories section? Now it says:
> You're running Sourcegraph app from your terminal. We found repositories below based on the path where you run sourcegraph CLI

Maybe you have a better copy for this

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+0.92 kb) | 0.01% (+0.92 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vk/add-built-in-repositories-ui-support/compare-report.html;tab=live_object) for a full comparison between the commits ba9ae09 and c29495a or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by taylorsperry** [comment]
@vovakulikov @almeidapaulooliveira on copy, maybe: 

> You're running the Sourcegraph app from your terminal. We found the repositories below in your path.

**Comment by sourcegraph-user-testing** [comment]
I found this journey super complex for something so simple as adding local folders. I understand the technical limitations of this release, and I hope we can come back to review it later. Also, we're running user testing after this interface, and let's learn from users how it works.

**Review by almeidapaulooliveira — APPROVED** [review]
I found this journey super complex for something so simple as adding local folders. I understand the technical limitations of this release, and I hope we can come back to review it later. Also, we're running user testing after this interface, and let's learn from users how it works.

**Comment by vovakulikov** [comment]
I think, in general, it should work like this 
- We run sourcegraph from terminal 
- We remember a path from the terminal and show it in the local repositories picker along with resolved repositories 
- You change a path, and you change local repositories on your instance (so it's possible to remove repositories that we resolved because you run the app from the terminal)

At the moment, these terminal-based repositories are read-only. I actually don't know why exactly they are read-only, @keegancsmith you probably have a reason for it?

I think the main problem at the moment is this separation between terminal repositories and manually added repositories. It should be one abstraction from user's point of view. (simular to how you work with IDE, you can open editor from terminal and it takes local repo from terminal, but then later you can change it in UI and open another repo but this time from editor UI)

**Comment by vovakulikov** [comment]
@taylorsperry I updated copy based on your comment, thanks

**Review by philipp-spiess — APPROVED** [review]
Charlie Day Thumb

**Pull request merged**
