### PR TITLE
search: include branches to index for indexserver

### PR DESCRIPTION
**Pull request by asdine**
This implements the `/.internal/search/configuration` which returns branches configuration to zoekt-sourcegraph-indexserver.
It also adds a new experimental site configuration field, allowing users to select the branches they want to index for a given repo.

### CODE REVIEW

**Comment by keegancsmith** [comment]
See my comments on the previous PR.

**Comment by keegancsmith** [comment]
Our current behaviour is to index HEAD of all repositories. We should continue this behaviour no matter what the configuration is. I think while introducing version contexts we should index additional branches. This will likely change as the feature evolves/we learn more. For now ensuring our current behaviour works and it is feature flagged is most important.

>> I was thinking we always have HEAD and we always index the branches in version contexts. This should be fine for our initial version?
>> We should have a feature flag which can disable multiple branch indexing, since version contexts doesn't actually rely on indexing to work (just to scale).

> If the zoekt-sourcegraph-indexserver calls the endpoint with a repo, we must only check if it exists in the version contexts?

The repo is used to check if we have extra branches to index. I think by using version contexts we can get the branches to index. I think for now using the version contexts as the extra branch config makes sense since it is our first use case for indexing more than HEAD. This will likely change in the future, but for now makes the most sense.

> If the zoekt-sourcegraph-indexserver calls the endpoint without a repo, what should we return?

We should use the old behaviour. indexserver and frontend are not rolled out atomically. In general you can assume frontend will always roll out before and more often than the indexserver. So you need to ensure when updating frontend that it is backwards compatible for clients.

> Does this mean we don’t need to let the user choose which repo to index in the conf?

Yes. I do think we need an extra bit of config to disable this behaviour that is independent of version contexts. My concern is when indexing multiple branches something breaks in sourcegraph. However, version contexts is useful without the indexing. So I can imagine a user wanting version contexts but not indexing. This is just temporary while we roll the feature out though.

**Comment by keegancsmith** [comment]
@asdine any updates here?

**Comment by asdine** [comment]
@keegancsmith I just need to some QA and it should be good

**Comment by keegancsmith** [comment]
Gonna work on this with fresh eyes :)

**Pull request closed without merging**
