### PR TITLE
search: only omit ending `.*` for parsing include pattern

### PR DESCRIPTION
**Pull request by unknwon**
This is a hacky but working patch that works with both #9146 and #4166.

I do not think this is the right fix but to reveal the problem we have in hand.

### CODE REVIEW

**Comment by keegancsmith** [comment]
yeah this is close enough to the right fix that we should ship it. Please add some test cases.

**Comment by unknwon** [comment]
> Please add some test cases.

Existing test cases catch this already, and basically how I come up with this fix:

https://github.com/sourcegraph/sourcegraph/blob/6489d84863529ce95b736a156ec9951f3fd00445/cmd/frontend/db/repos_test.go#L55-L57

**Comment by keegancsmith** [comment]
Those test cases don't cover where we currently fail. Can you add those in (ie .* not at the end)

**Comment by unknwon** [comment]
> Those test cases don't cover where we currently fail. Can you add those in (ie .* not at the end)

This may not be obvious, but this PR is base off `core/repo-search` branch 🤦‍♂ which contains the tests you added.

**Comment by keegancsmith** [comment]
Ok great, then lets ship this :)

I have two more test cases for ya:
- `^github.com/(golang|go-.*)/oauth$`
- `^github.com/(go.*lang|go)/oauth$`

I get the feeling the optimization I added in that old PR should only apply for things at the "highest" level. ie don't recurse into capture/or groups.

**Comment by unknwon** [comment]
> I get the feeling the optimization I added in that old PR should only apply for things at the "highest" level. ie don't recurse into capture/or groups.

Yeah, I can confirm this is true.

**Comment by unknwon** [comment]
I changed merge base to `master` branch, so we have the full picture here.

TODO:
- [ ] Delete `core/repo-search` branch after merge

**Comment by keegancsmith** [comment]
Changelog entry pls

**Comment by keegancsmith** [comment]
merged in master to hopefully fix CI

**Pull request merged**
