### PR TITLE
Add missing .gitattributes files for various generated files

### PR DESCRIPTION
**Pull request by varungandhi-src**
With PR review, I've noticed myself making the mistake multiple times where I end up reading a bunch of generated code when I should be focusing on the original code from which it was generated. Part of the issue here is that GitHub doesn't show the file header, which usually carries a "DO NOT EDIT, this was generated by blah." [This problem can be mitigated by using `.gitattributes` files](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github).

> Use a .gitattributes file to mark files that match a given "pattern" with the specified attributes.
>
> Use the linguist-generated attribute to mark or unmark paths that you would like to be ignored for the repository's language statistics and hidden by default in diffs

We already have one at the project root, but that doesn't catch everything. The current patch adds directory-local files, which should be allowed according the [Git docs](https://git-scm.com/docs/gitattributes):

> When deciding what attributes are assigned to a path, Git consults $GIT_DIR/info/attributes file (which has the highest precedence), **.gitattributes file in the same directory as the path in question** (emphasis added), and its parent directories up to the toplevel of the work tree (the further the directory that contains .gitattributes is from the path in question, the lower its precedence). Finally global and system-wide files are considered (they have the lowest precedence).

The official GitHub docs recommend:

> Unless the .gitattributes file already exists, create a .gitattributes file in the root of the repository.

I'm not 100% sure if directory-local `.gitattributes` work or not on GitHub. If this patch doesn't work, I guess we can combine all the `.gitattributes` into one jumbo `.gitattributes` at the root of the repo.

### CODE REVIEW

**Comment by eseliger** [comment]
These files are all generated and I think it's easy to forget to manually add the gitattributes entry after. Maybe we can teach the generator to also write to the gitattributes files?

**Comment by varungandhi-src** [comment]
> Maybe we can teach the generator to also write to the gitattributes files?

Are you suggesting we add this logic in https://github.com/derision-test/go-mockgen or somewhere else?

Only adding that to `go-mockgen` won't catch all issues, since there are other generators as well. For more coverage, we could add a lint pass which checks that every file with `DO NOT EDIT` also has a matching `linguist-generated` attribute (I don't know if this will run into false positives though).

**Review by keegancsmith — COMMENTED** [review]
This looks like a pain to keep up to date. Can we maybe just be a little fast and loose and just ignore all `mock_*test.go` files from the root? Same with `*.pb.go`. Then we can keep the more targetted gitattrs for the other patterns.

**Comment by eseliger** [comment]
Ah, didn't realize it was from multiple generators. Hmm, then I'd maybe say Keegan's comment would be the least risk for divergence?

**Comment by varungandhi-src** [comment]
> Can we maybe just be a little fast and loose and just ignore all `mock_*test.go` files from the root?

I tried a bunch of patterns originally, but couldn't quite get it to work in a way that would avoid also marking non-generated files as generated. Out of 58 files covered in this PR, this particular pattern will miss 20. Should we rename those 20 files then or should I add `.gitattributes` for those? (Or do we just leave them as they are?)

```
dev/internal/team/mock.go
docker-images/prometheus/cmd/prom-wrapper/mocks/prometheus_mock.go
enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_query.go
enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go
enterprise/cmd/frontend/internal/registry/stores/dbmocks/mock_stores.go
enterprise/internal/codeintel/stores/uploadstore/mocks/mock_store.go
enterprise/internal/database/mocks.go
enterprise/internal/insights/background/mock_repo_store.go
enterprise/internal/insights/compression/mock_commit_store.go
enterprise/internal/insights/discovery/mock_indexable_repos_lister.go
enterprise/internal/insights/discovery/mock_repo_store.go
enterprise/internal/insights/discovery/mock_setting_store.go
enterprise/internal/insights/store/mock_store_dataseriesstore.go
enterprise/internal/insights/store/mock_store_insightmetadatastore.go
enterprise/internal/insights/store/mock_store_interface.go
internal/authz/mock_sub_repo_perms_checker.go
internal/authz/mock_sub_repo_perms_getter.go
internal/database/mocks.go
internal/insights/mock_loader.go
internal/workerutil/dbworker/store/mocks/mock_store.go
```

It seems independently useful to have a consistent naming scheme for mock files.

Any thoughts on the lint suggestion I mentioned earlier? That should be more reliable to catch missing files.

> we could add a lint pass which checks that every file with DO NOT EDIT also has a matching linguist-generated attribute (I don't know if this will run into false positives though).

**Comment by keegancsmith** [comment]
> Any thoughts on the lint suggestion I mentioned earlier? That should be more reliable to catch missing files.

Lint seems somewhat frustrating vs the value gain. I think a generic pattern match is ideal.

Taking a step back we can check how linguist actually decides code is generated. @efritz seems like if go-mockgen slightly adjusted it's "generated" line github linguist would automatically pick it up:

https://github.com/github/linguist/blob/73e2d735c3c26577fc89c1cb3f8342e5a8ff1d82/lib/linguist/generated.rb#L317-L322

This seems like a better solution than having to maintain extra data and is minimal.

**Comment by varungandhi-src** [comment]
Good point, I hadn't considered looking at the Linguist source.

I've made the following changes:
1. Dropped the commit adding `.gitattributes` for the various mock files. Given that `go-mockgen` already adds lines like:
   ```
   // Code generated by go-mockgen 1.1.2; DO NOT EDIT.
   ```
   and that linguist is checking for `"Code generated by"`, I think the mock files should be ignored without needing to separately adding a `mock_*test.go` entry.
2. Added a more general check for `*.pb.go` instead of one specific to `lsif.pb.go`.

**Review by keegancsmith — APPROVED** [review]

**Pull request merged**
