### PR TITLE
Wildcard: Add first implementation of `<MultiCombobox />` component

### PR DESCRIPTION
**Pull request by vovakulikov**
## Background

A few code insights pages already have something like the Combobox component but instead of Combobox, they use something similar. A good example of it can be search-based insight creation UI (the repositories field). 

_Code insights creation UI search repositories field_
image

This field uses just a simple input with some logic on top of it. This logic is complex and sometimes when you work with simple text to manage a few items in this field (a few repositories) it can be complicated for users and can lead to some bugs there. 

Also, Multibox would be useful for further change in the creation UI form when we start implementation of the new dashboards settings section in the form.

This PR adds the MultiCombobox component but doesn't add this to the creation UI. It will be done in a separate PR. 

<table>
 <tr><th>Light theme</th><th>Dark theme</th></tr>
 <tr>
    <td>
    
Screenshot 2021-10-07 at 17 25 03
    </td>
    <td>
    
Screenshot 2021-10-07 at 17 25 17
</td>
</tr>
</table>

## Work in progress but not blockers for design review 
1. A11y support (labels, focus management)
2. Overflow content checks

### CODE REVIEW

**Comment by pdubroy** [comment]
This seems like it would be generally useful. Is there anything about this that is specific to Code Insights, or is this something that we could consider putting in Wildcard?

**Comment by felixfbecker** [comment]
Regardless of whether this gets added to the wildcard library or not, we shouldn't start using it while it is not accessible, and hence not merge it until then. We can always use a comma-delimited plain text input in the meantime, which is always accessible. This kind of component is _very_ tricky to get right (in a way that is not net-worse than a plain text input), it's not something that can just be done quickly or should be rushed. It's also something where I'd research existing open source solutions and assess if any of those would work, because the risk of bugs and missing accessibility nuances is high.

**Comment by vovakulikov** [comment]
@pdubroy I think We can say that in case if code insights will be needed for this component (for the creation UI) I or @unclejustin will make some changes there to prepare this component for production use. 

If we won't find time for it (in case if we delay or postpone the new creation UI with that component) I think it makes sense that FTP will implement that according to the FTP roadmap without any rush from our side of course. 

@pdubroy Is it ok, does it work for @sourcegraph/frontend-platform?

**Comment by vovakulikov** [comment]
Designs for this component from @AlicjaSuska https://www.figma.com/file/Fucz5IyDOx1gtb90Q6hDSQ/MultiCombobox?node-id=275%3A1628

**Comment by vovakulikov** [comment]
@quinnkeast If I got it right you're saying that we want to reuse the dropdown part of that component in other components/consumers? In this case, I think the right separation here would be: 
- Select-list component (just a list with disabled/selected items and keyboard navigation through that list)
- Dropdown panel (just position math with simple UI - containers with border and box-shadow)
- Input component

In this separation, we would easily build some complex components like this Multi Combobox.

**Comment by umpox** [comment]
@vovakulikov Any blockers to updating this PR with `main` and merging?

@sourcegraph/frontend-platform will drive this forward to being production ready through this tracking issue: https://github.com/sourcegraph/sourcegraph/issues/27705

**Comment by vovakulikov** [comment]
@umpox Sorry for the long response. Yes, I think it could be merged especially if the frontend platform will pick it up. @AlicjaSuska can you please approve this PR? Then all remaining visual changes will be addressed later.

**Review by unclejustin — APPROVED** [review]

**Comment by vovakulikov** [comment]
Hello there, it's been a while, how is everybody? I'm here to say: "OMG I'm closing this one, after all these years", for those who might be curious here is a [PR](https://github.com/sourcegraph/sourcegraph/pull/46362) where I finally got time and built MultiCombobox UI, thanks everyone you all were amazing and I'm closing this one, OMG once again. Cheers!

Closed by https://github.com/sourcegraph/sourcegraph/pull/46362

**Pull request closed without merging**
