### PR TITLE
web: codemod template literal to `classNames` call [3]

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context 

To improve consistency of class names creation in React components and avoid processing template literal cases in the [global-css-to-css-modules](https://github.com/sourcegraph/codemod/tree/main/src/transforms/globalCssToCssModule) codemod another codemod [was added](https://github.com/sourcegraph/codemod/pull/28) to automatically transform template literals to `classNames()` utility calls:

```tsx
<div className={`cool-class ${props.className || ''}`} />
// turns into 
<div className={classNames('cool-class', props.className)} />
```

This PR applies a newly added codemod to the part of the codebase. 

## Changes

- Converted template literals usage in `className` prop to `classNames()` utility call.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
Not a blocker, but do we have something in place that ensures we don't regress on this? :)

**Comment by valerybugakov** [comment]
@eseliger, as usual, code-review, unit-tests, and integrations test 🙂.
Do you have anything specific in mind?

**Comment by eseliger** [comment]
Oh, pardon! I didn't mean this PR isn't mature, I meant how do we prevent people from re-introducing this pattern.

**Comment by valerybugakov** [comment]
Oh, got it 😀
Yep, a custom ESLint rule to ban this pattern for some cases is under development.

**Comment by eseliger** [comment]
Awesome!

**Pull request merged**
