### PR TITLE
hide access token by default after creation

### PR DESCRIPTION
**Pull request by BolajiOlajide**
[Context](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694188323196199)

When a user creates an access token on Sourcegraph, we currently display the token by default in plain text. Sometimes the user is in a public place and this token could be captured by an attacker and used for malicious purposes.

This PR hides the token by default and the user can then click to see it or simply just copy it for use.

CleanShot 2023-09-12 at 13 32 06

## Test plan

* I manually went through the flow of creating an access token by visiting my profile page [`/users/<USER>/settings/tokens`](https://sourcegraph.sourcegraph.com/users/bolaji.olajide-tkzij/settings/tokens)
* Then clicking on the `Generate new token` button
* This should display the newly created access token with the token hidden by default.

### CODE REVIEW

**Review by unknwon — APPROVED** [review]

**Comment by BolajiOlajide** [comment]
Just realized even though the token is hidden, it's still contained in the `curl example`. I'll fix that later  on before merging lol

**Comment by eseliger** [comment]
is that token from the screenshot for localhost? 😬

**Comment by BolajiOlajide** [comment]
Lmaooo. Yes it’s for my local environment.
That’s why I didn’t bother removing it.

I already revoked it on my machine also incase of any magic.

**Review by eseliger — APPROVED** [review]
LGTM, pending collapsing the usage example with cURL by default as well :)

**Pull request merged**
