### PR TITLE
Open in Editor: Add filter for short URL patterns + test

### PR DESCRIPTION
**Pull request by vdavid**
- Fixes https://github.com/sourcegraph/sourcegraph/issues/43839

I've done some digging, and I don't see a truly elegant solution that I could deliver before tomorrow's branch cut.
The solution in this PR is not elegant, but it solves the current customer issue, and I find it unlikely that it'd break other cases.

My findings:
- The `repositoryPathPattern` is **not available** on the front end (for a reason).
    - Only the modified repo URLs are available, that is, the results of applying the `repositoryPathPattern` on the original URLs.
    - `repositoryPathPattern` is a part of the code host connection settings (The config visible at `/site-admin/external-services/{id}`), and the whole thing is not accessible to the front end. This is expected because this raw information should probably be available for admins.
    - Without `repositoryPathPattern`, we can't reliably determine how many pieces we should cut off from the URL.
- We could move the logic to the back end, and have the back end return an alternative path made for Open in Editor. This would probably involve introducing a new setting to the code host connection config (for each code host type), to set the number of pieces to cut off explicitly. Then the front-end logic would have no logic; it'd just use the URL provided.
  - I'm not confident that this would be a user-friendly solution; it's a bit too many settings, and I'm still wondering whether the cutoff point could be reliably calculated on the back end.

## Test plan

I've added a new test that covers this case; the old test and the new one are all passing, so I think this should be fine.

## App preview:

- [Web](https://sg-web-dv-open-in-editor-respect.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.02 kb) | 0.00% (+0.02 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/dv/open-in-editor-respect-repositorypathpattern/compare-report.html;tab=live_object) for a full comparison between the commits 565191b and 0e68f41 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by philipp-spiess — APPROVED** [review]
Nice!! The test suite is really paying off here to have confidence that we don't break other _tested_ branches. 💯 

I think the logic makes sense 👍

**Comment by philipp-spiess** [comment]
Maybe we want to add a change log entry for this though?

**Comment by vdavid** [comment]
@philipp-spiess Nice catch! The thing is, I've never added a changelog item before :embassarred_laugh: so it was totally not in my workflow. Added it now.

**Comment by philipp-spiess** [comment]
> @philipp-spiess Nice catch! The thing is, I've never added a changelog item before :embassarred_laugh: so it was totally not in my workflow. Added it now.

Haha yes it's not something that's naturally to me yet either 😬

**Comment by DaedalusG** [comment]
Looks good to me @vdavid thanks for the quick fix!

**Pull request merged**
