### PR TITLE
add steps to backup and restore compose db's

### PR DESCRIPTION
**Pull request by davejrt**
Add documented steps to backup and restore databases in compose deployments. 

Fixes https://github.com/sourcegraph/customer/issues/394

### CODE REVIEW

**Comment by davejrt** [comment]
@adeola-ak Can you please review, and ensure these steps are clear and you would be able to support the customer in this process if they asked questions.

**Comment by adeola-ak** [comment]
looking into this right now @davejrt sorry i didnt notice sooner!

**Comment by adeola-ak** [comment]
@davejrt I think these docs are great and exactly what i need to support a customer through this process. Thank you so much. 

One question from a customer: "would anything display in docker ps or grep that confirms a successful back up and restore?"

One other comment, while awaiting these docs a customer started a process to restore into a new environment and wants to know what we thought. I can make him aware that this is touched upon in this update, but I know he was curious to get feedback on his process because he already started it and saw what looks like some success
image

**Comment by davejrt** [comment]
I wouldn't recommend that approach, they're backing up everything related to docker, not only data but underlying docker objects which are well out of scope for this exercise. 

The alternative would be to back up and restore the volumes, which is [documented here ](https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes )however I feel as though the process I've documented is easier to follow in this case.

**Pull request merged**
