### PR TITLE
(WIP) pings: add support for frontend search performance stats

### PR DESCRIPTION
**Pull request by slimsag**
Implementation for RFC 283:

https://docs.google.com/document/d/1nYM4bZkH3u38Pae2Ad1SM9h-noFYxz_sIgjtdaIl9Yg/edit?ts=5fd992c6

Signed-off-by: Stephen Gutekanst <stephen.gutekanst@gmail.com>

### CODE REVIEW

**Comment by slimsag** [comment]
cc @rvantonder if you have any early advice it'd be much appreciated, still figuring out how things work with pings

**Comment by rvantonder** [comment]
So things have changed a bit since I looked at adding metrics, and I think it will differ a bit for frontend stuff. So I am going to liberally ping people who are more up to date. I think you will need the changes in this PR re: the shape of the data (and the aggregated kind), @efritz can confirm

The next thing to figure out is: You want to insert these events--I've only done this from the backend, using [`logBackendEvent`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+usagestats.LogBackendEvent%28...%29&patternType=structural)

You will presumably want to do this via some frontend call, I _think_ this is via something like [`eventLogger.log(...) or telemetryService.log(...)`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+eventLogger.log%28...%29+or+telemetryService.log%28...%29&patternType=structural) but this is where I'm fuzzy. @attfarhan probably has a good idea what the right call is. For context, for @attfarhan, I think the shape of the JSON (based on what we use for aggregated metrics in the backend) is:

```json
{"durationMs": %d, "search.latencies.frontend.%s"}
```

based on [what I did for backend](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results.go#L641-642)

**Comment by slimsag** [comment]
Thank you for the backend context!

I do have a pretty good idea of how to do the event logging on the frontend, but I'm not sure how exactly is the JSON shape determined? Is there a schema definition somewhere I have missed, or is this handled manually in bigquery I wonder? I haven't been able to find where exactly we specify that shape for the existing search latency events.

I am also wondering how the current search latency events end up as percentiles (P50, P90, etc. which I _think_ we collect for search latencies?) - I assume that happens somewhere in Sourcegraph code, not on the bigquery querying side?

**Comment by slimsag** [comment]
> I think this is via something like eventLogger.log(...) or telemetryService.log(...) but this is where I'm fuzzy

Update: I have found that `telemtryService` is what is provided to Sourcegraph extensions and allows them to log telemetry events. The `EventLogger` implements `TelemetryService` so, in effect, they are the same - but `eventLogger.log` should be used everywhere except inside an extension, it seems.

**Comment by slimsag** [comment]
Update: I got answers to my other questions in [this slack thread](https://sourcegraph.slack.com/archives/CN4FC7XT4/p1608249339308400)

**Comment by slimsag** [comment]
I have implemented a subset of this (data going to Prometheus) in https://github.com/sourcegraph/sourcegraph/pull/16935 and will follow-up on the rest here once I get back from holiday break. The remaining work is:

- [ ] It doesn't record search.latencies.frontend.<type>.first-result metrics for non-text-results (diff, commit, search, etc.) because these are rendered in a different frontend code path.
- [ ] It doesn't record search.latencies.frontend.<type>.first-result metrics when the streaming search feature flag is turned on. It does record search.latencies.frontend.code-load , though.
- [ ] The BigQuery schema needs to be updated (need to get Eric BM's help with this.)
- [ ] Need to figure out how to confirm actual telemetry pings are working as expected, prior to merge.

**Comment by slimsag** [comment]
!abandon

**Comment by rvantonder** [comment]
abandon

**Pull request closed without merging**
