### PR TITLE
Add repeatUntil() operator to remove kludge

### PR DESCRIPTION
**Pull request by lguychard**
I came across this kludge while reading through code, and thought I'd try to find the Right Way ™️ to fix it because it seemed fun. The use case for the new `repeatUntil()` operator here seems legit to me: polling until a condition is met, while still mirroring values (vs. `retryWhen()` polling, which only emits in the absence of an error).

There may be an even simpler way to do this, in which case I'd love to be further enlightened. This is obviously fairly low-priority to review 🙂

### CODE REVIEW

**Comment by felixfbecker** [comment]
This is really cool, love these kinds of PRs! I think we have some hacky "polling" in other places too so having one "blessed" solution would be valuable.

This reminds me of [`repeatWhen`](https://rxjs-dev.firebaseapp.com/api/operators/repeatWhen), but that doesn't give you access to the latest value.

One idea I have: Is this equivalent to
```ts
repeat(),
takeUntil(nodes => ...)
```
?
I.e. repeat indefinitely, but then stop when the condition is met.

By swapping the `repeat()` to a `repeatWhen(completions => completions.pipe(delay(time))` we can then get the delay behavior.

Could that work?

**Comment by lguychard** [comment]
@felixfbecker thanks for the suggestion!

This is not _strictly_ equivalent, since an implementation using `takeWhile()` will break the resubscription cycle as soon as any emitted value matches the condition (and not just the last emitted value), but I think it's maybe even better - after all only matching the condition on the last emitted value is a bit awkward if the source emits more than once.

Check out https://github.com/sourcegraph/sourcegraph/pull/9439/commits/7122c65d6cd27d4de5da16cfa2b5c06f6b54f71b - what do you think?

**Comment by lguychard** [comment]
Here's another use case for it: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9990c5a6bea2558d9f590197c1d6dcef3b72993d/-/blob/web/src/nav/StatusMessagesNavItem.tsx#L118-140

**Comment by lguychard** [comment]
And one more: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7468e5a/-/blob/web/src/enterprise/campaigns/detail/CampaignDetails.tsx#L138-149

**Comment by felixfbecker** [comment]
Cool! And great that we were able to verify this with your tests! What I'm left wondering now is which version is easier to understand, since `repeatUntil()` now does multiple things (repeating and delaying) and that violates SoC a bit, and composing the two operators inline is relatively concise too. That doesn't mean necessarily though that it is not easier to understand.

Without prior knowledge of this PR, which version would be easier to understand for you?

### A
```ts
return fetchAllRepositories(args).pipe(
    // Poll every 5000ms if repositories are being cloned or the list is empty.
    repeatUntil(
        result =>
            result.nodes &&
            result.nodes.length > 0 &&
            result.nodes.every(n => !n.mirrorInfo.cloneInProgress && n.mirrorInfo.cloned),
        5000
    )
)
```

### B
```ts
return fetchAllRepositories(args).pipe(
    // Poll every 5000ms if repositories are being cloned or the list is empty.
    repeatWhen(completions => completions.pipe(delay(5000))),
    takeWhile(
        result =>
            result.nodes &&
            result.nodes.length > 0 &&
            result.nodes.every(n => !n.mirrorInfo.cloneInProgress && n.mirrorInfo.cloned)
    )
)
```

**Comment by lguychard** [comment]
Trying my hardest to be unbiased, I would certainly still prefer 🅰️ - I find the cognitive overhead much lower. Considering we have three separate occurences of this pattern, I feel like extracting it into an operator would also be warranted. That being said, maybe getting some strictly unbiased opinions would be good 🙂

**Comment by eseliger** [comment]
I think 🅰️ is actually easier to understand and I've heard a few complaints that rxjs is not super beginner friendly and makes it hard to contribute to the web codebase, so I would also vote for it, just because it is simpler

**Comment by lguychard** [comment]
I clarified the signature by using an options object (`repeatUntil(predicate, { delay: 5000 })` instead of `repeatUntil(predicate, 5000)`) and updated CampaignDetails and StatusMessagesNavItem to use this operator. I think this is a net improvement and would like to merge if y'all agree 🙂

**Pull request merged**
