### PR TITLE
Ignore cookie warning in e2e tests

### PR DESCRIPTION
**Pull request by felixfbecker**
https://github.com/sourcegraph/sourcegraph/issues/6167#issuecomment-593834525

### CODE REVIEW

**Comment by eseliger** [comment]
can be closed, no?

**Comment by felixfbecker** [comment]
I guess so. We'll have to revisit though when we add back e2e tests (ideally we have them run with HTTPS, but I couldn't get that to work)

**Comment by lguychard** [comment]
@felixfbecker curious, what broke for you when running e2e tests with HTTPS? I was able to get that working recently (when generating test data for #9591 )

**Comment by felixfbecker** [comment]
We have one test (access tokens) that uses `got` to call the API to verify the access token works (and we want to use the API for test setup in general, #5259). This request would always fail with a NodeJS error when making the request against HTTPS, first because Node doesn't know about Caddy's custom SSL cert. When I set `NODE_EXTRA_CA_CERTS` to Caddy's cert folder, that error would go away, but the request would still fail with:
```
 GotError: write EPROTO 4526095808:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 80
```

The problem can be reduced to "make requests from NodeJS to our dev HTTPS instance work".

The other part would be making CI also use HTTPS for e2e tests.

**Comment by felixfbecker** [comment]
Curious how you got it to work? Did you not see that error?

**Comment by lguychard** [comment]
Oooh never mind - I was running a subset of tests, which did not include the access token test.

**Pull request closed without merging**
