### PR TITLE
Cody: Generate app scaffold

### PR DESCRIPTION
**Pull request by deepak2431**
This PR is for issue #50226. 

An attempt to generate most of the app scaffold with Cody. Developing an app scaffold can involve many steps; each developer has their requirements. It's good to consider the app's starting point with some options for the common dependencies. With this idea, I have implemented a small scaffold of React app in this PR. 
The current implementation involves the following steps:
1. Quick pick to select the app type
2. Provide the app name
3. Once the user selects the first two, it generates the scaffold by checking all dependencies and then generating the scaffold in the user's root.
4. If the scaffold generation is successful, then it returns the success message with some of the steps to start the app, else if it's unsuccessful, it returns the possible way to debug for the user and try again.

I have tried to think of the code implementation as it is easily extensible, like the one for Recipes, so I have used individual classes, interfaces and methods.

If this implementation is fine, I can include a few scaffolds in this PR:
1. React app
2. Angular app
3. Python apps Flask/Django

Input required:
1. Which more apps scaffold should we have the beginning as a starting point?

## Test plan
- Tested it on Mac, and it works completely fine

### CODE REVIEW

**Comment by deepak2431** [comment]
@beyang @philipp-spiess @abeatrix Do look at it and let me know your views before I move forward with the implementation. Thanks in advance :)

**Comment by philipp-spiess** [comment]
Hey @deepak2431!

Thanks again for a great contribution 🙇 

The code looks good but I’m not sure if we should go ahead with this recipe for a few reason:

1. There are so many different app scaffolds out there and we're likely not going to find the right one based on the current project easily. For example, I saw that you added `create-react-app` but this is only one way to start a React project today and getting this right would mean we have to maintain a long list of scaffolding generators.
2. This recipe doesn't seem to (and need to) leverage an AI at all. It's just a list of scaffold generators that you can trigger. It seems a bit out of scope for Cody.
3. The full story is a bit unclear. Compared to the tweet that #50226 links to, which seems to focus on E2E app generation, this is only creating some static files and we don't have any useful "follow-up" yet.

I’m curious to know what others from @sourcegraph/cody think about it though!

**Comment by deepak2431** [comment]
Thanks @philipp-spiess for the review. I completely agree with your point about maintaining and adding the scaffold generators. It would be tough to manage in the long term. 
Looking at the recipe title I thought of something like this, so didn’t used any A.I. prompts but I think there can be possibly way of using Cody prompts to do this. Need to think of it more.

Also, will wait for the views from other team members what they think about it, and what a good scaffold generator is expected to have with Cody.

**Comment by deepak2431** [comment]
> @deepak2431 Thank you!
> 
> And just to be very clear: I don't think this is an issue about your work. We're super appreciative of you helping us out like this 💪 My issue is more with the underlying issue (#50226) in general. I’m not sure if focusing on this is a good idea at the moment.

Yup, completely understand that @philipp-spiess. Love working on the project, will continue making contributions in any way I can help :)

**Comment by sqs** [comment]
<kbd>*semi-automated message*</kbd> Cody's source code has moved to a new repository, https://github.com/sourcegraph/cody. If you still intend to merge this change, please reopen your PR on that new repository.

The following are some of the path mappings from the old repository (https://github.com/sourcegraph/sourcegraph) to the new repository (https://github.com/sourcegraph/cody):

- `client/cody/ -> vscode/`
- `client/cody-shared/ -> lib/shared/`
- `client/cody-ui/ -> lib/ui/`

Thank you for the PR, and sorry for the inconvenience!

**Pull request closed without merging**
