### PR TITLE
Handle missing BUILDKITE_PULL_REQUEST or BUILDKITE_PULL_REQUEST_REPO gracefully

### PR DESCRIPTION
**Pull request by philipp-spiess**
c.f. https://sourcegraph.slack.com/archives/C01N83PS4TU/p1669960214116879

This prevents crashes on forks.

## Test plan

Will test run on CI.

## App preview:

- [Web](https://sg-web-ps-fix-bundle-size-script-for.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/fix-bundle-size-script-for-forks/compare-report.html;tab=live_object) for a full comparison between the commits 9fdf488 and e151326 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by valerybugakov — APPROVED** [review]
Thank you! 🙌

**Comment by valerybugakov** [comment]
Going to merge earlier to unblock a couple of aspect.dev PRs. Hope you don't mind 🙂

**Comment by philipp-spiess** [comment]
@valerybugakov Thanks haha :)

**Pull request merged**
