### PR TITLE
Use Dart Sass

### PR DESCRIPTION
**Pull request by felixfbecker**
`sass-loader` recommends using Dart Sass, which has become the official Sass implementation, as opposed to `node-sass` (`libsass`).

- No Node native addons, which means easier Node version upgrades
- Potentially solve some of the build flakiness (we don't know the root cause, but the errors always occur with `node-sass`)
- More precise float division
- Get new Sass features faster

But it is slightly slower. Build time sampled of enterprise web build from master (BEFORE), in seconds:

```
Count             : 100
Average           : 188.28016
Sum               : 18828.016
Maximum           : 283.475
Minimum           : 155.124
StandardDeviation : 30.953466408162
Property          :
```

On this branch (AFTER):

```
Count             : 6
Average           : 205.923166666667
Sum               : 1235.539
Maximum           : 254.762
Minimum           : 163.391
StandardDeviation : 37.7923489739215
Property          :
```

### CODE REVIEW

**Comment by felixfbecker** [comment]
@eseliger I have a theory what could cause the visual differences: we set `line-height` to `20/14`. Dart Sass might have a different floating point precision for division than libsass.

**Comment by felixfbecker** [comment]
Yep: `node-sass` calculates `1.42857`, Dart sass calculates `1.4285714286`

**Comment by felixfbecker** [comment]
Sampled web enterprise build times from master:

```
Count             : 100
Average           : 183.72s
Sum               : 18372.08s
Maximum           : 280.75s
Minimum           : 153.61s
StandardDeviation : 27.68s
```

**Comment by eseliger** [comment]
So this is _before_?

**Comment by felixfbecker** [comment]
Yep

**Comment by felixfbecker** [comment]
@sourcegraph/web I'd like to gather your thoughts on how we feel about the trade-off with build time here (see PR description)

**Comment by eseliger** [comment]
CI time I don't mind so much, is it much worse on recompile for the dev env?

**Comment by marekweb** [comment]
Going from a compiled module (if I understand correctly, libsass in C) to a JS module, it's interesting that the performance penalty is not really that significant. Looks like an OK tradeoff.

**Comment by felixfbecker** [comment]
The team has spoken!

**Comment by felixfbecker** [comment]
If things turn out to be too slow, @twop gratiously offered to rewrite our build tools in Rust+WASM.

**Pull request merged**
