### PR TITLE
static render of design

### PR DESCRIPTION
**Pull request by unclejustin**
Closes https://github.com/sourcegraph/sourcegraph/issues/30113

### CODE REVIEW

**Comment by vovakulikov** [comment]
Hey, @AlicjaSuska I finished this PR at some point. Almost everything like we have it in our Figma designs (including an updated copy) but there is one small thing about the gray callout arrow element. I left a comment in Figma about it https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW?node-id=1128:9814#147901927

In the nutshell I ended up with a simplified variant here because couldn't figure out how to deal with this element in the mobile layout. Maybe @unclejustin has ideas about it.

**Comment by vovakulikov** [comment]
Hey, @AlicjaSuska I finished this PR at some point. Almost everything like we have it in our Figma designs (including an updated copy) but there is one small thing about the gray callout arrow element. I left a comment in Figma about it https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW?node-id=1128:9814#147901927

In the nutshell I ended up with a simplified variant here because couldn't figure out how to deal with this element in the mobile layout. Maybe @unclejustin has ideas about it. 

Screenshot 2022-02-03 at 17 46 13

**Comment by AlicjaSuska** [comment]
Thank you @vovakulikov I understand the concern about the arrow. I think that badge grabs too much attention and causes a misalignment between the chart and the header + makes the empty white space below the CTA even bigger.

I'd rather move forward without the arrow at all. Since both fields have the 'success' state, they look interactive. Alternatively, we could also focus on the query field by default so that the cursor is blinking. wdyt @vovakulikov @Joelkw ?

**Comment by Joelkw** [comment]
@AlicjaSuska I agree the badge saying "interactive example" competes and isn't necessary. I'd hesitate to focus the query fields by default because that might have accessibility implications, and also feels a bit click-hijack-y to me. 

@vovakulikov  @AlicjaSuska  is there a "geometric" version of the arrow/note we could use instead, if the curve is the problem? I agree there's an odd amount of white space otherwise and it'd be nice to call out that it's interactive.

**Comment by AlicjaSuska** [comment]
Update after discussing with @vovakulikov :
- @Joelkw, I think there was a misunderstanding about the problem: the issue @vovakulikov described is with the placement of the arrow, not the shape of the arrow. Especially placement on mobile.
- we've agreed to leave the arrow on the desktop as is now. On mobile, we'll display elements in the following order: text - interactive insight - arrow ([Figma](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-WIP?node-id=1684%3A27176)):

Screenshot 2022-02-04 at 16 21 05

**Comment by vovakulikov** [comment]
Okay after discussion with @AlicjaSuska we brought the arrow element back and fix the mobile version of the layout with this element. [Desings](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-WIP?node-id=1684%3A27176)

Screenshot 2022-02-04 at 18 47 26

**Comment by vovakulikov** [comment]
@unclejustin can you please check that problem with CLA bot. Do we need to re-create the branch? Something definitely went wrong with cla check there. Feel free to create a new branch or whatever you need to avoid this poblem.

**Comment by felixfbecker** [comment]
My guess with the CLA error is that the problem is the PR was opened by @unclejustin but had no commits from @unclejustin, just @vovakulikov. I'd try pushing a new branch and reopening the PR @vovakulikov.

**Comment by unclejustin** [comment]
@vovakulikov let's move these changes to a different branch and try merging that. When I set up my new laptop I used the wrong email address (womp). I've corrected it since, but this PR is now corrupted.

**Comment by felixfbecker** [comment]
Can this be closed?

**Comment by vovakulikov** [comment]
I believe so, it seems this PR change was implemented in a separate PR and we just forgot about this one. cc @unclejustin I'm closing this let me know if we need this one

**Pull request closed without merging**
