### PR TITLE
Update auto-inference to work with NPM packages

### PR DESCRIPTION
**Pull request by varungandhi-src**
- First commit is a no semantic change commit that introduces a helper method `pathMap.insert` that's useful in the second commit.
- Second commit implements the main change where I tweak auto-inference to work with NPM packages.

Main questions:
- [ ] I've changed the invocation `npm install` to `npm install --ignore-scripts`, because the latter seems to be more applicable to TypeScript packages on NPM. Should we only do that in certain cases? (e.g. When we know we're trying to infer steps for an NPM package? When we see that one of the build steps involves deleting the `dist` directory?) What could go wrong by using `--ignore-scripts`?
- [ ] Should I add more tests? If so, what kind of tests?

### CODE REVIEW

**Review by olafurpg — CHANGES_REQUESTED** [review]
Would be be able to simplify this logic if npm package repos had a marker file similar to `lsif-java.json`? I think it's desirable to keep the inference logic as simple as possible. Instead, we should move the syntehtic `tsconfig.json` logic into lsif-node itself where we can iterate on it and release new improvements quickly without updating auto-inference. WDYT?

**Comment by olafurpg** [comment]
lsif-java has custom support to work with `lsif-java.json` https://github.com/sourcegraph/lsif-java/blob/a96b7eb03293f208bc609a121aad22e972272a22/lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/LsifBuildTool.scala#L78

**Comment by varungandhi-src** [comment]
Isn't there a problem with hash invalidation though? We don't know for sure whether this is good enough (at least, I'm not confident if this logic is enough to handle all the common cases in practice), and if we put that into an `lsif-node.json`, then we can't change the contents of the `lsif-node.json` in the future (say, because we think we can do a better job at inference) without invalidating the hashes of existing packages.

**Comment by varungandhi-src** [comment]
Let me close this; I'll create a separate PR for that, since it won't share much with this anyways.

**Pull request closed without merging**
