### PR TITLE
WIP web: Combine repository setting pages

### PR DESCRIPTION
**Pull request by keegancsmith**
As part of removing enabled/disabled state the landing page for repository
settings has much less information to show. So the decision was made to combine
all the pages into one. This commit naively combines all the current pages
without doing any adjustments as mentioned in the design.

Part of #2025

Test plan: Visit the settings page in development mode. Will also visit page with indexing disabled.

#### Design

This is a WIP, so we are still far off from the design. Additionally this PR will not implement the external service cards. That will be another PR. See comments images of current state.

Sourcegraph Engineer / Design Spec Link: https://zpl.io/anpXvGr
Public / Non-Engineer Design Link: https://sketch.cloud/s/wwoGV/Axae1bR/play

image

### CODE REVIEW

**Comment by keegancsmith** [comment]
@francisschmaltz the current state of this PR is still WIP, but I wanted to get some early feedback. The redesign is currently not showing what it looks like when we have indexed the repository. The old implementation shows indexing statistics. It also supports listing multiple indexed branches. Multiple indexed branches is not on our roadmap but has been requested from users so may get prioritized at some point.

I plan to implement the external service cards in another PR, since that touches quite a bit more code (including the backend). However, I'll update this PR to more closely match the design mocks.

#### Example without errors

screencapture-localhost-3080-github-com-keegancsmith-counsel-repo-settings-2019-04-04-10_07_46

#### Example with errors

screencapture-localhost-3080-github-com-keegancsmith-counsel-repo-settings-2019-04-04-09_59_01

**Comment by francisschmaltz** [comment]
@keegancsmith Sounds good! Let me know when all the UI is implemented. Since you're adding the card in a different PR, lets get the UI for all repos to the state here https://zpl.io/25O0Rqe and then work from there. I've added in indexing and errors to the mocks as well.

**Comment by felixfbecker** [comment]
@keegancsmith do you want me to review this already?

**Comment by keegancsmith** [comment]
> @keegancsmith Sounds good! Let me know when all the UI is implemented. Since you're adding the card in a different PR, lets get the UI for all repos to the state here https://zpl.io/25O0Rqe and then work from there. I've added in indexing and errors to the mocks as well.

Thanks! Will do

> @keegancsmith do you want me to review this already?

No. Note: I didn't add you as a reviewer (code owner)

**Comment by felixfbecker** [comment]
> No. Note: I didn't add you as a reviewer (code owner)

Then please use a draft PR next time, which avoids adding code owners as reviewers and sending out emails (as the code owner eventually I will want to review this code before merging, which is when you mark it as ready for review) 🙂

**Comment by keegancsmith** [comment]
This PR is super simple and was really just to kick-start discussion. The work for this milestone has gone into toher PRs. For 3.4 repository settings pages will be combined.

**Pull request closed without merging**
