### PR TITLE
Add browser extension integration tests

### LINKED ISSUE #12180: Add integration tests for browser extension
We have integration tests for the webapp now, and the infrastructure for it is generic and resides in shared/: https://github.com/sourcegraph/sourcegraph/blob/master/shared/src/testing/integration/context.ts

The browser extension can use this the same way the webapp does to define tests similar to the current browser extension e2e tests. The browser extension would more heavily rely on HARs (not used in the webapp anymore) to record and replay responses from code hosts, since those are harder to define manually.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #12180 

Kicked-off at hack time.

### CODE REVIEW

**Comment by tjkandala** [comment]
@marekweb @felixfbecker `CDPAdapter` is ready for review. All web tests are passing and background page requests are being intercepted. We will convert e2e tests to integration tests in separate PRs.

**Comment by felixfbecker** [comment]
@tjkandala to make sure I understand you correctly: this PR is ready to be merged? @marekweb could you review this this week?

**Comment by felixfbecker** [comment]
There's some weird error in Chromatic from Storybook that I can't make sense of, wonder if it reproduces locally.

**Comment by felixfbecker** [comment]
@tjkandala is this PR still relevant?

**Comment by tjkandala** [comment]
@felixfbecker We will be using this code for our DX project (browser extension integration tests). If necessary, you can close this PR and we can open a new PR for this branch.

**Comment by felixfbecker** [comment]
I think you can't open two PRs for the same branch in GitHub, so I'll just leave it open, unsubscribe and you can do what you want with :)

**Comment by tjkandala** [comment]
Closing this PR in favor of #23235, in which we've implemented [passing tests for GitHub and GitLab](https://buildkite.com/sourcegraph/sourcegraph/builds/103452#28aeca13-e161-4a20-9f73-22fa3e314b9d), as well as added a pipeline step to run these tests alongside our existing Puppeteer tests.

**Pull request closed without merging**
