### PR TITLE
web: don't disable "Settings" menu item for uncloned repos.

### PR DESCRIPTION
**Pull request by sashaostrikov**
Test plan:
Local sg run and visual check.

Spotted by @indradhanush [here](https://sourcegraph.slack.com/archives/C05HF5XGMFF/p1691052793147489)

### CODE REVIEW

**Comment by indradhanush** [comment]
@sashaostrikov Could you please add a screenshot of what this looks like now?

**Comment by sashaostrikov** [comment]
@mrnugget @indradhanush well, I thought it should work because we have an exception for site-admins being able to visit repo settings page ([here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/RepoContainer.tsx?L476-483)), but apparently it doesn't work. I think there might be a bug

**Comment by sashaostrikov** [comment]
@mrnugget @indradhanush I looked for the wrong repo. Retested for a legit empty repo and it works:


https://github.com/sourcegraph/sourcegraph/assets/94846361/c3e9bf0f-ee3d-4af4-86dd-4ee100090a6d

**Review by indradhanush — APPROVED** [review]
Looks good! 

What I was initially referring to is a link from the empty repo page to the settings page. 

But this is a good fix nonetheless. 👌

**Comment by sashaostrikov** [comment]
> What I was initially referring to is a link from the empty repo page to the settings page.

Yeah, I took a look into it and decided that it won't be that quick for me, I'll take a look [into it](https://github.com/sourcegraph/sourcegraph/issues/55547) next week, after I finish writing impact reviews :)

**Comment by mrnugget** [comment]
But an empty repo that successfully cloned is not what @indradhanush was asking about in Slack, right?

> Occasionally we and our customers see empty repository in case there has been an error with cloning the repo. Or the repo is being cloned. Either way, there is no way to navigate to the settings page of a repo until it has already been cloned. For repos that struggle to be cloned in the first place we won’t have any insight.

That sounds to me like repos that currently-cloning or failed to clone, right?

**Comment by sashaostrikov** [comment]
The screenshot was for the empty repo. That's why I decided to go that way. Anyway, that part was also not working.

As for currently cloning or failing to clone -- yep, that's a separate thing. We should make changes to Routing checks so that they don't redirect to `EmptyRepo`.

I've extended the description of an [issue](https://github.com/sourcegraph/sourcegraph/issues/55547) I've created to address this problem too.

**Pull request merged**
