### PR TITLE
[SG-35354] Accessibility: Contributors page: Button group "active" style is very similar to focus style

### PR DESCRIPTION
**Pull request by gitstart-sourcegraph**
### Description
The `focus` state and `active` state of the `group buttons` are  not distinct. One can mistake the other for another.

### Refs
[SG Issue](https://github.com/sourcegraph/sourcegraph/issues/35354)
[GitStart Issue](https://app.gitstart.com/clients/sourcegraph/tickets/SG-35354)

### Acceptance Criteria
1. The `focus state` remains as it is.
2. The `active state` is made to behave as the `hover` state.

### Test plan
- Navigate to the contributor's page. The group buttons should satisfy the **Acceptance Criteria**

## App preview:

- [Web](https://sg-web-contractors-sg-35354.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-sxggwcgvpn.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by valerybugakov** [comment]
@sourcegraph/design, could you take a look?

**Comment by felixfbecker** [comment]
Ping @sourcegraph/design

**Review by valerybugakov — APPROVED** [review]
LGTM from the technical pov. Let's wait for approval from the design team.

**Review by rrhyne — APPROVED** [review]
LGTM

**Pull request merged**
