### PR TITLE
cody: fix sign in issues with App

### PR DESCRIPTION
**Pull request by abeatrix**
Close https://github.com/sourcegraph/sourcegraph/issues/54045
Moved from https://github.com/sourcegraph/sourcegraph/pull/54063

This PR solves connection issues with App where:
1. can’t log out and get back in without access token 
2. can't log in if you have VS Code open first, before installing app

App team has confirmed the changes in this PR fixed the issue: ([slack thread 1](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687808792458379?thread_ts=1687789189.320849&cid=C04F9E7GUDP), [slack thread 2](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687809644246859?thread_ts=1687789189.320849&cid=C04F9E7GUDP), [slack thread 3](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687810950226229?thread_ts=1687789189.320849&cid=C04F9E7GUDP))

### Auth View Loading Issue - moving to a new PR
Notice we were setting authStatus on config change, which would first pick up the default config when the view is first loaded.

Update to send authStatus with config file via the publishConfig function, which gets trigger on every config change, and the login function also triggers it since the login function also updates the user config. this one we can make sure the config call would have the latest info.

Here you can see the call stack where login would be called before config change
image

### update

i found that i broke the last PR by accidentally removed (!view), where  `vscodeAPI.postMessage({ command: 'initialized' })` gets called repeatedly 😭 

```
        if (!view) {
            vscodeAPI.postMessage({ command: 'initialized' })
        }
```

## Test plan

Here is a video of how the changes would look:

https://github.com/sourcegraph/sourcegraph/assets/68532117/3875d28c-1ee9-4ab5-9334-cd0154462d44

### CODE REVIEW

**Review by toolmantim — APPROVED** [review]

**Comment by toolmantim** [comment]
@abeatrix just pushed some fixes for the Storybook renders, and approved them on Chromatic ✅

**Review by philipp-spiess — COMMENTED** [review]
There are still issues for me even after those changes. When i reload VS Code, I’m always logged out 😞

https://github.com/sourcegraph/sourcegraph/assets/458591/39451b21-bff1-4de8-ad6b-6d6504692065

**Comment by philipp-spiess** [comment]
Noticed something else on `main` (might be fixed on your PR but I want to write it down regardless):

When I reload VS Code, Cody always shows up on the sidebar, even if I had another sidebar view active before.

**Comment by toolmantim** [comment]
I'm experiencing both of these two @philipp-spiess

**Comment by abeatrix** [comment]
Hmm the logout issue is weird I don't think I've run into that before. 
@philipp-spiess Can you check if you have a different Endpoint set in your workspace settings?
@toolmantim ill take a look at this thanks for testing!

**Comment by philipp-spiess** [comment]
@abeatrix My user config has 

```
  "cody.serverEndpoint": "https://sourcegraph.com/",
```

But I also picked the dotcom login in the dropdown list I think

**Comment by abeatrix** [comment]
@toolmantim @philipp-spiess the app team has confirmed the changes in this PR solved the sign in issues with App ([slack thread 1](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687808792458379?thread_ts=1687789189.320849&cid=C04F9E7GUDP), [slack thread 2](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687809644246859?thread_ts=1687789189.320849&cid=C04F9E7GUDP), [slack thread 3](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687810950226229?thread_ts=1687789189.320849&cid=C04F9E7GUDP)), so I'm going to merge this PR and open a new PR for the loading issue.

**Comment by abeatrix** [comment]
Here is the latest demo of the sign in flow using the last commit from this branch: https://www.loom.com/share/9a3be7ebff0248748522da1c3bc5b3df?sid=b755b69b-7ede-424d-b9d0-b966991a9b1f

**Pull request merged**
