### PR TITLE
Prune storage

### LINKED ISSUE #3604: Remove unused StorageItems from browser extensions
There are a lot of StorageItems that are not _written_ to anywhere in the code base (they are _read_ though).

https://github.com/sourcegraph/sourcegraph/blob/68b73cac8a1fd9a9f2ad221ee12d53bd53b84d15/client/browser/src/browser/types.ts#L55-L79

@KattMingMing @sqs can we remove them or are they set through GCloud Admin and used by customers? If they are, which of them, and who did we document them to?

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #3604

### CODE REVIEW

**Comment by felixfbecker** [comment]
@ijsnow not sure how I would test managed storage and these settings, since we don't use them. I don't know if any customers use them. I was hoping from some insight from you how they work? See my comments in #3604

**Comment by lguychard** [comment]
@felixfbecker what is the status of this PR? Are you planning to close it in 3.4? If not, we should move https://github.com/sourcegraph/sourcegraph/issues/3604 out of the 3.4 milestone.

**Comment by felixfbecker** [comment]
I need information on what settings our customers use 😐
Moved to 3.5

**Comment by slimsag** [comment]
This PR has been open for a very long time with no progress, closing. Reopen if desired.

**Pull request closed without merging**
