### PR TITLE
JetBrains: Cody: Adding animation when waiting for first cody response

### PR DESCRIPTION
**Pull request by Sa1to**
It helps [JetBrains: Chat: Add some nice distraction while the first chunk of Cody's response is loading #152](https://github.com/sourcegraph/cody/issues/152)
## Test plan
* Open Cody chat window
* Write some message and check if waiting animation is displayed
* Write another message and before Cody response is loaded, press "Stop generating" button. Check if waiting animation disappeared after pressing the button.

https://github.com/sourcegraph/sourcegraph/assets/9321940/827dd6e6-bf01-40f5-81de-ff7f865aeadd

### CODE REVIEW

**Comment by vdavid** [comment]
I like the playfulness of this solution 🙃  WDYT, @danielmarquespt?

**Comment by Sa1to** [comment]
@olafurpg Please take a look :)

**Comment by danielmarquespt** [comment]
I really like the feedback for the user, but I think it would work better with a regular spinner.

Those are circular so rotation feels natural, rotating the Cody logo does not feel as natural or pleasant

**Comment by olafurpg** [comment]
Thank you for this contribution @Sa1to ! I am going to close this PR as a wontfix. The change itself is a nice improvement but this is not something that our small team is prioritizing right now.

**Pull request closed without merging**
