### PR TITLE
gitserver: use TLS configuration when pushing

### LINKED ISSUE #31010: gitserver: TLS configuration is ignored when invoking `git` from `createCommitFromPatch`
This was reported in sourcegraph/customer#688.

It's possible to configure Sourcegraph to communicate with a code host that uses a self-signed certificate by setting the following options:

1. In the external service configuration, adding a `certificate` option with a public key, and
2. In the site configuration, adding a block to `experimentalFeatures` that looks something like this:
    ```json
    "experimentalFeatures": {
      "tls.external": {
        "certificates": [
          "-----BEGIN CERTIFICATE-----\n<CERT CONTENT>\n-----END CERTIFICATE-----"
        ]
      }
    }
    ```

(There's also an option to just straight up skip verification, but let's pretend we didn't see that for now.)

These get used for different things: the site configuration certificate is used for API requests to the code host, and then the `tls.external` certificate is used by `gitserver`. (Why are these different? Good question. No idea.) The former works fine across the board. The latter works fine… for cloning and pulling. But not for pushing, which is what we need in Batch Changes.

Why?

[`cmd/gitserver/server` provides a function called `runWith`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d2b66247fa63b6317da259b003a2666d9ec2b3b4/-/blob/cmd/gitserver/server/serverutil.go?L149) that ensures that the right environment variables are provided to Git to handle the TLS configuration (among other things). Unfortunately, [`createCommitFromPatch` provides its own wrapper](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d2b6624/-/blob/cmd/gitserver/server/patch.go?L105) that doesn't delegate down to `runWith`.

I think the quick and dirty fix here is just to delegate to `runWith` instead of directly to `CombinedOutput()`, since the semantics are essentially the same. Testing this now, PR coming soon.

### PR DESCRIPTION
**Pull request by LawnGnome**
Fixes #31010.

## Test plan

Manually tested against a self-signed GitLab instance; tested against bitbucket.sgdev.org to make sure nothing unexpected broke. Unit tests continue to pass because _in theory_ there should be no behavioural change in the normal case; further automated testing has insufficient ROI (we'd need internal infrastructure just for this edge case).

### CODE REVIEW

**Review by courier-new — APPROVED** [review]
Thanks for putting in the effort to actually validate and test this fix. 🙏

**Review by eseliger — APPROVED** [review]
Great find!
I wonder if the env-forwarding can cause any trouble, but given it still works 🤷‍♂️

**Comment by LawnGnome** [comment]
> I wonder if the env-forwarding can cause any trouble, but given it still works 🤷‍♂️

I had the same thought, but I don't think `runWith` is setting anything that would cause any problems for us otherwise.

**Comment by eseliger** [comment]
yeah just double checked, we actually already forwarded the os.Environ() everywhere `run` is called

**Pull request merged**
