### PR TITLE
migrations: Drop global_dep and pkgs

### PR DESCRIPTION
**Pull request by keegancsmith**
These have been unused since 3.0. Our deprecation policy is 2 releases before making a backwards incompatible DB change.

### CODE REVIEW

**Comment by tsenart** [comment]
I pushed this already to our branch.

**Comment by keegancsmith** [comment]
Yeah, but we can merge it separately so thought it was worth putting into a PR.

**Comment by tsenart** [comment]
We need the migration numbers to be sequential. If we are going to extract this one to a separate PR, the leading number should change.

**Comment by tsenart** [comment]
1528395567 -> 1528395565

**Comment by keegancsmith** [comment]
Also note we don't name the migrations anymore so we get conflicts if two PRs create a migration at the same time.

**Pull request merged**
