### PR TITLE
Add security guidance to README

### PR DESCRIPTION
**Pull request by christinaforney**

### CODE REVIEW

**Comment by christinaforney** [comment]
> @beyang has historically owned our /security page and policies. Worth getting his 👍 at some point, but this seems unoffensive to me for now if you want to merge this week.

Not urgent, so happy to wait to merge this until I get his approval!

**Comment by slimsag** [comment]
GitHub has standard security policy features that integrate if this is placed into a SECURITY.md file instead. https://help.github.com/en/articles/adding-a-security-policy-to-your-repository

**Comment by dadlerj** [comment]
Hah — I had said we didn't want to maintain a separate SECURITY.md file, and preferred to add it to the README, but I didn't appreciate the new GitHub policy... 

I'm fine if you prefer to put it in a SECURITY file, but I want to keep most of this info a single place so we don't end up with mismatch info on this (and ideally our https://about.sourcegraph.com/security page).

**Comment by slimsag** [comment]
My guess is that more and more automated tooling (including on our end) will in the future make use of `SECURITY[.md]` files in the same way that e.g. GitHub and other code hosts present README's at the forefront.

I would suggest that ours just link to https://about.sourcegraph.com/security

**Pull request closed without merging**
