### PR TITLE
debt: Remove NamespaceUserID and NamespaceOrgID from external services

### PR DESCRIPTION
**Pull request by ryanslade**
This concept no longer exists as it was part of Cloud V1. Database
tables were left intact.

- [x] Confirm integration tests pass

## Test plan

Tests updated and removed
Will confirm dry run integration tests pass

### CODE REVIEW

**Comment by ryanslade** [comment]
Integration tests running here:
https://buildkite.com/sourcegraph/sourcegraph/builds/186270

**Comment by indradhanush** [comment]
Thank you for doing this. Let's not merge this until next week though. Just in case.

**Review by unknwon — APPROVED** [review]
Did not look at more than one line of code, but

**Review by cbart — APPROVED** [review]
👍 

Do I see right that at some point this would be followed with a migration to remove `namespace_user_id` and `namespace_org_id` from `external_services`?

**Comment by ryanslade** [comment]
> 👍
> 
> Do I see right that at some point this would be followed with a migration to remove `namespace_user_id` and `namespace_org_id` from `external_services`?

Yep, correct. But that's the last thing we want to do since we can't easily reverse it.

**Comment by mrnugget** [comment]
FYI we deleted some of the same code in previous week's `sg hacking hour`: https://github.com/sourcegraph/sourcegraph/pull/44824 but I was too slow to fix the frontend build to merge this. I think this PR here should take precedence, but you might want to take a look at the other PR to see how a test was fixed etc.

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.42 kb) | -0.00% (-0.42 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/rs/remove-namespace-graphql/compare-report.html;tab=live_object) for a full comparison between the commits 525a8ff and e14b9c8 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by ryanslade** [comment]
All green (including integration tests, will merge)

**Pull request merged**
