### PR TITLE
Remove icon from GraphQL schema

### LINKED ISSUE #19892: Remove GraphQL icon field
The icon field was deprecated after the 3.26.3 release, and should be removed in two releases.

### PR DESCRIPTION
**Pull request by camdencheek**
The icon resolver method of GenericSearchResultInterface is no longer
being used by the frontend, and is unlikely to be useful to anyone else
since `FileMatchResolver` already doesn't provide it. This commit removes icon
from the schema and from the resolvers.

Closes #19892

### CODE REVIEW

**Review by rvantonder — COMMENTED** [review]
Is there an off-chance this breaks clients that expect `Icon`? Maybe `src-cli`? Edit: is this a [potential reference](https://sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/internal/streaming/events.go#L78) in src-cli? It's probably not needed...

This sounds OK and I'm all for removing stuff but I don't really know what risk this poses so not confident about approving.

**Review by felixfbecker — APPROVED** [review]

**Comment by felixfbecker** [comment]
Good riddance :)

**Review by keegancsmith — CHANGES_REQUESTED** [review]
For backwards incompatible changes we first deprecate then remove 2 releases later. Even though no one is now using this (that we know of), we need to take this approach unfortunetly.

**Comment by camdencheek** [comment]
Sounds good -- I'll close this and open up a PR that deprecates it instead

**Pull request closed without merging**
