### PR TITLE
doc: initial document on exhaustive search

### PR DESCRIPTION
**Pull request by keegancsmith**

### CODE REVIEW

**Comment by lguychard** [comment]
@rrhyne this is probably relevant for you to review -- it documents how users can run an exhaustive search, and what they can expect from exhaustive searches.

**Comment by rrhyne** [comment]
This is so good. 

My only question (and it might be too early for this to land in the documentation) is will we document the scheduler mentioned in the RFC and its capacity/rules?

**Review by rrhyne — APPROVED** [review]

**Comment by keegancsmith** [comment]
> My only question (and it might be too early for this to land in the documentation) is will we document the scheduler mentioned in the RFC and its capacity/rules?

We mention the scheduler indirectly:

> Over time the priority of a query is reduced. This is to ensure we have capacity to answer interactive queries quickly, while still allowing slow queries to run to completion.

Do you think we should make it more explicit? For now I believe we will tune / adjust it based on feedback. As it stands we are already running into rate limit issues on dotcom which is independent of the scheduler.

I'm trying to imagine what we will say when someone reports it isn't working. I imagine I'd point them to the prometheus metric `zoekt_shards_sched`. I'm not sure that is worth documenting right now? But maybe there is some place I can write docs for CE?

**Comment by rrhyne** [comment]
Sorry, a bit late on this. If an admin or user can't change anything about it, it probably doesn't make sense to mention it. My only concern is how we would know zoekt_shards_sched a problem other than user-supplied feedback. This is probably where getting some metrics back in pings would be helpful.

**Comment by keegancsmith** [comment]
> My only concern is how we would know zoekt_shards_sched a problem other than user-supplied feedback.

Yeah this is a problem in general. We don't really want to alert on it. Additionally metrics like "average search time" are far more useful. When this metric becomes useful is debugging why average search time has gone up. So the follow-up action item should be to ensure we have some metrics in a dashboard for general search debuggability. This has been a long time coming, so I will finally file an issue about it :)

**Pull request merged**
