### PR TITLE
search multiple repos at multiple revisions

### PR DESCRIPTION
**Pull request by rvantonder**
This change allows to specify search queries on multiple repos at multiple revisions. Here is an example syntax:

```
repo:^github\.com/rvantonder/foo$@some-revision|^github\.com/rvantonder/bar$@other-revision|^github\.com/rvantonder/qux$@final-revision
```

I briefly checked that one can use commit sha hashes, tag names, and branch names after the `@`, so this should work. Let me know if there's an issue. The syntax is quite strict so that it minimizes the chance of other conflicting syntax. In particular:

- Each repo name _must_ be anchored by `^` and `$`
- Each repo name _must_ be a constant string, no regex syntax allowed! This is _checked_ and will not work otherwise. Note in the query above that `.` are escaped, as usual. So, for example, if the `.` were not escaped, it won't work. If a regex operator like `|` is used anywhere besides separators for repos, it won't work. If a regex `*` is used anywhere, it won't work. The behavior will be whatever the search behavior would have done without the changes in this PR.

The above syntax applies _only_ to searching of revisions of _different_ repositories. That is, the following will _not_ work, since multiple revisions are searched in the same repo, and you will get a message saying that it's not possible:

```
repo:^github\.com/rvantonder/foo$@a-revision-in-repo-foo|^github\.com/rvantonder/foo$@another-revision-in-repo-foo
```

It _is_ possible to do the above, but with a different syntax and functionality that already exists. To do that, use `:` to separate the revisions for the same repo:

```
repo:^github\.com/rvantonder/foo$@a-revision-in-repo-foo:another-revision-in-repo-foo
```

The `:` syntax above is an **experimental feature so you must enable the following in the site config**

```
  "experimentalFeatures": {
    "searchMultipleRevisionsPerRepository": true
  },

```

If the above is done, you can use combinations of the syntaxes of `|` and `:` to effectively search multiple repos at multiple revisions. I.e., this is fine:

```
repo:^github\.com/rvantonder/bar@revision|^github\.com/rvantonder/foo$@a-revision-in-repo-foo:another-revision-in-repo-foo
```

---

Due to an unrelated part of this change, it is possible that a search for the above will not only include file content results, but may also include name of the matched repos. For example, note the `Repository name match` results included in this multi-repo-multi-rev search:

Screen Shot 2020-03-31 at 4 38 09 PM

If this is problematic let me know, but that will be some extra effort to avoid.

To reproduce the above screenshot and test that this works:

- make sure the site config has that experimental feature flag on
- clone `github.com/rvantonder/another-test` and `github.com/rvantonder/weeeee`
- run the query:

```
repo:^github\.com/rvantonder/another-test$@revision-contains-b|^github\.com/rvantonder/weeeee$@revision-contains-z:revision-contains-q q|b|z
```

### CODE REVIEW

**Comment by dadlerj** [comment]
Thanks! To clarify the requirements at the top, none of these will apply if a user is doing a "standard" search, correct? I.e., this won't change any default search behavior?

**Comment by rvantonder** [comment]
> I.e., this won't change any default search behavior?

Indeed, that's the intent. The confidence we have is that this PR passes existing tests, meaning anything tested (which is hopefully decently thorough) is guaranteed to be OK.

**Comment by tsenart** [comment]
Can this PR be closed?

**Comment by rvantonder** [comment]
No, I'd like to keep this open because it contains code that may be useful for the planned work ahead. Closing it might delete the branch and an open PR is easier to find this way.

**Pull request closed without merging**
