### PR TITLE
CodeMirror: Make search-based code intelligence keyboard navigable

### PR DESCRIPTION
**Pull request by umpox**
## Description

This is a basic implementation at making our code accessible for all files (not just precise code intelligence)

This PR:
- Falls back to using occurrence information to build accessible tokens.
  - These tokens navigate to the references panel, which will either display valid information about definitions/references etc OR show "Failed to find token". Ideally we would render hover overlays here but we may not have time to implement this before we begin our accessibility audit.
   
## Test plan

Tested locally with a keyboard on files with no precise code intelligence

## App preview:

- [Web](https://sg-web-tr-blob-search-accessibility.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.49 kb) | 0.00% (+0.49 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/tr/blob-search-accessibility/compare-report.html;tab=live_object) for a full comparison between the commits f33115a and b74554d or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by olafurpg — APPROVED** [review]
LGTM 👍🏻 It's very nice to keyboard navigation working for search-based. 

However, we can't release the current feature as GA. The biggest blocking issue IMO for enabling this feature is that we render anchor links for all navigable tokens including ones that don't have meaningful code intel. We should stop using anchor links and use buttons instead that display a spinner when you click on them and should handle all cases of:

* There is not definition, tell the user there is no definition
* You're at the definition, trigger "find references" 
* There is a single definition, jump to it
* There are multiple definitions, open the ref panel with a focus on "Definitions"

No matter how hard we try, "go to definition" is never going to work like a normal HTML anchor link and we're misleading our users by rendering them as links. "Go to definition" is a rich navigation action with several different outcomes and our UI should treat it as such. There's no need to reinvent the wheel, we should use the same established patterns for "Go to definitioN" as VS Code and IntelliJ do. Clicking on a token should trigger the popover, and Cmd+Click should trigger "Go to definition". The automatic timeout to display the popover should be increased to a much longer delay like 2-3 seconds. Ideally, we should also support a keyboard shortcut an a right-click menu with "Go to definition" action.

**Comment by quinnkeast** [comment]
> LGTM 👍🏻 It's very nice to keyboard navigation working for search-based.
> 
> However, we can't release the current feature as GA. The biggest blocking issue IMO for enabling this feature is that we render anchor links for all navigable tokens including ones that don't have meaningful code intel. We should stop using anchor links and use buttons instead that display a spinner when you click on them and should handle all cases of:
> 
> * There is not definition, tell the user there is no definition
> * You're at the definition, trigger "find references"
> * There is a single definition, jump to it
> * There are multiple definitions, open the ref panel with a focus on "Definitions"
> 
> No matter how hard we try, "go to definition" is never going to work like a normal HTML anchor link and we're misleading our users by rendering them as links. "Go to definition" is a rich navigation action with several different outcomes and our UI should treat it as such. There's no need to reinvent the wheel, we should use the same established patterns for "Go to definitioN" as VS Code and IntelliJ do. Clicking on a token should trigger the popover, and Cmd+Click should trigger "Go to definition". The automatic timeout to display the popover should be increased to a much longer delay like 2-3 seconds. Ideally, we should also support a keyboard shortcut an a right-click menu with "Go to definition" action.

I generally agree with most of these thoughts. Like @olafurpg says, the UI patterns established around go to def in IDEs are solid and well-understood, and we'll probably need to mirror most of that behaviour. This'll take followup.

What I'm not sure about right now: what's the diff between what's required for the audit vs. GA?

**Comment by olafurpg** [comment]
@lrhacker is it acceptable that the a11y compatible workflow requires an enabling a configuration option that's disabled by default? If not, then we'll need to reach GA for the new keyboard workflow.

**Comment by lrhacker** [comment]
@olafurpg to some degree, yes, I think it is acceptable (in this case, my opinion is that it's definitely okay). As far as I know, the remaining work to get this to GA is already something we (Code Exploration) would want to be doing relatively soon based on our team's goals (cc @felixfbecker for confirmation).

IMO, since we are already motivated to get this to GA in a timely fashion, we have little risk in the blob view being a total mismatch from the audit results (as in, we won't have a blob view that's less accessible than originally audited - probably only more accessible). And even if it happens to not be the default yet, it can still be enabled in the app for folks who need it (like for any specific clients/contracts - but this obviously is not ideal and not the goal!).

**Comment by quinnkeast** [comment]
FYI, I'm going to capture the followup in [this design challenge doc](https://docs.google.com/document/d/1wy6Vc5yPSsVz35ikF5TF_5RuYpZ0pYlJB7wO884lcoc/edit#heading=h.qdhglxqcjf0d) for the time being so that we don't lose track of it.

**Pull request merged**
