### PR TITLE
campaigns: Handle GitHub merge events

### PR DESCRIPTION
**Pull request by ryanslade**
GitHub does not send specific `merge` webhook events, instead it sends a `PullRequest` event with the `close` action and sets a `merged` flag.

https://developer.github.com/v3/activity/events/types/#pullrequestevent

When we see that flag set we'll persist it as a `MergeEvent` instead.

Closes: https://github.com/sourcegraph/sourcegraph/issues/10071

### CODE REVIEW

**Comment by ryanslade** [comment]
One thing I'm not sure about is we are not populating this field:
https://github.com/sourcegraph/sourcegraph/blob/33880a51d811bb9c68b065997a9e1db6defb18cf/internal/extsvc/github/pulls.go#L210

We're not using it anywhere in our code and it doesn't arrive in the hook payload.

@mrnugget Are you happy for me to remove it?

**Comment by mrnugget** [comment]
> @mrnugget Are you happy for me to remove it?

Hmmm, I think we _should_ populate it. A customer [reported an issue just now](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1588952063354200) that's related to it. 

Is there no way to get to the data?

**Comment by ryanslade** [comment]
> > @mrnugget Are you happy for me to remove it?
> 
> Hmmm, I think we _should_ populate it. A customer [reported an issue just now](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1588952063354200) that's related to it.
> 
> Is there no way to get to the data?

We do get the commit data when doing a full sync but it's not available in the webhook payload. We could grab it from their API but I don't think it's a good idea for a query to their API to be triggered by a webhook. Especially as we want to reduce API requests to only happen from repo-updater.

So, I think the best option is to introduce a special case as you mentioned where we'll trigger a final sync after a merge event.

**Comment by ryanslade** [comment]
Ok, I've refreshed my memory on the sync code and I think we're ok.

The merge webhook will create a new merge event in our `changeset_event` table. This will be picked up as a new event when our schedule next runs (currently every two minutes) and this in turn will schedule the sync to run within 5 minutes of the merge. Is this not fast enough? 

The status will immediately show as merged in our UI but it'll take ~5 minutes for us to do a full sync again.

**Comment by mrnugget** [comment]
> The merge webhook will create a new merge event in our changeset_event table. This will be picked up as a new event when our schedule next runs (currently every two minutes) 

Even if we have received a `github:closed` event right before and the changeset is marked as closed? (See question 3 in the original ticket)

> Is this not fast enough?

For displaying the status in the UI it's fast enough (but depends on the answer to my previous question here).

But for the other customer issue, where a branch is deleted after merge, the answer to "is it fast enough?" depends on how fast the branch is deleted, I guess.

If the user merges a changeset and the branch is immediately deleted (which can be configured, I think) then I think it means that the campaign view displays an error from the time gitserver has picked up on the branch-deletion until the next sync.

(I don't think that we need to fix that issue in this PR, though, I just hoped that there might be a chance that GitHub sends the merge commit OID with the merge event and we could use that to update what we request from gitserver)

**Comment by ryanslade** [comment]
> Even if we have received a `github:closed` event right before and the changeset is marked as closed? (See question 3 in the original ticket)

We continue to sync closed changesets as usual. We only stop syncing changesets that belong to only closed campaigns.

When we receive two webhook events close together we schedule our next sync to be 5 minutes after the latest hook.

Regarding the customer issue, I don't think we should fix it in this PR so I'm going to merge this and we can look at that issue separately.

**Pull request merged**
