### PR TITLE
codeintel: Process manual uploads before auto-indexed artifacts

### LINKED ISSUE #42644: codeintel: Prioritize manual uploads over auto-indexed uploads
Help @varungandhi-src out when he needs to use dotcom to test but we've flooded the processing queue with 50k records ahead of his :(

We currently sort in the worker by upload date. We can order by a primary column that determines if there's an associated index identifier and sort those after those with a NULL value. This should tend to process all manual uploads before any auto-indexed ones.

### PR DESCRIPTION
**Pull request by efritz**
This PR adds an initial ranking to the processing order of `lsif_uploads` so that non-auto-indexed records always come first. Fixes #42644.

## Test plan

Tested locally.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]

**Comment by efritz** [comment]
@eseliger Do you think this will necessitate a new index? The previous ranking fields were not (but the upload pages are generally slow to load, maybe this is a factor).

**Comment by eseliger** [comment]
(yes this is very specific but the use-case screams for it 🤷)

maybe should try against a DB with lotta data

**Comment by efritz** [comment]
Alternatively would `ON lsif_uploads (process_after, uploaded_at, id) INCLUDE (associated_index_id) WHERE state = 'queued'` work?

My initial thoughts is this shouldn't make anything _worse_ but should fix the problem of drowning out our own manual uploads.

**Comment by eseliger** [comment]
hmm it has to find the upload in the index by `process_after, uploaded_at, id` first before it can the first pass of ordering then, my assumption is that having `associated_index_id` at the beginning would give us the small subset of manual uploads essentially for free and only then we need to match that triple.. maybe wrong though

**Comment by Strum355** [comment]
> maybe should try against a DB with lotta data

I hear dotcom has a big queue :trollface:

**Comment by efritz** [comment]
Tested sample queries on dotcom:

**Before**:
```sql
EXPLAIN ANALYZE select * from lsif_uploads u left join (SELECT
        r.id,
        ROW_NUMBER() OVER (ORDER BY
                COALESCE(r.process_after, r.uploaded_at),
                r.id
        ) as rank
FROM lsif_uploads_with_repository_name r
WHERE r.state = 'queued') s on u.id = s.id join repo on repo.id = u.repository_id limit 3;
```

```
                                                                                                 QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=69075.57..70470.88 rows=3 width=1043) (actual time=109.336..120.454 rows=3 loops=1)
   ->  Nested Loop Left Join  (cost=69075.57..308107276.19 rows=662298 width=1043) (actual time=109.335..120.452 rows=3 loops=1)
         Join Filter: (u.id = s.id)
         Rows Removed by Join Filter: 94227
         ->  Nested Loop  (cost=0.43..1340239.88 rows=662298 width=1031) (actual time=0.023..0.075 rows=3 loops=1)
               ->  Seq Scan on lsif_uploads u  (cost=0.00..461539.98 rows=662298 width=418) (actual time=0.010..0.019 rows=3 loops=1)
               ->  Index Scan using repo_pkey on repo  (cost=0.43..1.33 rows=1 width=613) (actual time=0.014..0.014 rows=1 loops=3)
                     Index Cond: (id = u.repository_id)
         ->  Materialize  (cost=69075.13..70155.65 rows=30872 width=12) (actual time=23.372..36.353 rows=31409 loops=3)
               ->  Subquery Scan on s  (cost=69075.13..70001.29 rows=30872 width=12) (actual time=70.112..95.765 rows=31409 loops=1)
                     ->  WindowAgg  (cost=69075.13..69692.57 rows=30872 width=20) (actual time=70.111..90.562 rows=31409 loops=1)
                           ->  Sort  (cost=69075.13..69152.31 rows=30872 width=12) (actual time=70.093..73.431 rows=31409 loops=1)
                                 Sort Key: (COALESCE(u_1.process_after, u_1.uploaded_at)), u_1.id
                                 Sort Method: quicksort  Memory: 2241kB
                                 ->  Gather  (cost=1000.98..66773.01 rows=30872 width=12) (actual time=0.560..60.334 rows=31409 loops=1)
                                       Workers Planned: 2
                                       Workers Launched: 2
                                       ->  Nested Loop  (cost=0.98..62685.81 rows=12863 width=12) (actual time=0.066..52.428 rows=10470 loops=3)
                                             ->  Parallel Index Scan using lsif_uploads_state on lsif_uploads u_1  (cost=0.55..41771.23 rows=14221 width=24) (actual time=0.026..10.594 rows=10470 loops=3)
                                                   Index Cond: (state = 'queued'::text)
                                             ->  Index Only Scan using repo_non_deleted_id_name_idx on repo r  (cost=0.43..1.47 rows=1 width=4) (actual time=0.004..0.004 rows=1 loops=31409)
                                                   Index Cond: (id = u_1.repository_id)
                                                   Heap Fetches: 27508
 Planning Time: 0.875 ms
 Execution Time: 120.951 ms
(25 rows)
```

**After**:
```sql
EXPLAIN ANALYZE select * from lsif_uploads u left join (SELECT
        r.id,
        ROW_NUMBER() OVER (ORDER BY
                r.associated_index_id IS NULL DESC,
                COALESCE(r.process_after, r.uploaded_at),
                r.id
        ) as rank
FROM lsif_uploads_with_repository_name r
WHERE r.state = 'queued') s on u.id = s.id join repo on repo.id = u.repository_id limit 3;
```

```
                                                                                                 QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=69075.57..70470.88 rows=3 width=1043) (actual time=125.038..136.504 rows=3 loops=1)
   ->  Nested Loop Left Join  (cost=69075.57..308107353.37 rows=662298 width=1043) (actual time=125.037..136.501 rows=3 loops=1)
         Join Filter: (u.id = s.id)
         Rows Removed by Join Filter: 94248
         ->  Nested Loop  (cost=0.43..1340239.88 rows=662298 width=1031) (actual time=0.023..0.091 rows=3 loops=1)
               ->  Seq Scan on lsif_uploads u  (cost=0.00..461539.98 rows=662298 width=418) (actual time=0.011..0.022 rows=3 loops=1)
               ->  Index Scan using repo_pkey on repo  (cost=0.43..1.33 rows=1 width=613) (actual time=0.017..0.017 rows=1 loops=3)
                     Index Cond: (id = u.repository_id)
         ->  Materialize  (cost=69075.13..70232.83 rows=30872 width=12) (actual time=28.278..41.573 rows=31416 loops=3)
               ->  Subquery Scan on s  (cost=69075.13..70078.47 rows=30872 width=12) (actual time=84.830..111.485 rows=31416 loops=1)
                     ->  WindowAgg  (cost=69075.13..69769.75 rows=30872 width=21) (actual time=84.829..106.130 rows=31416 loops=1)
                           ->  Sort  (cost=69075.13..69152.31 rows=30872 width=13) (actual time=84.799..88.069 rows=31416 loops=1)
                                 Sort Key: ((u_1.associated_index_id IS NULL)) DESC, (COALESCE(u_1.process_after, u_1.uploaded_at)), u_1.id
                                 Sort Method: quicksort  Memory: 2241kB
                                 ->  Gather  (cost=1000.98..66773.01 rows=30872 width=13) (actual time=0.492..67.444 rows=31416 loops=1)
                                       Workers Planned: 2
                                       Workers Launched: 2
                                       ->  Nested Loop  (cost=0.98..62685.81 rows=12863 width=13) (actual time=0.077..56.872 rows=10472 loops=3)
                                             ->  Parallel Index Scan using lsif_uploads_state on lsif_uploads u_1  (cost=0.55..41771.23 rows=14221 width=32) (actual time=0.034..10.042 rows=10472 loops=3)
                                                   Index Cond: (state = 'queued'::text)
                                             ->  Index Only Scan using repo_non_deleted_id_name_idx on repo r  (cost=0.43..1.47 rows=1 width=4) (actual time=0.004..0.004 rows=1 loops=31416)
                                                   Index Cond: (id = u_1.repository_id)
                                                   Heap Fetches: 27515
 Planning Time: 0.793 ms
 Execution Time: 137.034 ms
(25 rows)
```

**Pull request merged**
