### PR TITLE
code monitoring: code monitor examples in getting started page

### LINKED ISSUE #27170: Create code monitor library/samples page

### PR DESCRIPTION
**Pull request by limitedmage**
Fixes #27170

CleanShot 2021-12-02 at 13 55 43

Interaction example:

https://user-images.githubusercontent.com/206864/144509509-39c43aa6-bc16-4f02-b40d-fc72aac6e61d.mp4

### CODE REVIEW

**Comment by benvenker** [comment]
@limitedmage this is minor, but I wonder if we should say "Customize to add to your monitors" or something instead of just "Copy monitor" so it's a little more clear what they're about to do? I half expected the copy button to appear to do nothing but copy the query to the clipboard and then have the user click on the create button. Otherwise this looks awesome!

**Review by valerybugakov — APPROVED** [review]
✅

**Comment by fkling** [comment]
I also find the "Copy monitor" a bit vague. If people don't even have a good idea of what a monitor *is*, then I don't think they have a concept for copying a monitor. Maybe "Customize monitor" or just "Create monitor"? But maybe I'm overthinking this...

**Review by marisak — APPROVED** [review]
This looks great! I have a small visual nit: Does the h3 in the cards (e.g. "New library usage") have 16px margin by default? I think 8px would help bring the title and description closer together, which is helpful because they're semantically linked.

r.e. @benvenker and @fkling comments on the action label (currently "Copy monitor"): 
I agree that "Copy monitor" may be confusing. The flow is that the user clicks the link, and they're taken to the creation flow for a code monitor that's identical to the example. Since there's only one action, and the cards are pretty wide, I'm not concerned about using multiple words in the label. Some other options might be "Create copy of monitor," "Add to my monitors," "Customize to add to your monitors," "Create monitor," or "Customize monitor." (Included Ben and Felix's suggestions in the prior list.) Of that list, I think `Create copy of monitor` is the best combination of (a) clear about what will happen next, and (b) concise.

**Comment by limitedmage** [comment]
Updated based on comments. @marisak here's a screenshot with new spacing and copy: 
image

**Pull request merged**
