### PR TITLE
Scope signup to dot com

### LINKED ISSUE #45353: Scope Signup link to dot com only
Our signup link is not scoped to dot com.

See [thread](https://sourcegraph.slack.com/archives/C04CVDB322Y/p1670391520746349) for more details.

### PR DESCRIPTION
**Pull request by bretthayes**
This closes #45353 and scopes our signup link to dot com only. On prem/cloud instances will be able to navigate to `/sign-up` for creating local accounts.

## Test plan
Ensure sign up goes to signup.sourcegraph.com for dot com only

## App preview:

- [Web](https://sg-web-brett-scoped-signup.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by limitedmage** [comment]
Should we instead be looking for the `allowSignup` flag in the config?

**Review by limitedmage — APPROVED** [review]

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.11 kb) | 0.00% (+0.11 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/brett/scoped-signup/compare-report.html;tab=live_object) for a full comparison between the commits 40e7839 and 307c9cb or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by bretthayes** [comment]
> just saw that this is to show the link to `signup.sourcegraph.com`, not the `/sign-up` URL path. This is what I'd expect 👍

Sounds good, thank you for checking!

**Review by eseliger — APPROVED** [review]
thanks for the quick fix!

**Pull request merged**
