### PR TITLE
Update module to sourcegraph.com

### PR DESCRIPTION
**Pull request by keegancsmith**
Experimenting with making our import path prefix sourcegraph.com instead of github.com/sourcegraph/sourcegraph.

Should help us dogfood module support better, with shorter import paths to boot. Blocking merging this is allowing us to go get from this domain.

See commit by commit. First commit introduces a program I used to update the import paths.

### CODE REVIEW

**Comment by slimsag** [comment]
This PR has been open for a while with no progress, closing. Reopen if desired.

**Comment by keegancsmith** [comment]
Any interest in this? Will likely result in some minor disruption to our devs, but not much. Benefit: dogfood modules more, shorter import paths. WDYT? @tsenart @sqs

**Comment by tsenart** [comment]
I like it. Can you describe what sort of disruption you think it could cause?

**Comment by keegancsmith** [comment]
- Merge conflicts for in progress work.
- go tools that aren't go module ready failing. Devs would have to move the repo on there GOPATH.

Both somewhat minor. I'll add this to my backlog of fun things to try and accomplish. I'm gonna take this as a thumbs up on this approach :)

**Comment by unknwon** [comment]
>Devs would have to move the repo on there GOPATH.

As long as a symlink to/from the GOPATH works, I'm OK with it. It's even better to spot which tools that aren't go module ready.

**Comment by keegancsmith** [comment]
Ok, I will look into this just before the next branch cut. Otherwise cherrypicking changes will be a complete PITA.

**Comment by keegancsmith** [comment]
I was going to merge this, then realised we would be conflicting with our old vanity import path that some third parties may still be relying on. I want to add some logging to our `?go-get=1` support to find out more.

Another thought, should we be making the import path `sourcegraph.com`? Or maybe we can use a more succinct domain like `sgdev.org` (already own) or `sg.dev` (available to purchase)?

**Comment by tsenart** [comment]
My vote goes for `sg.dev`

**Comment by unknwon** [comment]
Hmm, it’s a public PR, we probably should purchase it quickly if we want. Or discard since the cost of a .dev domain is trivial.

**Comment by keegancsmith** [comment]
I'll be on vacation just before branch cut. If someone else wants to take a stab at this, please feel free since I won't be able to do it this milestone. (cc @sourcegraph/core-services)

**Comment by unknwon** [comment]
I think `sourcegraph.com` looks more official, shorter is cool, but less formal for this particular repository IMO.

**Comment by slimsag** [comment]
Modules are great and we should definitely dogfood our module support a lot more.

That said, history has proven to me that custom import paths are a bad idea unless we are very serious about maintaining them and in my experience we are not:

1) Many tools still rely on `go get` semantics and do not support modules. We would be needlessly breaking our ability to use Sourcegraph on such tools. For example, one I use quite frequently is https://gotools.org/github.com/sourcegraph/sourcegraph/pkg/markdown which would break if we do this.
2) Our import paths used to be `sourcegraph.com/...` but it proved to be quite a maintenance burden to support the `go get` case and we ended up dropping our support for it.

**Comment by unknwon** [comment]
Here is the [poll results](https://sourcegraph.slack.com/archives/C07KZF47K/p1572898723401500):

Screen Shot 2019-11-07 at 11 45 34 AM

**Pull request closed without merging**
