### PR TITLE
wildcard: move `react-loading-spinner` into wildcard package

### PR DESCRIPTION
**Pull request by gitstart-sourcegraph**
## Descriptions

- Move the code from https://github.com/sourcegraph/react-loading-spinner into the Wildcard component.
- Update usage of `react-loading-spinner` in our codebase to use the Wildcard component

## Refs

- [SourceGraph issue](https://github.com/sourcegraph/sourcegraph/issues/29047)
- [GitStart issue](https://app.gitstart.com/clients/sourcegraph/tickets/SG-29047)

### CODE REVIEW

**Comment by gitstart-sourcegraph** [comment]
@umpox We decided to use `inline?: boolean` prop instead of using class `inline-icon` but it seems that almost usages of this component have `inline={true}`, what do you think if we make `inline={true}` as default value

**Review by valerybugakov — COMMENTED** [review]
@gitstart-sourcegraph, it sounds good to me. We can easily refactor it back if there are any problems that @umpox finds when he comes back from vacation.

**Comment by gitstart-sourcegraph** [comment]
Hi @valerybugakov @oleggromov,
Changes has been completed, kindly take a look.

**Review by umpox — COMMENTED** [review]
Thanks @gitstart-sourcegraph, this looks good. Few further requested changes:

1. Can we remove the dependency on `@sourcegraph/react-loading-spinner` in package.json? We shouldn't need this anymore
2. Likewise, can we remove the `@sourcegraph/react-loading-spinner/lib/LoadingSpinner.css` import from client/branded/src/global-styles/index.scss. As these styles are now in the relevant CSS module :)
3. Finally, it looks like we configure the colors for this component in a separate file. Can we move [these variables](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@contractors/SG-29047/-/blob/client/shared/src/global-styles/icons.scss#L46:14-55:2) to the new CSS module file for the loading spinner?

**Comment by gitstart-sourcegraph** [comment]
@umpox Thanks. We updated PR with requested changes.

**Review by umpox — APPROVED** [review]
Thank you!

**Pull request merged**
