### PR TITLE
remove db dependency from gitserver client

### PR DESCRIPTION
**Pull request by camdencheek**
The gitserver client does not use its `db` dependency, so this removes it. Turns out, we're passing a lot of DBs around just for the gitserver client.

## Test plan

Unit tests. Just removing unused arguments. I depended on gopls a lot here.

### CODE REVIEW

**Review by Strum355 — APPROVED** [review]
😍

**Review by ggilmore — APPROVED** [review]
kill it with fire

**Review by eseliger — APPROVED** [review]

**Review by sashaostrikov — APPROVED** [review]
LGTM, thanks!

**Comment by ryanslade** [comment]
Nice! ❤️

**Pull request merged**
