### PR TITLE
remove Extensions navbar item

### LINKED ISSUE #16567: Collapse navbar items to hamburger menu on small screen sizes
#### Details

Navigation will grow by an element with the addition of code monitoring. That addition alone shortens the search box by 86 pixels  or around 10 to 11 characters.    With the display of ‘Get started’ for new users and code insights (which is feature flagged), the navigation is much too large to support the search bar. 

This Figma file explains the problem visually and presents a solution:

https://www.figma.com/file/QSEhj2Nt4MSYLTjqVa2mOO/Navigation-short-term-updates?node-id=2%3A6846&viewport=480%2C487%2C0.25

#### Impact 

High, the usability of the search bar will be significantly impaired. 

#### Urgency 

3.23

### PR DESCRIPTION
**Pull request by 5h1rU**
fix #16567

- Remove the menu option from the navigation bar
- Remove the UI component from the codebase
- Update snapshots

### CODE REVIEW

**Review by felixfbecker — APPROVED** [review]
LGTM! Any reason this PR is only a draft? Are there still any changes you want to make before getting review or merging?

**Review by tjkandala — APPROVED** [review]

**Review by AlicjaSuska — APPROVED** [review]
Looks good!

**Comment by felixfbecker** [comment]
@5h1rU Awesome! This fix needs to be cherry-picked from `main` into the 3.24 release branch (which is being released tomorrow). You can find the here: https://about.sourcegraph.com/handbook/engineering/releases#cherry-picking-a-fix-onto-release-branch
and get help from @sourcegraph/distribution if needed 🙂

**Comment by 5h1rU** [comment]
@davejrt is the release captain. He is taking care of this commit. https://github.com/sourcegraph/sourcegraph/commit/01db917471cb8c8dce0f637a9c494c96fed351fc

Anything you need, please ping me!

**Pull request merged**
