### PR TITLE
[SG-45991] Disable package hoisting

### PR DESCRIPTION
**Pull request by gitstart-sourcegraph**
## Description

- lift other dependencies from the root package.json to client workspaces packages and disable package hoisting in the `.npmrc` 

## Refs

[SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/45991)
[GitStart ticket](https://developers.gitstart.com/ticket/SG-45991)

## App preview:

- [Web](https://sg-web-contractors-sg-45991.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, thank you! The spec looks excellent. 

Let's first focus on completing the `pnpm` migration https://github.com/sourcegraph/sourcegraph/pull/46008. The key objective is to make the CI green. Then, we can test this PR properly, relying on CI checks. And after that, we think about enabling PnP in a follow-up PR.

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov  This workflow is failing https://github.com/sourcegraph/sourcegraph/actions/runs/3867861733/jobs/6592928831.
We are getting ERR_PNPM_OUTDATED_LOCKFILE with `frozen-lockfile` but it doesn't update pnpm-lock file when I tried to npm install locally or even with `--no-frozen-lockfile` included. There are some issues reporting the same issue with `auto-install-peers=true`. Could you take a look? Should we remove `auto-install-peers=true`?

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov Is it ok if we rebase this PR to vb/pnpm-test-3?

**Comment by valerybugakov** [comment]
> Is it ok if we rebase this PR to vb/pnpm-test-3?

@gitstart-sourcegraph, yes!

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 3.02% (+84.01 kb) 🔺 | 0.74% (+105.87 kb) 🔺 | 0.19% (+21.86 kb) 🔺 | 0.28% (+2) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/contractors/SG-45991/compare-report.html;tab=live_object) for a full comparison between the commits bed92e3 and 057af2f or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov We fixed errors on contractors pipeline. Could you please review and give us the errors on other pipelines?

**Comment by gitstart-sourcegraph** [comment]
Closing this based on it's interference with the Bezel migration.

**Pull request closed without merging**
