### PR TITLE
remove replacer

### PR DESCRIPTION
**Pull request by rvantonder**
This PR removes replacer/codemod and all references I could find to it. It served its purpose :-) There are a lot of places that a service touches, so this is best-effort. I tried to be thorough, but it may very well break things if I missed something. This PR does _not_ update deploy configurations for the replacer service (which should maybe be removed before merging this change).

Removes:

-  `cmd/replacer` service
- `replace:` field in queries
- codemod references/GQL requests in web code
- GQL type and resolvers for codemod/codemod results
- removes replacer from `Procfile` and start/dev/ci scripts
- removes replacer from architecture docs
- removes replacer from monitoring

Checked the following still work:

- dev startup
- go build
- go tests

Will let CI check the rest.

### CODE REVIEW

**Comment by slimsag** [comment]
I can nuke the deploy configs once you merge this - no need to do it before.

**Comment by rvantonder** [comment]
> I can nuke the deploy configs once you merge this - no need to do it before.

Oh ok good to know. Checks look good so I will just tag reviewers as an FYI and leave this PR up until ~Monday. I might do another pass by searching for replacer/codemod references on this branch to see if I missed anything.

**Comment by daxmc99** [comment]
image
Awesome!

**Comment by felixfbecker** [comment]
Just confirming - @dadlerj @sqs you're not using this in any demos anymore?

**Comment by rvantonder** [comment]
Yes, please confirm. Though I imagine any demo of replace should be fit to work with campaigns.

**Pull request merged**
