### PR TITLE
use Babel instead of ts-jest to speed up and simplify tests

### PR DESCRIPTION
**Pull request by sqs**
Removed typechecking from jest tests (by removing ts-jest and just using Babel's TypeScript transpilation, per https://jestjs.io/docs/en/getting-started#using-typescript). This makes tests run faster (~2s vs. ~9s for a single test after making a change to a `.ts` file) and simplifies their build configuration (by removing an unnecessary tool, ts-jest, from our toolchain). You should instead rely on your editor (and CI) for typechecking.

Babel is a good choice because it is the standard for transpilation, and tslint is being deprecated in favor of Babel + eslint (so we need to switch soon anyway to get the latest lint rules, such as those for React hooks).

### CODE REVIEW

**Comment by felixfbecker** [comment]
I don't currently see compile errors from test files in VS Code (without explicitly opening the file). It seems like they are not checked by the `tsc` tasks that get run. Could you ensure that?

**Comment by beyang** [comment]
@felixfbecker given that @sqs is out on pat leave, is this something that should be merged, or should we close this?

**Comment by sqs** [comment]
This can be merged when @babel/plugin-transform-typescript 7.5.0 is released, which should be soon. That version will incorporate the fix in https://github.com/babel/babel/pull/9610, which should solve the problem that causes CI to fail.

**Comment by felixfbecker** [comment]
7.5.0 was just released :)

**Comment by sqs** [comment]
@felixfbecker 	Re: vscode not showing errors from not-yet-opened files, I am indeed seeing that problem, but I am actually not seeing any of the tasks work:

```
> Executing task: yarn --prefix web run watch <

yarn run v1.16.0
error Command "run" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process terminated with exit code: 1
```

It doesn't seem to be related to this PR, so I'm not going to block this PR.

**Comment by felixfbecker** [comment]
🎉

**Pull request merged**
