### PR TITLE
dev: update to go 1.15

### PR DESCRIPTION
**Pull request by ggilmore**
cc @sourcegraph/cloud

### CODE REVIEW

**Comment by unknwon** [comment]
Not checked but looks like a problem with Go 1.15 gofmt? https://sourcegraph.slack.com/archives/C07KZF47K/p1597266059316000

**Comment by daxmc99** [comment]
I will try and test this locally today. Should we also consider bumping the images at the same time?

**Comment by ggilmore** [comment]
This change already bumps the go version that the agents use when building
the binaries for images

**Comment by tsenart** [comment]
What's up with this PR?

**Comment by daxmc99** [comment]
I believe this blocked us from upgrading https://github.com/golang/go/issues/39568

**Comment by tsenart** [comment]
@daxmc99: We'll need to update eventually. Can we ask our RDS customers to follow the steps described here during upgrade? https://github.com/golang/go/issues/39568#issuecomment-665863345

**Comment by daxmc99** [comment]
See this PR as well https://github.com/sourcegraph/sourcegraph/pull/13433

**Comment by daxmc99** [comment]
I'm going to merge this PR with https://github.com/sourcegraph/sourcegraph/pull/13433 and work on finishing off the tasks there.

**Comment by tsenart** [comment]
Ping. What's blocking progress here? @sourcegraph/distribution

**Comment by daxmc99** [comment]
Closing for https://github.com/sourcegraph/sourcegraph/pull/13433

**Pull request closed without merging**
