### PR TITLE
search: Add union merge autogold tests

### PR DESCRIPTION
**Pull request by camdencheek**
Creating this as a draft PR because the autogold tests are really slow. @slimsag, do you have any idea why these tests are taking >1s? Weirdly enough, two of the tests are logged as `0.0s`, but I don't see any clear pattern as to why. 

```
❯ go clean -testcache && go test ./cmd/frontend/graphqlbackend -run UnionMerge -v
=== RUN   TestUnionMerge
=== RUN   TestUnionMerge/#00
=== RUN   TestUnionMerge/#01
=== RUN   TestUnionMerge/#02
=== RUN   TestUnionMerge/#03
=== RUN   TestUnionMerge/#04
=== RUN   TestUnionMerge/#05
--- PASS: TestUnionMerge (7.33s)
    --- PASS: TestUnionMerge/#00 (1.64s)
    --- PASS: TestUnionMerge/#01 (1.32s)
    --- PASS: TestUnionMerge/#02 (2.88s)
    --- PASS: TestUnionMerge/#03 (0.00s)
    --- PASS: TestUnionMerge/#04 (0.00s)
    --- PASS: TestUnionMerge/#05 (1.49s)
PASS
ok      github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend  7.397s

```

### CODE REVIEW

**Comment by rvantonder** [comment]
yeah @slimsag we want to use the awesomegold but ran into slowness with these test cases. The generated values are large-ish, like:

```go
&SearchResultsResolver{SearchResults: []SearchResultResolver{
				&CommitSearchResultResolver{url: "a"},
				&CommitSearchResultResolver{
					diffPreview: &highlightedString{},
					url:         "a",
				},
				&FileMatchResolver{FileMatch: FileMatch{uri: "a"}},
				&RepositoryResolver{innerRepo: &types.Repo{Name: api.RepoName("a")}},
			}}
```

`json.Marshal` doesn't work I think because of the private fields, so couldn't use that. Alternative for us is to write our own string serializer but it's annoying for this `SearchRseultsResolver` type.

**Comment by slimsag** [comment]
Strange, I'll check it out in a few mins, can you check if `valast.String(value)` is slow too?

**Comment by slimsag** [comment]
👋 Lunch break Stephen here - I added an `AUTOGOLD_PROFILE=true` option found out that indeed, almost all of the time is being spent in [valast](https://github.com/hexops/valast) (which uses reflection to write out a Go AST.) Looking into it.

**Comment by slimsag** [comment]
Got a little bit closer: I added some more advanced profiling data you can get from `VALAST_PROFILE=true` in https://github.com/hexops/valast/pull/6 which has shown me it is finding some fairly complex data types - not 100% sure yet why it is taking so long on these data types yet, though.

Gotta finish up some of my other work, I'll take a look at this later tonight.

**Comment by camdencheek** [comment]
Awesome -- thanks @slimsag!

**Comment by slimsag** [comment]
Fixed some things and landed a 66% perf improvement on complex types like these. It cuts the runtime of your tests here in half / to 3s:

```
--- PASS: TestUnionMerge (2.96s)
    --- PASS: TestUnionMerge/#00 (1.05s)
    --- PASS: TestUnionMerge/#01 (0.77s)
    --- PASS: TestUnionMerge/#02 (0.77s)
    --- PASS: TestUnionMerge/#03 (0.00s)
    --- PASS: TestUnionMerge/#04 (0.00s)
    --- PASS: TestUnionMerge/#05 (0.37s)
```

You can upgrade with the following:

```
go get -u github.com/hexops/autogold@v1.3.0
```

I'm sure there are other improvements I can make as well - but hopefully this gets you far enough for now. Let me know if you see any other cases where its slow, etc.

**Comment by camdencheek** [comment]
🎉 That's awesome! Thanks for digging in. I'll get these tests converted 👍

**Pull request closed without merging**
