### PR TITLE
Code monitoring: add integration tests for create page

### PR DESCRIPTION
**Pull request by attfarhan**
Adds integration tests for CreateCodeMonitor page.

### CODE REVIEW

**Comment by attfarhan** [comment]
@limitedmage I'm going to merge this in as it's purely adding tests. Please take a look post-merge if you'd like!

**Comment by limitedmage** [comment]
This looks great! However, what is the rationale on having these tests as Puppeteer integration tests instead of/in addition to Jest unit tests/shallow integration tests? It seems to me like these scenarios could be better suited as Jest tests instead.

**Comment by attfarhan** [comment]
@limitedmage sorry for the late reply here. The big issue I ran into was that `useInputValidation` seems to return asynchronously, and I couldn't figure out how to wait for the validation in unit tests. @tjkandala do you have an idea on how to wait for validation in Jest tests? I'm only using synchronous validators so I expected validation to be instant but it seems there's some lag.

**Comment by tjkandala** [comment]
@attfarhan We [always debounce input](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/util/useInputValidation.ts#L147-149), even if there are no asynchronous validators, so you'd have to use fake timers in unit tests

**Pull request merged**
