### PR TITLE
rbac: add text on role assignment to roles page

### PR DESCRIPTION
**Pull request by BolajiOlajide**
This PR adds a link to the user management page so site administrators can assign roles to users.

## Test plan

Manual testing.

CleanShot 2023-03-17 at 16 50 43@2x

## App preview:

- [Web](https://sg-web-bo-add-instructions-for-assigning.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by rrhyne — APPROVED** [review]
LGTM!

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.15 kb) | 0.00% (+0.15 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/bo/add-instructions-for-assigning-roles/compare-report.html;tab=live_object) for a full comparison between the commits 54bfaea and e7228a7 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by courier-new — APPROVED** [review]

**Comment by courier-new** [comment]
I'm going to go ahead and merge this now so I can deal with the merge conflict right away. 😄

**Comment by BolajiOlajide** [comment]
> I'm going to go ahead and merge this now so I can deal with the merge conflict right away. 😄

Yeah! Sorry about the merge conflict.

**Pull request merged**
