### PR TITLE
remove more gitserver mocks

### PR DESCRIPTION
**Pull request by mollylogue**
ReadDir, LsFiles, Stat, GetDefaultBranch

## Test plan
ensure unit/integration tests pass successfully

### CODE REVIEW

**Review by sashaostrikov — APPROVED** [review]
Love it! LGTM! :shipit:

**Comment by sashaostrikov** [comment]
@mollylogue can you pls specify in scope of which effort/project/issue (if any) this changes are made? Probably this way you can get some help in doing this :)

**Comment by ryanslade** [comment]
I believe this is part of https://github.com/sourcegraph/sourcegraph/issues/38089

**Review by ryanslade — APPROVED** [review]
Nice!

**Comment by mollylogue** [comment]
> @mollylogue can you pls specify in scope of which effort/project/issue (if any) this changes are made? Probably this way you can get some help in doing this :)

Yeah, sorry 😅  It's this one right here: https://github.com/sourcegraph/sourcegraph/issues/38089 (which Ryan linked). Just trying to work through some tech debt since I haven't had the time in a while.

**Pull request merged**
