### PR TITLE
docs/update docker compose cloud deployment docs with new launch wizard

### PR DESCRIPTION
**Pull request by abeatrix**
This PR update the current Docker Compose deployments docs, including:
- AWS GCP DigitalOcean deployment docs with instructions using the latest launch wizard
  - The docs is currently using the old interface for each cloud host
- Add a new configuration page aligns with the one in our[ k8s docs](https://docs.sourcegraph.com/admin/deploy/kubernetes/helm#configuration)
- Add instructions and examples for using docker-compose.override.yaml for configuration purpose
  - Users are currently customizing their docker compose instance directly in the docker-compose.yaml file, which makes upgrades complicated
## Test plan

Manually in local instance
image
image

### CODE REVIEW

**Comment by beyang** [comment]
Review TODO (@beyang s personal notes)
- [ ] Review pages changes
- [ ] Run through AWS
- [ ] Run through DO
- [ ] Run through GCP
- [ ] Understand what configuration.md does

**Comment by abeatrix** [comment]
@beyang deployment docs for Azure is also ready for review: https://github.com/sourcegraph/sourcegraph/pull/41464

**Review by airamare01 — APPROVED** [review]
Looks good!

**Comment by beyang** [comment]
@abeatrix I made some updates to the docs:
* I eliminated the "Prerequisite" sections as they didn't seem like true prereqs (having an account with the cloud provider seemed obvious, and using the resource estimator can just be part of the normal doc flow)
* I moved the paragraph mentioning modifying the setup script if you forked the deployment repository to after the startup script contents. IMO, we don't necessarily need to call out forking this repository upfront, but rather can just recommend it when the user specifies the startup script.
* I updated and simplified some language in `configuration.md`---thanks for calling out these examples.

PTAL and lmk if you have any concerns. Otherwise, LGTM and feel free to merge.

**Pull request merged**
