### PR TITLE
Do not include archived changesets in apply preview

### LINKED ISSUE #22011: Archived changesets appear in preview
This is just a suspicion and I am not able to trace this down further before I leave, but I wanted to file a shallow ticket for now so I don't forget that I discovered this.
Essentially, in the screenshot below all the reopening changesets are archived changesets. They aren't actually reopened on apply but they clutter the preview and indicate false actions.

image

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #22011

Credit goes to @eseliger

### CODE REVIEW

**Review by eseliger — APPROVED** [review]

**Review by courier-new — APPROVED** [review]
👏👏👏

Was curious and tried looking into this myself yesterday during sprint planning, but what does "rewirer mapping" mean exactly?

**Review by LawnGnome — APPROVED** [review]
giphy

**Comment by eseliger** [comment]
> "rewirer mapping"

The rewirer is a part in the system that applies a batch change: after you apply a new batch spec, it finds the mappings between existing changesets in the batch change and _new_ changeset specs. When we have no changeset to a changeset spec, it is newly added to the BC, if we have a changeset we update, and if we have changesets that don't have a changeset spec _anymore_, we remove it from the BC (close, archive,..). There are a few things that are considered when doing the mappings, like externalID and headRef. 
In this bug, we still looked at archived changesets, so in the list of "changesets that don't have a spec", we'd get ALL archived ones always, because they can never have a matching spec. That's why they appeared in the overview and had the red "Detach" indicator bar. Hope this helps :)

**Comment by courier-new** [comment]
What a detailed response!! Yes, extremely, thank you Erik!! 🙇‍♀️

**Pull request merged**
