### PR TITLE
Allow default export for storybook stories

### LINKED ISSUE #23582: remove ESLINT rule `import/no-default-export` for Storybook
Why are default exports not usually allowed and why are we disabling it here?

_Originally posted by @limitedmage in https://github.com/sourcegraph/sourcegraph/pull/23528#discussion_r682929429_

### PR DESCRIPTION
**Pull request by courier-new**
Closes #23582. 🙂

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
🌟

**Review by 5h1rU — APPROVED** [review]
🙌🏼

**Comment by courier-new** [comment]
Is there a way to re-run the UI Review? There's [some strange error](https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-5f47f6b7a6a765c30d6765c6-1200&appId=5f0f381c0e50750022dc6bf7&number=23630&view=changes) on the `GitCommitNode` component that I'm pretty sure has nothing to do with this PR. 😅

**Comment by unclejustin** [comment]
Those comments were more important than we thought!

**Review by limitedmage — APPROVED** [review]
🎉

**Comment by limitedmage** [comment]
@courier-new  You can click on the `buildkite/sourcegraph` details and re-run the whole build there with the "Rebuild" button. That will re-run everything including Chromatic.

image

**Comment by courier-new** [comment]
Oh awesome, thanks @limitedmage!!

**Pull request merged**
