### PR TITLE
Enabling container scans with anchore

### PR DESCRIPTION
**Pull request by chayim**
This PR enables container scans of the server container, with anchore. It generates sarif responses which integrates into the GitHub ecosystem, as well as anchore-reports.

While the build has been tested locally using act, the upload-sarif and upload-artifact actions cannot be tested locally.

### CODE REVIEW

**Comment by pecigonzalo** [comment]
@chayim Do you have any examples of how this looks like?

**Review by ElizabethStirling — APPROVED** [review]
Seems reasonable. I assume later we'll be updating where the output is uploaded to so that it can be ingested by our centralized logging?

**Comment by chayim** [comment]
> @chayim Do you have any examples of how this looks like?

I don't. I have anchore itself locally with the table it spits out if you'd like it - but there's no sample available on how they provide this output to GitHub.

**Review by pecigonzalo — APPROVED** [review]
@chayim I understand, but without an output or any other information, Im only able to approve that the YAML looks good.
This only seems to scan `sourcegraph/server:insiders` which is quite different from the other images.

**Pull request merged**
