### PR TITLE
migrations: Update user-facing commands

### PR DESCRIPTION
**Pull request by efritz**
Pulled from #29831. This PR introduces a new set of commands for `sg migration` as well as the `migrator` instance:

(cc @caugustus-sourcegraph and @danieldides, although this shouldn't change any of the recent docs unless you were taking full advantage of the CLI surface)

- `up` will apply all unapplied migrations for the current schema (same as `up -target=0` or the default `up` command)
- `upto` will take an explicit target to apply (may apply multiple migrations if necessary)
- `downto` will take an explicit target to revert to (may unapply multiple migrations)
- `undo` will revert the "last applied" migration (this definition will change once we allow multiple migration parents)

Discussions about this set of commands (names, behaviors, etc) are welcome!

### CODE REVIEW

**Comment by camdencheek** [comment]
> `upto` will take an explicit target to apply (may apply multiple migrations if necessary)

I'm a little fuzzy on this. Given a commit graph like the following, will `sg migration upto` run migration `2`?

```
  /
2
```

**Comment by efritz** [comment]
@camdencheek 

Given a blank slate:

- `up` would be de-sugared into `upto 4`; 
- `upto 2` would run `[1, 2]`; 
- `upto 3` would run `[1, 3]`; 
- `upto 4` would run `[1, 2, 3, 4]`.

```
   1
  / \
 2   3
 \   /
   4
```

- If `[1, 2]` were applied, `undo` would unapply `2`.
- If `[1, 2, 3]` were applied, `downto 1` would unapply `[2, 3]`.

**Comment by camdencheek** [comment]
How does a graph like that get defined? AFAICT, we only define a single parent in the `metadata.yaml`

**Comment by camdencheek** [comment]
I guess my confusion here is, with migrations created concurrently, I expect we end up with a migration graph like this:

```
1
|\
2 3
|\
4 5
|\
6 7
|
8
```

When I create migration `8`, this seems to mean that `sg migration upto 8` will skip migrations `3`, `5`, and `7`. Theoretically, if my migration depends on those, I should probably add them as parents, but realistically when developing, those are just "old migrations" that I expect to be part of the schema, so it's difficult to find those and add them as dependencies.

**Comment by efritz** [comment]
@camdencheek Oh! When we add a new migration we make its parents the set of migrations with no children. That way if the latest migration is `5`, then the next migrations will be `6a`, `6b`, and `6c`. Once merged, the next created migration will have three parents: `[6a, 6b, 6c]`.

So in your diagram `4` should also have `3` as a parent, `6` should also have `5` a a parent, and `8` should also have `7` as a parent.

The idea is to only have a non-linear chain when there were two migrations that were being developed in an unrelated way around the same time. (We'll also later disambiguate the ordering guarantee by using the current unix nano instead of the next available integer on disk)

**Comment by camdencheek** [comment]
Aha! That was the piece I was missing. Thank you for clarifying 😄

**Review by caugustus-sourcegraph — APPROVED** [review]
The existing docs aren't impacted by this change, we only use / mention `up`. Not sure if we should try and add extra documentation for these commands; seems like they aren't broadly relevant to customers and the migrator tool itself documents the options.

**Comment by efritz** [comment]
> seems like they aren't broadly relevant to customers and the migrator tool itself documents the options.

It may become relevant if we want to document downgrade/repair processes, but if the current docs only mention `up` (without an explicit `-target` supplied) then everything seems golden! Thank you!

**Pull request merged**
