### PR TITLE
repo-updater: move Blame and ResolveRevision from vcs/git to gitserver/commands package

### PR DESCRIPTION
**Pull request by sashaostrikov**
Another refactoring PR in scope of https://github.com/sourcegraph/sourcegraph/issues/33280.

Blame and ResolveRevision commands are moved.

Blame couldn't be moved without ResolveRevision, that's why PR isn't nice in terms of size, sorry.

Closes https://github.com/sourcegraph/sourcegraph/issues/34048 and https://github.com/sourcegraph/sourcegraph/issues/35433

## Test plan
Existing tests should pass

### CODE REVIEW

**Comment by ryanslade** [comment]
With the other changes we made them methods on the gitserver client. Can we do that here too to be more consistent?

**Comment by sashaostrikov** [comment]
> With the other changes we made them methods on the gitserver client. Can we do that here too to be more consistent?

Sure, I somehow keep forgetting it, gonna fix it

**Comment by sashaostrikov** [comment]
@ryanslade PTAL

**Review by ryanslade — APPROVED** [review]
LGTM

Looks like you need to resolve some conflict and regenerate mocks.

**Review by mollylogue — APPROVED** [review]
From what I can tell the vast majority of this PR is just refactoring after moving ResolveRevision, plus adding the functions in test_utils.go for creating test git repos. Is there anything else I'm missing? Those pieces look good to me. 👍

**Comment by sashaostrikov** [comment]
> Is there anything else I'm missing?

Nope, you've got it completely right :)

**Pull request merged**
