### PR TITLE
Cody: Add VS Code wide logger for all LLM requests

### LINKED ISSUE #51346: Prompt quality: Improve the workflow to make changes to the prompt/make it easier to debug context issues
Part of https://github.com/sourcegraph/sourcegraph/issues/51344

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #51346 (for now)

This PR adds LLM request logging to the Cody VS Code extension, when the debug mode is enabled.

I often find myself adding console.log in the VS Code extension to see the exact prompts sent. However, the VS Code debug log truncates strings by default, making it a rough solution.

When sharing these in the internal channels, one idea we came up with was to leverage VS Code OutputChannels and serialize requests this way. This PR adds this for all LLM requests we currently make in VS Code.

The output is a bit hard to read unfortunlaty but since we use one line per entry, you can easily double click and copy the whole line. 

Maybe in the future we could register a custom language id and code lens to have this render as one line with a "copy" button, but for now this does the job I want it to (double click to copy the FULL request and having the ability to paste it somewhere for getting more detail out of it).

## Test plan

https://github.com/sourcegraph/sourcegraph/assets/458591/b3985f11-28b5-4882-b585-a4999cf3a269

### CODE REVIEW

**Comment by sourcegraph-buildkite** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.02 kb) | 0.00% (+0.02 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/cody-vsce-logger/compare-report.html;tab=live_object) for a full comparison between the commits 0f8f95b and 75e50cc or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by abeatrix — APPROVED** [review]
I dont know how to test it but LGTM 😆

**Review by eseliger — APPROVED** [review]
this is awesome!

**Comment by philipp-spiess** [comment]
> I dont know how to test it but LGTM 😆

Oh sorry I should have clarified!

1. Turn on the `debug` option.
2. make something that triggers a request
3. open the "output" tab and select Cody there -> see the requests being logged

**Comment by mrnugget** [comment]
Very cool!

**Pull request merged**
