### PR TITLE
migrations: change `-db` flag to be alias for `-schema` & allow container name as values

### PR DESCRIPTION
**Pull request by Strum355**
Changes the drift command's `-db` flag to be `-schema` (but allowing `-db` as an alias).
Also translates values such as `pgsql`, which coincide with the container/service names, to their schema names. 

## Test plan

Tested the flags, aliases and value aliases, all working as intended

### CODE REVIEW

**Comment by Strum355** [comment]
@efritz does this PR cover [this issue](https://github.com/sourcegraph/sourcegraph/issues/51174), or is there more to it?

**Comment by efritz** [comment]
@Strum355 I think this is a good approach for #51174, but to complete it I'd suggest:

- Ensuring anything that takes `--db` now takes `--schema/db` with the same transformation
- Any place in user-facing docs that references any of these flags or schema names will also add the container names (I'd suggest saying something like "the `pgsql` schema (referred to as `frontend` in migrator below v5.1)" for each occurrence so we don't break old flows)

**Comment by Strum355** [comment]
> Ensuring anything that takes `--db` now takes `--schema/db` with the same transformation

done this, lmk if its adequate

**Comment by DaedalusG** [comment]
> * o

For the docs part of this -- the problem of changing behavior across versions of migrator is a problem that will bloat our docs really bad if we add notes for these types of changes -- if possible its best if changes like this are backwards compatible i.e. you can still use frontend, but pgsql will also work. Still considering this problem.

**Comment by Strum355** [comment]
> you can still use frontend, but pgsql will also work

Thats what this PR does yea. You can still use `-db` flag, but its displayed as an alias to `-schema`. The help menus mention `frontend`, `codeinsights` and `codeintel`, but `pgsql`, `codeinsights-db` and `codeintel-db` are allowed too and will map respectively. Anything missing?

**Review by DaedalusG — APPROVED** [review]
Looks good to me just needs tried out

**Comment by Strum355** [comment]
```
 env - PGHOST=localhost PGPORT=6969 PGUSER=sg PGPASSWORD=sg PGDATABASE=sg ./migrator drift --schema pgsql
                                                                                            ^^^^^^^^^^^^^^
✱ Sourcegraph migrator 0.0.0+dev
ℹ️ Translating container/service name "pgsql" to schema name "frontend"
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ℹ️ Checking drift against version "v3.33.0"
ℹ️ Locating schema description
ℹ️ Reading schema definition in Local file (/schema-descriptions/v3.33.0-internal_database_schema.json)... Schema not found (open /schema-descriptions/v3.33.0-internal_database_schema.json: no such file or directory). Will attempt a fallback source.
ℹ️ Reading schema definition in GitHub (https://raw.githubusercontent.com/sourcegraph/sourcegraph/v3.33.0/internal/database/schema.json)... Schema not found (HTTP 404: https://raw.githubusercontent.com/sourcegraph/sourcegraph/v3.33.0/internal/database/schema.json). Will attempt a fallback source.
✅ Schema found in GCS (https://storage.googleapis.com/sourcegraph-assets/migrations/drift/v3.33.0-internal_database_schema.json).
✅ No drift detected
```

**Pull request merged**
