### PR TITLE
Add events from frictionless cody to allowlist

### PR DESCRIPTION
**Pull request by rrhyne**
The events need to make it into Amplitude to determine if our efforts are successful. 

## Test plan

* Ensure megration is applied in the DB
* Step through the home page to ensure events are triggered and are added to the allowlist
* Click the signup to get access button on Sorucegraph.com/search and fire an event
* Observe event in Amplitude

### CODE REVIEW

**Comment by rrhyne** [comment]
@nathan-downs can I get some help with this? I'm not sure how to test and get it deployed to Sourcegraph.com

**Comment by akalia25** [comment]
Hold off on merging until we redact sensitive data coming from https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@e0681853b0d6d9b2606a8031186fab969fb57d7d/-/blob/client/web/src/cody/stores/chat.ts?L129-132

**Review by nathan-downs — APPROVED** [review]
Changes look good to me, just add the backport label for it to be added to the next patch

**Comment by akalia25** [comment]
Once the below PR is merged is merged then we can merge this:
- https://github.com/sourcegraph/sourcegraph/pull/51668

**Comment by akalia25** [comment]
updated with `sg migration leaves` here:
- https://github.com/sourcegraph/sourcegraph/pull/51812

**Pull request merged**
