### PR TITLE
search: success tracking

### LINKED ISSUE #20502: Event tracking for search success
To measure search success we need to be able to see sessions with search errors, especially common errors such as "No results" and "Too many repositories". 

Additionally, two other events are required to capture the success of queries:
* Copy permalink (with hash) (this needs an event)
* Raw download (needs an event)

Add tracking for these events.

### PR DESCRIPTION
**Pull request by novoselrok**
Fixes #20502

### CODE REVIEW

**Review by limitedmage — COMMENTED** [review]
Is `Copy permalink (with hash)` implemented here?

**Comment by novoselrok** [comment]
> Is `Copy permalink (with hash)` implemented here?

Not yet, I'll talk to Rob to see what that actually entails.

**Review by limitedmage — APPROVED** [review]

**Comment by limitedmage** [comment]
> Not yet, I'll talk to Rob to see what that actually entails.

Sounds good, approving for this part. Maybe leave #20502 open or create a new issue to track the missing work?

**Comment by novoselrok** [comment]
> > Not yet, I'll talk to Rob to see what that actually entails.
> 
> Sounds good, approving for this part. Maybe leave #20502 open or create a new issue to track the missing work?

I added the missing Permalink click tracking in this PR, you can check again.

**Review by limitedmage — APPROVED** [review]
Looks good!

**Pull request merged**
