### PR TITLE
Page Rank notice

### LINKED ISSUE #44112: Add PageRank announcement to .com
[Figma](https://www.figma.com/file/XJKAYHao1pf1xgv2nEA4vF/UX%3A-Announcements-component-for-.com?node-id=25%3A1427#302844373)

As a non-developer, we'd like to easily make brief announcements for new content on dotcom's homepage.

**Acceptance criteria**:
- Make a component that intakes 4 props ((1) The non-linked text, (2) the linked text, (3) the link destination, (4) the end date)
- Announcement should have an expiration date to not show after, to avoid stale callouts
- First use case: Advert our improved PageRank-backed search results. Context in this [thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1667843373046269). 

Related design issue: https://github.com/sourcegraph/sourcegraph/issues/44108

### PR DESCRIPTION
**Pull request by st0nebraker**
Closes #44112 - Adds announcement for new Page Rank feature

image

## Test plan
- Ensure new announcement UI renders properly

### CODE REVIEW

**Comment by st0nebraker** [comment]
> This notice will only appear in the dev environment, is this what you want?

No. Which setting needs to change to set it on dotcom or other environments?

**Comment by eseliger** [comment]
Sourcegraph.com is configured here: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-cloud/-/blob/overlays/prod/frontend/files/global-settings.json?L77

What other environments do you need to set this for?

**Comment by st0nebraker** [comment]
Gotcha, thanks @eseliger, made that PR [here](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17473). Right now we just need it on .com. For my own knowledge, where do we change this for other repos? On sg/megarepo? https://sourcegraph.sourcegraph.com/search?q=context:global+file:global-settings.json&patternType=standard&sm=0

**Comment by eseliger** [comment]
> Gotcha, thanks @eseliger, made that PR https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17473

Sounds good, approved!

> For my own knowledge, where do we change this for other repos? On sg/megarepo? https://sourcegraph.sourcegraph.com/search?q=context:global+file:global-settings.json&patternType=standard&sm=0

Repos? Do you mean instances? 
If so, it's usually set in the global config section under site-admin at runtime

**Comment by st0nebraker** [comment]
> If so, it's usually set in the global config section under site-admin at runtime

So we can't add an announcement onto instances with this file somewhere else?

**Comment by limitedmage** [comment]
> So we can't add an announcement onto instances with this file somewhere else?

I don't think so, each instance has its own global settings configured by the site admin. Even so, I don't think we'd want this to show on customer instances, it feels like an ad :/

**Comment by st0nebraker** [comment]
> Even so, I don't think we'd want this to show on customer instances, it feels like an ad :/

Totally. I was thinking more so for future announcements and getting my bearings. I suppose we can find another solution if that comes up. Thanks for the context!

**Pull request closed without merging**
