### PR TITLE
Update quickstart.md

### PR DESCRIPTION
**Pull request by Kelvin-Lee**
`tee` might not take a `-name` field any longer:

```
kelvinlee@Kelvins-MacBook-Pro Project-Euler-Solutions % echo hello | tee -a $(find -name ./README.txt)
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
hello
```

`man tee` outputs:

```
(END)
TEE(1)                    BSD General Commands Manual                   TEE(1)

NAME
     tee -- pipe fitting

SYNOPSIS
     tee [-ai] [file ...]

DESCRIPTION
     The tee utility copies standard input to standard output, making a copy
     in zero or more files.  The output is unbuffered.

     The following options are available:

     -a      Append the output to the files rather than overwriting them.

     -i      Ignore the SIGINT signal.

     The following operands are available:

     file  A pathname of an output file.

     The tee utility takes the default action for all signals, except in the
     event of the -i option.

     The tee utility exits 0 on success, and >0 if an error occurs.

STANDARDS
     The tee function is expected to be POSIX IEEE Std 1003.2 (``POSIX.2'')
     compatible.

BSD                              June 6, 1993                              BSD
```

## Test plan
Trying out the Batch Changes doc locally. Including the `-name` flag fails. Excluding it allows me to create an expected changset.

### CODE REVIEW

**Comment by eseliger** [comment]
the `-name` parameter is passed to the `find` command here, not the `tee` command. It still supports `-name`:

```
     -name pattern
             True if the last component of the pathname being examined matches
             pattern.  Special shell pattern matching characters (“[”, “]”, “*”,
             and “?”) may be used as part of pattern.  These characters may be
             matched explicitly by escaping them with a backslash (“\”).
```

It doesn't work on macOS though. But batch changes containers always run as linux, so this shouldn't be a problem :)

**Review by eseliger — CHANGES_REQUESTED** [review]
see comment

**Comment by Kelvin-Lee** [comment]
Ah okay, thanks @eseliger . I guess I've completely misidentified the issue, though I did still run into _an_ issue. Will close this and re-raise if I still think something ought to be updated.

**Comment by Kelvin-Lee** [comment]
https://github.com/sourcegraph/sourcegraph/pull/33694 made instead.

**Pull request closed without merging**
