### PR TITLE
Search: make `type:` search filter singular

### PR DESCRIPTION
**Pull request by attfarhan**
Previously, we would not show an error if the `type:` field was entered into a query multiple times. Now, if multiple `type:` fields are in a query, we will display an error saying that you can only have one.

### CODE REVIEW

**Comment by slimsag** [comment]
FYI we officially support queries like 'type:symbol type:path error' to
find two types of results at one time today. I.e. this PR is actually
removing a 'feature'. This doesn't seem inherently bad to me, but we should
tread carefully and document this change heavily in case anyone may be
relying on it.

Also, if a user can't specify multiple types of results, do we still want
to be giving them multiple result types when they run a query like 'error'
(which today can return text, symbol, and path results)?

**Comment by felixfbecker** [comment]
Yeah, symbol search is designed to actually show both code and symbol results. That dual-on by default was only set to off-by-default because symbols didn't perform well and could slow the whole search down back in the day. Now with SQLite backend and even zoekt symbols we could enable it again.

However, with the current tabs UI it already communicates that types _are_ exclusive, because only one tab can be active at a time.

**Comment by attfarhan** [comment]
Ah wow, I was not aware we supported multiple types in a single query, especially given the type tabs we have now. 

Since we actually do support having multiple types, I don't think we should return an error then, and I'll close this PR.

cc @christinaforney: this thread is good knowledge for search, in case you were not aware of this functionality before.

**Comment by christinaforney** [comment]
Thanks for highlighting this! I wasn't aware of those details - I'll keep that in mind as we work on more search features. Appreciate the @ mention :)

**Comment by slimsag** [comment]
Farhan could you find a place to document this (search syntax docs maybe)
so the next person knows as well?

**Pull request closed without merging**
