### PR TITLE
build: Don't import dbmocks into executables

### PR DESCRIPTION
**Pull request by eseliger**
This removes

```
   54 MB github.com/sourcegraph/sourcegraph/internal/database/dbmocks
```

from the frontend binary. Since we need to do integrity testing of every binary on our Macs, this will hopefully speed up the restarting and recompiling process of frontend.

Test plan:

Tests still pass, compiler is happy.

### CODE REVIEW

**Comment by eseliger** [comment]
* **#61894** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/61894?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @eseliger and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by camdencheek — APPROVED** [review]
Nice! So this was just moving test code into test packages?

**Comment by eseliger** [comment]
Correct! So that it's not part of the build target anymore. Found this with the `goweight` tool. https://github.com/jondot/goweight

**Comment by camdencheek** [comment]
>  922 MB github.com/sourcegraph/sourcegraph/client/web/dist

**Comment by eseliger** [comment]
yea, we're hoarding artifacts locally :/ that actually makes linking and vetting the binary on start terrible slow :( https://sourcegraph.slack.com/archives/C04MYFW01NV/p1707734012803989

**Comment by eseliger** [comment]
### Merge activity

* **Apr 15, 4:07 PM EDT**: @eseliger merged this pull request with [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/61894).

**Pull request merged**
