### PR TITLE
CI: check yarn.lock for changes

### PR DESCRIPTION
**Pull request by chrismwendt**
This should prevent a dirty yarn.lock from getting checked in, resulting in PRs to update it such as https://github.com/sourcegraph/sourcegraph/pull/5330

### CODE REVIEW

**Comment by felixfbecker** [comment]
`yarn --frozen-lockfile` is supposed to do this:

>     --frozen-lockfile                   don't generate a lockfile and fail if an update is needed

I thought we were using it everywhere. Are we not, or is it not working?

**Comment by chrismwendt** [comment]
This also prevents merging a change that will cause yarn.lock to change when a dev runs `yarn` (without `--frozen-lockfile`). Does that sound good?

**Comment by felixfbecker** [comment]
Doesn't `yarn --frozen-lockfile` do exactly that?

It is used for the web app, but not for lsif-server: https://github.com/sourcegraph/sourcegraph/blob/f46c6f742fc0cc591f2fbef8c6cc92453da24914/cmd/server/build.sh#L55

**Comment by chrismwendt** [comment]
Oh yup, that should do the trick. Pushed.

**Pull request merged**
