### PR TITLE
experimental search input: Add support for history mode

### PR DESCRIPTION
**Pull request by fkling**
This PR adds support "history mode" to the experimental search input. Two major changes make this happen:

- Suggestions can be switched into a specific "mode". Modes are indicated by prefixing the input with the mode name (in this case 'History:'). Modes can be activated buy calling the `setMode` function.
- Suggestions can now come from multiple sources (i.e. sources can be defined independently, which means all the history-related logic is independent from other suggestion sources) and sources can be associated with a mode. If a mode is active only sources associated with a mode are used for suggestions.

See the demo video: 

https://user-images.githubusercontent.com/179026/215798119-40076a30-80a7-4de8-a67c-859790ffaa09.mp4

You'll also notice a `keybinding` property. I tested keybindings successfully but eventually decided to not add one for history mode right now because *which* binding to use requires some more thought.

Other supporting changes:

- improve multline rendering of suggestions with long labels or descriptions
- make our custom placeholder extension configurable via a facet so that the placeholder text can be changed more easily by other extensions. This is used to show a different text when the history mode is active.
- added a custom query syntax highlighting component that supports "matches" rendering

## Test plan

Manual testing.

## App preview:

- [Web](https://sg-web-fkling-experimental-history-mode.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.00% (-0.01 kb) | 0.06% (+8.68 kb) | 0.07% (+8.69 kb) | 0.14% (+1) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/fkling/experimental/history-mode/compare-report.html;tab=live_object) for a full comparison between the commits fdc83ef and 49f6f2b or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by fkling** [comment]
I refactored some of the code and added a border to the history button to visually separate it more from the rest of the input:

**Review by limitedmage — APPROVED** [review]
This is great! 

I have some feedback on keyboard usage but it's more general on the experimental input:

- The tab ordering is a little weird, the input is focused first and then any buttons/actions
- Pressing tab when a suggestion is highlighted moves the tab order instead of completing the suggestion
- Pressing enter when the history button is focused seems to submit the search instead of clicking the button (space key does click the button)

**Comment by fkling** [comment]
Thank you for the great feedback @limitedmage!

> The tab ordering is a little weird, the input is focused first and then any buttons/actions

Yeah, I noticed that too. That's because the button is rendered inside the input actually (as decoration). I'll keep it like this for now because it makes the integration a bit simpler but we might have to move it out of CodeMirror.

> Pressing tab when a suggestion is highlighted moves the tab order instead of completing the suggestion

That's (currently) intended. I don't know whether or not it's a *good* decision, but you can make the argument that it frees up the Tab key to do what it's supposed to do on a web page. However if it's expected or allowed from a a11y perspective then we can consider adding it back. Personally I prefer if there is only one way of doing something...

> Pressing enter when the history button is focused seems to submit the search instead of clicking the button (space key does click the button)

Thanks for catching that! I'll look into event handling again.

**Review by rrhyne — COMMENTED** [review]
Reviewed live. Comments and corrections are in Figma!

https://www.figma.com/file/aenTj3SG2zl1g90HcMDUm2/RFC-760-WIP%3A-Rebooting-the-search-input-UI?node-id=2112%3A24038

**Pull request merged**
