### PR TITLE
Add a panel for Org-related metrics to frontend, add OrgMemberships panels

### PR DESCRIPTION
**Pull request by rafax**
This PR adds a Grafana dashboard for Organisation related metrics and displays rate/p99 latency/error ratio for OrganisationMembers GraphQL call.
Screenshot 2022-01-14 at 16 06 35

### CODE REVIEW

**Review by kopancek — APPROVED** [review]
Is there a way to add unit to the charts y axis? Otherwise it is impossible to understand what the chart is really showing and requires looking into the source code to see the query behind it. E.g the rate is 5-min based and it's nowhere in the chart. Same for the latency - is it in seconds or miliseconds or microseconds? No way to know until you look.

**Comment by unknwon** [comment]
> Is there a way to add unit to the charts y axis? Otherwise it is impossible to understand what the chart is really showing and requires looking into the source code to see the query behind it. E.g the rate is 5-min based and it's nowhere in the chart. Same for the latency - is it in seconds or miliseconds or microseconds? No way to know until you look.

Maybe it's a version difference on Grafana? Looking at [similar definitions of code-intel](https://github.com/sourcegraph/sourcegraph/blob/904e5fd448c1ff562665e2ed4aeb0ae39832e5f4/monitoring/definitions/frontend.go#L140-L181) that use same `Unit`, `s` and `%` are shown on dotcom:

CleanShot 2022-01-17 at 11 47 01@2x

**Review by unknwon — APPROVED** [review]

**Comment by unknwon** [comment]
OK... just saw https://github.com/sourcegraph/sourcegraph/pull/29748/commits/904e5fd448c1ff562665e2ed4aeb0ae39832e5f4, it's just an outdated screenshot 😁

**Comment by rafax** [comment]
> Is there a way to add unit to the charts y axis? Otherwise it is impossible to understand what the chart is really showing and requires looking into the source code to see the query behind it. E.g the rate is 5-min based and it's nowhere in the chart. Same for the latency - is it in seconds or miliseconds or microseconds? No way to know until you look.

I added units in 904e5fd :)

**Pull request merged**
