### PR TITLE
remove batches notify

### PR DESCRIPTION
**Pull request by BolajiOlajide**
## Test plan

N/A

### CODE REVIEW

**Comment by chrispine** [comment]
I actually wanted to give @peterguy a chance to see if he wanted to take this over instead of just delete it. It's useful for a team that's responsible for Batch Changes!

**Comment by peterguy** [comment]
Thanks for flagging me, @chrispine; I would like to keep it! The message flags individual teammates in addition to `@sourcegraph/batchers`;  maybe we can remove those individuals and leave the team?

**Comment by chrispine** [comment]
Yeah, I have no idea if the team @mention even works (because why were we using both?) I didn't set this up 😛

**Comment by peterguy** [comment]
Instead of deleting the notification, let's redirect it to @sourcegraph/code-search. I made [another PR](https://github.com/sourcegraph/sourcegraph/pull/54560) for that.

**Comment by BolajiOlajide** [comment]
> Instead of deleting the notification, let's redirect it to @sourcegraph/code-search. I made [another PR](https://github.com/sourcegraph/sourcegraph/pull/54560) for that.

Thank you!

**Pull request closed without merging**
