### PR TITLE
db: Handle repo upserts which rename

### LINKED ISSUE #2690: Postgres unique constraint violation repo_external_service_unique_idx
- Visit https://sourcegraph.com/github.com/lukakerr/Pine
- Notice the error:

image

Trace: https://app.lightstep.com/sourcegraph-prod/trace?span_guid=608ddd6925155445&at_micros=1552366323485676

```
pq: duplicate key value violates unique constraint "repo_external_service_unique_idx"
```

### PR DESCRIPTION
**Pull request by keegancsmith**
If we have the same external service but different name it indicates a rename
has occurred. So we update the upsert to do an update if we match on name or
external repo. We also simplify the insert to only happen if the update did
not.

Part of #2025 
Fixes #2690

### CODE REVIEW

**Comment by keegancsmith** [comment]
@tsenart amusingly I think this will handle renames in the vast majority of cases, even without our new syncer running. Of course it doesn't handle deletes.

There is one corner case I am concerned about and will add a test for in a follow-up PR. It is when we have the repo table:

|name|external|
|------|------|
|a|x|
|b|y|

But then try to upsert `name=a, external=y`. It will run an update on both rows, leading to us violating the constraint. I am unsure as of yet how to solve that. I think in our syncer code we essentially handle this in the application layer rather than the SQL?

**Comment by keegancsmith** [comment]
@tsenart yeah the test case fails. I am thinking we need an approach which is like the migration you wrote were we pick a winner, but not sure on the details since we can't just hard delete. For now though this PR is a clear improvement and the corner case I am thinking of will very unlikely happen in practice.

```diff
diff --git a/cmd/frontend/db/repos_test.go b/cmd/frontend/db/repos_test.go
index 41ada2dfe1..9022ab5b91 100644
--- a/cmd/frontend/db/repos_test.go
+++ b/cmd/frontend/db/repos_test.go
@@ -207,4 +207,36 @@ func TestRepos_Upsert(t *testing.T) {
 	if !reflect.DeepEqual(rp.ExternalRepo, ext) {
 		t.Fatalf("rp.ExternalRepo: %s != %s", rp.ExternalRepo, ext)
 	}
+
+	// Rename corner case. Have in table (name=myrepo/renamed, externalrepo=a)
+	// and (name=myrepo/conflict, externalrepo=b). Then handle the case of
+	// Upsert(name=myrepo/conflict, externalrepo=a).
+	extb := &api.ExternalRepoSpec{
+		ID:          "ext:idb",
+		ServiceType: "test",
+		ServiceID:   "ext:test",
+	}
+	if err := Repos.Upsert(ctx, api.InsertRepoOp{Name: "myrepo/conflict", ExternalRepo: extb}); err != nil {
+		t.Fatal(err)
+	}
+
+	if err := Repos.Upsert(ctx, api.InsertRepoOp{Name: "myrepo/conflict", ExternalRepo: ext}); err != nil {
+		t.Fatal(err)
+	}
+
+	if _, err := Repos.GetByName(ctx, "myrepo/renamed"); !errcode.IsNotFound(err) {
+		if err == nil {
+			t.Fatal("myrepo/renamed should be renamed to resolve conflict with myrepo/conflict, but still present as myrepo/renamed")
+		} else {
+			t.Fatal(err)
+		}
+	}
+
+	rp, err = Repos.GetByName(ctx, "myrepo/conflict")
+	if err != nil {
+		t.Fatal(err)
+	}
+	if !reflect.DeepEqual(rp.ExternalRepo, ext) {
+		t.Fatalf("rp.ExternalRepo: %s != %s", rp.ExternalRepo, ext)
+	}
 }
```

**Comment by tsenart** [comment]
@keegancsmith: An external_id, once set, does not change. That's why can rely on it to handle renames. Only names can change value arbitrarily. Does this change the scenario above?

**Comment by keegancsmith** [comment]
> @keegancsmith: An external_id, once set, does not change. That's why can rely on it to handle renames. Only names can change value arbitrarily. Does this change the scenario above?

No. The problem is we can get into scenarios (although very rare) where between syncs the upstream repositories swap names. I believe our syncer should handle it. However, the context for this PR is we only have the details of one repository. So we don't know the new name of the conflicting repository. As such we can't avoid the conflict on name.

However, given this is a pretty rare case (no idea if it has actually ever happened in practice) this PR is a solving a very common problem. What do you think about merging this but we follow up with either:

1. A solution.
2. Wait for 3.3 were we use syncer only which detects this.

I may need to solve this for the Sourcegraph.com lazy case anyways, but I'd like to defer that to another PR.

**Pull request merged**
