### PR TITLE
fix go generate error

### PR DESCRIPTION
**Pull request by limitedmage**
Build is failing on main branch. Not sure why this is failing but I ran `go-generate.sh` to fix it.

### CODE REVIEW

**Review by daxmc99 — APPROVED** [review]
Fixed by running `./dev/check/go-generate.sh` and committing the result. Also ran `go mod tidy`

**Comment by limitedmage** [comment]
> Fixed by running `./dev/check/go-generate.sh` and committing the result. Also ran `go mod tidy`

Thank you!

**Comment by daxmc99** [comment]
All CI checks are passing besides LSIF uploads, planning to merge

**Comment by courier-new** [comment]
Thanks for this. 🙏

**Pull request merged**
