### PR TITLE
JetBrains: Add monochrome logo and use it in menus

### PR DESCRIPTION
**Pull request by vdavid**
Fixes https://github.com/sourcegraph/sourcegraph/issues/37692

I think this is an optimal solution based on the discussion under the issue.
I used the colors that JetBrains uses for their icons (both light and dark). 
It looks great on both dark and light themes.
One caveat: for whatever reason, when I hover a menu item with our icon when a light theme is enabled, the IDE doesn't switch the logo to the brighter version. It's weird because I do the same that they do, the file naming is right, and the IDE can clearly find both the light and dark versions, so not sure why it doesn't use it when hovered.
I think it's still much better than it was, though!

## Test plan

- [Loom](https://www.loom.com/share/d6178c0d6c7c4922b569be645b15ea72)

## App preview:

- [Web](https://sg-web-dv-jetbrains-make-icons-consistent.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ablwybtsch.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by philipp-spiess — APPROVED** [review]
Looks good from eng side, feel free to merge if @jjinnii can't get to it :)

**Review by jjinnii — COMMENTED** [review]
@vdavid @philipp-spiess I'm not sure I agree with changing the icon colors to be monochrome. In both light/dracula themes I see that native InteliJ as well as plugins utilize colors (they're not strictly monochrome). For consistency, we should be only be using one version of the logo throughout the experience in the plugin. We do use the monochrome logo to pair with a disabled state, which is OK. And I think that's even more reason to only use the monochrome logo in that specific instance.

[This issue](https://github.com/sourcegraph/sourcegraph/issues/37692) is inconsistency in the icon showing up next to line items in the menu, not about inconsistency in the styling of icons.

**Comment by vdavid** [comment]
@jjinnii shall we go with Option B then on #37692?

**Comment by jjinnii** [comment]
@vdavid I'm not sure how we'd define the 1-2 we use the colored logo for. For consistency, I would say C, which is use the colored logo on all our menu items like we have currently, except for when menua actions are disabled, at which point we currently use the monochrome logo. We need to fix the inconsistency of there being _no icon_ for the "open selection in Sourcegraph Web" action. 

As this is a sub-menu under under Sourcegraph, I don't think this comes across as "shady". I do agree with your point that the colors in our logos do stand out from the IntelliJ UI, but if we wanted to address that we should change all our icons to be monochrome and think of a different way to communicate a disabled state for actions. I don't think this is critical to address prior to release.

**Comment by vdavid** [comment]
For me it's too much, but I guess they'll get used to it:

CleanShot 2022-07-15 at 08 18 50@2x

Merging this. Thanks for your input @jjinnii! ❤️

**Comment by jjinnii** [comment]
I don't disagree, but we can always address this after release based on feedback!

**Pull request merged**
