### PR TITLE
notebooks: Group notebook routes

### PR DESCRIPTION
**Pull request by fkling**
This PR consolidates notebook routes into a single component.

I hope that doesn't interfere with the React router migration efforts. It makes it easier to integrate notebooks with the SvelteKit app and is also more in line with how other product areas are structured (e.g. insights, code monitors, ...).

This also removes the use of `showSearchNotebooks`, which has been removed in https://github.com/sourcegraph/sourcegraph/pull/46086.

(note: Adding people as reviewers who have better knowledge about react router than me)

## Test plan

- When signed out I can see a list of public notebooks and open public notebooks
  - Going to `/notebooks/new` redirects to the notebooks list page
- When signed in I see my own notebooks, can open my own notebooks and can create new notebooks.

## App preview:

- [Web](https://sg-web-fkling-notebook-routes.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.03% (-0.80 kb) | 0.00% (+0.20 kb) | 0.01% (+1.00 kb) | 0.13% (+1) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/fkling/notebook-routes/compare-report.html;tab=live_object) for a full comparison between the commits cafa28c and 8e24306 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by philipp-spiess — APPROVED** [review]
I think this makes sense for now in the very short term but with React router 6 we'd actually like to move more and more routes into a shared router map that is global so we can actually properly do data preloading (e.g. can't preload notebook data early if we don't know which specific page it even needs).

Any way that you could use the routes.tsx file instead somehow in Sveltekit?

**Comment by fkling** [comment]
> Any way that you could use the routes.tsx file instead somehow in Sveltekit?

I guess I can just replicate whatever Layout is doing. Load the routes definition, pull out the ones I need and create routes for them.

**Comment by fkling** [comment]
I can also discard this PR and create my own Notebook specific routing logic for the SvelteKit app. The Notebooks subtree is just easier to test than insights or batch changes and it seemed to be a reasonable change.
But if that makes things more complicated for you we don't have to do it!

**Comment by valerybugakov** [comment]
> with React router 6 we'd actually like to move more and more routes into a shared router map that is global so we can actually properly do data preloading

Thanks for communicating this, @philipp-spiess! It's not planned for the short-term future because we're focused on top-level routes and the application shell at the moment, but eventually, we want to lift most of the routes to the top level. This means there won't be a standalone router for the notebooks section.

**Review by valerybugakov — COMMENTED** [review]
Commenting to remove from the review queue.

**Pull request merged**
