### PR TITLE
Add .nvmrc for CI

### PR DESCRIPTION
**Pull request by felixfbecker**
This lets us easily upgrade Node without affecting builds of older release branches.

### CODE REVIEW

**Comment by felixfbecker** [comment]
This needs an `nvm install 12` in our Buildkite Dockerfile

**Comment by slimsag** [comment]
This PR has been open for a while with no progress, closing. Reopen if desired.

**Comment by felixfbecker** [comment]
@ggilmore assigning you given https://sourcegraph.slack.com/archives/CJX299FGE/p1569367210068900 :)

**Comment by felixfbecker** [comment]
@ggilmore was this done as 3.9?

**Comment by felixfbecker** [comment]
We have an nvmrc now.

**Pull request closed without merging**
