### PR TITLE
monitoring: move aggregator config to separate option

### PR DESCRIPTION
**Pull request by bobheadxi**
Another just-for-fun cleanup as I re-read some of this code for a thing I'm writing - the alert aggregator configuration is unused in the vast majority of cases. This change moves aggregator configuration to a separate function, and provides typed options that can be used. Makes for a much cleaner API.

New usage:

```diff
- monitoring.Alert().GreaterOrEqual(1, monitoring.StringPtr("sum"))
+ monitoring.Alert().GreaterOrEqual(1).AggregateBy(monitoring.AggregatorSum)
```

Without custom aggregator (the default case):

```diff
- monitoring.Alert().GreaterOrEqual(1, nil)
+ monitoring.Alert().GreaterOrEqual(1)
```

## Test plan

```
go generate ./monitoring/...
```

### CODE REVIEW

**Comment by bobheadxi** [comment]
Current dependencies on/for this PR:
* main
  * **PR #31518** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/31518" target="_blank">Graphite</a> 
    * **PR #31529** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/31529" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by michaellzc — APPROVED** [review]
The new `AggregateBy` API looks great! Also love the typed `Aggregator`, no more typo ;)

**Review by jhchabran — APPROVED** [review]
I love those little API changes 👨‍🍳👌

**Review by davejrt — APPROVED** [review]

**Comment by davejrt** [comment]
Happy to say I actually follow what's been done here after hacking on the autoscaler and "coffee and structs with @jhchabran "

**Pull request merged**
