### PR TITLE
Upgrade aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by eseliger**
This PR:
- Migrates to the AWS v2 API in the codeintel s3 adapter
- Upgrades the v2 package to the newest version

### CODE REVIEW

**Review by unknwon — APPROVED** [review]
Appreciated the effort ❤️ Nothing caught my eyes.

**Review by efritz — CHANGES_REQUESTED** [review]
Local dev isn't starting for me

**Comment by efritz** [comment]
This may be a MinIO issue (filed [here](https://github.com/minio/minio/issues/11804) if so), or it could be an issue with the new Go SDK version that just happens to make invalid requests in a way that S3 leniently accepts.

If MinIO claims it to be an issue with S3 we can follow up in another way.

**Review by mrnugget — COMMENTED** [review]
I have absolutely no clue about how we use AWS, so I'm defering to the others to give a thumbs up/down. But license check is failing.

**Review by efritz — APPROVED** [review]

**Comment by efritz** [comment]
Fixes https://github.com/sourcegraph/sourcegraph/issues/19729.

**Pull request merged**
