### PR TITLE
move legacy codeintel to enterprise

### PR DESCRIPTION
**Pull request by sqs**
The search-based code intelligence is an enterprise-only feature. This change clarifies it by showing a nicer message instead of an error if it's attempted to be used in the OSS build. It also cleans up how the enabled-or-not flag is determined in code.

Also cleans up other things related to code nav when running in OSS.

## Test plan

Confirm the "unavailable" message shows up in OSS:

cina

Confirm the references panel still works in non-OSS:

cienabled

## App preview:

- [Web](https://sg-web-sqs-codeintel-enterprise.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 1.07% (+31.13 kb) 🔺 | 0.00% (+0.22 kb) | -0.26% (-30.91 kb) 🔽 | -0.41% (-3) 🔽 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/sqs/codeintel-enterprise/compare-report.html;tab=live_object) for a full comparison between the commits 506523c and 524e11d or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by olafurpg — APPROVED** [review]
LGTM to unblock merge 👍🏻

Is it expected that the popover still shows an error here?

CleanShot 2022-10-28 at 16 33 31@2x

**Comment by olafurpg** [comment]
Ideally, we disable the injection of the legacy extension API around this file here https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/extensions/createNoopLoadedController.ts?L23

**Comment by sqs** [comment]
@olafurpg Yes, I did not go so far to fix that. It basically swaps out one error for another error.

**Comment by olafurpg** [comment]
What is the best way to detect that we're running OSS? As long as we have a boolean setting we can disable the injection

**Comment by sqs** [comment]
@olafurpg there's a `codeIntelligenceEnabled` boolean that's passed down

**Pull request merged**
