### PR TITLE
Fix VS Code build errors

### PR DESCRIPTION
**Pull request by philipp-spiess**
This fixes some strange build errors that I was encountering while working with the VS Code extension. No idea what's going on there with `client/shared/src/api/extension/api/decorations.ts` especially since both implementations of `TextDocumentDecorationType` now only define a `key` as needed 🤷 

## Test plan

`yarn build-vsce` works again

## App preview:

- [Web](https://sg-web-ps-fix-vscode-compile-error.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-wwpfqtttuu.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by abeatrix — APPROVED** [review]
approve to unblock :D

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/fix-vscode-compile-error/compare-report.html;tab=live_object) for a full comparison between the commits e98887a and 0089e93 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by abeatrix — CHANGES_REQUESTED** [review]
Just built from this branch and noticed the results are not rendering correctly:
image

**Comment by philipp-spiess** [comment]
This is the issue in main that was I was talking to you about and that I was doing the git bisect for. @tbliu98 is working on resolving this, it's not caused by my changes here.

**Review by abeatrix — APPROVED** [review]
Confirmed the build command is working 👍 thanks p!

**Pull request merged**
