### PR TITLE
Add o3de search page

### PR DESCRIPTION
**Pull request by unicodeveloper**
Adds a landing page for the Open 3D Engine (O3DE) community similar to what we have for Kubernetes, Android, Temporal and StackStorm

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@novoselrok any idea on what I am doing wrong here that is making this test not pass?

**Comment by limitedmage** [comment]
You need to run prettier to format `client/web/src/repogroups/o3de.tsx` according to our guidelines. You can do this by running `yarn prettier` or by using the Prettier VSCode extension.

**Comment by unicodeveloper** [comment]
@limitedmage Thanks. Let me try that

**Comment by novoselrok** [comment]
You'll also have to run `yarn test -u`, to update all the snapshots.

**Comment by malomarrec** [comment]
Unassigning myself from review as I'll be on PTO.

**Review by novoselrok — APPROVED** [review]
Fixed the remaining issues, feel free to merge whenever @unicodeveloper.

**Comment by unicodeveloper** [comment]
Thank you so much! @novoselrok 🙏🏿 

Quick question: How or what did you do to fix them? @novoselrok Would love to know for next time when I want to add other popular OSS pages.

**Comment by novoselrok** [comment]
I ran `yarn test -u` to fix the snapshots and removed a line from .gitignore.

**Comment by unicodeveloper** [comment]
Very interesting. I ran the same command, but when I pushed, it still failed. 🤔

**Comment by novoselrok** [comment]
> Very interesting. I ran the same command, but when I pushed, it still failed. 🤔

Very weird, not sure what could be the issue.

**Pull request merged**
