### PR TITLE
Add metrics for repo permissions sync

### PR DESCRIPTION
**Pull request by sashaostrikov**
Metric shows total number of repos for which permissions sync has been scheduled

Part of https://github.com/sourcegraph/sourcegraph/issues/27790

### CODE REVIEW

**Review by unknwon — APPROVED** [review]
Changes LGTM, but we also need to [add a Grafana panel to show the graph of this metric](https://github.com/sourcegraph/sourcegraph/blob/2ada4911722e2c812cc4f1bbfb6d5d1756891392/monitoring/definitions/repo_updater.go#L219), so technically it is not yet closing #27790.

**Comment by sashaostrikov** [comment]
> Changes LGTM, but we also need to [add a Grafana panel to show the graph of this metric](https://github.com/sourcegraph/sourcegraph/blob/2ada4911722e2c812cc4f1bbfb6d5d1756891392/monitoring/definitions/repo_updater.go#L219), so technically it is not yet closing #27790.

thanks for noticing! will add this metric to Grafana dashboard

**Review by ryanslade — APPROVED** [review]
LGTM

Feel free to add the dashboard in another PR

**Comment by ryanslade** [comment]
And congrats on your first PR! 🎉

**Review by indradhanush — APPROVED** [review]
LGTM. Also, this PR should help fix the failing CLA check: https://github.com/sourcegraph/clabot-config/pull/32

Feel free to approve. 

Also!!! Congrats on your first PR!!!

**Comment by sashaostrikov** [comment]
> LGTM. Also, this PR should help fix the failing CLA check: [sourcegraph/clabot-config#32](https://github.com/sourcegraph/clabot-config/pull/32)
> 
> Feel free to approve.
> 
> Also!!! Congrats on your first PR!!!
> 
> 

btw, do you how I can restart this single check? or should I push and wait for the whole pipeline to run again?

**Comment by indradhanush** [comment]
> btw, do you know how I can restart this single check? or should I push and wait for the whole pipeline to run again?

@sashaostrikov, Unfortunately I don't. I think pushing an empty commit should help fix it although not optimal at all.

**Pull request merged**
