### PR TITLE
docs: fix port number in ssl_https_self_signed_cert_nginx.md

### PR DESCRIPTION
**Pull request by zahassanyum**
Fix port

### CODE REVIEW

**Comment by unknwon** [comment]
Hi!

Would you please sign our CLA as instructed in https://github.com/sourcegraph/sourcegraph/pull/10516#issuecomment-626016242?

> You should receive feedback on your pull request within a few days. If you haven't already, please read through [ the contributing guide](https://github.com/sourcegraph/sourcegraph/blob/master/CONTRIBUTING.md?rgh-link-date=2020-05-08T20%3A54%3A26Z), and ensure that you've [signed the CLA](https://forms.gle/FuroWPvTT8JfHiEE9).
> 
> Did you run into any issues when creating this PR? Please describe them in [an issue](https://github.com/sourcegraph/sourcegraph/issues/new/choose) so we can make the experience better for the next contributor.

**Comment by uwedeportivo** [comment]
thanks very much for contributing 👍

**Comment by zahassanyum** [comment]
@unknwon Done.

**Comment by unknwon** [comment]
@zahassanyum Thank you! I've kicked off the CI build.

**Pull request merged**
