### PR TITLE
dev/sg: add 'sg adr [list|view|search|create]'

### PR DESCRIPTION
**Pull request by bobheadxi**
## Test plan

```sh
go run ./dev/sg adr list
go run ./dev/sg adr search go scripting
go run ./dev/sg adr view 1
go run ./dev/sg adr create hello world
go generate ./dev/adr-docs # no diff as expected
```

image

### CODE REVIEW

**Comment by bobheadxi** [comment]
Current dependencies on/for this PR:
* main
  * **PR #37715** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/37715" target="_blank">Graphite</a> 
    * **PR #37718** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/37718" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/37718?utm_source=stack-comment).

**Review by burmudar — APPROVED** [review]

**Comment by burmudar** [comment]
That was quick! Awesome addition

**Review by vrto — APPROVED** [review]
Awesome, thanks for adding this!

One small suggestion - can `sg adr open` accept a flag such as `--browser` to view an ADR directly in the browser (assuming docs is running)?

**Comment by bobheadxi** [comment]
> One small suggestion - can sg adr open accept a flag such as --browser to view an ADR directly in the browser (assuming docs is running)?

I'll look at this as a follow-up!

**Comment by jhchabran** [comment]
I love this so much.

**Comment by sanderginn** [comment]
Nice 🙂 

Is it a conscious choice not to include names of individuals or teams in the docs? Looking at the currently published ADRs, it's a bunch of effort to relate it back to who published it.

Has there been any initiative so far to introduce ADRs with our customer base? This addition would be a great jumping pad to get people contributing 🌟

**Comment by vrto** [comment]
@sanderginn ADRs are part of the codebase, so I'd treat them same as source code files - git blame to see author(s)

**Comment by sanderginn** [comment]
That's more or less what my approach would be, but I can imagine people who are less directly involved in code (e.g. EMs) could benefit from an explicit mention. Not a big deal tho 🙂

**Pull request merged**
