### PR TITLE
search: if not specified, set archived:no by default

### PR DESCRIPTION
**Pull request by rvantonder**
As in title. It is weird to me that the options in `ReposListOptions` imply negation of the property (`NoForks`, `NoArchived`), and I suppose this was because it was easy to fall back to `false` default values in tests and stuff. Consequently, now that `NoArchived` should be set to `true` by default, all the tests where it matters must add it explicitly.

There are ways to improve this, but I would rather not invest time refactoring here because I look forward to not doing it this way and using a `select` instead https://github.com/sourcegraph/sourcegraph/issues/7003.

Tests updated. Looks like we don't have e2e test for this :/. So I'll add one before merging but putting up fo review now.

### CODE REVIEW

**Comment by rvantonder** [comment]
Yes, that's the intended behavior. I'll add an e2e test to test the combinations.

**Comment by keegancsmith** [comment]
Changelog entry pls. After your several changes around this, might even justify an in-app alert to educate users.

**Comment by rvantonder** [comment]
> might even justify an in-app alert to educate users.

This logic would be part of the alert code I've been refactoring.  From #8739:

> Additionally we should consider a hint / suggestion when there are no repos matched to educate about including forked:yes or archived:yes if there are repos it would match.

Agree that would be ideal. I want it. The problem is that the current code that sort of does "do-a-hypothetical-search-and-then-raise-a-nice-suggestion-alert" is bad bad. So this is an expensive addition to do propoerly (will take me an extra day or two days). I don't want to make this alert code any worse. We should do it now, no sense in waiting. I'll give that attention before merging this PR. So, expect a couple days delay.

**Comment by rvantonder** [comment]
Added a suggestion for `archive:yes`, only when a single `repo:...` could potentially match, and not for other suggestion cases like repo:foo repo:bar`, because the latter will cascade to the former if the suggestions are taken, e.g.,:

suggest-archived

**Pull request merged**
