### PR TITLE
Update visual details for the creation intro page

### PR DESCRIPTION
**Pull request by vovakulikov**
Follow up for https://github.com/sourcegraph/sourcegraph/pull/28978

Fixes by Alicja feedback from the last PR and from Slack threads 

* update headers to 'track changes' and 'detect and track patterns'
* update the color of the headers and use case to body color in the light theme. Now, the color used is black (#0)
* update the charts used of the cards. I've made some changes regarding the alignment. New charts are available here
* thank you for the feedback regarding the extension icons. I think that 2.5 rem is too big - they look disproportional to other cards. I've increased the size slightly (to 28px) in the design. I think we should go with this size.

Also, I changed the layout of this page according to the experimental layout from @AlicjaSuska [here](https://www.figma.com/file/qomcHxvHjrwfS3We6NVHGh/Automatically-generated-data-series-%5Breview%5D?node-id=1828%3A36510)

I also changed the width of the container here based on feedback from Alicja 

Screenshot 2021-12-15 at 19 09 33

### CODE REVIEW

**Comment by vovakulikov** [comment]
Based on the latest [design](https://www.figma.com/file/qomcHxvHjrwfS3We6NVHGh/Automatically-generated-data-series-%5Breview%5D?node-id=1810%3A35518) spec and discussion with @AlicjaSuska here is the latest layout for this page. 

@AlicjaSuska It seems like the previous hover/focus state doesn't fit properly for cards where we have charts and example blocks with backgrounds. I added a hover box shadow for the card. Let me know if we need to create/adjust another visual state for this. Thanks

Screenshot 2021-12-16 at 04 43 42

**Review by AlicjaSuska — CHANGES_REQUESTED** [review]
Thank you @vovakulikov ! 
- regarding the hover state: as we've discussed on slack, let's increase the shadow to make the card look like it's more to the front ([Figma](https://www.figma.com/file/qomcHxvHjrwfS3We6NVHGh/Automatically-generated-data-series-%5Breview%5D?node-id=1890%3A39124))
- I've also created a '[design QA](https://www.figma.com/file/qomcHxvHjrwfS3We6NVHGh/Automatically-generated-data-series-%5Breview%5D?node-id=1890%3A39654)' that lists some small adjustments for the card layout

**Comment by vovakulikov** [comment]
@AlicjaSuska I added the last changes around desing QA questions. It should be in the storybook as soon as build is passed, Take a look

**Review by unclejustin — APPROVED** [review]
Code looks good 🌮 if @AlicjaSuska is happy, I'm happy. LGTM

**Review by AlicjaSuska — APPROVED** [review]

**Comment by AlicjaSuska** [comment]
Thank you for all the changes @vovakulikov LGTM!

**Pull request merged**
