### PR TITLE
[SG-27732] wildcard: manual migration TextArea

### PR DESCRIPTION
**Pull request by gitstart-sourcegraph**
## Descriptions

- All incorrect usage of the previous pattern has been updated to use the Wildcard component
- Enable a rule to ban the `textarea` element. This should be similar to [what has been done to the Button component](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/eslint-plugin-wildcard/lib/index.js?L23-24).
- Migrate all usage of `<textarea>` in the codebase. Use the eslint output from step 1, or [this Sourcegraph search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:.*.tsx+%3Ctextarea&patternType=literal).
- Move [FlexTextArea](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/wildcard-issue-automation/-/blob/client/web/src/enterprise/insights/components/form/repositories-field/components/flex-textarea/FlexTextArea.tsx#L71:1) to Wildcard.
- Replace [TextAreaAutosize](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/wildcard-issue-automation/-/blob/client/web/src/nav/Feedback/FeedbackPrompt.tsx#L137:34) with FlexTextArea. We should be able to remove `react-textarea-autosize` as a dependency.

## Refs

- [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/27732)
- [GitStart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27732)

## PR on client side

- https://github.com/sourcegraph/sourcegraph/pull/28942

### CODE REVIEW

**Comment by gitstart-sourcegraph** [comment]
Hi @valerybugakov , a after migrating to the wildcard `<Textarea />` component manually, we noticed a number of UI variations, based on a couple of component implementation details such as.
1. The wildcard label is wrapped in <small> element which defers from <label> which causes a text to seem bold.
2. Some labels on the previous <textarea>s had their own CSS style classes, since label is now passed as a string, we cannot pass those styles. What do you think about accepting label as a ReactNode element?
3. Label has  a `w-100` class, which tends to increase width of element.

What do you suggest as best workaround for these?, do we modify <TextArea /> implementation, in order to fit with use cases of element ?.

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, could you share one example for each point from your list? A link to the source code would be helpful to understand use-cases better.

**Comment by gitstart-sourcegraph** [comment]
> @gitstart-sourcegraph, could you share one example for each point from your list? A link to the source code would be helpful to understand use-cases better.

UI changes cases
1. The wildcard is wrapped into a label that has w-100
  - `client/wildcard/src/components/Form/TextArea/TextArea.tsx` L29
**Use cases(UI changes)**
  - `client/web/src/enterprise/insights/components/form/repositories-field/RepositoriesField.tsx` L116. 
  -  `client/web/src/enterprise/insights/components/form/repositories-field/RepositoryField.tsx` L36
```
The `FlexTextArea` component depends on `TextArea` wildcard. It means every component that depends on the above components have been affected
```
2. The wildcard label is wrapped in `<small>` element which defers from `<label>` which causes a text to seem bold.
  - `client/wildcard/src/components/Form/TextArea/TextArea.tsx` L30
3. Some labels on the previous <textarea>s had their own CSS classes. 
**Use cases**
  - `client/web/src/marketing/SurveyForm.tsx` L110-L112
  - `client/web/src/marketing/SurveyForm.tsx` L122-124

**Review by valerybugakov — COMMENTED** [review]
@oleggromov, could you take a look at it when you get a chance?

**Comment by umpox** [comment]
@gitstart-sourcegraph We will likely have to make slight changes where this component is used for different pages / use cases.

If in doubt, we want to keep these migrations purely technical. As in, ideally we avoid any UI changes at all. This might mean we need to add an additional `className` here and there to achieve this.

> The wildcard label is wrapped in element which defers from which causes a text to seem bold.
If these are minor changes that don't seem problematic, then we can keep it. If it looks slightly wrong for any reason then if it possible to add an additional `className` to preserve the old styles?

> Some labels on the previous <textarea>s had their own CSS style classes, since label is now passed as a string, we cannot pass those styles. What do you think about accepting label as a ReactNode element?
Yeah that's a good idea. Let's update it to take a `ReactNode` and then we have more control to override styles where necessary.

> Label has a w-100 class, which tends to increase width of element.
Can we remove the `w-100` class from label and only apply it where required through the `className` prop?

I

**Comment by gitstart-sourcegraph** [comment]
@umpox yeah, we got those issues when migrate all usage of <textarea> in our codebase to this component, we already think about doing what you have just suggested but just want to confirm. So we will continue this PR with the suggestions.

**Comment by gitstart-sourcegraph** [comment]
@umpox While continuing this PR, we found out that
- Current implementation of `<TextArea />` wrapping `textarea` and `message` inside `label`, there are some css rules for `label` which affects styles of `message` and others (ex: `letter-spacing` `margin-bottom`....). 
- Almost usages of `<textarea />` are following bootstrap template with `div.form-group -> textarea.form-control`, I think we should keep that for `wildcard/TextArea`, so we would have something like this:

```jsx
<div className={classNames('form-group', className)}>
    <label>
        {label && <div className="mb-2">{size === 'small' ? <small>{label}</small> : label}</div>}

        <textarea
            disabled={disabled}
            className={classNames(
                styles.textarea,
                'form-control',
                getValidStyle(isValid),
                size === 'small' && 'form-control-sm'
            )}
            {...otherProps}
            ref={reference}
        />
    </label>
    {message && <FormFieldMessage isValid={isValid}>{message}</FormFieldMessage>}
</div>
```

What do you think about these changes for `wildcard/TextArea`

**Review by umpox — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
