### PR TITLE
logo: Give a new face to this company

### PR DESCRIPTION
**Pull request by efritz**
Screen Shot 2021-03-29 at 2 34 57 PM

### CODE REVIEW

**Comment by andreeleuterio** [comment]
LGTM!

**Comment by ebrodymoore** [comment]
I'm sorry for suggesting this @everybody

**Comment by bmoe** [comment]
Why don't I see an approve button? I really want to push that approve button.

**Comment by efritz** [comment]
Looks like Sourcegraph just isn't ready for this yet.

**Comment by ebrodymoore** [comment]
Crisis averted

**Pull request closed without merging**
