### PR TITLE
web: site-admin: link to the management console

### LINKED ISSUE #1776: Site configuration area should always link to management console docs
This page should always link to the management console docs, somewhere: https://sourcegraph.com/site-admin/configuration

### PR DESCRIPTION
**Pull request by slimsag**
Fixes #1776

How it looks:

image

image

### CODE REVIEW

**Comment by slimsag** [comment]
@francisschmaltz @sqs please review wording / spacing etc.

**Comment by francisschmaltz** [comment]
@slimsag why did we remove the password?

**Comment by slimsag** [comment]
It's not removed, that is how the page looks after it is 'dismissed forever'

**Comment by slimsag** [comment]
The addition here was the text below the password area

**Pull request merged**
