### PR TITLE
remove code intel hover alerts

### PR DESCRIPTION
**Pull request by sqs**
The HoverAlerts for the code navigation precision level are large and distracting. I would guess most users tune them out, and most users can’t or don’t take action based on them.

Now that we are moving toward auto-indexing and accept that the burden is on us to make it easy for precise code navigation to be rolled out and on admins to actually set that up, they are even less valuable to show to each user IMO.

This is what I mean by "code intel hover alert" and what this PR removes:

image

Users can click on the badge in the top right corner of the hover (`SEARCH-BASED` in the screenshot above) if they want to find more information about the precision.

This does not affect the hover alerts for the browser extension that inform the user that (eg) GitHub's native tooltips are being suppressed.

## Test plan

With a clean localStorage to ensure the dismissal state is cleared, hover over code. Notice that there is no alert.

## App preview:

- [Web](https://sg-web-sqs-rm-codeintel-hover-alerts.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-cahbapyoln.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by olafurpg — APPROVED** [review]
Big +1. Thank you for pushing for this.

**Comment by jjinnii** [comment]
I agree and have no problems removing the alert. For more context as to why we hadn't removed it yet, we were aware of user feedback (internal/external) that this alert was distracting. Before auto-indexing was implemented, we were intending on[ improving this alert](https://www.figma.com/file/p5rVseXjNvXRkvXCdttbWt/Semantic-badge?node-id=704%3A10986) to achieve two things: 

- Help users understand the difference between precise and search-based intelligence without having to go to our docs
- Improve individual adoption of precise code intelligence 

However, as you mention, both of these goals are a lot less relevant with admin-level users setting up precise code intelligence for widespread adoption. 

cc: @macraig

**Review by jjinnii — APPROVED** [review]

**Comment by macraig** [comment]
+1 to @jjinnii's comment above, let's remove it.

**Review by philipp-spiess — APPROVED** [review]
This is amazing! Looks like the extension deprecation and subsequent code intel inlining already paid off 😄

**Comment by philipp-spiess** [comment]
@sqs Yup the code looks good to me 🙂

**Pull request merged**
