### PR TITLE
Cody: Stop trying to escape HTML to make it visible

### LINKED ISSUE #51776: Cody bug: Codeblock still contain escaped entities

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #51776

Oof, this has been an uphill battle so far. 

## The (not so happy) history

To give some context, it all started with this issue: #50680

Cody was passing-through unescaped HTML with side effects. The most annoying and visible ones in these issue were `<input>` and `<style>`.

After some investigation, we learned that this is because of an overly permissive DOMPurify config: Basically all non-XSS-related HTML tags were allowed in the output, including `<input>` and `<style>`.

We started exploring different route for fixes and I decided to go down the route of escaping non-code parts of the markdown so that `<input>` would be converted to `&lt;input&gt;` and would keep being visible to the user. 

This took a couple of back and forth to get right and we still haven't figured out a way to make it match the rendered output. One persisting issue, for example, is that the Markdown lexer returns a different structure for a given text then the final parser result -- And that is with us already using the same engine! This caused me to add workarounds like waiting for the whole markdown block to start the escaping since the issue was particularly visible when code blocks were started but not ended yet.

However, even after various iterations on this, we kept getting reports of issues. 

There are also some existing patterns that make this even harder:

- We are injecting HTML into the markdown before we go through any of the markdown conversation/escaping. This needs to happen on the vscode thread (so before we're even in the browser thread) since that's how we render hallucination <span>s or the error messages. -> This prevents us from doing these conversations in the react components that would fix the next issue:
- We apply the escaping on any input, including the user input, and directly to the response of the LLM. This means that if a user pasts `You & Me` in the chat, they're were actually sending `You &amp; Me` to the LLM. This would then cause more unexpected behavior because the LLM might respond with the escaped characters.

Most of these workarounds were added so that if Cody responds with `<input/>` it would render `<input/>` on the screen, and not just remove it. Given the complexity of this issue though and the current situation of having html escaping artifacts visible randomly, I’m not sure if this is a maxima that we should strive forward to in the short term anymore.

Unforutnalty there is also no way to configure DOMPurify to escape tags that are not matching the config. It will always remove them.

## This PR

In this PR, I’m reverting everything from the escaping journey and move from a denylist approach to an allowlist for DOMPurify.

This makes sure that only HTML attributes that we need for the markdown rendering will end up in the final HTML. 

### How does this affect UX

- If you ask Cody to write HTML **and don't use markdown to format it**, tags will be removed now
- If you ask about a HTML tag in the chat and do not wrap it inside a code block, they will not be visible in the UI (but the LLM will receive the right string)

## Test plan

Here are some examples:

Screenshot 2023-05-11 at 14 59 32
Screenshot 2023-05-11 at 14 57 41
Screenshot 2023-05-11 at 14 56 53

### CODE REVIEW

**Comment by almeidapaulooliveira** [comment]
Fantastic work, Philipp. Love the detailed history as well. Thank you!

**Comment by abeatrix** [comment]
image

i'm still getting escaped html from Cody's response (but definitely improved). Could this be the answer returned by Cody and not caused by our escaped HTML mechanism?

**Comment by philipp-spiess** [comment]
@abeatrix How did you get this? Did you reset the chat history?

My hunch is that this is, as you mentioned, a return from the LLM directly because of the chat history

**Review by abeatrix — APPROVED** [review]
Still seeing escaped html in Cody's answer in the Chat UI but not as bad, and asking Cody to do the same thing returns regular HTML in fixup so probably caused by another issue unrelated to this. Tested inline assist and the answer got back from Cody looks great. More importantly, No more path reverting to HTML tags issues 🎉  Thank you so much

image

**Comment by abeatrix** [comment]
> @abeatrix How did you get this? Did you reset the chat history?
> 
> My hunch is that this is, as you mentioned, a return from the LLM directly because of the chat history

Yea it was a new convo. Maybe you can try to reproduce it by trying to generate a typescript test using the unit test recipe to confirm?

**Comment by abeatrix** [comment]
Hmmm so I can reproduce it and I noticed the escaped HTML happens after the hallucination detection happened: https://www.loom.com/share/efdd6831414c410ab9712380b1c78a31

**Comment by philipp-spiess** [comment]
I’m so confused. I removed the code that does the replace from `>` to `&gt;` 🤔 

Also I tried to reproduce it but I can't get it to do the same :(

Screenshot 2023-05-11 at 15 48 32

Screenshot 2023-05-11 at 15 50 53

**Comment by philipp-spiess** [comment]
I’m so confused. I removed the code that does the replace from `>` to `&gt;` 🤔 

Also I tried to reproduce it but I can't get it to do the same :(

Screenshot 2023-05-11 at 15 48 32

Screenshot 2023-05-11 at 15 50 53

**Comment by abeatrix** [comment]
Yea the result is kinda random too. Sometimes it's just one, sometimes it'd be all of them: 
image

But for certain is the post-rendering process that is causing this because I don't see this issue when Cody is streaming the answers

**Pull request merged**
