### PR TITLE
web: trace search results and search query input

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context

Produce OpenTelemetry spans by several key React components:

1. `CodeMirrorQueryInput`
2. `StreamingSearchResultsListItem`
3. `StreamingSearchResults`
4. `SearchPage`
5. `SearchBox`

Closes https://github.com/sourcegraph/sourcegraph/issues/40468

## Test plan

1. `ENABLE_OPEN_TELEMETRY=true sg start web-standalone`
2. Open the browser console and ensure that debug-level output is enabled.
3. Open the search results page.
4. See spans created by the components listed above.

Screenshot 2022-11-09 at 11 32 45

## App preview:

- [Web](https://sg-web-vb-trace-more-react-components.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.10% (+2.75 kb) | 0.04% (+5.53 kb) | 0.02% (+2.79 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vb/trace-more-react-components/compare-report.html;tab=live_object) for a full comparison between the commits df6fcf0 and 5773b39 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by philipp-spiess — APPROVED** [review]
Nice! LGTM.

This only measures rendering time for these components though, does it? I.e it does not add event listeners for typing delay measurements (something I think would be cool to have for the query input things).

**Review by limitedmage — APPROVED** [review]
Very cool!

**Comment by valerybugakov** [comment]
> This only measures rendering time for these components though, does it? I.e it does not add event listeners for typing delay measurements (something I think would be cool to have for the query input things).

@philipp-spiess, yes, user interactions are not tracked yet. Probably, they will be a part of [the RUM instrumentation implemenation](https://github.com/sourcegraph/sourcegraph/issues/39280), or we will instrument _some_ interactions manually if an auto-instrumentation isn't a good fit.

**Pull request merged**
