### PR TITLE
wildcard: implement FeedbackPrompt

### PR DESCRIPTION
**Pull request by gitstart-sourcegraph**
## Descriptions:

1. Move [FeedbackPrompt](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/bootstrap-transition/-/blob/client/web/src/nav/Feedback/FeedbackPrompt.tsx#L193:29) to Wildcard.
2. Move [FeedbackBadge](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/bootstrap-transition/-/blob/client/web/src/components/FeedbackBadge.tsx?utm_source=VSCode-1.4.0#L10:23) to Wildcard.
3. Move [FeedbackText](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/bootstrap-transition/-/blob/client/web/src/components/FeedbackText.tsx?utm_source=VSCode-1.4.0#L7:23) to Wildcard

## Refs
- [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/27712)
- [GitStart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27712)

### CODE REVIEW

**Comment by gitstart-sourcegraph** [comment]
we have 3 ways of using `FeedbackPromptContent`:
- In Popover
- In Dialog
- In ButtonDropdown

Suggest that we can combine them into this kind of component

```
<FeedbackPrompt
    dialog={true/false} => should use `Dialog` or `Popover` (will update ButtonDropdown to use Popover)
    closePrompt={...}
    routeMatch={...}
    textPrefix={...}
    buttonProps={...} => for rendering `Button` as the trigger
>
    <span>Button content</span>
</FeedbackPrompt>
```

## Also
- `FeedbackPromptContent` handles `submitFeedback` with graphql mutation, should we keep that implementations in `wildcard` package?
- We can use `Popover` but current implementation requires `flipRightPosition` from `enterprise`, is it ok to move it to `wildcard`?

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, I would keep API interactions outside the Wildcard package and expose an interface to provide a submit handle. 

cc @oleggromov for the question related to combining multiple ways of component usage into one interface.

**Comment by gitstart-sourcegraph** [comment]
> an interface to provide a submit handle.

Thanks @valerybugakov. Looking forward to his response

**Comment by umpox** [comment]
> About FeedbackPrompt, as far as we can see, we have 3 ways of using FeedbackPromptContent:
In Popover
In Dialog
In ButtonDropdown
For moving this into wildcard, we suggest to combine them into this kind of component

My view is that these are all very similarly styled, and we should actually just use a single `Popover` style. I've already started working on adding the `Popover` component through https://github.com/sourcegraph/sourcegraph/pull/29054/files. Let's address moving the `FeedbackPrompt` in a follow-up PR once the `Popover` component is added.

> FeedbackPromptContent handles submitFeedback with graphql mutation, should we keep that implementations in wildcard package?

I agree with @valerybugakov, this can just be handled by the consumer through an `onSubmit` prop or something.

> We can use Popover but current implementation requires flipRightPosition from enterprise, is it ok to move it to wildcard?

This is the same as my implementation for `Popover`. Don't worry about this, I'll do it in my PR. We can reuse the Popover component once it has been added to Wildcard

**Review by umpox — APPROVED** [review]
This looks good. Let's update `FeedbackPrompt` in a follow-up PR once https://github.com/sourcegraph/sourcegraph/pull/29054 has been merged.

Please fix `yarn.lock` it looks like it has corrupted. `git checkout main yarn.lock` and rerunning `yarn` should fix.

**Review by valerybugakov — APPROVED** [review]

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov @umpox We are going to merge this PR. Should we keep the issue open or just let it close with this PR?

**Comment by umpox** [comment]
@gitstart-sourcegraph Please keep this issue open for now, we'll still want to move the `FeedbackPrompt` component but there's some ongoing discussions about how best to implement the `Popover` component first!

**Review by umpox — APPROVED** [review]

**Pull request merged**
