### PR TITLE
dx: inject remote js-context into local `index.html`

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context

- Adds support for the dynamic JS context received from the API proxy when the standalone web server is used. It means that `window.context.isAuthenticatedUser` changes now if we sign in or sign out! And all the other `jsContext` fields are always up to date. 🙂
- Drops `html-webpack-plugin` dependency.
- Supports `esbuild` development server.
- Closes https://github.com/sourcegraph/sourcegraph/issues/21870
- Prepares `web-standalone` for https://github.com/sourcegraph/sourcegraph/pull/47010

## Test plan

1. `sg start web-standalone`
2. `sg start web-standalone-prod`
3. `ENTERPRISE=true WEBPACK_SERVE_INDEX=true SOURCEGRAPH_API_URL=https://sourcegraph.sourcegraph.com DEV_WEB_BUILDER=esbuild pnpm --filter @sourcegraph/web serve:dev`

Try to sing in and sign up. Ensure that the `window.context` is updated and corresponds to the `jsContext` served by the proxied API.

## App preview:

- [Web](https://sg-web-vb-inject-remote-js-context.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by vovakulikov — APPROVED** [review]
Tested manually. I think the third option in this PR description doesn't work since we don't allow sing in flow with Github and other third party services for the local standalone

**Comment by valerybugakov** [comment]
@vovakulikov, it works for me, since we now have username/password authentication enabled on S2

**Comment by vovakulikov** [comment]
@valerybugakov yeah as we discussed in DM, I didn't know that there is an option to use pass/login for s2, I checked it just now and everything works with s2 and esbuild. 

Kind of side note: pnpm --filter @sourcegraph/web serve:dev says that you need to open sourcegraph.test:3443 but this script doesn't run caddy and in my case I need to go to the http port which is localhost:3080 to get access to the served client in the browser.

**Comment by valerybugakov** [comment]
@vovakulikov, my bad, I forgot to mention caddy. I have it running in a separate terminal window all the time 🙂

**Pull request merged**
