### PR TITLE
throttle stream search events instead of debouncing

### PR DESCRIPTION
**Pull request by camdencheek**
This fixes an issue with our streaming search rendering pipeline that
was, in some cases, causing no results to be rendered until the entire
search was complete.

When reducing the stream of search events, we were rate-limiting the
number of UI updates by piping them through `debounceTime`. The problem
with `debounceTime` in this case is it will not emit an event until the
configured time has passed and there have been no events observed. With
streaming search though, we are sending a progress event every 100
milliseconds, so the condition to emit an update event was never met. In
effect, this made it so no results were rendered on the page until the
search was complete, after which 500 milliseconds would pass and the
page would render.

This commit replaces `debounceTime` with `throttleTime`, which, instead
of waiting for a period of no events, always emits an event after the
interval if the value has changed. This change significantly improves
the time to first rendered results.

Before:

https://user-images.githubusercontent.com/12631702/128783646-d8b855f3-83b5-4e74-b096-dab93b1ca54d.mov

After:

https://user-images.githubusercontent.com/12631702/128783642-9639cc34-31a6-42b5-9382-394d873a31fa.mov

### CODE REVIEW

**Review by limitedmage — APPROVED** [review]
Great find! RxJS is great but it's hard to decide which operators to use when >__<

**Review by rvantonder — APPROVED** [review]
`:lolsob:`. feels good to fix this though...

I recorded some searches on Sourcegraph.com to compare time to first result after this change. Not that great for benching but better than nothing.

**Comment by rvantonder** [comment]
Don't think it's worth `master-dry-run`ing this, probably annoying to try merge with flaky CI. Happy to stamp a PR with a different branch name.

**Comment by rvantonder** [comment]
(well, since `master-dry-run` already passed except for the flaky QA thing... feel free to PR without)

**Comment by camdencheek** [comment]
Closing in favor of #23742

**Pull request closed without merging**
