### PR TITLE
Add temporary Firefox add-on alert

### LINKED ISSUE #14233: Add alert for all the Firefox users once the add-on is fixed
Part of the [RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing): Improve discoverability/awareness of the browser extension

**Description**
Once the Firefox extension is back, we need to communicate this to users. It's a great opportunity to highlight the benefits of using the extension as well.

**Design documentation**

- display [this alert](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=563%3A96) for all the users the day Firefox add-on is back
- as the regular alert, it should be displayed in the context of a file
- after 4 weeks, display the [regular alert](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=366%3A240) instead
- Add an event to the link in the alert to get data on how many people clicked on it @ebrodymoore FYI (for cloud only; server pings coming soon)

### PR DESCRIPTION
**Pull request by tjkandala**
Closes #14233

This component won't render anything after December 21, 2020.

@AlicjaSuska I interpreted "display this alert for all users" as "show this alert for users that have already dismissed the usual alert as well". Since this alert isn't meant to replace the original alert (under this interpretation), I made sure that the two alerts didn't look too bad together.

#### Only the Firefox alert
Screenshot from 2020-11-26 21-21-23

#### Both alerts
Screenshot from 2020-11-26 21-21-39

---

I decided that it wasn't yet time to create an abstract `<RepoAlerts>` component, since this is only the second alert and it's temporary. 

'install the add-on' links to our docs page instead of the direct download link, since that would feel sketchy and provides no further context.

I also added 
- **snapshot tests** to assert that this component only renders before the final date and that it doesn't break when passed unknown external URLs
- **stories** for all code hosts so you can easily check the copy.

All this code should be ripped out after December 21, 2020.

### CODE REVIEW

**Review by AlicjaSuska — CHANGES_REQUESTED** [review]
Thank you @tjkandala! I agree - we should show the 'FF add-on is back' to all the users, even those who have dismissed the regular alert in the past.

I think we should not show 2 alerts at the same time though. The 'FF add-on is back' alert should be the only one being shown. Also, if the user dismisses this alert, it should be treated as if they dismissed the regular 'install the add-on' alert.

Basically, the 'FF add-on is back' alert should substitute the regular 'install the add-on' alert for the time of this campaign.

There is one more visual adjustment - in the dark mode, the animated flashing background should be lighter. Please, see in [Figma](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=869%3A0).

Screenshots of current and designed states for comparison:

Screenshot 2020-11-27 at 09 51 46
Screenshot 2020-11-27 at 09 51 52

**Comment by felixfbecker** [comment]
@marekweb I see that the extension is not yet listed on AMO again: https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=sourcegraph
Do you know when that would happen or what stands in between that?

**Comment by tjkandala** [comment]
Screenshot from 2020-12-03 17-28-03

@AlicjaSuska Only one alert shows at a time now, color is fixed

@marekweb I left a `TODO` about the Firefox addon. We link to our docs for now, but we should link to AMO when possible

**Comment by marekweb** [comment]
> @marekweb I see that the extension is not yet listed on AMO again: https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=sourcegraph
Do you know when that would happen or what stands in between that?

I believe we had identified the apparent next steps to get the add-on page published, but we didn't complete them.

**Comment by felixfbecker** [comment]
Are those next steps written down somewhere? If it's straightforward I think we should take them before merging this.
I am worried about what implications this could otherwise have on upgrades. I know that for the self-hosted version, updates come from a JSON file in GCP. If we tell users to download the self-hosted version with this alert after they did not have the extension installed, and then we publish to AMO they might not get automatically updated to the store version and are stuck on their version. We then would have to tell them _again_ to download the version from the store and uninstall the current one.

**Review by AlicjaSuska — APPROVED** [review]

**Pull request closed without merging**
