### PR TITLE
reference panel: use search context if set

### PR DESCRIPTION
**Pull request by mrnugget**
Slack thread with context: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1659571561078019

Long story short: the extensions-based reference panel took the searchContext of a user into account when executing search queries for search-based code intel. See [this bit of code here](https://sourcegraph.com/github.com/sourcegraph/code-intel-extensions@ef4bbe5ff954be401c04e083f4063f6320ca5939/-/blob/template/src/util/api.ts?L527:15)

When building the new reference panel I forgot to port this over.

This now ports the behavior by using the helpers added to `legacy-extensions` when porting the old extensions code over.

## Video to demonstrate how it works

https://user-images.githubusercontent.com/1185253/194897972-2bffc0fa-e927-4423-8306-2902c9d6530c.mp4

## Test plan

Tested locally with and without search context.

## App preview:

- [Web](https://sg-web-mrn-search-context-ref-panel.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-rfxtcqhvuq.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by olafurpg — APPROVED** [review]
I haven't tested this locally but the diff LGTM 👍🏻

**Review by efritz — APPROVED** [review]
@olafurpg When you inlined the code were you on a non-`HEAD` branch? Seems like a few things fell through the cracks and wonder if a diff pass would be good to catch anything else that's hidden.

**Comment by olafurpg** [comment]
@efritz IIUC, this bug is unrelated to when extensions got inlined. The inlined extensions already use the correct search context. The regression was introduced when the new reference panel inlined extensions.

**Comment by mrnugget** [comment]
Yeah, it's not about inlining extension. I forgot to port these two lines over when adding search-based code intel the new reference panel back in ... April? I honestly think I glanced over these lines because I was focused on sending GraphQL requests without going through the extensions API and since I never use search contexts myself I didn't notice it

**Comment by philipp-spiess** [comment]
FYI I pushed another commit onto this branch as per @mrnugget's idea as I wanted to pull out the module scoped variable here into its own module so that we do not have a hard require to the migrated code intel APIs. If `enableLegacyExtensions` is true, this would otherwise load a bunch of code that isn't really used.

**Comment by olafurpg** [comment]
The only thing I'm aware of that fell through the cracks is https://github.com/sourcegraph/sourcegraph/pull/42055, which was caused by not adapting a diff from the new reference panel into the inlined extensions (`additionalLanguages` was not used anywhere in sourcegraph/code-intel-extensions but it had to be used in sourcegraph/sourcegraph).

**Comment by mrnugget** [comment]
Tested locally with @philipp-spiess's changes, still works. Enabling auto-merge.

**Pull request merged**
