### PR TITLE
Search suggestions: accept and trigger search result on `Enter`

### PR DESCRIPTION
**Pull request by olafurpg**
This PR changes the behavior of the experimental feature flag `applySearchQuerySuggestionOnEnter` so that pressing `Enter` accepts the selected suggestion and triggers a search. If the search query is for an exact repo, symbol, or file then we navigate straight to that result instead of opening the search page with only a single result.

All of the new/experimental functionality is hidden behind the `applySearchQuerySuggestionOnEnter` experimental feature flag. The only change to the default behavior is a bugfix where we now suggest repos/paths if the query contains `type:repo` or `type:path` instead of unconditionally suggesting symbols.

Big thanks to @Strum355 for pairing with me on this PR 🙏🏻 

Demo https://www.loom.com/share/481c43d64e0a42dc8ed1ad2d08103062

TODOs:

- [x] Fix failing tests
- [x] Add basic new tests for some new behavior
- [x] Hide new repo/path completion suggestions behind "apply on enter" feature flag

Worth considering fixing with a separate PR:
- Allow the user to unselect a completion by pressing UpArrow at the top suggestion. Currently, this cycles through the completion list.
- Make "click on suggestion" have the same behavior as "enter on suggestion". Currently, clicking has the same effect as `Tab`
- Show "No suggestions" when the user explicitly requests suggestions with Cmd+Space

## Test plan
See updated unit tests. It would be good to additionally have e2e tests covering common workflows like using `Enter` to select a repo and asserting that the URL has updated.

## App preview:

- [Web](https://sg-web-olafurpg-terminal-suggestions.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.19 kb) | 0.01% (+1.19 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/olafurpg/terminal-suggestions/compare-report.html;tab=live_object) for a full comparison between the commits 2673a43 and 1d0a9ec or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by limitedmage** [comment]
Meta comment: I personally don't like that `enter` would submit the search. Would be good to run a usability study to see which of the 3 behaviors is the most intuitive (tab selects suggestion and enter submits; enter selects suggestion if there is one and submits if there isn't; or enter selects and submits with one press).

I do love skipping the search results if there is only one result, this just makes sense.

**Comment by olafurpg** [comment]
@limitedmage Thank you for sharing! I think the "enter to search" behavior would be more intuitive if we make two further changes:


- Update the search query on UpArrow/DownArrow to match the highlighted suggestion. The search query should already be updated to the suggestion value when the user presses enter. Google search does this.
- Make suggestions same width as the search bar, similar to the UI of most other search engines.

**Comment by limitedmage** [comment]
> @limitedmage Thank you for sharing! I think the "enter to search" behavior would be more intuitive if we make two further changes:
> 
> * Update the search query on UpArrow/DownArrow to match the highlighted suggestion. The search query should already be updated to the suggestion value when the user presses enter. Google search does this.
> * Make suggestions same width as the search bar, similar to the UI of most other search engines.

Yes, if we can implement those UI updates, I think that would be a great experience! @fkling are those updates possible/easy? I'm fine with going ahead with this change under the current feature flag if we can implement that soon-ish.

**Review by sqs — APPROVED** [review]
I did not review the code, but I did review the new behavior and it looks a lot faster for users (and more intuitive IMO). I'm excited to try it and potentially make it the default behavior.

**Comment by olafurpg** [comment]
I've done a second review to make sure the riskier changes are behind the feature flag. Here are the main changes from the Loom demo:

"Instant results" have a lightning bolt icon to indicate speed (you skip the search page when pressing enter). Also notice that repository results have star counts to explain the ranking.
 
CleanShot 2022-11-18 at 13 58 12

Because all symbol results have the same icon now, I've added the symbol kind name to the label itself.

CleanShot 2022-11-18 at 14 02 42

Pressing enter on non-instant results no longer triggers a search because it was more confusing than helpful.

**Pull request merged**
