### PR TITLE
React to OS dark theme setting

### LINKED ISSUE #507: React to Mojave dark theme
#### Feature request description

CSS has a standard now for detecting dark mode and it has been implemented in Safari Technology Preview 68.

https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-color-scheme

We can read it from JS with https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

We should support three states essentially, "light", "dark" and "OS"/"auto".

### PR DESCRIPTION
**Pull request by felixfbecker**
https://caniuse.com/#feat=prefers-color-scheme

Closes #507

Also cleans up some of the `isLightTheme` props passing.

If no preference is saved yet, system is the default (which will be light for browsers/OS not supporting it).

### CODE REVIEW

**Comment by felixfbecker** [comment]
> We should paint most of the interface through css with `prefers-color-scheme` and then apply anything after. See my branch at [/theme-switch@`fs`](https://github.com/sourcegraph/sourcegraph/tree/fs/theme-switch)

And what would be the benefit of that?

**Comment by francisschmaltz** [comment]
We should use the code as intended instead of a hack to work around our legacy style code. When we do it through css the changes happen at the system level so there is some perforce gain as well as supporting the transition with system elements.

**Comment by felixfbecker** [comment]
I haven't noticed any performance problems. I think this is premature optimisation.

We do JS to switch themes on master, and we do it on this branch. Changing that would be a larger effort which is not a good use of our time because the benefit is marginal. The situation is not deteriorated by this PR, it just adds a nice-to-have feature.

**Comment by francisschmaltz** [comment]
> Changing that would be a larger effort which is not a good use of our time because the benefit is marginal.

Then we should postpone this feature until we can do it correctly

**Pull request merged**
