### PR TITLE
Integration test improvements

### PR DESCRIPTION
**Pull request by felixfbecker**
See commits.

### CODE REVIEW

**Comment by eseliger** [comment]
Are you sure the favicon is fixed? I think the hostname is wrong

> Browser console: ✖ error Failed to load resource: net::ERR_NAME_NOT_RESOLVED
--
  | at https://sourcegraph.test:3443/favicon.ico

**Comment by felixfbecker** [comment]
@eseliger nice catch, had to add `other` to the types of intercepted requests!

**Comment by felixfbecker** [comment]
No, that's because of this test: https://github.com/sourcegraph/sourcegraph/pull/12134#discussion_r456491848
cc @marekweb

**Comment by felixfbecker** [comment]
FYI @eseliger the campaigns story is flaky in Chromatic too (the video is only hidden in Percy)

**Pull request merged**
