### PR TITLE
Add events from frictionless cody to allowlist (#51649)

### PR DESCRIPTION
**Pull request by akalia25**
backport PR that has the main commit cherry picked
---------
The events need to make it into Amplitude to determine if our efforts are successful.

* Ensure megration is applied in the DB
* Step through the home page to ensure events are triggered and are added to the allowlist
* Click the signup to get access button on Sorucegraph.com/search and fire an event
* Observe event in Amplitude

---------

Co-authored-by: Aditya Kalia <32119652+akalia25@users.noreply.github.com>
(cherry picked from commit 49522d84a60e95752e4aa5879a09ce22b7f6216d)

### CODE REVIEW

**Comment by camdencheek** [comment]
@akalia25 does this need to make it into the patch release?

**Comment by akalia25** [comment]
@camdencheek yes, please, if possible! 

I did this backport before your message on release-guild to just add the `please-backport-5.0` label. So hopefully this doesnt cause you too much trouble!

**Comment by camdencheek** [comment]
No problem! Just wanted to make sure this didn't slip through the cracks

**Comment by camdencheek** [comment]
Approved to unblock. Go ahead and merge this whenever it's ready

**Review by camdencheek — APPROVED** [review]

**Comment by akalia25** [comment]
@camdencheek, hmm getting this error, is 5.0 restricted to only allow release captains to merge? If so, this PR is ready to merge, whenever someone can merge.
image

**Comment by rrhyne** [comment]
TY @camdencheek!

**Pull request merged**
