### PR TITLE
show org name not displayName in most places

### PR DESCRIPTION
**Pull request by sqs**
Previously, organizations would be displayed using their `displayName`, which was inconsistent and non-canonical. The `displayName` is also longer, so it's not suited to display in select menus and other similar places.

For example, when viewing the user menu or creating a batch change or saved search, the dropdown will now show `sourcegraph` instead of `Sourcegraph` (where the latter is the display name).

image

## Test plan

Go to create a batch change or saved search and confirm that org names not displayNames are shown.

## Changelog

- The user menu and other filter menus now show the names of organizations, not their "display names", to avoid ambiguity. For example, these menus will now show `abc-corp` not `ABC Corp` (if the latter was the `abc-corp`'s display name).

### CODE REVIEW

**Review by BolajiOlajide — CHANGES_REQUESTED** [review]
I think there's a conversation to be had around this change. There's been discussions during the Batch Changes era about displaying the `displayName` for both users and org namespace.
Whilst the `displayName` is non-canonical, it is the one slug that's easily editable and recognizable within Sourcegraph. In the user dropdown, the display name is what we show to users and this change could bring about confusion.

CleanShot 2024-07-18 at 12 45 05@2x

For example on S2, we have an org with the name `sourcegraph` and `displayName` of CodeSearch.

CleanShot 2024-07-18 at 12 45 38@2x

I've seen customers create orgs with weird names and they usually depend on the `displayName` especially during org changes.

CleanShot 2024-07-18 at 12 38 21@2x

Personally, I'd even prefer displaying the `displayName` for both User and Org in the namespace selector component.

**Comment by sqs** [comment]
@BolajiOlajide What if we change what’s displayed in the user menu as well to just show the name not displayName? Then it’s consistent.

What are the situations you’re aware of where that would be bad for customers?

**Comment by eseliger** [comment]
Since displayName is not globally unique using that field could actually be quite misleading. 

I wonder if we should have a displayName at all - or if we should, if we should instead say whenever you display `displayName` you also have to render the canonical name. 

So overall I am ok with this change.

**Comment by BolajiOlajide** [comment]
> @BolajiOlajide What if we change what’s displayed in the user menu as well to just show the name not displayName? Then it’s consistent.
> 
> What are the situations you’re aware of where that would be bad for customers?

The one case that stands out was after a customer re-org, they wanted the org to reflect it's new name and all they did was update the `displayName`.

**Comment by BolajiOlajide** [comment]
> Since displayName is not globally unique using that field could actually be quite misleading.
> 
> I wonder if we should have a displayName at all - or if we should, if we should instead say whenever you display `displayName` you also have to render the canonical name.
> 
> So overall I am ok with this change.

Good point on it's uniqueness. 
If you check the linked screenshot in my earlier message, we also have a `displayName` field for Users.

**Comment by BolajiOlajide** [comment]
@sqs If we can make the update in the sidebar, it will at the very least reduce confusion from customers.

We can then communicate this change as time goes on.

**Comment by sqs** [comment]
@BolajiOlajide Thanks! Updated all the other similar places where we showed the org displayName to just show the name.

**Review by BolajiOlajide — APPROVED** [review]

**Pull request merged**
