### PR TITLE
web: Add aria roles to Tabs component

### LINKED ISSUE #12915: Code view sidebar should use a tab group
Currently, the code view sidebar tabs (File/Symbols) are not being labeled correctly as a tab group. Each tab is just being treated as a button.

https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

Screen Shot 2020-08-11 at 9 05 02 AM

### PR DESCRIPTION
**Pull request by jeanduplessis**
To improve accessibility the `tablist` and `tab` roles were added to the elements of the component.

Closes #12915

### CODE REVIEW

**Review by felixfbecker — APPROVED** [review]
Awesome 🎉 
We can merge this as-is since it's strictly an improvement, although to make these fully accessible a few more things would need to be added (see the link in the issue), in order of importance:
- `aria-selected="true/false"` on the tab
- `aria-controls="#id"` on the tab to reference the tabpanel
- `aria-labelledby="#id"` on the tabpanel to reference the tab

The code also needs to be formatted by Prettier (that's why CI is failing). If you're using VS Code, this should happen automatically on save. Otherwise you can run `yarn prettier` in the terminal to format all files.

**Comment by felixfbecker** [comment]
FYI @jeanduplessis it looks like your local git email config doesn't match any email in your GitHub profile so the two are not linked.

**Comment by jeanduplessis** [comment]
@felixfbecker thanks for the initial review. I wasn't 100% sure whether to implement the other aria properties, but definitely agree we can and should add those. I'll create a follow up issue so that we don't lose track of doing it.

Thanks for the heads-up on prettier and my git email config - will fix those now.

**Comment by jeanduplessis** [comment]
I've opened up the follow-up issue here: https://github.com/sourcegraph/sourcegraph/issues/15403

**Review by limitedmage — APPROVED** [review]

**Pull request merged**
