### PR TITLE
Open in Editor: Use line numbers to open the right line of the file

### PR DESCRIPTION
**Pull request by vdavid**
We had two issues:
1. We didn't _pass_ the needed information (the search query part of the URL) to the URL builder logic, so it had no chance to use it 😄 
2. We didn't use the returned `position` information, just `range`, so if only a single line was selected, it wouldn't have used the returned position info.

Fixed both and now it works fine for me.

## Test plan

Half-minute Loom demo: https://www.loom.com/share/d77cb2b773af46a4aa9156feec1b6796

## App preview:

- [Web](https://sg-web-dv-fix-open-in-editor-line-numbers.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.03 kb) | -0.00% (-0.03 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/dv/fix-open-in-editor-line-numbers/compare-report.html;tab=live_object) for a full comparison between the commits d991f0c and 0d14273 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by philipp-spiess — APPROVED** [review]
oh, nice fix!

**Comment by jjinnii** [comment]
@vdavid Thank you for working on this fix! I had this come up a couple of times in user interviews 😄

**Comment by vdavid** [comment]
@jjinnii I hadn't heard about it before @coury-clark reported it on Slack.
If you have any ideas on how to make the info from from user interviews → GitHub board where we prioritize items, let me know. I'd love to give ourselves a chance to prioritize our backlog items based on user feedback.

**Comment by jjinnii** [comment]
They are interviews I did very recently right before the offsite, so I have not had a chance to synthesize those findings yet. In general, issues that are created tags me and the acting PM, so I'll try to proactively add feedback. I don't quite see another way around this. This team is obviously in a weird in btw state right now where we don't have groomings/plannings where we might have surfaced this as well.

**Pull request merged**
