### PR TITLE
Cody: Promote VS Code extension to beta

### PR DESCRIPTION
**Pull request by philipp-spiess**
Part-of #51445

I did a grep across the repo for "experimental" and replaced all labels that made sense. Speciifcally:

- This changes the label inside the VS Code extension
- Changes the labels inside the docs
- Changes the label inside the App "coming soon" upsell

cc @gwestersf 

## Test plan

Screenshot 2023-05-09 at 16 05 13

### CODE REVIEW

**Comment by philipp-spiess** [comment]
@gwestersf This does not include about.sourcegraph.com (since that's a different repo). Is this on your agenda? :)

**Comment by philipp-spiess** [comment]
@gwestersf Also: Do you think we need to block on the full to-do lost that you shared in #51445 before we release the next VS Code release?

**Comment by sourcegraph-buildkite** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.02 kb) | -0.00% (-0.02 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/cody-beta/compare-report.html;tab=live_object) for a full comparison between the commits c462e57 and 0f40428 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by thenamankumar — APPROVED** [review]

**Review by abeatrix — APPROVED** [review]
NICE!

**Comment by gwestersf** [comment]
> 

Two responses:

Please execute the changes on About repo also. I noticed it a lot on the pricing page.

We do not need to block and wait for VS code to release. Just start deploying the changes on a rolling basis. It will eventually be consistent.

**Comment by philipp-spiess** [comment]
@gwestersf Looks like someone else was faster: https://about.sourcegraph.com/cody

Didn't find any other referencess to cody as experimental 😎

**Pull request merged**
