### PR TITLE
feat: add local navigation via tree-sitter

### PR DESCRIPTION
**Pull request by tjdevries**
Use our new scip-syntax (currently named scip-semantic, will rename shortly) to provide local navigation within a file

## Test plan

- [ ] Add perl and then test local nav is significantly better

### CODE REVIEW

**Comment by tjdevries** [comment]
@olafurpg got the first version of this working today. was planning on getting farther but i busted up my index finger (not a joke, it's actually super bruised haha) so i don't think i'll get any farther tonight. pushed though and you should be able to get local symbol nav for golang at least at the moment.

**Review by olafurpg — COMMENTED** [review]
I tried to build this locally but I'm getting the following error in Cargo

```
error: no matching package named `scip-semantic` found
location searched: https://github.com/sourcegraph/scip-semantic#5da4804d
required by package `sg-syntax v0.1.0 (/Users/olafurpg/dev/sourcegraph/sourcegraph/docker-images/syntax-highlighter/crates/sg-syntax)`
[Finished running. Exit status: 101]
```

Do I need to make any local steps to get this working? What do you think about inlining scip-semantic for now so that we can iterate on everything in the monorepo?

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.40 kb) | 0.00% (+0.40 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/scip-syntax-documents/compare-report.html;tab=live_object) for a full comparison between the commits c6172c6 and 498604f or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by tjdevries** [comment]
- [ ] TODO: Remove all of our unwraps & expects from tags code. gracefully skip failing for now (so that it is low risk for now). we can graduate to a failed request later.

**Comment by tjdevries** [comment]
@olafurpg this happens when you request "goto references"

image

**Pull request merged**
