### PR TITLE
metrics: Add task label to RequestMeter

### PR DESCRIPTION
**Pull request by ryanslade**
Adds the `task` field to the our `RequestMeter`. This will allow us to track the reason
we're hitting external API's.

At the moment it's only being tagged for external service syncing as well as repo and 
user permissions syncing.

# Test Plan

Test locally to ensure metrics are populated

### CODE REVIEW

**Comment by ryanslade** [comment]
@indradhanush I'm struggling to get Grafana to load locally, would you mind double checking that this works? 

You should be able to see it coming through after a while using this query:
```
sum by (job) (rate(src_github_requests_total[5m]))
```

**Comment by indradhanush** [comment]
I had this running in the background with my code host setup to sync repos from ghe.sgdev.org, but I didn't see any classification based on job type.
image


Also this test is failing at the moment:

```
➜ richgo test -v -run TestRequestMeter
START| RequestMeterTransport
     | t=2022-03-24T20:05:37-0700 lvl=dbug msg="TRACE foosystem" host=foosystem.com path=/apiCallA code=200 duration=10.489283ms
     | t=2022-03-24T20:05:37-0700 lvl=dbug msg="TRACE foosystem" host=foosystem.com path=/apiCallB code=200 duration=10.550886ms
     |     metrics_test.go:74: inconsistent label cardinality: expected 4 label values but got 3 in prometheus.Labels{"category":"/apiCallA", "code":"200", "host":"foosystem.com"}
FAIL | RequestMeterTransport (0.02s)
     | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
     | 	panic: runtime error: invalid memory address or nil pointer dereference
     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x94b57d]
     | goroutine 18 [running]:
     | testing.tRunner.func1.2({0x9b8a40, 0xec55b0})
     | 	/usr/lib/go/src/testing/testing.go:1389 +0x24e
     | testing.tRunner.func1()
     | 	/usr/lib/go/src/testing/testing.go:1392 +0x39f
     | panic({0x9b8a40, 0xec55b0})
     | 	/usr/lib/go/src/runtime/panic.go:838 +0x207
     | github.com/prometheus/client_golang/prometheus/testutil.ToFloat64({0x0, 0x0})
     | 	/home/dhanush/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/testutil/testutil.go:93 +0xfd
     | github.com/sourcegraph/sourcegraph/internal/metrics.TestRequestMeterTransport(0xc000103040)
     | 	/home/dhanush/sourcegraph/sourcegraph/internal/metrics/metrics_test.go:76 +0x3cf
     | testing.tRunner(0xc000103040, 0xa9a888)
     | 	/usr/lib/go/src/testing/testing.go:1439 +0x102
     | created by testing.(*T).Run
     | 	/usr/lib/go/src/testing/testing.go:1486 +0x35f
     | exit status 2
FAIL | 	github.com/sourcegraph/sourcegraph/internal/metrics	0.029s
```

**Review by asdine — APPROVED** [review]

**Comment by ryanslade** [comment]
@indradhanush Thanks for looking into this. I got monitoring working locally and have confirmed that it works. 

I had to rename to `task` since `job` is actually already being using by our default Prometheus collector.

**Comment by ryanslade** [comment]
@cla-bot check

**Pull request merged**
