### PR TITLE
Log events when user views campaign preview and create/updates campaign

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes https://github.com/sourcegraph/sourcegraph/issues/15482 and is the client-side portion of it. The backend portion is in https://github.com/sourcegraph/sourcegraph/pull/15279.

@dadlerj @ebrodymoore Since this only logs events I wasn't sure about how to document this, but I added it to the ping-data pages.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
The TypeScript phoenix arose from its ash!

**Comment by dadlerj** [comment]
Event logging alone does _not_ need to be listed on the pings page! Events are all logged locally, inside of the self-hosted instance, and are not sent off-site. The pings page is only about data that is sent off-site (in pings). So if we eventually start sending aggregates of this data back, then (and only then) we would have to add it.

**Review by eseliger — APPROVED** [review]
LGTM

**Comment by mrnugget** [comment]
> Event logging alone does _not_ need to be listed on the pings page! Events are all logged locally, inside of the self-hosted instance, and are not sent off-site. The pings page is only about data that is sent off-site (in pings). So if we eventually start sending aggregates of this data back, then (and only then) we would have to add it.

Ah, thank you! I'll remove the mention then.

But it seems like I misunderstood the original ticket (https://github.com/sourcegraph/sourcegraph/issues/15482) and I need to also query and include these events in https://github.com/sourcegraph/sourcegraph/pull/15279

**Review by chrispine — COMMENTED** [review]
👍

**Pull request merged**
