### PR TITLE
Fix(search): auth issues with Sourcegraph VSCode extension

### LINKED ISSUE #60710: VSCode Search plugin error when using 5.3.0 instance
- **Sourcegraph version:**  5.3.0
- **Plugin version:** v2.2.16
- **Platform information:** 
macOS 14.1

#### Steps to reproduce:

1. Install latest version of VSCode Code Search plugin ([link](https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph)) 
2. Open extension and click "Have an Account?"
3. Enter instance URL and access token
4. See error:
```
Unable to verify your access token for sourcegraph.com. Please try again with a new access token or restart VS Code if the instance URL has been updated.

```

#### Expected behavior:
Extension should authenticate and allow user to search

#### Actual behavior:
Error is thrown and cannot authenticate

#### Additional information:
Looking at the request sent to the instance it contains the following GraphQL query:

```
query CurrentAuthState {
  currentUser {
    __typename
    id
    databaseID
    username
    avatarURL
    email
    displayName
    siteAdmin
    url
    settingsURL
    organizations {
      nodes {
        id
        name
        displayName
        url
        settingsURL
      }
    }
    session {
      canSignOut
    }
    viewerCanAdminister
    tosAccepted
    searchable
    emails {
      email
      verified
    }
  }
}
```

which returns an empty string on 5.3.0 but not on previous versions. This is due to a change in 5.3.0 where we dropped `searchable` DB column ([link](https://github.com/sourcegraph/sourcegraph/pull/60429)).

#### Screenshots

Screenshot 2024-02-22 at 15 10 56

Screenshot 2024-02-22 at 15 14 55

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

### PR DESCRIPTION
**Pull request by peterguy**
Fixes the issues requiring the workaround described in [this video](https://www.loom.com/share/10a4a66a19b548c7b0866fe2cc358daa).

Closes #60710 

No more manual editing of `settings.json`.

The endpoint URL and access code can now all be managed from the UI

### First
Build and run locally.
```
git switch peterguy/vscode-sourcegraph-extension-fix-auth
cd client/vscode
pnpm run build
```
### Then
Launch extension in VSCode: open the `Run and Debug` sidebar view in VS Code, then select `Launch VS Code Extension` from the dropdown menu.
Click on `Have an account?` to open the login dialog.
Enter an access token and the URL of the Sourcegraph instance to which you would like to connect.
Click `Authenticate account`.
In the Help and Feedback section, click your username to open the logout panel, then log out.
Repeat the login process.
You can check `settings.json` if you'd like to confirm that it's no longer being used.
If you're logging in to dotcom, you'll probably se a SQL error. The login process still works; the SQL error does not have long to live.

## Changelog

- Entering the URL and access token in the UI now works - no more manual editing of `settings.json`

### CODE REVIEW

**Comment by peterguy** [comment]
Tagging @sourcegraph/security-code-review (@shivasurya) for a review, because this involves managing an access token.

The original code had a listener that reloaded the extension if the endpoint URL in `settings.json` changed in order, "to prevent data 'contamination' (e.g. sending private repo names to Cloud instance)." Now that the endpoint URL and access token are managed in the UI only, that reload ~is not~ should not be necessary; I would appreciate another set of eyes to confirm that.

Also, is it possible to meddle with the extension's `globalState` storage? If so, we should add more safeguards to prevent "data 'contamination'".

**Review by evict — APPROVED** [review]

**Comment by evict** [comment]
> Also, is it possible to meddle with the extension's globalState storage? If so, we should add more safeguards to prevent "data 'contamination'".

That should be private to the extension only.
🔒

**Comment by camdencheek** [comment]
I tried this out locally, but was unable to get it to work. I attempted to log in with S2 with an access token I just created, but got the following error:

screenshot-2024-06-11_10-48-54@2x

After the error, the Sourcegraph panel has no option to try to log in again and when I try to run a search, I get 401 Unauthorized errors:

```Failed to get instance version from host: HTTPStatusError: Request to https://sourcegraph.sourcegraph.com/.api/graphql?SiteProductVersion failed with 401 Unauthorized
	at checkOk (/Users/camdencheek/src/sourcegraph/sourcegraph/client/http-client/src/http-status-error.ts:39:15)
	at requestGraphQLFromVSCode (/Users/camdencheek/src/sourcegraph/sourcegraph/client/vscode/src/backend/requestGraphQl.ts:47:26)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {name: 'HTTPStatusError', status: 401, stack: 'HTTPStatusError: Request to https://sourcegra…ions (node:internal/process/task_queues:95:5)', message: 'Request to https://sourcegraph.sourcegraph.c…eProductVersion failed with 401 Unauthorized'}
```

Anything else I should try to collect?

**Comment by peterguy** [comment]
@camdencheek Make sure you're switching to the feature branch `peterguy/vscode-sourcegraph-extension-fix-auth` before testing.

Here's a walkthrough of how I test login.

https://github.com/sourcegraph/sourcegraph/assets/129280/579b8503-085d-4e9d-88f5-c9815f95fb77

**Comment by camdencheek** [comment]
Aah, I think I missed the `pnpm build` step. I was thinking the "run and debug extension" did that. Anyways after going through the steps in the video, it works great! Thanks Peter!

**Review by camdencheek — APPROVED** [review]

**Comment by peterguy** [comment]
> I was thinking the "run and debug extension" did that
The README for the extension does say to use either `pnpm run build` OR "run and debug", but I've found I need to do both. I haven't updated the README yet. :-D

**Pull request merged**
