### PR TITLE
gitserver: use cat-file for reading blobs containing ..

### PR DESCRIPTION
**Pull request by keegancsmith**
We special case ".." in path to running a less efficient two commands. For other paths we can rely on the faster git show.

git show will try and resolve revisions on anything containing "..". Depending on what branches/files exist, this can lead to:

- error: object $SHA is a tree, not a commit
- fatal: Invalid symmetric difference expression $SHA:$name
- outputting a diff instead of the file

The last point is a security issue for repositories with sub-repo permissions since the diff will not be filtered.

Test Plan: wrote tests and test e2e

### CODE REVIEW

**Comment by keegancsmith** [comment]
I cleaned up this PR and added tests. I'd like to land this today to backport it to the patch release we are cutting today given this will fix an issue at a customer.

**Review by sashaostrikov — APPROVED** [review]
Thanks for finding and fixing this! 🙏🏻

**Review by evict — APPROVED** [review]

**Review by kopancek — APPROVED** [review]
:shipit:

**Comment by keegancsmith** [comment]
Running into the test failing on CI but not locally. I am guessing this is a difference between my local git and what is running on CI. After digging into the git history it seems this is actually a bug in `git ls-tree` that was fixed. https://lore.kernel.org/git/211115.86o86lqe3c.gmgdl@evledraar.gmail.com/

I'll see if I can find a more reliable way to lookup the blob OID of a path.

**Pull request merged**
