### PR TITLE
schema: Use go embed instead of stringdata tool

### PR DESCRIPTION
**Pull request by ryanslade**

### CODE REVIEW

**Comment by ryanslade** [comment]
@keegancsmith @eseliger  Any reason we didn't already do this? I saw you guys doing a lot of embed changes recently.

If not, I'll do the others between meetings later today.

**Comment by eseliger** [comment]
No reason I just wasn't sure how the generation of the Schema struct is affected by this

**Comment by ryanslade** [comment]
That felt good!

**Review by eseliger — APPROVED** [review]
Nice! 🙏

**Review by unknwon — COMMENTED** [review]
Cool!!!

**Pull request merged**
