### PR TITLE
sveltekit-prototype: Add separator component and setup storybook

### PR DESCRIPTION
**Pull request by fkling**
This commit adds a simple separator component to be used for resizing
panels (e.g. sidebars) and is used on file tree pages. The way the 
separator works is quite simple atm: It computes its position in relation
to the size of the parent element and saves that value in the provided store.
The parent component can use this value however it sees fit.
The current value is persisted in local storage.
I assume that this functionality will be expanded or changed in the future
but it's a start.

I also setup storybook 7, following the default setup instructions. I
left everybody as default except for deleting the example stories it
came with. We can always change the structure later.
Initially I wasn't able to run `pnpm run storybook`, it was throwing an
error about not being able to import `ts-dedent`. Adding it to the root
`package.json` file seems to resolve this issue.

Repo page: 

https://github.com/sourcegraph/sourcegraph/assets/179026/fb6ba082-8959-47ed-b2ae-8e1aa351b64c

Storybook: 

## Test plan

Open repo page and use separator.

Run storybooks with `pnpm run storybooks`

Run existing storybooks in the workspace roots. It's not impacted by adding a new version.

### CODE REVIEW

**Review by vovakulikov — APPROVED** [review]
I'm a bit of scared by `parentElement` reading but I don't have anything better in svelte world API, I think later for the history and reference panel we will need to extend separator with vertical mode but it should be 5 minute change. I was afraid that getBoundingClientRect doesn't catch the screen zoom level but tested it in all major browsers and all works as it should. Overall, nice component!

**Comment by fkling** [comment]
@vovakulikov 

> I'm a bit of scared by `parentElement` reading

Why? Only because it's not common in the React world to access the DOM or for other reasons?

> I was afraid that getBoundingClientRect doesn't catch the screen zoom level but tested it in all major browsers and all works as it should

Ah good thinking, I haven't thought about that. I'm sure the logic can be improved. It doesn't work well either if the left pane has margin set, but I guess that can be avoided.

And yes, I assume we'll extend/improve it.

**Comment by vovakulikov** [comment]
> Why? Only because it's not common in the React world to access the DOM or for other reasons?

not only because of this, I can imagine when the container itself has additional nested layouts within root container 
in which we want to have resizable panel, (this might be needed sometimes for some visual tweaks), in this case 
assumption that the parent element is a root element is wrong and we would have to call something like .parentElement.parentElement to get the right width/height value. Or we could pass the root element as prop to avoid 
this problem with parent.parent but this would require additional prop in the Separator component (might be complicated 
to use it in this case). 

In react I think I would create pass root component internally through context, so the Separator would require parent element  explicitly.

**Comment by fkling** [comment]
Good points. I wanted to keep it as simple as possible for now. We can always deal with the more complicated setups later.

>  Or we could pass the root element as prop to avoid
this problem with parent.parent but this would require additional prop in the Separator component (might be complicated to use it in this case).

I actually thought about the same, I think that would be easy to do.

> In react I think I would create pass root component internally through context, so the Separator would require parent element explicitly.

We could do that too.

**Pull request merged**
