### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by jhgilbert**
I was coming up to speed on Sourcegraph and caught some typos in the docs. I only fixed the obvious ones -- not looking to take up a lot of anyone's time with style/grammar battles.

## Test plan

- All changes except one are in Markdown files, so I just made sure they rendered properly where relevant.
- One change is to an error message, so I did a quick search to make sure no tests depend on the literal misspelled verbiage.

### CODE REVIEW

**Comment by jhgilbert** [comment]
@sourcegraph/contribution-reviewers I've signed the CLA. Thanks!

**Comment by jhgilbert** [comment]
@iskyOS and @ryphil, just wanted to flag this one for you. I kept it as noncontroversial as I could for an easy win. It was great meeting you today!

**Review by ryphil — APPROVED** [review]

**Comment by jdorfman** [comment]
@cla-bot

**Comment by jdorfman** [comment]
@cla-bot check

**Comment by jdorfman** [comment]
@jhgilbert looking into this

**Comment by jdorfman** [comment]
@jhgilbert sorry for the delay! We would love to hook you up with some Sourcegraph swag. Please email me if interested: community@sourcegraph.com

**Pull request merged**
