### PR TITLE
Backport notification fix to version 3.33

### PR DESCRIPTION
**Pull request by camdencheek**
This backports the fixes we made to saved search and code monitor notifications onto version 3.33.
Patch release request [here](https://github.com/sourcegraph/sourcegraph/issues/27999). I didn't realize
we had release branches, which is why I didn't make this until now 😄

### CODE REVIEW

**Review by tsenart — APPROVED** [review]

**Review by eseliger — APPROVED** [review]
LGTM, did you run the migration a couple of times in a row to validate it won't crash on a subsequent startup?

**Comment by camdencheek** [comment]
Yes. However, you just reminded me that I should test upgrading from v3.33.1 to v3.34.0, and I seem to be getting a migration failure there. Looking into it before merging this.

**Comment by camdencheek** [comment]
_sigh_
```

error: 2 errors occurred:
        * migration failed in line 0: BEGIN;

UPDATE saved_searches
SET (notify_owner, notify_slack) = (false, false);

ALTER TABLE saved_searches
        ADD CONSTRAINT saved_searches_notifications_disabled CHECK (
                notify_owner = false
                AND notify_slack = false
        );

ALTER TABLE IF EXISTS saved_searches
        ALTER COLUMN user_id DROP NOT NULL;

COMMIT;
 (details: ERROR: constraint "saved_searches_notifications_disabled" for relation "saved_searches" already exists (SQLSTATE 42710))
        * ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02) in line 0: SELECT pg_advisory_unlock($1)
```

**Comment by camdencheek** [comment]
It's too late to fix the migrations in v3.34, so I've pushed another commit that renames the constraints. These constraints will not be removed on upgrade to v3.34, but I think that's okay since they shouldn't affect anything because they just constrain removed features. We can add a new migration that deletes these migrations in a future release so they're eventually cleaned up.

**Comment by camdencheek** [comment]
> Won't this make us have two constraints that do the same thing? Not sure I follow why you got those errors if we drop the constraint before re-creating it.

Yes, it will for users that upgrade from v3.33.1 to v3.34.0. We only drop the constraint before recreating it in v3.33.1. The migration that made it into v3.34.0 does not drop the constraint before creating it, so that migration fails when we upgrade from a v3.33.1 instance that has applied this patch.

**Comment by tsenart** [comment]
> Does this sound reasonable to you two @tsenart @eseliger?

SGTM.

**Pull request merged**
