### PR TITLE
search: clicking a search suggestion no longer appends filters

### PR DESCRIPTION
**Pull request by limitedmage**
Search suggestions already come with all the existing filters added, so there is no need to add them to the URL when generating the link.

Also fixes a small bug that caused filters to not be toggled properly (eg. after clicking on "lang:c++" and then on "lang:c", the result would be "++" instead of "lang:c++ lang:c". Gif of this bug:

Screen Recording 2020-08-05 at 8 41 28 AM 2

### CODE REVIEW

**Comment by attfarhan** [comment]
Looks good to me so far!

**Comment by attfarhan** [comment]
> Also fixes a small bug that caused filters to not be toggled properly
Can you provide repro steps for this? I don't think I know what the bug is.

Once you mark the PR as ready for review, CI will run and it'll run all our tests, and you'll be able to see if there are any failures. If you want to run frontend unit tests locally, you can run `yarn run test` and `yarn run test-e2e` (for end to end tests).

If you want to add tests for this, it might make sense to add an end to end test.

**Comment by felixfbecker** [comment]
@attfarhan is there a reason you'd recommend an e2e test over an [integration test](https://docs.sourcegraph.com/dev/testing#client-integration-tests)? Seems like this does not need to  involve the backend :)

**Comment by limitedmage** [comment]
@attfarhan I added a Gif recording of the other small bug I found. I've published the review so CI runs and will add integration tests.

**Comment by attfarhan** [comment]
Oops sorry mixed up the terms, integration tests make sense.

**Pull request merged**
