### PR TITLE
licensing: always allow promoting site admin for SOAP users

### PR DESCRIPTION
**Pull request by unknwon**
We aren't able to fix the expired license issue for a MI without being a site admin but also aren't able to be automatically promoted to be site admin with an expired license on the MI 😂 

## Test plan

CI

### CODE REVIEW

**Review by rafax — APPROVED** [review]

**Review by filiphaftek — APPROVED** [review]

**Review by mrnugget — APPROVED** [review]
Curious what @pjlast and @kopancek have to say, but LGTM

**Review by kopancek — COMMENTED** [review]
I would love to have more context on why this is needed.

I was of the impression that every sourcegraph operator was automatically made a site-admin as well.

**Comment by unknwon** [comment]
>I was of the impression that every sourcegraph operator was automatically made a site-admin as well.

It is, which is why it is currently failing because the `SetIsSiteAdmin` (that invokes this hook) is used to "automatically" make every sourcegraph operator a site admin 😂

**Comment by kopancek** [comment]
> > I was of the impression that every sourcegraph operator was automatically made a site-admin as well.
> 
> It is, which is why it is currently failing because the `SetIsSiteAdmin` (that invokes this hook) is used to "automatically" make every sourcegraph operator a site admin 😂

Then I think a better approach would be to create the user as a site admin from the get go, instead of calling `SetIsSiteAdmin` 🤔

**Comment by unknwon** [comment]
> > > I was of the impression that every sourcegraph operator was automatically made a site-admin as well.
> > 
> > 
> > It is, which is why it is currently failing because the `SetIsSiteAdmin` (that invokes this hook) is used to "automatically" make every sourcegraph operator a site admin 😂
> 
> Then I think a better approach would be to create the user as a site admin from the get go, instead of calling `SetIsSiteAdmin` after the user is created 🤔

Using `SetIsSiteAdmin` is idempotent while set site admin during user creation is not, there could be cases when the Sourcegraph operator was also a regular user (due to email matching) and we need to make sure if a user logs in as a Sourcegraph operator, the user always become a site admin.

**Review by pjlast — APPROVED** [review]

**Review by daxmc99 — APPROVED** [review]

**Review by bobheadxi — APPROVED** [review]

**Comment by unknwon** [comment]
Merging as-is, happy to address post-merge feedback!

**Pull request merged**
