### PR TITLE
opentelemetry-collector: build custom collector with gcloudexporter

### PR DESCRIPTION
**Pull request by bobheadxi**
Supercedes #39257 , part of #39174 

This is required to not pull in a _massive_ amount of dependencies to include the gcloud exporter.

## Test plan

```
docker-images/opentelemetry-collector/build.sh
```

### CODE REVIEW

**Comment by bobheadxi** [comment]
cc'ing some reviewers as an FYI, I am heading OOO until Monday

**Comment by bobheadxi** [comment]
Current issues: 

```
docker run --rm --name=otel-collector sourcegraph/opentelemetry-collector:dev --config "/etc/otel-collector/configs/jaeger.yaml"
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/otelcol-sourcegraph: no such file or directory
```

**Comment by jhchabran** [comment]
It boots properly now: 

```
docker run --platform linux/amd64 --rm --name=otel-collector sourcegraph/opentelemetry-collector --config "/etc/otel-collector/configs/jaeger.yaml"
2022-07-23T16:42:03.374Z	info	service/telemetry.go:107	Setting up own telemetry...
2022-07-23T16:42:03.394Z	info	service/telemetry.go:146	Serving Prometheus metrics	{"address": ":8888", "level": "basic"}
2022-07-23T16:42:03.395Z	info	extensions/extensions.go:42	Starting extensions...
2022-07-23T16:42:03.395Z	info	extensions/extensions.go:45	Extension is starting...	{"kind": "extension", "name": "health_check"}
2022-07-23T16:42:03.396Z	info	healthcheckextension@v0.54.0/healthcheckextension.go:44	Starting health_check extension	{"config": {"Port":13133,"TCPAddr":{"Endpoint":"0.0.0.0:13133"},"Path":"/","CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2022-07-23T16:42:03.399Z	warn	healthcheckextension@v0.54.0/healthcheckextension.go:52	`Port` is deprecated, use `Endpoint` instead
2022-07-23T16:42:03.401Z	info	extensions/extensions.go:49	Extension started.	{"kind": "extension", "name": "health_check"}
2022-07-23T16:42:03.401Z	info	extensions/extensions.go:45	Extension is starting...	{"kind": "extension", "name": "zpages"}
2022-07-23T16:42:03.402Z	info	zpagesextension/zpagesextension.go:64	Registered zPages span processor on tracer provider
2022-07-23T16:42:03.403Z	info	zpagesextension/zpagesextension.go:74	Registered Host's zPages
2022-07-23T16:42:03.411Z	info	zpagesextension/zpagesextension.go:86	Starting zPages extension	{"config": {"TCPAddr":{"Endpoint":"localhost:55679"}}}
2022-07-23T16:42:03.412Z	info	extensions/extensions.go:49	Extension started.	{"kind": "extension", "name": "zpages"}
2022-07-23T16:42:03.412Z	info	pipelines/pipelines.go:74	Starting exporters...
2022-07-23T16:42:03.412Z	info	pipelines/pipelines.go:78	Exporter is starting...	{"kind": "exporter", "data_type": "traces", "name": "jaeger"}
2022-07-23T16:42:03.422Z	info	pipelines/pipelines.go:82	Exporter started.	{"kind": "exporter", "data_type": "traces", "name": "jaeger"}
2022-07-23T16:42:03.422Z	info	pipelines/pipelines.go:86	Starting processors...
2022-07-23T16:42:03.423Z	info	pipelines/pipelines.go:98	Starting receivers...
2022-07-23T16:42:03.423Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2022-07-23T16:42:03.424Z	info	jaegerexporter@v0.54.0/exporter.go:186	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "IDLE"}
2022-07-23T16:42:03.428Z	info	otlpreceiver/otlp.go:70	Starting GRPC server on endpoint 0.0.0.0:4317	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2022-07-23T16:42:03.429Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2022-07-23T16:42:03.430Z	info	healthcheck/handler.go:129	Health Check state change	{"status": "ready"}
2022-07-23T16:42:03.431Z	info	service/collector.go:220	Starting otelcol-sourcegraph...	{"Version": "1.0.0", "NumCPU": 5}
2022-07-23T16:42:03.431Z	info	service/collector.go:128	Everything is ready. Begin running and processing data.
2022-07-23T16:42:03.434Z	warn	zapgrpc/zapgrpc.go:191	[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
  "Addr": ":14250",
  "ServerName": "localhost:14250",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp :14250: connect: connection refused"	{"grpc_log": true}
2022-07-23T16:42:04.431Z	info	jaegerexporter@v0.54.0/exporter.go:186	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "TRANSIENT_FAILURE"}
2022-07-23T16:42:05.429Z	info	jaegerexporter@v0.54.0/exporter.go:186	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "IDLE"}
^C2022-07-23T16:42:12.400Z	info	service/collector.go:159	Received signal from OS	{"signal": "interrupt"}
2022-07-23T16:42:12.401Z	info	service/collector.go:236	Starting shutdown...
2022-07-23T16:42:12.402Z	info	healthcheck/handler.go:129	Health Check state change	{"status": "unavailable"}
2022-07-23T16:42:12.402Z	info	pipelines/pipelines.go:118	Stopping receivers...
2022-07-23T16:42:12.405Z	info	pipelines/pipelines.go:125	Stopping processors...
2022-07-23T16:42:12.406Z	info	pipelines/pipelines.go:132	Stopping exporters...
2022-07-23T16:42:12.408Z	info	extensions/extensions.go:56	Stopping extensions...
```

**Comment by bobheadxi** [comment]
Thanks @jhchabran !

**Comment by bobheadxi** [comment]
Was able to get the server up and running and sending data to Honeycomb:

image

**Comment by bobheadxi** [comment]
The scan passed in CI, and I also did a manual scan just in case, with https://github.com/sourcegraph/sourcegraph/pull/39396 :

```
trivy image --severity "HIGH,CRITICAL" us.gcr.io/sourcegraph-dev/opentelemetry-collector:9eceedc366be65efade620c5551b5ca190da0314_163109_candidate
2022-07-25T21:31:37.803-0400    INFO    Need to update DB
2022-07-25T21:31:37.803-0400    INFO    DB Repository: ghcr.io/aquasecurity/trivy-db
2022-07-25T21:31:37.803-0400    INFO    Downloading DB...
33.22 MiB / 33.22 MiB [----------------------------------------------------------------------------------------------------------------------------] 100.00% 13.85 MiB p/s 2.6s
2022-07-25T21:31:41.121-0400    INFO    Vulnerability scanning is enabled
2022-07-25T21:31:41.121-0400    INFO    Secret scanning is enabled
2022-07-25T21:31:41.121-0400    INFO    If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-25T21:31:41.121-0400    INFO    Please see also https://aquasecurity.github.io/trivy/0.30.3/docs/secret/scanning/#recommendation for faster secret detection
2022-07-25T21:31:44.288-0400    INFO    Detected OS: alpine
2022-07-25T21:31:44.288-0400    INFO    Detecting Alpine vulnerabilities...
2022-07-25T21:31:44.289-0400    INFO    Number of language-specific files: 1
2022-07-25T21:31:44.289-0400    INFO    Detecting gobinary vulnerabilities...

us.gcr.io/sourcegraph-dev/opentelemetry-collector:9eceedc366be65efade620c5551b5ca190da0314_163109_candidate (alpine 3.14.6)

Total: 0 (HIGH: 0, CRITICAL: 0)
```

**Review by jhchabran — APPROVED** [review]
Otel, here we come 🚀 🌔

**Pull request merged**
