### PR TITLE
Add indexing to RepoListOptions

### PR DESCRIPTION
**Pull request by cbart**
This pull request adds in two extra `ReposListOptions`:

- `NoIndexed` that excludes zoekt-indexed repos from the list
- `OnlyIndexed` that excludes not-zoekt-indexed repos from the list

The behavior is similar to corresponding `NoCloned` and `OnlyCloned`. The implementation takes advantage of `zoekt_repos` table which refers to zoekt-indexed repos.

@mrnugget let me know if I'm thinking right in terms of using `LEFT JOIN` as well as `COALESCE(index_status,...)`. The way I interpreted `ZoektRepos()` and the associated [handler](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c59b95a9003a12269c75f2041cef37d7bcb1609b/-/blob/cmd/frontend/internal/httpapi/search.go?L331-356) was that we are going to get rows with `indexed` status only. Or is there a code path that I missed that inserts every repo (within `repos` table) in to `zoekt_repos` table (with the default `not_indexed` value)?

## Test plan

Extend the repo_test.go with checking against an indexed and unindexed repository.

### CODE REVIEW

**Comment by mrnugget** [comment]
> Or is there a code path that I missed that inserts every repo (within `repos` table) in to `zoekt_repos` table (with the default `not_indexed` value)?

We have a database trigger for that, yes :) Take a look at `"public.repo"`'s triggers here: https://github.com/sourcegraph/sourcegraph/blob/3033610b103e82904dfa7eabd33e1494c8520d3a/internal/database/schema.md#table-publicrepo

**Review by mrnugget — APPROVED** [review]
Very nice! Love the tests. Approving to unblock you, but I think we can remove the `LEFT JOIN` and `COALESCE`. Feel free to merge after fixing that.

**Review by eseliger — COMMENTED** [review]
Can we see a query plan from the dotcom DB for this? Wonder if we need any index to make this performant

**Comment by cbart** [comment]
@eseliger Thanks for the comment and for the advice given offline. Here's the `psql` output:

```
EXPLAIN ANALYZE SELECT repo.id,repo.name,repo.private,repo.external_id,repo.external_service_type,repo.external_service_id,repo.uri,repo.description,repo.fork,repo.archived,repo.stars,repo.created_at,repo.updated_at,repo.deleted_at,repo.metadata,repo.blocked,(SELECT json_object_agg(key, value) FROM repo_kvps WHERE repo_kvps.repo_id = repo.id),
(
        SELECT
                json_agg(
                json_build_object(
                        'CloneURL', esr.clone_url,
                        'ID', esr.external_service_id,
                        'Kind', LOWER(svcs.kind)
                )
                )
        FROM external_service_repos AS esr
        JOIN external_services AS svcs ON esr.external_service_id = svcs.id
        WHERE
                esr.repo_id = repo.id
                AND
                svcs.deleted_at IS NULL
)

FROM repo
JOIN zoekt_repos zr ON zr.repo_id = repo.id
WHERE
        repo.deleted_at IS NULL AND repo.blocked IS NULL AND (zr.index_status = 'not_indexed'
 AND  zr.index_status = 'indexed')   -- Populates "queryConds"
        AND
        (
(
    -- Bypass authz
    TRUE
)
) -- Populates "authzConds"
ORDER BY id        -- Populates "querySuffix"
;
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                       QUERY PLAN                                                                                       │
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ Sort  (cost=0.01..0.02 rows=0 width=692) (actual time=0.008..0.008 rows=0 loops=1)                                                                                                     │
│   Sort Key: id                                                                                                                                                                         │
│   Sort Method: quicksort  Memory: 25kB                                                                                                                                                 │
│   ->  Result  (cost=0.00..0.00 rows=0 width=692) (actual time=0.001..0.001 rows=0 loops=1)                                                                                             │
│         One-Time Filter: false                                                                                                                                                         │
│         SubPlan 1                                                                                                                                                                      │
│           ->  Aggregate  (cost=1.70..1.71 rows=1 width=32) (never executed)                                                                                                            │
│                 ->  Index Only Scan using repo_kvps_pkey on repo_kvps  (cost=0.43..1.67 rows=8 width=42) (never executed)                                                              │
│                       Index Cond: (repo_id = id)                                                                                                                                       │
│                       Heap Fetches: 0                                                                                                                                                  │
│         SubPlan 2                                                                                                                                                                      │
│           ->  Aggregate  (cost=8.63..8.64 rows=1 width=32) (never executed)                                                                                                            │
│                 ->  Nested Loop  (cost=5.24..8.62 rows=1 width=58) (never executed)                                                                                                    │
│                       ->  Index Scan using external_service_repos_repo_id_external_service_id_unique on external_service_repos esr  (cost=0.43..2.65 rows=1 width=51) (never executed) │
│                             Index Cond: (repo_id = id)                                                                                                                                 │
│                       ->  Bitmap Heap Scan on external_services svcs  (cost=4.81..5.92 rows=1 width=15) (never executed)                                                               │
│                             Recheck Cond: (id = esr.external_service_id)                                                                                                               │
│                             Filter: (deleted_at IS NULL)                                                                                                                               │
│                             ->  Bitmap Index Scan on external_services_pkey  (cost=0.00..4.81 rows=1 width=0) (never executed)                                                         │
│                                   Index Cond: (id = esr.external_service_id)                                                                                                           │
│ Planning Time: 0.893 ms                                                                                                                                                                │
│ Execution Time: 0.090 ms                                                                                                                                                               │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(22 rows)
Time: 84.976 ms
```

**Pull request merged**
