### PR TITLE
codeintel: Add fast-path edge unmarshalling

### PR DESCRIPTION
**Pull request by efritz**
For LSIF inputs with integer identifiers, it's much faster to deserialize them directly into structs via json.Unmarshal rather than try to unmarshal them into byte slices and do it by hand (which is what the interner does).

### CODE REVIEW

**Comment by aidaeology** [comment]
Please add tests for any unmarshalEdgeFast()

**Comment by efritz** [comment]
It's already covered by existing tests, specifically `TestUnmarshalEdgeNumericIDs`.

**Comment by efritz** [comment]
@aidaeology I don't feel like this is debt, it's just an enhancement.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Pull request merged**
