### PR TITLE
Bump go.mod to pickup Zoekt fix

### PR DESCRIPTION
**Pull request by daxmc99**

### CODE REVIEW

**Comment by slimsag** [comment]
On mobile so I can’t link, but there is a script in the dev folder you want to use to do this. Updating the go.mod alone is not enough

**Comment by slimsag** [comment]
dev/update-zoekt-something*

**Comment by daxmc99** [comment]
Thanks! I will make sure to run that. I think this PR was made in error on my part. This is the 3.18 branch and SHOULD NOT be merged into master

**Comment by daxmc99** [comment]
@slimsag After running the script I didn't see any diff produced. I believe what I did manually had the same result.

**Comment by slimsag** [comment]
got it - makes sense - this is the script I was speaking of: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/zoekt/update

You should be good then! :)

**Comment by daxmc99** [comment]
This PR was opened by accident. Closing

**Pull request closed without merging**
