### PR TITLE
replace amazon logo with reddit logo

### PR DESCRIPTION
**Pull request by BolajiOlajide**
## Test plan

Ensure everything works fine.

## App preview:

- [Web](https://sg-web-bo-add-reddit-icon.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-mfszraevsl.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]

**Comment by limitedmage** [comment]
To confirm: we are replacing the Amazon logo with the Reddit logo?

**Comment by BolajiOlajide** [comment]
> To confirm: we are replacing the Amazon logo with the Reddit logo?

Yes that's correct. For context, you can view the request [here.](https://sourcegraph.slack.com/archives/C07KZF47K/p1661884527823739)

**Comment by unknwon** [comment]
> To confirm: we are replacing the Amazon logo with the Reddit logo?

I have the same confusion with the PR title ... 😂 Suggested "replace amazon logo with reddit logo".

**Review by unknwon — APPROVED** [review]

**Comment by BolajiOlajide** [comment]
> > To confirm: we are replacing the Amazon logo with the Reddit logo?
> 
> I have the same confusion with the PR title ... 😂 Suggesting "replace amazon logo with reddit logo".

My bad. That was a mistake. Thanks for pointing it out Joe.

**Pull request merged**
