### PR TITLE
Replace fmt.Sprintf with equivalent strconv.Itoa

### PR DESCRIPTION
**Pull request by mrnugget**
This campaign replaces `fmt.Sprintf` with `strconv.Itoa`

### CODE REVIEW

**Review by asdine — APPROVED** [review]

**Review by LawnGnome — CHANGES_REQUESTED** [review]
+1 for the idea, but it looks like there's some `import` blocks to be cleaned up before this can be merged.

**Comment by keegancsmith** [comment]
Maybe you need a goimports step in your campaign?

**Comment by mrnugget** [comment]
> Maybe you need a goimports step in your campaign?

Yep, I'm on it :)

**Comment by mrnugget** [comment]
Due to a bug (on it), campaigns didn't pick up and re-open the closed changeset here, so we have a new one: https://github.com/sourcegraph/sourcegraph/pull/13811

**Pull request closed without merging**
