### PR TITLE
ci: upload lsif-go dump to S2

### PR DESCRIPTION
**Pull request by unknwon**
## Test plan

n/a

### CODE REVIEW

**Review by ryanslade — APPROVED** [review]

**Comment by michaellzc** [comment]
we already have auto indexing enabled for `sg/sg` on `s2` https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-graph/indexes

is this still necessary?

**Comment by Strum355** [comment]
> we already have auto indexing enabled for `sg/sg` on `s2` [sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-graph/indexes](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-graph/indexes)
> 
> is this still necessary?
> 
> (we are also going to increase the auto indexing interval from the default `24h` to `1h` soon)

Personally I hold the opinion that doing uploads ourselves should be the preferred method (both for ourselves and for customers), it would generally be the most up-to-date (when a PR is opened, when a PR is merged, on new commits to a PR), which would be the most optimal for consumers (reviewers, PR author etc).

**Comment by unknwon** [comment]
> we already have auto indexing enabled for `sg/sg` on `s2` https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-graph/indexes
> 
> is this still necessary?
> 
> (we are also going to increase the auto indexing interval from the default `24h` to `1h` soon)

I think I couldn't see any code-intel popover in any PRs when configured my browser extension to s2, so yeah similar thinking as @Strum355 mentioned.

**Comment by michaellzc** [comment]
> > we already have auto indexing enabled for `sg/sg` on `s2` [sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-graph/indexes](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-graph/indexes)
> > is this still necessary?
> > (we are also going to increase the auto indexing interval from the default `24h` to `1h` soon)
> 
> Personally I hold the opinion that doing uploads ourselves should be the preferred method (both for ourselves and for customers), it would generally be the most up-to-date (when a PR is opened, when a PR is merged, on new commits to a PR), which would be the most optimal for consumers (reviewers, PR author etc).

(not blocking this PR, but just sharing my thoughts)

> doing uploads ourselves should be the preferred method (both for ourselves and for customers

I understand we want to see precise search results even on PR branches

On Cloud (MI), we just made auto-indexing generally available to all users, and yet we ourself still opt to use CI to upload indexes because we want more coverage.

I brought up similar questions a while ago https://sourcegraph.slack.com/archives/CHXHX7XAS/p1657033725832799, where auto-indexing only functions on a fixed schedule (default to `24h`). Related issue: https://github.com/sourcegraph/sourcegraph/issues/38230

If we are not satisfied with what auto-indexing deliver, unable to index stuff on demand or based on events omitted by code host. I would imagine customers could be facing similar frustration as well. Is there any plan to prioritize this feature? Is there a product gap logged yet?

cc @RafLeszczynski @sourcegraph/cloud

**Comment by unknwon** [comment]
> If we are not satisfied with what auto-indexing can deliver, unable to index stuff on demand or based on events omitted by code host (e.g. trigger a new index job when there's a `pull_reqest:open` webhook event). I would imagine customers could be facing similar frustration as well. Is there any plan to prioritize this feature? Is there a product gap logged yet?

Totally up for some on-demand mechanism for auto-indexing.

Though if we think one step back, what's the value proposition we give to users? Is auto-indexing just provides less value for GitHub repos because we would be doing exact same thing that GitHub Actions offer? (i.e. we provide much more value for code hosts that don't have a native CI)

**Comment by Strum355** [comment]
> On Cloud (MI), we just made auto-indexing generally available to all users, and yet we ourself still opt to use CI to upload indexes because we want more coverage.

correct, however I wouldnt look at autoindexing as existing to replace uploading from CI, but rather to complement it. Its initial raison d'etre was to increase coverage of precise code-intel on dotcom and for enterprise for cases where customers didnt want to or couldnt setup indexing in CI for various reasons such as overhead to CI pipelines, not high enough priority, not code they actually own themselves (this is the case on s2 already, where we've added external repos to our instance, and compounded by package repos). 
By providing low(er) effort pathways to precise code-intel, the goal is to encourage more active and wider adoption of precise code-intel, better customer retention and growth through seeing the value in precise code-intel, which they may otherwise not experience due to above reasons. 

> Is there any plan to prioritize this feature? Is there a product gap logged yet?

I dont think its currently prioritized or any other status of it, we're getting quite people-constrained between database migrator work, other cloud efforts, and a number of upcoming paternity leaves :sweat: cc @macraig we'll be able to focus more on these things once 4.0 has rolled around

**Comment by eseliger** [comment]
Logging a feature gap should always be an option even if we have 0 engineers right now :)

**Comment by macraig** [comment]
Hi all, thanks for the feedback! I've created a product gap that contains https://github.com/sourcegraph/sourcegraph/issues/38230.

**Comment by michaellzc** [comment]
> I wouldnt look at autoindexing as existing to replace uploading from CI, but rather to complement it
> By providing low(er) effort pathways to precise code-intel, the goal is to encourage more active and wider adoption of precise code-intel, better customer retention and growth through seeing the value in precise code-intel, which they may otherwise not experience due to above reasons.

@macraig would you clarify @Strum355 's point from the product perspective?

- how do we position auto-indexing as a feature? Is it just a complement to uploading indexes from CI? Or it should be a zero-config that just works and doesn't require additional config (i.e. uploading additional indexes from CI)
- With Cloud (managed instances) context in mind, we're offering auto-indexing to customers as an added value. However, at the end of day, we may still need to ask customers to upload indexes from CI to unlock that full experience. Do you think this affects the managed experience that Cloud is aiming to offer?

**Comment by macraig** [comment]
> how do we position auto-indexing as a feature? Is it just a complement to uploading indexes from CI? Or it should be a zero-config that just works and doesn't require additional config (i.e. uploading additional indexes from CI)

It's a bit of both. Auto-indexing per se should be zero-config that just works, which satisfies the needs @Strum355 described above (low adoption barrier to precise code-intel, no need for CI access, possibility of indexing external code and packages, etc). That said, given the diverse dev envs customers have, auto-indexing might not always be the best solution for _every_ customer's needs or cover 100% of their codebase, and that is fine. Ideally, every customer can choose what works for them: the more automatized experience with auto-indexing, manually configuring via CI, or a mix of both (this last one will likely get closer to 100% for the average customer). 

> With Cloud (managed instances) context in mind, we're offering auto-indexing to customers as an added value. However, we may still need to ask customers to upload indexes from CI to unlock that full experience. Do you think this affects the managed experience that Cloud is aiming to offer?

Again, this will depend on customer needs. The overarching goal is to get precise navigation to all Cloud customers right out of the box to hit the ground running (before, we only offered this experience via a high level of manual investment, so there's already a ton of value here). Depending on their env and needs and their eagerness to have more precise coverage (which we hope happens!), we will either improve auto-indexing and inference or prompt them for manual installation for the cases we can't cover.

**Pull request merged**
