### PR TITLE
Add lucky generator for symbol types

### PR DESCRIPTION
**Pull request by beyang**
I thought it would be reasonable if I typed `function foobar` to see results for functions matching "foobar". This would map to adding the `type:symbol select:symbol.function` query terms to the query.

The rule also incorporates lucky shorthands for all the `select:symbol.*` types.

## Test Plan

Added a test in the pattern of previous lucky rule tests. Manually tested by Camden.

### CODE REVIEW

**Review by camdencheek — APPROVED** [review]
I like this a lot. This feels like a very natural addition to the lucky search heuristics. As a nice bonus, it seems likely this will organically improve the discoverability of symbol search.

The code change looks solid. I tested that it even composes with the "AND patterns together" rule so `function abc def` will be attempted as `type:symbol select:symbol.function (abc and def)`, which is exactly what these compositions were designed to do 😄 

Thanks for the contribution!

**Review by rvantonder — APPROVED** [review]
I like this a lot too, let's ship it.

**Comment by camdencheek** [comment]
@beyang I took the liberty of adding a test plan to your PR so CI passes. Feel free to merge whenever

**Comment by beyang** [comment]
Thank you @camdencheek for the test addition! Thank you @rvantonder for the wonderful composition architecture here that was super easy to work with. And thank you both for the quick review!

**Pull request merged**
