### PR TITLE
Update Cody Web to 0.3.7

### PR DESCRIPTION
**Pull request by thenamankumar**
closes: https://linear.app/sourcegraph/issue/SRCH-821/context-is-not-being-fetched-on-vs-code-even-though-its-being-fetched

CleanShot 2024-08-06 at 16 13 05@2x

This PR updates Cody Web to 0.3.7. The latest version introduces the following changes:
- Removes the Cody history panel and rather uses the tabs. (As updated in latest version on Cody Web)
- Removes the `experimental.noodle` flag set to true. 
- Fixes the issue where the query for `getCodyContext` contained mention chips text and was different from VS Code. 

## Test plan

- visit /cody/chat

### CODE REVIEW

**Review by peterguy — APPROVED** [review]
works great for me locally.

**Comment by fkling** [comment]
Does this also affect the behavior of the cody sidebar? I assume so. In that case the svelte app needs to be updated too.

**Comment by thenamankumar** [comment]
@fkling yes I missed the svelte one. Working on it now. Thanks for catching it.

**Comment by thenamankumar** [comment]
@fkling I have updated the Svelte Code as well. It is a small change, just 2 import renames but I am not able to test it locally.

Have spent enough time figuring out how to solve this 500 issue on `sg start`. I am getting this error even on `main` HEAD. 
CleanShot 2024-08-07 at 10 09 58@2x

With `vite dev` and `sg start web-standalone` I am not able to login locally.

Given this is an easily reversible & small change, I am merging the PR and triggering a dotcom deployment to test it on prod. While I wait for team members to start working today, so I can get help to test it locally as well.

**Pull request merged**
