### PR TITLE
Add lsif-server migration instructions for pure docker

### PR DESCRIPTION
**Pull request by efritz**

### CODE REVIEW

**Comment by slimsag** [comment]
Thanks for sending, I'll take over this PR from here.

**Comment by efritz** [comment]
Bump in case this was forgotten before the release.

**Comment by slimsag** [comment]
Not forgotten, I will own. I just haven't shipped this to the customer using it yet. Will do so early next week.

**Comment by slimsag** [comment]
Effectively merged into https://github.com/sourcegraph/sourcegraph/pull/10487

**Pull request closed without merging**
