### PR TITLE
Cody: Implementation of ignore md files in context result

### LINKED ISSUE #51491: Cody: Improve context search result quality
Follow up on https://github.com/sourcegraph/sourcegraph/pull/51077

@beyang

> Improving results quality. I think a quick win here could be to filter out markdown files, which often provide useful context for Cody, but aren't relevant when you're looking for a snippet of code.

### PR DESCRIPTION
**Pull request by deepak2431**
This issue is for fix #51491. It implements the code to ignore the md and txt files while displaying context results.

## Test plan

tested manually

### CODE REVIEW

**Comment by deepak2431** [comment]
@abeatrix Requesting review for this PR!

**Review by abeatrix — APPROVED** [review]
It works! Thanks for the quick fix!

**Comment by philipp-spiess** [comment]
@abeatrix It looks like you forgot to trigger the CI pipeline here :D Unfortunlaty you'll have to do this manually for a contribution like this. You'll need to copy the SHA of the last commit and do this:

```
sg ci build --commit 3d2e22f91085019af518e8248eb292d6f95507fb
```

This is for us to make sure only "legit" code runs on our CI (and has access to our env secrets). The GitHub button alone to run the PR is not enough unfortunlaty as it won't propagate Buildkite

**Comment by abeatrix** [comment]
@philipp-spiess omg I was going to ask in our sync today 😂 thank you!!!

**Comment by philipp-spiess** [comment]
Finally a green build 🙈

**Pull request merged**
