### PR TITLE
Update Docs UI/UX

### PR DESCRIPTION
**Pull request by francisschmaltz**
Migrated from https://github.com/sourcegraph/docs.sourcegraph.com/pull/11

Update docs UI to be inline with our product UI

- [x] Use main SG theme 
- [x] Update logo
- [x] Update header
- [x] Update text styles and colors
- [x] Update layout
- [x] Add mobile support
- [x] Add docs content nav on left side

Fixes: https://github.com/sourcegraph/sourcegraph/issues/2464
Fixes: https://github.com/sourcegraph/sourcegraph/issues/2463
Fixes: https://github.com/sourcegraph/sourcegraph/issues/1701
Fixes: https://github.com/sourcegraph/sourcegraph/issues/2246
Fixes: https://github.com/sourcegraph/docs.sourcegraph.com/pull/10

Other features:
- Adds support for alternative search providers (Default: Google, DuckDuckGo, Sourcegraph.com)
- Adds clear footer
- Adds mobile support.

Desktop:
screen shot 2019-03-01 at 5 56 13 pm
screen shot 2019-03-01 at 5 58 28 pm
screen shot 2019-02-27 at 8 04 32 pm
screen shot 2019-03-01 at 5 57 50 pm

Mobile:
screen shot 2019-03-01 at 5 56 39 pm

screen shot 2019-03-01 at 5 58 39 pm

### CODE REVIEW

**Comment by francisschmaltz** [comment]
@felixfbecker continuing conversation from old PR.

**Comment by ryan-blunden** [comment]
Overall this is looking great and our users will appreciate the theme and functionality improvements.

Below is a list of (mostly quick and small) changes to complete before the PR is merged.
 
## Search

 - [ ] Remove "Search docs with:" label
 - [ ] Revert to a single button*

*The search chooser functionality should be moved into a separate PR and put on hold (for now) as it's not required, plus there are some issues to fix:

  - [ ] Searching with Sourcegraph is kinda cool but not genuinely helpful.
  - [ ] Doesn't remember selection (annoying to have to choose every time).

## Version selector

Looks great! just minor tweaks.

 - [ ] Remove `Sourcegraph version:` label
 - [ ] List in date descending order

## Left nav

This is looking great! I could go either way on the collapsing functionality but I think it's useful to be able to see the major sections of the docs above the fold (when all collapsed).

 - [ ] CSS hiding menu items at bottom on Chrome, e.g. Admin.
 - [ ] Change "Docs home" to "Home".
 - [ ] Remove Quickstart link as it's not needed anymore ( but don't delete page).
 - [ ] Add hover style and selected style for all headings and sections (see gif).
 - [ ] No nav should be open on the home page.

## Breadcrumb trail

Love the new styles, just need to remove the "Documentation" bread crumb element on the home page.

 - [ ] Remove breadcrumb on home page

## Content

 - [ ] Add `alt` text for logo svg
 - [ ] docs-content-section min height 700px as pages such as [Repositories](http://localhost:5080/admin/repo) look weird.
 - [ ] Change `#` on hover to the link icon that GitHub or Stripe uses as it's represents a link better

## Mobile Left nav

The main menu toggle element needs to be dedicated to helping the user navigate around the site. The other links are secondary and could even be merged with the footer or just left out entirely.

 - [ ] Add docs nav after search and before About, Code and Sourcegraph.com

**Comment by francisschmaltz** [comment]
>  Remove "Search docs with:" label
Revert to a single button
The search chooser functionality should be moved into a separate PR and put on hold (for now) as it's not required, plus there are some issues to fix:
Searching with Sourcegraph is kinda cool but not genuinely helpful.
Doesn't remember selection (annoying to have to choose every time).

Search was reverted to previous functionality in commit 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/2c93dd3310b55d8fa7906f55b3017628261cd907

**Comment by francisschmaltz** [comment]
> Set .docs-content-section min-height to 700px so short pages such as the repositories index look weird.

Docs pages that are smaller than the height of the viewport automatically expand to fill the heigh of the viewport minus the footer, so all content is displayed and the footer is either at the bottom of the screen or below the content (whichever is lower).

**Comment by francisschmaltz** [comment]
> List in date descending order

Resolved in commit 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/2c93dd3310b55d8fa7906f55b3017628261cd907

**Comment by francisschmaltz** [comment]
>Add alt text for logo svg

Good catch, fixed in 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/0b5b256a9249a46b6833bb2cfd75ecbd6a5d9d26

**Comment by ryan-blunden** [comment]
> Docs pages that are smaller than the height of the viewport automatically expand to fill the heigh of the viewport minus the footer, so all content is displayed and the footer is either at the bottom of the screen or below the content (whichever is lower).

I just think this looks weird and looks a lot better when the viewport height is a minimum size.

screenflow

**Comment by francisschmaltz** [comment]
> Menu items at bottom of certain sections, e.g, Admin are partly obscured on Chrome

This was caused by a a max-height assumption problem. 

> Remove Quickstart link as it's not needed anymore ( but don't delete page).

Removed link


Both corrected in 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/8d87797cd7e3eb92cc6e46e03c0f07dcbd9aae66

**Comment by francisschmaltz** [comment]
> Remove unnecessary @ for master and @v in versions list

Fixed in commit 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/1e8ebbf038f17b19545582d36e900dd5f779037b

Removed `@` from the version to reflect how Sourcegraph styles tags and branches.

screen shot 2019-03-04 at 4 57 22 pm
screen shot 2019-03-04 at 4 58 06 pm

**Comment by felixfbecker** [comment]
> Using a custom non-flexbox grid makes it a lot simpler and cleaner to create the fixed sections on a grid. It makes it a lot easier to create a clean grid that will work for the subsections.

@francisschmaltz could you explain _why_ it is simpler? It looks like you define classes for a 12-column grid, just like Bootstrap. Consider that teammates don't know how your custom grid works but are more likely to know how Bootstrap grid works (and there are learning materials)

**Comment by francisschmaltz** [comment]
> could you explain why it is simpler? 

I needed to space the main 3 elements out evenly without using flex box to get the desired scrolling behavior. While it would have been the simplest to just add the position and grid-like behavior to the elements without defining a grid, defining a grid that is super simple makes it a bit easier to change the  width later on if required. I simply needed a way to make sure that all the elements were positioned correctly as block elements. Using bootstrap would have been preferable, but it would have made it a fair bit more complex to get the desired layout and scroll behavior with our default grid.

**Comment by francisschmaltz** [comment]
> Change "Docs home" to "Home".

and 

> Remove breadcrumb on home page

Resolved in 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/fcafe1c419e46bb15f8ed691fb2a94c40af343b6

**Comment by francisschmaltz** [comment]
> No nav section open on home page.

Resolved in 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/f236e715fce0c58af71f1c720cd2adeb4d688090

**Comment by francisschmaltz** [comment]
> Remove Sourcegraph version: label

Although this is against our style guide, removed at request in 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/06e2c9527123c6e846bd1add7e3e7a838e5b01e1

`area-label` was added on dropdown to inform screen readers of the dropdown function.

**Comment by francisschmaltz** [comment]
> Change # on hover to the link icon that GitHub or Stripe uses as it's represents a link better

Discussed offline. This will not be included in this PR.

**Comment by francisschmaltz** [comment]
> Add hover style and selected style for all headings and sections

Added hover state in 
https://github.com/sourcegraph/sourcegraph/pull/2564/commits/fb3aa5347c860a8c20473d3407033fe4bffd4e1f

Note: this does not highlight the nav section for the page the user is currently on. There's not a *simple* solution to this. A separate issue/PR should be created if this functionality is wanted as it requires pragmatically creating the content nav.

**Pull request closed without merging**
