### PR TITLE
dev/ci: generate notifications for release nightly builds

### PR DESCRIPTION
**Pull request by bobheadxi**
Release nightly healthchecks, if failed, will now try to tag either a Slack user based on `captainGitHubUsername`  or the dev experience support handle. I noticed this request in [RFC 590](https://docs.google.com/document/d/1C--cw5ZC-OUsQT7sbe3GboDxOGHs16KB0jM_F0BAWVI/edit#)

We cannot use Slack usernames for tagging because doing so is not supported by Buildkite/Slack.

## Test plan

```sh
export SLACK_INTEGRATION_TOKEN=...
go run enterprise/dev/ci/gen-pipeline.go -overrideRunType=1 -yaml
```

You get:

```yaml
notify:
- if: build.state == "failed"
  slack:
    channels:
    - '#buildkite-main'
    message: cc <@U02UJSAEQP9>
```

The above is @michaellzc , current release captain

### CODE REVIEW

**Comment by michaellzc** [comment]
Not blocking just an idea.

Bill is setting up a new release guild rotation. We haven't figured out how the process would work yet, especially with stuff like how to track the rotation schedule and who will be a part of the release guild. How about we reuse our on-call infra with opsgenie

- create a new team named release-guild
- [slackengine] or opsgenis can add on-call release captain to a new slack handle `@release-guild` or something similar

in the event of a failure on release branch health check, we just ping the @release-guild handle on slack.

**Comment by bobheadxi** [comment]
>  can add on-call release captain to a new slack handle @release-guild or something similar

This sounds great! I imagine the release tool can configure that too. It would make this notification implementation much simpler - let's put this on hold until a decision is made on that front!

**Comment by jhchabran** [comment]
@bobheadxi I removed ourselves from the reviewers' list while it's on hold, otherwise we're getting slack pings from the GitHub bot every day!

**Comment by bobheadxi** [comment]
I asked about this in Slack ( https://sourcegraph.slack.com/archives/C032Z79NZQC/p1650916160913289 ), but there doesn't seem to be any urgency/interest so closing this out for now

**Pull request closed without merging**
