### PR TITLE
Faster ReposourceCloneURLToRepoName

### PR DESCRIPTION
**Pull request by ryanslade**
We noticed that on sourcegraph.com running ReposourceCloneURLToRepoName could be very slow, 
often take more than 3 seconds to return.

There were two problems: 
1. We fetch up to 500 external services at a time
2. For each service, we need to decrypt config which makes an API call taking around 7m. These were run in sequence.

This PR improves the performance in four ways: 

1. As a fast path, should be able to get the repo name from `external_service_repos` table in a simple query if we already have the repo cloned.
2. If that fails, we first try our `cloud_default` external services as they'll match the majority of repos.
3. We fetch in smaller batches
4. We make the API calls to decrypt in parallel.

Found while investigating https://github.com/sourcegraph/sourcegraph/issues/23775

### CODE REVIEW

**Review by tsenart — COMMENTED** [review]
One idea: Instead of doing all of this iteration, since we have the `clone_url` in the `external_service_repos` table, we can efficiently look-up all external services and repos that match it.

**Comment by ryanslade** [comment]
All we want is the repo name, so couldn't we just join against the repo table and return that directly?

One thing that made me not consider that in the first place is that I thought we wanted to deprecate the clone_url column? Maybe I'm thinking of something else..

**Comment by tsenart** [comment]
> All we want is the repo name, so couldn't we just join against the repo table and return that directly?

Yep, that's exactly what I mean, taking into consideration any normalization we might need to do to the incoming clone url argument.

> One thing that made me not consider that in the first place is that I thought we wanted to deprecate the clone_url column? Maybe I'm thinking of something else..

Nope, this column is super useful. We got rid of the secrets in it which is enough.

**Comment by unknwon** [comment]
Apart from the https://github.com/sourcegraph/sourcegraph/pull/24588#pullrequestreview-746044362, what about just listing external services with no namespace? (Cloud only support github.com and gitlab.com, on-prem there is only site-level external services)

**Comment by tsenart** [comment]
@ryanslade: What leads you to believe that this code needs to work with repositories we don't yet have in the DB?

And if so, how would the current code cover that use case?

**Comment by ryanslade** [comment]
I made that assumption because it seems to just need to decipher the name from clone_url and just looks for a code host that can do that without ever checking if we actually have the repo. Also, the path I followed to find this issue is through looking up submodules and I don't think we guarantee that all submodules are cloned do we? 

But, given that this code was originally added to support "open in editor" here https://github.com/sourcegraph/sourcegraph/pull/16846 I think maybe we can safely assume that the repo exists. It doesn't make sense try try and open a repo we don't have.

So, I'm going to change this PR to do a simple db lookup and just choose the first repo name that comes back

**Comment by ryanslade** [comment]
So I switched to the simple DB lookup but then a bunch of existing tests starting failing. One example that I'm not sure how to get around is we want this method to support looking up submodules defined using relative paths. 

So, instead I'm just using the DB lookup as a fast path which we should hit the majority of the time on .com

**Review by unknwon — APPROVED** [review]

**Comment by ryanslade** [comment]
We noticed that on sourcegraph.com running ReposourceCloneURLToRepoName could be very slow,
often take more than 3 seconds to return.

There were two problems:

1. We fetch up to 500 external services at a time
2. For each service, we need to decrypt config which makes an API call taking around 7m. These were run in sequence.

This PR improves the performance in four ways:

1. As a fast path, should be able to get the repo name from external_service_repos table in a simple query if we already have the repo cloned.
2. If that fails, we first try our cloud_default external services as they'll match the majority of repos.
3. We fetch in smaller batches
4. We make the API calls to decrypt in parallel.

**Pull request merged**
