### PR TITLE
Add setup wizard metrics/pings

### PR DESCRIPTION
**Pull request by vovakulikov**
Closes https://github.com/sourcegraph/sourcegraph/issues/47974
[Setup wizard Pings RFC](https://docs.google.com/document/d/1Xh6J1oZ_UrRl55eoJ6ViAvuXewoKOED9zIQhnGrOAH0/edit#heading=h.trqab8y0kufp)
[Figma schema](https://www.figma.com/file/EuRdjjQF8a9kRJMRce4HyI/UX%3A-Instance-setup-experience?node-id=1819%3A18403&t=gENaNogKlNZyxgcq-0)

This PR adds (none aggregated) [usage stats events](https://docs.sourcegraph.com/dev/background-information/data-usage-pipeline). 

## TODO 
- [x] Add event logs to the web app 
- [x] Add events to the user stats data stream allow-list
- ~~Update query schema~~ (based on the new flow, there is no need for this)

## Test plan
- Check that client sends events to the backend 

## App preview:

- [Web](https://sg-web-vk-add-setup-wizard-metrics.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.41 kb) | 0.01% (+1.41 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vk/add-setup-wizard-metrics/compare-report.html;tab=live_object) for a full comparison between the commits 0c316d9 and 91ea697 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by almeidapaulooliveira — CHANGES_REQUESTED** [review]
I see you're using the `SetupWizardViewedTab` as the event name. If we use a name in the Figma board and another name in the implementation, we can never find that event on Amplitude when creating the dashboards. I suggest using the names that are documented.

**Comment by vovakulikov** [comment]
@almeidapaulooliveira it's in draft status I will let you know when this is ready for your review

**Comment by vovakulikov** [comment]
@almeidapaulooliveira, it's ready for your review! 🎆 Since we haven't merged local repositories UI you can't test them manually, but I added them to the allow-list, when local UI will be ready we will connect events with UI

**Comment by vovakulikov** [comment]
Question to data engs 
since these events are not aggregated pings but just user events, should I update the amplitude query only? https://sourcegraph.sourcegraph.com/github.com/sourcegraph/analytics/-/blob/BigQuery%20Schemas/amplitude%20events.sql?L5

**Comment by vovakulikov** [comment]
@almeidapaulooliveira @ryphil just to make sure we keep this in mind, even though I added local repositories pings here based on a conversation with @marekweb and this [thread](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1678223382210839) about Sourcegraph thread usage stats pings won't be included in the starship version.  

Practically, this means we won't have any information about the setup wizard in the Sourcegraph App. I still added setup wizard's event just to simplify process when we will have pings uploading from the Sourcegraph app

**Comment by vovakulikov** [comment]
@akalia25 so basically, all usage data events which are not in the list above will show up in the Amplitude automatically?

**Comment by vovakulikov** [comment]
Aha, I see the query in console looks like this is the case, thanks @akalia25 (cool that we don't need to update anything to have events in amplitude, in the past I think we had to update something in analytics repo)

**Comment by akalia25** [comment]
> Aha, I see the query in console looks like this is the case, thanks @akalia25 (cool that we don't need to update anything to have events in amplitude, in the past I think we had to update something in analytics repo)

Awesome! Yeah we made some changes to make the data flow to amplitude easier :) --> and if for whatever reason you find that you dont see those events popup in Amplitude, i'd be happy to take a look.

**Review by almeidapaulooliveira — APPROVED** [review]

**Pull request merged**
