### PR TITLE
Packages: Update overview page

### PR DESCRIPTION
**Pull request by umpox**
closes https://github.com/sourcegraph/sourcegraph/issues/37770
closes https://github.com/sourcegraph/sourcegraph/issues/37766

## Description

Packages popover:
- Updates revision selector and compare selector to only show tags
- Changes wording from "Tags" to "Versions"
- Removes commit data from tag nodes
- Updates styling to reflect less content

Packages overview page:
- Remove branches and batch changes tabs
- Updates wording and link of Tags tab to "Versions"
- Adds a new icon to indicate it is a package.
- Removes contributors and commits section from README and file directory pages

Tags page:
- Adds new entry route, under /versions
- Updates wording of page from "Tags" to "Versions" regardless if loaded under /tags or /versions (to support old links)
- Removes commit data from tag nodes for packages.

## Screenshots

image

image

image

image

## Test plan

Tested locally

1. Compare package overview page AND revision popover https://sourcegraph.test:3443/npm/typescript vs https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph
2. Compare package directory page https://sourcegraph.test:3443/npm/typescript/-/tree/lib vs https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/tree/dev
3. Compare package versions page https://sourcegraph.test:3443/npm/typescript/-/versions and https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/tags
  - Check inverse works as expected https://sourcegraph.test:3443/npm/typescript/-/tags vs https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/versions

## App preview:

- [Web](https://sg-web-tr-update-package-overview.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.48 kb) | 0.00% (+0.48 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/tr/update-package-overview/compare-report.html;tab=live_object) for a full comparison between the commits bcffd48 and 06745e9 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by umpox** [comment]
@Strum355 Packages return the "defaultBranch" as:

```
"defaultBranch":
  "displayName":"latest"
  "abbrevName":"latest"
}
```

So the popover shows this as a default 
image

Maybe this is fine, but just wanted to raise it. Not sure if we have a way to expose this as a version right now.

**Comment by umpox** [comment]
@sourcegraph/design @Strum355 Added an icon to indicate this is a package on the overview page:

image



Happy to change if we have any better alternative icons in mind. Some mdi icon options:

image

**Comment by Strum355** [comment]
> @sourcegraph/design @Strum355 Added an icon to indicate this is a package on the overview page:
> 
> image
> 
> Happy to change if we have any better alternative icons in mind. Some mdi icon options:
> 
> image

I really like this if we're sticking with the ecosystem prefixes 🙏 
Id be interested in crowdsourcing some opinions from devs, or even design, what they think about the ecosystem prefixes. Do we keep them and go with the 📦 icon, or do we strip the prefix and replace the icon with one of the ecosystem icons like we have on the package listings and extsvc pages? What do you think?

**Comment by Strum355** [comment]
> @Strum355 Packages return the "defaultBranch" as:
> 
> ```
> "defaultBranch":
>   "displayName":"latest"
>   "abbrevName":"latest"
> }
> ```
> 
> So the popover shows this as a default image
> 
> Maybe this is fine, but just wanted to raise it. Not sure if we have a way to expose this as a version right now.

This is a good point. We're currently using this so that the frontend will default to it as the landing place, but of course this is a (known) leakage of the underlying implementation in the graphql API. I think this is fine as-is for the time being until packages n co become more first-class in our API

**Review by olafurpg — APPROVED** [review]
I haven't reviewed the code itself, but the changes look great when running locally.

**Review by olafurpg — APPROVED** [review]
Took a look at the implementation and have no comments. Looks good 👍🏻

**Review by Strum355 — APPROVED** [review]

**Pull request merged**
