### PR TITLE
gitserver: make errors to have pointer receivers

### PR DESCRIPTION
**Pull request by DaivikDave**
Fixes [#33099](https://github.com/sourcegraph/sourcegraph/issues/33099)
@sourcegraph/repo-management

## Test plan
Changing errors to have pointer receiver shouldn't break anything https://go.dev/blog/error-handling-and-go

### CODE REVIEW

**Comment by ryanslade** [comment]
@DaivikDave Thanks, please can you remove the TODO block at the top of that file?

**Comment by DaivikDave** [comment]
@ryanslade I've removed them. Thanks

**Review by ryanslade — APPROVED** [review]

**Comment by ryanslade** [comment]
Sorry about the delay, I'll merge this next week.

**Comment by ryanslade** [comment]
@DaivikDave It looks like there are some valid build failures on this, for example:

```
internal/gitserver/gitdomain/services.go:46: cannot use BadCommitError{...} (type BadCommitError) as type error in return argument:
	BadCommitError does not implement error (Error method has pointer receiver)
internal/gitserver/gitdomain/services_test.go:101:4: cannot use BadCommitError{...} (type BadCommitError) as type error in field value:
	BadCommitError does not implement error (Error method has pointer receiver)
```

**Comment by DaivikDave** [comment]
@ryanslade Thanks for pointing it out. I missed that the errors should also be pointers. I'll push the fix for this also build locally before testing. Sorry

**Comment by ryanslade** [comment]
Thanks for the fix, it looks like you need to format the code in `internal/vcs/git/revisions.go`

**Comment by DaivikDave** [comment]
Thanks @ryanslade, I formatted the document. Also I wanted to know if there is a way to test and build the code changes other than the sg test command.

**Comment by ryanslade** [comment]
`sg test` should work. Is that what you used? I'm surprised it didn't pick up at least the first issue.

**Comment by DaivikDave** [comment]
@ryanslade I hadn't run the sg test command the first time i made the PR, but i ran it in my latest commit.
I am unable to test using sg test on main branch. Tests under some of the folders are failing.
Here's a brief output from sg test command I ran on main branch
Starting testsuite "backend".
Running /bin/bash -c go test ./... in "/home/daivik/Desktop/open-source/sourcegraph"...
?   	github.com/sourcegraph/sourcegraph	[no test files]
# github.com/google/zoekt
../../../work/pkg/mod/github.com/sourcegraph/zoekt@v0.0.0-20210721121719-c54bd1fb8d2e/matchtree.go:530:9: cannot use maxUInt32 (untyped int constant 4294967295) as int value in assignment (overflows)
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/auth [build failed]
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/backend [build failed]
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend [build failed]
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/externallink [build failed]
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/app [build failed]
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/app/debugproxies [build failed]
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/app/jscontext [build failed]
ok  	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/app/router	0.010s
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/app/ui [build failed]
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/app/updatecheck [build failed]
ok  	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/auth	162.042s
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/auth/userpasswd [build failed]
ok  	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/bg	0.008s [no tests to run]
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli [build failed]
ok  	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/loghandlers	0.004s
ok  	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware	0.012s
ok  	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cloneurls	163.707s
Am I missing something in my setup?

**Comment by ryanslade** [comment]
@DaivikDave What version of Go are you using? I'm not seeing errors when running locally on `1.18.1`

**Comment by indradhanush** [comment]
Superseded by #40429.

**Pull request closed without merging**
