### PR TITLE
permission sync jobs: don't highlight if 0 added/0 removed

### PR DESCRIPTION
**Pull request by mrnugget**
I don't really like this: I think when nothing was changed it can just be plain and boring.

screenshot_2023-03-31_12 26 06@2x

## After

screenshot_2023-03-31_14 21 38@2x

## Test plan

- Existing tests

## App preview:

- [Web](https://sg-web-mrn-fix-0-sync-jobs.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by mrnugget** [comment]
I cannot test this with Storybook because apparently the story broke: 
screenshot_2023-03-31_12 28 41@2x


@thenamankumar @sashaostrikov

**Review by sashaostrikov — COMMENTED** [review]
I'd like to ask design for this matter, IMO it would be too disturbing and colorful for numbers in one column to be of different colors.
Can you add an "after" screenshot in description too?

**Comment by mrnugget** [comment]
@sashaostrikov I added an "after" screenshot

**Comment by danielmarquespt** [comment]
Just remove the sign, but keep the color. It helps to parse the columns vertically.

In case of 0 we can apply the `var(--success-2)` color to it, to mute it down and give relevance to the other changes

Screenshot 2023-04-03 at 16 52 43

**Comment by mrnugget** [comment]
done! 
screenshot_2023-04-04_10 42 10@2x

**Comment by mrnugget** [comment]
@sashaostrikov wanna re-review?

**Review by sashaostrikov — APPROVED** [review]
Looks nice!
I wonder if we need to "mute" 0 result in `total` column as well?
Approving to unblock anyway.

**Review by thenamankumar — APPROVED** [review]

**Comment by mrnugget** [comment]
> I wonder if we need to "mute" 0 result in `total` column as well?

It is already `text-muted` 😄

**Comment by danielmarquespt** [comment]
> > I wonder if we need to "mute" 0 result in `total` column as well?
> 
> It is already `text-muted` 😄

You can use `var(--icon-muted)` in this case

**Comment by mrnugget** [comment]
done: 
screenshot_2023-04-04_15 03 27@2x

**Review by danielmarquespt — APPROVED** [review]
Ship it!

**Pull request merged**
