### PR TITLE
disallow updating monitor namespace to one uneditable by caller

### PR DESCRIPTION
**Pull request by camdencheek**
Any sensitive PR comments should be discussed in https://github.com/sourcegraph/security-issues/issues/170

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
Rubber stamp. You may would request owner(s) of code monitors to check this or other logic, I'm not sure who's the best for that.

**Comment by camdencheek** [comment]
> You may would request owner(s) of code monitors to check this or other logic

I believe search product is now the technical owner, but I think @stefanhengl might know a bit more about it?

**Comment by benvenker** [comment]
@camdencheek we are, in fact, the owners!

**Review by andreeleuterio — APPROVED** [review]
LGTM! I tested it against this branch and got:
```
{
  "errors": [
    {
      "message": "update namespace: must be authenticated as the authorized user or as an admin (must be site admin)",
      "path": [
        "updateCodeMonitor"
      ]
    }
  ],
  "data": null
}
```

Thanks @camdencheek!

**Pull request merged**
