### PR TITLE
web: upgrade babel plugins to support TS `satisfies` operator

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context 

[TypeScript 4.9 has been released](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/) and [we are on it already](https://github.com/sourcegraph/sourcegraph/issues/44638). But our current `babel` version doesn't support the new [satisfies operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/#the-satisfies-operator). This PR upgrades `babel` packages to fix this issue.

See the babel release blogpost for more info: https://babeljs.io/blog/2022/10/27/7.20.0

## Test plan

CI is green.

## App preview:

- [Web](https://sg-web-vb-babel-upgrade.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.91% (+26.07 kb) 🔺 | 0.47% (+70.34 kb) 🔺 | 0.37% (+44.27 kb) 🔺 | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vb/babel-upgrade/compare-report.html;tab=live_object) for a full comparison between the commits bfe5818 and 1dbb1f6 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by philipp-spiess** [comment]
Screenshot 2022-12-13 at 11 55 52

👀  Can you double-check if this is true?

**Review by vdavid — APPROVED** [review]
TIL `satisfies`.

Once CI is happy, I'm happy.

Currently, CI has an issue with the lockfile that `yarn dedupe` should fix, but I'm not sure what's wrong with the `extension-api`.

**Comment by valerybugakov** [comment]
Thanks, @vdavid! I'm looking into the issue 👍

**Review by taras-yemets — APPROVED** [review]

**Comment by valerybugakov** [comment]
I generated the bundle-size diff report locally against the latest commit  on `main` :
Screenshot 2022-12-14 at 12 00 33

It might be that the issue was in the missing `yarn dedupe` command. Waiting for the latest results from the CI check.

**Comment by valerybugakov** [comment]
Ok, the latest CI report also looks much better than the initial one. I'm going ahead with merging this.

**Comment by philipp-spiess** [comment]
Ah nice so this was just modules being added multiple times? Glad we have safeguards to guard against it 😰

**Pull request merged**
