### PR TITLE
Fix: add link to saved searches to search results page

### PR DESCRIPTION
**Pull request by attfarhan**
Fixes https://github.com/sourcegraph/sourcegraph/issues/4274

(I'm out for the week so if this is approved please feel free to merge)

### CODE REVIEW

**Comment by felixfbecker** [comment]
@attfarhan I notice you often push Prettier commits. Does auto-format not work in your editor? Happy to help

**Comment by dadlerj** [comment]
@felixfbecker can this be merged given what Farhan said above?

**Comment by felixfbecker** [comment]
Yeah I approved it

**Comment by slimsag** [comment]
I will cherry-pick onto 3.4 and update CHANGELOG. Friendly reminder to update CHANGELOG in the future :)

**Comment by slimsag** [comment]
(I was wrong and this didn't need a changelog entry nor a patch release, see https://github.com/sourcegraph/sourcegraph/issues/4274#issuecomment-498469000)

**Pull request merged**
