### PR TITLE
a8n: Use simple header for campaign pages

### LINKED ISSUE #7868: Use simplified header on Campaign pages
Currently you can see the search bar when on Campaign pages. If there is a search in scope, that will be shown. This feels out of context for the Campaign state, since the search bar does not influence what happens on these pages.

image

Instead, we should use the simplified header used on the search query builder to avoid confusion.

image

### PR DESCRIPTION
**Pull request by eseliger**
I think it looks good and takes off some visual complexity of this already very packed UI

image

image

Closes #7868

### CODE REVIEW

**Comment by christinaforney** [comment]
Every time I try to leave a page I get the notification asking me if I want to discard my changes:

**Comment by felixfbecker** [comment]
Hmm I actually find the campaigns UI looks very _empty_ (no sidebar, panels etc). Removing the search bar makes it feel detached from the rest of the product for me (search, repos, ...). Thoughts?

**Comment by christinaforney** [comment]
> Hmm I actually find the campaigns UI looks very _empty_ (no sidebar, panels etc). Removing the search bar makes it feel detached from the rest of the product for me (search, repos, ...). Thoughts?

I was worried about that too, but personally I don't get that feeling when trying it out. The problems we're trying to solve here are:
1. Confusing the user that they can use the search bar to influence the campaign form (this is no longer valid due to removal of create form fields).
1. Reduce visual noise when looking at a campaign page, especially when in interactive mode since the search query stays in the UI even when search results aren't shown

image

I have similar concerns about site admin/settings pages:

image

image

@felixfbecker Do you have any ideas about how we could improve this without it looking so _empty_? This is a change that would be great to A/B test if we had the infrastructure in place...

**Comment by eseliger** [comment]
Closing this as a result of the discussion here https://sourcegraph.slack.com/archives/C02FSM7DW/p1580328729029100

**Pull request closed without merging**
