### PR TITLE
authz: enforce one authz provider per code host type

### LINKED ISSUE #8597: Ambiguous association between permissions and authz provider
In the current design of permissions tables (i.e. `user_permissions`, `repo_permissions`), it has the assumption that only one authz provider per code host is configured for mirroring permissions. This assumption IMO is inherited from the assumption of a customer would only want to configure at most one code host connection per type, i.e. only one GitLab code host connection, and maybe another GitHub code host connection.

Some evidences are in cache implementation, we only store the project/repo ID but not the actual service ID (e.g. https://github.com, https://gitlab.mycorp.com) these project/repo IDs belong to, which could potentially have collisions when there are multiple authz providers configured for the same type of code host, e.g. two GitLab authz providers.
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/authz/github/cache.go
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/authz/gitlab/cache.go

It is generally unlikely thus not a problem so far, but could cause ambiguity with the transition of moving permissions syncing to the background (RFC 113) which unifies the store layer to Postgres.

There are two ways we could think about this problem:
a. We make it clear in [our docs: **Repository permissions**](https://docs.sourcegraph.com/admin/repo/permissions) that we currently only support one code host authz provider per type until a large customer wants such support.
b. We fix it now.

I personally prefer **option a** because:
1. We could do the migration in the future (find the code host config has the authz provider and update the column in perms table with the URL of that code host).
2. It is still possible to configure multiple code host connections of same type, but only have single authz provider.
3. Tackle **option b** requires non-trivial work with not so much in return (for the foreseeable future) given the assumption of only having one authz provider configured has lasted in fairly long time.

cc @beyang in case I missed some parts from the whole picture.

### PR DESCRIPTION
**Pull request by unknwon**
This PR enforces one authz provider per code host type in the code level, also updated relevant docs.

image

Fixes #8597.

### CODE REVIEW

**Comment by beyang** [comment]
I thought the ambiguity issue was with more than one code host with the same type *and* hostname, not just the same type. Am I mistaken here?

Also, there might currently be customers with more than one code host of the same type and hostname, so this should be a loud warning, rather than a hard error.

**Comment by beyang** [comment]
I thought the ambiguity issue was with more than one code host with the same type *and* hostname, not just the same type. Am I mistaken here?

Also, there might currently be customers with more than one code host of the same type and hostname, so this should be a loud warning, rather than a hard error.

**Comment by unknwon** [comment]
@beyang 
> I thought the ambiguity issue was with more than one code host with the same type _and_ hostname, not just the same type. Am I mistaken here?

The number of the code host connections configured to sync repositories is not the problem.

The number of authz providers (i.e. occurrences of `"authorization"` as the keyword) configured for each type of code host connection is the problem.

In fact, when a customer configures multiple authz providers with exact same type and same hostname, it's not a problem, because permissions are mirroring from the same source of truth. So it's just a redundant configuration. 

However, with multiple authz providers with exact same type but different hostname, permissions are having different sources of truth and our current cache implementation could potentially cause one source overwrites the other in an undefined way.

> Also, there might currently be customers with more than one code host of the same type and hostname, so this should be a loud warning, rather than a hard error.

Agree, will change to warnings.

**Comment by unknwon** [comment]
> This should also be documented in the schema docs. Any way to enforce it there? Note: There are current customers who have configured multiple, see [#8597 (comment)](https://github.com/sourcegraph/sourcegraph/issues/8597#issuecomment-591903254)

Addressed concern in #8597.

**Comment by unknwon** [comment]
Had a video chat with @tsenart and we will solve this problem entirely by migrating to use permissions tables for RFC 113. Thus closing.

**Pull request closed without merging**
