### PR TITLE
Change symbols service discovery to default k8s

### PR DESCRIPTION
**Pull request by daxmc99**
Use k8s native service discovery (DNS)
Not our custom resolver logic

## Test plan

Manual review

### CODE REVIEW

**Review by michaellzc — APPROVED** [review]
lgtm

maybe also consider just removing the layer of `internal/endpoint` from symbols client? https://github.com/sourcegraph/customer/issues/1736#issuecomment-1381116245

**Review by abeatrix — APPROVED** [review]

**Review by keegancsmith — CHANGES_REQUESTED** [review]
This doesn't do service discovery though? If you have multiple replicas we won't route correctly and get more cache misses.

**Comment by keegancsmith** [comment]
To explain more deeply, when you do a request against `repo`, we use rendezvous hashing to pick a specific replica of symbols to go to. That means we always send the same request to that repo. This is because there is a whole bunch of work we do before we can search a repo that we want to keep in the local cache (in this case fetch repo, compute symbols).

By using the generic service address each time we get a request it will go to a random replica. That is why this is sub-optimal.

**Comment by daxmc99** [comment]
@keegancsmith  My understanding is that the `Symbols` service doesn't need 1:1 routing and that random or round-robin based routing (the default provided by the K8s Service) is acceptable in this case. 

@DaedalusG mentioned that we rarely see customers run multiple replicas of searcher.

**Comment by daxmc99** [comment]
@keegancsmith Also see https://github.com/sourcegraph/customer/issues/1736#issuecomment-1381116245

**Comment by DaedalusG** [comment]
> @DaedalusG mentioned that we rarely see customers run multiple replicas of searcher.

Replicas of searcher are uncommon but definitely not never done -- same with symbols, some deployments with very large repos are using replicas like sort of fail overs 🤷‍♂️ 

fwiw though the current strategy can present gnarly debugging as it violates cluster admin expectations:
https://github.com/sourcegraph/customer/issues/480
https://github.com/sourcegraph/customer/issues/1736

**Comment by keegancsmith** [comment]
> Also see 
> https://github.com/sourcegraph/customer/issues/1736#issuecomment-1381116245

I will continue the discussion there. I see a few things that from my
perspective are incorrect. It is possible things have changed in symbols
(maybe state doesn't live on the pod anymore?). However, for searcher, zoekt
and gitserver we require knowing the hostname of all endpoints.

**Comment by daxmc99** [comment]
Closing this PR as we solved the issue affecting the specific customer but I think there is still space here for a larger discussion. 

My position from experience is that while searcher is horizontally scalable, we rarely do this.  
Its also not trivial to scale up _stateful_ services where a specific datum exists on a single replica. Kubernetes doesn't have primitives for this without leaning on stateful sets (which have their own set of problems). 

Ironically, this is an area where things like service meshes usually help ensure connections are routed to the correct pods via things like headers, etc. 

Good defaults matter and ~~by default we deploy a single instance of searcher~~ 
Actually no, [we deploy two replicas](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph/-/blob/base/searcher/searcher.Deployment.yaml?L14)
So this PR would have been a performance decrease for our default deployments. 
Thanks @keegancsmith

**Pull request closed without merging**
