### PR TITLE
search: update changelog to mention addition of streaming search

### PR DESCRIPTION
**Pull request by limitedmage**

### CODE REVIEW

**Comment by rvantonder** [comment]
Going to flag this concern that I raised in https://github.com/sourcegraph/sourcegraph/issues/16423. If this goes in the changelog, customers will have the option to set streaming when they read this. IMO, even though it is experimental, it is _not_ enough to just say:

>  Note that not all search features are supported in this mode yet.

That's because, as I point out in I point out in https://github.com/sourcegraph/sourcegraph/issues/16423, it _breaks_ searches with operators (there are results, but they do not accurately reflect what the query means). So then the natural question for streaming is: how does it actually work and what does it assume? Can I trust any query does what it says? It is OK to say "not all search features are supported in this mode yet" but then I would expect there to be an alert for queries containing operators, for example, and not a broken search semantics.

This is my opinion, I defer to @lguychard and @christinaforney to make the call on risk/expectation.

**Comment by limitedmage** [comment]
> Going to flag this concern that I raised in #16423. If this goes in the changelog, customers will have the option to set streaming when they read this. IMO, even though it is experimental, it is not enough to just say:
> 
> > Note that not all search features are supported in this mode yet.

This is a very valid concern. We can postpone adding this to the changelog until it's more complete/stable.

**Review by keegancsmith — COMMENTED** [review]
I agree, lets only advertise this once we are happy with the experience.

**Comment by lguychard** [comment]
I think it's time to revive this :)

**Comment by limitedmage** [comment]
> I think it's time to revive this :)

Happy to get this in whenever we feel it's ready. Do we want to wait until it's turned on in cloud for sourcegraph org for a couple of days just to verify?

**Pull request merged**
