### PR TITLE
remove explore page

### LINKED ISSUE #5318: Discrepancy in reported repository count between admin and non-admin users
Reported by https://app.hubspot.com/contacts/2762526/company/554338610.

Repro:

* Visit /explore as a normal user and admin user
* In the “Repositories" section, a normal user just sees 4 repos and doesn't see the "view all" link at the bottom:
image
* An admin user sees the link, and can click to see all 7 repositories

No repository permissions have been configured on this instance.

### PR DESCRIPTION
**Pull request by sqs**
The explore page (at `/explore`) showed recommended extensions based on a hardcoded list, selected Sourcegraph editor/browser/CLI integrations, and a few repositories on the instance. It was intended to be a good place for users to visit to get set up with Sourcegraph. In practice, we never promoted it to users, never included it in our demo paths, and never spent any time maintaining it. We also never heard from users that it was helpful (or not). Based on this (intuition suggests it's not useful + lack of data to suggest otherwise), we should remove it.

Its intent is good and we should find a good way to accomplish its goals in the product, but good intent is not enough for a product feature to stick around (especially when it occupies a prominent link in the global nav).

Incidentally fixes #5318 and #4019.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Would insights be able to communicate these metrics instead?

**Comment by sqs** [comment]
Which metrics? I think the explore page’s content is too boring for insights.

**Comment by felixfbecker** [comment]
In the PR description you said "I am going to keep this PR as a draft until I have a proposal for slightly better messaging on the instance homepage", from which I inferred you wanted to put the content of the explore page in some way on the instance homepage (search landing page), which I also plan to have insights be able to contribute to.

I thought about "most popular extensions". I feel like any other metrics are too boring/not useful for any place in our app tbh. But if you feel like the entire content is too boring to be put on the instance homepage, then I must have misunderstood your last paragraph on why this is a draft PR for now?

**Comment by sqs** [comment]
I was thinking of putting the repos list and recommended extensions/integrations on the homepage. Those are interesting enough for the homepage (although dismissible or customizable, not always displayed), but they don't seem like "insights" to me.

**Comment by felixfbecker** [comment]
I see, agreed.

**Comment by AlicjaSuska** [comment]
@sqs I would like to come back to this topic as it connects with the work that I'm currently focusing on. My proposition is to entirely **get rid of the Explore page**. The reasoning:

1. **Takes up important space in the authorized users' top bar** 
I would like to use this place for the[ Extensions page](https://www.figma.com/file/7Ek89vyDoqlGhCn3wyS40J/11872-Extensions-discoverability-Final-review?node-id=93%3A1) to improve their discoverability and for easier access.
---
2. **Contents of the Explore page are being promoted in other places now**
- **Popular extensions** - we're making changes to the extensions registry to draw users' attention to the most useful ones. [New extensions registry](https://www.figma.com/file/7Ek89vyDoqlGhCn3wyS40J/11872-Extensions-discoverability-Final-review?node-id=86%3A648) page has categories and better filters. Also, language extensions are hidden at first to make others stand out more.
- **Popular integrations**
-> Browser extension - I'm working on the [RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing). I'm planning, among other changes, to add 'Browser extension' link to the Profile dropdown menu. Also, 'Browser extension' is added to the bottom of @rrhyne  [server page design](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing)
-> Sourcegraph CLI - this one is not addressed yet. If we see fit, maybe it can be added to the 'Explore and extend' section on the home page as well?
-> Editor extensions - they will have their own category in the [new extensions registry](https://www.figma.com/file/7Ek89vyDoqlGhCn3wyS40J/11872-Extensions-discoverability-Final-review?node-id=86%3A648)
- **Popular repositories** - we have repo groups now for cloud home page and repositories for [server home](https://www.figma.com/file/sPRyyv3nt5h0284nqEuAXE/12192-Sourcegraph-server-page-v1?node-id=255%3A1611) that @rrhyne designed. Also, the current link 'show all repositories' doesn't work anymore, it gives the error of 'too many matching repositories' 
---
3. **Explore page is not very popular now** ([16 views last month](https://analytics.google.com/analytics/web/#/report/content-pages/a40540747w150533180p155508056/_u.dateOption=last30days&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:~2Fexplore&explorer-graphOptions.selected=analytics.nthMonth) so removing it shouldn't cause any damage to the flow of our users

I'm looking for your feedback on this @sqs @christinaforney @felixfbecker @rrhyne @quinnkeast

**Comment by quinnkeast** [comment]
I support the idea of getting rid of the explore page. Like @AlicjaSuska says, its purpose and functionality is now distributed across several other, more purposeful channels, and it sounds like it's not providing much value today.

**Comment by sqs** [comment]
Yep, let’s remove it.

**Comment by AlicjaSuska** [comment]
Thank you! @felixfbecker FYI

**Comment by sqs** [comment]
Proceeding with removal

**Pull request merged**
