### PR TITLE
codeintel: consolidate enterprise & oss codeintel packages

### PR DESCRIPTION
**Pull request by Strum355**
Movin enterprise codeintel stuff (and ~two others that had to be dragged along) out of `enterprise/internal` and into `internal` as part of the shift towards enterprise-only

## Test plan

Successfully built frontend with bazel, CI will check the rest :sunglasses: no logic changed, just shufflin things around

### CODE REVIEW

**Review by efritz — CHANGES_REQUESTED** [review]
Embeddings movement might cause issues if we're abusing patch release for features in the near future.

**Comment by Strum355** [comment]
> Embeddings movement might cause issues if we're abusing patch release for features in the near future.

Was moved because we cant depend on `enterprise/internal/embeddings` from `internal/codeintel/*`

**Comment by camdencheek** [comment]
@efritz we can backport the move of the embeddings package. The enterprise split is a pain for embeddings already, and I don't want our bad release process to block us from making necessary changes.

**Review by camdencheek — APPROVED** [review]

**Review by efritz — APPROVED** [review]

**Comment by Strum355** [comment]
@camdencheek ive undone the changes to moving embeddings out of enterprise, as theres a lot going on here already. You can reopen and rebase your PR after this is merged if youd like :slightly_smiling_face:

**Review by efritz — APPROVED** [review]

**Pull request merged**
