### PR TITLE
HACK: Add syntax highlighting to reference panel

### PR DESCRIPTION
**Pull request by mrnugget**
Hacked `<CodeExcerpt />` into `ReferencesPanel`.

See video:

https://user-images.githubusercontent.com/1185253/191068687-374222a7-44f5-4c5b-97f7-48e8006de701.mp4

## Bugs/TODOs:

* ~VisibilityDetector in `CodeExcerpt` didn't seem to work in ref panel. Had to turn it off~ -> @vovakulikov fixed that! Thank you.
* You can't select text in the results. Cursor changes but you can't select it.
* Lots of prop drilling to get to that highlighting function.
* Off-by-one errors probably.
* ~The `bottom: -500` offset for the visibility detector is independent of the height of the panel. What if someone resizes panel at runtime?~
* ~Since we load the highlights lazily, it can feel a bit weird when scrolling fast~ -> I changed it to show plain text first before falling back to syntax highlighting.

## Design questions

**EDIT:** I added a small border between results

screenshot_2022-09-09_15 33 30@2x

## Test plan

- N/A

## App preview:

- [Web](https://sg-web-mrn-refpanel-code-excerpt.onrender.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by mrnugget** [comment]
@olafurpg @macraig I fixed the tests, so theoretically this _could_ be merged, but it has tradeoffs (see original PR description). I'll leave it up to you to decide whether this should go into 4.0 last minute (I'd personally say no, since it hasn't been tested that much really and I think the visibility-sensor offset thing and the non-working text selection bug don't give me great confidence)

**Comment by macraig** [comment]
@olafurpg what do you think of pushing this to 4.1?

**Comment by mrnugget** [comment]
Now that the branch has been cut, I'd say the bar is even higher to get this in.

**Comment by macraig** [comment]
@mrnugget I agree we should push this over to 4.1 given we don't have strong confidence in its current status, more so if the branch has already been cut.

**Comment by olafurpg** [comment]
I agree with delaying this until 4.1.

**Pull request closed without merging**
