### PR TITLE
release: Release `cody` to Open VSX Registry

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

Release `Sourcegraph Cody` VS Code Extension to Open VSX Registry.

**Suggestion**: We should have a common CI pipeline, which could detect file changes of both VS Code Extension (Sourcegraph & Sourcegraph Cody) and release automatically with a new changes. So, that it follows the consistent approach across the extensions & also avoid problems like this (https://github.com/sourcegraph/sourcegraph/pull/49408#issuecomment-1486147185)

## Test plan

Since, we don't have the CI to prepublish and test, we need to open in workspace and execute the following command (this requires OpenVSX PAT Token):

```sh
npm run ovsx:publish
```

> **Note**: You can use anything like yarn, pnpm to excute this command

### CODE REVIEW

**Comment by akosyakov** [comment]
@beyang would it be possible 🙏 We would like to try in Gitpod

**Comment by philipp-spiess** [comment]
This is awesome, thank you so much! I'll get this sorted!

**Review by philipp-spiess — APPROVED** [review]

**Comment by philipp-spiess** [comment]
https://open-vsx.org/extension/sourcegraph/cody-ai 🎉 

I’m not sure if it'll work with GitPod just yet as we rely on some binaries that won't work in a web worker context I’m afraid, but we'll get there!

Thanks for the contribution, really appreciate it!

**Comment by akosyakov** [comment]
> I’m not sure if it'll work with GitPod just yet as we rely on some binaries that won't work in a web worker context I’m afraid, but we'll get there!

Gitpod installs it on backend if an extension is not of web kind.

**Comment by philipp-spiess** [comment]
> Gitpod installs it on backend if an extension is not of web kind.

Ohhh awesome! TIL :)

**Pull request merged**
