### PR TITLE
Refresh: Further updates to various settings pages

### PR DESCRIPTION
**Pull request by umpox**
Further updates from this comment https://github.com/sourcegraph/sourcegraph/pull/21692#issuecomment-854141901

## Screenshots
image

image

image

image

### CODE REVIEW

**Comment by quinnkeast** [comment]
Some further QA on my part:

- [ ] For the code host connections and the sign in connection elements, we should use less padding (16px/1rem), and the dividing line should be full width. Here's the same two with some adjustments to reflect this:

CleanShot 2021-06-04 at 11 54 09@2x


CleanShot 2021-06-04 at 11 54 31@2x

- [ ] The code host icons on the code host connections view are too small. They should be the same size as on the sign in connections view.
- [ ] The "empty" dotted circle is too light. It should use `border-color-2`.

**Review by valerybugakov — APPROVED** [review]
LGTM!

**Comment by umpox** [comment]
@quinnkeast Good points, I have updated - please let me know if I have misunderstood or missed anything!

I'm not sure on the first point, the padding here is consistent with the other 'containers' we have used across the app + settings pages. I think changing the padding here won't be great for consistency in the code and UI. Likewise with the borders (although that would would be a little trickier to achieve as it would mean the border would have to break out of the padding within the container)

**Comment by quinnkeast** [comment]
Changes look good!

As to:

> I'm not sure on the first point, the padding here is consistent with the other 'containers' we have used across the app + settings pages. I think changing the padding here won't be great for consistency in the code and UI. Likewise with the borders (although that would would be a little trickier to achieve as it would mean the border would have to break out of the padding within the container)

Honestly, I'm fine leaving this for now. This is more a result of not having "designed" the settings pages with intention in the earlier stages of this project, so there's a lot of things that can be adjusted and improved and should probably be done separately.

**Pull request merged**
