### PR TITLE
insights: remove stray characters

### LINKED ISSUE #34219: insights: delete insight title contains stray characters
Title in modal for deleting an insight contains stray characters.

Screen Shot 2022-04-20 at 3 03 01 PM

### PR DESCRIPTION
**Pull request by chwarwick**
removed stray $
resolves #34219
## Test plan
visual compare:
Before: 
Screen Shot 2022-04-20 at 3 03 01 PM

After:
Screen Shot 2022-04-21 at 2 20 12 PM

## App preview:

- [Link](https://sg-web-cw-fix-delete-title.onrender.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by vovakulikov** [comment]
@AlicjaSuska do you remember did we add these character because it was part of the original designs for this modal?

**Comment by chwarwick** [comment]
> @AlicjaSuska do you remember did we add these character because it was part of the original designs for this modal?

@vovakulikov Looks like it is just the `$` that was not intentional and possible should be a `'` instead of ` 

I'll change it.

**Comment by chwarwick** [comment]
updated after image.

⬇️  from #32374
DELETE INSIGHT POPUP
Header: 'Delete ‘[insight name]’? (color: $danger-01)
Body: 'Are you sure you want to delete insight [insight name]? This can't be undone.'
Buttons: Cancel / Delete forever (button: danger)

**Review by vovakulikov — APPROVED** [review]
Oh, I misunderstood the problem @chwarwick sorry. LGTM

**Pull request merged**
