### PR TITLE
Add IDE CTA pings

### PR DESCRIPTION
**Pull request by vdavid**
**Important:** This PR builds upon #29966, merge that first, then rebase!

- Added a few lines to the site admin "pings" page, plus rationalized BExt ping description as well
- Added notes to pings.md, plus rationalized BExt ping description as well
- Added IDE CTA data to CTAUsage in types.go
- Added IDE CTA-related SQL to CTA query, plus rationalized existing query lines and renamed a few variables to accommodate for the larger amount of data
- Updated and ran the related test—it works as intended.

## Test plan

- Run `sg start`
- Check the latest ping on the site admin page to see if the new data is included there

### CODE REVIEW

**Comment by ebrodymoore** [comment]
All good on my end to merge this. Just updated the schema so these data points can be received! Please get a review from a software engineer instead of me though 😄

**Comment by vdavid** [comment]
@ebrodymoore said OK from their side, but I'll need another developer to take a look at the branch before I merge this.

**Review by attfarhan — APPROVED** [review]
Ping structure looks good!

**Review by slimsag — APPROVED** [review]
Nice job sorting through the madness here :)

**Pull request merged**
