### PR TITLE
[language-platform]: Update error message in autoindexing page when tags fails

### PR DESCRIPTION
**Pull request by Numbers88s**
Fixes https://github.com/sourcegraph/sourcegraph/issues/42434

Update error message in autoindexing page when tags fails
## Test plan
Run all the test.

clear

### CODE REVIEW

**Review by efritz — CHANGES_REQUESTED** [review]
@Numbers88s I don't think this fixes the linked issue. We shouldn't be blowing up the entire page when this occurs. The original problem is that if this particular gitserver issue happens that we can't see ANY data from the UI or GraphQL.

**Comment by Numbers88s** [comment]
> @Numbers88s I don't think this fixes the linked issue. We shouldn't be blowing up the entire page when this occurs. The original problem is that if this particular gitserver issue happens that we can't see ANY data from the UI or GraphQL.

Well should we be swallowing the error? This is happening in the index connection resolver, so if one of them can't resolve the tag then the whole index list errors out. Should I return nil instead of the error?

**Comment by Numbers88s** [comment]
> Is it possible on the UI side to show the error but render the rest of the data, if the error is of this particular class?

I don't think so. It's inside a resolver. And the way the UI component is written it checks for the whole data or an error. So afaik it'll do one or the other. Thats why I was thinking of sending nil for the tags instead of the error of "git not found". Again its for the whole list not a single one.

**Comment by Strum355** [comment]
> And the way the UI component is written it checks for the whole data or an error. 

Always irked me coz I swore graphql should let you return both data and any errors. Is this not possible with some part of our graphql stack or is it just not exposed today in the client side code?

**Comment by Numbers88s** [comment]
> > And the way the UI component is written it checks for the whole data or an error.
> 
> Always irked me coz I swore graphql should let you return both data and any errors. Is this not possible with some part of our graphql stack or is it just not exposed today in the client side code?

Currently we have a data or error functionality, not both. We could if we change what we send and its general structure.

**Review by efritz — APPROVED** [review]

**Comment by efritz** [comment]
> Is this not possible with some part of our graphql stack or is it just not exposed today in the client side code?

@Strum355 I believe that our idiom for loading data is: check for error, if present display it; else display the data. I know we get back `error` and `data` fields separately so it's completely possible on the client side (I think we just haven't done it anywhere).

**Comment by Strum355** [comment]
> > Is this not possible with some part of our graphql stack or is it just not exposed today in the client side code?
> 
> @Strum355 I believe that our idiom for loading data is: check for error, if present display it; else display the data. I know we get back `error` and `data` fields separately so it's completely possible on the client side (I think we just haven't done it anywhere).

Cool beans, thought it was one or the other coz it was always called `xOrError`

**Comment by Numbers88s** [comment]
@Strum355 Just putting this here if you're interested. https://itnext.io/the-definitive-guide-to-handling-graphql-errors-e0c58b52b5e1

**Pull request merged**
