### PR TITLE
searcher: combine line matches for the same line

### PR DESCRIPTION
**Pull request by camdencheek**
Previously, searcher was creating a new LineMatch for every fragment
matched. For long lines with many matched fragments, this meant
duplicating the content of that line many times in both allocations and
when serializing. This was causing significant memory issues in searcher
now that we don't have strict limits on the number of matches per file 
(when streaming is enabled).

At its most regressive, a regex query for `.` will return one fragment for 
every character in every file. Previously, for every fragment, we would
allocate a string with the line contents and serialize that line content. 
This means, for the query `.` and line length n, we were copying and 
serializing n^2 bytes, vs n bytes after this change. 

I have a feeling this will magically fix many of the OOMs I've been debugging,
since the query I was using to reproduce the OOM was just the string literal `to`.

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
Rubber stamping so you can get this in and will comment after if I see issues.

Aside: I think I ran into issues yesterday searching on unindexed repos for short strings! But I'm not sure if it was streaming changes or infra issues :-)

**Review by rvantonder — COMMENTED** [review]
Cool! This looks like an important change 😄 

I do wonder if there's a better way to build the result list. Like, instead of looking at the previous match and checking if it's on the same line, factor/restructure things so that we basically do:

```
for each line {
   for each fragment
     ...
   }
}
```

It _seems_ possible that we could create a `for` loop over each line, rather than sending multiple lines to `appendMatches`, and hopefully without incurring a perf hit to do one line at a time. So yeah basically create an `appendMatchesForLine` function and factor things out this way, I think might be cleaner.

**Comment by camdencheek** [comment]
> I do wonder if there's a better way to build the result list.

Yes, I agree. It's a little complex because a match can span multiple lines, and we don't (currently) know whether it spans multiple lines until we get into `appendMatches`. I wanted to keep this change as minimal and understandable as possible, but I think it can be made cleaner.

**Review by keegancsmith — COMMENTED** [review]
to be a little controversial... do we use the preview line in sourcegraph-frontend? I have a feeling we might not and we just use the ranges + fetching from gitserver for highlighting, but I may be wrong.

**Comment by camdencheek** [comment]
>  do we use the preview line in sourcegraph-frontend?

I don't believe we do. We _do_ use it for [Rijnard's new compute package](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/compute/match_context_result.go?L99:51&subtree=true), so I don't think we can immediately drop it.

However, I've also been thinking about whether we can drop it entirely. If we move towards streaming highlighted results (to avoid the highlight delay in the frontend), the compute package could use the full file contents we fetch for that.

**Comment by rvantonder** [comment]
> I don't believe we do. We do use it for Rijnard's new compute package, so I don't think we can immediately drop it.

Please don't let this newly-introduced experimental package be a reason to keep around preview :-) I can probably easily adapt things to work with a change.

>  I have a feeling we might not and we just use the ranges + fetching from gitserver for highlighting,

I need to look into how to fetch from gitserver within our frontend (so I can see how I could migrate to do things this way in `compute`). This has been an open question in my mind for a while. Anyone have a quick answer for that? 😛 

By the way `Preview` has been a thorny thing from an API perspective: https://github.com/sourcegraph/sourcegraph/issues/11134. My experience is: the `preview` item is/was a very convenient for rendering search results previews, but the spec is loose and any client relying on `preview` can create mismatched expectations (and burden) for backend (e.g., should preview support returning context lines?). I think we moved away from it in our client because of highlighting, but not sure. I would be in favor of moving away from using `preivew` and feel strongly that if we do we should completely remove `preview` from the API not leave it around to create mismatched expectations for clients.

**Comment by camdencheek** [comment]
> Anyone have a quick answer for that? 

We use [`(*GitTreeEntryResolver).Highlight()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/git_tree_entry.go?L106-115&subtree=true). We make a single graphql request per file to highlight. You can skip that step if you have the contents and just go straight to the `highlightContent` call that is nested in that method.

**Comment by keegancsmith** [comment]
Thinking out loud:

It is somewhat inefficient that we go and ask gitserver for some content which searcher/zoekt already has. If you do move to streaming highlighting, we should probably consider something like preview and/or zoekt's feature which returns file content.

The main downside of returning file content is we only highlight what is seen on screen which is much smaller than the number of matches usually. Maybe the ideal approach is something like Zoekt's MaxDocDisplay, but an "above the fold MaxDocDisplay" just for content.

... Starting to sound over engineered. Probably best to stick to asking gitserver :)

**Pull request merged**
