### PR TITLE
Automatically retry e2e on release branches; else soft fail

### PR DESCRIPTION
**Pull request by nicksnyder**
This is an alternative to disabling e2e tests outright, as proposed in https://github.com/sourcegraph/sourcegraph/pull/6163.

e2e test will still run on all branches so we can continue collecting data, but [failures will not block merging](https://buildkite.com/changelog/56-command-steps-can-now-be-made-to-soft-fail). Unfortunately, we still have to wait for tests to complete before getting a green status so there is no "builds are faster" win here.

In the cases where we do want to block on e2e tests (e.g. renovate branches, release branches), failures will be automatically retried once.

### CODE REVIEW

**Comment by nicksnyder** [comment]
I was hesitant to actually merge this because I was worried that it might reduce the amount of feedback (and examples) for test failures (therefore making it harder for us to actually fix the problem). Since we can track everything here: https://buildkite.com/organizations/sourcegraph/reports/job-retries I am less worried about this and think we can merge it.

One remaining question I have: do we think it is better to soft fail on branches or automatically retry once (and then soft fail)?

**Comment by unknwon** [comment]
@nicksnyder:
> I was hesitant to actually merge this because I was worried that it might reduce the amount of feedback (and examples) for test failures (therefore making it harder for us to actually fix the problem). 

I'm not sure if it's entirely possible or how hard/easy it is. Ideally, I want to have a new #buildkite-e2e channel which receives all the e2e failures notifications. Not to reuse #buildkite because I figure that's for the very purpose of monitoring builds on our `master` branch, and reduce noisy from anything that is not an e2e failure.

>Since we can track everything here: [buildkite.com/organizations/sourcegraph/reports/job-retries](https://buildkite.com/organizations/sourcegraph/reports/job-retries) I am less worried about this and think we can merge it.

It seems the report only shows stats of retires, but no clues about which builds were retried (or can we?). Nevertheless, it is still very useful to monitor the progress.

> One remaining question I have: do we think it is better to soft fail on branches or automatically retry once (and then soft fail)?

I think "soft fail on branches" is enough because the goal here is to collect flaky tests we expect to pass, retry in my mind is made for something totally unexpected failures (network issues on agents, no disk space, etc.). We need retry right now because of the hope to pass CI and it is required to merge a PR, but if we don't require e2e to be a blocker of PRs, retry is no more than another effort to capture more flaky tests.

WDYT?

**Comment by nicksnyder** [comment]
> It seems the report only shows stats of retires, but no clues about which builds were retried (or can we?). Nevertheless, it is still very useful to monitor the progress.

Oh you are right. When I looked on my phone this morning it looked like it linked to the retried builds, but you are right it just links to the project. Hmm. How can we get/generate a list of all failed e2e builds so we can audit that list for flakiness without depending on devs to proactively report failures?

> We need retry right now because of the hope to pass CI and it is required to merge a PR, but if we don't require e2e to be a blocker of PRs, retry is no more than another effort to capture more flaky tests.

I think I have convinced myself that this PR is good to merge.

This PR proposes to make e2e soft fail so flakiness doesn't delay merging. The benefit is that flakiness doesn't slow down devs, but we do incur a risk of a bad change landing in master. This is mitigated by the fact that a "real" failure will cause master to fail too (and it will be automatically retried once to confirm) so we should still be able to revert real failures out of master quickly. This optimizes for the observed reality that most failures are false negatives. If this turns out to not be the case moving forward we can reverse or adjust this decision (and also make progress on the actual flakiness in the meantime).

**Comment by nicksnyder** [comment]
> This is mitigated by the fact that a "real" failure will cause master to fail too (and it will be automatically retried once to confirm)

I am going to update the diff to make this statement true.

**Comment by unknwon** [comment]
>How can we get/generate a list of all failed e2e builds so we can audit that list for flakiness without depending on devs to proactively report failures?

I don't have admin access to "Sourcegraph" org on Buildkite.com, so I don't know what's the exact setup. But from my own organization, I can see the "Reports - Job Retries" is made by Buildkite and no customization available.

But I see the Slack integration they provide does have the ability I described:

Screen Shot 2019-10-29 at 5 02 00 PM

Notice the "Only some pipelines", it's empty for me because my organization has no pipeline, but I expect the Sourcegraph org has and we can choose just for e2e.

**Comment by unknwon** [comment]
BTW, I suggest to turn off "pass builds" notifications of `master` in #buildkite channel unless someone finds it useful. I believe only failure messages make the #buildkite channel more attractive when it has less noisy.

---

I just realized... I got the wrong concept of what a "pipeline" is... I'm looking into the APIs see if there any other way.

**Comment by nicksnyder** [comment]
> I propose to turn off "pass builds" notifications of master in #buildkite channel unless someone finds it useful. I believe only failure messages make the #buildkite channel more attractive when it has less noisy.

Not all passing builds post to #buildkite; only those that fix a broken build (e.g. to notify the channel that master is no longer broken). I do think that is valuable.

**Comment by nicksnyder** [comment]
I made you an admin on buildkite since you are looking into this stuff.

**Pull request merged**
