### PR TITLE
Don't observe sync storage in native integration

### PR DESCRIPTION
**Pull request by tjkandala**

### CODE REVIEW

**Comment by marekweb** [comment]
If this fixes the `sync` bug then I'd like to understand what was the incorrect assumption that led to the bug. My understanding is that this file isn't bundled in the native integration, but it's not clear to me why there is both a `IS_EXTENSION` constant and an `isExtension` value.

**Comment by tjkandala** [comment]
> but it's not clear to me why there is both a `IS_EXTENSION` constant and an `isExtension` value.

It looks like the constant is defined in files which aren't shared between the extension and native integrations

> If this fixes the `sync` bug then I'd like to understand what was the incorrect assumption that led to the bug. My understanding is that this file isn't bundled in the native integration

I started working on this PR after noticing that these were the only calls to `storage.sync` added in 3.20. However, since this code isn't bundled in the native integration, this can't possibly be the source of the bug.

I see that `onHoverAlertDismissed` is the only function called in the native integration that doesn't check `isExtension` before writing to `sync` storage. The user could be shown the "need private instance" alert if they aren't on a private Sourcegraph instance but are on a private Bitbucket Server instance, and dismissing the alert could cause this error to be thrown.

**Comment by tjkandala** [comment]
> but it's not clear to me why there is both a IS_EXTENSION constant and an isExtension value.

It looks like the constant is defined in files which aren't shared between the extension and native integrations

> If this fixes the sync bug then I'd like to understand what was the incorrect assumption that led to the bug. My understanding is that this file isn't bundled in the native integration

I started working on this PR after noticing that these were the only calls to storage.sync added in 3.20. However, since this code isn't bundled in the native integration, this can't possibly be the source of the bug.

**Thought**: [`observeSendTelemetry`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/code-hosts/shared/codeHost.tsx#L1100) seems to always read and write from `sync` storage (by way of `observeOptionFlag` -> `observeOptionFlags` -> `observeStorageKey`) regardless of `isExtension`. Could this be the cause of the issue? `observeStorageKey` doesn't catch errors, so it could conceivably throw the reported error.

**Comment by marekweb** [comment]
> Thought: observeSendTelemetry seems to always read from sync storage (by way of observeOptionFlag -> observeOptionFlags -> observeStorageKey) regardless of isExtension. Could this be the cause of the issue? observeStorageKey doesn't catch errors, so it could conceivably throw the reported error.

Good find -- I think that's might be exactly the problem.

I took a look and I went ahead and wrote a tentative fix for this -- added to this branch. Let me know what you think.

There's one other use of `sync` storage: in [`getActiveHoverAlerts`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/code-hosts/shared/hoverAlerts.tsx#L20:30-20:36). It's been like that for a long time so I'm not sure how to interpret it: are active hovers in fact broken in the native integration?

**Review by jeanduplessis — COMMENTED** [review]
I don't have enough context to comment on the overall solution, but what I do see here and based on my little understanding it seems sound.

**Review by felixfbecker — APPROVED** [review]
Taking a step back, we should think about how we can systemically prevent this:

1. Passing an interface around for storage instead of `if` statements with globals (i.e. _branch by abstraction_)
2. Disallowing reference to `browser.` global in the shared and native integration folders with ESLint (forcing interfaces to be passed in)

That shouldn't block this PR though.

**Comment by felixfbecker** [comment]
@sourcegraph/distribution can you release this in a patch release? @tjkandala we should probably also include a changelog entry 📝

**Pull request merged**
