### PR TITLE
Rename togglePatternType to setPatternType, get rid of toggled prop in RegexpToggle

### PR DESCRIPTION
**Pull request by attfarhan**
This PR changes the logic for toggling the regex selector in the search bar. Prior, the logic was "if we are currently searching literally and it changes, toggle the regexp button on" and "if we are currently searching in regexp and it changes, toggle the regexp button off". 

Now that there is a third option to search with `patterntype:structural`, the previous boolean logic does not have enough information to decide whether to toggle the button based on the previous state. This means that in the current behavior, if we switch from `literal` to `structural`, the toggle would be turned on (which we don't want).

This PR changes the state of the toggle button to be based on the current `patterntype`, where `patterntype = structural` implies that the toggle is off.

### CODE REVIEW

**Comment by rvantonder** [comment]
For visibility, this is based off of #7267 which I've already looked at.

**Comment by rvantonder** [comment]
Specifically, the changes in this file are needed: https://github.com/sourcegraph/sourcegraph/pull/7263/commits/aa7d11ac961ce188964c1a3a2a5d2f222e70ed37#diff-ebf054db77ad7310b66e80f52943fc81. Since I haven't had time to test these changes with this PR, we should hold off.

**Comment by rvantonder** [comment]
I added the URL changes in 6739469, but there are some other interactions that don't quite work. Example:

- start with `http://localhost:3080/search?q=+func&patternType=literal`
- type `patterntype:structural func` as the search query
- hit the regexp toggle button
- structural search is activated, and the URL changes to 
`http://localhost:3080/search?q=+func&patternType=structural`

This change will need more QA.

**Comment by attfarhan** [comment]
Our intention when building this was that `patternType` in the query is _always_ the highest precedence. So if you click the regexp toggle, and an opposite `patternType` is in your query, the `patternType` specified in the textual query would win. If you do `patternType:literal test` on https://sourcegraph.com/search, you'd see the same behavior as you describe for structural. I think as long as we're consistent with this, it's a decent enough compromise, in my opinion. Perhaps we should be more clear about this in the docs or somewhere, though. WDYT?

**Comment by rvantonder** [comment]
> you'd see the same behavior as you describe for structural

OK. Then It seems this is not specific to this change then, but I find it surprising. I.e., as a user it's not clear what takes precedence, and I don't think documentation is a good avenue for communicating this, since it should be intuitive (don't think anyone would be inclined to go and look it up or read through the docs unless they needed to). Besides that behavior, this looks good to me.

**Pull request merged**
