### PR TITLE
search: introduce ctx to QueryToZoektQuery

### PR DESCRIPTION
**Pull request by keegancsmith**
We want to be able to check feature flags. Alternatively we may want to
instead communicate this in the high level structs we pass
around. However, that was a more complicated change to understand but I
am happy to follow-up and do that. For now I want feature flags to allow
gating the new lang support which is causing some issues.

### CODE REVIEW

**Comment by tsenart** [comment]
I think @rvantonder would prefer to keep context out of this method. If you want access to the FlagSet, I think we could pass that in as a separate argument or as an additional field in searchResolver. It is already set by a middleware (https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/featureflag/middleware.go?L47&subtree=true), so it should be easy to get it from the context in the caller of toSearchInputs.

**Comment by rvantonder** [comment]
Agree with @tsenart. Propagating `ctx` isn't the end of the world but I've tried to keep it out of `toSearchInputs` (job creation) because it can lead to mixing concerns about runtime signals/deadline/cancellation etc. that don't really have a business to be in the static translation. So yeah I'd prefer if we do what @tsenart suggests which is to propagate the flags at the lowest point where we have context (this is `evaluatePatternExpression` caller) to the `toSearchInputs` function. It's easy to get it from this caller with:

`flagsToPass := featureflag.FromContext(ctx)`

About putting it in the resolver: could do and not the end of the world either but avoiding bloating the resolver would be great since we eventually don't want our search evaluation routine to depend on resolver values.

**Comment by keegancsmith** [comment]
I want to start using things like feature flags more often. My first instinct was to update the struct we pass in to have a field like `GenerateZoektLang bool` or something. But I wasn't sure which struct was best and how to thread through (relying on @rvantonder here for direction). I don't really like the idea of adding another arg to QueryToZoektQuery, since there are so many call sites and a feature flag is temporary. IE that is a lot of code churn for something that should be localized. Given those concerns, it seems like relying on ctx is the best bet since we already pass it around so much and I would like us to use feature flags a lot more (and this will be _the_ way to do it).

Another idea is something like `search.Features` struct which contains this and future feature flags (like we had for globbing/etc). This struct is then passed around in all `search.*Inputs`. That way keep this somewhat pure approach?

**Review by rvantonder — APPROVED** [review]
I like the idea of separate dedicated type as argument more (speaking as someone comitted to maintaining this code). Since we're already adding an argument I'd rather that argument reflect its intent (feature flag) than context (which is basically a generic proxy for feature flags and unlikely to be used for anything other than feature flags). So that's the extent of my 'guidance' :p If you want to roll with `ctx` it's ~fine and not worth bikeshedding over IMO

**Comment by keegancsmith** [comment]
To continue the bikeshed just a little bit more, I'd rather it isn't another argument to this function but is somehow part of a struct (or many). Do you have any guidance on that?

**Comment by rvantonder** [comment]
Right, yeah, I'm in favor if minting a new type with `query` and `featureFlag` fields as args to `toSearchInputs` (which should really become toSearchJobs` soon), above propagating args.

Brought to you by "When in doubt mint more types" gang

**Comment by rvantonder** [comment]
about where to mint that type, locally in this file seems OK. In time a majority of the definitions in `search/types.go` will go yo respective packages, so that's fine and will get moved out eventually. Other than that, `query_converter.go`?

**Comment by keegancsmith** [comment]
@rvantonder I sketched out a solution that feels good to me in https://github.com/sourcegraph/sourcegraph/pull/28969. Lets continue there and abandon this.

**Pull request closed without merging**
