### PR TITLE
JetBrains: Bump version to 2.0.0-alpha.3

### PR DESCRIPTION
**Pull request by philipp-spiess**
Let's release another preview build! I’m bumping the version and will ship once we merge #38707 cc @vdavid 

## Test plan

Just a version bump.

## App preview:

- [Web](https://sg-web-ps-jetbrains-alpha-3.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-yomztqzoox.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by vdavid — APPROVED** [review]
LGTM. Also merged the dependency, so we can go ahead with this!

**Comment by vdavid** [comment]
Oh, I just realized, did you rebase on the latest `main`, @philipp-spiess, to include the panda fix we were waiting for?

**Comment by philipp-spiess** [comment]
I'll release from `main` now, so this is not an issue :)

**Comment by vdavid** [comment]
Oh yeah, makes sense :)

**Pull request merged**
