### PR TITLE
Cody: Login screen CSS fix

### PR DESCRIPTION
**Pull request by deepak2431**
This PR improves some of the CSS styles.

## Test plan
Before:
iScreen Shoter - Code - 230622120803

After:
iScreen Shoter - Code - 230622135547

### CODE REVIEW

**Comment by deepak2431** [comment]
@abeatrix Can I have a review please?

**Review by abeatrix — APPROVED** [review]
You're the best 🚀

**Comment by deepak2431** [comment]
Thanks a lot, @abeatrix :)

**Comment by deepak2431** [comment]
@abeatrix The auto-quash didn't worked, can you merge this please?

**Comment by sqs** [comment]
<kbd>*semi-automated message*</kbd> Cody's source code has moved to a new repository, https://github.com/sourcegraph/cody. If you still intend to merge this change, please reopen your PR on that new repository.

The following are some of the path mappings from the old repository (https://github.com/sourcegraph/sourcegraph) to the new repository (https://github.com/sourcegraph/cody):

- `client/cody/ -> vscode/`
- `client/cody-shared/ -> lib/shared/`
- `client/cody-ui/ -> lib/ui/`

Thank you for the PR, and sorry for the inconvenience!

**Pull request closed without merging**
