### PR TITLE
bitbucketserver: Ignore host when replaying API fixtures

### PR DESCRIPTION
**Pull request by keegancsmith**
On CI we now set BITBUCKET_SERVER_HOST, which has lead to CI failing since we
now attempt to speak to the host. We speak to the host since the URLs now don't
match what is recorded in our fixtures. This commit updates the matching logic
so that we ignore the host and scheme, and instead only rely on the Path for
matching a request to a fixture.

### CODE REVIEW

**Comment by tsenart** [comment]
Nice! I think we need this in repo updater as well!

**Comment by unknwon** [comment]
Our CI now constantly fails on `"Get https://bitbucket.sgdev.org/rest/api/1.0/users?limit=1: Requested interaction not found"` e.g.: https://buildkite.com/sourcegraph/sourcegraph/builds/43102#ed8f5560-9c46-4083-bf8e-0e931ee68bbb

(above PR only has one line README change, also fails on other markdown-only PR, e.g. https://github.com/sourcegraph/sourcegraph/pull/5574)

Could this be related?

**Comment by unknwon** [comment]
Interestingly... I'm able to pass these failed tests locally, with `BITBUCKET_SERVER_HOST` set to `https://bitbucket.sgdev.org`.

**Comment by unknwon** [comment]
I found the problem, I'm not sure what was the exact reason, maybe it is related to the way how our Builtkite Agent "merges" a change from PR and test.

I rebased my branch based on **master** branch (which includes fixes in this PR), then CI passes.

I thought CI should merge changes with latest master then try to run tests, doesn't seem like so? Or am I missing something?

**Comment by keegancsmith** [comment]
it doesn't merge, its the same branch that you have.

**Comment by unknwon** [comment]
Thanks! That explains why I need to merge/rebase the master. 

But shouldn't it run tests as if the changes are merged into master? Otherwise, how does it ensure changes in my PR won't break master (say my branch is way behind master)?

**Comment by keegancsmith** [comment]
If your branch is way behind master then it might break tests. In practice this is very rare for our commit rate. But for example this is something that is often done in larger companies (or done by default in patch based review tools)

**Comment by unknwon** [comment]
In my case, that was exactly one commit behind (squash commit from this PR). But easily fixable by merge master, just wasn’t so obvious.

**Pull request merged**
