### PR TITLE
CodeMirror blob: Implement "click line to select"

### PR DESCRIPTION
**Pull request by fkling**
Relates to #41975 

The current blob view allows users to select a line clicking on the line itself outside of any actual text. This PR brings that functionality to CodeMirror as well.

https://user-images.githubusercontent.com/179026/193065624-b18d83f4-e7a7-41e8-ae58-870bf081df1b.mp4

## Test plan

- Click on whitespace after actual line content -> line is selected
- Click inside line content (comments work best because they don't trigger jump to definition) -> line is not selected
- Shift+click on whitespace after line content -> line range is selected
- Select text -> line is not selected
- Shift+click while text is selected -> text selection is extended

## App preview:

- [Web](https://sg-web-fkling-41975-cmb-blob-line.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-hisnuepkmx.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by olafurpg — CHANGES_REQUESTED** [review]
I tried this locally and noticed that the browser URL doesn't change when clicking on the right margin, unlike when I click on the gutter. Otherwise, this looks great and the interplay between text and line selection is pretty intuitive.

**Comment by olafurpg** [comment]
Also, I was unable to run `sg start` from the latest commit in this PR. I had to rebase on top of main to get the page loading. It seems unrelated to this PR, just an FYI if the build is failing for you too

**Comment by jjinnii** [comment]
Looks great @fkling, thanks for working on these changes! A couple of questions/comments: 

- That highlight blue looks much darker than the one that's currently implemented. It looks like you're using our link blue, not the bg highlight blue. Could you double check this? 
- I know it's not a part of the current file view, but I actually liked the underline upon hover on the line numbers to signify that it selects the lines. Was removing it intentional to more closely match current behavior? Thoughts on bringing it back?

**Comment by olafurpg** [comment]
> underline upon hover on the line numbers to signify that it selects the lines

+1 to keeping this change, I liked it as well even if it's different from the old blob. It's also the simplest way to tell that you have the CM blob enabled 😄

**Comment by fkling** [comment]
@olafurpg Thanks for catching that. I was so focused on the text selection interaction that I forgot that updating the URL is handled separately.

@jjinnii Do you mean the text selection color or the line selection color? The text selection is what the browser uses (at least for me with Firefox, I don't see any difference between the old and new blob view). The line selection color is the same as the old blob view (`var(--code-selection-bg)`).

**Review by olafurpg — APPROVED** [review]
LGTM 👍🏻 The URL updates now as expected

**Pull request merged**
