### PR TITLE
search: validate values of field index

### PR DESCRIPTION
**Pull request by stefanhengl**
With this change, I am adding validation for `index:` to the query package.
At the same time, I move the (misplaced) parser for YesNoOnly from the 
repos package to the query package.

In a follow-up PR I would like to add the value of the field `index` to `SearchInputs`,
because we want to use the value in at least two places.

### CODE REVIEW

**Comment by stefanhengl** [comment]
@rvantonder what is actually the preferred pattern moving forward? Should downstream code (graphqlbackend, streaming) keep accessing QueryInfo to extract values or do we add fields to SearchInputs whenever we need them in more than one place?

**Comment by rvantonder** [comment]
This is good for now!

We should aim to do go in this direction:

- Statically validate all values that we can up front (in `validate.go`). Once this is done, we know that any values (like index, etc.) is something we can convert to values that are valid at run time.

- Convert a query into an internal data structure that we use to evaluate a query. We don't have an ideal internal data structure yet, the closest we have is, say, [`TextParameters`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/types.go#L96) for text search. (Relatedly, why I pitched [`search.Parameters`](https://github.com/sourcegraph/sourcegraph/pull/17752#issuecomment-768897243, possibly as an initial way of defining this internal type).

> In a follow-up PR I would like to add the value of the field index to SearchInputs

Basically, I think go ahead. How this pans out specifically for something like `index`, would factor into 
a sketch of what we should aim to capture in an internal data structure, see this part in [RFC 254](https://docs.google.com/document/d/1_m63fsBMAtqaq3GA_aMzKUPxD3yxTy8d12lJE6qN6PU/edit#heading=h.s25eb1cluqod). We want to get to a place where we to use the value of `index` to create an internal data structure where the meaning (behavior and think we want to compute) is _implied_ (so that we can just case out on the type after doing the conversion from the `index value` to an internal `Query`, rather than check some argument passed 20 functions deep into the code, or access the value directly in the parsed query).

I.e.,

```
                                                                      .-- no -- create RepoQuery or whatever else this might imply (with value index:no to query DB, say, or, RepoQuery is just an alias for a DBQuery)
                                                                     /
                                     ,-- index:no -- is it text search? -- yes -- create UnindexedQuery	
                                    /
parse query -> parse index value ---
                                  |  \__ index:only -- is it text search? -- create ZoektQuery, resolve indexed repos (index implied)
                                  |                               \
                                  |                                `-- no -- create RepoQuery (with value index:only to query DB, say.)
                                   \
                                    `-- index:yes -- is it text search? -- yes -- create ZoektQuery, resolve indexed repos and create UnindexedQuery, resolve unindexed repos
                                                               \
                                                                `-- no -- etc.
```

This ^ is in contrast to what we do now which is, well, "just try to grab and validate whatever data we need  at the point where we're trying to make a decision (possibly from disparate data inputs because 🤷 )". This is only a sketch, subject to what we can pull off given crosscutting concerns, but I hope that's helpful?

**Review by rvantonder — APPROVED** [review]
Yay, moving `ParseYesNoOnly` up front into the validation function is good. 

Now, strictly speaking, we don't need to call `ParseYesNoOnly` in `search.go` if we guarantee the values are validated and normalized (invariant). But we do need a more convenient way to access the values than just `Query.StringValue(query.FieldFork)`. 

Once I remove the `Query.StringValue` interface it'll be better and we can get rid of these `ParseYesNoOnly` calls in `search.go`.

**Comment by stefanhengl** [comment]
This is really helpful. One really nice thing about casing out after creating an internal data structure is that we can gradually move to such a design from where we are right now. We could EG start casing out on indexed ZoektQuery against the "old" code path and then move one type after the other to the front. I think if we isolated the various code paths better we could move much quicker when optimizing them.

**Pull request merged**
