### PR TITLE
Remove owner from NoAlert observable

### PR DESCRIPTION
**Pull request by rafax**
Removing owner from monitoring definition we don't alert on. [Context](https://sourcegraph.slack.com/archives/C03L2R35ENL/p1704240126855279)
## Test plan

- CI

### CODE REVIEW

**Review by vdavid — APPROVED** [review]
Makes sense in the light of [this thread](https://sourcegraph.slack.com/archives/C03L2R35ENL/p1704716565040909?thread_ts=1704240126.855279&cid=C03L2R35ENL).

**Comment by vdavid** [comment]
Looks like CI needs `bazel run //doc/admin/observability:write_monitoring_docs_1` to be run on this branch.

I ran it as an attempt to help, but then our git hooks started making unrelated whitespace changes, at which point it seemed like my contribution might cause you more headaches than help, so I didn't push the changes.

**Comment by Strum355** [comment]
@rafax looks like the commit history of this branch needs a cleanup :grimacing:

**Comment by rafax** [comment]
> @rafax looks like the commit history of this branch needs a cleanup 😬

Yeah, I tried to use a tool for stacking PRs but clearly used it in a wrong way :/ will fix, thanks for pointing that out.

**Comment by rafax** [comment]
Version without messed-up Git history.

**Pull request closed without merging**
