### PR TITLE
Wildcard [Charts]: Move charts to the wildcard package

### PR DESCRIPTION
**Pull request by vovakulikov**
Closes https://github.com/sourcegraph/sourcegraph/issues/39955
Blocker for https://github.com/sourcegraph/sourcegraph/pull/40138

## Background
Code Insights team is working on a new UI for the search result page. This UI implies using chart components on the search page. Currently, the chart components are stored in the `web` package. The web package depends on the `search-ui` package. If we want to reuse chart components in the `search-ui` package, this will lead us to cyclic dependency (web → search-UI → web). 

In order to resolve this, we have to move chart components into a separate package (or wildcard package). The chart components are consumer agnostic, don't use any code insights specific logic and already have been used in more than one place in the app (at the moment, they have two primary consumers, code insights and site admin page). So based on this, I think putting them in the wildcard makes sense. This also may lead to better usage since they will be more accessible. 

## Follow-ups
- Currently, chart components don't have good docs, we have an issue, and this will be addressed later (but I hope shortly) https://github.com/sourcegraph/sourcegraph/issues/39878
- Chart components don't have a clear design in the Figma wildcard components. https://github.com/sourcegraph/sourcegraph/issues/40210
- https://github.com/sourcegraph/sourcegraph/issues/40253

## Test plan

- Make sure that code insights don't have any visual regressions
- Make sure that site admin pages don't have any visual regressions

## App preview:

- [Web](https://sg-web-vk-move-charts-to-wildcard.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-jqiibmgzpk.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by vovakulikov** [comment]
@sourcegraph/frontend-platform-devs can you help me out with test errors here? It seems that the Chart Tooltip component isn't able to import other parts of the wildcard (`createRectangle` helper) and fails with `TypeError: (0 , _wildcard.createRectangle) is not a function` is it a known limitation?

**Comment by vovakulikov** [comment]
It seems like this problem with `createRectangle` comes from the line in tooltip component where I have `const TOOLTIP_PADDING = createRectangle(0, 0, 10, 10)` in module scope. But I don't a clear reason why this is a problem for test runner

**Comment by vovakulikov** [comment]
It gets even more interesting if I move ` const TOOLTIP_PADDING = createRectangle(0, 0, 10, 10)` from the module scope to the react component scope, then this problem just goes away, I don't fully understand why

**Review by valerybugakov — COMMENTED** [review]
@vovakulikov, the issue with the `createRectangle` in tests is caused by circular imports inside the `wildcard` package. Replacing absolute imports with relative ones fixes the issue. See the screenshot attached. 

It is not a problem with `webpack` because it can evaluate modules "smartly" going through the circular dependency graph. And tests fail because there's no smart evaluation mechanism — they are just executed as is and some variables in the circular dependency graph are still uninitialized: `TypeError: (0 , _wildcard.createRectangle) is not a function`. 

We must always use relative imports inside the package to avoid such issues until we have a better mechanism (e.g., path aliases to enable absolute imports in packages). Also, in this particular case, it seems that geometry models defined in the `Popover` component should live in the shared folder outside of the component since `Chart` components also depend on them.

Let me know if this makes sense!

Screen Shot 2022-08-11 at 16 04 15

**Review by valerybugakov — COMMENTED** [review]
We need to replace [global `@sourcegraph/wildcard` imports](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+rev:vk/move-charts-to-wildcard+file:client/wildcard/src/components/Charts+from+%27%40sourcegraph/wildcard&patternType=standard) inside the `Charts` folder.

**Review by valerybugakov — COMMENTED** [review]
Excited to have charts inside of the Wildcard component library. Eventually, it should make charts UI consistent across our client applications and features in the monorepo. The @sourcegraph/code-insights-frontend team has done an excellent job building and testing these abstractions in production, and it's great that other teams will have more exposure to available components thanks to this change! 

Thanks, @vovakulikov! 🎉

**Review by valerybugakov — APPROVED** [review]
Thanks!

**Comment by vovakulikov** [comment]
Thanks for your review @valerybugakov. I filed an issue about the wildcard and small package follow-up here https://github.com/sourcegraph/sourcegraph/issues/40253

**Pull request merged**
