### PR TITLE
user invites: add collaborator discovery / email invites option

### LINKED ISSUE #27101: User invitations
User invitations will allow users who have signed up for Sourcegraph to invite their friends and colleagues to the service. This feature can be placed in multiple locations within the application to maximize the chance of users inviting others to the application. 

There are two types of invitation features:

* A form that allows users to manually add email addresses, then send invitations via email
* A feature that extracts collaborators email addresses from a user's repositories and allows the user to invite those users to Sourcegraph

More information [in this RFC](https://docs.google.com/document/d/1Nsg6wneYlOQWzVXeQjS93zdd-MewGyv4gARB6_PHQOo/edit?usp=drive_web&ouid=107037782400977645523).

## Acquisition
These features can be included in multiple flows within the application: 

* After (or on) the post sign-up repositories saved stage
* On the homepage
* After the repositories selection process in the repositories settings page
* In the team creation form

Note:
_These features should be considered independent from teams functionality because we need to allow individual users to invite collaborators outside of a team context. That said, they should be developed in such a way as to also empower the team functionality 

## What metrics will signal this effort is successful?
* The experiment produces a viral coefficient greater than 1.

### PR DESCRIPTION
**Pull request by slimsag**
This PR implements #27101

image

## How to test this branch

Run with `sg start dotcom`, navigate to https://sourcegraph.com/welcome?debug=1 and select a few repositories that should have collaborators in their commit history. Navigate to the third step and they should show up.

**Important:** Actual email sending is not yet implemented here, so once you click the invite buttons they'll just switch to loading state infinitely.

## TODO before merge

* [x] @philipp-spiess We need the `CopyableText` for user invite URLs needs to log an event, e.g. `UserInvitations_CopiedInviteLink` I think we'll need to send another PR to add an `onCopy` callback to `CopyableText` so we can implement this.
* [x] @philipp-spiess After my changes here, the `StartSearching` function is now quite lengthy! We should refactor this so it instead uses `UserInvites` and `ActivityLog` components probably, maybe defined in the same `StartSearching.tsx` file though since they're really the same page?
* [x] @slimsag We need it to actually make the GraphQL request to send email invites. I'm working on the backend for this now.
* [x] @philipp-spiess or @slimsag: Is the way we're logging events here OK? https://sourcegraph.slack.com/archives/CN4FC7XT4/p1643836277948139
* [x] @philipp-spiess or @slimsag there appears to be some caching bug: if you first select one repository that doesn't have any (or very few) collaborators, you'll see those in the UI. But then if you go back and select more repos that should have many more collaborators, no further GraphQL request is made. I suspect because it doesn't change the Apollo request that `useExternalServices` makes but I am a n00b here. Not sure how to solve this yet.
* [x] @rrhyne I took some liberties with the design to account for not including the repo name in the list, which me and Rob agreed to, would like him to look over what I've done here and confirm this looks okay from a design POV.
* [x] *new* Update "Invite all" button text to "Invite [N] users" [from figma](https://www.figma.com/file/9KUQex1haXP6BpC2wDgtXC/Inviting-collaborators?node-id=734%3A7022)
* [x] *new* Update the paragraph of text below the "Introduce friends and colleagues to Sourcegraph" header at top of page to new text from [from figma](https://www.figma.com/file/9KUQex1haXP6BpC2wDgtXC/Inviting-collaborators?node-id=734%3A7022)
* [x] *new* Right now I removed the loading indicator instantly (when the request to send the email invite would've finished), but we need to change this to display the green check mark + invited text instead. https://github.com/sourcegraph/sourcegraph/pull/30595/files#diff-2246aaf22cb3ef43fd5b5dd7695b7b37f0bc52183c8a2bb9f08b86563344529aR184-R186

## Dependencies

* [x] https://github.com/sourcegraph/sourcegraph/pull/30589
* [x] https://github.com/sourcegraph/sourcegraph/pull/30591
* [x] https://github.com/sourcegraph/sourcegraph/pull/30592
* [x] https://github.com/sourcegraph/sourcegraph/pull/30613
* [x] https://github.com/sourcegraph/sourcegraph/pull/30777
* [x] https://github.com/sourcegraph/sourcegraph/pull/30780

Fixes #27101

### CODE REVIEW

**Comment by slimsag** [comment]
@philipp-spiess OK, I merged all the PRs and rebased against `main`. I'm focusing on the backend, you focus on the remaining frontend work here and we'll sync up to see where we land next week (totally fine if you don't get to all of it) :)

**Review by philipp-spiess — APPROVED** [review]
I am biased but I do think this is great! When playing with it I noticed some issues with the activity log jumping between loading states too often. I do think that these are unrelated to our change but I'll verify to be 100% sure tomorrow.

**Comment by slimsag** [comment]
OK @philipp-spiess

**Make sure you run with `DEBUG_EMAIL_INVITES_MOCK=true sg start dotcom` (so it just prints to console when it would normally send an email) otherwise you really will send real emails from your dev server!**

Here's my update:

* Your changes look good.
* Please review these two backend PRs for me:
  * https://github.com/sourcegraph/sourcegraph/pull/30777
  * https://github.com/sourcegraph/sourcegraph/pull/30780
* I force pushed: rebased on `main`, and temporarily merged my two backend PRs above into here for testing.
* I fixed the "my own email shows up in the list" issue you mentioned

Everything works now end-to-end: you can invite real people from the flow.

---

Once those two PRs are approved, and you're happy with the frontend changes here, I'll merge all 3.

**Comment by philipp-spiess** [comment]
> When playing with it I noticed some issues with the activity log jumping between loading states too often. I do think that these are unrelated to our change but I'll verify to be 100% sure tomorrow.

I can confirm that this is also happening on `main` without any of our changes. This seems accepted as the backend state never returns anything other than `cloned: true`. Perhaps all my test repos are simply indexed already?

I noticed another issue that happens only if you add _a lot_ of repos (i.e when adding 500 repos): For some reason the `EXTERNAL_SERVICES_WITH_COLLABORATORS` query is reloading sporadically when this is happening. I tried finding out why exactly this is the case (i.e something must be fiddling with the cached object here) but I still am not sure. Given the rarity of this issue and the relatively low impact (=> It will reload the contributors list and render more contributors) I'd say this is okay for now. 

I guess the better cleanup here would be to move the logic to update the synced repos away from the page load here altogether but that's a bigger change and it needs a different UI as well (i.e where do we show the loading indicator for that?). 

So TL;DR: You have my go!

**Pull request merged**
