### PR TITLE
search: use minimal zoekt listing for select:repo

### PR DESCRIPTION
**Pull request by keegancsmith**
This is the first user of zoekt's minimal listing. We also update the
zoekt aggregator to aggregate minimal listings.

Co-authored-by: @tsenart

### CODE REVIEW

**Review by camdencheek — APPROVED** [review]
Nice!

**Review by stefanhengl — APPROVED** [review]
LGTM

**Comment by tsenart** [comment]
@keegancsmith: Any reason for holding off on merging this?

**Comment by keegancsmith** [comment]
> @keegancsmith: Any reason for holding off on merging this?

CI was failing, I forced pushed a fix on Friday afternoon. I think you reviewed this shortfly after that :) Will merge today.

**Pull request merged**
