### PR TITLE
executors: Handle pod that is never scheduled

### PR DESCRIPTION
**Pull request by Piszmog**
If a pod cannot be scheduled in a node it will sit in pending state forever. Eventually the scheduler will delete the pod. I added a check to look at the deletion timestamp to see if the scheduler deleted the pod.

When this happens, I want to bubble up a more helpful error instead of waiting for the context timeout.

## Test plan

Added additional tests.

### CODE REVIEW

**Review by efritz — APPROVED** [review]
Out of curiosity, is the change of moving the deletePods from defer to Teardown necessary for this solution?

**Comment by Piszmog** [comment]
@efritz no, this was just a bug I am fixing that I found while inducing this edge case

**Review by danieldides — APPROVED** [review]
LGTM

**Review by danieldides — APPROVED** [review]
LGTM

**Pull request merged**
