### PR TITLE
all: migrate to github.com/inconshreveable/log15

### PR DESCRIPTION
**Pull request by keegancsmith**
We currently use gopkg.in/inconshreveable/log15.v2, which points to
github.com/inconshreveable/log15. However, recently goimports started inserting
github.com domain instead of the gopkg.in domain. This also seems to be the
prefered import path based on the documentation / import paths in the log15.

### CODE REVIEW

**Comment by mrnugget** [comment]
Finally! 🙏 

> However, recently goimports started inserting
> github.com domain instead of the gopkg.in domain.

I think it's been doing that for me ever since I joined Sourcegraph and I had to manually fix the import path every time.

> No campaigns for this? @mrnugget

That was my first thought when I saw the PR description 😎

**Comment by unknwon** [comment]
> > No campaigns for this? @mrnugget
> 
> That was my first thought when I saw the PR description 😎

Send PRs to all repos with a go.mod file!

**Comment by creachadair** [comment]
> > However, recently goimports started inserting
> > github.com domain instead of the gopkg.in domain.
> 
> I think it's been doing that for me ever since I joined Sourcegraph and I had to manually fix the import path every time.

I think goimports has preferred the canonical import path for several releases now. Since this module doesn't declare one, the `github.com` path is preferred by default, so I'm surprised this is only happening for you recently. Is it possible you recently upgraded to a newer version of `goimports`? I've had stale versions before, since it's not part of the default install.

**Comment by keegancsmith** [comment]
I mispoke when I said recently. What I meant was recently it annoyed me enough to make the switch :) Yes this has been plaguing me for a long time.

**Pull request merged**
