### PR TITLE
db: add gitserver_repo_migration_cursor table

### LINKED ISSUE #32313: gitserver: Create a table for the rendezvous migration
Create a table that will host the progress of the migration to Rendezvous hashing. 

- cursor: Name of the last migrated repository, can be null

### PR DESCRIPTION
**Pull request by asdine**
Adds a table to host the migration cursor.
Fixes #32313

## Test plan

Tested with sg migration up and undo

### CODE REVIEW

**Comment by ryanslade** [comment]
Weren't we going to use the `metadata` column on the OOB migration?

**Review by sashaostrikov — APPROVED** [review]
LGTM!

**Comment by asdine** [comment]
We have chicken and egg problem:
- Every component of the migration needs the cursor
- If I understand correctly, adding an OOB migration line in the `out_of_band_migrations` table triggers the migration starting at the version specified with `introduced_version_major`. It seems that it should be added at the end of the development?

But now that I think about it, we could simply add an API to get the cursor, that API would return 0 for now and would then be updated later to get the cursor from the metadata of the OOB row.

I'll close this and do it that way. I'm open to suggestions though

**Comment by ryanslade** [comment]
That sounds good to me 👍

**Pull request closed without merging**
