### PR TITLE
user invites: Disable user invites when instance signup is disabled and on on-prem

### LINKED ISSUE #32123: user invites: What do do with the collaborators home page panel when admins have sign-up disabled?
From the question here: https://github.com/sourcegraph/sourcegraph/pull/31406#discussion_r817210590

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes #32123

When an instance has signups disabled, there's no value in our feature so we might as well disable it?

Additionally this force-disables this feature on non .com instances for now.

## Test plan

I configured the server as suggested below and verified that the variables have the correct value by adding `console.log` statements:

Screenshot 2022-03-08 at 11 51 13

Screenshot 2022-03-08 at 14 01 04

### CODE REVIEW

**Comment by slimsag** [comment]
In a dev instance, to test this change you can edit `../dev-private/enterprise/dev/site-config.json` like so:

```diff
diff --git a/enterprise/dev/site-config.json b/enterprise/dev/site-config.json
index 5e52b33..01f19b7 100644
--- a/enterprise/dev/site-config.json
+++ b/enterprise/dev/site-config.json
@@ -21,7 +21,7 @@
   "auth.providers": [
     // AUTHENTICATION
     //
-    { "type": "builtin", "allowSignup": true },
+    { "type": "builtin", "allowSignup": false },
     //
     //
     // See dev/auth-provider/README.md for more information on how to use the Keycloak OpenID/SAML
```

We should also disable this for non-dotcom instances, too, for now. You can just check if `window.context.sourcegraphDotComMode` is false and disable in that case. (then we'll remove that once we want to ship this to on-prem customers)

**Review by limitedmage — APPROVED** [review]
I think you can repro by editing your site config at https://sourcegraph.test:3443/site-admin/configuration and disabling `allowSignup` inside of all items in `auth.providers` (or maybe just the built-in one?)

Should the panel be disabled if built-in auth is disabled but other auth methods like GitHub, Okta, etc have sign ups enabled?

**Comment by slimsag** [comment]
`allowSignup` is only a valid option in builtin provider FYI, other providers have no such config option.

Also, note that `window.context.allowSignup` checks if *any* of the providers have the option set to `true`.

> Should the panel be disabled if built-in auth is disabled but other auth methods like GitHub, Okta, etc have sign ups enabled?

Great question. The current behavior here would be that if (a) builtin auth is enabled (b) `allowSignup` is configured to `false` and (c) you have OAuth configured, then it may be the case that users can sign in via OAuth but not builtin auth on your instance and we would not show it in this case.

In an ideal world, I think we would still show it in this case, as it's quite likely your instance has "open registration" in this case and builtin auth is just reserved for a small group of people (maybe initial users before OAuth was configured.)

In practice, this behavior is probably fine. I doubt many people actually have that configuration, excluding managed instances where that is indeed the case today but won't be in the future (migrating away from basic auth there.)

Good to go with the current behavior of this change IMO.

**Review by slimsag — APPROVED** [review]

**Comment by limitedmage** [comment]
> `allowSignup` is only a valid option in builtin provider FYI, other providers have no such config option.

`allowSignup` definitely exists for the other auth providers and lets you, for example, create a new account when clicking the "log in with GitHub" button. If `allowSignup` is enabled, users that aren't registered yet will have an account created when logging in with GitHub. Otherwise they will get an error.

**Comment by philipp-spiess** [comment]
> Should the panel be disabled if built-in auth is disabled but other auth methods like GitHub, Okta, etc have sign ups enabled?

Since we only send invited users a link to the `/sign-up` page, we should probably use the same gating that we use for that page. 

Looking at the code it seems to use `context.allowSignup` as well, so if _any_ auth provider allows sign up, the page will be accessible to users: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/auth/SignUpPage.tsx?L50-52

**Comment by slimsag** [comment]
> `allowSignup` definitely exists for the other auth providers

Huh, TIL! Thanks for mentioning this! I think I got confused by this comment in code:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8d47b9d509f701d31fa3f287d750ce9c95ad6ce4/-/blob/internal/conf/auth.go?L34-35

**Comment by limitedmage** [comment]
@slimsag Oh interesting, I think this comment is outdated. When doing the recent ToS work I had to debug all of these odd scenarios and I can confirm the flag indeed works for other providers like GitHub.

**Pull request merged**
