### PR TITLE
Migrate search export to the core workflow

### PR DESCRIPTION
**Pull request by taras-yemets**
Migrates [search-export extension](https://github.com/sourcegraph/sourcegraph-search-export) functionality into the core workflow.
Closes https://github.com/sourcegraph/sourcegraph/issues/38379

**Notes on implementation**
1. This PR migrates the existing extension functionality with known limitations (we do not actually export all search results found, but only a certain portion of it, what actually the [`query SearchResults` returns](https://github.com/sourcegraph/sourcegraph-search-export/blob/master/src/extension.ts#L73)).
2. There are [2 extension specific user settings](https://github.com/sourcegraph/sourcegraph-search-export/blob/master/src/extension.ts#L38-L39):  `searchExport.searchPatternType` and `searchExport.maxMatchContentLength`. We migrate the former but ignore the latter as it targets Sourcegraph versions [prior to 3.29](https://github.com/sourcegraph/sourcegraph-search-export/blob/master/src/extension.ts#L50-L62), and the migrated functionality will be available only for 4.0+ Sourcegraph users.
3. The only visual change in the regular UI is the export button text; notification behavior remains the same.
4. Export search results button is added to the simple UI actions dropdown.

| Extension | Core workflow feature |
| -- | -- |
|  Screenshot 2022-08-02 at 17 54 03Screenshot 2022-08-02 at 17 53 22 | Screenshot 2022-08-02 at 18 22 03 Screenshot 2022-08-02 at 17 53 22|
||Screenshot 2022-08-03 at 15 19 27|

## Test plan
1. `sg start web-standalone`
5. Enable `sourcegraph/search-export` extension
6. Search for something, click "Export search results" button and download the suggested file
7. Enable `extensionsAsCoreFeatures` experimental feature in user settings.
8. Repeat step 3 and ensure the same search results are downloaded.

## App preview:

- [Web](https://sg-web-taras-yemets-migrate-search-export.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-axsvitqpee.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by jjinnii — APPROVED** [review]
LGTM, the actual UI for how the search exports should look/behave will be worked in a later PR :)

**Comment by taras-yemets** [comment]
https://github.com/sourcegraph/sourcegraph/pull/39450/commits/006d9a2a6f6d37bce038e1efa52b8d650ad0c33d adds Export results button to the simple UI dropdown.
Screenshot 2022-08-03 at 15 19 27
FYI: @jjinnii

**Comment by jjinnii** [comment]
Ah okay sorry I missed that. That should be fine, there didn't seem to be outstanding feedback from the designers either than potentially changing the menu dropdown names, but that can always be done in a later PR.

**Comment by taras-yemets** [comment]
@jjinnii, you haven't missed anything! I just added this commit and updated you that [this comment](https://www.figma.com/file/7bVINrmqfDpxmLx3gv1uVa?node-id=2123:8726#239187997) is addressed.

**Review by abeatrix — APPROVED** [review]
Confirmed the search export works as expected.

**Review by philipp-spiess — APPROVED** [review]
NASA LGTM

**Comment by taras-yemets** [comment]
@jjinnii,
When we click on the export search results button multiple times (with the same or changed query/pattern type), we get the same notification with a download link multiple times in a row. The only thing that changes in the notification is the download link URL, the notification text doesn't indicate search results for which query are about to be downloaded ([Loom](https://www.loom.com/share/be9e89791f4f473bb8db41bfac2b57ab)).
I'm thinking about how we can improve this experience. Should we ignore consecutive export button clicks if the query didn't change and replace the existing notification if it did change (so that we have a max 1 export results notification at a time)? Ot should we include the search query/pattern type indicator in the notification message so that it's clear what results we are going to download? What do you think?

**Comment by philipp-spiess** [comment]
My 5ct: I think what would be really cool is to get a progress indicator inline (so rendered in the menu). E.g. when the query takes longer than expected, some kind of feedback would be great! Can we disable the menu bar entry when a download is started and render a loading indicator inside of it until it finishes (or fails) and the notification pops up? 😬

**Comment by jjinnii** [comment]
@taras-yemets Taking a look at this! Just a quick clarification question. In the Loom, you're clicking "Cancel" instead of actually saving the export, and yet the downloads are still happening. Was that just in the Loom, and I'm assuming the questions here about in the instances a user:
* Proceeds with multiple downloads because the previous download is taking too long and there isn't a confirmation, or just user error?

**Comment by taras-yemets** [comment]
@jjinnii, I click the export button and then the download button in the notification shown. Then I refuse to save the file, but the notification I clicked the download button from remains open. 
Then I click on the export button again and get a new notification, click the download button again, and refuse to save the file. I have one more open notification.
After I change the search query I click the export button again and refuse to save the file. I have one more notification with the same text, but with a different download link.

**Comment by jjinnii** [comment]
@taras-yemets Sorry I'm still not understanding, why would we show a "Search export is complete" notification when the user has chosen to "cancel" the search export action?

**Comment by taras-yemets** [comment]
@jjinnii, the notification says that search export results are _ready for download_. When the download button on the notification is clicked, the file download dialog is opened (the download process starts if you click the save button).  
I agree that the notification text may seem confusing. I just took the text from the search-export extension.

**Comment by jjinnii** [comment]
OHH okay so sorry. So that green checkmark saying "Search results export is complete" is actually saying  "Search results export is ready for download". 

Okay agreed that the verbiage needs to be changed + the stacking behavior is not great, although that's less a concern for me rather than the copy.

I will work on providing quick designs for this after my dinnertime by today! cc: @taras-yemets

**Comment by jjinnii** [comment]
As discussed[ in Slack ](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1660133768048839), please add a loading state within the menu to the[ right of the "search exports" action](https://www.figma.com/file/7bVINrmqfDpxmLx3gv1uVa/Sunsetting-extensions?node-id=2314%3A10700). As the user has already decided to click on downloading a search results file, we're moving forward with a solution that gets rid of an additional "download file" and going straight into file download after the file preparation is complete. 

Please share a Loom once this is implemented for quick UI review @taras-yemets !

**Comment by taras-yemets** [comment]
>please add a loading state within the menu to the[ right of the "search exports" action](https://www.figma.com/file/7bVINrmqfDpxmLx3gv1uVa/Sunsetting-extensions?node-id=2314%3A10700).

@jjinnii, it appeared that the export result item click (as well as any other item click) in the file actions menu triggers menu close, so there's no possibility to see the loading state of the button. What do you think about the current state ([Loom](https://www.loom.com/share/66929197d8e64404b0a2d6d79b911c3d))?

**Comment by jjinnii** [comment]
@taras-yemets I'm a bit confused by the Loom! I see no latency and also no loading state in your video -- could you explain a bit more what your alternative solution is?

**Comment by taras-yemets** [comment]
> I see no latency and also no loading state in your video

@jjinnii, there's no latency as search results request takes not that much time to resolve, and there's no loading state as any menu item click triggers immediate menu closing. The search results actions menu uses the wildcard [Menu component](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/wildcard/src/components/Menu/Menu.tsx), which uses the [Reach-UI Menu components](https://reach.tech/menu-button/) under the hood and closing menu on item click seems the default behavior for the latter.

**Comment by jjinnii** [comment]
@taras-yemets  Right I understand that the menu closes automatically after selection, so we _can't_ show the loading state as in my designs. My question is rather did we need the loading state in the first place? I was under the impression that preparing the file could have a bit of a wait -- should I create a design for a loading state that does not utilize the menu component?

**Comment by taras-yemets** [comment]
@jjinnii,
>Right I understand that the menu closes automatically after selection, so we can't show the loading state as in my designs

Correct.

 > My question is rather did we need the loading state in the first place? I was under the impression that preparing the file could have a bit of a wait
 
 Theoretically, it may take some time, but I've never experienced that (even on fast 3G). We request not all the search results (including `count:all` in our query may take ages to resolve), but a portion of them, so the waiting time is reasonable. 
 
 >should I create a design for a loading state that does not utilize the menu component?
 
 I think we can skip the loading state for now and then get back to it if loading times increase or we receive the corresponding feedback.
 
 What do you think?

**Comment by jjinnii** [comment]
@taras-yemets Okay! If we don't believe that latency is an issue then I agree we don't need another loading state (I would have had to go with the original alert to do so). Also, I'm assuming [this related work](https://github.com/sourcegraph/sourcegraph/issues/40217) will further help with the latency as well!

**Pull request merged**
