### PR TITLE
searcher: use gitserver.NewClient directly

### PR DESCRIPTION
**Pull request by keegancsmith**
This looks like the new way to do stuff, so using it directly. The git package was just a wrapper around using NewClient, so this is a noop for functionality.

Test Plan: CI

### CODE REVIEW

**Review by sashaostrikov — COMMENTED** [review]
Hey @keegancsmith 

Although it may look like some extra layer of wrapping, it is done intentionally in scope of adopting hexagonal architecture for repo management. All calls to gitserver should be done within `vcs/git` package. So I'd like to leave the call to `git.ArchiveReader` be.

Here is a link to related RFC: https://docs.google.com/document/d/1sxHpZIqKGi66evDQl6sN1FAJObbHAIkdl49EKOy7aUs/edit

**Comment by keegancsmith** [comment]
Alright will close out. The linked RFC is quite old, is it still up to date? I took a quick look at it and it isn't clear to me why we won't be using a gitserver client. Additionally, its very high level and doesn't really document what your plan is to be honest. The examples listed where about Init and Fetch which have never been concerns for application code which calls out to gitserver.

**Comment by keegancsmith** [comment]
Chatted to @asdine and @sashaostrikov over zoom and gained some context. LGTM :)

**Comment by keegancsmith** [comment]
@sashaostrikov based on this, it looks like we might end up using gitserver client directly? https://github.com/sourcegraph/sourcegraph/pull/33177

**Comment by sashaostrikov** [comment]
@keegancsmith well, it looks like this, this is some new refactoring I wasn't aware of previously

cc @ryanslade

**Comment by ryanslade** [comment]
Can you fix the conflicts please?

**Comment by keegancsmith** [comment]
merged in latest main

**Review by ryanslade — APPROVED** [review]
👍

**Pull request merged**
