### PR TITLE
graphqlbackend: treat yes/true and no/false values the same

### PR DESCRIPTION
**Pull request by keegancsmith**
This commit updates the yesNoOnly parser to not return different values
for true and false. Instead it will return yes or no respectiveley. This
simplifies read sites since we don't need to check for true or yes, etc.

This also highlighted a weird bit of logic. Previously if you did
"fork:yes" we would include forks. However, if you did "fork:true" we
only searched forks. I am unsure if this is intentional behaviour, but
it is surprising to me. Rather if a user only wants to search forks I'd
expect them to search "fork:only".

### CODE REVIEW

**Comment by keegancsmith** [comment]
@rvantonder please read the description for the change in behaviour. Is that intentional? Should I include a changelog entry detailed how this will change?

**Comment by efritz** [comment]
LGTM

**Comment by rvantonder** [comment]
Also good catch. Also Changelog maybe.

**Comment by keegancsmith** [comment]
> (unit test would be nice to have in this PR but I'm not going to block on that).

Took a look, unit test for that weird behaviour is too tricky to add right now. I think capturing this with the integration test will be best for now. I've been making some refactoring as I've been doing my indexed work, so I've been paying my test debt in the larger changes :P

**Pull request merged**
