### PR TITLE
gitserver: correctly join path to CloneFromShard

### PR DESCRIPTION
**Pull request by keegancsmith**
filepath is the incorrect package to use for joining a path onto a URL (use path package). Additionally, path.Join is not correct to use on a URL since it is supposed to operate on a path, not a URL. In go1.19 path join additionally does cleaning. This means things like "http://" will change into "http:/", leading to the feature breaking.

This commit introduces a wrapper around url.JoinPath in our url wrapper package and uses that in gitserver.

Test Plan: go test works on go1.19

### CODE REVIEW

**Comment by keegancsmith** [comment]
@burmudar I was nerd sniped at why this test was failing in go1.19. Took a bit too long to root cause lol, maybe I should start using a debugger instead of printf.

**Comment by burmudar** [comment]
@keegancsmith All part of the plan :D
gif

Seriously though, thanks for looking at it!

**Comment by burmudar** [comment]
@keegancsmith also, you should convert to the the next best debugging technique which is emoji based print

```
println("🐽")
println("🐌")
```

Credit to @jhchabran showing me this 😄

**Review by ryanslade — APPROVED** [review]
Worth adding a small unit test?

**Comment by burmudar** [comment]
ci pipeline is still using 1.18 ... [I've kicked off a main-dry-run with this change and also updating to 1.19.2](https://buildkite.com/sourcegraph/sourcegraph/builds/176006)

**Comment by burmudar** [comment]
And golangci-lint fails 😞

**Comment by keegancsmith** [comment]
@burmudar golangci-lint works for me on my linux box with version 1.48.0. However, it does have a bunch of failures. I am guessing quite a few of the linters are disabled on go1.18 and our codebase has rotted a bit w.r.t. lints.

**Comment by keegancsmith** [comment]
BTW I landed this but I had a shower thought. This API is weird, we shouldn't be joining in the gitserver. CloneFromShard (or maybe something more generic) should just be a clone url fully formed so we don't need to do these shenangins.

**Pull request merged**
