### PR TITLE
Wrap up overflowing code snippets in docs, fixes 5533

### PR DESCRIPTION
**Pull request by vanesa**
Add scrolling to note paragraphs that overflow in the docs. Fixes: https://github.com/sourcegraph/sourcegraph/issues/5533

Before:

image

After: 
image

### CODE REVIEW

**Comment by ryan-blunden** [comment]
Any issues with displaying on mobile?

**Comment by vanesa** [comment]
I used Chrome mobile preview to test it and it shows no issues:
image

You can just scroll sideways.

**Comment by vanesa** [comment]
Using `white-space:pre-wrap` instead:
image

**Comment by vanesa** [comment]
These changes affect other pages too, which leads to code wrapping pretty early:

image


vs before my changes:
image

**Comment by vanesa** [comment]
Improved styling:
image

Mobile:
image

**Pull request merged**
