### PR TITLE
validate settings and site config in DB layer, not elsewhere

### PR DESCRIPTION
**Pull request by sqs**
Now, JSONC syntax validation and JSON Schema validation for all 3 types of config (settings, site config, external service config) occurs at the DB layer.

Previously, it occurred in different places:

- Settings validation occurred in the DB layer, but JSONC syntax validation occurred twice (once directly and once implicitly during JSON Schema validation). This made the code confusing and was unnecessary.
- Site config syntax validation occurred in the DB layer, but JSON Schema validation only occurred in the graphqlbackend layer. This meant that it was possible to use JSON-Schema-invalid site config if supplied via `SITE_CONFIG_FILE`.
- External service config always only occurs in the DB layer.

The DB layer is the lowest layer, and performing the validation there ensures that it's not possible to store invalid config.

## Test plan

unit tests added

### CODE REVIEW

**Comment by sqs** [comment]
@sourcegraph/iam: Is it intended that site admins can provide site config via `SITE_CONFIG_FILE` that is not valid per the JSON Schema? (This may help in tricky upgrade situations where we introduced a backward-incompatible JSON Schema change.) If so, this PR is invalid.

**Comment by ryanslade** [comment]
FYI: I'm looking into a related issue where it seems we're not validating external service config when we do an upsert, but we *do* validate when we create or update the config explicitly. 

https://github.com/sourcegraph/sourcegraph/pull/41985

**Comment by kopancek** [comment]
> @sourcegraph/iam: Is it intended that site admins can provide site config via `SITE_CONFIG_FILE` that is not valid per the JSON Schema? (This may help in tricky upgrade situations where we introduced a backward-incompatible JSON Schema change.) If so, this PR is wrong.

To me this does not sound like a concern we should have. I cautiously asked on slack as well https://sourcegraph.slack.com/archives/C07KZF47K/p1664184544526099 and response from @efritz seems to be the same - if there's an error in site config during upgrade, we will rely on manual intervention today.

I will try to review the PR in depth tomorrow and hopefully get someone else to review as well, so that we have more than 1 pair of eyes check it. And coordinate with @ryanslade on merging, since he's opened a related PR #41985

**Comment by ryanslade** [comment]
External service config is now properly validated over all code paths via https://github.com/sourcegraph/sourcegraph/pull/41985

**Review by mrnugget — APPROVED** [review]

**Review by miveronese — APPROVED** [review]
It looks good to me.

**Review by daxmc99 — APPROVED** [review]
LGTM. The only place cloud currently uses the site config schema today is to generate requests to the GraphQL API to modify certain fields (adding license keys, silencing alerts, etc). 
Seems like the behavior is functionally the same from our POV

**Comment by keegancsmith** [comment]
FYI this PR was reverted due to it causing issues. See https://github.com/sourcegraph/sourcegraph/pull/42282 for details.

**Pull request merged**
