### PR TITLE
Run bext e2e tests on all branches, against a local instance

### PR DESCRIPTION
**Pull request by lguychard**
Adds e2e tests for setting the Sourcegraph URL through the options page, which in turns makes it possible to run the browser extension e2e tests against a local instance in CI. This would allow to run the e2e tests on all branches.

Still have to figure out how to fix the [build fail](https://buildkite.com/sourcegraph/sourcegraph/builds/29589#68be8180-ab22-43ba-bf13-08fe572ca160/38-222) on this -- fails with `TimeoutError: Timed out after 30000 ms while trying to connect to Chrome`, maybe linked to running puppeteer twice in a row (webapp, then bext)?

### CODE REVIEW

**Comment by chrismwendt** [comment]
I get this error when I run locally:

image

Maybe the browser extension needs to be built first in e2e.sh?

**Comment by chrismwendt** [comment]
Now I get this error:

image

Maybe there's some setting to allow navigating to the extension page?

**Comment by chrismwendt** [comment]
Oh, the bundle has a different extension ID on my machine:

image

I couldn't figure out how to get the extension ID. Relevant links:

- https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#working-with-chrome-extensions
- https://stackoverflow.com/questions/16993486/how-to-programmatically-calculate-chrome-extension-id this looks complex

**Comment by lguychard** [comment]
Interesting. We have a [`key`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/extension/manifest.spec.json#L67-68) set in manifest.spec.json, which [should prevent exactly that](https://developer.chrome.com/apps/manifest/key):

> This value can be used to control the unique ID of an extension, app, or theme when it is loaded during development.

I'll look into why it's not working here.

**Comment by chrismwendt** [comment]
@lguychard Oh, nice!

As an alternative, I tried listing the browser targets again. When I save this to a file `foo.js` and run `node foo.js`, it works:

```TypeScript
const puppeteer = require('puppeteer')

const chromeExtensionPath = './client/browser/build/chrome'

async function main() {
  const browser = await puppeteer.launch({args:[
                `--disable-extensions-except=${chromeExtensionPath}`,
                `--load-extension=${chromeExtensionPath}`],headless: false})
  const page = await browser.newPage()

  await new Promise(resolve => setTimeout(resolve, 3000))

  const target = browser.targets().find(target => target._targetInfo.title === 'Sourcegraph')
  await page.goto(new URL('..', target._targetInfo.url).href + '/options.html')

  await new Promise(resolve => setTimeout(resolve, 3000))

  page.close()
  browser.close()
}
main()
```

However, when running `env ... yarn --cwd client/browser run test-e2e`, there is no extension named `'Sourcegraph'`, and I'm not sure what the difference is.

**Comment by felixfbecker** [comment]
@chrismwendt maybe your condition checking the `title` is different?

**Comment by felixfbecker** [comment]
What's the status of this?

**Comment by felixfbecker** [comment]
It would be nice to have this to merge Puppeteer updates with confidence

**Pull request closed without merging**
