### PR TITLE
Add back build badge

### PR DESCRIPTION
**Pull request by felixfbecker**
https://github.com/sourcegraph/sourcegraph/pull/164#issuecomment-426288311

### CODE REVIEW

**Comment by slimsag** [comment]
I'm fine with having the build badge, but it should be on the right of the logo not beneath it. Having a whole line of whitespace dedicated to just a badge is silly. i.e. if we're going to have it, it should be:

image

**Comment by francisschmaltz** [comment]
Just to chime in on this:

It should be on its own line. Next to the logo looks rough.

**Comment by slimsag** [comment]
Sent https://github.com/sourcegraph/sourcegraph/pull/238 which I think is better. I _really_ do not like the idea of wasting an entire line of space just for badges.

**Comment by francisschmaltz** [comment]
@slimsag Looks good in #238! Saw this on the train so I didn't see that. I just didn't want it to be smushed like this photo!

**Comment by nicksnyder** [comment]
I quickly looked up a few projects. When no logo is involved I see both solutions (same line and separate line). When a logo is involved I only found examples of separate line for badges (but could be correlated to projects having a lot of badges and needing a separate line anyway).

Unless you can solve the vertical alignment issue I think a separate line (as proposed in this pr) is the least bad solution.

**Comment by slimsag** [comment]
We're at a stalemate, I remain unconvinced that a build badge is worth pushing the tagline down an entire paragraph's size in whitespace. The last option I can offer you that I would be content with is ditching our logo entirely:

> # [Sourcegraph](https://sourcegraph.com) <a href="https://github.com/sourcegraph/sourcegraph/blob/master/LICENSE">Apache license</a>  <a href="https://buildkite.com/sourcegraph/sourcegraph"></a>

**Comment by francisschmaltz** [comment]
Let's do the solution in  #238 . If it looks bad on mobile we can add a css line to break it to a new line on small viewports.

**Comment by slimsag** [comment]
@francisschmaltz markdown HTML is restricted you cannot use CSS

**Comment by nicksnyder** [comment]
#238 as it is currently is not an option (right justified badges). Its is highly unusual and there are visual defects. "Optimizing for mobile" is not a requirement. "Not proactively making it look bad on mobile" is a requirement.

The acceptable options that I see are:
1. Merge this PR as-is: keep logo and badge on new line.
2. Remove logo and put badges next to title as Stephen suggested in https://github.com/sourcegraph/sourcegraph/pull/219#issuecomment-426511966.
3. Not add badges and keep the README as it is. I am actually ok with this, but I assume others are not.

Of the three, I think (1) is the best solution because
1. Our logo is nice to have for our flagship product (thanks for adding it!)
2. There is also plenty of precedent for putting badges on a new line, especially when there is a logo in the readme. I am sorry if you personally find this unappealing, but it seems like a broader audience has deemed this an acceptable solution.
3. This PR is ready to merge, we have already spent more time discussing this than it is worth, and it is easy to change in the future.

With that, I am clicking the merge button.

**Comment by felixfbecker** [comment]
Btw I definitely see the point you are making @slimsag, it's not optimal that there is a single badge on its own, and it would look better if there were more. There also used to be more, but they were removed piece by piece, so I am just trying to get at least the uncontroversial obviously useful ones back. I would be 100% for adding e.g. a license badge too as you did in #238 and I think that would already make it look better.

**Comment by nicksnyder** [comment]
https://github.com/sourcegraph/sourcegraph/commit/15f312fcc9ac265e3508b1bdffb88a3e9a3f2441

**Pull request merged**
