### PR TITLE
Setup Wizard nav item for App

### LINKED ISSUE #48967: Setup Wizard: Add navigation link to setup wizard
Since Sourcegraph app clones repositories if you run your app from the terminal it already will have some repositories on the instance, and we won't show wizard by default. 

But with the setup wizard, you can add other local repositories too so it should be possible to go to the setup somehow from the UI (even if you have some repositories on the instance) 

In this issue, we should add "Go to setup wizard" item in the user menu.

### PR DESCRIPTION
**Pull request by st0nebraker**
Closes #48967; Adds a nav item to setup wizard for App users.

image

## Test plan
- Ensure item appears on App platform only

**NOTE**: 1st local repo wizard step isn't done yet. May be a good idea to not merge this until #48214 is merged to not mislead any sourcegraphers testing App in the meantime.

## App preview:

- [Web](https://sg-web-becca-app-setup-wiz-nav-item.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by philipp-spiess — APPROVED** [review]
Oh NICE! 👯 

@taylorsperry suggested to call it "Repositories", what do you think about that instead?

https://github.com/sourcegraph/sourcegraph/issues/48967#issuecomment-1462480326

**Review by slimsag — APPROVED** [review]
Epic, thank you so much for doing this!

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.06 kb) | 0.00% (+0.06 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/becca/app-setup-wiz-nav-item/compare-report.html;tab=live_object) for a full comparison between the commits da0ec4d and ca36461 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by paulo-digital** [comment]
I think the setup wizard it's a clear description of what the user will encounter. Also, we have a repo section on settings.

How will we deal with this option after the user run the wizard for the first time? Will it be a permanent option?

**Comment by almeidapaulooliveira** [comment]
I think 'setup wizard' it's a clear description of what the user will encounter. I'm concerned that users will rely on the wizard for settings instead of the admin panel.

How will we deal with this item after the user runs through it the first time? Hide it, or it's going to be a permanent option?

**Comment by vovakulikov** [comment]
@almeidapaulooliveira, it's going to be a permanent option, I think because otherwise there won't be any option to add local repositories if you run your instance from the terminal (terminal gives us some repositories so the flag that we use on the client needsRepositoriesSetup will be true all time, means there will be no wizard UI by default) 

Ideally, I would say that we have to have a setup wizard local repositories step somewhere outside the wizard (like the site admin page?) but considering a given timeline I think it's going to be in the second version

**Comment by vovakulikov** [comment]
@almeidapaulooliveira just FYI Becca and Taylor found as I think good compromise here - putting the setup wizard link in the code host site admin page see this comment https://github.com/sourcegraph/sourcegraph/issues/48967#issuecomment-1462856103

**Comment by almeidapaulooliveira** [comment]
Yes, I understand. This should be considered design debt, I'll open an issue to document those. I believe you already started taking this notes somewhere, I'm right?

**Comment by vovakulikov** [comment]
@almeidapaulooliveira I've been writing down follow; up yes, I will clear up the board and file a bunch of issues right after we finish the first version for the Starshipt 

@st0nebraker, any stoppers here to merge this one?

**Pull request merged**
