### PR TITLE
codeintel: Mirror repository badge on new repository page

### PR DESCRIPTION
**Pull request by efritz**
This PR covers the first checkbox on #34490. To test locally, you will need to make the following request in the API console:

```graphql
mutation CreateFeatureFlag {
  createFeatureFlag(name: "new-repo-page", value: true) {
    __typename
  }
}

```

**List of changes**:

- Move `massageIndexerSupportMetadata` into hooks
- Rename `BadgeContent` to `UserFacingCodeIntelligenceBadgeContent`
- Rename `InternalBadgeContent` to `InternalCodeIntelligenceBadgeContent`
- Split `CodeIntelligenceBadge` into `CodeIntelligenceBadgeContent` and `CodeIntelligenceBadgeMenu`
- Add content component to repo redesign page

This PR has not (intentionally) change any user-facing behaviors of the current repository menu badge - just exposes internals so that we can reuse the menu contents.

Screenshot

## Test plan

Tested storybook and app by hand.

## App preview:

- [Web](https://sg-web-ef-badge-repo-page.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-dauzwqyftw.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by abeatrix — COMMENTED** [review]
The badge looks great to me!

I'm not sure if this is caused by my dev env but the README file section is not loading for me when I tried to build with your branch (building from the main branch works though):
image

Log from console:
```
[enterprise-frontend] context: context.Background.WithValue(type *http.contextKey, val <not Stringer>).WithValue(type *http.contextKey, val [::1]:3082).WithCancel.WithCancel.WithValue(type ot.key, val <not Stringer>).WithValue(type opentracing.contextKey, val <not Stringer>).WithValue(type opentracing.contextKey, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val unknown).WithValue(type sessions.contextKey, val <not Stringer>).WithValue(type actor.contextKey, val Actor UID 1, internal false).WithValue(type featureflag.flagContextKey, val <not Stringer>).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type trace.key, val Blob).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val
[enterprise-frontend]                 query Blob($repoName: String!, $commitID: String!, $filePath: String!, $disableTimeout: Boolean!) {
[enterprise-frontend]                     repository(name: $repoName) {
[enterprise-frontend]                         commit(rev: $commitID) {
[enterprise-frontend]                             file(path: $filePath) {
[enterprise-frontend]                                 ...BlobFileFields
[enterprise-frontend]                             }
[enterprise-frontend]                         }
[enterprise-frontend]                     }
[enterprise-frontend]                 }
[enterprise-frontend]                 fragment BlobFileFields on File2 {
[enterprise-frontend]                     content
[enterprise-frontend]                     richHTML
[enterprise-frontend]                     highlight(disableTimeout: $disableTimeout) {
[enterprise-frontend]                         aborted
[enterprise-frontend]                         html
[enterprise-frontend]                         lsif
[enterprise-frontend]                     }
[enterprise-frontend]                 }
[enterprise-frontend]             )
```

Can you confirm if the README is loading on your build?

**Comment by efritz** [comment]
@abeatrix *works soo gud*

image

**Comment by abeatrix** [comment]
> @abeatrix _works soo gud_
> 
> image

Yeee it's working for me now, thanks for the update!

image

**Review by abeatrix — APPROVED** [review]
🚀 🚀 🚀

**Pull request merged**
