### PR TITLE
migrations: reorder to enable 3.34.2 patch release

### PR DESCRIPTION
**Pull request by tsenart**
The 3.34.2 patch release includes some migrations we just added today.
In order for us to only ship those and not introduce any gaps in the
migration sequence numbers, we reorder the migrations which is possible
since they have no inter-dependencies.

Co-authored-by: Eric Fritz <eric@sourcegraph.com>

### CODE REVIEW

**Review by rmmh — APPROVED** [review]

**Comment by efritz** [comment]
**DO NOT MERGE UNTIL** `c7fdc4542542: migrations: Make repo.stars not nullable (#28624)` is live in cloud.

```
➜  sourcegraph git:(main) ✗ sg live cloud
✅ Done
✅ Done updating list of commits

💡 Live on "cloud": adb73bd (built on 2021-12-06)

   836237a867b5 (44 minutes ago, Eric Fritz): database: Split schemas code into files (#28642)
   c6a9b10501a6 (50 minutes ago, Kevin Wojkovich): Prepare patch release (#28639)
   e8c541cf450e (60 minutes ago, Eric Fritz): dbconn: Use correct prefix for frontend db (#28636)
   c42a08f6fb0c (79 minutes ago, Tomás Senart): Update CHANGELOG
   13e1c945706a (2 hours ago, Eric Fritz): doc: Add reference page for code intelligence envarrs (#28635)
   c7fdc4542542 (2 hours ago, Tomás Senart): migrations: Make repo.stars not nullable (#28624)
   564c4ad82c9c (2 hours ago, Eric Fritz): codeintel: Optionally accept uploads for unresolvable commits (#28501)
   b1d4bfaa0a58 (3 hours ago, Eric Fritz): chore: Collapse lib/postgresdsn and internal/db/migration/schema (#28632)
   c62a1ae18eeb (3 hours ago, Dax McDonald): Add Jennifer and Daniel to team/devops label notification (#28634)
   ecc5407f6f07 (3 hours ago, Stephen Gutekanst): security: remove our CSRF tokens to improve security and reduce complexity of our threat model (#28572)
   18e5b45f14bb (3 hours ago, Cesar Jimenez): Rename sidebarToggle setting (#28568)
   fda5db4f73fb (3 hours ago, coury-clark): Insights: updated GraphQL create and update mutations to handle capture group insight series (#28492)
   bd6645afa078 (5 hours ago, Eric Fritz): chore: Clean up definitions in migrations package (#28617)
   84e3b0e24d7a (5 hours ago, Eric Fritz): chore: Remove unknown path from codenotify (#28616)
   09a2370cc22a (5 hours ago, Eric Fritz): migration: Share postgres dsn resolution code (#28618)
🚀 adb73bd88ae5 (5 hours ago, Eric Fritz): chore: Add codenotify (#28619)
```

**Comment by mrnugget** [comment]
Hmm, this also _renamed_ the migration files so that the filename doesn't match the content anymore. Was that on purpose?

Examples:

https://github.com/sourcegraph/sourcegraph/blob/7a4b2e6889e0dfbf3113799a3b5a9c2ee882f329/migrations/frontend/1528395947_repo_stars_not_null.up.sql
https://github.com/sourcegraph/sourcegraph/blob/7a4b2e6889e0dfbf3113799a3b5a9c2ee882f329/migrations/frontend/1528395946_repo_stars_call_nulls_to_zero.up.sql
https://github.com/sourcegraph/sourcegraph/blob/7a4b2e6889e0dfbf3113799a3b5a9c2ee882f329/migrations/frontend/1528395945_repo_stars_null_to_zero.up.sql

Seems like a potential foot gun?

**Comment by tsenart** [comment]
Ah, yeah, I think we should fix the names. Would there be any problem with doing that @efritz?

**Comment by efritz** [comment]
Not at all, only the numbers are read by golang-migrate.

**Comment by mrnugget** [comment]
Alright, who's going to do that then?

**Comment by tsenart** [comment]
https://github.com/sourcegraph/sourcegraph/pull/28904

**Pull request merged**
