### PR TITLE
blob: show experimental keyboard shortcuts in help

### PR DESCRIPTION
**Pull request by taras-yemets**
Show experimental blob page shortcuts based on `blob-page-switch-areas-shortcuts` feature flag value.
See [this thread](https://sourcegraph.slack.com/archives/C0HMGV90V/p1678197149771269) for more context.

|Feature flag enabled|Feature flag disabled|
|--|--|
|Screenshot 2023-03-08 at 23 14 15|Screenshot 2023-03-08 at 23 13 42|

## Test plan
Tested manually (screenshots attached).

## App preview:

- [Web](https://sg-web-taras-yemets-show-blob-page.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.04% (+1.26 kb) | 0.05% (+7.42 kb) | 0.05% (+6.15 kb) | -0.13% (-1) 🔽 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/taras-yemets/show-blob-page-shortcuts-in-help/compare-report.html;tab=live_object) for a full comparison between the commits 5d30798 and d3f5848 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by fkling** [comment]
How quickly do you want to get this in? 😅 What I'd like us to do eventually is to build the keyboard help dynamically based on the shortcuts that are currently registered in the component tree. This way we will always only show information about the shortcuts that are actively working.

However I haven't looked too closely into the current implementation to see how difficult it would be to add that...

**Comment by philipp-spiess** [comment]
> What I'd like us to do eventually is to build the keyboard help dynamically based on the shortcuts that are currently registered in the component tree. 

Not sure if I’m a fan on this. This would make keyboard shortcuts for lesser used features very hard to find out about and if you only check the map once, e.g. on the homepage, you'd never learn about those :/

I just checked Linear as well, an app that does excellent keyboard handling, and they also have a list of all keyboard shortcuts inside the app. I can, for example, see editor actions for markdown formatting on the home page. I think the separate sections help a lot though and we should add one for "code view" or whatever public-facing word we use for this part of the UI! 

Screenshot 2023-03-09 at 00 53 18

**Comment by taras-yemets** [comment]
I think we can split shortcuts into sections when we move further implementing [RFC 345](https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#heading=h.trqab8y0kufp).

**Comment by taras-yemets** [comment]
@fkling, highlighting active shortcuts sounds good to me 👍🏻

**Comment by taras-yemets** [comment]
> How quickly do you want to get this in?

@fkling, shortcut handlers are already merged (https://github.com/sourcegraph/sourcegraph/pull/46829) and enabled for everyone on s2 and Sourcegrapg org members on dotcom. Including them in the shortcuts help modal would be nice for better discoverability (in addition to the #progress or #feedback-dogfood post I will add shortly).

**Comment by taras-yemets** [comment]
>do you think we can even turn it on for the release?

@philipp-spiess, do you mean removing the feature flag?

**Comment by philipp-spiess** [comment]
> @philipp-spiess, do you mean removing the feature flag?

Precisely 😐

**Comment by taras-yemets** [comment]
> CMD+C copies text but focuses the code view in addition

May be fixed by https://github.com/sourcegraph/sourcegraph/pull/49055 🤞🏻 
cc: @philipp-spiess

**Review by philipp-spiess — APPROVED** [review]

**Pull request merged**
