### PR TITLE
RFC: Use native links in references panel

### PR DESCRIPTION
**Pull request by philipp-spiess**
This was motivated by [feedback from this conversation](https://sourcegraph.slack.com/archives/C04931KQVRC/p1679323575904199)

This changes the implementation of the references panel to use a native `<a>` tag instead of the current `<div role="link>`, removing the previous need to [custom handled click event](https://github.com/sourcegraph/sourcegraph/blob/d646d9b71f3b91f3e7b79e70386bbd437e99de5f/client/branded/src/search-ui/components/codeLinkNavigation.ts#L123:17) to make it easier to select text on the link but giving us the following benifits:

- We can now add a native onDoubleClick handler (not possible with the previous selection logic as double click was used to select the word). This way, we can use a normal double click to open a reference directly in the blob view instead of having this awkward "click twice with a delay" pattern.
- We can now right click => Open link in new tab 🤯 
- cmd+click also now opens the symbol in a new tab which is super handy.

While doing this, I also fixed another issue: We used a different font to render the references than we used in the blob view. This changes the fonts to use `var(--code-font-family);` instead.

## Test plan

https://user-images.githubusercontent.com/458591/226999869-1b8806ed-7188-4656-ae0b-226936c650a1.mov

## App preview:

- [Web](https://sg-web-ps-ref-panel-cmd-click.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by taras-yemets** [comment]
Clicking on the result _twice_ to propagate it to the main view is confusing to me too. 
I think that _double click_ is more suitable for propagating the result to the main view in the current tab (similar to JetBrains find window: it opens side blob on click and propagates result to the main view on the double click), and _cmd+click_
for opening the result in a new tab (similar to links).

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.72 kb) | 0.01% (+0.72 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/ref-panel-cmd-click/compare-report.html;tab=live_object) for a full comparison between the commits d646d9b and db69296 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by philipp-spiess** [comment]
> I think that double click is more suitable for propagating the result to the main view in the current tab (similar to JetBrains find window: it opens side blob on click and propagates result to the main view on the double click), and cmd+click
for opening the result in a new tab (similar to links).

I don't think we can implement a proper double-click here because of the magic we do in: https://github.com/sourcegraph/sourcegraph/blob/d646d9b71f3b91f3e7b79e70386bbd437e99de5f/client/branded/src/search-ui/components/codeLinkNavigation.ts#L123:17

Double click on selecteable items should select the whole world and if we need keep the item selectable, we can't have double click.

This handler was added for search results though, maybe we don't need to use it and can just render regular links instead?

**Comment by philipp-spiess** [comment]
I generally feel like double click is not a pattern that we should use a lot. It's very rarely used on the web, e.g. I can not name a single other web product I use that implements it. Maybe because it's so hard to discover, I don't know.

**Comment by taras-yemets** [comment]
@philipp-spiess, fair point about the double-click discoverability 👍🏻 

Then it seems we don't have a common approach for Cmd+click: links open in the new tab (default), and the main blob view navigates to the definition (if found) in the current tab. So in this case cmd+click can either propagate the result to the main blob view in the current tab or open it in the new one. 
I like opening in the new tab option more, probably with underlining the hovered line when `cmd` is held, so it feels more like a link.

**Comment by taras-yemets** [comment]
> What are your thoughts on making it a bit harder to select the text underneath and removing the [onClickCodeExcerptHref](https://github.com/sourcegraph/sourcegraph/blob/d646d9b71f3b91f3e7b79e70386bbd437e99de5f/client/branded/src/search-ui/components/codeLinkNavigation.ts#L123:17) part?

@philipp-spiess, what do you mean when saying "making it a bit harder to select the text"? Ignoring double- and triple-clicks?

**Comment by philipp-spiess** [comment]
@taras-yemets Check out [this comment](https://github.com/sourcegraph/sourcegraph/blob/d646d9b71f3b91f3e7b79e70386bbd437e99de5f/client/branded/src/search-ui/components/codeLinkNavigation.ts#L108-L121):  the current implementation here allows us to start a selection of text within a link, something that's not possible with a native link:


https://user-images.githubusercontent.com/458591/226600271-88ad002c-b5ed-4f6d-a154-359585e23271.mov

My suggestion is that we remove this feature from the references panel so we have a normal `<a>` instead that would support:

- cmd+click to open in new tab
- single click would be intercepted and open in side blob
- doubleclick handler can be added to open in main blob

**Comment by taras-yemets** [comment]
@philipp-spiess, I don't have a strong opinion on whether we should keep or remove the possibility of selecting text from the search result code snippet. 
I rarely use it and prefer to copy text from the main or side blob, but there could be other opinions or use cases. For example, the user wants to copy the part of the result code snippet and paste it into the search input. In this case, they may not want to wait for the side blob to load 🤔 Moreover, the result code snippet on the search results page supports text copying, so it could have been added to the references panel for consistency sake. But it's only an assumption.

I looked through the history and discovered that this feature was added in https://github.com/sourcegraph/sourcegraph/pull/42180, addressing https://github.com/sourcegraph/sourcegraph/pull/41569#issuecomment-1251173619.

@olafurpg, @mrnugget, do you think supporting text selection in the references panel code snippets is critical? What do you think about @philipp-spiess suggestion (https://github.com/sourcegraph/sourcegraph/pull/49709#issuecomment-1477719994)?

**Comment by mrnugget** [comment]
I don't think text selection is critical _if_ it feels correct. Example: I can't select the text in the buttons of this comment form, because the cursor changes. But I can select text whenever I get the normal text-select cursor.

As long as that's given, I'm fine with disabling it.

**Comment by philipp-spiess** [comment]
I've updated the implementation now to switch to using a native link instead. I like this so much more and it feels like text selection still works just fine enough.

I also fixed a mismatch in the font used for the references list 😐 

Check out the updated pull request description!

**Comment by taras-yemets** [comment]
Great work! Thank you, @philipp-spiess!

I tried it locally, and for some reason, Cmd+click didn't work for me: with the `cmd` key pressed single click opened the result in a side blob view, and a double click opened it in the main view in the current tab.

https://user-images.githubusercontent.com/25318659/227221922-6c3b5395-132b-4e95-9be9-ac9d4ef143f6.mov




>removing the previous need to [custom handled click event](https://github.com/sourcegraph/sourcegraph/blob/d646d9b71f3b91f3e7b79e70386bbd437e99de5f/client/branded/src/search-ui/components/codeLinkNavigation.ts#L123:17) to make it easier to select text on the link

Nit (feel free to ignore): Text selection is less predictable with this implementation: most of the time, I wasn't able to select text with a mouse, but sometimes I managed to have part of the result selected. What do you think if we do not allow selecting text at all to avoid confusion? And maybe underlining the hovered line text to resemble link styles more?

**Comment by taras-yemets** [comment]
>>Text selection is less predictable with this implementation: most of the time, I wasn't able to select text with a mouse, but sometimes I managed to have part of the result selected.
>
>Hm it didn't feel like this at all for me, can you elaborate which behavior felt unreliable?

I could select some text with a mouse on one search result code snippet, but couldn't on another. Though I couldn't reproduce this issue reliably. I just pulled the latest changes and couldn't reproduce it anymore.

Great work, @philipp-spiess!

**Pull request merged**
