### PR TITLE
third-party-licenses: add syntect_server licenses

### LINKED ISSUE #11269: License report for syntect_server & its dependencies
See https://github.com/sourcegraph/sourcegraph/pull/11116#discussion_r433355048

### PR DESCRIPTION
**Pull request by slimsag**
This PR adds third-party licenses for syntect_server. I did not use CSV format and used multiple files because documenting/explaining all of this is a little bit cumbersome to do.

The `dependencies.json` is auto-generated via [a script](https://github.com/sourcegraph/syntect_server/blob/master/gen-license-dependencies.sh) while the `syntaxes.txt` is hand-crafted and will have to be maintained as part of adding any new language syntaxes: https://github.com/slimsag/Packages#license

Note: This information is only up-to-date for Sourcegraph >= v3.21, since that version of Sourcegraph [removes some syntaxes which had missing/incompatible licenses](https://github.com/sourcegraph/sourcegraph/pull/14456)

Fixes #11269

### CODE REVIEW

**Comment by slimsag** [comment]
@dadlerj can you review? Does this look sufficient from your POV?

**Comment by dadlerj** [comment]
Thanks!

Curious why you included the dependencies of a dependency here—i.e., why include third-party-licenses/ThirdPartySyntectServer.dependencies.json instead of only including the third-party-licenses/ThirdPartySyntectServer.txt file?

I don't see it having any big downsides of course (only small, practical concerns like making this directory more confusing and adding more file formats than necessary), but my impression is that because most of the sub-licenses (standard MIT/BSD/Apache) don't require this sort of sub-attribution, particularly given the code isn't available in this repository (whereas we would want to include these disclosures in the syntect fork).

I'm no expert, of course. Mostly curious if you are doing it to have a margin of safety and because there's no downside, or if you have reason to believe I'm incorrect and we do _need_ to include these.

**Comment by slimsag** [comment]
I'm no expert/lawyer, of course, but, pretending that I am:

> but my impression is that because most of the sub-licenses (standard MIT/BSD/Apache) don't require this sort of sub-attribution, particularly given the code isn't available in this repository (whereas we would want to include these disclosures in the syntect fork).

This is not what I believe to be true. None of these licenses have any exception about sub-attribution or dependencies of dependencies, they just talk holistically about the software the license is describing. They don't care how it gets redistributed by you, you have to abide by the license.

- For the MIT license, it is a legal grey area whether or not redistributing MIT software in binary form requires the license to be redistributed as well.
- For the Apache and BSD licenses, they seem pretty cut-and-dry that even if you are distributing software just in binary form that you need to include a copy of the license.

From a technical/legal POV, I think we very much need to at least try to include the license for every piece of software we distribute - whether that is in binary, source, or Docker Image (binary) form. Obviously, in some cases this is harder than others - like tracking down every piece of included software in the base Docker images we use, for example - I believe any judge would just look to see if we made an effort in good faith in such a scenario.

From a non-legal POV, I believe there is also a bit of a moral obligation to include licenses for every piece of software (even dependencies of dependencies) we use because it provides attribution for OSS authors where they otherwise would receive none. Again, we don't need to go to the edges of the earth here - but I think it's a nice gesture to make.

#### The MIT license leaves it ambiguous (legal grey area) whether or not distribution of the license is required when distributing compiled versions of MIT software.**

It states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

And it defines "Software" as:

> this software and associated documentation files (the "Software")

Does "Software" include compiled versions of the software? Its a grey area.


#### The Apache-2.0 license requires that the license must always be included

Section 4. "Redistribution" of the Apache license (too long to copy here, see [here](https://opensource.org/licenses/Apache-2.0)) says that when redistributing Derivative Works, which includes "any work, whether in Source or Object form, that is based on (or derived from) the Work", "You must give any other recipients of the Work or Derivative Works a copy of this License" among other things.

This seems pretty cut-and-dry to me that, even if it is dependencies of dependencies of dependencies - if we're redistributing the binary form of Apache software, the license must be included.

#### The BSD 3-clause license requires that the license must always be included

It says:

> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

This also seems pretty cut-and-dry to me.

**Comment by slimsag** [comment]
@dadlerj you okay with me merging this as-is?

**Comment by slimsag** [comment]
No objections and this seems better than the state we were in before, so merging. Happy to follow-up on any feedback

**Pull request merged**
