### PR TITLE
Fix external_service_sync_jobs cleanup job

### PR DESCRIPTION
**Pull request by eseliger**
This was never updated after we introduced the 'failed' state and made 'errored' transient.
As a result, on dotcom we currently have `1,167,159` external_service_sync_jobs, of which.. `1,121,444` should've been deleted, only 4% of that table size are required. This'll likely also yield some nice performance gains.

## Test plan

Validated that older failures I saw on my instance are now gone.

### CODE REVIEW

**Review by bobheadxi — APPROVED** [review]
only thought would be to include a docstring indication to where the valid states are declared

**Comment by eseliger** [comment]
It's generic dbworker terms, do you think I should link to that?

**Comment by bobheadxi** [comment]
> It's generic dbworker terms

Yeah I think so, this looks like a custom implementation of logging the results of a worker right? For example, I wouldn't really know where to start at a glance 😛 but mostly a "a brief pointer might be nice for an uninformed reader" kind of thought, so no need to consider this blocking

**Comment by eseliger** [comment]
Not custom, it's just the database table backing the dbworker Store for the worker of external service sync jobs, and we occasionally prune old entries in there.

**Review by LawnGnome — APPROVED** [review]

**Review by ryanslade — APPROVED** [review]
Nice catch!

**Review by mrnugget — APPROVED** [review]
NICE!

**Pull request merged**
