### PR TITLE
insights: adds live preview for strat insights

### PR DESCRIPTION
**Pull request by chwarwick**
Adds live preview for insights that define repos using a search query
## Test plan
Manual check of live preview for each insight type
Manual check of live preview used on getting started page

## App preview:

- [Web](https://sg-web-cw-live-preview-strat.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.02% (+0.69 kb) | 0.07% (+9.72 kb) | 0.08% (+9.02 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/cw/live-preview-strat/compare-report.html;tab=live_object) for a full comparison between the commits 11c0d2c and 6073d5c or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by vovakulikov — APPROVED** [review]

**Comment by vovakulikov** [comment]
@chwarwick I think that we forgot about the additional screen for the live preview when we have more than 20 repos to preview. In this case, we should have an error or blur screen with a message that we tried to run a preview but got too many repos to provide a proper preview

**Comment by chwarwick** [comment]
> @chwarwick I think that we forgot about the additional screen for the live preview when we have more than 20 repos to preview. In this case, we should have an error or blur screen with a message that we tried to run a preview but got too many repos to provide a proper preview

There's a separate screen for that?  I just had the api return an error.

**Comment by vovakulikov** [comment]
@chwarwick In [original Alicja designs](https://www.figma.com/file/ZUSD4DTNBdGGomLn6uKZFj/RFC-741-proposal-B%3A-design-for-running-insights-over-partial-sets-%2342333?node-id=246%3A11&t=gurkIcKZ0U4sEPU9-0) there was a special live preview card state for it 

Screenshot 2022-12-22 at 11 04 57

**Comment by vovakulikov** [comment]
I can add this handling later in my PR but just FYI that we have a special state for this type of error. Maybe it would be better if we had a union type in live preview results in the API.

**Pull request merged**
