### PR TITLE
git: use custom format for git log

### PR DESCRIPTION
**Pull request by keegancsmith**
Git has supported %S since 2.21 (Q1 2019). Git commit search was written
before that at Sourcegraph so we had a workaround using "--source". Now
that it is supported we can more directly use it instead of ignoring
extra information on the line.

Additionally we may be able to drastically simplify commit search and
just call log. A todo is left in the code for future travellers.

### CODE REVIEW

**Review by camdencheek — APPROVED** [review]
Nice! I'll plan to dig in on #17483 soon, so will try to find some time to refactor/simplify then.

**Comment by keegancsmith** [comment]
It seems our CI is using a git that is 2 years old. This PR requires a git 2.21 (Q1 2019). I think we used to use a modern git, but I think we may have switched to a different distribution/etc for CI? We should still be using modern git in the images we build (I hope!). Easy enough to fix, but won't get to it this week. cc @pecigonzalo

**Comment by pecigonzalo** [comment]
I give this a look later today and open an issue/fix.

**Comment by keegancsmith** [comment]
> I give this a look later today and open an issue/fix.

Thanks!

**Pull request merged**
