### PR TITLE
chore: Squash migrations

### PR DESCRIPTION
**Pull request by efritz**
`./dev/db/squash_migrations.sh frontend v3.21.0`

### CODE REVIEW

**Review by daxmc99 — COMMENTED** [review]
My understanding of this is that these migrations are quite old that they are from a version of Sourcegraph << 3.24?

**Comment by efritz** [comment]
@daxmc99 This will squish any migration defined in 3.21 or below. Anything defined in 3.22 or above is unsquashed.

**Review by daxmc99 — APPROVED** [review]
After hiding the deleted files on Github this makes sense. There is no change to the functionality of the migrations other than the deleted files are moved into a single file (squish). 
Out of curiosity, why not squash all the way up to the latest?

**Comment by efritz** [comment]
@daxmc99 If you can upgrade N versions we need to keep all the migrations from the previous N versions. We had a 2 minor version guarantee which is where that process came from.

**Pull request merged**
