### PR TITLE
app: implement notifications sent by sourcegraph.com to Sourcegraph App users

### PR DESCRIPTION
**Pull request by slimsag**
This gives us the ability to add notifications for Sourcegraph App users to the Sourcegraph.com site configuration (under `dotcom.app.notifications`) with Markdown messages including text, links & more.

When the App sends a telemetry ping, the response now includes these notifications, which the app then stores in the site config `notifications` field. They are then rendered as dismissible alerts:

image

Each notification has a unique key, and so once dismissed the user will never see it again (unless we add a new one in the sourcegraph.com site config.)

Additionally, we can specify a version range in the sourcegraph.com site config to make the notification target specific Sourcegraph App versions. For example, if we release a broken version we could notify those users specifically and inform them.

## Test plan

Because this hinges on a sourcegraph.com change, this is hard to test. What I've done to de-risk it is:

1. Made each commit individually clear/transparent; most of the changes to the `updatecheck` code are VERY low risk and easily verified.
2. Every change only affects App; there is near-zero risk to other deployment types.
3. Once merged; we can test this further (post-code-freeze) and confirm it works. We still have time to land bug fixes should any issue pop up.
4. I used VERY defensive coding; so if it doesn't work the notifications will just not appear (rather than e.g. crash the app, or cause pings to stop working.)

I think this is worth the risk in terms of value it gives us, and because it makes pings more defensible to users, and gives us a better way to communicate with these early adopters. I suggest we land this before code freeze as a result - even if it's not 100% perfect.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.22 kb) | 0.01% (+1.22 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/sg/notifications/compare-report.html;tab=live_object) for a full comparison between the commits 09a0578 and 4286ccc or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by marekweb — APPROVED** [review]
Approving because it looks good to me, but with the caveat that I'm not that familiar with the affected code so additional reviews would be a good idea.

**Comment by vovakulikov** [comment]
I haven't tested this manually but one thing that I've seen about a dismissible notification is that dismiss action works via localstorage, so when you click dismiss we write in localstorage information (notification key) to hide the notification next time, I'm curios is this the case that if you open the client in the different browser you will have all notification at once 🤔

**Comment by marekweb** [comment]
I'll go ahead and merge this.

@vovakulikov Good point, we can look at improvements to the frontend side of these notifications (we should probably use temporary settings instead of localstorage, if we don't already) For now, the dismiss behavior isn't too much of a concern for how we'll use this in App I think, and we can still refine it.

**Comment by vovakulikov** [comment]
Agree about Sourcegraph App application area for this notification system, so I agree with merging this. But I'm a bit concerned that we're putting everything into the temporal settings API just because it exists. Notification dismiss actions probably should work differently to avoid big size of temporally setting object (this temporal settings object is important for our performance because since recently we load it with `window.context` so big size of temporally settings will slow down every page of Sourcegraph)

I know that there is a project about system Notification Center, probably we can return to this with this project and try to find a better, more scalable solution.

**Pull request merged**
