### PR TITLE
Code intel: Polish precise index UI

### PR DESCRIPTION
**Pull request by umpox**
Issue https://github.com/sourcegraph/sourcegraph/issues/47262

## Description

Fixes a bunch of areas of polish for precise indexes. 

There's still quite a bit we can do, but not as high priority as making large improvements/new features (e.g. dashboard/indexing)

Summary of changes:
- Checkboxes, repo links and index links no longer clash together. I have added a chevron to each index and preserved the hover state to ensure we still indicate these are clickable. 
  - @efritz LMK if you feel the indexes still aren't obvious enough that they're clickable. It's tricky to get this right and maintain good accessibility. A big win here though, is that normal link behavior works for the index page (e.g. open in new tab)
- Update checkbox permission logic. No longer shows if user is not an admin (and thus can't use any of the controls)
- Increase checkbox clickable area
- Update commit hash styles to use `Badge`, similar to other usage in our app
- Switch delete/auto index buttons so they are consistent across pages
- If we open an errored index page, we now show the error log message by default
- Fix height of items so they are consistent within the list
- Fix dark mode hover colors

## Test plan

Tested locally

## App preview:

- [Web](https://sg-web-tr-polish-index-ui.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+0.86 kb) | 0.01% (+0.86 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/tr/polish-index-ui/compare-report.html;tab=live_object) for a full comparison between the commits b4d03cf and 962744a or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by umpox** [comment]
@efritz Couple of things:

1. You mentioned an improvement would be to show pre-index, index steps outside of the timeline. Could you elaborate where you think would be useful to show these?

2. Added a (low priority) issue to support filtering by indexer in the BE: https://github.com/sourcegraph/sourcegraph/issues/47723

3. Can you think of a short (few sentences) tooltip that will explain what the "replaceable by auto-indexing" button does?
image

**Comment by efritz** [comment]
@umpox 

1. (See linked image below). I think it would make sense to separate some of the data in the timeline _from_ the timeline entirely. The BE should return everything _except_ the timings/logs for each step of the index - the actual metadata should always be present. I think it makes sense if we move the metadata out into another tab in the precise index detail page entire and either keep the timeline view as-is or just keep the timing/logs in the timeline. Note that whatever component we end up using here could also be used to show more detail about _configurable_ jobs in the dashboard/configuration views.
2. Nice, will tackle this week.
3. _this is the way_ has a nice ring to it, but something like _Allow Sourcegraph to re-index this commit in the future and replace this data._ would be accurate.

image

**Review by efritz — APPROVED** [review]
Really liked the clickable row but if it's conflicting with a11y drop it HOT.

**Pull request merged**
