### PR TITLE
gqltest: disable and/or search test

### PR DESCRIPTION
**Pull request by bobheadxi**
https://github.com/sourcegraph/sourcegraph/issues/29828 - this failure has occurred twice in `main` already

### CODE REVIEW

**Review by rvantonder — COMMENTED** [review]
@unknwon any chance you have an idea why this test flaked or what we can do about it? I ran into a similar thing last week where the test reported 999 results but expected 1000. The build below passed with a retry:

https://buildkite.com/sourcegraph/sourcegraph/builds/125889#ffba80f5-e5df-457b-a4ca-213a1c83410d/387-391

CC @camdencheek @tsenart

**Review by rvantonder — APPROVED** [review]

**Comment by keegancsmith** [comment]
Given this is an and/or test my first suspicion would be the new concurrent or code having some minor race condition? @tsenart I bought up something minor in a call which may be the issue. There was a (we thought rare) off by one around deciding when to limit and how that interacts with file path matches vs file content matches.

**Comment by unknwon** [comment]
Raw thoughts:

Given we've ensured repositories to be cloned before starting tests, and in addition to Keegan's comment, could it be streaming search sometimes needs a longer wait time? (I couldn't tell if this tests runs with streaming mode or not, so I might be off here)

**Comment by tsenart** [comment]
I'm looking into this today.

**Comment by keegancsmith** [comment]
FYI this is the little bit of code which might contain the bug https://github.com/sourcegraph/sourcegraph/pull/29540/files#r786672991

**Pull request merged**
