### PR TITLE
Spell npm consistently.

### PR DESCRIPTION
**Pull request by varungandhi-src**
- Spelled as Npm or NPM depending on local case convention.
  For local variables and in types, Npm should be preferred.
  For fully uppercase spellings, NPM should be used.
- Default to spelling it as npm otherwise.

This matches the convention in the npm/cli code and the
[recommendation in the npm/cli README](https://github.com/npm/cli/#is-it-npm-or-npm-or-npm).

## Test plan

Ran existing tests.

### CODE REVIEW

**Comment by unknwon** [comment]
Thank you!

Idiomatically should be `NPMPackagesSyncer` not `NpmPackagesSyncer`, as `HTTPServer` not `HttpServer` 😁

**Comment by tsenart** [comment]
> Idiomatically should be NPMPackagesSyncer not NpmPackagesSyncer, as HTTPServer not HttpServer 😁

Yeah, +1. It's an acronym, so uppercase is the Go convention. Node Package Manager = NPM

**Comment by varungandhi-src** [comment]
I thought so too earlier but according to the [official documentation](https://github.com/npm/cli/#faq-on-branding), it's not an acronym.

> Is it "npm" or "NPM" or "Npm"?
>
> npm should never be capitalized unless it is being displayed in a location that is customarily all-capitals (ex. titles on man pages).

> Is "npm" an acronym for "Node Package Manager"?
>
> Contrary to popular belief, npm is not in fact an acronym for "Node Package Manager"

---

> Idiomatically should be NPMPackagesSyncer not NpmPackagesSyncer, as HTTPServer not HttpServer 😁

The npm code itself uses Npm for type names, since it is not an acronym. https://sourcegraph.com/github.com/npm/cli/-/blob/test/fixtures/mock-npm.js?L140:11

This is despite using HTTPS and not Https. https://sourcegraph.com/github.com/npm/cli/-/blob/node_modules/https-proxy-agent/dist/agent.js

**Comment by unknwon** [comment]
> > Idiomatically should be NPMPackagesSyncer not NpmPackagesSyncer, as HTTPServer not HttpServer 😁
> 
> The npm code itself uses Npm for type names, since it is not an acronym. https://sourcegraph.com/github.com/npm/cli/-/blob/test/fixtures/mock-npm.js?L140:11

Should have been said it is idiomatically just in Go, not knowledgable to talk about JS 😁

**Comment by varungandhi-src** [comment]
AFAICT, npm/cli code uses similar casing conventions for JS as we use for Go. For example OTP is spelled as OTP instead of Otp. https://sourcegraph.com/github.com/npm/cli/-/blob/lib/auth/legacy.js?L17:16

**Pull request merged**
