### PR TITLE
prometheus: alert dashboard links with fixed timestamps

### PR DESCRIPTION
**Pull request by bobheadxi**
While working on https://github.com/sourcegraph/sourcegraph/pull/17014 I added a relative timestamp to the dashboard link in alerts, did a bit of fenangling to make the link completely fixed to timestamps associated with the delivered alert.

We can depend on `(index .Alerts 0)` because our grouping strategy ensures each group delivered only has one alert.

I'm still a bit unsure about this now that I've got it working, the experience is a bit less than ideal for alerts that e.g. are spikes lasting a second, since then we get a link to a panel that has a tiny window. An alternative is [`time` and `time.window`](https://grafana.com/docs/grafana/latest/dashboards/time-range-controls/#control-the-time-range-using-a-url), but that might not be great for alerts lasting longer. It is not possible to do arithmetic on these timestamps in alertmanager templates: https://github.com/prometheus/alertmanager/issues/1188

=> **update**: see https://github.com/sourcegraph/sourcegraph/pull/17034#issuecomment-756598154

### CODE REVIEW

**Comment by pecigonzalo** [comment]
@bobheadxi You can use something like `&time=1609931477000&time.window=3600000` instead, check https://grafana.com/docs/grafana/latest/dashboards/time-range-controls/#control-the-time-range-using-a-url

**Comment by bobheadxi** [comment]
I considered that (see PR description):

> An alternative is time and time.window, but that might not be great for alerts lasting longer.

It's not a great experience if the alert spans, say, 24 hours of problems

**Comment by pecigonzalo** [comment]
I see, I did not notice that in the body my bad. I think defaulting to 1h or inferring `time.window` from something like the alert `period * 1.5` should be ok.

Eg if CPU utilization alerts when its `> 50 for 5m` we link to a dashboard of time of alert and `time.window` of `7.5m`

**Comment by bobheadxi** [comment]
>  inferring time.window from something like the alert period * 1.5 should be ok.

Unfortunately you cannot do arithmetic in alertmanager templates :/ However, I think I found a nice middle-ground strategy with e3f166ff1be18a491b39dce230c03d1c70cd1cb2:

* If start and end available, link to a fixed timeframe on the start and end
* If end is not available (alert still active), link to start and window of 1 hour

**Comment by pecigonzalo** [comment]
> Unfortunately you cannot do arithmetic in alertmanager templates

But couldnt we set that in the generated alert file when its generated by the generator?

**Review by pecigonzalo — APPROVED** [review]

**Comment by bobheadxi** [comment]
> But couldnt we set that in the generated alert file when its generated by the generator?

We can't infer `period * 1.5` for example (assuming by period you mean the time the alert is active - or you mean the `for` parameter? these are often just 0 or a small number)

**Comment by pecigonzalo** [comment]
> We can't infer period * 1.5 for example (assuming by period you mean the time the alert is active - or you mean the for parameter? these are often just 0 or a small number)

I meant the `for` parameter. To be honest, I think just using 1h for the link is also fine. /shrug

**Comment by bobheadxi** [comment]
Merging for now, can see how it works in practice :) this will be nice for looking at past alerts

**Pull request merged**
