### PR TITLE
search: send progress in done event

### PR DESCRIPTION
**Pull request by keegancsmith**
This is a non functional commit which shows where my knowledge ends for
observables. I want to make it such that done now contains a progress
payload. I want to emit that then close up the observable. I tried
factoring out the observable bits (foo) then got stuck with how to use
it in the message handler for done.

Help plz @lguychard @limitedmage

### CODE REVIEW

**Comment by lguychard** [comment]
@keegancsmith PTAL https://github.com/sourcegraph/sourcegraph/pull/16298/commits/ef4040e2a66ae7f404f3469694a1c4c13b9e1f4c

**Comment by keegancsmith** [comment]
> @keegancsmith PTAL [ef4040e](https://github.com/sourcegraph/sourcegraph/commit/ef4040e2a66ae7f404f3469694a1c4c13b9e1f4c)

nice LGTM!

**Comment by keegancsmith** [comment]
This is still not working. But I am thinking we shouldn't do this anymore. I think done should be preserved as something used by API to indicate the stream is finished. The complication it introduces in the code above + the need to update tests is a sign of why this is likely the wrong choice.

I think instead the typescript consumer API should listen for the observable being complete, then update progress to be done. So we additionally remove the "done" field from progress. @limitedmage WDYT?

**Comment by limitedmage** [comment]
> I think instead the typescript consumer API should listen for the observable being complete, then update progress to be done. So we additionally remove the "done" field from progress. @limitedmage WDYT?

This definitely works, seems like a more natural thing than returning the `done` boolean with the progress.

**Comment by limitedmage** [comment]
@keegancsmith  is this PR still current/ready for review?

**Comment by keegancsmith** [comment]
@limitedmage the suggestion of making the frontend listen to the observable being complete and treating that as done is not done. I think we should do that, so filed https://github.com/sourcegraph/sourcegraph/issues/16833

This PR is now very out of date, so gonna close it out and rely on the issue to track this idea.

**Pull request closed without merging**
