### PR TITLE
db: Migration to remove webhook_build_jobs table

### LINKED ISSUE #46562: Remove webhook build job
This was left over from our intern project and is currently unused. With recent changes to add a dashboard to display worker processes it is confusing to see this job as it doesn't do anything at the moment.

We should at the very least remove the job from [the list of jobs](https://github.com/sourcegraph/sourcegraph/blob/fa037a33cd1f7e2fc7c319a1591b27a3acb63d8c/enterprise/cmd/worker/shared/shared.go#L41)  and ideally also remove the code and db tables as we probably won't get to background webhook creation for a while and having unused code lying around isn't great.

/cc @ryphil

### PR DESCRIPTION
**Pull request by ryanslade**
As it is not being used anymore.

Closes #46562 

## Test plan

Ran up and down migrations and ran local instance manually to confirm removal.

### CODE REVIEW

**Review by sashaostrikov — APPROVED** [review]
:shipit::shipit::shipit:

**Review by mrnugget — APPROVED** [review]

**Comment by ryanslade** [comment]
4.4 has now been tagged so the backcompat tests shouldn't be running against 4.3 should they?

Do I need to wait for some other process to complete?

**Comment by mrnugget** [comment]
Have you rebased?

**Comment by ryanslade** [comment]
> Have you rebased?

Just tried that. Looks like the release is later today and I'm hoping after that goes out the backcompat tests will be bumped to 4.4.0

**Comment by mrnugget** [comment]
> Just tried that. Looks like the release is later today and I'm hoping after that goes out the backcompat tests will be bumped to 4.4.0

You can also take a quick look at how the tests work so you don't end up hoping for the wrong thing.

**Comment by ryanslade** [comment]
> > Just tried that. Looks like the release is later today and I'm hoping after that goes out the backcompat tests will be bumped to 4.4.0
> 
> You can also take a quick look at how the tests work so you don't end up hoping for the wrong thing.

Yep, looks like it happens once the release is staged:

https://github.com/sourcegraph/sourcegraph/blob/be4f4409a3a6b5b88a2188e1b03b3f57d47f1c54/enterprise/dev/ci/internal/ci/pipeline.go#L78-L79

Which happens here:

https://github.com/sourcegraph/sourcegraph/blob/d83e67512402304cb879412ebd1eb89d5ea40758/dev/release/src/release.ts#L512-L515

**Pull request merged**
