### PR TITLE
doc: Fix broken link

### PR DESCRIPTION
**Pull request by saintmalik**
## Summary

Easy navigation and easy reading for others

### CODE REVIEW

**Comment by saintmalik** [comment]
@courier-new mind checking this

**Review by courier-new — APPROVED** [review]
Thanks for fixing this!

**Comment by courier-new** [comment]
Hey @saintmalik, we recently added a Contributor License Agreement, and I think it needs to run a contributor check before our normal PR checks will run and let you merge! If you push an empty commit, or force push your existing commit, it should trigger the cla-bot to run the check. 🙂

**Comment by saintmalik** [comment]
> Hey @saintmalik, we recently added a Contributor License Agreement, and I think it needs to run a contributor check before our normal PR checks will run and let you merge! If you push an empty commit, or force push your existing commit, it should trigger the cla-bot to run the check. 🙂

Will do that

**Comment by saintmalik** [comment]
Not sure I can trigger the cla bot from here again, but I have triggered it on another pull request which I just closed and I have signed the cla

Screenshot_2021-11-08-06-45-59-614_com brave browser~2

**Comment by courier-new** [comment]
Great, thanks! I think the other PR checks won't run without cla-bot, unfortunately. 😅 I wonder if I can trigger it with a comment...

@cla-bot check

**Comment by courier-new** [comment]
Oh hmm, it sounds like it didn't find you. 🙁 Is it possible you used a different email for this commit than the one you submitted for the other PR? Sorry, this feels like overkill for a docs link change ahaha, so appreciate your patience. 🙂

**Comment by saintmalik** [comment]
> Oh hmm, it sounds like it didn't find you. 🙁 Is it possible you used a different email for this commit than the one you submitted for the other PR? Sorry, this feels like overkill for a docs link change ahaha, so appreciate your patience. 🙂

@cla-bot check

**Comment by saintmalik** [comment]
> Oh hmm, it sounds like it didn't find you. 🙁 Is it possible you used a different email for this commit than the one you submitted for the other PR? Sorry, this feels like overkill for a docs link change ahaha, so appreciate your patience. 🙂

Not sure what's wrong, I have signed and resigned now

**Comment by courier-new** [comment]
😞 Let me reach out to someone else on the team and see if we can get this sorted.

**Comment by valerybugakov** [comment]
@cla-bot check

**Comment by saintmalik** [comment]
> @cla-bot check

Can you reopen this Pull Request for me🙏🏾

**Comment by saintmalik** [comment]
Can you reopen this Pull Request for me🙏🏾 @courier-new @valerybugakov

**Comment by valerybugakov** [comment]
@saintmalik, it's not possible from my end.

Screenshot 2021-11-08 at 10 48 21

**Comment by saintmalik** [comment]
Ohhh no, looks like I will make those contribution again, will send in my PR now fixing different issues this time.

Thank you

**Pull request closed without merging**
