### PR TITLE
Add check to make sure local main branch is neither behind nor ahead of remote main branch

### PR DESCRIPTION
**Pull request by marsblkm**
Solve #31734

Added a simple, similar check to make sure local `main` branch is not ahead of remote main branch as well.

## Test plan
@coury-clark tested locally by removing the `main` branch limitation, testing a dry run slack update before the new commit, pushing a new commit, and testing to receive this error:

image

### CODE REVIEW

**Comment by marsblkm** [comment]
@sourcegraph/contribution-reviewers

**Comment by coury-clark** [comment]
@cla-bot check

**Comment by coury-clark** [comment]
Hi @marsblkm! Thanks so much for the contribution! I've added you to the CLA bot!

**Review by coury-clark — APPROVED** [review]
LGTM! 🎉 Thanks so much for the contribution!

**Comment by marsblkm** [comment]
Just curious:
@coury-clark 
It seems like some checks were not successful. Do I need to worry about them?
Totally new to this CI process so sorry if it is a dumb question

**Comment by coury-clark** [comment]
> Just curious: @coury-clark It seems like some checks were not successful. Do I need to worry about them? Totally new to this CI process so sorry if it is a dumb question

Trying to figure that out myself 😅 We've recently introduced some new CI steps for SOC2 compliance and it seems they aren't playing nice with external contributors. We're looking into it!

**Comment by marsblkm** [comment]
> > Just curious: @coury-clark It seems like some checks were not successful. Do I need to worry about them? Totally new to this CI process so sorry if it is a dumb question
> 
> Trying to figure that out myself 😅 We've recently introduced some new CI steps for SOC2 compliance and it seems they aren't playing nice with external contributors. We're looking into it!

No worries👌🏻

**Comment by unknwon** [comment]
Buildkite needs manual trigger for external contributions: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/external_contributions/#option-2-in-the-buildkite-web-interface

I just did for this one.

**Comment by coury-clark** [comment]
@marsblkm looks like the build failed, could you run `yarn prettier` in the sourcegraph repo and push a fresh commit?

**Comment by marsblkm** [comment]
> @marsblkm looks like the build failed, could you run `yarn prettier` in the sourcegraph repo and push a fresh commit?

Ah seems like a format issue. Just ran it and pushed the commit. 😁
Sorry for the trouble

**Comment by coury-clark** [comment]
Thanks @marsblkm! Just merged this change! 🎉

**Pull request merged**
