### PR TITLE
[Request access] Add admin analytics

### PR DESCRIPTION
**Pull request by erzhtor**
Closes https://github.com/sourcegraph/sourcegraph/issues/48252.

This PR adds "# of pending requests" to AnalyticsOverviewPage, AnalyticsUsersPage, and UserManagement pages.

## Screenshot

| Before | After |
| --: | :-- |
| image | image | 
| image | image |
| image | image |

## Test plan
- `sg start`
- Disable built-in signup
- Open https://sourcegraph.test:3443/site-admin
- Open https://sourcegraph.test:3443/site-admin/analytics/users
- Open https://sourcegraph.test:3443/site-admin/users
- Check that the "# of pending requests" are shown on the pages

## App preview:

- [Web](https://sg-web-erzhtor-add-request-access-admin.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by erzhtor** [comment]
@rrhyne, I realized "# pending requests" duplicates the number from the NavBar notification bar. Should we still add it to these pages?

**Comment by rrhyne** [comment]
> @rrhyne, I realized "# pending requests" duplicates the number from the NavBar notification bar. Should we still add it to these pages?

@erzhtor It is, if this number isn't hard to get to, perhaps total requests in the timeframe (approved and pending) would be better? If that is too difficult, or there is not enough time, it's fine as is. These are used in reporting and the number is important in that context.

**Review by rrhyne — APPROVED** [review]
Approving, leaving as is is fine with me!

**Comment by erzhtor** [comment]
> @erzhtor It is, if this number isn't hard to get to, perhaps total requests in the timeframe (approved and pending) would be better? If that is too difficult, or there is not enough time, it's fine as is. These are used in reporting and the number is important in that context.

Good suggestion, thank you! Let's take it as a follow-up for the future if you don't mind for now, as adding timeframe-based metrics will require some extra effort, and I'm currently low on capacity with other PRs/issues.

**Pull request merged**
