### PR TITLE
JetBrains: Detect line separator

### PR DESCRIPTION
**Pull request by vdavid**
Fixes https://github.com/sourcegraph/sourcegraph/issues/55512

## Test plan

Try to reproduce the problem on Windows.
I'm blocked on testing it by https://github.com/sourcegraph/sourcegraph/issues/55916

### CODE REVIEW

**Review by olafurpg — APPROVED** [review]
Very nice!

**Comment by vdavid** [comment]
Merging this as "definitely not worse than it was", we'll test it further when solving https://github.com/sourcegraph/sourcegraph/issues/55916

**Comment by zzl221000** [comment]
@vdavid 
[All text strings passed to Document modification methods (`setText()`, `insertString()`, `replaceString()`) must use only `\n` as line separators.](https://plugins.jetbrains.com/docs/intellij/documents.html#what-are-the-rules-of-working-with-documents)
Detecting line separator is a redundant operation

**Comment by vdavid** [comment]
@zzl221000: Thanks for that thought! is this the simplification you're suggesting? https://github.com/sourcegraph/sourcegraph/pull/56531

**Pull request merged**
