### PR TITLE
Add minimal enforced linting rules

### PR DESCRIPTION
**Pull request by camdencheek**
Adds a minimal `golangci-lint` configuration to enforce linting across
the project. Currently, the only lint it enforces is `ineffassign` since
there were only a couple of instances to change for that, and it allows
us to experiment with enforced linting with a pretty low barrier.

A separate configuration (`.golangci.enforced.yml`) was added so linting
behavior for people who have it set up as an editor integration does not
change. I think that ideally, we should aim to unify these, but for now
this strikes a nice balance between nagging lints and lints that cause CI
to fail.

Motivation: Linting occasionally helps me catch significant issues in my code,
and currently, linting is not enforced so the default `.golangci.yml` configuration
gives results that are too noisy to be useful. If we start enforcing linting, it
forces us to either explicitly ignore lints with `//nolint` or to fix them so that 
running a linter only gives results which are relevant to your current changes. 
Reviewdog is nice in that it only shows lints for the files touched in a PR, but 
that doesn't help the local development experience since there are still loads 
of ignored lints.

I'll be keeping this open for a few days to allow for questions/comments/concerns.

Note that the build should fail until the following PRs are merged:
- ~~#18699~~
- ~~#18701~~ 

Prior discussion:
- #9193
- #10858

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
I'm a fan of having this in the workflow. This is basically a rubber stamp.

I also wonder about pre-commit hooks that will run golint locally, I just haven't looked into how to set up the rules to match our CI's.

**Comment by tsenart** [comment]
FYI we already have golangci-lint running as Github action, but nothing is shown as a hard error or warning because it was deemed to noisy at a some point. Happy to see refreshed attention on this. Maybe we can unify the approaches? https://github.com/sourcegraph/sourcegraph/blob/main/.github/workflows/reviewdog.yml#L11

**Comment by camdencheek** [comment]
@tsenart Yes! My understanding is that `reviewdog.yml` uses `.golangci.yml` as its source of linters. I created a new `.golangci.mandatory.yml` so that we can still get the non-mandatory lint messages from `golangci.yml` (both from reviewdog and in people's editors), but we can add linters to `.golangci.mandatory.yml` as we fix the warnings that currently exist on `main`, with the eventual goal of unifying the two config files. Does that seem like a reasonable approach?

**Comment by camdencheek** [comment]
@rvantonder RE: rules to match our CI, we should just be able to point any git hooks at `.golangci.mandatory.yml`. Basically, just run `./dev/check/go-lint.sh` (it was changed in this PR to do just that).

**Comment by camdencheek** [comment]
@tsenart I created a tracking issue for reconciling `.golangci.yml` and `.golangci.mandatory.yml` in #18720

**Comment by tsenart** [comment]
> Does that seem like a reasonable approach?

:+1:

**Review by tsenart — APPROVED** [review]

**Comment by rvantonder** [comment]
@camdencheek it would be great if we could add an entry to our handbook about Go development and how to set up local dev to run lint (either just the command, or adding to commit hook).

**Comment by camdencheek** [comment]
Great idea -- can do!

**Review by cmego95 — COMMENTED** [review]
#18720

**Pull request merged**
