### PR TITLE
JetBrains: store access token in a safe way

### PR DESCRIPTION
**Pull request by szymonprz**
- Display access tokens in password fields so they're hidden by default
- You can edit your access token only when it's visible; if it's not visible, then you need to provide the new token
- Enterprise and dotcom access tokens on the application level are stored in a safe way using IntelliJ PasswordSafe
- We're accessing the access token only for the selected instance type

closes https://github.com/sourcegraph/cody/issues/120

## Test plan
- Access tokens should be stored in a keychain
- We should ask for permission to access a keychain item only for access token from the currently selected instance
- It should be possible to edit an access token while it's visible
- It should not be possible to edit an access token when it's not visible

### CODE REVIEW

**Comment by vdavid** [comment]
@szymonprz, I've tested it but the hide/show buttons didn't show up for me, plus it appears to delete my existing tokens: https://www.loom.com/share/18eff66c562447828e53f39a8114a37b?sid=fe0f7415-da4c-4005-baa0-fcbb165c27f3

**Comment by szymonprz** [comment]
@vdavid it is intended to clear the access token once you focus the input if the token is hidden, you can't edit it if you don't see it (we don't want to load the access token from the secure storage), We will allow you to edit the access token only if you reveal it. The design is similar to all those one time access tokens, you can see them only once and then if you want to change it you need to provide a new token or you need to reveal it (which loads the token from the secure storage and you will be asked for your password to access it, or you "allowed always" it previously)

What do you suggest to do to avoid loading the access tokens when we open the settings page, but to allow to edit the access token? 

One solution that comes to my mind is to load the access token if you focus the input and then we could replace the mock access token with the real one, wdyt?

**Comment by vdavid** [comment]
> it was intended to clear the access token once you focus the input if the token is hidden, you can't edit it if you don't see it (we don't want to load the access token from the secure storage), We will allow you to edit the access token only if you reveal it. The design is similar to all those one time access tokens, you can see them only once and then if you want to change it you need to provide a new token or you need to reveal it (which loads the token from the secure storage and you will be asked for your password to access it, or you "allowed always" it previously)

I agree with all of this, and I think we can achieve this without letting the user unintentionally delete their token.
What I'd do is simply disable the field while the show/hide status (with the eye icon) is set to "hidden".

> What do you suggest to do to avoid loading the access tokens when we open the settings page, but to allow to edit the access token?

Disable the field when the token is hidden.

> One solution that comes to my mind is to load the access token if you focus the input and then we could replace the mock access token with the real one, wdyt?

We could also trigger the "show" event when clicking the disabled textbox, for convenience. It sounds like a simple additional click event listener. You could add it to see how it feels.

Two more observations:
1. We require the user's password even when they click "hide". In this case, I don't think we're retrieving any information, so we shouldn't need to go to the keychain in this case.
2. When the user disallows access to the token from the secure store, we resort to loading the token from the XML. I think we don't want this, as it leads to the unusual and unexpected behavior that I show in the video below. In this case, we should display an error message that we don't have access.

Loom where I demo all of these:
https://www.loom.com/share/21bccaebddca487391599d90fbebbe58?sid=e92af5e5-6532-4e2a-a79e-60f0ec7faaf3

**Comment by vdavid** [comment]
Changes:
- Avoided getting infinite login windows if an enterprise instance is configured. The problem was that we asked for a l/p not just at the plugin start but at each access to the value. Now we only ask for it once and then cache it.
- Disable the field when the token is hidden.
- We no longer try to fetch the user's password even when they click "hide".
- When the user disallows access to the token from the secure store, we don't try to load the token from the XML anymore but we display an error message.
- A bunch of refactors and commenting.

**Review by vdavid — APPROVED** [review]
Went through the code once more and it all looks good to me.

**Pull request merged**
