### PR TITLE
remove many removed and unused fields from settings and site config schemas

### PR DESCRIPTION
**Pull request by sqs**
The intent of this commit is to only remove fields that are:

- entirely ineffective (such as those documented with "REMOVED")
- long-deprecated where the functionality is no longer present
- deprecated and replaced with another property that has the same effect

The intent is not to remove any fields that are in active use.

This is a followup to https://github.com/sourcegraph/sourcegraph/pull/45995.

* Closes https://github.com/sourcegraph/sourcegraph/issues/44180
* Closes https://github.com/sourcegraph/sourcegraph/issues/44181

## Test plan

The integration test suite will catch any issues.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.01% (-0.23 kb) | -0.08% (-10.80 kb) 🔽 | -0.09% (-10.57 kb) 🔽 | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/sqs/rm-many-fields-from-schemas/compare-report.html;tab=live_object) for a full comparison between the commits 5b790bd and 45cd517 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by limitedmage** [comment]
Does this close the three issues mentioned here: https://github.com/sourcegraph/sourcegraph/discussions/45232#discussioncomment-4318274 ?

**Comment by sqs** [comment]
@limitedmage:

> Does this close the three issues mentioned here: [#45232 (comment)](https://github.com/sourcegraph/sourcegraph/discussions/45232#discussioncomment-4318274) ?

Yes to the first 2, and I posted https://github.com/sourcegraph/sourcegraph/issues/44182#issuecomment-1369219243 on the 3rd.

**Review by limitedmage — APPROVED** [review]
This PR makes me soooo happy! Thank you!!

**Comment by sqs** [comment]
@limitedmage Yes, same here! :tada: Thanks for the review!

**Comment by mrnugget** [comment]
ⓝⓘⓒⓔ!

**Pull request merged**
