### PR TITLE
fix file decorations on files sidebar

### PR DESCRIPTION
**Pull request by 5h1rU**

### CODE REVIEW

**Comment by felixfbecker** [comment]
Could we prevent a regression like this in the future through an integration test with a Percy snapshot?

**Review by eseliger — APPROVED** [review]

**Review by tjkandala — APPROVED** [review]
Thank you, looks great

**Comment by 5h1rU** [comment]
> Could we prevent a regression like this in the future through an integration test with a Percy snapshot?

Do you know how to add a flag `"codecov.fileDecorations.show": true` to user settings in order to make this visible on Percy?

**Comment by felixfbecker** [comment]
The integration tests work with little sample extensions instead of the real hosted extensions, so that shouldn't be necessary. The settings are also mocked through the GraphQL mocks. You can find more info here: https://docs.sourcegraph.com/dev/how-to/testing#client-integration-tests

**Pull request merged**
