### PR TITLE
Milan/disable codehost connection checks

### PR DESCRIPTION
**Pull request by kopancek**
Disable connection checks for code hosts

This is currently implemetned as TCP dial to the code host. We have customers
behing a proxy, that disallows TCP dial, which means this check will always fail
for them, which is a false positive. On top of that, we do this check in repo
syncer as well. If the check fails, we disable repo syncing.

We decided a safer approach for now is to disable the feature and create a patch
release, so that we can unblock the affected customers.

We will fix these checks in a followup PR.

Related: https://github.com/sourcegraph/sourcegraph/issues/46915

## Test plan

Testing manually locally.

### CODE REVIEW

**Review by sashaostrikov — COMMENTED** [review]
2 main things I am thinking about:
1) Should we just implement better check like in what is done in [this PR](https://github.com/sourcegraph/sourcegraph/pull/46904) and not remove connection check functionality?
2) If we want to remove it, I'd remove the code instead of commenting this out. Git remembers everything and our codebase is clean&clear without commented out code :)

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.01% (-0.38 kb) | -0.01% (-0.79 kb) | -0.00% (-0.41 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/milan/disable_codehost_connection_checks/compare-report.html;tab=live_object) for a full comparison between the commits 1abfe67 and eabdecd or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by mrnugget** [comment]
> 2 main things I am thinking about:

Here's how I see it:

1. We need to ship a patch release to fix this issue for customers. It's stopping their code from being synced.
2. We need to keep patches as small as possible.
3. Disabling the checks is pretty small.
4. We want to keep the checks and make them better.

That lead me to this idea: disable the checks in patch release, then fix them on `main` properly.

Another option is to add a feature flag on top.

**Comment by mrnugget** [comment]
> 2\. If we want to remove it, I'd remove the code instead of commenting this out. Git remembers everything and our codebase is clean&clear without commented out code :)

Woops, I shouldn't have commented before looking at the code 😄 Yes, I agree we shouldn't comment code out and instead remove it.

**Comment by mrnugget** [comment]
superseeded by https://github.com/sourcegraph/sourcegraph/pull/46918

**Pull request closed without merging**
