### PR TITLE
github: Request 'repo' OAuth scope

### PR DESCRIPTION
**Pull request by ryanslade**
This will allow us to more easily enable private code in future.

Closes: https://github.com/sourcegraph/sourcegraph/issues/20250

### CODE REVIEW

**Comment by ryanslade** [comment]
@sourcegraph/batchers Just to be safe, does this affect anything on your side?

**Comment by eseliger** [comment]
We currently don't use oauth mechanisms, so this should be safe :)

**Review by unknwon — APPROVED** [review]
The change itself LGTM, not sure how it would impact users who are not willing to give us access to private repositories though.

**Comment by ryanslade** [comment]
I guess those users can choose to add their own token?

**Comment by unknwon** [comment]
> I guess those users can choose to add their own token?

Good point!

**Pull request merged**
