### PR TITLE
Support Node 13

### PR DESCRIPTION
**Pull request by felixfbecker**
Test plan:

### CODE REVIEW

**Comment by eseliger** [comment]
have you tried this out on your local machine? Since CI doesn't respect engine versions in the `package.json`

**Comment by unknwon** [comment]
FYI, 13.1 fails on my local dev, I tried the same change a week ago, not sure anything has changed in our codebase regarding support Node 13.

**Comment by felixfbecker** [comment]
@unknwon what errors are you seeing?

**Comment by unknwon** [comment]
I'm running macOS 10.15.1

```
$ node -v
v13.2.0
```

```

direnv: export +NO_KEYCLOAK +PGDATABASE +PGHOST +PGPASSWORD +PGPORT +PGSSLMODE +PGUSER
➜  sourcegraph git:(master) ./enterprise/dev/start.sh
Installing enterprise web dependencies...
yarn install v1.16.0
[1/5] 🔍  Validating package.json...
error @: The engine "node" is incompatible with this module. Expected version ">=8.0.0 <13.0.0". Got "13.2.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
➜  sourcegraph git:(master) ./enterprise/dev/start.sh
Installing enterprise web dependencies...
yarn install v1.16.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "history@4.5.1" is incompatible with requested version "history@^4.9.0"
warning Resolution field "history@4.5.1" is incompatible with requested version "history@^4.9.0"
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > graphiql@0.13.2" has unmet peer dependency "prop-types@>=15.5.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface@1.3.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-parser@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-config@2.0.1" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-language-service-types@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-language-service-utils@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-config > graphql-import@0.4.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning " > monaco-editor-webpack-plugin@1.7.0" has incorrect peer dependency "monaco-editor@^0.15.1".
[5/5] 🔨  Building fresh packages...
[9/17] ⢀ node-sass
[-/17] ⢀ waiting...
[8/17] ⢀ iltorb
[7/17] ⢀ fsevents
error /Users/joe/Sourcegraph/sourcegraph/node_modules/iltorb: Command failed.
Exit code: 1
Command: node ./scripts/install.js || node-gyp rebuild
Arguments:
Directory: /Users/joe/Sourcegraph/sourcegraph/node_modules/iltorb
Output:
info looking for cached prebuild @ /Users/joe/.npm/_prebuilds/d99c28-iltorb-v2.4.3-node-v79-darwin-x64.tar.gz
http request GET https://github.com/MayhemYDG/iltorb/releases/download/v2.4.3/iltorb-v2.4.3-node-v79-darwin-x64.tar.gz
http 404 https://github.com/MayhemYDG/iltorb/releases/download/v2.4.3/iltorb-v2.4.3-node-v79-darwin-x64.tar.gz
WARN install No prebuilt binaries found (target=13.2.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@13.2.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp http GET https://nodejs.org/download/release/v13.2.0/node-v13.2.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v13.2.0/node-v13.2.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v13.2.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v13.2.0/SHASUMS256.txt
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joe/Sourcegraph/sourcegraph/node_modules/iltorb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joe/Library/Caches/node-gyp/13.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/joe/Library/Caches/node-gyp/13.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/joe/Library/Caches/node-gyp/13.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/joe/Sourcegraph/sourcegraph/node_modules/iltorb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/joe/Sourcegraph/sourcegraph/node_modules/iltorb




warning Error running install script for optional dependency: "/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@13.2.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@13.2.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@13.2.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@13.2.0 | darwin | x64
gyp http GET https://nodejs.org/download/release/v13.2.0/node-v13.2.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v13.2.0/node-v13.2.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v13.2.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v13.2.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/joe/Sourcegraph/sourcegraph/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joe/Sourcegraph/sourcegraph/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joe/.node-gyp/13.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/joe/.node-gyp/13.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/joe/Sourcegraph/sourcegraph/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/joe/.node-gyp/13.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/joe/Sourcegraph/sourcegraph/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command \"/usr/local/Cellar/node/13.2.0/bin/node\" \"/Users/joe/Sourcegraph/sourcegraph/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64\" \"--napi_version=5\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v79\"
gyp ERR! cwd /Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.2.0/bin/node /Users/joe/Sourcegraph/sourcegraph/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1023:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/13.2.0/bin/node\" \"/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents
node-pre-gyp ERR! node -v v13.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/13.2.0/bin/node /Users/joe/Sourcegraph/sourcegraph/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/joe/Sourcegraph/sourcegraph/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)"
info This module is OPTIONAL, you can safely ignore this error
```

**Comment by felixfbecker** [comment]
@unknwon I don't get that error, I suspect you'd get the same error if you had to compile a native extension for Node 12. My guess is that it's an issue with the Catalina security system. Check out the solution in this thread to reinstall the tools: 

```
sudo rm -rf $(xcode-select -print-path)
xcode-select --install
```

https://github.com/schnerd/d3-scale-cluster/issues/7#issuecomment-550579897
and also: https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md

**Comment by felixfbecker** [comment]
Merging as I can't find any issues and the change itself is harmless (you can continue to use Node 12)

**Comment by unknwon** [comment]
Thanks, fixed!

**Pull request merged**
