### PR TITLE
describe the default repo set in the search results banner

### LINKED ISSUE #5091: search results on sourcegraph.com don't make clear which repos were searched or how many
Here is an example of search results:
Screen Shot 2019-08-05 at 1 52 06 PM

There is no indication of how many repositories were searched, and no link to find out which ones.

### PR DESCRIPTION
**Pull request by ijt**
Fixes #5091 

Test plan: manual

### CODE REVIEW

**Comment by ijt** [comment]
@felixfbecker, @nicksnyder suggested this in #5091.

**Comment by felixfbecker** [comment]
But the banner is shown in all cases, even if I have specified a `repo:` filter. That is confusing because as a first time user, this being an alert I first think it means it is searching over the top 500 repos instead of my filter, only to realise (if I read to the end) that apparently I'm supposed to do exactly what I just did. In which case I wonder, why would the software show me the alert then?

**Comment by nicksnyder** [comment]
> That is confusing because as a first time user

My hunch is that first time users usually won't specify a `repo:` filter (because they aren't going to be familiar with our filter syntax) and if they are not a first time user they have probably dismissed the banner.

Even if they are a first time user and specify a `repo:` filter I don't think the message is that confusing due to the clauses that clarify behavior:

> Sourcegraph.com searches over the top 500 GitHub repositories **by default**. You can search over other public repositories **by providing a repo: filter**

Any user that uses a `repo:` filter and actually reads the message should understand that their search is in the latter category, not the former.

@ijt we could also test the search string for the presence of `repo:` or `repogroup:` and adjust the message based on that. I think this would be easy to do?

```
// pseudocode
if query contains "repo:" or "repogroup:" then
    display previous message
else
   display current message
```

**Comment by ijt** [comment]
Done in https://github.com/sourcegraph/sourcegraph/pull/5142.

**Pull request merged**
