### PR TITLE
 docs: Ritza editing january 2023 

### PR DESCRIPTION
**Pull request by sixhobbits**
## Test plan

Test plan No tests required as these are only grammatical fixes in the documentation.

succeeds https://github.com/sourcegraph/sourcegraph/pull/47261

### CODE REVIEW

**Review by jdorfman — APPROVED** [review]

**Comment by jdorfman** [comment]
@camdencheek can you help figure out why this isn't passing? They are just grammar fixes.

**Comment by camdencheek** [comment]
@jdorfman We need to opt out of backporting to the 5.0 branch with the `confirm-no-backport` label. These will go live on our docs site when merged, but we don't need to cut a new release candidate for them.

**Comment by jdorfman** [comment]
@camdencheek ahhh got it thanks!

**Comment by eseliger** [comment]
As part of #wg-delete-week I am going to close this PR. If it’s still needed, feel free to reopen and restore the branch.

**Pull request closed without merging**
