### PR TITLE
Remove non-community repogroups

### PR DESCRIPTION
**Pull request by limitedmage**
Removes the following repogroup pages:

- `refactor-python2-to-3`
- `golang`
- `react-hooks`
- `android`

The repogroups themselves are not removed and they will continue to function with the `repogroup:` filter. They are in the global settings for Sourcegraph.com.

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
Rubber stamp, I'm guessing there was a decision somewhere, can't tell from description.

**Comment by limitedmage** [comment]
@rrhyne  Let me know if it's OK to check this in now.

**Comment by rrhyne** [comment]
Good with it, but would like to know if there are any visual repercussions with the current layout. To that end, can I get a screenshot?

**Review by rrhyne — APPROVED** [review]
LGTM!

**Pull request merged**
