### PR TITLE
Disable Terraform scanning step in Buildkite pipeline

### PR DESCRIPTION
**Pull request by ferozsalam**
Until we can move to using a pinned Checkov image version – the lack of image pinning is causing the build step to break unpredictably.

## Test plan

Confirm that the build step no longer occurs

### CODE REVIEW

**Review by andreeleuterio — APPROVED** [review]

**Review by bobheadxi — APPROVED** [review]
you'll need to comment out `addTerraformScan` (the entire function) + regenerate the docs (`sg generate go` or `go generate ./enterprise/dev/ci`)

**Comment by ferozsalam** [comment]
> you'll need to comment out `addTerraformScan` (the entire function) + regenerate the docs (`sg generate go` or `go generate ./enterprise/dev/ci`)

We're probably going to reintroduce this functionality soon, but with a pinned package version – does this still apply?

**Comment by bobheadxi** [comment]
@ferozsalam yeah we still need to do it, or CI won't let you merge this PR 😅

**Comment by ferozsalam** [comment]
Thanks @bobheadxi!

**Pull request merged**
