### PR TITLE
ranking: Add initial service

### PR DESCRIPTION
**Pull request by efritz**
This is a stub implementation of a codeintel ranking service. Next steps (post-merge) will be to:

1. Add usable stub implementations (star count + lexicographic ordering of files)
2. Have @keegancsmith integrate with a branch of search code that consumes these rankings
3. Begin indexing repo rankings in the background
4. Modify service API definitions to return indexed rank when it exists (discuss fallback expectations)

## Test plan

No new testable behavior.

### CODE REVIEW

**Comment by keegancsmith** [comment]
@stefanhengl and I discussed this this morning:

```
BulkRankRepos(repoIds) -> []float64?
```


This looks good. For the demo, we likely will only incorporate rank at the time of indexing a repository. This means I suspect zoekt will only call `BulkRankRepos` with one ID. Are you expecting zoekt to do large sets here, so that you can work out relationships between repos? I imagined that zoekt asking for repo ranks, the service would of calculated this between all repos on an instance.

Do you need to know the SHA of the repo we are indexing to calculate rank?

We could make this part of `IndexOptions`. But that means it needs to be performant. If its not performant and we want to run this in production, we are either gonna need to limit which repos we turn this on for, or engineer in some stuff were we index and calculate repo rank concurrently.

What is the `float64`? Is it `[0,1]`? Additionally, is a rank of `0.5` twice as good as `0.25`? IE are we linear, logarithmic, etc? This feels like something we should document in the API, but obviously we can change it. Reason I ask now is because it will affect how we mix in the rank with other scores we calculate.

```
BulkRankDocuments(...) -> ...?

(repo, paths) -> []float64?
(repo, commit, paths) -> []float64?
(repo@commit) -> map[string]float64?
(repo@commit) -> io.ReadCloser
(repo) -> io.ReadCloser
```


I think any of these work, so whatever is most convenient. Also I think we can change it as we go. Zoekt does chunk up repos into 100MB chunks, so it could be asking these questions per 100MB chunk (which likely would be good for monorepos). But this means we need to integrate sourcegraph APIs into the zoekt indexer. It would be nice instead to just bulk download some artifact with all ranks for a repo. In future we likely wanna think about subsets of paths for incremental indexing. So if I had to pick a winner, it would be the one that returns an `io.ReadCloser` in a simple format. This is since inside of Sourcegraph we won't actually care about the data, we are just passing it on to zoekt.

Note: this artifact could also include the repo score.

**Comment by keegancsmith** [comment]
There is some way using sg I think to trigger docker image builds in CI. You could then pull down the server docker image locally and test.

**Comment by efritz** [comment]
@keegancsmith Thanks for the thoughts!

> Are you expecting zoekt to do large sets here, so that you can work out relationships between repos?

No, I think we'll need to rank repos in the background and only return online ranking data. I'm not sure what the appropriate (long term and/or demo) solution is for when we don't have an indexed page rank for something Zoekt is indexing **now**. For the demo maybe we can just force the ranking to happen online? This has scale issues but could be smooth if we sufficiently feature flag it.

> Do you need to know the SHA of the repo we are indexing to calculate rank?

Can use `HEAD` always if that makes sense.

> [...] engineer in some stuff were we index and calculate repo rank concurrently.

I'm leaning this way. Periodically refresh a global index and use the latest data with a fallback for repos that aren't yet represented.

> What is the `float64`?

Up to you. Since we have a global ranking here for repos, the float could literally be `position / # positions` and we get a total order when compared to other repos.

> This is since inside of Sourcegraph we won't actually care about the data, we are just passing it on to zoekt.

That's true for the offline ranking, but online ranking scores will be consumed by the GraphQL layer in the `frontend`, no? We should aim to keep the API uniform so that the act of _getting a rank for an object_ kinda looks the same from any direction (although perf guarantees will definitely have to be considered with a particular consumption pattern in mind).

**Comment by keegancsmith** [comment]
@efritz how are you feeling about the signature for the document ranks in a repo? I have a feeling I'll have some time to work on this tomorrow, so just wanna get started on the more likely API.

**Comment by efritz** [comment]
@keegancsmith How does this signature look? 

d4d5ca771b0a2b47d965633d323d6d3a342dcc3f

**Comment by keegancsmith** [comment]
LGTM

**Comment by efritz** [comment]
@keegancsmith Should we merge this stub and iterate on `main`?

**Review by keegancsmith — APPROVED** [review]
LGTM

**Pull request merged**
