### PR TITLE
graphqlbackend: Escape path in TreeEntry.url

### PR DESCRIPTION
**Pull request by keegancsmith**
Test plan: unit and browsing locally github.com/ggilmore/q-test

Part of https://github.com/sourcegraph/sourcegraph/issues/4408

### CODE REVIEW

**Comment by keegancsmith** [comment]
@felixfbecker From testing locally I see the frontend treats the TreeEntry.path inconsistently. It depends on if I navigate via the sidebar or the main file explorer. Currently it TreeEntry.path is not escaped. What do you think the correct thing to do here?

Via sidebar I end up at: http://localhost:3080/github.com/ggilmore/q-test/-/blob/Geoffrey's%20random%20queries.32r242442bf/%%20token.4288249258.sql
```
URIError: Failed to decode param '/github.com/ggilmore/q-test/-/blob/Geoffrey's%20random%20queries.32r242442bf/%%20token.4288249258.sql'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:317:13)
    at /Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:317:13)
    at /Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/keegan/go/src/github.com/sourcegraph/sourcegraph/node_modules/express/lib/router/index.js:335:12)
```

Via main file explorer I end up at: http://localhost:3080/github.com/ggilmore/q-test/-/blob/Geoffrey's%20random%20queries.32r242442bf/%%20token.4288249258.sql
and get this error: `Pathname "/github.com/ggilmore/q-test@82c0b5724db782d5983ac8aace4635762266e892/-/blob/Geoffrey's%20random%20queries.32r242442bf/%%20token.4288249258.sql" could not be decoded. This is likely caused by an invalid percent-encoding.`

**Comment by felixfbecker** [comment]
The two links you posted are identical?

Is this testing from this branch or master?

**Comment by keegancsmith** [comment]
from this branch. on master nothing in the repo renders. Sorry yeah they are the same link, so not inconsistent. I think the error just happens at a different layer. One presented me with a blank page with just the stack trace, the other was a nicer error page in our app.

**Comment by keegancsmith** [comment]
Either way I think this PR is a clear improvement. There are some other bugs probably. I am unsure if path should be escaped or not. If escaped, then I can update this PR. If not, we need to update the webapp in another PR.

**Comment by felixfbecker** [comment]
Imo `path` should not be escaped, since it is not a URL. I would expect it to be the file path as in OS file system or git semantics.

Do you want me to test this branch and look into it?

**Comment by keegancsmith** [comment]
yes please. I can just merge this into master, since this PR just escapes URL (like it should do). Then we can follow-up with path.

**Comment by felixfbecker** [comment]
SGTM

**Comment by felixfbecker** [comment]
@keegancsmith I cannot repro the above error. How did you reproduce it? What did you mean with "main file explorer"?

**Comment by keegancsmith** [comment]
I'll comment on the linked issue

**Pull request merged**
