### PR TITLE
Backend: return an error on concurrent transaction usage

### PR DESCRIPTION
**Pull request by camdencheek**
This upgrades concurrent transaction usage from a log message to a hard error for every method except `QueryRow`. I cannot make `QueryRow` a hard error because I cannot construct a `*sql.Rows` object from an error. In the future, this may be upgraded to a panic.

We want errors here so that we can propagate the error upwards with information. Right now, we get a stack trace, but that stack trace ends at every goroutine boundary, so it's difficult to trace the source. With an error, we can propagate that error up and figure out where the goroutine was spawned from.

## Test plan

Added unit test for the new error return values and updated unit test to ensure we're still logging for the `QueryRow` case.

### CODE REVIEW

**Comment by camdencheek** [comment]
@sourcegraph/code-intel and @sourcegraph/batchers, could you take a look at the failing tests to see whether the things they are testing are actually using transactions concurrently, or whether these are just tests that need updated? This PR upgrades concurrent transaction usage to an error, so these tests would have previously just logged a problem.

**Comment by camdencheek** [comment]
@Numbers88s (pinging based on git blame), it looks like there is at least one real issue [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@30fd54e7d605fa1079ed762e99215a8bd930e6a2/-/blob/enterprise/internal/codeintel/uploads/internal/store/store_uploads.go?L1596-1598). Three goroutines are spun up that concurrently write to the same transaction.

**Comment by Numbers88s** [comment]
> @Numbers88s (pinging based on git blame), it looks like there is at least one real issue [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@30fd54e7d605fa1079ed762e99215a8bd930e6a2/-/blob/enterprise/internal/codeintel/uploads/internal/store/store_uploads.go?L1596-1598). Three goroutines are spun up that concurrently write to the same transaction.

@efritz ☝️

**Comment by camdencheek** [comment]
The batch change issues appear to be from some feature flag concurrency. I'll handle that one

**Comment by camdencheek** [comment]
> What's the issue with concurrent transaction usage?

It breaks things. Using transactions concurrently yields unpredictable results. While investigating this originally, usually it would cause a cryptic error like `driver: bad connection`. However, occasionally, it would cause a panic in the driver. I also remember there being a github issue suggesting this could cause data corruption, but I didn't ever go far enough to verify that myself and I can't find it after a few seconds of searching, so I might be making that up.

A while ago, I updated the transactions to wrap all operations in a mutex, so it at _least_ protects against the most common issues and it provides visibility into where this happening by logging an error message. This works alright for any writes, but it does not provide real protection for reads because the rows object returned holds a reference to the connection that outlasts the lifetime of the mutex lock. 

This lock serializes all operations on a transaction, so your concurrent inserts here are not actually concurrent right now anyways. This PR changes the logic so that, instead of serializing, we just return an error that explains that the transaction is being used concurrently.

**Comment by camdencheek** [comment]
Feature flag issues fixed [here](https://github.com/sourcegraph/sourcegraph/pull/45747#issue-1499204156)

**Comment by camdencheek** [comment]
> committing this now will likely just trash all LSIF/SCIP uploads in the interim.

I'm happy to delay this if it'll get in the way of your stuff. I do think we should eventually merge this change though. Concurrent transaction usage is very unsafe, and the safeguards I added a while ago do not protect against everything.

**Comment by camdencheek** [comment]
Closing since this is quite old and the logging is good enough for now

**Pull request closed without merging**
