### PR TITLE
gitserver: use fetch when cloning

### PR DESCRIPTION
**Pull request by keegancsmith**
Instead of calling git clone, we can instead run `git init` followed by
a `git fetch`. This allows us to remove clone specific code which
duplicated logic between fetch and clone.

Additionally clone was the only place storing the remoteURL on disk for
gitserver. So by relying on fetch we will not store the remoteURL on
disk anymore. A separate commit will remove existing remoteURLs on disk.

Tomas and I audited the callsites which do remote calls and all of them
specify the remoteURL as a command line argument. Additionally we never
refer to a "git remote", so we don't need to store a git remote.

The only other setting we would get from clone is we set
"--mirror". However, this didn't affect anything in our setup since:
- We specify which refs to fetch
- We never do a push without specifying a ref.

The only potential breaking change here is users of customFetchCmd. We
are only aware of one customer using this. Now that we won't have a
remote set, it is possible the customFetchCmd would break if it used
it. We call this out explicitly in our CHANGELOG and will follow-up with
Customer Engineering to ensure the potentially affected customer is
aware. If it does affect them they can specify additional arguments to
fetch (such as the remote URL) to unblock.

Co-authored-by: @tsenart

### CODE REVIEW

**Review by tsenart — APPROVED** [review]

**Review by arussellsaw — APPROVED** [review]

**Comment by keegancsmith** [comment]
@tsenart not sure why this is failing the `git log` tests. We do some funky stuff around how we setup git repos in the test, which is my suspicion. Alternatively this is exposing a real breakage :) I don't have bandwidth to investigate this tomorrow, could you take this over the finish line?

**Comment by tsenart** [comment]
> I don't have bandwidth to investigate this tomorrow, could you take this over the finish line?

I will! Thanks for pairing with me on this today!

**Comment by tsenart** [comment]
@keegancsmith: It seems there are differences between the old code and the new code that cause functional disparities. Here's a diff of the old and new `.git` directories that gitserver produces in `TestRepository_RawLogDiffSearch`.

```diff
$ diff -r old.git/ new.git/
Only in new.git/: FETCH_HEAD
diff -r old.git/HEAD new.git/HEAD
1c1
< ref: refs/heads/branch2
---
> ref: refs/heads/master
diff -r old.git/config new.git/config
7,10d6
< [remote "origin"]
<       url = file:///var/folders/sp/9jflt4d96wn7bgbq312dswx40000gn/T/test592535169/remotes/TestRepository_RawLogDiffSearch124699628
<       fetch = +refs/*:refs/*
<       mirror = true
Only in new.git/objects: 11
Only in new.git/objects: 2d
Only in new.git/objects: 34
Only in new.git/objects: 4a
Only in new.git/objects: aa
Only in new.git/objects: b9
Only in new.git/objects: ce
Only in new.git/objects: d8
Only in old.git/objects/pack: pack-681593ca8b2f7f95e60dd8b77f0272036bf235fe.idx
Only in old.git/objects/pack: pack-681593ca8b2f7f95e60dd8b77f0272036bf235fe.pack
Only in old.git/: packed-refs
Only in new.git/refs/heads: branch1
Only in new.git/refs/heads: branch2
Only in new.git/refs/heads: master
Only in new.git/refs/tags: mytag
```

Not sure my git-foo is enough to proceed :D Any hints from this output?

**Comment by keegancsmith** [comment]
@tsenart what is in `Only in old.git/: packed-refs`? The fact that `HEAD` is master in new is a sign that something in this implementation may not be working. We have some code which tries to find out what the remote HEAD is, that might have broken here?

**Comment by tsenart** [comment]
@keegancsmith

```
$ cat old.git/packed-refs
# pack-refs with: peeled fully-peeled sorted 
b9b2349a02271ca96e82c70f384812f9c62c26ab refs/heads/branch1
aad4ca5293b3544eb170b8782e61331b3da901cd refs/heads/branch2
ce72ece27fd5c8180cfbc1c412021d32fd1cda0d refs/heads/master
ce72ece27fd5c8180cfbc1c412021d32fd1cda0d refs/tags/mytag
```

**Comment by tsenart** [comment]
>  We have some code which tries to find out what the remote HEAD is, that might have broken here?

Yeah, we have `ensureHead` which looks at the `HEAD` file and makes sure one exists if it can't find one, defaulting to master. Seems like `git fetch` doesn't create a `HEAD` file, only a `FETCH_HEAD` one. Would it be safe to change `ensureHead` to look at `FETCH_HEAD` instead? Do you know the reason for git having these two different files?

**Comment by tsenart** [comment]
Technically, a git clone is a git fetch followed by a git merge FETCH_HEAD. Maybe we're just missing that last command? Does that make sense?

**Comment by keegancsmith** [comment]
We won't be able to run merge because we have a bare checkout. A downside of running fetch with a refspec is git doesn't normal advertise symrefs (ie HEAD). We support parsing out the refspec when we run fetch. See the code which uses git show in our doUpdate code. We need to run that code when cloning.

I think we should add a test in gitserver which checks unusual default branch on clone, and then default branch updates for future fetches. The code before this PR should pass this, and I suspect will break in this PR (until we fix it).

**Comment by unknwon** [comment]
>Instead of calling git clone, we can instead run git init followed by
a git fetch. 

This is brilliant!

**Pull request merged**
