### PR TITLE
fix(build): update wolfi image lock for otel

### PR DESCRIPTION
**Pull request by Chickensoupwithrice**
We need to update the wolfi lock image for https://github.com/sourcegraph/sourcegraph/pull/63171 in order for `sg run` to work

We've made all the changes to the deployment repos for this to be pushed out in the release today. 

## Test plan

Manually tested

## Changelog

- fix(build): update wolfi lock for otel-collector

### CODE REVIEW

**Comment by Chickensoupwithrice** [comment]
Not sure why there's so many merge commits? The file changed is the correct one.

**Review by bobheadxi — APPROVED** [review]
🔥

**Comment by willdollman** [comment]
Is this PR intended to update the otel package to the 0.103.0-9 version that was introduced in [this pr](https://github.com/sourcegraph/sourcegraph/pull/63171/files#diff-c4b85f9a40207f45cc97a051e50a08352bbe2302c44b65911deec373410c4ad1R3)? This doesn't do that - you can inspect the lockfile to see that it's still including the old 0.92.0-r7 version https://github.com/sourcegraph/sourcegraph/blob/03ac595af93455f101b59211ca8bdfc03101a886/wolfi-images/opentelemetry-collector.lock.json#L748-L754

**Comment by willdollman** [comment]
I suspect `sg wolfi lock opentelemetry-collector` was run before the buildkite pipeline for the original PR had completed, so it pulled in a list of packages before the updated otel package had been published. 

I've rerun the command locally and it pulls in the updated package - see https://github.com/sourcegraph/sourcegraph/pull/63758

**Comment by Chickensoupwithrice** [comment]
Thank you @willdollman 🙏🏽  saving my ass

**Comment by willdollman** [comment]
very happy to see this change land at last! 😍

**Comment by Chickensoupwithrice** [comment]
Okay, fixed up the git history, and made sure the updated version of `otel` is part of the lock file

**Review by willdollman — APPROVED** [review]

**Pull request merged**
