### PR TITLE
app: add splashscreen window

### PR DESCRIPTION
**Pull request by burmudar**
This adds the splash screen created by @toolmantim! for context see https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687145983903239
## Test plan
built the app locally and tested out the splash screen

### CODE REVIEW

**Review by vovakulikov — COMMENTED** [review]
@burmudar I haven't debugged the rust shell, but it seems like something is failing there because it looks like the API shell isn't loaded properly. The window isn't draggable or resizable, and toolbar isn't rendered. 

Screenshot 2023-06-19 at 15 34 01

**Review by limitedmage — COMMENTED** [review]
Why are we creating a new window instead of using the existing `app-shell`'s `index.html` file in the main window?

**Comment by burmudar** [comment]
> Why are we creating a new window instead of using the existing `app-shell`'s `index.html` file in the main window?

With a separate window it feels similar to other splash screens I've experienced (but might be wrong!). The splash window also has no decorations as apposed to the main window.

**Comment by burmudar** [comment]
@vovakulikov tested it out on my side and I'm not experiencing that. When you have time can we have a quick zoom just so that I can try to recreate it my side!

**Comment by toolmantim** [comment]
Exciting!! Thanks for bringing this to life.

I was wondering what the discussion about the extra window was… and read https://tauri.app/v1/guides/features/splashscreen/. It's a bit odd they assume you want a separate window, isn't it? I would have assumed it would be the same window… ala Figma & Slack. Might be worth checking if that feels better?

Any tips for booting the app locally, so I can review?

**Comment by burmudar** [comment]
> Exciting!! Thanks for bringing this to life.
> 
> I was wondering what the discussion about the extra window was… and read https://tauri.app/v1/guides/features/splashscreen/. It's a bit odd they assume you want a separate window, isn't it? I would have assumed it would be the same window… ala Figma & Slack. Might be worth checking if that feels better?
> 
> Any tips for booting the app locally, so I can review?

Have to do a full build unfortunately. The shell doesn't behave the same way in dev mode! I'll send a build that I've done recently :D

re: The windows - Keeping it in one window as @limitedmage mentioned will definitely simplify this as currently there is a juggling of windows that have to be showed and closed etc.

I'll circle back to this later today or tomorrow to move it to one window

**Review by limitedmage — APPROVED** [review]

**Pull request merged**
