### PR TITLE
Take percy snapshots of storybooks

### LINKED ISSUE #9565: Add Percy tests from storybooks
Percy supports screenshotting storybooks.
- This way we can expand our stoybook library and get free unit tests for free
- It adds a layer of testing we are severely undertesting, which is styling
- It makes it easier for the design team to review changes, as they can review screenshots in Percy
- One screenshot can replace dozens of assertions, and is way easier to evolve

First came up in https://sourcegraph.slack.com/archives/CMT39K56Z/p1579792526049200

### LINKED ISSUE #10631: Record coverage of Storybooks
Splitting this out of https://github.com/sourcegraph/sourcegraph/issues/9565 because it is more involved.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #9565 
Closes #10631

Also simplifies our Storybook config (Storybook has new recommended config approaches since 5.3).

The coverage and uploading to Percy is separate, because Percy doesn't actually run our storybook in CI. It just gets all static HTML and uploads it to Percy to do the screenshotting in the cloud. We therefor track the coverage by loading each story in Puppeteer in a separate job.

This fixes one important bug that took a long time to find - our Puppeteer coverage reporter overwrote coverage files from previous tests. This must have been a problem for e2e coverage too.

Check out the Percy report in the GitHub status checks below, and the coverage report in the Codecov comment below.

### CODE REVIEW

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
2 things I noticed:

- Percy doesn't know it's only a subset of snapshots, so it complains about snapshots missing in the upload (the ones from e2e tests). Hence, I think once e2e runs all the snapshots will be marked as new and a diff check is lost
- Codecov cli logs the following:
```
==> Searching for coverage reports in:
--
  | + .
  | -> Found 3 reports
  | ==> Detecting git/mercurial file structure
  | ==> Reading reports
  | + ./shared/src/e2e/coverage.ts bytes=2180
  | + ./.storybook/coverage.test.ts bytes=704
  | + ./coverage/coverage-final.json bytes=1606867
  | ==> Appending adjustments
```

I don't know if it's an immediate problem, but they seemingly upload our two TS files as reports as well, probably because they are named `coverage` 😁

**Comment by felixfbecker** [comment]
Ah, you're right :/
This sounds like a general problem if we have e2e tests screenshot and _any_ other tests screenshot, and have e2e tests not run on every commit but the other tests. Any ideas for a solution?

**Comment by felixfbecker** [comment]
Configured with separate projects, I think this should solve it. https://docs.percy.io/docs/multiple-projects-per-repo

**Comment by eseliger** [comment]
I think we should estimate the cost of this as well - we generate a whole lot of snapshots for these tests, and percy charges per snapshot.
We currently generate 41 of them - at 1 width for both Chrome and Firefox, which yields 82 snapshots per build in CI, in the past month, we had 2690 builds in BK, totalling to 220580 snapshots. At the first 10000 free, and $0.006/snapshot, that'll cost us an additional 
((2690)*82-10000)*0.006=$1263.48

I think one way to reduce it is to disable Firefox in the percy project, which slashes it in half already

**Comment by felixfbecker** [comment]
That's a good point. I think we should also consider alternatives to Percy. For example, [Chromatic](https://www.chromatic.com/) has flat pricing tiers, is by the Storybook creators and has more features dedicated to Storybooks we could find valuable: It also hosts our storybook in the cloud and allows commenting and discussing it, which could be useful for our design process.

cc @rrhyne

**Comment by eseliger** [comment]
Where did you see that? I only find pricing tiers that are equally priced as Percy (per Snapshot and 0.006 ea)

**Comment by felixfbecker** [comment]
Ah I missed the "extra screenshot" price. It still seems though that with the same amount of snapshots, the Pro plan of Chromatic would be cheaper than Percy.

**Comment by felixfbecker** [comment]
@eseliger Percy has different plans - I think at that volume we wouldn't use the "Small" plan with 10k included anymore

- Small: 10k for $29/month plus $0.006 per additional screenshots
- Medium: 80k for $349/month plus $0.006 per additional screenshots
- Large: 200k for $849/month plus $0.006 per additional screenshots

**Comment by eseliger** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/10666

**Pull request merged**
