### PR TITLE
database: Remove repo external service indirection

### PR DESCRIPTION
**Pull request by ryanslade**
We don't need to go via repo-updater, we can query the database
directly.

### CODE REVIEW

**Comment by tsenart** [comment]
@ryanslade: Is this PR supposed to not be draft? You assigned reviewers so I'm not sure :)

**Comment by ryanslade** [comment]
> @ryanslade: Is this PR supposed to not be draft? You assigned reviewers so I'm not sure :)

My bad, I want to add a test before opening it up for review

**Comment by ryanslade** [comment]
@tsenart Test added, ready for review now

**Review by tsenart — APPROVED** [review]

**Comment by tsenart** [comment]
I like how we're stripping away repo-updater's server endpoints one by one.

**Pull request merged**
