### PR TITLE
[config]: Reverting External URL Update and Removal of sync.Once

### PR DESCRIPTION
**Pull request by cesrjimenez**
In light of recent failures, this Pull Request reverts the changes made to the external URL in a [previous PR](https://github.com/sourcegraph/sourcegraph/pull/56916), ensuring stability and functionality. This PR is a proactive measure to unblock the system by reverting to a stable state, with a follow-up PR planned to address the reference to the global external URL variable. Additionally, an unnecessary `sync.Once` has been removed, a likely culprit in needing to restart the server when externalURL is updated.

#### Changes:

1. **Reversion of External URL Update**:
   - The external URL has been reverted to its prior state by undoing changes from the previous PR. This change stabilizes the system and unblocks current failures.

2. **Removal of Unnecessary sync.Once**:
   - Removed an extraneous `sync.Once`, streamlining the codebase and removing unneeded synchronization.

#### Next Steps

- **Upcoming PR**: An additional Pull Request will follow that eliminates any reference to the global external URL variable, further refining and improving the codebase.

## Test plan

- Extensive testing has been performed to ensure that the reversion and removal actions do not introduce further issues.
- Automated tests have been updated to reflect these changes, ensuring ongoing stability.

### CODE REVIEW

**Comment by camdencheek** [comment]
Fixes https://github.com/sourcegraph/sourcegraph/issues/57052

**Review by camdencheek — APPROVED** [review]
LGTM, thanks!

**Comment by unknwon** [comment]
@cesrjimenez added backport label assuming you want to backport this PR.

**Comment by cesrjimenez** [comment]
> @cesrjimenez added backport label assuming you want to backport this PR to 5.2.

@unknwon yes please.

**Comment by unknwon** [comment]
Oops 🙈 Why ... @cesrjimenez could you follow the playbook to do the manual backport? 🙏

**Comment by cesrjimenez** [comment]
> Oops 🙈 Why ... @cesrjimenez could you follow the playbook to do the manual backport? 🙏

@unknwon Done ✅ Let me know if anything else is needed ✌️

**Comment by unknwon** [comment]
> > Oops 🙈 Why ... @cesrjimenez could you follow the playbook to do the manual backport? 🙏
> 
> @unknwon Done ✅ Let me know if anything else is needed ✌️

All good, thank you!

**Pull request merged**
