### PR TITLE
db: Add cascading delete on gitserver_repos

### PR DESCRIPTION
**Pull request by ryanslade**

### CODE REVIEW

**Review by tsenart — APPROVED** [review]
If we do delete a repo, but we still have the clone in gitserver for a while, how should that be represented?

**Comment by ryanslade** [comment]
Do we need to represent it anywhere? It'll eventually be removed from gitserver if we ever have disk pressure and it also means that if the repo is added again at some point it'll be quicker to clone since it'll just need to fetch new commits.

Maybe we want to add a cleanup job that removes repos on disk that are no longer in our repo table?

**Comment by tsenart** [comment]
> Maybe we want to add a cleanup job that removes repos on disk that are no longer in our repo table?

Yeah, I think we already have that, but it's very "eventual". 

With my initial comment, I just wanted to make sure that the code in gitserver that writes to the gitserver_repos table won't fail if the associated repo row has been soft deleted.

**Comment by ryanslade** [comment]
> With my initial comment, I just wanted to make sure that the code in gitserver that writes to the gitserver_repos table won't fail if the associated repo row has been soft deleted.

There's a chance that while we're iterating repos to sync their gitserver state a repo may be deleted between us getting it from the db and writing the batch to `gitserver_repos`. In this case that batch will fail but we'll continue syncing the rest. The process will repeat again in 10 minutes and so we'll eventually be consistent. I think that's ok given that we generally don't hard delete repos anyway.

**Pull request merged**
