### PR TITLE
search: remove more unneeded zoekt parameter values

### PR DESCRIPTION
**Pull request by rvantonder**
Stacked on https://github.com/sourcegraph/sourcegraph/pull/24183.

I should've done this all at once but didn't realize I could just look at the values being used by our zoekt search calls and delete the rest _since that was the point of expanding them before_.  Here are the shared ones we need (cool search btw):

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+return+doZoektSearchGlobal%28...%29+and+return+zoektSearch%28...%29&patternType=structural

Screen Shot 2021-08-19 at 8 25 42 PM

But I've been branching off doing other refactors so got a bit distracted. The `ZoektParameters` type is ~basiccally small enough to just propagate the args directly, but I want to simplify some logic first. We can remove the type and have disjoint types for global/non-global.

### CODE REVIEW

**Comment by keegancsmith** [comment]
> Here are the shared ones we need (cool search btw):

I think you want `or` not `and` :P

> The `ZoektParameters` type is ~basiccally small enough to just propagate the args directly

I like using structs to be honest. Using params directly for this stuff has a tendancy to grow and shrink over time and structs are better at that. Also avoids shortcuts people end up taking like passing in `nil` for most call sites when doing a refactor.

**Review by keegancsmith — APPROVED** [review]

**Comment by rvantonder** [comment]
> I think you want or not and :P

would be true, I knew both calls were in the same file though so I was lazy.

> I like using structs to be honest

I appreciate knowing your preference, I don't feel strongly about this convention, so will stick to this where possible! It really is useful for the intermediate exercise of teasing out state dependencies though. The struct method works as long as we fight the tendency to bloat structs with everything. Big objects in and of itself is not the worst IMO--the problem is that sometimes this leads to lax treatment of control flow and separation of concern which are often encapsulated in smaller pieces of state.

**Comment by keegancsmith** [comment]
> The struct method works as long as we fight the tendency to 
> bloat structs with everything.

Agreed. Although I think the main cause of that is having a 
"types" like package which everyone uses. Rather the option/param 
type should live next to the function/constructor/pkg which 
consumes it.

**Review by stefanhengl — APPROVED** [review]

**Comment by rvantonder** [comment]
> Although I think the main cause of that is having a
"types" like package which everyone uses. Rather the option/param
type should live next to the function/constructor/pkg which
consumes it.

Make sense. I'm coming around to separating type definitions based on use, so am OK with things evolving in that direction, after I'm done with `<stuff>`. I admit I'm responsible for minting the `types` package but never really completing the turnaround of what that was meant to accomplish, which I'm finally getting to now. What that was meant to achieve was to capture _all_ the state so we have complete knowledge and then partition to concerns--_before_ I started touching this months (>year?) ago it was a complete free-for-all and it wasn't even possible to know what mattered where at all, there were _no_ real composite types, just args/values being passed wherever, IIRC.

**Pull request merged**
