### PR TITLE
docs: render typedoc documentation for the extension API

### PR DESCRIPTION
**Pull request by ryan-blunden**
This addresses https://github.com/sourcegraph/sourcegraph/issues/739

### CODE REVIEW

**Comment by sqs** [comment]
> Sweet, could we host this on docs.sourcegraph.com ?

https://github.com/sourcegraph/docsite only serves Markdown now, but it could be made to serve static files from an npm package somewhat easily. The easier immediate solution is to use unpkg.com and publish the docs that way, though. (That is what @felixfbecker 	suggested and @ryan-blunden plans to do that.)

**Comment by felixfbecker** [comment]
Is this ready or WIP?

**Comment by ryan-blunden** [comment]
It's ready as far as I'm concerned.

Next step is to publish this along with the npm module.

**Comment by felixfbecker** [comment]
I'm surprised that you had to pass no arguments to `typedoc` at all

**Comment by ryan-blunden** [comment]
This is missing the typedoc.js file. I'll add this tomorrow.

**Comment by ryan-blunden** [comment]
The `typedoc.js` file is added and this is now ready for review.

sourcegraph-extension-api-docs

**Comment by felixfbecker** [comment]
Looks great! Can you make the `"sourcegraph"` root module the entry point (landing page)? I think there is an option for that.

**Comment by ryan-blunden** [comment]
I've got one more thing to fix, don't merge yet.

**Comment by ryan-blunden** [comment]
This is now ready for final review.

**Comment by ryan-blunden** [comment]
See https://unpkg.com/sourcegraph/dist/docs/index.html

**Pull request merged**
