### PR TITLE
fix: add internal flag when running in e2e test mode

### PR DESCRIPTION
**Pull request by dadlerj**

### CODE REVIEW

**Comment by dadlerj** [comment]
@chrismwendt @KattMingMing brought up a good suggestion, any reason these couldn't be configured to run as "dev" instances (`DEPLOY_TYPE=dev`)?

**Comment by chrismwendt** [comment]
`DEPLOY_TYPE=dev` sounds good, too :+1:

**Comment by slimsag** [comment]
Yeah I am in favor of using a `DEPLOY_TYPE` (dev or introducing a new one is fine) instead. The less config points the better.

**Comment by dadlerj** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/pull/2975

**Pull request closed without merging**
