### PR TITLE
search streaming: remove preview from event API

### PR DESCRIPTION
**Pull request by camdencheek**
This PR removes line previews from search result events streamed to the client.

Preview is only used client-side behind a dev-only flag that uses it as an alternative to using the highlighted code. The dev-only flag appears to be pretty broken, so I removed it under the assumption that it's not used. In either case, I don't think a dev-only flag is reason enough to justify sending the match contents every time. 

This PR goes as far as removing references to Preview in client-side code (only used in types, tests and the dev feature), and removing it from the `frontend -> client` API. Further work can be done to remove it from the backend `LineMatch` and all downstream producers of the preview (such as in searcher). This further work will likely be the more valuable, since we currently pay the overhead of serialization for these line matches even when they're never sent to the client because the display limit is hit. 

As a ballpark number on how much difference this makes, for the search `repo:github.com/sourcegraph/sourcegraph$ todo(`, the stream request now transfers 57KB versus the 696KB on `main` for a 91% reduction. 

Progresses #23982

### CODE REVIEW

**Comment by keegancsmith** [comment]
Awesome stuff. One potential downside... does src-cli use it?

**Comment by camdencheek** [comment]
Shoot. I keep forgetting about src-cli. It definitely does use it. Not entirely sure what to do about that at the moment.

**Review by rvantonder — APPROVED** [review]
I don't _think_ `src-cli` is affected. Last I recall, I didn't use `preview` to implement highlighting for structural search, and made it highlight by grabbing the file contents. This was for GQL, I'm not 100% sure about the streaming addition, but it looks like it's using the code I wrote that uses the whole file: https://sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/cmd/src/search_stream.go?L332&subtree=true. Best to double check though...



It is kinda unfortunate that `src-cli` queries the entire file contents. We don't have a way to return plaintext or console highlighting with the `highlight` call in GQL for fragments. And it's unfortunate that even if we did, we still need 2 roundtrips to get the highlighted subset, and it is also not exposed via a streaming endpoint. The same roundtrip/GQL issue exists for our frontend web code. It seems like if we could optionally bundle the output of highlighting + stream it would be optimal, but I suppose right now we can't have it all!

Thoughts on removing`preview` from GQL? Just thinking we should try get rid of all this mostly together.

**Comment by rvantonder** [comment]
I had a look at `src-cli`.[ I see it does use `match.Line` instead of retrieving the file contents](https://sourcegraph.com/github.com/sourcegraph/src-cli@3eb98de8e9ac2276a3e27edd09aaee7c81fbd080/-/blob/cmd/src/search_stream.go?L332&subtree=true), even though it uses the function that I wrote specifically for applying highlights given the entire file contents, and not the preview line. I'm guessing structural search highlighting never worked with the `src-cli` streaming client 😕 

The "easy" way to address this is fetch the file contents and substitute it for the uses of `match.Line`. Maybe serverside rendering + streaming is the better approach. This also made me realize that we still have `diffPreview`, which also has its markdown parts stripped in `src-cli`. It seems a bit counterintuitive to keep `diffPreview` and throw out `preview`, and that we have special functions for this stripping "server-rendered" markdown like triple ticks in diff previews in `src-cli`. 

I'm wondering if the proper solution here ultimately means streaming highlight-rendered "previews" (HTML for frontend, ANSI escape sequences for console, plaintext for general purposes etc., that also allows specifying how many context lines) so we can support our clients and avoid roundtrips. This is a bigger commitment, so maybe we're not ready to remove `preview` just yet (?). I imagine we can optimize things for our web client and continue to feed `preview` to src-cli, but this is the kind of fragmented thing I don't think is worth doing. What do you think?

**Comment by rvantonder** [comment]
OK thinking more about it, it seems to me like streaming-enabled server-side highlighted previews with three output formats (HTML, ANSI, plaintext) would be pretty dang great. We would use the same backend logic that @slimsag implemented to do this for a range over a file (doing the entire file if needed), and with the ability to specify how many context lines to highlight.

**Comment by stefanhengl** [comment]
So funny. I just stumbled upon the same thing while checking how to support the usual -A, -B context flags for src-cli. Server-side highlighted previews sounds way better than letting src-cli retrieve the file contents.

**Comment by camdencheek** [comment]
I like Rijnard's idea. I'll close this in favor of continuing discussion in https://github.com/sourcegraph/sourcegraph/issues/24097

**Pull request closed without merging**
