### PR TITLE
ci: fix buildkite false negative on eslint errors

### PR DESCRIPTION
**Pull request by limitedmage**

### CODE REVIEW

**Comment by limitedmage** [comment]
@pecigonzalo  I managed to fixed the false negative issue but I don't know why the `^^^ +++` isn't being printed so Buildkite autoexpands to the failure. See https://buildkite.com/sourcegraph/sourcegraph/builds/91100#a24a0f9d-3a52-4899-9aef-69675700e34c

**Comment by pecigonzalo** [comment]
@limitedmage It seems to be expanding properly the `client/web: yarn -s run eslint --quiet` section.

**Comment by limitedmage** [comment]
> @limitedmage It seems to be expanding properly the `client/web: yarn -s run eslint --quiet` section.

Oh it does seem to be expanding for me now :)

**Review by efritz — APPROVED** [review]

**Comment by pecigonzalo** [comment]
🎉

**Pull request merged**
