### PR TITLE
app: improve bundling of app-shell code

### PR DESCRIPTION
**Pull request by burmudar**
the sourcegraph backend already has the Sourcegraph client web embedded so we just need to get the app-shell transpiled and ready for tauri-shell. The app-shell is also just a bridge between the tauri application and the sourcegraph backend thus there isn't much js code right now

## Test plan
`pnpm tauri build` and see the app is loaded properly

### CODE REVIEW

**Comment by chwarwick** [comment]
I pulled this branch to try it out and when I ran `pnpm tauri build` from the root of the sourcegraph project I got: 
```
pnpm tauri build
     Running beforeBuildCommand `./src-tauri/compose-assets.sh`
+ rm -rf assets/
+ mkdir -p assets
+ cp -r '../client/app-shell/dist/*' assets/
cp: ../client/app-shell/dist/*: No such file or directory
       Error beforeBuildCommand `./src-tauri/compose-assets.sh` failed with exit code 1
```

**Comment by burmudar** [comment]
> I pulled this branch to try it out and when I ran `pnpm tauri build` from the root of the sourcegraph project I got:
> 
> ```
> pnpm tauri build
>      Running beforeBuildCommand `./src-tauri/compose-assets.sh`
> + rm -rf assets/
> + mkdir -p assets
> + cp -r '../client/app-shell/dist/*' assets/
> cp: ../client/app-shell/dist/*: No such file or directory
>        Error beforeBuildCommand `./src-tauri/compose-assets.sh` failed with exit code 1
> ```
Ah I forgot a part there - lemme fix it quickly

**Comment by chwarwick** [comment]
> @chwarwick should be better now!

new one 

```
     Running beforeBuildCommand `./src-tauri/compose-assets.sh`
+ rm -rf assets/
+ mkdir -p assets
+ cd ..
+ pnpm build
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: build
spawn build ENOENT
+ cp -r '../client/app-shell/dist/*' assets/
cp: directory assets does not exist
       Error beforeBuildCommand `./src-tauri/compose-assets.sh` failed with exit code 1
```

**Comment by burmudar** [comment]
> > @chwarwick should be better now!
> 
> new one
> 
> ```
>      Running beforeBuildCommand `./src-tauri/compose-assets.sh`
> + rm -rf assets/
> + mkdir -p assets
> + cd ..
> + pnpm build
>  ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: build
> spawn build ENOENT
> + cp -r '../client/app-shell/dist/*' assets/
> cp: directory assets does not exist
>        Error beforeBuildCommand `./src-tauri/compose-assets.sh` failed with exit code 1
> ```

Ok I actually tested it now ... it _should_ be fixed now

**Review by chwarwick — APPROVED** [review]

**Pull request merged**
