### PR TITLE
Better import ordering with prettier

### PR DESCRIPTION
**Pull request by umpox**
## Description

Uses [@ianvs/prettier-plugin-sort-imports](https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports) for import ordering instead of eslint.

Much quicker, can be done automatically on save without any significant delay.

## Test plan

Tested through the diff :) 

## App preview:

- [Web](https://sg-web-tr-use-prettier-for-import-order.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by philipp-spiess — APPROVED** [review]
omg yes please

**Comment by philipp-spiess** [comment]
This should probably be added here when it's done though: https://github.com/trivago/prettier-plugin-sort-imports unless we [move the whole config into the monorepo](https://sourcegraph.slack.com/archives/C01C3NCGD40/p1677237103848509)

Otherwise we end up with two places where rules are defined and it'll get messy (we already have this situation for eslint 😰)

**Review by valerybugakov — APPROVED** [review]
@umpox, let do this!

**Review by eseliger — APPROVED** [review]
this will change my life

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.15 kb) | -0.00% (-0.15 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/tr/use-prettier-for-import-order-diff/compare-report.html;tab=live_object) for a full comparison between the commits 9dc6534 and f02011d or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by limitedmage — APPROVED** [review]
THANK YOU!!!!

**Review by vdavid — APPROVED** [review]
Nice!

**Comment by umpox** [comment]
@philipp-spiess Agree re: moving to the main config. Have merged this and going to let it settle in to check there's no unexpected issues. We can then move to the main config and update all the other repos if all good! (just a bit time consuming)

**Pull request merged**
