### PR TITLE
refactor: extract codeintellify as new package

### PR DESCRIPTION
**Pull request by gitstart-sourcegraph**
## Description

Let's extract the codeintellify package because it doesn't have external dependencies.

## Ref
[SourceGraph issue](https://github.com/sourcegraph/sourcegraph/issues/28965)
[GitStart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-28965)

### CODE REVIEW

**Comment by chrismwendt** [comment]
CleanShot 2022-01-03 at 18 11 11@2x

CleanShot 2022-01-03 at 18 11 46@2x

Did you forget to delete the old code?

**Comment by gitstart-sourcegraph** [comment]
@chrismwendt Thank you. we forgot to the last steps 😄 Pushed updates for it, could you please take a look

**Review by chrismwendt — APPROVED** [review]
I verified defs/refs/hovers/impls still work ✅

**Review by valerybugakov — APPROVED** [review]
Thanks!

**Pull request merged**
