### PR TITLE
Increase max-age of assets to 1 year

### PR DESCRIPTION
**Pull request by heyajulia**
This commit increases the max-age of assets to 31536000 seconds (one year) to improve loading times.

Fixes sourcegraph/sourcegraph#34433.

## Test plan

Before switching the branch with my change, run Sourcegraph and send a request to, for example, http://sourcegraph.test:3080/.assets/img/sourcegraph-mark.svg?v=2:

```
$ curl -I "http://sourcegraph.test:3080/.assets/img/sourcegraph-mark.svg?v=2"
HTTP/1.1 405 Method Not Allowed
X-Powered-By: Express
allow: GET
cache-control: immutable, max-age=172800, public
content-length: 45
content-type: text/plain; charset=utf-8
date: Thu, 19 May 2022 14:03:39 GMT
server: Caddy
x-content-type-options: nosniff
connection: close
Vary: Accept-Encoding
```

Note that the `max-age` is 172800, as expected.

But when we run Sourcegraph using the code from my branch:

```
$ curl -I "http://sourcegraph.test:3080/.assets/img/sourcegraph-mark.svg?v=2"
HTTP/1.1 405 Method Not Allowed
X-Powered-By: Express
allow: GET
cache-control: immutable, max-age=31536000, public
content-length: 45
content-type: text/plain; charset=utf-8
date: Thu, 19 May 2022 14:06:14 GMT
server: Caddy
x-content-type-options: nosniff
connection: close
Vary: Accept-Encoding
```

Now, the `max-age` is 31536000, as expected.

### CODE REVIEW

**Comment by heyajulia** [comment]
Hey @sourcegraph/contribution-reviewers, I signed the CLA! :)

**Comment by heyajulia** [comment]
I'm asking for a review from @beyang because they last touched that line of code (in https://github.com/sourcegraph/sourcegraph/commit/757f273a60d1f2510e31a5871efafd38ef56fd93), and a review from @nihaals because they opened the corresponding issue. (I hope I'm doing this right!)

**Review by nihaals — APPROVED** [review]

**Comment by jdorfman** [comment]
@heyajulia thanks for the contribution! I will work on getting this merged asap.

**Comment by heyajulia** [comment]
Yay, thanks! 🎉

Sorry about the merge commit, by the way. I didn't know "Fetch upstream" would also update this pull request. I hope there's still a way to clean it up. (I also think I lost the approving review? 😨)

**Comment by jdorfman** [comment]
@cla-bot check

**Comment by jdorfman** [comment]
Adding @beyang to code review since he made the last one


[Beyang Liu, 3 years ago: • increase max-age of bundle.js](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/757f273a60d1f2510e31a5871efafd38ef56fd93)

**Review by jasongornall — APPROVED** [review]

**Comment by davejrt** [comment]
@cla-bot check

**Comment by oleggromov** [comment]
@filiphaftek please have a look - will Cloudflare pick up the changes automatically, or do we have any overrides there?

**Comment by oleggromov** [comment]
From my point of view, for instances that don't/won't have edge caching in front of them, looks good. Anyways we "freeze" assets by fingerprinting them. Should be fine.

**Comment by jdorfman** [comment]
@filiphaftek whatcha think?

**Comment by daxmc99** [comment]
I’m not the most experienced frontend developer but isn’t one year a bit excessive? If we ever improperly cache some asset then it will be stuck for one year. We have had serious cache issues in the past which have only been temporary problems (thankfully) due to cache age of 2 days.

**Comment by nihaals** [comment]
> I’m not the most experienced frontend developer but isn’t one year a bit excessive?

I used 1 year in #34433 as it's the maximum value and essentially considered "forever" in terms of caching, which implies you're cache busting. I checked all the static assets and every one I saw either used the hash in the file name or `?v=`, so every asset should be fine.

> If we ever improperly cache some asset then it will be stuck for one year. We have had serious cache issues in the past which have only been temporary problems (thankfully) due to cache age of 2 days. 

Is there any public documentation on these issues? If these issues occurred after cache busting was added then this could cause issues, but as I said, everything seems to be implemented correctly, so I'm surprised Sourcegraph had any caching issues. If I remember correctly, the only asset I saw which didn't use the hash in the file name is the logo SVG, which uses `?v=`, which I assume is manually bumped with an update, and if it is correctly bumped then should also be safe.

If there *has* been consistent issues, then maybe `immutable` should be removed, as it implies that the assets will not change while the path stays the same ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#immutable)).

**Comment by jdorfman** [comment]
> This should be fully fixed now but this is what makes me cautious about this.

@daxmc99 do think this PR is redundant? 

Either way, we owe @heyajulia a status update. =)

**Review by daxmc99 — APPROVED** [review]

**Comment by daxmc99** [comment]
@heyajulia is this good to merge?

**Comment by heyajulia** [comment]
Looks good! 👍🏻

**Comment by jdorfman** [comment]
@daxmc99 let's :shipit:

**Pull request merged**
