### PR TITLE
JetBrains: Force the popup into persistent mode and manually detect clicks into the main IDE window

### LINKED ISSUE #34969: JetBrains: Leave popup open when focus leaves the IDE
## Context

Currently, when the "Find on Sourcegraph" popup is open and one focuses away from the IDE with Cmd+Tab on a Mac, the popup disappears.
The "Find in Files" native popup remains open on Cmd+Tab.

## Problem

This behavior somehow makes the popup feel awkward and unusual for the IDE.
This is something that I (David) as a long-time JetBrains user notice a lot and has a strong negative impact on my experience.

## Solution

Keep the popup open until the user closes it with Esc, Alt+Enter, or clicking away from it inside the IDE.

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #34969

Note: @madppiper and me have been looking into [#34969](https://github.com/sourcegraph/sourcegraph/issues/34969)  today. This PR is a potential workaround (I wanted to persist this idea until after the long weekend). This is not intended to be merged like this. 

We noticed that the default JBPopup implementation has a "persisted" mode which, when enabled, uses a different implementation for the popup. One that is intended to stay active for longer.

In this PR we create a popup with this mode so that there is no automatic handling for deactivating the popup enabled at all (hats off to @madppiper for discovering this).

With this behavior, we need to manually add the triggers for hiding the popover. We have already done this for `esc` and there is currently only one second closing method that we want: Closing when the IDE window behind the popup is clicked. 

I've taken a very stupid and hacky attempt at doing this in this PR. It's a hack built on top of another hack and is likely causing more headache in the long-run, but it also unblocks the problem to some extend 🙈 .

I also already discovered an issue with this method: When the focus inside the project jumps to _another_ popover (e.g. when you open find everywhere), we don't have a focus event on the main window and our modal stays open. We probably instead want to add a focus handler for every window in the project (if this is possible somehow?) and detect if anything outside our popup is focused. 

## Test plan

Manual testing including jumping to other JetBrains project and non JetBrains applications:

https://user-images.githubusercontent.com/458591/172340419-9c927aa1-1b40-48b8-890b-7ef281baf428.mov

## App preview:

- [Web](https://sg-web-ps-jetbrains-manual-close-window.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-oznpgsfmrg.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by vdavid** [comment]
Nice, yeah, I was thinking about something of this sort, but my concern was exactly that I wasn't sure how to grab _any_ focus change inside the IDE, including other popups. I hope we can make this work, it could be a solution that works well (despite being hacky).

**Comment by philipp-spiess** [comment]
> Nice, yeah, I was thinking about something of this sort, but my concern was exactly that I wasn't sure how to grab _any_ focus change inside the IDE, including other popups.

Yeah, I’m like 80% sure that there _is_ a way to do that. Unfortunately listening for unfocused events of the popover alone isn't it. Either we can listen on _any_ focus inside _any_ of the swing components and check if they are part of the current's project window or we hook into the WINDOW_OPENEND and WINDOW_CLOSING `WindowEvent`s. 

I'll give this an hour or so to try but I didn't want to spend too much time on this just yet so if you want to do that, feel free to take over 🙂

**Comment by philipp-spiess** [comment]
Seems to work this way 🙂   

https://user-images.githubusercontent.com/458591/172340419-9c927aa1-1b40-48b8-890b-7ef281baf428.mov

**Review by vdavid — APPROVED** [review]
The code LGTM, plus I've tested it and it feels perfect!

**Comment by madppiper** [comment]
Just as a quick note: 

I still stand by the original statement that we should revisit the browser integration and see that we can fix the keyboard events not being passed properly in mac/unix and potential rendering issues. Once that is fixed we can use OSR and revert many changes such as this. The solution there, involves overriding all of the CEFBrowser and wrappers, so it will be time consuming to do.

For the time being this seems like a workable solution however, so happy for this to be used.

**Comment by philipp-spiess** [comment]
> I still stand by the original statement that we should revisit the browser integration and see that we can fix the keyboard events not being passed properly in mac/unix and potential rendering issues.

We should probably also make sure that JetBrains is aware of all the workarounds that are necessary from our side just because of this bug.

💯 % agree with the rest. This works okay-ish enough for now so that we should be able to get quality feedback from JetBrains users (which is our highest priority for the first release here)

**Comment by madppiper** [comment]
> > I still stand by the original statement that we should revisit the browser integration and see that we can fix the keyboard events not being passed properly in mac/unix and potential rendering issues.
> 
> We should probably also make sure that JetBrains is aware of all the workarounds that are necessary from our side just because of this bug.
> 
> 💯 % agree with the rest. This works okay-ish enough for now so that we should be able to get quality feedback from JetBrains users (which is our highest priority for the first release here)

I'll reach out to the devs in the private chat...

**Comment by vdavid** [comment]
> I'll reach out to the devs in the private chat...

Thanks!
If that means the JetBrains Platform Slack, feel free to mention me, I'm @David Veszelovszki

**Pull request merged**
