### PR TITLE
Svelte: Font size tweaks for results indicator

### PR DESCRIPTION
**Pull request by taiyab**
Follow up to https://github.com/sourcegraph/sourcegraph/pull/62317

## Test plan
Locally tested for visual changes.

### CODE REVIEW

**Review by camdencheek — CHANGES_REQUESTED** [review]
Something about this change caused the button to change size vertically between the loaded and completed states

https://github.com/sourcegraph/sourcegraph/assets/12631702/d8d23766-6288-4617-813d-68fb83ff8e2b

**Comment by taiyab** [comment]
@camdencheek Should be sorted now.

**Comment by camdencheek** [comment]
Looks like there is still a shift when `TimeoutMessage` is shown because we would need to keep the padding in sync between all three things. 

Instead of having to keep the padding in sync between these three different spots, I think it would be better to just [increase the `row-gap`](https://github.com/sourcegraph/sourcegraph/pull/62352) in the flexbox. I made that PR against this branch so you can merge it in if it looks good to you

screenshot-2024-05-01_14-16-29@2x

**Comment by taiyab** [comment]
Merged in your changes.

**Review by camdencheek — APPROVED** [review]

**Pull request merged**
