### PR TITLE
nix: format shell.nix

### PR DESCRIPTION
**Pull request by keegancsmith**
I don't know which formatter this is running, but it is what happens when I run M-x nix-format-buffer in emacs.

Test Plan: nix develop

### CODE REVIEW

**Comment by Strum355** [comment]
This seems to be using [nixfmt](https://github.com/serokell/nixfmt) instead of [nixpkgs-fmt](https://github.com/nix-community/nixpkgs-fmt). Do you have any particular preference in the output? I lean towards nixpkgs-fmt personally (the line breaks feel a bit awkward imo)

We could add a formatter thatd be invoked consistently by [`nix fmt`](https://sourcegraph.com/github.com/NixOS/nix/-/blob/src/nix/fmt.md) that I just discovered

**Comment by Strum355** [comment]
Huh its still different, even though rnix-lsp supposedly runs nixpkgs-fmt :thinking: im gonna have to look into that

**Comment by keegancsmith** [comment]
Maybe I am using a different version of nixpkgs-fmt? `nixpkgs-fmt 1.3.0`

**Comment by Strum355** [comment]
Yup, [looks like rnix-lsp is still on 1.2.0](https://github.com/nix-community/rnix-lsp/issues/100). I agree with lilyball that I prefer the output from 1.2.0, but alas :sweat_smile:

**Comment by Strum355** [comment]
Assuming all nix files are formatted with nixpkgs-fmt 1.3.0, then Im cool with merging this. I can sort out lsp using the wrong formatter on my own end

**Comment by keegancsmith** [comment]
@Strum355 I under-engineered supporting nix fmt. Approve? :)

**Comment by Strum355** [comment]
> @Strum355 I under-engineered supporting nix fmt. Approve? :)

Already ahead of you :smugcat: https://github.com/sourcegraph/sourcegraph/pull/51409

**Pull request closed without merging**
