### PR TITLE
App Prototype: Add "Connect to Sourcegraph.com" prototype

### PR DESCRIPTION
**Pull request by philipp-spiess**
Part of #47998

This uses #49107 to add a new "Connect to Sourcegraph.com" workflow to App. When no access token is set in the site config, an option to "Connect to Sourcegraph.com" is rendered in the menu dropdown. When clicked, the user is redirected to dotcom where an auth token is created and the user is directed back to App.

To check if a user is signed-in, I added a new GraphQL endpoint so that we can, in the future, make sure the token is valid by sending a POST to `https://sourcegraph.com/.api/graphql` to validate the token.

The redirect screen handles invalid `code` parameters in the URL and uses a full page reload after the token is written to the site config to avoid any stale cache issues (since this is localhost only, it's very fast anyways).

## Test plan

https://user-images.githubusercontent.com/458591/225983059-4e2830b3-a332-4ec1-b9e4-88e376330561.mov

(My local devserver runs on a different port than App so there's an awkward manual URL replacement happening)

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.05% (+1.44 kb) | 0.06% (+9.18 kb) | 0.07% (+7.74 kb) | 0.27% (+2) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/app-sign-in-via-dotcom/compare-report.html;tab=live_object) for a full comparison between the commits cdfaa77 and 9b8ad1c or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by slimsag — APPROVED** [review]
This looks fantastic.

**Comment by slimsag** [comment]
@philipp-spiess Given that this is just an option hidden under the navbar, I would actually encourage us to merge this. I don't see a ton of harm in _having that option there_, even if for right this very moment it provides no benefit. Alternatively, we could further hide it (e.g. merge it but don't link in the navbar so you must manually navigate to it)

I think it'd be beneficial for others (Taylor etc.) to be able to experience this UX flow, and that'd let us start iterating on deciding how we want to feature this more prominently and what feature will be gated behind this.

**Comment by philipp-spiess** [comment]
> Alternatively, we could further hide it (e.g. merge it but don't link in the navbar so you must manually navigate to it)

I'd prefer this. I think it's really confusing at the moment since you get no more reference to this feature once you do link the account other than the button no longer showing up.

I can put the nav bar item behind an additional feature flag.

**Pull request merged**
