### PR TITLE
search-blitz: gigarepo literal queries uniq names

### PR DESCRIPTION
**Pull request by keegancsmith**
Oops, I broke CI.

Test Plan: go test

### CODE REVIEW

**Review by stefanhengl — APPROVED** [review]

**Review by vrto — APPROVED** [review]
Nice 👍

**Comment by keegancsmith** [comment]
Ok I found the issue. Our CI doesn't detect it needs to run go tests because I only modified data that is input to go test, not any go files. I'll see how easy this is to rectify.

**Comment by keegancsmith** [comment]
Here is a proposed change to CI to prevent this from happening in the future https://github.com/sourcegraph/sourcegraph/pull/33581

**Comment by keegancsmith** [comment]
I just force merged this since only cla bot failed, but CI was happy.

**Pull request merged**
