### PR TITLE
[language-platform] Adding to the redis API

### PR DESCRIPTION
**Pull request by Numbers88s**
Added this additional methods as we are using them for the Rank work we are doing in codeintel

## Test plan
Added unit test plus manual testing

more

### CODE REVIEW

**Review by keegancsmith — COMMENTED** [review]
is redis the appropriate place to store this data? For "cache" the ranking data will be volatile. For "store" we don't expect the values to be huge, store is meant to be relatively small and just store things like session data. I would expect this stuff to live in postgres?

**Comment by Numbers88s** [comment]
> is redis the appropriate place to store this data? For "cache" the ranking data will be volatile. For "store" we don't expect the values to be huge, store is meant to be relatively small and just store things like session data. I would expect this stuff to live in postgres?

Yup, I agree. This is for the demo for Merge. There are plans to migrate to postgres post merge. However I need a brief moment where I store all the definitions and references briefly which will be store for a couple hours  before redoing the whole thing again.

**Comment by keegancsmith** [comment]
I need to add more documentation, sorry. But unless you intend on using this in the sourcegraph app (ie single binary), you don't need to expand this interface. Rather use the `Pool()` function to get at redis. All the methods that are currently in the interface are needed to support sourcegraph in single binary.

**Comment by Numbers88s** [comment]
> 

You don't see value in adding this functionality to the internal/redispool? You have a nice little API here just adding to it.

**Comment by keegancsmith** [comment]
I'm about to land a PR which makes this API work on postgres and redis. Expanding the surface makes that a bit more diffiicult.

I think a nice approach is rather than getting a huge struct/interface, do something like `FIFOList` where it can take in a redis but provide a well typed API. I like KeyValue, but I don't like how big it is. Mainly done to get something done sooner, my plan was to try and break it up afterwards to see if things are still nice.

**Comment by Numbers88s** [comment]
> 

That's a bummer man. I wish we could share these legos. It's a nice API and I don't see the length as a problem since its well paired up with the Redis documentation. Makes it real easy to jump in add to it and test. It's bear bones but it has niceties like `Value` and `Values`, the loop to check for type and cast it appropriately. It's nice. I would have to redo all that functionality that is just sitting there. I would ask you to consider using `KeyValue` in your new API that takes in a redis or postgres just cause I think you have something good here. Regardless, of course it's up to you. I'll figure something out for myself and good luck with Sourcegraph App ✌️

**Pull request closed without merging**
