### PR TITLE
become handbook-first: move non-technical docs to about repository

### PR DESCRIPTION
**Pull request by sqs**
As part of our goal to become [handbook-first](https://about.gitlab.com/handbook/handbook-usage/#why-handbook-first), this deletes Markdown documents that are not related to the code or product. These are being moved to the https://github.com/sourcegraph/about repository. Keeping all company, handbook, and process documentation in that repository makes it easier for everyone to contribute to and allows us to render information more nicely on about.sourcegraph.com (e.g., to have our product roadmap render as something other than just Markdown-rendered HTML).

cc @nicksnyder @christinaforney @dadlerj (for awareness)

Related: https://github.com/sourcegraph/about/pull/300

### CODE REVIEW

**Comment by dadlerj** [comment]
@sqs did you see https://github.com/sourcegraph/sourcegraph/pull/6301 and the discussion around it in Slack? Sorry for not pinging you earlier. If you prefer moving docs out of our sourcegraph repo docs, I can take this over.

**Comment by sqs** [comment]
@dadlerj Ah, I saw it briefly but didn't pay enough attention to it. I think we should separate docs as described in https://github.com/sourcegraph/about/pull/300. But you should just merge that #6301 PR first and then I will move them out because I have an idea of the structure I want for the handbook.

**Comment by nicksnyder** [comment]
I like the idea of using sourcegraph/about. Decoupling this doc from our product doc makes sense, and I do think we want to have a "pretty" version of our handbook docs beyond just markdown.

Please remove stale references from CODEOWNERS.

**Comment by nicksnyder** [comment]
- [ ] Also please update our job descriptions with updated links

**Comment by sqs** [comment]
@nicksnyder:

- CODEOWNERS updated
- careers repo updated in https://github.com/sourcegraph/careers/pull/55

**Pull request merged**
