### PR TITLE
JetBrains: set 'codemirror6' as monaco query input editor component

### PR DESCRIPTION
**Pull request by taras-yemets**
Closes https://github.com/sourcegraph/sourcegraph/issues/37722

Sets 'codemirror6' as editor component for the monaco query input.
By default ([settings](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=HEAD&file=doc%2Fadmin%2Fconfig%2Fsettings.schema.json&editor=VSCode&version=2.2.4&start_row=305&start_col=30&end_row=305&end_col=30&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands), [usages](https://sourcegraph.com/search?q=context:global+repo:sourcegraph/sourcegraph+%3F%3F+%27monaco%27&patternType=literal)) `monaco` is the editor component used in [`LazyMonacoQueryInput` component](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=HEAD&file=client%2Fsearch-ui%2Fsrc%2Finput%2FLazyMonacoQueryInput.tsx&editor=VSCode&version=2.2.4&start_row=61&start_col=3&end_row=61&end_col=3&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands).

Although, mouse selection works well for both editor components on sourcegraph.com, for yet unknow reason `monaco` editor component doesn't allow mouse selection while `codemirror6` allows.
This PR suggests to ignore `editor` experimental feature value until we figure out why `monaco` editor component doesn't wotk for the JetBRains plugin.

[Loom](https://www.loom.com/share/0d0b8aeae4fb477f8de4b7fad78c5297)

## Test plan
Run JetBrains plugin in standalone mode and ensure that query input can be selected both with keyboard and mouse/touchpad.

## App preview:

- [Web](https://sg-web-taras-yemets-jetbrains-fix-search.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ezisbwufui.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by philipp-spiess — COMMENTED** [review]
This is great! We need to test one thing though. For the arrow up/down navigation while the editor is selected, we have a very specific logic that is tied to the codemirror implementation. Can you verify that this still works and fix if needed?

I’m referring to this: https://github.com/sourcegraph/sourcegraph/blob/main/client/jetbrains/webview/src/search/results/SearchResultList.tsx#L82-L97

To test, search for something and use the arrow up/down key

**Comment by taras-yemets** [comment]
Very helpful comment, @philipp-spiess! Thank you!

To remove the leftovers after the editor component change I made the following changes:
- updated selectors in the key down handler (https://github.com/sourcegraph/sourcegraph/pull/37742/commits/a86c9995dc5801eda502d1b64661de1868601fb1)
- reverted https://github.com/sourcegraph/sourcegraph/pull/37336 (https://github.com/sourcegraph/sourcegraph/pull/37742/commits/a2a66c18171336582aab572617c991ff0ec678a8)
- removed other Monaco editor-specific styling (https://github.com/sourcegraph/sourcegraph/pull/37742/commits/b58ff2c2e0a7f5867c2d64cb112eb584072962a2)

It looks like the key down handler looks as expected, but given that the editor component change may trigger other unexpected regressions I would highly appreciate it if you try these changes on your own.

**Comment by philipp-spiess** [comment]
@taras-yemets Nice! The changes seem to work great. One thing I noticed (not sure if this is expected or not) but it seems to me as if there are some icons not loading in the dropdown. Is this expected to look like that? Also the dropdown font size seems to be small (not sure if this is just my perception though).

Screenshot 2022-06-27 at 14 08 15

**Comment by taras-yemets** [comment]
@philipp-spiess, for some reason I'm getting the other results 🤔 

Screenshot 2022-06-27 at 15 28 36
Screenshot 2022-06-27 at 15 27 29


> some icons not loading in the dropdown

All the autocompletion variants I tried (including the one on your screenshot) were with icons.

> dropdown font size seems to be small

Just checked: JetBrains plugin and sourcegraph.com both have 14px autocompletion items font size.

**Comment by taras-yemets** [comment]
Updated description with a Loom. 
cc: @philipp-spiess

**Comment by taras-yemets** [comment]
> In the dark mode, the icons don't change their color

@philipp-spiess, nice catch! It looks like a common issue for the `codemirror6` editor component. See screenshot from sourcegraph.com 👇🏻 
Screenshot 2022-06-27 at 15 55 55

Looking into possible ways to fix it now.

**Comment by philipp-spiess** [comment]
Ooh gotcha I think this is fine to fix as a follow up then (but we should still fix it 😅)

**Pull request merged**
