### PR TITLE
Add note for Postgres min req upgrade

### PR DESCRIPTION
**Pull request by macraig**

### CODE REVIEW

**Review by efritz — APPROVED** [review]
Can we put this notice in the upgrade docs as well?

**Comment by efritz** [comment]
https://docs.sourcegraph.com/admin/updates/docker_compose (and for pure docker, k8s).

**Comment by macraig** [comment]
@davejrt are the upgrade docs something you usually update right before the release? Do you want me to open a PR with the notice on those docs or would you rather add it when releasing?

**Comment by davejrt** [comment]
LGTM

**Pull request merged**
