### PR TITLE
Simplify ViewResolver type

### PR DESCRIPTION
**Pull request by lguychard**
A `ViewResolver` is now simply a function that takes a container as input and returns `Iterable<View>`, instead of being defined with a selector and a `resolveView()` function.

### CODE REVIEW

**Comment by lguychard** [comment]
When we wrote `trackViews()`, we opted not to run the resolvers on removed nodes, to guard against cases where resolution depends on state outside the code view, and the needed state would be inaccessible because the node has been removed from the tree. It wasn't a bug we actually encountered, merely something that was raised during code review, and then accounted for, but it is definitely possible. The result would have been leaked code views. Reference: https://github.com/sourcegraph/sourcegraph/pull/2909#discussion_r268204729

The issue you raised in https://github.com/sourcegraph/sourcegraph/pull/3920#discussion_r282926627 is a different bug, that leads to systematically leaked code views: if the resolver returns a different element than the selector, the code view will be leaked when removed from the DOM, because the resolver is not run on removed nodes.

This PR does reintroduce the first bug, in order to fix the second.

I do think that looking at the context of an element initially matched with a selector in order to return the correct code view element is a valid use case. On github.com, for instance, we can't come up with an unambiguous enough selector to match the whole code view on blob views ([example](https://sourcegraph.com/gitlab.com/rluna-open-source/code-management/sourcegraph/sourcegraph/-/blob/browser/src/libs/github/code_intelligence.ts#L162-177)), and the issue was the same for snippets.

One way to keep this possible while avoiding both bugs would be to simply check whether removed nodes are tracked views, or contain tracked views within their subtree (without running selectors or resolvers on removed nodes).

**Comment by felixfbecker** [comment]
That would be less performant though because we would have to iterate over all registered code views instead of doing a O(1) Map lookup.

Anything that speaks against my suggestion?

**Comment by lguychard** [comment]
Your suggestion is still potentially vulnerable to https://github.com/sourcegraph/sourcegraph/pull/2909#discussion_r268204729 if `findElements()` does something akin to [this code](https://sourcegraph.com/gitlab.com/rluna-open-source/code-management/sourcegraph/sourcegraph/-/blob/browser/src/libs/github/code_intelligence.ts#L162-177), isn't it?

**Comment by felixfbecker** [comment]
Hmm yeah I think you're right. Sounds like we need to iterate.

**Comment by felixfbecker** [comment]
FYI I think that refactor would conflict with native diff views

**Comment by felixfbecker** [comment]
Do you want to get this in for 3.5?

**Comment by lguychard** [comment]
If time, but it's really not the most critical thing now that #4371 is merged. I'll move this to the backlog milestone to reflect this, and rebase when I get the chance.

**Comment by slimsag** [comment]
This PR has been open for a very long time with no progress, closing. Reopen if desired.

**Pull request closed without merging**
