### PR TITLE
web: do not classify 404 as an error in StatusCode component.

### PR DESCRIPTION
**Pull request by sashaostrikov**
Test plan:
Storybook.

## App preview:

- [Web](https://sg-web-ao-ui-webhooks-404-is-new-ok.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.02 kb) | 0.00% (+0.02 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ao/ui/webhooks/404-is-new-ok/compare-report.html;tab=live_object) for a full comparison between the commits 8579ed7 and df8fe89 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Comment by sashaostrikov** [comment]
> Hmmmm this won't work for the `webhookLog` graphql queries where specify something like `onlyErrors: true` so the headers at the top will show an error count but then you won't be able to find it.
> 
> Similarly, if you were to eventually be able to filter by Only Errors, this would still return 404s but then have them not marked as errors in the UI

ah, that makes sense, let me rethink it

**Review by mrnugget — APPROVED** [review]

**Comment by mrnugget** [comment]
> Hmmmm this won't work for the `webhookLog` graphql queries where specify something like `onlyErrors: true` so the headers at the top will show an error count but then you won't be able to find it.

Does that mean we need a backend solution? I think so, right?

**Comment by sashaostrikov** [comment]
> Does that mean we need a backend solution? I think so, right?

actually a fullstack solution 😎 (I'm on it, will push shortly)

**Review by mrnugget — APPROVED** [review]
Sweet!

**Comment by sashaostrikov** [comment]
This is no longer needed in favor of new webhooks error handling. Details: https://sourcegraph.slack.com/archives/C03K05FCRFH/p1670562935303159?thread_ts=1670489194.319089&cid=C03K05FCRFH

**Pull request closed without merging**
