### PR TITLE
gitlab: Return 500 from OAuth handler

### PR DESCRIPTION
**Pull request by ryanslade**
This allows us to pick up the error in our sentry handler so that we get
some observability.

### CODE REVIEW

**Comment by ryanslade** [comment]
@unknwon I'm not sure about this approach. I almost just added an explicit `sentry.CaptureError` after `validateResponse` but at least with this approach we'll capture any error.

Assuming this actually gets picked up by Sentry, I'm not 100% sure how to test the flow.

**Review by arussellsaw — APPROVED** [review]

**Comment by unknwon** [comment]
> @unknwon I'm not sure about this approach. I almost just added an explicit `sentry.CaptureError` after `validateResponse` but at least with this approach we'll capture any error.
> 
> Assuming this actually gets picked up by Sentry, I'm not 100% sure how to test the flow.

Hmm... I almost certain `sentry.CaptureError` won't be picked up by this PR because we currently (unfortunately) only send 500 errors to Sentry for GraphQL requests. We need to (again sadly) explicitly call `sentry.CaptureError` here to make it be sent to Sentry. I'll share on Slack about to test it on local dev.

**Comment by ryanslade** [comment]
@unknwon Are you sure, it looks like `httptrace` is included on all our handlers and it included sentry logging:
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+tracepkg.HTTPTraceMiddleware%28h%29&patternType=literal

**Comment by unknwon** [comment]
Let's test it to be sure then: https://sourcegraph.slack.com/archives/CHPC7UX16/p1618393300295700

**Comment by ryanslade** [comment]
I can't seem to get GitLab OAuth to work locally, keep getting this error: 

Screenshot 2021-04-14 at 16 12 51

From what I can tell, this is the redirect URL: `https://sourcegraph.test:3443/.auth/gitlab/callback`

**Comment by unknwon** [comment]
> I can't seem to get GitLab OAuth to work locally, keep getting this error:
> 
> Screenshot 2021-04-14 at 16 12 51
> 
> From what I can tell, this is the redirect URL: `https://sourcegraph.test:3443/.auth/gitlab/callback`

Oh... for local GitLab.com OAuth, I set redirect url to be actually http://localhost:3080 🤦

**Comment by ryanslade** [comment]
I'm closing this as it doesn't do what we want.

We'll need to add something at a different layer to make this work as the oauth handlers are injected in [here](https://github.com/sourcegraph/sourcegraph/blob/108a15da31fff5ba2153138eac3c226ebf1e81ce/enterprise/cmd/frontend/internal/auth/oauth/middleware.go#L26) and so don't use the rest of our tracing infrastructure.

We'll need a better solution for this but I don't feel it's high enough priority to work on right now.

**Pull request closed without merging**
