### PR TITLE
Docs improvements to the main Cody page

### PR DESCRIPTION
**Pull request by MaedahBatool**
This PR ships improvement to the main Cody docs overview page with the following revamped changes:

- Improvements to the page information architecture
- Placement of callouts buttons and user-driven actions
- Simplify brand tone and overall grammar, vocab
- Remove fluff and inconsistent content structures

## Preview Link

- [View here →](https://docs.sourcegraph.com/@cody-docs-pr1/cody)

## Screencast

https://sourcegraph.slack.com/files/U05EH1A6Y3F/F05JWJ0D75Z/sg.mp4

## Test plan

- Check links

### CODE REVIEW

**Review by camdencheek — COMMENTED** [review]
I know we have a few committed already, but we should avoid committing more images to the repo because those will inflate the repo size forever and ever. 

I've uploaded the images to our `sourcegraph-assets` cloud storage bucket (I can show you how to do that if you'd like), and they can be found at these URLS:
- https://storage.googleapis.com/sourcegraph-assets/docs/images/cody/cody-logomark-default.svg
- https://storage.googleapis.com/sourcegraph-assets/docs/images/cody/enterprise.png
- https://storage.googleapis.com/sourcegraph-assets/docs/images/cody/jb_beam.svg
- https://storage.googleapis.com/sourcegraph-assets/docs/images/cody/vscode.svg

**Review by camdencheek — APPROVED** [review]
Changes look great! Approved to unblock, pending removal of the images from the repo

**Comment by MaedahBatool** [comment]
> Changes look great! Approved to unblock, pending removal of the images from the repo

Thank you. Removed the local image files. 👍

**Review by jdorfman — APPROVED** [review]

**Comment by MaedahBatool** [comment]
Closing this one: https://github.com/sourcegraph/sourcegraph/pull/55407

**Comment by unknwon** [comment]
> I've uploaded the images to our `sourcegraph-assets` cloud storage bucket (I can show you how to do that if you'd like), and they can be found at these URLS:

I bookmarked [this link](https://handbook.sourcegraph.com/handbook/editing/handbook-images-video/) for my own use 😄

**Pull request closed without merging**
