### PR TITLE
[UX] Distinguish between login and account connection attempts

### PR DESCRIPTION
**Pull request by pjlast**
Closes https://github.com/sourcegraph/cody/issues/1266

This PR introduces a new query parameter to the `/.auth/.../login/...` URL paths: `&connect=true` . If this URL parameter is present, the handler should interpret this request as an account connection request, and connect the external account to the existing Sourcegraph user session.

However, if this parameter is not present, and there is an active Sourcegraph session, the user should be signed out and signed back in using the new user session.

Loom: https://www.loom.com/share/681748358f1842b6b67f8b76e87151c5

## Test plan

CI still passes and manual testing.

### CODE REVIEW

**Comment by toolmantim** [comment]
I'm not quite sure I fully understand this enough to review sorry! Would @chenkc805 and @dominiccooney be more suitable?

**Review by vdavid — APPROVED** [review]
The code looks good to me, and I still agree with the functinality. Thanks for this, and sorry for the slow review!

**Comment by dominiccooney** [comment]
@pjlast thanks for working on this!

Do the IDEs need to direct people to a different login URL now? Can we still direct them to a specific provider (GitHub/GitLab/Google) in the VScode UI (even if via a redirect on sourcegraph.com)?

Was it possible to manually test this with the VScode sign in flow? It is hard to test because the SSO providers require the hostname to be sourcegraph.com, so wondering about that.

What happens if the "signing in" account is already associated with a different dotcom account? Or if the dotcom account already has an account associated with a given provider eg GitHub?

**Comment by pjlast** [comment]
@dominiccooney no need for a different URL, VS Code can stay exactly the same :)

I tested by copying the VS Code URL and just modifying the params so that it points to my local Sourcegraph and provider.

> What happens if the "signing in" account is already associated with a different dotcom account?

The user will be signed into that dotcom account

> Or if the dotcom account already has an account associated with a given provider eg GitHub?

The new provider (lets say Google) will be associated with that Dotcom account as well (if there was a verified email match for example)

**Pull request merged**
