### PR TITLE
Refresh: Update secondary button icon color

### PR DESCRIPTION
**Pull request by umpox**
Based on Figma discussion: https://www.figma.com/file/J8MduuIBmHAdMFsohckpsi?node-id=156%3A45&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#81794976

### Before
image

### After
image

### CODE REVIEW

**Review by pdubroy — APPROVED** [review]
Code looks good to me. @rrhyne can vouch for the visual change.

**Comment by umpox** [comment]
@rrhyne Only remaining question: should we also use `icon-color` in the disabled state? Currently it uses `text-muted` to match the disabled text which matches the other buttons

**Review by pdubroy — COMMENTED** [review]
@umpox a separate issue I noticed is inconsistent padding:

CleanShot 2021-05-20 at 09 47 15

Should I open a separate ticket for that?

**Comment by umpox** [comment]
@pdubroy Not sure how feasible that will be to do on a global level, the padding is consistent in the code
image

It's more of a problem with the viewbox of the icons we are using
image

**Comment by rrhyne** [comment]
Tom is correct, this is due to the viewport spacing and icon size. 

Most icons in our library (not all) are 1 to 2 pixels of left space between the left viewport edge and where the icon starts. I tested applying -2px left margin to the svg in the button and it corrects this problem in most cases.

We'll see an issue in our own icons (like code monitoring) that do not respect this size, but overall it would be a good correction for the issue.

Tom can you apply this margin?

**Review by limitedmage — COMMENTED** [review]
The disabled style looks way too similar to the non-disabled styles, especially for the outline button. Will this be addressed separately?

**Comment by rrhyne** [comment]
That will be a separate ticket.

**Comment by umpox** [comment]
@rrhyne I don't think that should be the responsibility of our buttons, rather we should adjust the viewbox of specific icons to fix these kind of issues in areas where they are particularly problematic. Some icons are quite a bit more than 2px, like we commonly use the `PlusIcon`
image  and some icons have no whitespace at all.

Looking into if there's any more creative solutions to managing this problem, but merging this PR now!

**Comment by rrhyne** [comment]
Thanks for merging the PR. 

The objective of the negative margin on the left is to reduce the 1 to 2 px of space between viewbox and left button edge. This is fairly consistent among icons and would generally solve the issues Patrick pointed out. 

Review [this simple test](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=3225%3A152) to see what I mean. The blue line is the edge of all icon's viewport, the red line is a guide set 2px into the icon's left edge. Note that almost every icon adheres to that amount of 'padding', thought the plus icon is 1px smaller and the wrench and others are .5 to 1px larger. 

This leads me to think the best solution overall is something like:  button > .icon {margin-left:-2px;}
image

**Pull request merged**
