### PR TITLE
gRPC: migrate repoupdater

### PR DESCRIPTION
**Pull request by camdencheek**
This PR adds a gRPC implementation of the repoupdater API. There were two new endpoints added in https://github.com/sourcegraph/sourcegraph/pull/47932 and https://github.com/sourcegraph/sourcegraph/pull/48096 that are not covered, but I will hit those in a followup PR to keep this from getting more stale. 

Contributes to https://github.com/sourcegraph/sourcegraph/issues/46526

## Test plan

Existing extensive tests in the GraphQL layer.

### CODE REVIEW

**Comment by gl-srgr** [comment]
@camdencheek there are some repoupdater client and server changes for setup experience effort; if I can help with migration of the new calls then let me know

https://github.com/sourcegraph/sourcegraph/pull/47932
https://github.com/sourcegraph/sourcegraph/pull/48096

**Comment by camdencheek** [comment]
@gl-srgr thanks for letting me know! I'll take a look and update this PR. Moving it to draft in the meantime.

**Comment by camdencheek** [comment]
The changes appear to be adding two new endpoints that are not covered by this PR, so I'll just plan on converting those in a followup PR.

**Comment by camdencheek** [comment]
> Have you thought about disabling the grpc feature flag (or hard-coding it to false in the client) until that future PR with the new methods is merged?

It shouldn't be a problem to have a mix of grpc/non-grpc, right? We're doing that for gitserver right now

**Comment by ggilmore** [comment]
> > Have you thought about disabling the grpc feature flag (or hard-coding it to false in the client) until that future PR with the new methods is merged?
> 
> It shouldn't be a problem to have a mix of grpc/non-grpc, right? We're doing that for gitserver right now

Ah, my bad -  I see we'd just default to the REST implementations for the ones that haven't been migrated to gRPC yet (I thought we'd fail with a NotImplemented error)

**Pull request merged**
