### PR TITLE
App: use unwrap_or_else() with shell::open()

### PR DESCRIPTION
**Pull request by ar-jan**
## Test plan

Change verified by Sourcegraphers

### CODE REVIEW

**Comment by ar-jan** [comment]
I've now signed the CLA.

Can a change as small as this be tested, and if so how?

**Review by slimsag — APPROVED** [review]

**Comment by slimsag** [comment]
@chwarwick you cool with this change? I figure without it the app just crashes if URL opening fails, so this seems like a clear win. I'll merge and do another release tomorrow if so

**Comment by burmudar** [comment]
@clabot check

**Comment by burmudar** [comment]
@cla-bot check

**Review by marekweb — APPROVED** [review]

**Comment by chwarwick** [comment]
> @chwarwick you cool with this change? I figure without it the app just crashes if URL opening fails, so this seems like a clear win. I'll merge and do another release tomorrow if so

I see no problems with it

**Review by chwarwick — APPROVED** [review]
I did look briefly at this issue and thought the error could possibly be related to the regexp in the conf file that guards shell access.

**Pull request merged**
