### PR TITLE
[a11y] fuzzy finder: remove tab keyboard shortcut

### LINKED ISSUE #44124: Fuzzy finder "Show more" button and search link are not accessible due to tab key override
The fuzzy finder overrides the <kbd>tab</kbd> key to switch between symbol types and has some controls that don't have keyboard shortcuts, like the "Show more" button and the search link at the bottom.

An easy fix would be to remove the <kbd>tab</kbd> override, since all the symbol types now have independent keyboard shortcuts.

### PR DESCRIPTION
**Pull request by limitedmage**
Closes #44124

## Test plan

Verify tab key now works as normal in the fuzzy finder modal (command+k) and all other keyboard shortcuts in the modal still work (eg command+i to search repos)

## App preview:

- [Web](https://sg-web-jp-fuzzyfindertab.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.12 kb) | -0.00% (-0.12 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/jp/fuzzyfindertab/compare-report.html;tab=live_object) for a full comparison between the commits 82c45d1 and 167924f or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by olafurpg — APPROVED** [review]
LGTM 👍🏻 Two followup questions that might be worth addressing separately:

- Is it OK that `Tab` doesn't focus on the result list? It cycles between the input, scope selector, and the search query
- I need to press `Shift-Tab` to focus on the exit button to close the modal. I'm not able to reach it with `Tab` alone. Is this normal or expected?
- In the Repos tab, it focuses on the code host icon (github.com). Pressing `Enter` has no effect when the code host icon is focused. This behavior is inconsistent with the Files/Symbols tabs where it's not possible to focus on the icons.

**Comment by limitedmage** [comment]
@olafurpg Thanks for your feedback, I've made the following changes:

- Tabs and close button are now focusable with both tab and shift+tab. You can use the arrow keys to move between tabs when focused.
- The close button is before the tabs in DOM order so tabs are focused first with shift+tab
- Real tab panels are now used, so the tabs are correctly associated with the content
- The result item can now be focused with the tab key

> In the Repos tab, it focuses on the code host icon (github.com). Pressing Enter has no effect when the code host icon is focused. This behavior is inconsistent with the Files/Symbols tabs where it's not possible to focus on the icons.

I have no idea why the icons next to repos are focusable but the other icons aren't. @lrhacker is this related to the way tooltips work?

**Comment by lrhacker** [comment]
@limitedmage If that is the only difference between the icons (with a tooltip vs without), then yes, I think that is likely the cause. I recall having a conversation a bit ago around the general concept of using tooltips on non-interactive components (like icons or plain text) at all, but there was no specific resolution to the issue that we decided at the time.

**Review by olafurpg — COMMENTED** [review]
Nice job improving the `Tab` behavior! Thank you @limitedmage 🙏🏻 

Only one thing stood out for me, what element is being focused after pressing `Tab` twice from the input?

CleanShot 2022-11-18 at 09 00 13@2x

**Comment by limitedmage** [comment]
> Only one thing stood out for me, what element is being focused after pressing `Tab` twice from the input?

It's focusing the tabpanel. Due to https://github.com/sourcegraph/sourcegraph/issues/35159 the focus outline is not completely visible though.

**Pull request merged**
