### PR TITLE
dev/gqltest: enable streaming integration tests

### PR DESCRIPTION
**Pull request by keegancsmith**
This runs all search tests against both the GraphQL API as well as the streaming API. Some tests do not work yet against streaming, so they are individually skipped. Some other tests had subtle bugs in them that I fixed.

I would like to land this in so we get integration testing coverage going forward for streaming.

### CODE REVIEW

**Comment by keegancsmith** [comment]
whoops meant to mark this as a draft, do not approve just yet :)

**Comment by unknwon** [comment]
CleanShot 2021-03-03 at 22 27 23@2x

You can still convert to draft if you want.

**Review by rvantonder — APPROVED** [review]
So `stable` isn't really as important in these tests. Before we had this integration testing infra, I used `stable` to get a deterministic result because I used the entire result value as the snapshot, not just count or something like that. When we added this new infra, it got carried over without change (because it wasn't really doing any harm). 

We can probably wholesale remove `stable` in these tests.  Doesn't have to be this PR. If we do remove `stable` and it causes test failures, that's curious.

I do think it's nice to not just test against `count` oracles but we've been mostly testing against `count` for a while already so it probably doesn't make a difference.

Looks good mostly, still some failures but pre-approving to get this off the review queue :-)

**Comment by keegancsmith** [comment]
> We can probably wholesale remove `stable` in these tests. Doesn't have to be this PR. If we do remove `stable` and it causes test failures, that's curious.

Cool. I removed them wholesale but added one or two back. The fun thing about it is it goes via the pagination APIs internally so we get to test that part of our code for free. So I'll keep them.
 
> I do think it's nice to not just test against `count` oracles but we've been mostly testing against `count` for a while already so it probably doesn't make a difference.

I agree, I was quite surprised at the strange things I found while doing this. For now keeping the existing behaviour makes it easy.

> Looks good mostly, still some failures but pre-approving to get this off the review queue :-)

I think these failures are due to stable being removed? It is surprising though. I couldn't reproduce locally, but I'm gonna try remove my local external services and try again.

**Comment by rvantonder** [comment]
> The fun thing about it is it goes via the pagination APIs internally so we get to test that part of our code for free.

Stable/pagination is just an abstraction over single-shot search queries, which is why I felt comfortable using it for integration tests. You could, in theory, remove pagination and write a wrapper around our search code that just makes sure to search the first repo on the instance for these tests. Just saying this isn't really about paging, just an interface for this hypothetical wrapper that already exists :-)

**Pull request merged**
