### PR TITLE
Fix browser extension e2e tests

### PR DESCRIPTION
**Pull request by tjkandala**
Fix e2e to unblock browser extension release.

From Slack:

> The "actual definition" is changing on us:
> - on [Tuesday](https://buildkite.com/sourcegraph/browser-extension-nightly-e2e/builds/379#4e1c5d07-68af-42ae-9662-5883378dbfd7/51-414).
> - on [Wednesday](https://buildkite.com/sourcegraph/sourcegraph/builds/94534#6a66f0e4-0107-4bf4-af52-9ed3041c8665/49-417), changed the "expected" to Tuesday's "actual", but the "actual" changed again.
> Is definition URL too unstable to rely on for tests? If so, should we just assert that we navigate somewhere (URL changed) after clicking "Go to Definition?

### CODE REVIEW

**Comment by efritz** [comment]
I'm not sure why it was inconsistent for a period, but it looks like the definition flipped _back_ to the original definition.

**Comment by tjkandala** [comment]
@efritz linking to the same file is promising, but both the position (L247:2 -> L233:2) and site (Sourcegraph -> GitHub) have changed:
 
- original (stable for ~1 year)  `https://sourcegraph.com/github.com/gorilla/mux@e73f183699f8ab7d54609771e1fa0ab7ffddc21b/-/blob/regexp.go#L247:24&tab=def`

- now: `https://github.com/gorilla/mux/blob/e73f183699f8ab7d54609771e1fa0ab7ffddc21b/regexp.go#L233:2`

**Comment by felixfbecker** [comment]
Could this be because an LSIF bundle wasn't uploaded for the latest commit at the time the tests ran? A simple solution could be to allow both to pass the test

**Comment by efritz** [comment]
@tjkandala 

One of those opens a panel and another goes directly there. I'm not sure why ctags is no longer giving multiple definition results.

**Comment by tjkandala** [comment]
@efritz @felixfbecker Thanks for clarifying. Since it seems like there are multiple valid responses, I've modified the tests to support multiple passing definition URLs

**Comment by efritz** [comment]
In general I feel it's dangerous to rely on data from our production instance which will be increasingly relying on auto-index heuristics as we rapidly scale.

**Comment by muratsu** [comment]
I'm just going to go ahead and merge this. If it fails one more time, I'll disable the failing tests until we have the bandwidth to work on a real fix (converting them to integration tests with stubs).

**Pull request merged**
