### PR TITLE
Add collapse visual state to the drill-down panel for the independent insight page

### PR DESCRIPTION
**Pull request by vovakulikov**
Closes https://github.com/sourcegraph/sourcegraph/issues/35044

This PR simply adds collapsed visual state for the drill down panel.

## Test plan
- Make sure that the dashboard page filter panel layout doesn't have any visual regression
- Make sure that the filters section on the insight independent page matches [the design](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270)

## App preview:

- [Web](https://sg-web-vk-add-collapse-expand-state-to.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-kdsvqwhycq.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by vovakulikov** [comment]
@unclejustin Thanks for catching layout problem, I fixed this and also tuned logic around suggestion appearance ([related Slack thread](https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1652908729222369)), please have a look

**Review by AlicjaSuska — COMMENTED** [review]
Thank you for implementing this @vovakulikov
- could we add the 'context' keyword to the pill in this view. Now that I look at it, it's a little odd that we have repo and -repo but not context. [Updated design](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1251%3A22337)
- the vertical divider between context and regex areas is missing ([design](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1251%3A22337))

Thank you!

**Comment by vovakulikov** [comment]
@AlicjaSuska thanks for your review
- I added a context prefix in the last commit for the search filter preview pill 
- About the separator, this isn't as easy as I was expecting. If it's not a vital thing can we hold on to adding this? we still need to rethink our layout (from a tech point of view) with @unclejustin since he is adding a new filter panel (series order) and we need to think about a separator there as well.

**Comment by vovakulikov** [comment]
@unclejustin can you please take a look at this one again

**Review by unclejustin — APPROVED** [review]

**Pull request merged**
