### PR TITLE
web: add time-since-navigation and time-since-app-mount to spans

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context

This PR adds `time.since_navigation` and `time.since_app_mount` to every client span. We can leverage these attributes to create valuable dashboards in Honeycomb later.

Closes https://github.com/sourcegraph/sourcegraph/issues/44008

## Test plan

1. `ENABLE_OPEN_TELEMETRY=true sg start web-standalone`
2. Open the browser console and ensure that debug-level output is enabled.
3. Reload any web application page.
4. See new attributes added to spans.

Screenshot 2022-11-07 at 17 06 32

## App preview:

- [Web](https://sg-web-vb-time-since-shared-span-start.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.07% (+1.99 kb) | 0.01% (+2.00 kb) | 0.00% (+0.01 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vb/time-since-shared-span-start/compare-report.html;tab=live_object) for a full comparison between the commits d8ef73b and 5773b39 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by philipp-spiess — APPROVED** [review]
LGTM but I’m curious why we have to do this on the client--Couldn't the future dashboard do that on demand as well?

**Review by vovakulikov — APPROVED** [review]

**Comment by vovakulikov** [comment]
@philipp-spiess Just I guess, I suspect that, in this case, we have to store too much information instead of one specific metric. Like `ClientAttributes.TimeSinceAppMount` requires `startTimeMs` and `appMountSpan.startTime`. But kind of agree that as we get more and more metrics we should track low level data and calculate them on the fly in the dashboard not in a runtime.

**Comment by valerybugakov** [comment]
@philipp-spiess, @vovakulikov, I'm going to write documentation sometime next week to clarify how everything is connected and also list known limitations/issues. 

The problem with the computation of the `TimeSinceAppMount` metric on demand is that I didn't find a way to do it in Honeycomb. It's possible to create [computed columns in Honeycomb](https://docs.honeycomb.io/working-with-your-data/use-advanced-operators/derived-columns/) based on existing values, but it's unclear how we can join multiple spans to do the required math. E.g., here we need to find an ancestor `PageView` span and do the following: `CurrentSpan.startTime - PageView.startTime`. I [asked about it in the #wg-observability channel](https://sourcegraph.slack.com/archives/C033PDEV740/p1664972620718599).

Let me know if you have ideas on how to accomplish this in Honeycomb!

**Comment by philipp-spiess** [comment]
Thanks for the explaination both of you! I agree that in this case it makes sense to go ahead with this.

> Let me know if you have ideas on how to accomplish this in Honeycomb!

I have no idea about Honeycomb unfortunately 😅

**Pull request merged**
