### PR TITLE
web: merge the `search` package into `shared`

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context

Eliminates `search` & `shared` packages' circular dependency. See [the Client packages cyclic dependencies document](https://docs.google.com/document/d/1AbRH8k7CqQzq2MIFupyL7FOMq-SiUIWkYxZE8fyRqBg/edit) for more context.

## Test plan

CI

## App preview:

- [Web](https://sg-web-vb-remove-search-package.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.19% (+5.25 kb) 🔺 | 0.09% (+12.65 kb) 🔺 | 0.06% (+7.40 kb) | -0.14% (-1) 🔽 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vb/remove-search-package/compare-report.html;tab=live_object) for a full comparison between the commits 3d4ad91 and a0facbe or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by vovakulikov — APPROVED** [review]
Code LGTM, but I'm a little bit worried that we increased the initial chunk size with this change. At the first glance, it seems that shouldn't happen because of the tree shaking but maybe it's broken at the moment.

**Comment by valerybugakov** [comment]
@vovakulikov, thanks for the review! I'll double-check the bundle size report locally.

**Comment by valerybugakov** [comment]
Updated import paths to remove integration tests mocks from the bundle: 
Screenshot 2022-12-26 at 10 53 26

**Pull request merged**
