### PR TITLE
Allow signed in users to see Cody UI

### PR DESCRIPTION
**Pull request by taylorsperry**
📣 *Do not merge until we have coordinated with marketing to announce publicly [thread](https://sourcegraph.slack.com/archives/C01KPE23H4M/p1682029152895819)* 

This PR updates the `cody-experimental` feature flag to allow all signed in users to see Cody UI in sourcegraph.com by default. It follows https://github.com/sourcegraph/sourcegraph/pull/50925#event-9067575559, which introduced rate limiting to prevent usage from becoming too expensive/vulnerable to abuse. 

This is a change made by Cody! I asked Cody how to do it in the chat UI, and within my editor I used the "Fixup" option to refactor it. Was Cody right here? 

Screenshot 2023-04-21 at 11 02 34 AM

I also asked Cody to generate a unit test for this change, which it did, but I'm not sure where it should go or if it's necessary. The tests we have in `feature_flag_test.go` seem to be generic tests, and I don't know whether or not it would be appropriate to add one that's specific to the `IsCodyEnabled` function. 

## Test plan

See question above, re: testing.

### CODE REVIEW

**Comment by taylorsperry** [comment]
I see that there are some percy/buildkite checks failing. I tried running `sg lint --fix go` and it's stuck after waiting 5 mins. Any ideas? 
Screenshot 2023-04-21 at 11 14 44 AM

**Comment by valerybugakov** [comment]
@taylorsperry, you can review Percy changes and approve them yourself if they look good based on PR changes

**Comment by philipp-spiess** [comment]
Awesome work!!

I’m not the best to review the backend side since I don't know how we use the feature flag there, but for the frontend we currently directly use the `useFeatureFlag` API. This means that the feature flag will stay false even for logged in users.

[Here](https://sourcegraph.sourcegraph.com/search?q=context:global+repo:sourcegraph/sourcegraph+path:client/web+cody-experimental+lang:TypeScript+&patternType=standard&sm=1&groupBy=repo) is a list of all the places that currently query the feature flag. I think what we want here is to manually add a check for wether the app is dotcom and there's a current user (probably at this point it makes sense to extract the logic into a `useIsCodyEnabled()` hook as well).

> I also asked Cody to generate a unit test for this change, which it did, but I'm not sure where it should go or if it's necessary. The tests we have in feature_flag_test.go seem to be generic tests, and I don't know whether or not it would be appropriate to add one that's specific to the IsCodyEnabled function.

I'll let someone more familiar with go answer this but if you want to test the frontend, you can build the web app in dotcom mode.

You'd start the app like this:

```
sg start dotcom
```

And then reproduce the different scenarios there (logged out vs logged in). Feature flag on vs off, etc.

**Comment by eseliger** [comment]
Superseded by https://github.com/sourcegraph/sourcegraph/pull/51249, closing.

**Pull request closed without merging**
