### PR TITLE
Fix #4508: firefox should ask for limited domain permissions

### LINKED ISSUE #4508: Firefox extension should ask for limited URL access
The Firefox chrome extension currently asks for access to all websites. It should be updated to ask for the same limited set of sites that the Chrome extension asks for.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4d84cd2b62888f584c514e67e46119dff43a3049/-/blob/browser/scripts/tasks.ts#L84:31

We originally wanted to use limited access but because of https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1382953 it made the on-boarding flow really terrible for users. This issue is fixed so we can revisit.

### PR DESCRIPTION
**Pull request by exoego**
Closes #4508

Test plan: Honestly, I have no idea how to test installation situation.

### CODE REVIEW

**Comment by exoego** [comment]
Any chance to get review?

**Comment by christinaforney** [comment]
@lguychard or @felixfbecker - from this and the linked ticket it sounds like we might be able to make this improvement now that the original bug has been resolved? Could you make some suggestions for how to test this?

**Comment by felixfbecker** [comment]
@lguychard do you know if permission requests get triggered for dev builds?

**Comment by lguychard** [comment]
Thank you for contribution @exoego! Apologies for the waiting time on this.

@felixfbecker yes, permissions prompts are shown in dev mode.

After testing this fix, I've been able to get the permissions prompt to display by interacting with the browser action's context menu, or the "grant permissions" link from the popup.

However, AFAICT, the permissions prompt is triggered **only once**. After the user has interacted with it, it is never shown again, even for a different website. On further requests, the promise returned by `browser.permissions.request` never resolves, and no prompt is shown. This is an issue for us, because in most cases enterprise users would need to grant permissions for their Sourcegraph instance's URL *and* their code host URL.

I'm looking into whether there is already an upstream bug for this / this could be linked to testing in dev mode, but if this is confirmed to be a limitation on the Firefox side, it would be a blocker for us.

**Comment by lguychard** [comment]
Closing this PR because of https://github.com/sourcegraph/sourcegraph/pull/4760#issuecomment-526188376.

**Pull request closed without merging**
