### PR TITLE
schema: cleanup schema gen

### PR DESCRIPTION
**Pull request by keegancsmith**
See individual commits. The gen.go file was unwieldy.

### CODE REVIEW

**Comment by keegancsmith** [comment]
@sourcegraph/campaigns is there a reason you redeclare types in the schema.json files you added? EG `GitCommitDescription`.

Note: I created this PR before you landed your branch. Just merged in master and running into this issue. In my cleanup I run all schema.json files through `go-jsonschema-compiler`. But I see you didn't do that. I can update this branch to exclude the schema files you have added.

**Comment by mrnugget** [comment]
> @sourcegraph/campaigns is there a reason you redeclare types in the schema.json files you added? EG `GitCommitDescription`.

You mean, why have two types with that name in two specs? They're different: one is the expanded version (with a `diff`) and one is just the message.

**Comment by Jaxkr** [comment]
Hey, Jackson from DocForge here. It looks like our tool flagged something in this PR but unfortunately your install was misconfigured and linking you to localhost (so sorry about that!). It looks like you fixed the affected documentation here: https://github.com/sourcegraph/sourcegraph/pull/12400

Just popping in to let you know that the links inside GitHub checks should be fixed. If you still need to manually resolve any documents, you can do so at https://sourcegraph.app.docforge.dev/review-queue

Thanks for trying DocForge!

**Comment by keegancsmith** [comment]
> > @sourcegraph/campaigns is there a reason you redeclare types in the schema.json files you added? EG `GitCommitDescription`.
> 
> You mean, why have two types with that name in two specs? They're different: one is the expanded version (with a `diff`) and one is just the message.

Check out this branch and try run `go test ./schema` and you will understand. IE We now have `GitCommitDescription` declared twice, which means go-jsonschema-compiler generates a struct called `GitCommitDescription` twice == bad time.

Your suggestion of renaming it works. I'm happy to cook up new names for it, or you are welcome to do that and push to this branch. Play around until `go generate ./schema && go test ./schema` has exit code 0.

**Comment by keegancsmith** [comment]
@Jaxkr thanks for checking up. Always nice when a service owner does that :)

**Comment by mrnugget** [comment]
> Your suggestion of renaming it works. I'm happy to cook up new names for it, or you are welcome to do that and push to this branch. Play around until `go generate ./schema && go test ./schema` has exit code 0.

I think we can rename `GitCommitDescription` in `changeset_spec.schema.json` to `ExpandedGitCommitDescription`. What do you think @eseliger? 

@keegancsmith you can either do that or I'll do that later today and push to this branch.

**Pull request merged**
