### PR TITLE
Fix UserSettingsRepositoriesPage to show user repos when only added via public code (no code host connections)

### LINKED ISSUE #19161: No entrypoint for managing repos if the user hasn't added a code host
Now that we have the 'public repos' box, we want users to be able to add those repos without connecting a code host, however right now there's no way to access the manage repos page without adding a code host. we should also probably make sure the manage repos page understands the current state when loaded without a code host, as it will show options that don't make any sense at the moment, eg 'selected repos'. we should probably get rid of the entire top box.

this is a blocker for #19139

### LINKED ISSUE #19162: Public repos are not listed in UserSettingsRepositoryPage if the user doesn't also have repos added via a code host.
If a user has added code via the 'public code' textbox, but not added any code from their code host, they won't see any repositories in UserSettingsRepositoryPage. if they then add a single repo from their code host, all of their added repos appear. we should fix this to always list repos even if we only have ones from public code.

this blocks #19139

### PR DESCRIPTION
**Pull request by arussellsaw**
closes #19161 
closes #19162

I spotted this morning that if you added code via public repos without any code host connections, nothing would appear. this is because we were testing for the existence of code hosts to show the FilteredConnection element. It also meant that there was no entrypoint to add public code without a code host connection, i've fixed that as well with updated copy & different logic for showing the add/manage repos button.

There's some slightly janky state in here, as we need to present the filtered connection in order to populate the hasRepos state, and then hide it if there's nothing. If there's a better way for me to directly call queryRepositories without creating too many extra network requests please let me know, but i wasn't sure how i could do that.

### CODE REVIEW

**Comment by arussellsaw** [comment]
also adding @ryanslade for backend review, as i've fixed repos.TotalCount to include public repos

**Review by unknwon — APPROVED** [review]

**Comment by unknwon** [comment]
nit: add some tests to cover the `if` branches

**Comment by artemruts** [comment]
I'll test with the latest `main` and post here, bc I just merged some previously approved changes.

**Comment by artemruts** [comment]
ui

@arussellsaw I think if no code hosts are connected and we allow users to navigate to the "manage" section of the repos, they may (will) select the UI for affiliated repos and will see an error.

**Review by ryanslade — APPROVED** [review]
SQL LGTM :)

**Comment by arussellsaw** [comment]
@artemruts quinn updated the board yesterday, i'll add this in another PR
Screenshot 2021-03-17 at 07 38 11

**Comment by arussellsaw** [comment]
@artemruts i decided to implement it in this PR, rather than wait for you to wake up, approve this, add another feedback cycle, felt quicker 😅

**Review by artemruts — APPROVED** [review]

**Pull request merged**
