### PR TITLE
Add SRC_DISABLE_PROFILER feature flag for local dev with SOURCEGRAPHDOTCOM_MODE enabled

### PR DESCRIPTION
**Pull request by arussellsaw**
When running with `SOURCEGRAPHDOTCOM_MODE` we will try to set up the gcloud profiler, but this will fail locally unless you have some specific gcloud config, considering this is non-critical i've demoted to Printf. perhaps we want to do something else to make sure we catch failure to profile in prod though?

EDIT: used SRC_DISABLE_PROFILER instead

context: https://sourcegraph.slack.com/archives/C07KZF47K/p1611568786046600

### CODE REVIEW

**Review by attfarhan — APPROVED** [review]
Thanks!. LGTM but you should probably wait on Tomas or someone else on Cloud before merging 😄

**Comment by unknwon** [comment]
I think a normal printf won't raise any notice on production until we realize there is no profiler at the time we need it.

The alternative I recommend would be a env var flag like `SRC_DISABLE_PROFILER`.

**Comment by tsenart** [comment]
> The alternative I recommend would be a env var true/false flag like SRC_DISABLE_PROFILER.

+1

**Comment by arussellsaw** [comment]
👍  sounds good, updated!

**Review by ryanslade — APPROVED** [review]

**Pull request merged**
