### PR TITLE
monitoring: cadvisor observables review

### PR DESCRIPTION
**Pull request by bobheadxi**
Closes https://github.com/sourcegraph/sourcegraph/issues/17158

I did some flyby changes of sorts while checking. tl;dr: no `disk` category metrics from https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md#prometheus-container-metrics

* Remove container fs inodes: disk metrics are not supported in OCI it seems (https://github.com/google/cadvisor/issues/2785), and the metrics it reports in docker-compose feels rather dubious at times. Instead, I've made `ContainerIOUsage` a shared observable, and the services that had relevant uses for the inodes monitoring now have this instead.
* Docs changes and improvements, including a new cAdvisor page in the docsite
* Reworked container restart to something that I think works using cAdvisor metrics - [demo](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%221610515309000%22,%221610522759000%22,%22Prometheus%22,%7B%22expr%22:%22(count%20by(name)%20(container_last_seen%7Bname%3D~%5C%22frontend.*%5C%22%7D%5Cnunless%20(container_last_seen%7Bname%3D~%5C%22frontend.*%5C%22%7D%20offset%201m))%20-%201)%20%3E%200%22,%22requestId%22:%22Q-11c1cfee-f541-4c0e-b7e0-e1a14d3a7257-0A%22,%22instant%22:false,%22range%22:true%7D%5D&right=%5B%221610515309000%22,%221610522759000%22,%22Prometheus%22,%7B%22expr%22:%22group%20by(version,%20instance)%20(src_service_metadata%7Bjob%3D~%5C%22.*frontend%5C%22,instance%3D%5C%22sourcegraph-frontend-54c86475d6-76vfb%5C%22%7D%20unless%20(src_service_metadata%7Bjob%3D~%5C%22.*frontend%5C%22,instance%3D%5C%22sourcegraph-frontend-54c86475d6-76vfb%5C%22%7D%20offset%201m))%22,%22requestId%22:%22Q-609ae89d-64ff-459d-83b0-840c18bfdd4c-0A%22,%22instant%22:true,%22range%22:true%7D%5D). Left graph is new restart query, right graph is version "changes" - it seems that the same pod reporting a new version indicates a gap in the data indicating a restart. [At 7:17 UTC pod `sourcegraph-frontend-54c86475d6-76vfb` was reported OOMKilled](https://sourcegraph.slack.com/archives/C0NF93T1C/p1610522237438600), at 7:18 UTC the pod re-reports the same version (see right graph), and the new query reports a non-zero value at the same time (see left graph - note that it doesn't report non-zero for the initial pod startup at 5:27 UTC). I'm pretty optimistic this works, and it'll let us get rid of the somewhat gnarly recording rule used now (that doesn't work in k8s). The alert is just a warning anyway, so can adjust as needed. closes https://github.com/sourcegraph/sourcegraph/issues/9793
* Titles are now shared for consistency and ease of editing

### CODE REVIEW

**Comment by pecigonzalo** [comment]
I did not get a chance to review it yet but have you checked https://awesome-prometheus-alerts.grep.to/rules#docker-containers?

`time() - container_last_seen > 60`

**Comment by bobheadxi** [comment]
> I did not get a chance to fully review it yet but have you checked awesome-prometheus-alerts.grep.to/rules#docker-containers?
>
> `time() - container_last_seen > 60`

@pecigonzalo  [demo](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%221610515309000%22,%221610522759000%22,%22Prometheus%22,%7B%22expr%22:%22time()%20-%20container_last_seen%7Bname%3D~%5C%22frontend.*%5C%22%7D%20%3E%2060%22,%22requestId%22:%22Q-c6a7e6c2-0da2-4a85-a989-95b1b54ba295-0A%22,%22instant%22:false,%22range%22:true%7D%5D&right=%5B%221610515309000%22,%221610522759000%22,%22Prometheus%22,%7B%22expr%22:%22group%20by(version,%20instance)%20(src_service_metadata%7Bjob%3D~%5C%22.*frontend%5C%22,instance%3D%5C%22sourcegraph-frontend-54c86475d6-76vfb%5C%22%7D%20unless%20(src_service_metadata%7Bjob%3D~%5C%22.*frontend%5C%22,instance%3D%5C%22sourcegraph-frontend-54c86475d6-76vfb%5C%22%7D%20offset%201m))%22,%22requestId%22:%22Q-872567f5-1c79-4547-8f02-2c0ce7a95f54-0A%22,%22instant%22:true,%22range%22:true%7D%5D) - this seems to return some false positives :( neat website though!

**Comment by pecigonzalo** [comment]
@bobheadxi how do you know its a false positive? In #bots-production I can see the OOM.

**Comment by bobheadxi** [comment]
Oh hm, I was assuming the version change would catch all restarts so was aligning the two, but I think the query on this site might be more accurate

**Comment by bobheadxi** [comment]
Oh, the event at the left seems to be a false positive - I don't see an OOM event in #bots-production for `sourcegraph-frontend-54c86475d6-f6g5s` at 5:30 UTC, and I believe it's an initial deploy:

image

**Comment by pecigonzalo** [comment]
Checking https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_pod%22%20resource.labels.location%3D%22us-central1-f%22%20resource.labels.cluster_name%3D%22cloud%22%20frontend;timeRange=2021-01-13T05:46:51.764Z%2F2021-01-13T12:46:51.764441Z?project=sourcegraph-dev I can match many of the spikes to liveness probe failures. 

I would also consider `up` or `container_last_seen` metric to be more accurate than diff versioning as you can have downtime without version changes.

**Comment by bobheadxi** [comment]
I think you're right - switched in 7570ecbc18fcb5e8d3abfca0b0e4e1f835e65e30

> I would also consider up or container_last_seen metric to be more accurate than diff versioning as you can have downtime without version changes.

It would be without the gauge disappearing, but you're right regardless in that the presence of the gauge is not a reliable indicator

**Comment by pecigonzalo** [comment]
> Seems we'll be getting a lot of alerts :)

Yep. It might be good to add an `unless deploying` sort of check there. I cant recall how I did this in the past, but Ill check if I can find any references. There is something to be said here for not alerting on missing pods unless its happening over a period of time. As long as the deployment is healthy, if a pod dies every now and then, it might not be relevant. Something like `kube_pod_container_status_restarts_total` for crashlooping. eg. https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/apps_alerts.libsonnet and `5.1.17.` in the previous link.

On a side-note I really like the idea of alerts like the one in  `KubernetesStatefulsetUpdateNotRolledOut` on that linked website.

**Comment by bobheadxi** [comment]
>  if a pod dies every now and then, it might not be relevant.

Fits the description of a `warning` then!

**Comment by bobheadxi** [comment]
> On a side-note I really like the idea of alerts like the one in KubernetesStatefulsetUpdateNotRolledOut on that linked website.

https://github.com/sourcegraph/sourcegraph/issues/16309

**Comment by pecigonzalo** [comment]
Like 13975, but not just for .com down or up.

**Review by pecigonzalo — APPROVED** [review]

**Comment by daxmc99** [comment]
I wonder if adding https://github.com/kubernetes/kube-state-metrics would make sense to allow for determining when pods have a frequent number of restarts.

**Pull request merged**
