### PR TITLE
license: fix missing assignments of loggers

### PR DESCRIPTION
**Pull request by unknwon**
Fix regression introduced in https://github.com/sourcegraph/sourcegraph/pull/56142

Context: https://sourcegraph.slack.com/archives/CMBA8F926/p1692894504864389

## Test plan

CleanShot 2023-08-24 at 13 54 45@2x

### CODE REVIEW

**Review by rafax — APPROVED** [review]
Approving to unblock the fix - is there a way to catch similar issues automatically? It feels like we should be checking if all keys of a struct are being assigned?

**Comment by unknwon** [comment]
> Approving to unblock the fix - is there a way to catch similar issues automatically? It feels like we should be checking if all keys of a struct are being assigned?

The best way IMO to prevent this type issues... are to use constructors instead of assigning field values directly, which is very easy to miss assignments in all places.

**Comment by rafax** [comment]
> > Approving to unblock the fix - is there a way to catch similar issues automatically? It feels like we should be checking if all keys of a struct are being assigned?
> 
> The best way IMO to prevent this type issues... are to use constructors instead of assigning field values directly, which is very easy to miss assignments in all places.

Agreed, but it still feels like we could catch this with static analysis (but maybe I'm biased by other programming languages, and this is hard in go).

**Comment by rafax** [comment]
> > > Approving to unblock the fix - is there a way to catch similar issues automatically? It feels like we should be checking if all keys of a struct are being assigned?
> > 
> > 
> > The best way IMO to prevent this type issues... are to use constructors instead of assigning field values directly, which is very easy to miss assignments in all places.
> 
> Agreed, but it still feels like we could catch this with static analysis (but maybe I'm biased by other programming languages, and this is hard in go).

Guess this is what I'm looking for https://github.com/GaijinEntertainment/go-exhaustruct

**Pull request merged**
