### PR TITLE
search: introduce ExecutionResult to enforce telemetry collection

### PR DESCRIPTION
**Pull request by keegancsmith**
This just introduces the type without actually recording the telemetry. Additionally we introduce a new parameter to Plan to capture the subsystem. The goal is to start recording prometheus, honeycomb and logging across all search clients. Currently we only record this for GraphQL and streaming http requests.

This commit doesn't actually implement the telemetry sending. That will come in the next (much smaller) commit.

Additionally code monitors does not yet support telemetry since it directly uses the job interface. That will be followed up with.

Test Plan: go test

Part of https://github.com/sourcegraph/sourcegraph/issues/53766

### CODE REVIEW

**Comment by keegancsmith** [comment]
I also need to capture streaming.Stats, just pushed a commit for that.

I am thinking of designs to remove these downsides. We could automatically capture UserResultCount and Stats. Downside is we calculate Stats twice which can be bad due to memory use. Additionally UserResultCount will be different to what graphql actually does.

Another design is we remove stats aggregation into the client and users of the API don't need to aggregate that themselves anymore.

Another idea is to remove the logic in DetermineStatusForLogs which consults Stats. This might be a viable approach.

**Comment by camdencheek** [comment]
I guess I'm a little confused by the design and what exactly we're trying to achieve here. I would've expected we could just wrap it in another `SearchJob` 🤔

**Comment by keegancsmith** [comment]
thanks, that is probably the better direction. I need to learn how all this stuff fits together these days.

**Comment by stefanhengl** [comment]
@keegancsmith I see no update since your last comment. Should I review this?

**Pull request closed without merging**
