### PR TITLE
diff search: Don't duplicate hunk body in memory

### PR DESCRIPTION
**Pull request by eseliger**
This reads it line by line, instead of keeping a copy of all the lines in memory. Small improvement probably, but something I saw while digging through some code and might be giving us _something_ back.

Small comparison of bufio.Scanner vs bytes.Split mem consumption over a larger file like our pnpm lock file. 

```go
func BenchmarkMemorySplit(b *testing.B) {
	data, err := os.ReadFile("../../../pnpm-lock.yaml")
	if err != nil {
		b.Fatal(err)
	}
	for i := 0; i < b.N; i++ {
		for _, l := range bytes.Split(data, []byte("\n")) {
			if len(l) > 10000 {
				b.Fatal("long line")
			}
		}
	}
}

func BenchmarkMemoryScan(b *testing.B) {
	data, err := os.ReadFile("../../../pnpm-lock.yaml")
	if err != nil {
		b.Fatal(err)
	}
	for i := 0; i < b.N; i++ {
		sc := bufio.NewScanner(bytes.NewReader(data))
		for sc.Scan() {
			l := sc.Bytes()
			if len(l) > 10000 {
				b.Fatal("long line")
			}
		}
		if err := sc.Err(); err != nil {
			b.Fatal(err)
		}
	}
}

```

```
goos: darwin
goarch: arm64
pkg: github.com/sourcegraph/sourcegraph/internal/gitserver/search
BenchmarkMemorySplit-10             1854            567782 ns/op          688682 B/op          1 allocs/op
BenchmarkMemoryScan-10              2194            538442 ns/op            4610 B/op          2 allocs/op
PASS
ok      github.com/sourcegraph/sourcegraph/internal/gitserver/search    2.839s
```

## Test plan

Existing test suite.

### CODE REVIEW

**Review by efritz — APPROVED** [review]

**Review by camdencheek — APPROVED** [review]

**Comment by camdencheek** [comment]
Actually, why is this better? `bytes.Split()` does not copy. And it only allocates a single new slice (maybe with some extra for slice growth?) for all the split lines. A scanner will also allocate an internal buffer.

**Comment by eseliger** [comment]
wait, it does not?

**Comment by camdencheek** [comment]
Yeah, I [just double checked](https://go.dev/play/p/Op3V4ohun9Z). Mutating the original slice is visible in the split slices

**Comment by Strum355** [comment]
Id like everyone to know that for once it wasnt Claude that lied to me that bytes.Split doesnt copy :trollface:

**Comment by eseliger** [comment]
lol, the other way around it isn't, that's confusing :D 

https://go.dev/play/p/4JIY6KF0MCz

**Comment by camdencheek** [comment]
@eseliger, that example is overwriting the value of a slice inside a slice of slices. That means it's no longer pointing to the original value. If you do `parts[1][0] = 'f'`, you'd see the same thing

**Comment by eseliger** [comment]
🤦🤦 

alright, that benchmark confuses me

**Comment by camdencheek** [comment]
I _am_ still confused where the additional allocated bytes are coming from in your benchmark though

**Comment by camdencheek** [comment]
@eseliger: I can't reproduce your benchmark results...

```
goos: darwin
goarch: arm64
pkg: github.com/camdencheek/scratch
BenchmarkMemorySplit-10             1986            590751 ns/op
BenchmarkMemoryScan-10              2252            533624 ns/op
PASS
ok      github.com/camdencheek/scratch  2.521s
```

**Comment by eseliger** [comment]
`-benchmem` gives you these additional fields

**Comment by camdencheek** [comment]
Okay, I think we solved it. Byte slices are 8 bytes each for a pointer, a length, and a capacity for 24 bytes total. `bytes.Split()` returns a slice of slice headers. It doesn't copy the underlying contents, but the headers themselves are significant for large files. For `pnpm-lock.yaml`, there are 28604 lines, which, when multiplied by 24 bytes per line accounts for 686496 of the 688651 allocated bytes. So it's not the slice contents that are causing allocated bytes here, it's the slice headers themselves.

**Comment by camdencheek** [comment]
Given that the scanner is both faster and allocates fewer bytes, consider my questions resolved 👍 merge at will!

**Pull request merged**
