### PR TITLE
tenant: set pprof label for tenant

### PR DESCRIPTION
**Pull request by keegancsmith**
In the future this will allow us to attribute stack traces collected by pprof to a tenant. This only sets it for the http middleware. I am unsure how to achieve the same thing for grpc, since that uses propogators.

Test Plan: captured a goroutine profile and saw some goroutines with a tenant label

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
>  I am unsure how to achieve the same thing for grpc, since that uses propogators.

Because we don't have an `onEnd` method then?

I think you don't want to use the propagator there, you want an interceptor instead like here: https://sourcegraph.sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fsourcegraph&branch=es%2F08-07-tenantlogtenant-lessqueriesintosqldatabase&file=internal%2Fgrpc%2Fcontextconv%2Fconversion.go&editor=VSCode&version=2.2.17&start_row=56&start_col=0&end_row=70&end_col=1

**Review by jtibshirani — APPROVED** [review]
Nice! In addition to gRPC, should we add this to internal HTTP middleware too?

**Comment by eseliger** [comment]
@sourcegraph/multi-tenant I added internal HTTP and gRPC support here as well, PTAL

**Review by keegancsmith — COMMENTED** [review]
LGTM

**Pull request merged**
