### PR TITLE
Remove all arguments from event logging calls in web.

### PR DESCRIPTION
**Pull request by efritz**
Remove all current arguments from event logging in web.

This is *actually* what @dan asked for this before merging https://github.com/sourcegraph/sourcegraph/pull/7988.

### CODE REVIEW

**Comment by felixfbecker** [comment]
This looks like a perfect thing to do with Comby :)

**Comment by dadlerj** [comment]
@felixfbecker https://sourcegraph.slack.com/archives/C89KCDK5J/p1579800269004100?thread_ts=1579742604.023800&cid=C89KCDK5J :)

**Comment by dadlerj** [comment]
@efritz just made some tweaks. Some of the params we probably do still want, so I added some back. Also took care of removing/updating the `eventLogger.logViewEvent` params (since they get logged to the same `event_logs` DB).

**Comment by efritz** [comment]
Yay, you fixed the build too!

**Comment by lguychard** [comment]
According to this Percy diff, this PR appears to cause the navbar activation checklist to not be displayed: https://percy.io/Sourcegraph/Sourcegraph/builds/3901686?utm_campaign=Sourcegraph&utm_content=Sourcegraph&utm_source=github_status_public

**Pull request merged**
