### PR TITLE
search: always limit commit and diff to less than 10,000 repos

### PR DESCRIPTION
**Pull request by keegancsmith**
We have been noticing spikes in search latency on Sourcegraph.com. Turns out the root cause is saved searches doing diff searches. [Ops Log](https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit#bookmark=id.7bmlvlgpkt06). The diff searches would be run over 200k repos, and would constantly fail and keep getting retried.

In https://github.com/sourcegraph/sourcegraph/issues/7215 (https://github.com/sourcegraph/sourcegraph/pull/7272) we removed any limit if `before:` or `after:` is specified. This was to ensure saved searches worked. However, we need some limit since diff search won't work over 200k repos. This only recently become a problem due to us increasing default repos from 10k to 200k. This PR introduces a limit of 10,000. This may affect customers. If so I can increase to a higher number.

Additionally this PR enforces these limits if we search commits at all. For example `type:diff type:path foo` will try search 200k repos with diff search. If you try this out it returns, but that is due to some weird timeout behaviour. We don't report diff didn't work. I think its likely better to just alert to the user and not search.

cc people who have investigated this @pecigonzalo @bobheadxi @daxmc99

### CODE REVIEW

**Comment by keegancsmith** [comment]
I'm going to merge this in now to see the impact on sourcegraph.com. We have plenty of time before branch cut to adjust how we do this / etc. Still want to hear your thoughts @slimsag.

**Comment by slimsag** [comment]
How does this affect someone who has saved searches already with >10k repos indexed? I guess they would silently stop working but I’m not sure

**Comment by keegancsmith** [comment]
It would silently stop working. However, did it even work before? IE what we are seeing in production is it silently not working due to timeouts / overloading sourcegraph.

**Comment by pecigonzalo** [comment]
Do you think it would be possible and a good idea to set the limit on a site-config or env var? We setup a default at X, but allow deployments to change it something else.

**Comment by keegancsmith** [comment]
> Do you think it would be possible and a good idea to set the limit on
> a site-config or env var? We setup a default at X, but allow
> deployments to change it something else.

Yes that sounds like a good compromise. I'll do that tomorrow.

**Comment by keegancsmith** [comment]
Configurable limit introduced in https://github.com/sourcegraph/sourcegraph/pull/13439

**Comment by sqs** [comment]
The changelog says:

> This may affect your saved searches.

I would like to be specific here. Is the below sentence accurate? (I'll figure out how to word it for the changelog, so don't focus on the wording, but rather the accuracy of the statement.)

> If you have saved searches that ran diff or commit queries over more than 10,000 repositories, and *somehow* they ran to completion (unlikely!), then those saved searches will no longer work.

**Comment by keegancsmith** [comment]
> I would like to be specific here. Is the below sentence accurate? (I'll figure out how to word it for the changelog, so don't focus on the wording, but rather the accuracy of the statement.)
>
>> If you have saved searches that ran diff or commit queries over more than 10,000 repositories, and *somehow* they ran to completion (unlikely!), then those saved searches will no longer work.

That sounds good. Thank you for picking this up and improving it.

**Pull request merged**
