### PR TITLE
all: use alpine-3.14

### PR DESCRIPTION
**Pull request by keegancsmith**
Note: I am adding a lot of reviewers here, mainly for awareness than actually reviewing the code. The actual code changes are boring, the PR description is more important.

We have a 3.14 image available, but when we introduced it we ran into problems using it. This updates all images to use the newer version of alpine.

``` shell
ruplacer --go \
  sourcegraph/alpine-3.12:142406_2022-04-14_8836ac3499f4@sha256:4681a48d1fb9a73fef1b540c08b3411f797351bbeda749f5dca21213a1e71526 \
  sourcegraph/alpine-3.14:142406_2022-04-14_8836ac3499f4@sha256:2a2d1cbaec78882661fe1aa5b0a4af0c23a37be2ea9ff8aadc2da5b80852c233
```

I also had to pin postgresql in the server image since we can't upgrade it otherwise customer upgrades fail (incompatible on disk data). Additionally we had to include `libstc++` and `libgcc` for tree sitter.

Risks: I am relying on our CI to catch problems with this upgrade. The main risks here are us not testing things which exercise non-go binaries that rely on shared libraries. What comes to mind is things like p4 and tree-sitter, I am unsure if they get properly exercised. However, I think now is a good time to land a change like this since we have a lot of time until branch cut.

Test Plan: main dry run on CI to test docker image building and integration testing.

### CODE REVIEW

**Comment by keegancsmith** [comment]
@chrismwendt I know you have been making some changes to how we build symbols. Any idea why bumping the alpine distro to 3.14 causes the build to fail?

**Comment by keegancsmith** [comment]
@chrismwendt the sanity check fails:

```
#16 [symbols 5/6] RUN env SANITY_CHECK=true /usr/local/bin/symbols
  | #16 sha256:60316c31d41b9902c408c105328267c167675ebb027438bb5f3d24129d6609fe
  | #16 0.544 Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/bin/symbols)
  | #16 0.544 Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/symbols)
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4copyEPcmm: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: __cxa_end_catch: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE10_M_disposeEv: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: __cxa_begin_catch: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: __cxa_rethrow: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE9_M_mutateEmmPKwm: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _Znwm: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZdlPvm: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZSt20__throw_length_errorPKc: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _Unwind_Resume: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: _ZSt19__throw_logic_errorPKc: symbol not found
  | #16 0.544 Error relocating /usr/local/bin/symbols: __gxx_personality_v0: symbol not found
  | #16 ERROR: executor failed running [/bin/sh -c env SANITY_CHECK=true /usr/local/bin/symbols]: exit code: 127
```

**Comment by chrismwendt** [comment]
I pushed a [fix](https://github.com/sourcegraph/sourcegraph/pull/34508/commits/9d8b6d7a94535e4c28fa1f171098c1b4f52dbb10) which adds `apk add ... libstc++ libgcc` for tree-sitter.

I'm guessing sourcegraph/alpine-3.12 already had those packages installed and 3.14 doesn't, but I'm not 100% sure 🤷

**Comment by keegancsmith** [comment]
@chrismwendt thanks, that resolved it. Now the issue is a legit one, the version of postgres changes thanks to the different alpine and our CI caught a legit issue :)

```
2022-05-03 07:51:32.411 UTC [27] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.6.
```

**Comment by keegancsmith** [comment]
The road was long, but CI is green.

**Comment by keegancsmith** [comment]
Note: I am adding a lot of reviewers here, mainly for awareness than actually reviewing the code. The actual code changes are boring, the PR description is more important.

**Review by dcomas — APPROVED** [review]
Thanks for updating this. No issues on our side.

**Pull request merged**
