### PR TITLE
cmd/server: use sourcegraph/alpine base image and sourcegraph user

### PR DESCRIPTION
**Pull request by ggilmore**
See: #2044 

When migrating from the latest insiders to this version, we get the following error: 

```
2019/02/26 19:46:34 enterprise edition
/etc/sourcegraph/ssh does not exist, so only repos that do not require SSH will be accessible.
$ mkdir -p /run/postgresql
✱ Setting up postgres failed:

$ mkdir -p /run/postgresql
mkdir: can't create directory '/run/postgresql': Permission denied

exit status 1
```

### CODE REVIEW

**Comment by slimsag** [comment]
Yeah, as I mentioned on Slack the issue here is that the files are owned by root before but after this change are being accessed by the `sourcegraph` user.

One option for an automatic migration path here would be to:

1. Still run the container as root in our 3.2 release.
2. As root, chown the files to sourcegraph UID:GID, `chown -R 100:101 /the/files`
3. Downgrade to the regular `sourcegraph` user, run the entrypoint as that.
4. In 3.3 or some other future sourcegraph version, finally remove root and instead just use the `sourcegraph` user.

Otherwise, this will require manual migration I think and we'll have to wait until the next major release I imagine.

**Comment by slimsag** [comment]
Maybe there is some user detection we could do inside the container where a user interested in running as non-root could do so with the manual migration, while others would go through the automatic migration above (requiring root)? Not positive

**Comment by ggilmore** [comment]
Actually, this approach won't work. All the [references to `su-exec`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+su-exec) will fail since you need `root` permissions in order use `su-exec`.

**Comment by slimsag** [comment]
Correct, we would also need to run postgres as a non-root user: https://stackoverflow.com/questions/40644400/create-postgresql-database-without-root-privilege

**Comment by keegancsmith** [comment]
The postgres container has a nice pattern for chmod + su-exec if you are root which we could copy. The su-exec's in our go code could be conditional on us being root.

**Comment by ggilmore** [comment]
@keegancsmith Are you referring to https://github.com/sourcegraph/infrastructure/blob/master/docker-images/postgres-11.1/rootfs/postgres.sh ?

**Comment by keegancsmith** [comment]
Yes, in particular https://github.com/sourcegraph/infrastructure/blob/master/docker-images/postgres-11.1/rootfs/postgres.sh#L48-L55

**Comment by slimsag** [comment]
This PR has been open for a very long time with no progress, closing. Reopen if desired.

**Pull request closed without merging**
