### PR TITLE
Release Sourcegraph v3.9.4

### PR DESCRIPTION
**Pull request by slimsag**

### CODE REVIEW

**Comment by ggilmore** [comment]
So this is just a Docs update?

**Comment by slimsag** [comment]
Yes?

**Comment by slimsag** [comment]
I am completing https://github.com/sourcegraph/sourcegraph/issues/6300 if that is what you are asking

**Comment by ggilmore** [comment]
OK, you have my approval (can’t mark it as approved on my phone for whatever reason)

**Comment by slimsag** [comment]
Ah for some reason I thought we had required approvals on, if I had known that wasn't the case I would've just merged without given there is nothing here to review

**Pull request merged**
