### PR TITLE
 executors: bump firecracker kernel to 5.10.135

### PR DESCRIPTION
**Pull request by Strum355**
Changes the kernel docker image used by ignite from the default weaveworks/ignite-kernel to sourcegraph/ignite-kernel:5.10.135-amd64. This addresses the Dirtypipe vulnerability fixed in 5.10.102

Works on https://github.com/sourcegraph/security-issues/issues/296.

## Test plan

Tested locally via direct ignite calls, and a `docker run --rm hello-world` within the VM.

### CODE REVIEW

**Comment by eseliger** [comment]
Is it purely the kernel upgrade that makes a change to the boot time here? 
Also, let's publish this under sourcegraph please so it seems more legit :)

**Comment by Strum355** [comment]
> Is it purely the kernel upgrade that makes a change to the boot time here?
Theres a number of different kernel settings Ive discovered after a bit of a dive in. Im gonna leave this PR _for now_ and do a deeper dive tomorrow, make sure Im using a solid config and that everything is fine

>  Also, let's publish this under sourcegraph please so it seems more legit :)
totally, not sure where to go with this, we've only a limited number of docker hub seats :thinking:

**Comment by Strum355** [comment]
@eseliger ive changed this PR to only bump to 5.10.135, built from the ignite repo

**Review by eseliger — APPROVED** [review]
Great!

**Pull request merged**
